--
-- Tables
-- This file declares all tables in the public schema.
--
-- Multi-tenancy: every tenant table carries `organization_id`, filled by default
-- from the current user (private.current_organization_id()) and enforced by RLS
-- (see 05_policies.sql). Foreign keys between tenant tables are composite
-- (organization_id, id) so a row can never reference a row of another clinic.
--

-- Extensions
create extension if not exists "citext" with schema "extensions";
-- net.http_post: note attachments cleanup (cleanup_note_attachments)
create extension if not exists "pg_net" with schema "extensions";

-- Private schema: helpers not exposed through the REST API
create schema if not exists "private";

-- Tenant helpers. Declared before the tables because they are used as column
-- defaults. SECURITY DEFINER so that they can read public.sales without
-- recursing into its RLS policies. A disabled user belongs to no organization.
create or replace function private.current_organization_id() returns bigint
    language plpgsql stable security definer
    set search_path to ''
    as $$
begin
  return (
    select s.organization_id
    from public.sales s
    where s.user_id = auth.uid() and not s.disabled
  );
end;
$$;

create or replace function private.current_user_role() returns text
    language plpgsql stable security definer
    set search_path to ''
    as $$
begin
  return (
    select s.role
    from public.sales s
    where s.user_id = auth.uid() and not s.disabled
  );
end;
$$;

create or replace function private.current_sales_id() returns bigint
    language plpgsql stable security definer
    set search_path to ''
    as $$
begin
  return (
    select s.id
    from public.sales s
    where s.user_id = auth.uid() and not s.disabled
  );
end;
$$;

--
-- Organizations and staff
--

create table public.organizations (
    id bigint generated by default as identity primary key,
    name text not null,
    created_at timestamp with time zone not null default now(),
    timezone text not null default 'Asia/Almaty',
    currency text not null default 'KZT',
    -- Billing (tariffs and payments come in a later stage)
    plan text not null default 'trial',
    trial_ends_at timestamp with time zone default (now() + interval '14 days'),
    constraint organizations_name_not_blank check (btrim(name) <> '')
);

-- Clinic settings editable by the owner and the head
create table public.organization_settings (
    organization_id bigint primary key,
    -- Which deals a manager (administrator / curator) sees
    manager_deal_visibility text not null default 'all',
    -- Moving a deal to another pipeline: to its first stage, or the user picks the stage
    pipeline_move_mode text not null default 'first_stage',
    constraint organization_settings_visibility_check
        check (manager_deal_visibility in ('all', 'own', 'own_and_unassigned')),
    constraint organization_settings_pipeline_move_check
        check (pipeline_move_mode in ('first_stage', 'choose_stage'))
);

create table public.sales (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    -- owner: everything incl. billing and staff; head: reports, settings, all deals; manager: day-to-day work
    role text not null default 'manager',
    -- Kept for the Atomic CRM UI: owners and heads are administrators
    administrator boolean generated always as (role in ('owner', 'head')) stored,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false,
    secondary_emails jsonb not null default '[]'::jsonb,
    constraint sales_role_check check (role in ('owner', 'head', 'manager')),
    constraint sales_secondary_emails_is_array check (jsonb_typeof(secondary_emails) = 'array')
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

-- One configuration row per organization (UI settings: title, logos, options)
create table public.configuration (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    config jsonb not null default '{}'::jsonb,
    constraint configuration_organization_id_key unique (organization_id)
);

--
-- Dictionaries (configured by each clinic)
--

create table public.pipelines (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    position integer not null default 0,
    is_default boolean not null default false,
    created_at timestamp with time zone not null default now(),
    constraint pipelines_name_not_blank check (btrim(name) <> '')
);

-- Stage kinds: open (in progress), won (success), lost (refusal).
-- Every pipeline keeps at least one won and one lost stage.
create table public.stages (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    pipeline_id bigint not null,
    name text not null,
    position integer not null default 0,
    color text not null default '#83A2DB',
    kind text not null default 'open',
    created_at timestamp with time zone not null default now(),
    constraint stages_kind_check check (kind in ('open', 'won', 'lost')),
    constraint stages_name_not_blank check (btrim(name) <> '')
);

-- Services / treatment directions (implantation, orthodontics...)
create table public.services (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    position integer not null default 0,
    is_archived boolean not null default false,
    constraint services_name_not_blank check (btrim(name) <> '')
);

-- Lead sources. System sources (with a code) are used by integrations and
-- cannot be deleted or re-coded; clinics add their own.
create table public.lead_sources (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    code text,
    is_system boolean not null default false,
    position integer not null default 0,
    is_archived boolean not null default false,
    constraint lead_sources_name_not_blank check (btrim(name) <> ''),
    constraint lead_sources_system_has_code check (not is_system or code is not null)
);

create table public.lost_reasons (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    position integer not null default 0,
    is_archived boolean not null default false,
    constraint lost_reasons_name_not_blank check (btrim(name) <> '')
);

create table public.tags (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    color text not null
);

--
-- Patients and deals
--

create table public.patients (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    first_name text,
    last_name text,
    middle_name text,
    -- [{ "number": "+77011234567", "type": "Mobile" }], numbers normalized by trigger
    phone_jsonb jsonb not null default '[]'::jsonb,
    -- Normalized numbers, maintained by trigger, for search and deduplication
    phones text[] not null default '{}'::text[],
    birth_date date,
    city text,
    whatsapp text,
    instagram text,
    telegram text,
    -- Source of the first request (filled from the first deal)
    source_id bigint,
    tags bigint[] not null default '{}'::bigint[],
    sales_id bigint,
    gender text,
    avatar jsonb,
    background text,
    status text,
    first_seen timestamp with time zone not null default now(),
    last_seen timestamp with time zone not null default now(),
    constraint patients_phone_jsonb_is_array check (jsonb_typeof(phone_jsonb) = 'array')
);

create table public.patient_notes (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    patient_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    patient_id bigint not null,
    -- Filled with the default pipeline and its first stage when omitted
    pipeline_id bigint not null,
    stage_id bigint not null,
    name text,
    source_id bigint,
    service_id bigint,
    -- Amounts in tenge: treatment plan and total of payments (maintained by trigger)
    plan_amount bigint not null default 0,
    paid_amount bigint not null default 0,
    sales_id bigint,
    lost_reason_id bigint,
    lost_comment text,
    appointment_at timestamp with time zone,
    visit_at timestamp with time zone,
    tags bigint[] not null default '{}'::bigint[],
    description text,
    index integer not null default 0,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    stage_changed_at timestamp with time zone not null default now(),
    closed_at timestamp with time zone,
    first_response_at timestamp with time zone,
    archived_at timestamp with time zone,
    constraint deals_plan_amount_positive check (plan_amount >= 0)
);

create table public.deal_notes (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.deal_payments (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    deal_id bigint not null,
    amount bigint not null,
    paid_at date not null default current_date,
    comment text,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    constraint deal_payments_amount_positive check (amount > 0)
);

-- Deal log: creation, stage changes and edits (who, when, what)
create table public.deal_events (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    deal_id bigint not null,
    type text not null,
    from_stage_id bigint,
    to_stage_id bigint,
    changes jsonb not null default '{}'::jsonb,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    constraint deal_events_type_check check (type in ('created', 'stage_changed', 'updated'))
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    deal_id bigint not null,
    type text not null default 'call',
    text text,
    due_date timestamp with time zone not null,
    done_date timestamp with time zone,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    constraint tasks_type_check check (type in ('call', 'message', 'reminder', 'other'))
);

-- Calls: logged by hand in the MVP, the structure is ready for telephony
create table public.calls (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    patient_id bigint not null,
    deal_id bigint,
    direction text not null,
    duration_seconds integer not null default 0,
    comment text,
    called_at timestamp with time zone not null default now(),
    sales_id bigint,
    external_id text,
    recording_url text,
    created_at timestamp with time zone not null default now(),
    constraint calls_direction_check check (direction in ('in', 'out')),
    constraint calls_duration_positive check (duration_seconds >= 0)
);

--
-- Tenant keys: (organization_id, id) is unique on every tenant table so that
-- composite foreign keys can pin references to the same organization.
--

alter table public.sales add constraint sales_organization_id_id_key unique (organization_id, id);
alter table public.pipelines add constraint pipelines_organization_id_id_key unique (organization_id, id);
alter table public.stages add constraint stages_organization_id_id_key unique (organization_id, id);
alter table public.stages add constraint stages_pipeline_id_id_key unique (pipeline_id, id);
alter table public.services add constraint services_organization_id_id_key unique (organization_id, id);
alter table public.lead_sources add constraint lead_sources_organization_id_id_key unique (organization_id, id);
alter table public.lost_reasons add constraint lost_reasons_organization_id_id_key unique (organization_id, id);
alter table public.tags add constraint tags_organization_id_id_key unique (organization_id, id);
alter table public.patients add constraint patients_organization_id_id_key unique (organization_id, id);
alter table public.patient_notes add constraint patient_notes_organization_id_id_key unique (organization_id, id);
alter table public.deals add constraint deals_organization_id_id_key unique (organization_id, id);
alter table public.deal_notes add constraint deal_notes_organization_id_id_key unique (organization_id, id);
alter table public.deal_payments add constraint deal_payments_organization_id_id_key unique (organization_id, id);
alter table public.tasks add constraint tasks_organization_id_id_key unique (organization_id, id);
alter table public.calls add constraint calls_organization_id_id_key unique (organization_id, id);

--
-- Foreign keys
--

alter table public.organization_settings
    add constraint organization_settings_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.sales
    add constraint sales_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);
alter table public.configuration
    add constraint configuration_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;

alter table public.pipelines
    add constraint pipelines_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.stages
    add constraint stages_pipeline_id_fkey foreign key (organization_id, pipeline_id) references public.pipelines(organization_id, id) on delete cascade;
alter table public.services
    add constraint services_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.lead_sources
    add constraint lead_sources_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.lost_reasons
    add constraint lost_reasons_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.tags
    add constraint tags_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;

alter table public.patients
    add constraint patients_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.patients
    add constraint patients_source_id_fkey foreign key (organization_id, source_id) references public.lead_sources(organization_id, id);
alter table public.patients
    add constraint patients_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.patient_notes
    add constraint patient_notes_patient_id_fkey foreign key (organization_id, patient_id) references public.patients(organization_id, id) on delete cascade;
alter table public.patient_notes
    add constraint patient_notes_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.deals
    add constraint deals_patient_id_fkey foreign key (organization_id, patient_id) references public.patients(organization_id, id) on delete cascade;
alter table public.deals
    add constraint deals_pipeline_id_fkey foreign key (organization_id, pipeline_id) references public.pipelines(organization_id, id);
-- The stage must belong to the deal's pipeline
alter table public.deals
    add constraint deals_stage_id_fkey foreign key (pipeline_id, stage_id) references public.stages(pipeline_id, id);
alter table public.deals
    add constraint deals_source_id_fkey foreign key (organization_id, source_id) references public.lead_sources(organization_id, id);
alter table public.deals
    add constraint deals_service_id_fkey foreign key (organization_id, service_id) references public.services(organization_id, id);
alter table public.deals
    add constraint deals_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);
alter table public.deals
    add constraint deals_lost_reason_id_fkey foreign key (organization_id, lost_reason_id) references public.lost_reasons(organization_id, id);

alter table public.deal_notes
    add constraint deal_notes_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.deal_notes
    add constraint deal_notes_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.deal_payments
    add constraint deal_payments_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.deal_payments
    add constraint deal_payments_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.deal_events
    add constraint deal_events_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;

alter table public.tasks
    add constraint tasks_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.tasks
    add constraint tasks_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.calls
    add constraint calls_patient_id_fkey foreign key (organization_id, patient_id) references public.patients(organization_id, id) on delete cascade;
alter table public.calls
    add constraint calls_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.calls
    add constraint calls_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

--
-- Indexes
--

create index sales_organization_id_idx on public.sales using btree (organization_id);
create unique index pipelines_one_default_idx on public.pipelines using btree (organization_id) where is_default;
create index stages_pipeline_id_idx on public.stages using btree (pipeline_id, position);
create unique index lead_sources_code_idx on public.lead_sources using btree (organization_id, code) where code is not null;
create index patients_phones_idx on public.patients using gin (phones);
create index patients_last_seen_idx on public.patients using btree (organization_id, last_seen desc);
create index patient_notes_patient_id_idx on public.patient_notes using btree (organization_id, patient_id);
create index deals_board_idx on public.deals using btree (organization_id, pipeline_id, stage_id, index);
create index deals_patient_id_idx on public.deals using btree (organization_id, patient_id);
create index deals_sales_id_idx on public.deals using btree (organization_id, sales_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (organization_id, deal_id);
create index deal_payments_deal_id_idx on public.deal_payments using btree (organization_id, deal_id);
create index deal_events_deal_id_idx on public.deal_events using btree (organization_id, deal_id, created_at);
create index tasks_deal_id_idx on public.tasks using btree (organization_id, deal_id);
create index tasks_open_due_idx on public.tasks using btree (organization_id, due_date) where done_date is null;
create index calls_patient_id_idx on public.calls using btree (organization_id, patient_id);
create unique index calls_external_id_idx on public.calls using btree (organization_id, external_id) where external_id is not null;
