--
-- Tables
-- This file declares all tables in the public schema.
--
-- Multi-tenancy: every tenant table carries `organization_id`, filled by default
-- from the current user (private.current_organization_id()) and enforced by RLS
-- (see 05_policies.sql). Foreign keys between tenant tables are composite
-- (organization_id, id) so a row can never reference a row of another clinic.
--

-- Extensions
create extension if not exists "citext" with schema "extensions";
-- net.http_post: note attachments cleanup (cleanup_note_attachments)
create extension if not exists "pg_net" with schema "extensions";

-- Private schema: helpers not exposed through the REST API
create schema if not exists "private";

-- Tenant helpers. Declared before the tables because they are used as column
-- defaults. SECURITY DEFINER so that they can read public.sales without
-- recursing into its RLS policies. A disabled user belongs to no organization,
-- nor does an integrator whose access expired (sales.access_expires_at, stage 25).
create or replace function private.current_organization_id() returns bigint
    language plpgsql stable security definer
    set search_path to ''
    as $$
begin
  return (
    select s.organization_id
    from public.sales s
    where s.user_id = auth.uid() and not s.disabled
      and (s.access_expires_at is null or s.access_expires_at > now())
  );
end;
$$;

create or replace function private.current_user_role() returns text
    language plpgsql stable security definer
    set search_path to ''
    as $$
begin
  return (
    select s.role
    from public.sales s
    where s.user_id = auth.uid() and not s.disabled
      and (s.access_expires_at is null or s.access_expires_at > now())
  );
end;
$$;

create or replace function private.current_sales_id() returns bigint
    language plpgsql stable security definer
    set search_path to ''
    as $$
begin
  return (
    select s.id
    from public.sales s
    where s.user_id = auth.uid() and not s.disabled
      and (s.access_expires_at is null or s.access_expires_at > now())
  );
end;
$$;

--
-- Organizations and staff
--

create table public.organizations (
    id bigint generated by default as identity primary key,
    name text not null,
    created_at timestamp with time zone not null default now(),
    timezone text not null default 'Asia/Almaty',
    currency text not null default 'KZT',
    -- Billing (tariffs and payments come in a later stage)
    plan text not null default 'trial',
    trial_ends_at timestamp with time zone default (now() + interval '14 days'),
    constraint organizations_name_not_blank check (btrim(name) <> '')
);

-- Clinic settings editable by the owner and the head
create table public.organization_settings (
    organization_id bigint primary key,
    -- Which deals a manager (administrator / curator) sees
    manager_deal_visibility text not null default 'all',
    -- Moving a deal to another pipeline: to its first stage, or the user picks the stage
    pipeline_move_mode text not null default 'first_stage',
    -- New leads without a responsible (messengers, website forms): not
    -- distributed, round robin among the chosen employees, or given to the
    -- first chosen employee who answers
    lead_distribution text not null default 'off',
    lead_distribution_sales_ids bigint[] not null default '{}'::bigint[],
    last_distributed_sales_id bigint,
    constraint organization_settings_visibility_check
        check (manager_deal_visibility in ('all', 'own', 'own_and_unassigned')),
    constraint organization_settings_lead_distribution_check
        check (lead_distribution in ('off', 'round_robin', 'first_response')),
    constraint organization_settings_pipeline_move_check
        check (pipeline_move_mode in ('first_stage', 'choose_stage'))
);

create table public.sales (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    -- owner: everything incl. billing and staff; head: reports, settings, all deals; manager: day-to-day work;
    -- integrator: technical account of an agency, settings only (stage 25)
    role text not null default 'manager',
    -- Kept for the Atomic CRM UI: owners and heads are administrators
    administrator boolean generated always as (role in ('owner', 'head')) stored,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false,
    secondary_emails jsonb not null default '[]'::jsonb,
    constraint sales_role_check check (role in ('owner', 'head', 'manager', 'integrator')),
    constraint sales_secondary_emails_is_array check (jsonb_typeof(secondary_emails) = 'array')
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

-- One configuration row per organization (UI settings: title, logos, options)
create table public.configuration (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    config jsonb not null default '{}'::jsonb,
    constraint configuration_organization_id_key unique (organization_id)
);

--
-- Dictionaries (configured by each clinic)
--

create table public.pipelines (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    position integer not null default 0,
    is_default boolean not null default false,
    created_at timestamp with time zone not null default now(),
    constraint pipelines_name_not_blank check (btrim(name) <> '')
);

-- Stage kinds: open (in progress), won (success), lost (refusal).
-- Every pipeline keeps at least one won and one lost stage.
create table public.stages (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    pipeline_id bigint not null,
    name text not null,
    position integer not null default 0,
    color text not null default '#83A2DB',
    kind text not null default 'open',
    created_at timestamp with time zone not null default now(),
    constraint stages_kind_check check (kind in ('open', 'won', 'lost')),
    constraint stages_name_not_blank check (btrim(name) <> '')
);

-- Services / treatment directions (implantation, orthodontics...)
create table public.services (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    position integer not null default 0,
    is_archived boolean not null default false,
    constraint services_name_not_blank check (btrim(name) <> '')
);

-- Lead sources. System sources (with a code) are used by integrations and
-- cannot be deleted or re-coded; clinics add their own.
create table public.lead_sources (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    code text,
    is_system boolean not null default false,
    position integer not null default 0,
    is_archived boolean not null default false,
    constraint lead_sources_name_not_blank check (btrim(name) <> ''),
    constraint lead_sources_system_has_code check (not is_system or code is not null)
);

create table public.lost_reasons (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    position integer not null default 0,
    is_archived boolean not null default false,
    constraint lost_reasons_name_not_blank check (btrim(name) <> '')
);

create table public.tags (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    color text not null
);

--
-- Patients and deals
--

create table public.patients (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    first_name text,
    last_name text,
    middle_name text,
    -- [{ "number": "+77011234567", "type": "Mobile" }], numbers normalized by trigger
    phone_jsonb jsonb not null default '[]'::jsonb,
    -- Normalized numbers, maintained by trigger, for search and deduplication
    phones text[] not null default '{}'::text[],
    birth_date date,
    city text,
    whatsapp text,
    instagram text,
    telegram text,
    -- Source of the first request (filled from the first deal)
    source_id bigint,
    tags bigint[] not null default '{}'::bigint[],
    sales_id bigint,
    gender text,
    avatar jsonb,
    background text,
    status text,
    first_seen timestamp with time zone not null default now(),
    last_seen timestamp with time zone not null default now(),
    constraint patients_phone_jsonb_is_array check (jsonb_typeof(phone_jsonb) = 'array')
);

create table public.patient_notes (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    patient_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    patient_id bigint not null,
    -- Filled with the default pipeline and its first stage when omitted
    pipeline_id bigint not null,
    stage_id bigint not null,
    name text,
    source_id bigint,
    service_id bigint,
    -- Amounts in tenge: treatment plan and total of payments (maintained by trigger)
    plan_amount bigint not null default 0,
    paid_amount bigint not null default 0,
    sales_id bigint,
    lost_reason_id bigint,
    lost_comment text,
    appointment_at timestamp with time zone,
    visit_at timestamp with time zone,
    tags bigint[] not null default '{}'::bigint[],
    description text,
    index integer not null default 0,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    stage_changed_at timestamp with time zone not null default now(),
    closed_at timestamp with time zone,
    first_response_at timestamp with time zone,
    archived_at timestamp with time zone,
    constraint deals_plan_amount_positive check (plan_amount >= 0)
);

create table public.deal_notes (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.deal_payments (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    deal_id bigint not null,
    amount bigint not null,
    paid_at date not null default current_date,
    comment text,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    constraint deal_payments_amount_positive check (amount > 0)
);

-- Deal log: creation, stage changes and edits (who, when, what)
create table public.deal_events (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    deal_id bigint not null,
    type text not null,
    from_stage_id bigint,
    to_stage_id bigint,
    changes jsonb not null default '{}'::jsonb,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    constraint deal_events_type_check check (type in ('created', 'stage_changed', 'updated'))
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    deal_id bigint not null,
    type text not null default 'call',
    text text,
    due_date timestamp with time zone not null,
    done_date timestamp with time zone,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    constraint tasks_type_check check (type in ('call', 'message', 'meeting', 'reminder', 'other'))
);

-- Calls: logged by hand in the MVP, the structure is ready for telephony
create table public.calls (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    patient_id bigint not null,
    deal_id bigint,
    direction text not null,
    duration_seconds integer not null default 0,
    comment text,
    called_at timestamp with time zone not null default now(),
    sales_id bigint,
    external_id text,
    recording_url text,
    created_at timestamp with time zone not null default now(),
    constraint calls_direction_check check (direction in ('in', 'out')),
    constraint calls_duration_positive check (duration_seconds >= 0)
);

--
-- Messengers (Wazzup24): WhatsApp, Instagram, Telegram
--

-- Connection of the clinic to Wazzup24. The API key is a secret: no client
-- role can read this table, only the edge functions (service role).
create table public.messenger_integrations (
    organization_id bigint primary key,
    provider text not null default 'wazzup',
    api_key text,
    -- Part of the webhook URL given to Wazzup24: identifies the clinic
    webhook_token text not null default replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', ''),
    connected_at timestamp with time zone,
    last_error text,
    constraint messenger_integrations_provider_check check (provider in ('wazzup'))
);

-- Channels connected in Wazzup24 (a WhatsApp number, an Instagram account...)
create table public.messenger_channels (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    external_id text not null,
    transport text not null,
    -- Phone number or account name shown to the employees
    name text,
    state text,
    created_at timestamp with time zone not null default now(),
    constraint messenger_channels_transport_check check (transport in ('whatsapp', 'instagram', 'telegram', 'telegram_bot'))
);

-- Who a patient is in each messenger: WhatsApp chats are phone numbers,
-- Instagram and Telegram chats are identified by their external id.
-- telegram_bot: the clinic's own Telegram bot (Bot API, stage 8), next to
-- Telegram through Wazzup24
create table public.patient_chats (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    patient_id bigint not null,
    transport text not null,
    chat_id text not null,
    username text,
    created_at timestamp with time zone not null default now(),
    constraint patient_chats_transport_check check (transport in ('whatsapp', 'instagram', 'telegram', 'telegram_bot'))
);

-- Messages of a deal. Written by the edge functions only (received through
-- the webhook, or sent through Wazzup24); employees only mark them read.
create table public.messages (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    patient_id bigint not null,
    deal_id bigint not null,
    channel_id bigint,
    transport text not null,
    chat_id text not null,
    direction text not null,
    -- Author of an outgoing message; null for the patient or the system
    sales_id bigint,
    text text,
    content_uri text,
    content_type text not null default 'text',
    -- inbound, sent, delivered, read, error
    status text not null default 'sent',
    error text,
    external_id text,
    sent_at timestamp with time zone not null default now(),
    -- Incoming messages: when an employee opened the conversation
    read_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    constraint messages_direction_check check (direction in ('in', 'out')),
    constraint messages_transport_check check (transport in ('whatsapp', 'instagram', 'telegram', 'telegram_bot')),
    constraint messages_status_check check (status in ('inbound', 'sent', 'delivered', 'read', 'error'))
);

--
-- Automations: tasks created by rules, stage checklists
--

-- A task created on its own: when a deal is created, or enters a stage
create table public.task_rules (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    event text not null,
    stage_id bigint,
    type text not null default 'call',
    text text not null,
    due_in_minutes integer not null default 60,
    is_active boolean not null default true,
    position integer not null default 0,
    created_at timestamp with time zone not null default now(),
    constraint task_rules_event_check check (event in ('deal_created', 'stage_entered')),
    constraint task_rules_stage_check check ((event = 'stage_entered') = (stage_id is not null)),
    constraint task_rules_type_check check (type in ('call', 'message', 'meeting', 'reminder', 'other')),
    constraint task_rules_text_not_blank check (btrim(text) <> ''),
    constraint task_rules_due_positive check (due_in_minutes >= 0)
);

-- What must be done at a stage before the deal moves further
create table public.stage_checklist_items (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    stage_id bigint not null,
    text text not null,
    position integer not null default 0,
    constraint stage_checklist_items_text_not_blank check (btrim(text) <> '')
);

create table public.deal_checklist_checks (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    deal_id bigint not null,
    item_id bigint not null,
    sales_id bigint default private.current_sales_id(),
    checked_at timestamp with time zone not null default now()
);

--
-- Tenant keys: (organization_id, id) is unique on every tenant table so that
-- composite foreign keys can pin references to the same organization.
--

alter table public.sales add constraint sales_organization_id_id_key unique (organization_id, id);
alter table public.pipelines add constraint pipelines_organization_id_id_key unique (organization_id, id);
alter table public.stages add constraint stages_organization_id_id_key unique (organization_id, id);
alter table public.stages add constraint stages_pipeline_id_id_key unique (pipeline_id, id);
alter table public.services add constraint services_organization_id_id_key unique (organization_id, id);
alter table public.lead_sources add constraint lead_sources_organization_id_id_key unique (organization_id, id);
alter table public.lost_reasons add constraint lost_reasons_organization_id_id_key unique (organization_id, id);
alter table public.tags add constraint tags_organization_id_id_key unique (organization_id, id);
alter table public.patients add constraint patients_organization_id_id_key unique (organization_id, id);
alter table public.patient_notes add constraint patient_notes_organization_id_id_key unique (organization_id, id);
alter table public.deals add constraint deals_organization_id_id_key unique (organization_id, id);
alter table public.deal_notes add constraint deal_notes_organization_id_id_key unique (organization_id, id);
alter table public.deal_payments add constraint deal_payments_organization_id_id_key unique (organization_id, id);
alter table public.tasks add constraint tasks_organization_id_id_key unique (organization_id, id);
alter table public.calls add constraint calls_organization_id_id_key unique (organization_id, id);
alter table public.messenger_channels add constraint messenger_channels_organization_id_id_key unique (organization_id, id);
alter table public.patient_chats add constraint patient_chats_organization_id_id_key unique (organization_id, id);
alter table public.messages add constraint messages_organization_id_id_key unique (organization_id, id);
alter table public.task_rules add constraint task_rules_organization_id_id_key unique (organization_id, id);
alter table public.stage_checklist_items add constraint stage_checklist_items_organization_id_id_key unique (organization_id, id);
alter table public.deal_checklist_checks add constraint deal_checklist_checks_organization_id_id_key unique (organization_id, id);

--
-- Foreign keys
--

alter table public.organization_settings
    add constraint organization_settings_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.sales
    add constraint sales_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);
alter table public.configuration
    add constraint configuration_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;

alter table public.pipelines
    add constraint pipelines_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.stages
    add constraint stages_pipeline_id_fkey foreign key (organization_id, pipeline_id) references public.pipelines(organization_id, id) on delete cascade;
alter table public.services
    add constraint services_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.lead_sources
    add constraint lead_sources_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.lost_reasons
    add constraint lost_reasons_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.tags
    add constraint tags_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;

alter table public.patients
    add constraint patients_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.patients
    add constraint patients_source_id_fkey foreign key (organization_id, source_id) references public.lead_sources(organization_id, id);
alter table public.patients
    add constraint patients_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.patient_notes
    add constraint patient_notes_patient_id_fkey foreign key (organization_id, patient_id) references public.patients(organization_id, id) on delete cascade;
alter table public.patient_notes
    add constraint patient_notes_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.deals
    add constraint deals_patient_id_fkey foreign key (organization_id, patient_id) references public.patients(organization_id, id) on delete cascade;
alter table public.deals
    add constraint deals_pipeline_id_fkey foreign key (organization_id, pipeline_id) references public.pipelines(organization_id, id);
-- The stage must belong to the deal's pipeline
alter table public.deals
    add constraint deals_stage_id_fkey foreign key (pipeline_id, stage_id) references public.stages(pipeline_id, id);
alter table public.deals
    add constraint deals_source_id_fkey foreign key (organization_id, source_id) references public.lead_sources(organization_id, id);
alter table public.deals
    add constraint deals_service_id_fkey foreign key (organization_id, service_id) references public.services(organization_id, id);
alter table public.deals
    add constraint deals_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);
alter table public.deals
    add constraint deals_lost_reason_id_fkey foreign key (organization_id, lost_reason_id) references public.lost_reasons(organization_id, id);

alter table public.deal_notes
    add constraint deal_notes_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.deal_notes
    add constraint deal_notes_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.deal_payments
    add constraint deal_payments_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.deal_payments
    add constraint deal_payments_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.deal_events
    add constraint deal_events_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;

alter table public.tasks
    add constraint tasks_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.tasks
    add constraint tasks_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.calls
    add constraint calls_patient_id_fkey foreign key (organization_id, patient_id) references public.patients(organization_id, id) on delete cascade;
alter table public.calls
    add constraint calls_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.calls
    add constraint calls_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.messenger_integrations
    add constraint messenger_integrations_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.messenger_channels
    add constraint messenger_channels_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.patient_chats
    add constraint patient_chats_patient_id_fkey foreign key (organization_id, patient_id) references public.patients(organization_id, id) on delete cascade;
alter table public.messages
    add constraint messages_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.messages
    add constraint messages_patient_id_fkey foreign key (organization_id, patient_id) references public.patients(organization_id, id) on delete cascade;
alter table public.messages
    add constraint messages_channel_id_fkey foreign key (organization_id, channel_id) references public.messenger_channels(organization_id, id) on delete set null (channel_id);
alter table public.messages
    add constraint messages_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.task_rules
    add constraint task_rules_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.task_rules
    add constraint task_rules_stage_id_fkey foreign key (organization_id, stage_id) references public.stages(organization_id, id) on delete cascade;
alter table public.stage_checklist_items
    add constraint stage_checklist_items_stage_id_fkey foreign key (organization_id, stage_id) references public.stages(organization_id, id) on delete cascade;
alter table public.deal_checklist_checks
    add constraint deal_checklist_checks_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.deal_checklist_checks
    add constraint deal_checklist_checks_item_id_fkey foreign key (organization_id, item_id) references public.stage_checklist_items(organization_id, id) on delete cascade;
alter table public.deal_checklist_checks
    add constraint deal_checklist_checks_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

--
-- Indexes
--

create index sales_organization_id_idx on public.sales using btree (organization_id);
create unique index pipelines_one_default_idx on public.pipelines using btree (organization_id) where is_default;
create index stages_pipeline_id_idx on public.stages using btree (pipeline_id, position);
create unique index lead_sources_code_idx on public.lead_sources using btree (organization_id, code) where code is not null;
create index patients_phones_idx on public.patients using gin (phones);
create index patients_last_seen_idx on public.patients using btree (organization_id, last_seen desc);
create index patient_notes_patient_id_idx on public.patient_notes using btree (organization_id, patient_id);
create index deals_board_idx on public.deals using btree (organization_id, pipeline_id, stage_id, index);
create index deals_patient_id_idx on public.deals using btree (organization_id, patient_id);
create index deals_sales_id_idx on public.deals using btree (organization_id, sales_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (organization_id, deal_id);
create index deal_payments_deal_id_idx on public.deal_payments using btree (organization_id, deal_id);
create index deal_events_deal_id_idx on public.deal_events using btree (organization_id, deal_id, created_at);
create index tasks_deal_id_idx on public.tasks using btree (organization_id, deal_id);
create index tasks_open_due_idx on public.tasks using btree (organization_id, due_date) where done_date is null;
create index calls_patient_id_idx on public.calls using btree (organization_id, patient_id);
create unique index calls_external_id_idx on public.calls using btree (organization_id, external_id) where external_id is not null;
create unique index messenger_integrations_webhook_token_idx on public.messenger_integrations using btree (webhook_token);
create unique index messenger_channels_external_id_idx on public.messenger_channels using btree (organization_id, external_id);
create unique index patient_chats_chat_idx on public.patient_chats using btree (organization_id, transport, chat_id);
create index messages_deal_id_idx on public.messages using btree (organization_id, deal_id, sent_at);
create index messages_unread_idx on public.messages using btree (organization_id, deal_id) where direction = 'in' and read_at is null;
create index task_rules_event_idx on public.task_rules using btree (organization_id, event, stage_id);
create index stage_checklist_items_stage_id_idx on public.stage_checklist_items using btree (stage_id, position);
create unique index deal_checklist_checks_item_idx on public.deal_checklist_checks using btree (deal_id, item_id);
create unique index messages_external_id_idx on public.messages using btree (organization_id, external_id) where external_id is not null;
