--
-- Tables
-- This file declares all tables in the public schema.
--
-- Multi-tenancy: every tenant table carries `organization_id`, filled by default
-- from the current user (private.current_organization_id()) and enforced by RLS
-- (see 05_policies.sql). Foreign keys between tenant tables are composite
-- (organization_id, id) so a row can never reference a row of another clinic.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema: helpers not exposed through the REST API
create schema if not exists "private";

-- Tenant helpers. Declared before the tables because they are used as column
-- defaults. SECURITY DEFINER so that they can read public.sales without
-- recursing into its RLS policies. A disabled user belongs to no organization.
create or replace function private.current_organization_id() returns bigint
    language plpgsql stable security definer
    set search_path to ''
    as $$
begin
  return (
    select s.organization_id
    from public.sales s
    where s.user_id = auth.uid() and not s.disabled
  );
end;
$$;

create or replace function private.current_user_role() returns text
    language plpgsql stable security definer
    set search_path to ''
    as $$
begin
  return (
    select s.role
    from public.sales s
    where s.user_id = auth.uid() and not s.disabled
  );
end;
$$;

create table public.organizations (
    id bigint generated by default as identity primary key,
    name text not null,
    created_at timestamp with time zone not null default now(),
    timezone text not null default 'Asia/Almaty',
    currency text not null default 'KZT',
    -- Billing (tariffs and payments come in a later stage)
    plan text not null default 'trial',
    trial_ends_at timestamp with time zone default (now() + interval '14 days'),
    constraint organizations_name_not_blank check (btrim(name) <> '')
);

create table public.sales (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    -- owner: everything incl. billing and staff; head: reports, settings, all deals; manager: day-to-day work
    role text not null default 'manager',
    -- Kept for the Atomic CRM UI: owners and heads are administrators
    administrator boolean generated always as (role in ('owner', 'head')) stored,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false,
    secondary_emails jsonb not null default '[]'::jsonb,
    constraint sales_role_check check (role in ('owner', 'head', 'manager')),
    constraint sales_secondary_emails_is_array check (jsonb_typeof(secondary_emails) = 'array')
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.companies (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint
);

create table public.deal_notes (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.tags (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

-- One configuration row per organization (UI settings: title, logos, options)
create table public.configuration (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    config jsonb not null default '{}'::jsonb,
    constraint configuration_organization_id_key unique (organization_id)
);

-- Global list shared by all organizations (read-only for users)
create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Tenant keys: (organization_id, id) is unique on every tenant table so that
-- composite foreign keys can pin references to the same organization.
--

alter table public.sales add constraint sales_organization_id_id_key unique (organization_id, id);
alter table public.companies add constraint companies_organization_id_id_key unique (organization_id, id);
alter table public.contacts add constraint contacts_organization_id_id_key unique (organization_id, id);
alter table public.contact_notes add constraint contact_notes_organization_id_id_key unique (organization_id, id);
alter table public.deals add constraint deals_organization_id_id_key unique (organization_id, id);
alter table public.deal_notes add constraint deal_notes_organization_id_id_key unique (organization_id, id);
alter table public.tags add constraint tags_organization_id_id_key unique (organization_id, id);
alter table public.tasks add constraint tasks_organization_id_id_key unique (organization_id, id);

--
-- Foreign keys
--

alter table public.sales
    add constraint sales_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.companies
    add constraint companies_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.contacts
    add constraint contacts_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.contact_notes
    add constraint contact_notes_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.deals
    add constraint deals_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.deal_notes
    add constraint deal_notes_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.tags
    add constraint tags_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.tasks
    add constraint tasks_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.configuration
    add constraint configuration_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;

-- Same-organization references (MATCH SIMPLE: a null child column skips the check)
alter table public.companies
    add constraint companies_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (organization_id, company_id) references public.companies(organization_id, id) on update cascade on delete cascade;
alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.contact_notes
    add constraint contact_notes_contact_id_fkey foreign key (organization_id, contact_id) references public.contacts(organization_id, id) on update cascade on delete cascade;
alter table public.contact_notes
    add constraint contact_notes_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (organization_id, company_id) references public.companies(organization_id, id) on update cascade on delete cascade;
alter table public.deals
    add constraint deals_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.deal_notes
    add constraint deal_notes_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on update cascade on delete cascade;
alter table public.deal_notes
    add constraint deal_notes_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (organization_id, contact_id) references public.contacts(organization_id, id) on update cascade on delete cascade;
alter table public.tasks
    add constraint tasks_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

--
-- Indexes
--

create index sales_organization_id_idx on public.sales using btree (organization_id);
create index contact_notes_contact_id_idx on public.contact_notes using btree (organization_id, contact_id);
create index contacts_company_id_idx on public.contacts using btree (organization_id, company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (organization_id, deal_id);
create index deals_company_id_idx on public.deals using btree (organization_id, company_id);
create index tasks_contact_id_idx on public.tasks using btree (organization_id, contact_id);
