--
-- Automatic messages by templates, stage scripts (stage 6)
--
-- A rule "stage X -> template Y" puts a message in the queue (automessages)
-- when a deal enters the stage: N minutes after, or N minutes before the
-- visit (deals.appointment_at). The deal triggers schedule and cancel the
-- queue, so all the timing logic lives here. The edge function
-- automessages_dispatch, started every minute by pg_cron, takes the due rows
-- (public.claim_automessages) and sends them through Wazzup24; "show to the
-- employee first" rules become a task with the text instead.
--

-- pg_cron starts the dispatcher (the job itself is created by the migration
-- 20261002000000_stage6_automessages.sql: it is data, not schema)
create extension if not exists "pg_cron" with schema "pg_catalog";

-- What the employee says to the patient at a stage (shown on the deal page)
alter table public.stages add column script text;

-- Texts of the clinic, with the variables {имя}, {услуга}, {дата_визита}, {клиника}, {врач}
create table public.message_templates (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    body text not null,
    position integer not null default 0,
    created_at timestamp with time zone not null default now(),
    constraint message_templates_name_not_blank check (btrim(name) <> ''),
    constraint message_templates_body_not_blank check (btrim(body) <> '')
);

-- Stage X -> template Y.
--   timing after_stage: offset_minutes after the deal enters the stage;
--   timing before_visit: offset_minutes before deals.appointment_at.
--   mode auto: sent by the dispatcher; confirm: a task shows the text to the
--   responsible, who sends it (or not).
create table public.automessage_rules (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    stage_id bigint not null,
    template_id bigint not null,
    timing text not null default 'after_stage',
    offset_minutes integer not null default 0,
    mode text not null default 'auto',
    is_active boolean not null default true,
    position integer not null default 0,
    created_at timestamp with time zone not null default now(),
    constraint automessage_rules_timing_check check (timing in ('after_stage', 'before_visit')),
    constraint automessage_rules_mode_check check (mode in ('auto', 'confirm')),
    constraint automessage_rules_offset_positive check (offset_minutes >= 0)
);

-- The queue. pending -> sending -> sent | failed (auto rules),
-- pending -> awaiting (task created) -> sent (confirm rules),
-- pending | awaiting -> cancelled (the deal left the stage, the visit moved,
-- the rule was switched off, an employee cancelled it).
create table public.automessages (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    deal_id bigint not null,
    rule_id bigint,
    -- Stage and timing of the rule when scheduled: leaving the stage or
    -- moving the visit cancels the row
    stage_id bigint not null,
    timing text not null,
    send_at timestamp with time zone not null,
    status text not null default 'pending',
    -- Rendered when the row is due
    text text,
    error text,
    claimed_at timestamp with time zone,
    processed_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    constraint automessages_status_check check (status in ('pending', 'sending', 'awaiting', 'sent', 'cancelled', 'failed')),
    constraint automessages_timing_check check (timing in ('after_stage', 'before_visit'))
);

-- The task of a "show to the employee first" message, and the message sent
alter table public.tasks add column automessage_id bigint;
alter table public.messages add column automessage_id bigint;

alter table public.message_templates add constraint message_templates_organization_id_id_key unique (organization_id, id);
alter table public.automessage_rules add constraint automessage_rules_organization_id_id_key unique (organization_id, id);
alter table public.automessages add constraint automessages_organization_id_id_key unique (organization_id, id);

alter table public.message_templates
    add constraint message_templates_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.automessage_rules
    add constraint automessage_rules_stage_id_fkey foreign key (organization_id, stage_id) references public.stages(organization_id, id) on delete cascade;
alter table public.automessage_rules
    add constraint automessage_rules_template_id_fkey foreign key (organization_id, template_id) references public.message_templates(organization_id, id) on delete cascade;
alter table public.automessages
    add constraint automessages_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.automessages
    add constraint automessages_rule_id_fkey foreign key (organization_id, rule_id) references public.automessage_rules(organization_id, id) on delete set null (rule_id);
alter table public.automessages
    add constraint automessages_stage_id_fkey foreign key (organization_id, stage_id) references public.stages(organization_id, id) on delete cascade;
alter table public.tasks
    add constraint tasks_automessage_id_fkey foreign key (organization_id, automessage_id) references public.automessages(organization_id, id) on delete set null (automessage_id);
alter table public.messages
    add constraint messages_automessage_id_fkey foreign key (organization_id, automessage_id) references public.automessages(organization_id, id) on delete set null (automessage_id);

create index automessage_rules_stage_id_idx on public.automessage_rules using btree (organization_id, stage_id);
create index automessages_due_idx on public.automessages using btree (send_at) where status = 'pending';
create index automessages_deal_id_idx on public.automessages using btree (organization_id, deal_id);
create index tasks_automessage_id_idx on public.tasks using btree (organization_id, automessage_id) where automessage_id is not null;
create index messages_automessage_id_idx on public.messages using btree (organization_id, automessage_id) where automessage_id is not null;

--
-- Functions
--

-- "12 марта в 14:30" in the time zone of the clinic
CREATE OR REPLACE FUNCTION "private"."format_visit_date"("value" timestamp with time zone, "time_zone" "text") RETURNS "text"
    LANGUAGE "sql" STABLE
    SET "search_path" TO ''
    AS $$
  select extract(day from t.wall)::integer || ' '
    || (array['января', 'февраля', 'марта', 'апреля', 'мая', 'июня', 'июля',
              'августа', 'сентября', 'октября', 'ноября', 'декабря'])[extract(month from t.wall)::integer]
    || ' в ' || to_char(t.wall, 'HH24:MI')
  from (select value at time zone coalesce(nullif(time_zone, ''), 'Asia/Almaty') as wall) t
$$;

-- Replaces {variable} with its value (a missing value gives an empty string),
-- then collapses the spaces left behind. Same as renderTemplate() in the app.
CREATE OR REPLACE FUNCTION "private"."render_template"("body" "text", "vars" "jsonb") RETURNS "text"
    LANGUAGE "plpgsql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
declare
  result text := coalesce(body, '');
  item record;
begin
  for item in select * from jsonb_each_text(coalesce(vars, '{}'::jsonb)) loop
    result := replace(result, '{' || item.key || '}', coalesce(item.value, ''));
  end loop;
  result := regexp_replace(result, '[ \t]+', ' ', 'g');
  result := regexp_replace(result, ' *\n *', E'\n', 'g');
  return btrim(result, E' \n');
end;
$$;

-- Values of the template variables for a deal. plpgsql: {врач} reads
-- deals.doctor_id and public.doctors, declared later in 13_doctors.sql.
CREATE OR REPLACE FUNCTION "private"."automessage_vars"("deal" "public"."deals") RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  return (
    select jsonb_build_object(
      'имя', nullif(btrim(p.first_name), ''),
      'услуга', sv.name,
      'дата_визита', private.format_visit_date(coalesce(deal.appointment_at, deal.visit_at), o.timezone),
      'клиника', coalesce(nullif(btrim(c.config ->> 'title'), ''), o.name),
      'врач', nullif(btrim(dr.name), '')
    )
    from public.organizations o
      left join public.configuration c on c.organization_id = o.id
      left join public.patients p on p.organization_id = o.id and p.id = deal.patient_id
      left join public.services sv on sv.organization_id = o.id and sv.id = deal.service_id
      left join public.doctors dr on dr.organization_id = o.id and dr.id = deal.doctor_id
    where o.id = deal.organization_id
  );
end;
$$;

-- Quiet hours: nothing is sent between 21:00 and 9:00 of the clinic, a send
-- time outside 9:00-21:00 moves to the next 9:00
CREATE OR REPLACE FUNCTION "private"."automessage_send_time"("send_at" timestamp with time zone, "time_zone" "text") RETURNS timestamp with time zone
    LANGUAGE "sql" STABLE
    SET "search_path" TO ''
    AS $$
  select case
    when t.wall::time < time '09:00' then (t.wall::date + time '09:00') at time zone t.tz
    when t.wall::time >= time '21:00' then (t.wall::date + 1 + time '09:00') at time zone t.tz
    else send_at
  end
  from (
    select send_at at time zone coalesce(nullif(time_zone, ''), 'Asia/Almaty') as wall,
      coalesce(nullif(time_zone, ''), 'Asia/Almaty') as tz
  ) t
$$;

-- Queues the messages of the active rules of the deal's current stage
-- (only_timing: only the rules of this timing). A "before the visit" rule
-- does nothing without a visit date, or when the visit is already past.
CREATE OR REPLACE FUNCTION "private"."schedule_automessages"("deal" "public"."deals", "only_timing" "text" DEFAULT NULL::"text") RETURNS integer
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  zone text;
  scheduled integer;
begin
  if deal.archived_at is not null then
    return 0;
  end if;
  select o.timezone into zone from public.organizations o where o.id = deal.organization_id;
  insert into public.automessages (organization_id, deal_id, rule_id, stage_id, timing, send_at)
  select deal.organization_id, deal.id, j.rule_id, j.stage_id, j.timing, j.send_at
  from (
    select r.id as rule_id, r.stage_id, r.timing, r.position,
      private.automessage_send_time(
        case when r.timing = 'after_stage'
          then now() + make_interval(mins => r.offset_minutes)
          else greatest(deal.appointment_at - make_interval(mins => r.offset_minutes), now())
        end,
        zone) as send_at
    from public.automessage_rules r
    where r.organization_id = deal.organization_id
      and r.stage_id = deal.stage_id
      and r.is_active
      and (only_timing is null or r.timing = only_timing)
      and (r.timing = 'after_stage' or deal.appointment_at > now())
  ) j
  where j.timing = 'after_stage' or j.send_at < deal.appointment_at
  order by j.position, j.rule_id;
  get diagnostics scheduled = row_count;
  return scheduled;
end;
$$;

-- Cancels the queued messages of a deal (statuses: which ones; only_timing:
-- only the rows of this timing)
CREATE OR REPLACE FUNCTION "private"."cancel_automessages"("org_id" bigint, "target_deal_id" bigint, "statuses" "text"[], "only_timing" "text", "reason" "text") RETURNS integer
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  cancelled integer;
begin
  update public.automessages a
  set status = 'cancelled', error = reason, processed_at = now()
  where a.organization_id = org_id
    and a.deal_id = target_deal_id
    and a.status = any(statuses)
    and (only_timing is null or a.timing = only_timing);
  get diagnostics cancelled = row_count;
  return cancelled;
end;
$$;

-- Deal trigger: entering a stage queues its messages, leaving it cancels
-- them, moving the visit reschedules the "before the visit" ones
CREATE OR REPLACE FUNCTION "private"."handle_deal_automessages"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  -- Imported deals (crm.importing, see import_batch) get no auto-messages
  if current_setting('crm.importing', true) = 'on' then
    return null;
  end if;
  if tg_op = 'INSERT' then
    perform private.schedule_automessages(new);
    return null;
  end if;
  if new.stage_id is distinct from old.stage_id then
    perform private.cancel_automessages(new.organization_id, new.id, array['pending', 'awaiting'], null,
      'Сделка ушла с этапа');
    perform private.schedule_automessages(new);
  elsif new.archived_at is not null and old.archived_at is null then
    perform private.cancel_automessages(new.organization_id, new.id, array['pending', 'awaiting'], null,
      'Сделка в архиве');
  elsif new.appointment_at is distinct from old.appointment_at then
    perform private.cancel_automessages(new.organization_id, new.id, array['pending'], 'before_visit',
      'Дата визита изменилась');
    perform private.schedule_automessages(new, 'before_visit');
  end if;
  return null;
end;
$$;

-- Employees may only cancel a queued message (column grant: status). Security
-- invoker on purpose: current_user is 'authenticated' for an employee's own
-- update, the owner or service_role for the system (triggers, dispatcher).
CREATE OR REPLACE FUNCTION "private"."handle_automessage_update"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
begin
  if current_user = 'authenticated' then
    if new.status is distinct from old.status
      and (new.status <> 'cancelled' or old.status not in ('pending', 'awaiting')) then
      raise exception 'Можно только отменить сообщение, которое ещё не отправлено'
        using errcode = 'check_violation', hint = 'automessage_not_cancellable';
    end if;
    if new.status = 'cancelled' and old.status <> 'cancelled' then
      new.error := 'Отменено сотрудником';
      new.processed_at := now();
    end if;
  end if;
  -- The task of a cancelled "show first" message is not needed any more
  if new.status = 'cancelled' and old.status = 'awaiting' then
    delete from public.tasks t
    where t.organization_id = new.organization_id and t.automessage_id = new.id and t.done_date is null;
  end if;
  return new;
end;
$$;

-- A message stored with its automessage: the row is sent, its task done
CREATE OR REPLACE FUNCTION "private"."handle_automessage_sent"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  update public.automessages a
  set status = 'sent', error = null, text = new.text, processed_at = now()
  where a.organization_id = new.organization_id and a.id = new.automessage_id;
  update public.tasks t
  set done_date = now()
  where t.organization_id = new.organization_id and t.automessage_id = new.automessage_id
    and t.done_date is null;
  return null;
end;
$$;

-- Dispatcher (edge function automessages_dispatch, service role only): takes
-- the due rows, at most per_clinic per clinic, with FOR UPDATE SKIP LOCKED so
-- that two runs never take the same row. Returns the rows to send through
-- Wazzup24 (status sending); "show first" rows become a task (awaiting);
-- rows whose deal left the stage or whose rule is off are cancelled; a
-- clinic without messengers gets a failed row with the reason.
CREATE OR REPLACE FUNCTION "public"."claim_automessages"("per_clinic" integer DEFAULT 20) RETURNS TABLE("id" bigint, "organization_id" bigint, "deal_id" bigint, "patient_id" bigint, "message_text" "text")
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  job public.automessages;
  job_deal public.deals;
  job_rule public.automessage_rules;
  template_body text;
  rendered text;
  taken jsonb := '{}'::jsonb;
begin
  -- A run that died while sending: rather a failed row than a message sent twice
  update public.automessages a
  set status = 'failed', error = 'Отправка прервалась, проверьте переписку', processed_at = now()
  where a.status = 'sending' and a.claimed_at < now() - interval '10 minutes';

  for job in
    select a.* from public.automessages a
    where a.status = 'pending' and a.send_at <= now()
    order by a.send_at, a.id
    limit 1000
    for update skip locked
  loop
    if coalesce((taken ->> job.organization_id::text)::integer, 0) >= per_clinic then
      continue;
    end if;
    select d.* into job_deal from public.deals d
    where d.organization_id = job.organization_id and d.id = job.deal_id;
    select r.* into job_rule from public.automessage_rules r
    where r.organization_id = job.organization_id and r.id = job.rule_id;

    if job_deal.stage_id is distinct from job.stage_id or job_deal.archived_at is not null then
      update public.automessages a
      set status = 'cancelled', error = 'Сделка ушла с этапа', processed_at = now()
      where a.id = job.id;
      continue;
    end if;
    if job_rule.id is null or not job_rule.is_active then
      update public.automessages a
      set status = 'cancelled', error = 'Правило выключено или удалено', processed_at = now()
      where a.id = job.id;
      continue;
    end if;

    select t.body into template_body from public.message_templates t
    where t.organization_id = job.organization_id and t.id = job_rule.template_id;
    rendered := private.render_template(template_body, private.automessage_vars(job_deal));
    if coalesce(rendered, '') = '' then
      update public.automessages a
      set status = 'failed', error = 'Пустой текст сообщения', processed_at = now()
      where a.id = job.id;
      continue;
    end if;

    if job_rule.mode = 'confirm' then
      insert into public.tasks (organization_id, deal_id, type, text, due_date, sales_id, automessage_id)
      values (job.organization_id, job.deal_id, 'message', rendered, now(), job_deal.sales_id, job.id);
      update public.automessages a
      set status = 'awaiting', text = rendered, processed_at = now()
      where a.id = job.id;
      continue;
    end if;

    if not exists (
      select 1 from public.messenger_integrations i
      where i.organization_id = job.organization_id and i.api_key is not null
    ) and not exists (
      select 1 from public.telegram_bots b
      where b.organization_id = job.organization_id and b.bot_token is not null
    ) then
      update public.automessages a
      set status = 'failed', text = rendered, processed_at = now(),
          error = 'Мессенджеры не подключены (Настройки → Мессенджеры)'
      where a.id = job.id;
      continue;
    end if;

    update public.automessages a
    set status = 'sending', text = rendered, claimed_at = now()
    where a.id = job.id;
    taken := jsonb_set(taken, array[job.organization_id::text],
      to_jsonb(coalesce((taken ->> job.organization_id::text)::integer, 0) + 1));
    id := job.id;
    organization_id := job.organization_id;
    deal_id := job.deal_id;
    patient_id := job_deal.patient_id;
    message_text := rendered;
    return next;
  end loop;
end;
$$;

-- Called every minute by pg_cron: starts the edge function when something is
-- due. Needs two Vault secrets: project_url and automessages_dispatch_key
-- (the same key as the function's AUTOMESSAGES_DISPATCH_KEY).
CREATE OR REPLACE FUNCTION "private"."request_automessages_dispatch"() RETURNS bigint
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  project_url text;
  dispatch_key text;
begin
  if not exists (
    select 1 from public.automessages a
    where (a.status = 'pending' and a.send_at <= now())
      or (a.status = 'sending' and a.claimed_at < now() - interval '10 minutes')
  ) then
    return null;
  end if;
  if to_regclass('vault.decrypted_secrets') is null then
    return null;
  end if;
  execute 'select decrypted_secret from vault.decrypted_secrets where name = $1'
    into project_url using 'project_url';
  execute 'select decrypted_secret from vault.decrypted_secrets where name = $1'
    into dispatch_key using 'automessages_dispatch_key';
  if project_url is null or dispatch_key is null then
    raise warning 'automessages: Vault secrets project_url and automessages_dispatch_key are not set';
    return null;
  end if;
  return net.http_post(
    url := rtrim(project_url, '/') || '/functions/v1/automessages_dispatch',
    body := '{}'::jsonb,
    params := '{}'::jsonb,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || dispatch_key
    ),
    timeout_milliseconds := 5000
  );
end;
$$;

-- Default templates and rules of a clinic: a reminder the day before the
-- visit (on), a reactivation 30 days after a refusal and a greeting of new
-- leads (off, shown to the employee first)
CREATE OR REPLACE FUNCTION "private"."seed_automessages"("org_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  default_pipeline_id bigint;
  reminder_id bigint;
  reactivation_id bigint;
  greeting_id bigint;
begin
  if exists (select 1 from public.message_templates t where t.organization_id = org_id) then
    return;
  end if;
  insert into public.message_templates (organization_id, name, body, position)
  values (org_id, 'Напоминание о визите',
    'Здравствуйте, {имя}! Напоминаем, что вы записаны в {клиника} на {дата_визита}. Если планы изменились, напишите нам, пожалуйста.', 0)
  returning id into reminder_id;
  insert into public.message_templates (organization_id, name, body, position)
  values (org_id, 'Возврат после отказа',
    'Здравствуйте, {имя}! Это {клиника}. Вы обращались к нам недавно. Вопрос ещё актуален? Будем рады помочь и подобрать удобное время.', 1)
  returning id into reactivation_id;
  insert into public.message_templates (organization_id, name, body, position)
  values (org_id, 'Приветствие',
    'Здравствуйте, {имя}! Спасибо за обращение в {клиника}. Подскажите, пожалуйста, что вас беспокоит и когда вам удобно прийти на консультацию?', 2)
  returning id into greeting_id;

  select p.id into default_pipeline_id from public.pipelines p
  where p.organization_id = org_id and p.is_default;
  if default_pipeline_id is null then
    return;
  end if;
  insert into public.automessage_rules (organization_id, stage_id, template_id, timing, offset_minutes, mode, is_active, position)
  select org_id, s.id, reminder_id, 'before_visit', 24 * 60, 'auto', true, 0
  from public.stages s where s.pipeline_id = default_pipeline_id and s.name = 'Записан';
  insert into public.automessage_rules (organization_id, stage_id, template_id, timing, offset_minutes, mode, is_active, position)
  select org_id, s.id, reactivation_id, 'after_stage', 30 * 24 * 60, 'confirm', false, 1
  from public.stages s where s.pipeline_id = default_pipeline_id and s.kind = 'lost'
  order by s.position limit 1;
  insert into public.automessage_rules (organization_id, stage_id, template_id, timing, offset_minutes, mode, is_active, position)
  select org_id, s.id, greeting_id, 'after_stage', 0, 'confirm', false, 2
  from public.stages s where s.pipeline_id = default_pipeline_id
  order by s.position, s.id limit 1;
end;
$$;

--
-- Triggers
--

create or replace trigger deal_automessages
    after insert or update on public.deals
    for each row execute function private.handle_deal_automessages();

create or replace trigger automessage_update
    before update on public.automessages
    for each row execute function private.handle_automessage_update();

create or replace trigger message_automessage_sent
    after insert on public.messages
    for each row
    when (new.automessage_id is not null)
    execute function private.handle_automessage_sent();

--
-- Row Level Security
--

alter table public.message_templates enable row level security;
alter table public.automessage_rules enable row level security;
alter table public.automessages enable row level security;

-- Templates and rules are settings (owner and head); the queue follows the deal
create policy "Organization members can read" on public.message_templates for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Owner and head can insert" on public.message_templates for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can update" on public.message_templates for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head can delete" on public.message_templates for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Organization members can read" on public.automessage_rules for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Owner and head can insert" on public.automessage_rules for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can update" on public.automessage_rules for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head can delete" on public.automessage_rules for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Rows of visible deals can be read" on public.automessages for select to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = automessages.organization_id and d.id = automessages.deal_id));
create policy "Rows of visible deals can be updated" on public.automessages for update to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = automessages.organization_id and d.id = automessages.deal_id))
    with check (organization_id = (select private.current_organization_id()));

--
-- Grants
--

grant all on table public.message_templates to anon;
grant all on table public.message_templates to authenticated;
grant all on table public.message_templates to service_role;
grant all on table public.automessage_rules to anon;
grant all on table public.automessage_rules to authenticated;
grant all on table public.automessage_rules to service_role;
grant all on sequence public.message_templates_id_seq to anon, authenticated, service_role;
grant all on sequence public.automessage_rules_id_seq to anon, authenticated, service_role;

-- The queue is written by the system; employees read it and may cancel
revoke all on table public.automessages from anon, authenticated;
grant select on table public.automessages to authenticated;
grant update (status) on table public.automessages to authenticated;
grant all on table public.automessages to service_role;
revoke all on sequence public.automessages_id_seq from anon, authenticated;
grant all on sequence public.automessages_id_seq to service_role;

revoke all on function public.claim_automessages(integer) from public, anon, authenticated;
grant execute on function public.claim_automessages(integer) to service_role;
-- Definer helpers of the triggers and the dispatcher: not callable by clients
revoke all on function private.request_automessages_dispatch() from public, anon, authenticated;
revoke all on function private.schedule_automessages(public.deals, text) from public, anon, authenticated;
revoke all on function private.cancel_automessages(bigint, bigint, text[], text, text) from public, anon, authenticated;
revoke all on function private.seed_automessages(bigint) from public, anon, authenticated;
revoke all on function private.automessage_vars(public.deals) from public, anon, authenticated;
grant execute on function private.automessage_vars(public.deals) to service_role;
revoke all on function private.handle_deal_automessages() from public, anon, authenticated;
revoke all on function private.handle_automessage_sent() from public, anon, authenticated;
