--
-- Stage 8: requests from the website, Tilda and 2GIS (lead webhook), and the
-- clinic's own Telegram bot (Bot API) next to the Wazzup24 channels.
--

--
-- Tables
--

-- Token of the clinic's lead webhook (edge function leads_webhook?token=).
-- Readable by the service role only; owners and heads get it through
-- public.lead_webhook_token() and change it with
-- public.regenerate_lead_webhook_token().
create table public.lead_integrations (
    organization_id bigint primary key,
    token text not null default replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', ''),
    created_at timestamp with time zone not null default now(),
    token_changed_at timestamp with time zone
);

-- Every request received through the webhook: what the form sent, where it
-- went, and the payload hash that makes a repeated submission a no-op
create table public.lead_submissions (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    phone text not null,
    payload_hash text not null,
    payload jsonb not null default '{}'::jsonb,
    patient_id bigint not null,
    deal_id bigint not null,
    created_at timestamp with time zone not null default now()
);

-- The clinic's own Telegram bot (token from @BotFather). Secret: service role
-- only, like messenger_integrations. webhook_token is part of the webhook
-- URL (identifies the clinic), secret_token is checked in the
-- X-Telegram-Bot-Api-Secret-Token header of every update.
create table public.telegram_bots (
    organization_id bigint primary key,
    bot_token text,
    bot_id bigint,
    username text,
    name text,
    webhook_token text not null default replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', ''),
    secret_token text not null default replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', ''),
    connected_at timestamp with time zone,
    last_error text
);

alter table public.lead_submissions add constraint lead_submissions_organization_id_id_key unique (organization_id, id);

alter table public.lead_integrations
    add constraint lead_integrations_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.lead_submissions
    add constraint lead_submissions_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.lead_submissions
    add constraint lead_submissions_patient_id_fkey foreign key (organization_id, patient_id) references public.patients(organization_id, id) on delete cascade;
alter table public.lead_submissions
    add constraint lead_submissions_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.telegram_bots
    add constraint telegram_bots_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;

create unique index lead_integrations_token_idx on public.lead_integrations using btree (token);
create index lead_submissions_dedupe_idx on public.lead_submissions using btree (organization_id, phone, created_at);
create unique index telegram_bots_webhook_token_idx on public.telegram_bots using btree (webhook_token);

--
-- Functions
--

-- A request from a website form, Tilda or 2GIS (edge function leads_webhook,
-- service role):
--   { name, phone, source, service, comment, utm: { utm_source, ... } }
-- source is a code or a name of the clinic's sources (default: website),
-- service a name of its services (case-insensitive). Finds the patient by
-- phone or creates one, attaches the request to the patient's most recently
-- updated open deal or opens a new deal (distributed by the clinic rules, with
-- its automatic tasks), and always writes the form into a note of the deal.
-- The same form sent again within 5 minutes is ignored.
CREATE OR REPLACE FUNCTION "public"."ingest_lead"("token" "text", "lead" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint;
  lead_name text := nullif(btrim(lead ->> 'name'), '');
  lead_phone text := private.normalize_phone(nullif(btrim(lead ->> 'phone'), ''));
  lead_source text := nullif(btrim(lead ->> 'source'), '');
  lead_service text := nullif(btrim(lead ->> 'service'), '');
  lead_comment text := nullif(btrim(lead ->> 'comment'), '');
  utm jsonb;
  payload jsonb;
  hash text;
  previous public.lead_submissions;
  found_source public.lead_sources;
  found_service_id bigint;
  found_patient_id bigint;
  found_deal_id bigint;
  created_patient boolean := false;
  created_deal boolean := false;
  note_text text;
  new_note_id bigint;
  new_submission_id bigint;
begin
  select i.organization_id into org_id
  from public.lead_integrations i
  where i.token = ingest_lead.token;
  if org_id is null then
    raise exception 'Unknown lead token' using errcode = '28000';
  end if;
  if jsonb_typeof(lead) is distinct from 'object'
    or lead_phone is null or length(lead_phone) not between 11 and 16 then
    raise exception 'A lead needs a phone number' using errcode = '22023';
  end if;

  -- UTM tags: an utm object and/or top-level utm_* fields
  select coalesce(jsonb_object_agg(e.key, e.value), '{}'::jsonb) into utm
  from (
    select u.key, u.value
    from jsonb_each_text(case when jsonb_typeof(lead -> 'utm') = 'object' then lead -> 'utm' else '{}'::jsonb end) as u
    union
    select u.key, u.value
    from jsonb_each_text(lead) as u
    where u.key like 'utm\_%'
  ) as e
  where nullif(btrim(e.value), '') is not null;
  payload := jsonb_strip_nulls(jsonb_build_object(
    'name', lead_name, 'phone', lead_phone, 'source', lead_source,
    'service', lead_service, 'comment', lead_comment,
    'utm', case when utm <> '{}'::jsonb then utm end
  ));
  hash := md5(payload::text);

  -- Forms are often submitted twice: the same request within 5 minutes is
  -- stored once (concurrent submissions of a phone wait for each other)
  perform pg_advisory_xact_lock(hashtextextended(org_id::text || ':' || lead_phone, 0));
  select * into previous from public.lead_submissions s
  where s.organization_id = org_id and s.phone = lead_phone and s.payload_hash = hash
    and s.created_at > now() - interval '5 minutes'
  order by s.created_at desc
  limit 1;
  if found then
    return jsonb_build_object('lead_id', previous.id, 'patient_id', previous.patient_id,
      'deal_id', previous.deal_id, 'duplicate', true);
  end if;

  select * into found_source from public.lead_sources s
  where s.organization_id = org_id
    and (lower(s.code) = lower(coalesce(lead_source, 'website')) or lower(s.name) = lower(coalesce(lead_source, 'website')))
  order by s.is_archived, s.is_system desc, s.position, s.id
  limit 1;
  if not found then
    select * into found_source from public.lead_sources s
    where s.organization_id = org_id and s.code = 'website';
  end if;

  if lead_service is not null then
    select s.id into found_service_id from public.services s
    where s.organization_id = org_id and lower(btrim(s.name)) = lower(lead_service)
    order by s.is_archived, s.position, s.id
    limit 1;
  end if;

  -- The patient: by phone, else a new one
  select p.id into found_patient_id from public.patients p
  where p.organization_id = org_id and p.phones @> array[lead_phone]
  order by p.last_seen desc, p.id desc
  limit 1;
  if found_patient_id is null then
    insert into public.patients (organization_id, first_name, phone_jsonb, source_id)
    values (
      org_id,
      coalesce(lead_name, lead_phone),
      jsonb_build_array(jsonb_build_object('number', lead_phone, 'type', 'mobile')),
      found_source.id
    )
    returning id into found_patient_id;
    created_patient := true;
  end if;

  -- The deal: the most recently updated open one, else a new request
  select d.id into found_deal_id
  from public.deals d
    join public.stages s on s.id = d.stage_id
  where d.organization_id = org_id and d.patient_id = found_patient_id
    and s.kind = 'open' and d.archived_at is null
  order by d.updated_at desc, d.id desc
  limit 1;
  if found_deal_id is null then
    insert into public.deals (organization_id, patient_id, source_id, service_id)
    values (org_id, found_patient_id, found_source.id, found_service_id)
    returning id into found_deal_id;
    created_deal := true;
  elsif found_service_id is not null then
    update public.deals
    set service_id = found_service_id
    where organization_id = org_id and id = found_deal_id and service_id is null;
  end if;

  note_text := concat_ws(E'\n',
    case when created_deal then 'Заявка' else 'Повторная заявка' end
      || ' (' || coalesce(found_source.name, 'Сайт') || ')',
    'Имя: ' || lead_name,
    'Телефон: ' || lead_phone,
    case when lead_source is not null and lower(lead_source) not in (lower(found_source.name), lower(coalesce(found_source.code, '')))
      then 'Источник: ' || lead_source end,
    'Услуга: ' || lead_service,
    'Комментарий: ' || lead_comment,
    (select string_agg(u.key || ': ' || u.value, E'\n' order by u.key) from jsonb_each_text(utm) as u)
  );
  insert into public.deal_notes (organization_id, deal_id, type, text, date)
  values (org_id, found_deal_id, 'lead', note_text, now())
  returning id into new_note_id;

  update public.patients set last_seen = now()
  where organization_id = org_id and id = found_patient_id;

  insert into public.lead_submissions (organization_id, phone, payload_hash, payload, patient_id, deal_id)
  values (org_id, lead_phone, hash, payload, found_patient_id, found_deal_id)
  returning id into new_submission_id;

  return jsonb_build_object('lead_id', new_submission_id, 'patient_id', found_patient_id,
    'deal_id', found_deal_id, 'note_id', new_note_id, 'created_patient', created_patient,
    'created_deal', created_deal, 'duplicate', false);
end;
$$;

-- Token of the clinic's lead webhook (owner and head), created on first use
CREATE OR REPLACE FUNCTION "public"."lead_webhook_token"() RETURNS "text"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  result text;
begin
  if org_id is null or private.current_user_role() not in ('owner', 'head') then
    raise exception 'Only the owner and the head manage the lead webhook' using errcode = '42501';
  end if;
  insert into public.lead_integrations (organization_id) values (org_id)
  on conflict (organization_id) do nothing;
  select i.token into result from public.lead_integrations i where i.organization_id = org_id;
  return result;
end;
$$;

-- A new token: forms still sending the old one are refused
CREATE OR REPLACE FUNCTION "public"."regenerate_lead_webhook_token"() RETURNS "text"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  result text;
begin
  if org_id is null or private.current_user_role() not in ('owner', 'head') then
    raise exception 'Only the owner and the head manage the lead webhook' using errcode = '42501';
  end if;
  insert into public.lead_integrations (organization_id) values (org_id)
  on conflict (organization_id) do update
  set token = replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', ''),
      token_changed_at = now()
  returning token into result;
  return result;
end;
$$;

-- Is the clinic's Telegram bot connected (owner and head; the token stays secret)
CREATE OR REPLACE FUNCTION "public"."telegram_bot_status"() RETURNS TABLE("connected" boolean, "username" "text", "name" "text", "connected_at" timestamp with time zone, "last_error" "text")
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
  select b.bot_token is not null, b.username, b.name, b.connected_at, b.last_error
  from public.telegram_bots b
  where b.organization_id = private.current_organization_id()
    and private.current_user_role() in ('owner', 'head')
$$;

-- A Telegram user shared their phone number with the bot: the number goes
-- to the patient of the chat. When another patient already has it and the
-- chat's patient is only this chat (no phone, no other chat, no notes, no
-- calls), the chat's patient is merged into the known one: its deals,
-- messages and chat move there. Otherwise the phone is just stored.
CREATE OR REPLACE FUNCTION "private"."link_telegram_phone"("org_id" bigint, "chat_patient_id" bigint, "phone" "text") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  known_patient_id bigint;
begin
  if exists (
    select 1 from public.patients p
    where p.organization_id = org_id and p.id = chat_patient_id and p.phones @> array[phone]
  ) then
    return '{}'::jsonb;
  end if;

  select p.id into known_patient_id from public.patients p
  where p.organization_id = org_id and p.phones @> array[phone] and p.id <> chat_patient_id
  order by p.last_seen desc, p.id desc
  limit 1;

  if known_patient_id is not null
    and exists (
      select 1 from public.patients p
      where p.organization_id = org_id and p.id = chat_patient_id and cardinality(p.phones) = 0
    )
    and (select count(*) from public.patient_chats c
         where c.organization_id = org_id and c.patient_id = chat_patient_id) = 1
    and not exists (select 1 from public.patient_notes n
                    where n.organization_id = org_id and n.patient_id = chat_patient_id)
    and not exists (select 1 from public.calls c
                    where c.organization_id = org_id and c.patient_id = chat_patient_id)
  then
    update public.patient_chats set patient_id = known_patient_id
    where organization_id = org_id and patient_id = chat_patient_id;
    update public.deals set patient_id = known_patient_id
    where organization_id = org_id and patient_id = chat_patient_id;
    update public.messages set patient_id = known_patient_id
    where organization_id = org_id and patient_id = chat_patient_id;
    update public.lead_submissions set patient_id = known_patient_id
    where organization_id = org_id and patient_id = chat_patient_id;
    update public.patients as known
    set telegram = coalesce(known.telegram, merged.telegram), last_seen = now()
    from public.patients merged
    where known.organization_id = org_id and known.id = known_patient_id
      and merged.organization_id = org_id and merged.id = chat_patient_id;
    delete from public.patients where organization_id = org_id and id = chat_patient_id;
    return jsonb_build_object('patient_id', known_patient_id, 'merged_patient_id', chat_patient_id);
  end if;

  update public.patients
  set phone_jsonb = phone_jsonb || jsonb_build_array(jsonb_build_object('number', phone, 'type', 'mobile'))
  where organization_id = org_id and id = chat_patient_id;
  return jsonb_build_object('phone_saved', true);
end;
$$;

-- An update of the clinic's Telegram bot (edge function telegram_webhook,
-- service role), in the shape of public.ingest_message with transport
-- telegram_bot and chat_id = the Telegram chat id. The secret token of the
-- X-Telegram-Bot-Api-Secret-Token header must match. contact.phone is set
-- when the user shared their own contact: the phone is saved (see
-- private.link_telegram_phone), and a new chat whose phone is already known
-- joins that patient.
CREATE OR REPLACE FUNCTION "public"."ingest_telegram_message"("webhook_token" "text", "secret_token" "text", "message" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  bot public.telegram_bots;
  msg_chat_id text := nullif(btrim(message ->> 'chat_id'), '');
  shared_phone text := private.normalize_phone(nullif(btrim(message #>> '{contact,phone}'), ''));
  known_patient_id bigint;
  result jsonb;
begin
  select * into bot from public.telegram_bots b
  where b.webhook_token = ingest_telegram_message.webhook_token;
  if not found or bot.bot_token is null
    or bot.secret_token is distinct from ingest_telegram_message.secret_token then
    raise exception 'Unknown webhook token' using errcode = '28000';
  end if;
  if msg_chat_id is null then
    raise exception 'Unsupported message' using errcode = '22023';
  end if;

  if shared_phone is not null and not exists (
    select 1 from public.patient_chats c
    where c.organization_id = bot.organization_id and c.transport = 'telegram_bot' and c.chat_id = msg_chat_id
  ) then
    select p.id into known_patient_id from public.patients p
    where p.organization_id = bot.organization_id and p.phones @> array[shared_phone]
    order by p.last_seen desc, p.id desc
    limit 1;
    if known_patient_id is not null then
      insert into public.patient_chats (organization_id, patient_id, transport, chat_id, username)
      values (bot.organization_id, known_patient_id, 'telegram_bot', msg_chat_id, nullif(btrim(message #>> '{contact,username}'), ''));
    end if;
  end if;

  result := public.ingest_message(
    ingest_telegram_message.webhook_token,
    message || jsonb_build_object(
      'transport', 'telegram_bot',
      'channel_id', case when bot.bot_id is not null then 'tgbot:' || bot.bot_id end
    )
  );

  if shared_phone is not null then
    result := result || private.link_telegram_phone(bot.organization_id, (result ->> 'patient_id')::bigint, shared_phone);
  end if;
  return result;
end;
$$;

--
-- Row level security
--

alter table public.lead_integrations enable row level security;
alter table public.lead_submissions enable row level security;
alter table public.telegram_bots enable row level security;

-- lead_integrations and telegram_bots have no policy at all: their tokens are
-- only read by the edge functions (service role) and the RPCs above.
create policy "Owner and head can read" on public.lead_submissions for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

--
-- Grants
--

revoke all on table public.lead_integrations from anon, authenticated;
grant all on table public.lead_integrations to service_role;
revoke all on table public.telegram_bots from anon, authenticated;
grant all on table public.telegram_bots to service_role;
revoke all on table public.lead_submissions from anon, authenticated;
grant select on table public.lead_submissions to authenticated;
grant all on table public.lead_submissions to service_role;
revoke all on sequence public.lead_submissions_id_seq from anon, authenticated;
grant all on sequence public.lead_submissions_id_seq to service_role;

revoke all on function public.ingest_lead(text, jsonb) from public, anon, authenticated;
grant execute on function public.ingest_lead(text, jsonb) to service_role;
revoke all on function public.lead_webhook_token() from public, anon;
grant execute on function public.lead_webhook_token() to authenticated, service_role;
revoke all on function public.regenerate_lead_webhook_token() from public, anon;
grant execute on function public.regenerate_lead_webhook_token() to authenticated, service_role;
revoke all on function public.telegram_bot_status() from public, anon;
grant execute on function public.telegram_bot_status() to authenticated, service_role;
revoke all on function public.ingest_telegram_message(text, text, jsonb) from public, anon, authenticated;
grant execute on function public.ingest_telegram_message(text, text, jsonb) to service_role;
revoke all on function private.link_telegram_phone(bigint, bigint, text) from public;
grant execute on function private.link_telegram_phone(bigint, bigint, text) to service_role;
