--
-- Data import (Excel / CSV, amoCRM export) and groundwork for MIS integrations
--
-- external_refs: which row of the CRM a record of another system is (an amoCRM
-- deal, a row of a clinic's Excel file, later a patient of a MIS). Imports use
-- it to find what they already brought in, so running a file twice changes
-- nothing. entity_id is not a foreign key (it points at one of several tables);
-- triggers remove the references of deleted patients and deals.
--
-- integrations: connections to other systems (MIS). Their settings hold API
-- keys, so only the service role reads the table, like messenger_integrations;
-- employees see the status through integration_status().
--

create table public.external_refs (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    entity text not null,
    entity_id bigint not null,
    system text not null,
    external_id text not null,
    created_at timestamp with time zone not null default now(),
    -- appointment: a MIS appointment on its deal; payment, doctor: stage 27
    constraint external_refs_entity_check check (entity in ('patient', 'deal', 'sales', 'service', 'appointment', 'payment', 'doctor')),
    constraint external_refs_system_not_blank check (btrim(system) <> ''),
    constraint external_refs_external_id_not_blank check (btrim(external_id) <> ''),
    constraint external_refs_external_id_key unique (organization_id, system, entity, external_id)
);

create table public.integrations (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    kind text not null,
    -- requested: the clinic asked for the connector; connected / error: a
    -- running connector; disabled: turned off by the clinic
    status text not null default 'requested',
    settings jsonb not null default '{}'::jsonb,
    last_sync_at timestamp with time zone,
    last_error text,
    created_at timestamp with time zone not null default now(),
    -- dentist_plus, macdent: the connectors of stage 27 (27_mis_connectors.sql)
    constraint integrations_kind_check check (kind in ('ident', 'dentalpro', 'medelement', '1c_medicine', 'other', 'dentist_plus', 'macdent')),
    constraint integrations_status_check check (status in ('requested', 'connected', 'error', 'disabled')),
    constraint integrations_settings_is_object check (jsonb_typeof(settings) = 'object'),
    constraint integrations_organization_id_kind_key unique (organization_id, kind)
);

alter table public.external_refs add constraint external_refs_organization_id_id_key unique (organization_id, id);
alter table public.integrations add constraint integrations_organization_id_id_key unique (organization_id, id);

alter table public.external_refs
    add constraint external_refs_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.integrations
    add constraint integrations_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;

create index external_refs_entity_idx on public.external_refs using btree (organization_id, entity, entity_id);

--
-- Functions
--

-- References of a deleted patient or deal
CREATE OR REPLACE FUNCTION "private"."delete_external_refs"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  delete from public.external_refs r
  where r.organization_id = old.organization_id
    and r.entity = tg_argv[0]
    and r.entity_id = old.id;
  return null;
end;
$$;

-- One row of an import (see import_batch). Returns what happened to the
-- patient and to the deal: created, updated or skipped (nothing new).
CREATE OR REPLACE FUNCTION "private"."import_row"("org_id" bigint, "import_kind" "text", "item" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  source_system text := coalesce(nullif(btrim(item ->> 'system'), ''), 'excel');
  p jsonb := coalesce(item -> 'patient', '{}'::jsonb);
  d jsonb := item -> 'deal';
  numbers text[];
  patient_ext text := nullif(btrim(p ->> 'external_id'), '');
  patient_row public.patients;
  saved_patient public.patients;
  patient_outcome text;
  deal_ext text;
  deal_name text;
  deal_row public.deals;
  saved_deal public.deals;
  deal_outcome text;
  target_stage public.stages;
  current_kind text;
  reason_id bigint;
  created timestamp with time zone;
  paid bigint;
  new_tags bigint[];
begin
  numbers := array(
    select distinct n
    from (
      select private.normalize_phone(x) as n
      from jsonb_array_elements_text(coalesce(p -> 'phones', '[]'::jsonb)) as x
    ) as normalized
    where n is not null
    order by n
  );
  if cardinality(numbers) = 0 and patient_ext is null
    and coalesce(nullif(btrim(p ->> 'first_name'), ''), nullif(btrim(p ->> 'last_name'), '')) is null then
    raise exception 'Нет ни имени, ни телефона пациента' using errcode = 'check_violation';
  end if;

  -- The patient: by the id in the source system, then by phone, then (no
  -- phone at all) by full name and birth date
  if patient_ext is not null then
    select pt.* into patient_row
    from public.external_refs r
      join public.patients pt on pt.organization_id = r.organization_id and pt.id = r.entity_id
    where r.organization_id = org_id and r.system = source_system
      and r.entity = 'patient' and r.external_id = patient_ext;
  end if;
  if patient_row.id is null and cardinality(numbers) > 0 then
    select pt.* into patient_row
    from public.patients pt
    where pt.organization_id = org_id and pt.phones && numbers
    order by pt.id
    limit 1;
  end if;
  if patient_row.id is null and cardinality(numbers) = 0 then
    select pt.* into patient_row
    from public.patients pt
    where pt.organization_id = org_id and pt.phones = '{}'::text[]
      and lower(coalesce(pt.last_name, '')) = lower(coalesce(nullif(btrim(p ->> 'last_name'), ''), ''))
      and lower(coalesce(pt.first_name, '')) = lower(coalesce(nullif(btrim(p ->> 'first_name'), ''), ''))
      and lower(coalesce(pt.middle_name, '')) = lower(coalesce(nullif(btrim(p ->> 'middle_name'), ''), ''))
      and pt.birth_date is not distinct from (p ->> 'birth_date')::date
    order by pt.id
    limit 1;
  end if;

  new_tags := array(select t::bigint from jsonb_array_elements_text(coalesce(p -> 'tags', '[]'::jsonb)) as t);
  if patient_row.id is null then
    created := coalesce((p ->> 'created_at')::timestamp with time zone, now());
    insert into public.patients (
      organization_id, first_name, last_name, middle_name, phone_jsonb, birth_date,
      city, source_id, sales_id, tags, background, first_seen, last_seen, custom_values
    )
    values (
      org_id,
      nullif(btrim(p ->> 'first_name'), ''),
      nullif(btrim(p ->> 'last_name'), ''),
      nullif(btrim(p ->> 'middle_name'), ''),
      coalesce((select jsonb_agg(jsonb_build_object('number', n, 'type', 'Mobile')) from unnest(numbers) as n), '[]'::jsonb),
      (p ->> 'birth_date')::date,
      nullif(btrim(p ->> 'city'), ''),
      (p ->> 'source_id')::bigint,
      (p ->> 'sales_id')::bigint,
      new_tags,
      nullif(btrim(p ->> 'background'), ''),
      created,
      created,
      case when jsonb_typeof(p -> 'custom_values') = 'object' then p -> 'custom_values' else '{}'::jsonb end
    )
    returning * into saved_patient;
    patient_outcome := 'created';
  else
    -- Fill what is missing, never overwrite what the clinic already has
    update public.patients pt
    set first_name = coalesce(pt.first_name, nullif(btrim(p ->> 'first_name'), '')),
        last_name = coalesce(pt.last_name, nullif(btrim(p ->> 'last_name'), '')),
        middle_name = coalesce(pt.middle_name, nullif(btrim(p ->> 'middle_name'), '')),
        phone_jsonb = pt.phone_jsonb || coalesce((
          select jsonb_agg(jsonb_build_object('number', n, 'type', 'Mobile'))
          from unnest(numbers) as n
          where not n = any(pt.phones)
        ), '[]'::jsonb),
        birth_date = coalesce(pt.birth_date, (p ->> 'birth_date')::date),
        city = coalesce(pt.city, nullif(btrim(p ->> 'city'), '')),
        source_id = coalesce(pt.source_id, (p ->> 'source_id')::bigint),
        sales_id = coalesce(pt.sales_id, (p ->> 'sales_id')::bigint),
        tags = pt.tags || array(select t from unnest(new_tags) as t where not t = any(pt.tags)),
        background = coalesce(nullif(pt.background, ''), nullif(btrim(p ->> 'background'), '')),
        custom_values = case
          when jsonb_typeof(p -> 'custom_values') = 'object' then (p -> 'custom_values') || pt.custom_values
          else pt.custom_values
        end
    where pt.organization_id = org_id and pt.id = patient_row.id
    returning * into saved_patient;
    patient_outcome := case
      when to_jsonb(saved_patient) is distinct from to_jsonb(patient_row) then 'updated'
      else 'skipped'
    end;
  end if;
  if patient_ext is not null then
    insert into public.external_refs (organization_id, entity, entity_id, system, external_id)
    values (org_id, 'patient', saved_patient.id, source_system, patient_ext)
    on conflict (organization_id, system, entity, external_id)
    do update set entity_id = excluded.entity_id;
  end if;

  if import_kind <> 'deals' or d is null or jsonb_typeof(d) <> 'object' then
    return jsonb_build_object('patient', patient_outcome, 'patient_id', saved_patient.id);
  end if;

  -- The deal: by the id in the source system, else by patient and name
  deal_ext := nullif(btrim(d ->> 'external_id'), '');
  deal_name := coalesce(nullif(btrim(d ->> 'name'), ''), 'Обращение');
  if deal_ext is not null then
    select dl.* into deal_row
    from public.external_refs r
      join public.deals dl on dl.organization_id = r.organization_id and dl.id = r.entity_id
    where r.organization_id = org_id and r.system = source_system
      and r.entity = 'deal' and r.external_id = deal_ext;
  else
    select dl.* into deal_row
    from public.deals dl
    where dl.organization_id = org_id and dl.patient_id = saved_patient.id
      and lower(btrim(coalesce(dl.name, ''))) = lower(deal_name)
    order by dl.id
    limit 1;
  end if;

  if (d ->> 'stage_id') is not null then
    select s.* into target_stage
    from public.stages s
    where s.organization_id = org_id and s.id = (d ->> 'stage_id')::bigint;
    if target_stage.id is null then
      raise exception 'Этап не найден' using errcode = 'foreign_key_violation';
    end if;
  end if;
  -- A refused deal needs a reason: the file's, else "Другое", else the first one
  reason_id := (d ->> 'lost_reason_id')::bigint;
  if target_stage.kind = 'lost' and reason_id is null then
    select lr.id into reason_id
    from public.lost_reasons lr
    where lr.organization_id = org_id
    order by lr.name = 'Другое' desc, lr.position, lr.id
    limit 1;
  end if;
  new_tags := array(select t::bigint from jsonb_array_elements_text(coalesce(d -> 'tags', '[]'::jsonb)) as t);
  paid := coalesce(round((d ->> 'paid_amount')::numeric), 0)::bigint;
  created := (d ->> 'created_at')::timestamp with time zone;

  if deal_row.id is null then
    insert into public.deals (
      organization_id, patient_id, pipeline_id, stage_id, name, source_id, service_id,
      plan_amount, sales_id, lost_reason_id, tags, description, created_at, custom_values
    )
    values (
      org_id,
      saved_patient.id,
      target_stage.pipeline_id,
      target_stage.id,
      deal_name,
      (d ->> 'source_id')::bigint,
      (d ->> 'service_id')::bigint,
      coalesce(round((d ->> 'plan_amount')::numeric), 0)::bigint,
      (d ->> 'sales_id')::bigint,
      reason_id,
      new_tags,
      nullif(btrim(d ->> 'description'), ''),
      coalesce(created, now()),
      case when jsonb_typeof(d -> 'custom_values') = 'object' then d -> 'custom_values' else '{}'::jsonb end
    )
    returning * into saved_deal;
    -- The dates of the file, not of the import
    if created is not null then
      update public.deals dl
      set stage_changed_at = created,
          closed_at = case when dl.closed_at is not null then created end
      where dl.organization_id = org_id and dl.id = saved_deal.id;
    end if;
    deal_outcome := 'created';
  else
    select s.kind into current_kind from public.stages s where s.id = deal_row.stage_id;
    update public.deals dl
    set plan_amount = coalesce(round((d ->> 'plan_amount')::numeric)::bigint, dl.plan_amount),
        source_id = coalesce(dl.source_id, (d ->> 'source_id')::bigint),
        service_id = coalesce(dl.service_id, (d ->> 'service_id')::bigint),
        sales_id = coalesce(dl.sales_id, (d ->> 'sales_id')::bigint),
        tags = dl.tags || array(select t from unnest(new_tags) as t where not t = any(dl.tags)),
        description = coalesce(nullif(dl.description, ''), nullif(btrim(d ->> 'description'), '')),
        -- Custom fields: what the deal does not have yet
        custom_values = case
          when jsonb_typeof(d -> 'custom_values') = 'object' then (d -> 'custom_values') || dl.custom_values
          else dl.custom_values
        end,
        -- The stage of the file, within the same pipeline; a refusal stays
        stage_id = case
          when target_stage.id is not null and target_stage.pipeline_id = dl.pipeline_id
            and current_kind <> 'lost' then target_stage.id
          else dl.stage_id
        end,
        lost_reason_id = case
          when target_stage.kind = 'lost' and target_stage.pipeline_id = dl.pipeline_id
            and current_kind <> 'lost' then coalesce(dl.lost_reason_id, reason_id)
          else dl.lost_reason_id
        end
    where dl.organization_id = org_id and dl.id = deal_row.id
    returning * into saved_deal;
    deal_outcome := case
      when (to_jsonb(saved_deal) - 'updated_at') is distinct from (to_jsonb(deal_row) - 'updated_at') then 'updated'
      else 'skipped'
    end;
  end if;

  -- "Paid" of the file: a payment for what the deal does not have yet
  if paid > saved_deal.paid_amount then
    insert into public.deal_payments (organization_id, deal_id, amount, paid_at, comment)
    values (org_id, saved_deal.id, paid - saved_deal.paid_amount,
      coalesce(created, now())::date, 'Импорт');
    if deal_outcome = 'skipped' then
      deal_outcome := 'updated';
    end if;
  end if;

  if deal_ext is not null then
    insert into public.external_refs (organization_id, entity, entity_id, system, external_id)
    values (org_id, 'deal', saved_deal.id, source_system, deal_ext)
    on conflict (organization_id, system, entity, external_id)
    do update set entity_id = excluded.entity_id;
  end if;

  return jsonb_build_object(
    'patient', patient_outcome, 'patient_id', saved_patient.id,
    'deal', deal_outcome, 'deal_id', saved_deal.id
  );
end;
$$;

-- Imports a batch of rows prepared by the import wizard (at most a few
-- hundred per call). Kind: 'patients' (patients only) or 'deals' (patients
-- and their deals). Every row:
--   { index, system: 'excel' | 'amocrm',
--     patient: { external_id, first_name, last_name, middle_name, phones[],
--                birth_date, city, source_id, sales_id, tags[], background, created_at,
--                custom_values },
--     deal: { external_id, name, stage_id, source_id, service_id, plan_amount,
--             paid_amount, sales_id, lost_reason_id, tags[], description, created_at,
--             custom_values } }
-- custom_values: { "<field id>": value } (19_custom_fields.sql); an existing
-- patient or deal only gets the fields it has no value for.
-- Dictionary ids are resolved by the wizard. Runs with the rights of the
-- caller (RLS applies); only the owner and the head import. While importing,
-- deals get no rule tasks, are not redistributed and skip stage checklists
-- (the crm.importing flag). A failing row is reported and the others go on.
CREATE OR REPLACE FUNCTION "public"."import_batch"("kind" "text", "rows" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  item jsonb;
  row_position integer;
  outcome jsonb;
  row_outcome text;
  result jsonb := jsonb_build_object(
    'created', 0, 'updated', 0, 'skipped', 0,
    'patients_created', 0, 'patients_updated', 0,
    'deals_created', 0, 'deals_updated', 0,
    'errors', '[]'::jsonb
  );
begin
  if org_id is null or private.current_user_role() not in ('owner', 'head') then
    raise exception 'Импорт доступен владельцу и руководителю клиники'
      using errcode = 'insufficient_privilege';
  end if;
  if kind is null or kind not in ('patients', 'deals') then
    raise exception 'Неизвестный вид импорта: %', kind using errcode = 'invalid_parameter_value';
  end if;
  if jsonb_typeof(rows) is distinct from 'array' then
    raise exception 'Ожидается массив строк' using errcode = 'invalid_parameter_value';
  end if;

  perform set_config('crm.importing', 'on', true);
  -- The audit log shows these changes as coming from the import
  perform set_config('crm.audit_source', 'import', true);
  -- Imported deals don't notify employees ("deal assigned to you")
  perform set_config('crm.notifications', 'off', true);
  for item, row_position in
    select e.value, e.ordinality::integer from jsonb_array_elements(rows) with ordinality as e
  loop
    begin
      outcome := private.import_row(org_id, kind, item);
      row_outcome := case
        when 'created' in (outcome ->> 'patient', outcome ->> 'deal') then 'created'
        when 'updated' in (outcome ->> 'patient', outcome ->> 'deal') then 'updated'
        else 'skipped'
      end;
      result := result || jsonb_build_object(row_outcome, (result ->> row_outcome)::integer + 1);
      if outcome ->> 'patient' in ('created', 'updated') then
        result := result || jsonb_build_object(
          'patients_' || (outcome ->> 'patient'),
          (result ->> ('patients_' || (outcome ->> 'patient')))::integer + 1);
      end if;
      if outcome ->> 'deal' in ('created', 'updated') then
        result := result || jsonb_build_object(
          'deals_' || (outcome ->> 'deal'),
          (result ->> ('deals_' || (outcome ->> 'deal')))::integer + 1);
      end if;
    exception when others then
      result := jsonb_set(result, '{errors}', (result -> 'errors') || jsonb_build_array(jsonb_build_object(
        'index', coalesce((item ->> 'index')::integer, row_position),
        'message', sqlerrm
      )));
    end;
  end loop;
  perform set_config('crm.importing', 'off', true);
  perform set_config('crm.audit_source', '', true);
  perform set_config('crm.notifications', '', true);
  return result;
end;
$$;

-- MIS connectors of the clinic, without their settings (secrets)
CREATE OR REPLACE FUNCTION "public"."integration_status"() RETURNS TABLE("kind" "text", "status" "text", "last_sync_at" timestamp with time zone, "last_error" "text")
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
  select i.kind, i.status, i.last_sync_at, i.last_error
  from public.integrations i
  where i.organization_id = private.current_organization_id()
  order by i.kind;
$$;

-- The owner or the head asks for a MIS connector ("Оставить заявку")
CREATE OR REPLACE FUNCTION "public"."request_integration"("integration_kind" "text") RETURNS "text"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  saved_status text;
begin
  if org_id is null or private.current_user_role() not in ('owner', 'head') then
    raise exception 'Заявку оставляет владелец или руководитель клиники'
      using errcode = 'insufficient_privilege';
  end if;
  insert into public.integrations (organization_id, kind)
  values (org_id, integration_kind)
  on conflict (organization_id, kind) do update set kind = excluded.kind
  returning status into saved_status;
  return saved_status;
end;
$$;

--
-- Triggers
--

create or replace trigger patient_deleted_external_refs
    after delete on public.patients
    for each row execute function private.delete_external_refs('patient');

create or replace trigger deal_deleted_external_refs
    after delete on public.deals
    for each row execute function private.delete_external_refs('deal');

--
-- Row Level Security
--

alter table public.external_refs enable row level security;
alter table public.integrations enable row level security;

-- External references: members read (a patient card may show its MIS id),
-- the owner and the head write them (imports). integrations has no policy:
-- its settings are secrets, only the service role (connectors) reads them.
create policy "Organization members can read" on public.external_refs for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Owner and head can insert" on public.external_refs for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can update" on public.external_refs for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head can delete" on public.external_refs for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

--
-- Grants
--

grant all on table public.external_refs to anon;
grant all on table public.external_refs to authenticated;
grant all on table public.external_refs to service_role;
grant all on sequence public.external_refs_id_seq to anon, authenticated, service_role;
revoke all on table public.integrations from anon, authenticated;
grant all on table public.integrations to service_role;
revoke all on sequence public.integrations_id_seq from anon, authenticated;
grant all on sequence public.integrations_id_seq to service_role;

revoke all on function private.delete_external_refs() from public;
grant execute on function private.delete_external_refs() to authenticated, service_role;
revoke all on function private.import_row(bigint, text, jsonb) from public;
grant execute on function private.import_row(bigint, text, jsonb) to authenticated, service_role;
revoke all on function public.import_batch(text, jsonb) from public, anon;
grant execute on function public.import_batch(text, jsonb) to authenticated, service_role;
revoke all on function public.integration_status() from public, anon;
grant execute on function public.integration_status() to authenticated, service_role;
revoke all on function public.request_integration(text) from public, anon;
grant execute on function public.request_integration(text) to authenticated, service_role;
