--
-- Doctors, consultation price, prepayments (stage 13)
--
-- The clinic owner wants the conversion of every doctor. A doctor is not a
-- CRM user: a name and a specialty in a dictionary of the clinic, edited by
-- the owner and the head (Settings → Doctors), read by everybody. An inactive
-- doctor is hidden from the pickers and stays on the old deals. There is no
-- schedule (docs/DECISIONS.md); a MIS integration will map doctors.id to its
-- own ids, so the ids never change and a doctor with deals cannot be deleted.
--
-- The prepayment is not a deal column: a payment has a kind (prepayment or
-- payment), the prepayment of a deal is the sum of its prepayments, and the
-- paid amount stays the sum of all its payments (deals.paid_amount).
--
-- public.deals_summary is declared here rather than in 03_views.sql: it shows
-- the doctor's name, and the schema files load in order. The report functions
-- (09_reports.sql) and the template variables (08_automessages.sql) that read
-- the new columns are plpgsql, whose bodies are resolved when they run.
--

create table public.doctors (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    specialty text,
    is_active boolean not null default true,
    position integer not null default 0,
    created_at timestamp with time zone not null default now(),
    constraint doctors_name_not_blank check (btrim(name) <> '')
);

-- The doctor of a deal and the price of the consultation, in tenge
alter table public.deals add column doctor_id bigint;
alter table public.deals add column consultation_amount bigint;
alter table public.deals add constraint deals_consultation_amount_positive check (consultation_amount >= 0);

-- A payment is a prepayment or a regular payment
alter table public.deal_payments add column kind text not null default 'payment';
alter table public.deal_payments add constraint deal_payments_kind_check check (kind in ('prepayment', 'payment'));

alter table public.doctors add constraint doctors_organization_id_id_key unique (organization_id, id);

alter table public.doctors
    add constraint doctors_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
-- Composite: a deal can only point at a doctor of its own clinic
alter table public.deals
    add constraint deals_doctor_id_fkey foreign key (organization_id, doctor_id) references public.doctors(organization_id, id);

create index doctors_organization_id_idx on public.doctors using btree (organization_id, position);
create index deals_doctor_id_idx on public.deals using btree (organization_id, doctor_id) where doctor_id is not null;

--
-- Views
--

-- Deals with what the board and the lists display
create or replace view public.deals_summary with (security_invoker = on) as
select
    d.id,
    d.organization_id,
    d.patient_id,
    d.pipeline_id,
    d.stage_id,
    d.name,
    d.source_id,
    d.service_id,
    d.plan_amount,
    d.paid_amount,
    d.sales_id,
    d.lost_reason_id,
    d.lost_comment,
    d.appointment_at,
    d.visit_at,
    d.tags,
    d.description,
    d.index,
    d.created_at,
    d.updated_at,
    d.stage_changed_at,
    d.closed_at,
    d.first_response_at,
    d.archived_at,
    s.kind as stage_kind,
    p.first_name as patient_first_name,
    p.last_name as patient_last_name,
    p.phones[1] as patient_phone,
    lower(concat_ws(' ', d.name, p.last_name, p.first_name, p.middle_name, array_to_string(p.phones, ' '))) as search_text,
    (
        select count(*)
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
    ) as nb_open_tasks,
    (
        select min(t.due_date)
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
    ) as next_task_due_at,
    (
        select count(*)
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id and m.direction = 'in' and m.read_at is null
    ) as nb_unread_messages,
    (
        select max(m.sent_at)
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id
    ) as last_message_at,
    (
        select m.text
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id
        order by m.sent_at desc, m.id desc
        limit 1
    ) as last_message_text,
    d.doctor_id,
    dr.name as doctor_name,
    d.consultation_amount,
    (
        select coalesce(sum(pay.amount), 0)::bigint
        from public.deal_payments pay
        where pay.organization_id = d.organization_id and pay.deal_id = d.id and pay.kind = 'prepayment'
    ) as prepayment_amount,
    -- Deal list (stage 21): the latest change or message, the nearest open task
    greatest(d.updated_at, (
        select max(m.sent_at)
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id
    )) as last_activity_at,
    (
        select t.text
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
        order by t.due_date, t.id
        limit 1
    ) as next_task_text
from public.deals d
    join public.stages s on s.id = d.stage_id
    join public.patients p on p.organization_id = d.organization_id and p.id = d.patient_id
    left join public.doctors dr on dr.organization_id = d.organization_id and dr.id = d.doctor_id;

--
-- Row Level Security
--

alter table public.doctors enable row level security;

-- A dictionary: every employee reads it (pickers), the owner and the head edit it
create policy "Organization members can read" on public.doctors for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Owner and head can insert" on public.doctors for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can update" on public.doctors for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head can delete" on public.doctors for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

--
-- Grants
--

grant all on table public.doctors to anon;
grant all on table public.doctors to authenticated;
grant all on table public.doctors to service_role;
grant all on sequence public.doctors_id_seq to anon, authenticated, service_role;

grant all on table public.deals_summary to anon;
grant all on table public.deals_summary to authenticated;
grant all on table public.deals_summary to service_role;
