--
-- Doctors, consultation price, prepayments (stage 13)
--
-- The clinic owner wants the conversion of every doctor. A doctor is not a
-- CRM user: a name and a specialty in a dictionary of the clinic, edited by
-- the owner and the head (Settings → Doctors), read by everybody. An inactive
-- doctor is hidden from the pickers and stays on the old deals. There is no
-- schedule (docs/DECISIONS.md); a MIS integration will map doctors.id to its
-- own ids, so the ids never change and a doctor with deals cannot be deleted.
--
-- The prepayment is not a deal column: a payment has a kind (prepayment or
-- payment), the prepayment of a deal is the sum of its prepayments, and the
-- paid amount stays the sum of all its payments (deals.paid_amount).
--
-- public.deals_summary shows the doctor's name; it is declared in
-- 19_custom_fields.sql, after the last columns it reads (schema files load in
-- order). The report functions
-- (09_reports.sql) and the template variables (08_automessages.sql) that read
-- the new columns are plpgsql, whose bodies are resolved when they run.
--

create table public.doctors (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    specialty text,
    is_active boolean not null default true,
    position integer not null default 0,
    created_at timestamp with time zone not null default now(),
    constraint doctors_name_not_blank check (btrim(name) <> '')
);

-- The doctor of a deal and the price of the consultation, in tenge
alter table public.deals add column doctor_id bigint;
alter table public.deals add column consultation_amount bigint;
alter table public.deals add constraint deals_consultation_amount_positive check (consultation_amount >= 0);

-- Stage 18 (18_unsorted_duplicates.sql): a new lead of a system channel
-- waiting in «Неразобранное» since this time. Declared here because
-- deals_summary below shows it.
alter table public.deals add column unsorted_at timestamp with time zone;

-- A payment is a prepayment or a regular payment
alter table public.deal_payments add column kind text not null default 'payment';
alter table public.deal_payments add constraint deal_payments_kind_check check (kind in ('prepayment', 'payment'));

alter table public.doctors add constraint doctors_organization_id_id_key unique (organization_id, id);

alter table public.doctors
    add constraint doctors_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
-- Composite: a deal can only point at a doctor of its own clinic
alter table public.deals
    add constraint deals_doctor_id_fkey foreign key (organization_id, doctor_id) references public.doctors(organization_id, id);

create index doctors_organization_id_idx on public.doctors using btree (organization_id, position);
create index deals_doctor_id_idx on public.deals using btree (organization_id, doctor_id) where doctor_id is not null;

--
-- Row Level Security
--

alter table public.doctors enable row level security;

-- A dictionary: every employee reads it (pickers), the owner and the head edit it
create policy "Organization members can read" on public.doctors for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Owner and head can insert" on public.doctors for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can update" on public.doctors for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head can delete" on public.doctors for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

--
-- Grants
--

grant all on table public.doctors to anon;
grant all on table public.doctors to authenticated;
grant all on table public.doctors to service_role;
grant all on sequence public.doctors_id_seq to anon, authenticated, service_role;

