--
-- Audit log (stage 15): who changed what and when, for the clinic managers.
--
-- public.audit_log gets one row per action: the employee (sales_id, null for
-- the system), the source ('user', 'automation', 'webhook', 'system', or what
-- the caller sets in crm.audit_source, e.g. 'import'), the entity and its id,
-- the action and the changed fields only, as { field: [before, after] } (the
-- format of deal_events.changes).
--
-- Deals keep their own log (public.deal_events, shown in the deal feed): a
-- trigger copies every new deal event here, so the diff of a deal is computed
-- once, in handle_deal_after_write. The other entities are logged by the
-- triggers of this file. Secrets (messenger API keys, webhook tokens) are
-- never copied: only the listed fields are.
--
-- Cascades are not logged row by row: a deleted deal takes its tasks and
-- payments, a deleted clinic takes everything, including its log. Rows
-- written by other triggers (tasks of the automation rules, responsible given
-- to the patient by the deal...) are logged with the source 'automation' and
-- no employee. The template of a new clinic is not logged.
--
-- Only the owner and the head read the log; nobody writes it but these
-- SECURITY DEFINER triggers (no insert, update or delete policy or grant).
--

create table public.audit_log (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    at timestamp with time zone not null default now(),
    sales_id bigint,
    source text not null default 'user',
    entity text not null,
    entity_id bigint,
    action text not null,
    changes jsonb not null default '{}'::jsonb,
    deal_id bigint,
    patient_id bigint
);

-- No foreign key to the logged rows: the log outlives deleted deals and
-- patients. The clinic's deletion removes its log.
alter table public.audit_log
    add constraint audit_log_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;

create index audit_log_at_idx on public.audit_log using btree (organization_id, at desc);
create index audit_log_entity_idx on public.audit_log using btree (organization_id, entity, entity_id);
create index audit_log_sales_id_idx on public.audit_log using btree (organization_id, sales_id, at desc);
create index audit_log_deal_id_idx on public.audit_log using btree (organization_id, deal_id) where deal_id is not null;
create index audit_log_patient_id_idx on public.audit_log using btree (organization_id, patient_id) where patient_id is not null;

-- Who acts: the signed-in employee; for the edge functions (service role),
-- the employee they act for (header x-crm-actor, only trusted from the
-- service role) or nobody. The source: crm.audit_source when a function sets
-- it, else header x-crm-source, else 'user', 'webhook' (service role without
-- an employee) or 'system'.
CREATE OR REPLACE FUNCTION "private"."audit_actor"("org_id" bigint, OUT "actor_id" bigint, OUT "actor_source" "text") RETURNS "record"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $_$
declare
  claims jsonb := coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb, '{}'::jsonb);
  headers jsonb;
  header_actor text;
begin
  if private.current_organization_id() = org_id then
    actor_id := private.current_sales_id();
  end if;
  actor_source := nullif(current_setting('crm.audit_source', true), '');
  if actor_id is null and claims ->> 'role' = 'service_role' then
    headers := coalesce(nullif(current_setting('request.headers', true), '')::jsonb, '{}'::jsonb);
    header_actor := headers ->> 'x-crm-actor';
    if header_actor ~ '^[0-9]{1,18}$' then
      select s.id into actor_id
      from public.sales s
      where s.id = header_actor::bigint and s.organization_id = org_id;
    end if;
    actor_source := coalesce(actor_source, nullif(headers ->> 'x-crm-source', ''));
    if actor_id is null then
      actor_source := coalesce(actor_source, 'webhook');
    end if;
  end if;
  actor_source := coalesce(actor_source, case when actor_id is not null then 'user' else 'system' end);
end;
$_$;

-- { field: [before, after] } of the fields that differ. A missing row (insert,
-- delete) only shows the fields that have a value.
CREATE OR REPLACE FUNCTION "private"."audit_diff"("old_row" "jsonb", "new_row" "jsonb", "fields" "text"[]) RETURNS "jsonb"
    LANGUAGE "plpgsql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
declare
  field text;
  before jsonb;
  after jsonb;
  changes jsonb := '{}'::jsonb;
begin
  foreach field in array fields loop
    -- Custom fields (19_custom_fields.sql): one entry per field, "cf:<id>"
    if field = 'custom_values' then
      changes := changes || private.custom_values_diff(old_row -> field, new_row -> field);
      continue;
    end if;
    before := nullif(old_row -> field, 'null'::jsonb);
    after := nullif(new_row -> field, 'null'::jsonb);
    if old_row is null and after = '[]'::jsonb then
      after := null;
    end if;
    if new_row is null and before = '[]'::jsonb then
      before := null;
    end if;
    if before is distinct from after then
      changes := changes || jsonb_build_object(field, jsonb_build_array(before, after));
    end if;
  end loop;
  return changes;
end;
$$;

-- Generic row log. Arguments: the entity name, then its logged fields
-- (comma-separated). Patients, tasks, payments, deletion of deals, settings.
CREATE OR REPLACE FUNCTION "private"."audit_row"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  entity_name text := tg_argv[0];
  fields text[] := string_to_array(tg_argv[1], ',');
  old_row jsonb := case when tg_op <> 'INSERT' then to_jsonb(old) end;
  new_row jsonb := case when tg_op <> 'DELETE' then to_jsonb(new) end;
  row_data jsonb := coalesce(new_row, old_row);
  org_id bigint := (row_data ->> 'organization_id')::bigint;
  diff jsonb;
  row_action text;
  row_deal_id bigint;
  row_patient_id bigint;
  actor record;
begin
  -- Cascades, and settings written by other code (template of a new clinic)
  if pg_trigger_depth() > 1
    and (tg_op = 'DELETE' or entity_name in ('pipeline', 'stage', 'task_rule', 'checklist_item', 'settings'))
  then
    return null;
  end if;
  -- A row deleted with its parent (deal of a deleted patient, task of a
  -- deleted deal, stage of a deleted pipeline, anything of a deleted clinic):
  -- only the parent's deletion is logged
  if tg_op = 'DELETE' and (
    not exists (select 1 from public.organizations o where o.id = org_id)
    or (entity_name in ('task', 'payment') and not exists (
      select 1 from public.deals d where d.organization_id = org_id and d.id = (row_data ->> 'deal_id')::bigint))
    or (entity_name = 'deal' and not exists (
      select 1 from public.patients p where p.organization_id = org_id and p.id = (row_data ->> 'patient_id')::bigint))
    or (entity_name = 'stage' and not exists (
      select 1 from public.pipelines p where p.id = (row_data ->> 'pipeline_id')::bigint))
    or (entity_name in ('checklist_item', 'task_rule') and row_data ->> 'stage_id' is not null and not exists (
      select 1 from public.stages s where s.id = (row_data ->> 'stage_id')::bigint))
  ) then
    return null;
  end if;

  diff := private.audit_diff(old_row, new_row, fields);
  if tg_op = 'UPDATE' and diff = '{}'::jsonb then
    return null;
  end if;

  row_action := case tg_op when 'INSERT' then 'create' when 'DELETE' then 'delete' else 'update' end;
  if entity_name = 'task' and tg_op = 'UPDATE' then
    if diff ? 'done_date' then
      row_action := case when new_row ->> 'done_date' is null then 'reopen' else 'complete' end;
    elsif diff ? 'sales_id' and (select count(*) from jsonb_object_keys(diff)) = 1 then
      row_action := 'reassign';
    end if;
  end if;

  if entity_name = 'patient' then
    row_patient_id := (row_data ->> 'id')::bigint;
  elsif entity_name = 'deal' then
    row_deal_id := (row_data ->> 'id')::bigint;
    row_patient_id := (row_data ->> 'patient_id')::bigint;
  elsif row_data ? 'deal_id' then
    row_deal_id := (row_data ->> 'deal_id')::bigint;
    select d.patient_id into row_patient_id
    from public.deals d
    where d.organization_id = org_id and d.id = row_deal_id;
  end if;

  select * into actor from private.audit_actor(org_id);
  if pg_trigger_depth() > 1 then
    actor.actor_id := null;
    actor.actor_source := 'automation';
  end if;

  insert into public.audit_log (organization_id, sales_id, source, entity, entity_id, action, changes, deal_id, patient_id)
  values (org_id, actor.actor_id, actor.actor_source, entity_name, (row_data ->> 'id')::bigint,
    row_action, diff, row_deal_id, row_patient_id);
  return null;
end;
$$;

-- Deals: a copy of every deal event (creation, stage change, edit)
CREATE OR REPLACE FUNCTION "private"."audit_deal_event"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  deal public.deals;
  diff jsonb := coalesce(new.changes, '{}'::jsonb);
  event_action text;
  actor record;
begin
  select * into deal from public.deals d
  where d.organization_id = new.organization_id and d.id = new.deal_id;

  if new.type = 'created' then
    event_action := 'create';
    diff := private.audit_diff(null, to_jsonb(deal),
      array['name', 'pipeline_id', 'stage_id', 'sales_id', 'source_id', 'service_id', 'plan_amount', 'custom_values']);
    if diff -> 'plan_amount' ->> 1 = '0' then
      diff := diff - 'plan_amount';
    end if;
  elsif new.type = 'stage_changed' then
    event_action := 'stage_change';
    diff := jsonb_build_object('stage_id', jsonb_build_array(new.from_stage_id, new.to_stage_id)) || diff;
  elsif diff ? 'archived_at' then
    event_action := case when diff -> 'archived_at' ->> 1 is null then 'unarchive' else 'archive' end;
  else
    event_action := 'update';
  end if;

  select * into actor from private.audit_actor(new.organization_id);
  actor.actor_id := coalesce(new.sales_id, actor.actor_id);
  -- The deal changed by another trigger (payments total, first answer)
  if pg_trigger_depth() > 2 then
    actor.actor_id := null;
    actor.actor_source := 'automation';
  elsif new.sales_id is not null and actor.actor_source in ('system', 'webhook') then
    actor.actor_source := 'user';
  end if;

  insert into public.audit_log (organization_id, at, sales_id, source, entity, entity_id, action, changes, deal_id, patient_id)
  values (new.organization_id, new.created_at, actor.actor_id, actor.actor_source, 'deal', new.deal_id,
    event_action, diff, new.deal_id, deal.patient_id);
  return null;
end;
$$;

-- Employees: invitation (sign-up for the owner), role change, disabling,
-- name or email change. An invitation comes from the auth trigger: the users
-- edge function puts the inviting employee in app_metadata.invited_by.
CREATE OR REPLACE FUNCTION "private"."audit_employee"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $_$
declare
  diff jsonb;
  row_action text;
  actor record;
  invited_by text;
begin
  diff := private.audit_diff(
    case when tg_op = 'UPDATE' then to_jsonb(old) end,
    to_jsonb(new),
    array['first_name', 'last_name', 'email', 'role', 'disabled']
  );
  if tg_op = 'INSERT' then
    diff := diff - 'disabled';
    row_action := case when new.role = 'owner' then 'create' else 'invite' end;
  elsif diff = '{}'::jsonb then
    return null;
  elsif diff ? 'disabled' then
    row_action := case when new.disabled then 'disable' else 'enable' end;
  elsif diff ? 'role' then
    row_action := 'role_change';
  else
    row_action := 'update';
  end if;

  select * into actor from private.audit_actor(new.organization_id);
  if tg_op = 'INSERT' and actor.actor_id is null then
    if new.role = 'owner' then
      actor.actor_id := new.id;
    else
      select u.raw_app_meta_data ->> 'invited_by' into invited_by
      from auth.users u where u.id = new.user_id;
      if invited_by ~ '^[0-9]{1,18}$' then
        select s.id into actor.actor_id
        from public.sales s
        where s.id = invited_by::bigint and s.organization_id = new.organization_id;
      end if;
    end if;
    if actor.actor_id is not null then
      actor.actor_source := 'user';
    end if;
  end if;

  insert into public.audit_log (organization_id, sales_id, source, entity, entity_id, action, changes)
  values (new.organization_id, actor.actor_id, actor.actor_source, 'employee', new.id, row_action, diff);
  return null;
end;
$_$;

-- Messengers: connection and disconnection only. The API key and the
-- webhook token are secrets and never reach the log.
CREATE OR REPLACE FUNCTION "private"."audit_messenger"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  was_connected boolean := false;
  is_connected boolean := new.api_key is not null;
  actor record;
begin
  if tg_op = 'UPDATE' then
    was_connected := old.api_key is not null;
  end if;
  if was_connected = is_connected then
    return null;
  end if;
  select * into actor from private.audit_actor(new.organization_id);
  insert into public.audit_log (organization_id, sales_id, source, entity, action, changes)
  values (new.organization_id, actor.actor_id, actor.actor_source, 'messenger',
    case when is_connected then 'connect' else 'disconnect' end,
    jsonb_build_object('provider', jsonb_build_array(null, new.provider),
      'connected', jsonb_build_array(was_connected, is_connected)));
  return null;
end;
$$;

--
-- Triggers
--

create or replace trigger audit_deal_event
    after insert on public.deal_events
    for each row execute function private.audit_deal_event();

create or replace trigger audit_deal_deleted
    after delete on public.deals
    for each row execute function private.audit_row('deal', 'name,patient_id,pipeline_id,stage_id,sales_id,plan_amount');

create or replace trigger audit_patient
    after insert or update or delete on public.patients
    for each row execute function private.audit_row('patient', 'last_name,first_name,middle_name,phones,sales_id,tags,custom_values');

create or replace trigger audit_deal_payment
    after insert or update or delete on public.deal_payments
    for each row execute function private.audit_row('payment', 'amount,paid_at,comment');

create or replace trigger audit_task
    after insert or update or delete on public.tasks
    for each row execute function private.audit_row('task', 'type,text,due_date,duration_minutes,done_date,result,sales_id');

create or replace trigger audit_employee
    after insert or update on public.sales
    for each row execute function private.audit_employee();

create or replace trigger audit_pipeline
    after insert or update or delete on public.pipelines
    for each row execute function private.audit_row('pipeline', 'name,is_default');

create or replace trigger audit_stage
    after insert or update or delete on public.stages
    for each row execute function private.audit_row('stage', 'pipeline_id,name,kind,position');

create or replace trigger audit_settings
    after update on public.organization_settings
    for each row execute function private.audit_row('settings', 'manager_deal_visibility,pipeline_move_mode,lead_distribution,lead_distribution_sales_ids,unsorted_enabled,unsorted_source_ids');

create or replace trigger audit_task_rule
    after insert or update or delete on public.task_rules
    for each row execute function private.audit_row('task_rule', 'event,stage_id,type,text,due_in_minutes,is_active');

create or replace trigger audit_checklist_item
    after insert or update or delete on public.stage_checklist_items
    for each row execute function private.audit_row('checklist_item', 'stage_id,text');

create or replace trigger audit_messenger
    after insert or update on public.messenger_integrations
    for each row execute function private.audit_messenger();

--
-- Reading: owner and head only, with the deal and patient names
--

create or replace view public.audit_log_summary with (security_invoker = on) as
select
    a.id,
    a.organization_id,
    a.at,
    a.sales_id,
    a.source,
    a.entity,
    a.entity_id,
    a.action,
    a.changes,
    a.deal_id,
    a.patient_id,
    d.name as deal_name,
    nullif(btrim(concat_ws(' ', p.last_name, p.first_name)), '') as patient_name,
    lower(concat_ws(' ',
        d.name, p.last_name, p.first_name, p.middle_name, array_to_string(p.phones, ' '),
        a.changes -> 'name' ->> 0, a.changes -> 'name' ->> 1,
        a.changes -> 'last_name' ->> 0, a.changes -> 'first_name' ->> 0
    )) as search_text
from public.audit_log a
    left join public.deals d on d.organization_id = a.organization_id and d.id = a.deal_id
    left join public.patients p on p.organization_id = a.organization_id and p.id = a.patient_id;

alter table public.audit_log enable row level security;

create policy "Owner and head can read" on public.audit_log for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

--
-- Grants: read only, and only through RLS
--

revoke all on table public.audit_log from anon, authenticated, service_role;
grant select on table public.audit_log to authenticated;
grant select on table public.audit_log to service_role;
revoke all on sequence public.audit_log_id_seq from anon, authenticated, service_role;

revoke all on table public.audit_log_summary from anon, authenticated, service_role;
grant select on table public.audit_log_summary to authenticated;
grant select on table public.audit_log_summary to service_role;

revoke all on function private.audit_actor(bigint) from public;
grant execute on function private.audit_actor(bigint) to service_role;
revoke all on function private.audit_diff(jsonb, jsonb, text[]) from public;
grant execute on function private.audit_diff(jsonb, jsonb, text[]) to service_role;
revoke all on function private.audit_row() from public;
grant execute on function private.audit_row() to service_role;
revoke all on function private.audit_deal_event() from public;
grant execute on function private.audit_deal_event() to service_role;
revoke all on function private.audit_employee() from public;
grant execute on function private.audit_employee() to service_role;
revoke all on function private.audit_messenger() from public;
grant execute on function private.audit_messenger() to service_role;
