--
-- Custom fields (stage 19): «Дополнительные поля» of deals and patients, as
-- in amoCRM.
--
-- public.custom_fields holds the definitions of a clinic, per entity (deal or
-- patient): name, type, options of the lists, required flag, order, active
-- flag, and for the deals whether the kanban card shows the field (two at
-- most). The owner and the head edit them (Settings → Поля), every employee
-- reads them. An archived field (is_active = false) is hidden, its values
-- stay. Name, entity and type identify a field for the templates
-- ({поле:Название}), the import and the CSV export: the name is unique in the
-- entity, the type and the entity never change.
--
-- The values live in deals.custom_values and patients.custom_values, a jsonb
-- object keyed by the field id: { "12": "Инстаграм", "15": true }.
--   text, textarea, phone, url, select, date ("YYYY-MM-DD"),
--   datetime (ISO, UTC)       → a string
--   number, money (tenge)     → a number (money: a whole number ≥ 0)
--   checkbox                  → true / false
--   multiselect               → an array of options, in the order of the list
-- An empty value is no key. The trigger private.handle_custom_values
-- normalizes the values that changed (private.custom_value), drops the keys of
-- unknown fields, keeps the values of archived fields as they were, and checks
-- the required fields. Same rules in the app: customFields/customFields.ts.
--
-- Required fields are checked when an employee saves (not the webhooks, the
-- automations, nor the import):
--   * a deal outside the first stage of its pipeline (like amoCRM, a new lead
--     can come in empty) and not refused — when it is created there, moves to
--     another stage or its custom fields change;
--   * a patient — when its custom fields change (the quick creation of a
--     patient from a deal and the incoming requests are not blocked).
-- A required checkbox must be ticked.
--
-- deals_summary and patients_summary are declared here: they show the values,
-- and the columns are added by this file. The functions of earlier files that
-- read the values (deal log, audit diff, template variables, import) are
-- plpgsql, whose bodies are resolved when they run.
--

create table public.custom_fields (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    entity text not null,
    name text not null,
    type text not null,
    options jsonb not null default '[]'::jsonb,
    required boolean not null default false,
    position integer not null default 0,
    is_active boolean not null default true,
    show_on_card boolean not null default false,
    created_at timestamp with time zone not null default now(),
    constraint custom_fields_entity_check check (entity in ('deal', 'patient')),
    constraint custom_fields_type_check check (type in (
        'text', 'textarea', 'number', 'money', 'date', 'datetime',
        'checkbox', 'select', 'multiselect', 'phone', 'url'
    )),
    constraint custom_fields_name_not_blank check (btrim(name) <> ''),
    -- {поле:Название} of the templates
    constraint custom_fields_name_no_braces check (name !~ '[{}]'),
    constraint custom_fields_options_array check (jsonb_typeof(options) = 'array'),
    constraint custom_fields_card_deal_only check (not show_on_card or entity = 'deal')
);

alter table public.custom_fields add constraint custom_fields_organization_id_id_key unique (organization_id, id);

alter table public.custom_fields
    add constraint custom_fields_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;

create index custom_fields_organization_id_idx on public.custom_fields using btree (organization_id, entity, position);
create unique index custom_fields_name_key on public.custom_fields using btree (organization_id, entity, lower(name));

-- The values, keyed by field id
alter table public.deals add column custom_values jsonb not null default '{}'::jsonb;
alter table public.deals add constraint deals_custom_values_object check (jsonb_typeof(custom_values) = 'object');
alter table public.patients add column custom_values jsonb not null default '{}'::jsonb;
alter table public.patients add constraint patients_custom_values_object check (jsonb_typeof(custom_values) = 'object');

-- Filters of the lists: custom_values @> '{"12": "Инстаграм"}'
create index deals_custom_values_idx on public.deals using gin (custom_values jsonb_path_ops);
create index patients_custom_values_idx on public.patients using gin (custom_values jsonb_path_ops);

--
-- Functions
--

-- A value checked and normalized for its field (null: empty). Raises
-- «Поле «…»: ожидается …» (hint custom_field_invalid). Same as
-- normalizeCustomValue() in the app.
CREATE OR REPLACE FUNCTION "private"."custom_value"("field" "public"."custom_fields", "value" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $_$
declare
  value_kind text := jsonb_typeof(value);
  raw text;
  amount numeric;
  day date;
  moment timestamp with time zone;
  phone text;
  chosen text[] := array[]::text[];
  item jsonb;
  canonical text;
  failed boolean := false;
begin
  if value is null or value_kind = 'null' then
    return null;
  end if;

  if field.type = 'checkbox' then
    if value_kind = 'boolean' then
      return value;
    end if;
    if value_kind in ('string', 'number') then
      raw := lower(btrim(value #>> '{}'));
      if raw = '' then
        return null;
      elsif raw in ('true', '1', 'да', 'yes', '+') then
        return 'true'::jsonb;
      elsif raw in ('false', '0', 'нет', 'no', '-') then
        return 'false'::jsonb;
      end if;
    end if;
    failed := true;
  elsif field.type = 'multiselect' then
    if value_kind = 'string' then
      value := jsonb_build_array(value);
    elsif value_kind <> 'array' then
      failed := true;
    end if;
    if not failed then
      for item in select e.value from jsonb_array_elements(value) as e loop
        if jsonb_typeof(item) <> 'string' then
          failed := true;
          exit;
        end if;
        raw := btrim(item #>> '{}');
        continue when raw = '';
        select o.value into canonical
        from jsonb_array_elements_text(field.options) as o
        where lower(btrim(o.value)) = lower(raw)
        limit 1;
        if canonical is null then
          failed := true;
          exit;
        end if;
        chosen := chosen || canonical;
      end loop;
    end if;
    if not failed then
      if cardinality(chosen) = 0 then
        return null;
      end if;
      -- In the order of the list, each option once
      return (
        select jsonb_agg(o.value order by o.ordinality)
        from jsonb_array_elements_text(field.options) with ordinality as o
        where o.value = any(chosen)
      );
    end if;
  elsif value_kind not in ('string', 'number') then
    failed := true;
  else
    raw := btrim(value #>> '{}');
    if raw = '' then
      return null;
    end if;
    case field.type
      when 'text' then
        if length(raw) <= 1000 then
          return to_jsonb(raw);
        end if;
        failed := true;
      when 'textarea' then
        if length(raw) <= 10000 then
          return to_jsonb(raw);
        end if;
        failed := true;
      when 'number', 'money' then
        if value_kind = 'string' then
          raw := replace(regexp_replace(raw, '[\s\u00a0₸]|тг\.?|тенге', '', 'gi'), ',', '.');
        end if;
        if raw ~ '^-?\d{1,15}(\.\d{1,6})?$' then
          amount := raw::numeric;
          if field.type = 'number' then
            return to_jsonb(trim_scale(amount));
          elsif amount >= 0 then
            return to_jsonb(round(amount)::bigint);
          end if;
        end if;
        failed := true;
      when 'date' then
        if raw ~ '^\d{4}-\d{2}-\d{2}$' then
          begin
            day := raw::date;
            return to_jsonb(to_char(day, 'YYYY-MM-DD'));
          exception when others then
            failed := true;
          end;
        end if;
        failed := true;
      when 'datetime' then
        -- A moment with its time zone, as the app sends it (toISOString)
        if raw ~ '^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}(:\d{2}(\.\d{1,6})?)?(Z|[+-]\d{2}(:?\d{2})?)$' then
          begin
            moment := raw::timestamp with time zone;
            return to_jsonb(to_char(moment at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'));
          exception when others then
            failed := true;
          end;
        end if;
        failed := true;
      when 'select' then
        select o.value into canonical
        from jsonb_array_elements_text(field.options) as o
        where lower(btrim(o.value)) = lower(raw)
        limit 1;
        if canonical is not null then
          return to_jsonb(canonical);
        end if;
        failed := true;
      when 'phone' then
        phone := private.normalize_phone(raw);
        if phone ~ '^\+7\d{10}$' or (phone !~ '^\+7' and phone ~ '^\+\d{11,15}$') then
          return to_jsonb(phone);
        end if;
        failed := true;
      when 'url' then
        if raw !~* '^[a-z][a-z0-9+.-]*://' then
          raw := 'https://' || raw;
        end if;
        if length(raw) <= 2000 and raw ~* '^https?://[^\s/]+\.[^\s]+$' then
          return to_jsonb(raw);
        end if;
        failed := true;
      else
        failed := true;
    end case;
  end if;

  raise exception 'Поле «%»: ожидается %', field.name, case field.type
      when 'text' then 'текст до 1000 символов'
      when 'textarea' then 'текст до 10 000 символов'
      when 'number' then 'число'
      when 'money' then 'сумма в тенге'
      when 'date' then 'дата'
      when 'datetime' then 'дата и время'
      when 'checkbox' then 'да или нет'
      when 'select' then 'значение из списка'
      when 'multiselect' then 'значения из списка'
      when 'phone' then 'номер телефона'
      when 'url' then 'ссылка'
      else 'другое значение'
    end
    using errcode = 'check_violation', hint = 'custom_field_invalid';
end;
$_$;

-- { "cf:<field id>": [before, after] } of the values that differ: the deal
-- log (deal_events.changes) and the audit log show one line per field
CREATE OR REPLACE FUNCTION "private"."custom_values_diff"("before" "jsonb", "after" "jsonb") RETURNS "jsonb"
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select coalesce(jsonb_object_agg('cf:' || k.key, jsonb_build_array(v.b -> k.key, v.a -> k.key)), '{}'::jsonb)
  from (
    select
      case when jsonb_typeof(before) = 'object' then before else '{}'::jsonb end as b,
      case when jsonb_typeof(after) = 'object' then after else '{}'::jsonb end as a
  ) as v,
  lateral (
    select jsonb_object_keys(v.b) as key
    union
    select jsonb_object_keys(v.a)
  ) as k
  where (v.b -> k.key) is distinct from (v.a -> k.key)
$$;

-- A value as a patient reads it in a message: «150 000 ₸», «12.03.2026»,
-- «12 марта в 14:30», «да». Same as customFieldText() in the app.
CREATE OR REPLACE FUNCTION "private"."custom_field_text"("field_type" "text", "value" "jsonb", "time_zone" "text") RETURNS "text"
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $_$
begin
  if value is null or jsonb_typeof(value) = 'null' then
    return null;
  end if;
  if field_type = 'checkbox' then
    return case when value = 'true'::jsonb then 'да' else 'нет' end;
  end if;
  if jsonb_typeof(value) = 'array' then
    return nullif((
      select string_agg(e.value, ', ' order by e.ordinality)
      from jsonb_array_elements_text(value) with ordinality as e
    ), '');
  end if;
  begin
    if field_type = 'money' then
      return regexp_replace(round((value #>> '{}')::numeric)::text, '(\d)(?=(\d\d\d)+$)', '\1 ', 'g') || ' ₸';
    elsif field_type = 'date' then
      return to_char((value #>> '{}')::date, 'DD.MM.YYYY');
    elsif field_type = 'datetime' then
      return private.format_visit_date((value #>> '{}')::timestamp with time zone, time_zone);
    end if;
  exception when others then
    return value #>> '{}';
  end;
  return value #>> '{}';
end;
$_$;

-- Template variables {поле:Название} of the fields of an entity (archived
-- fields too: their values stay). A field without a value gives an empty text.
CREATE OR REPLACE FUNCTION "private"."custom_field_vars"("org_id" bigint, "field_entity" "text", "field_values" "jsonb", "time_zone" "text") RETURNS "jsonb"
    LANGUAGE "sql" STABLE
    SET "search_path" TO ''
    AS $$
  select coalesce(
    jsonb_object_agg('поле:' || f.name, private.custom_field_text(f.type, field_values -> f.id::text, time_zone)),
    '{}'::jsonb
  )
  from public.custom_fields f
  where f.organization_id = org_id and f.entity = field_entity
$$;

-- Definitions: trimmed name, clean list of options, type and entity fixed,
-- at most two fields on the kanban card
CREATE OR REPLACE FUNCTION "private"."handle_custom_field_write"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
begin
  new.name := btrim(new.name);
  if tg_op = 'UPDATE' then
    if new.entity is distinct from old.entity or new.type is distinct from old.type then
      raise exception 'Тип поля изменить нельзя: создайте новое поле'
        using errcode = 'check_violation', hint = 'custom_field_type_locked';
    end if;
    new.organization_id := old.organization_id;
    new.created_at := old.created_at;
  end if;

  if new.type in ('select', 'multiselect') then
    if jsonb_typeof(new.options) is distinct from 'array' then
      new.options := '[]'::jsonb;
    end if;
    -- Trimmed, without blanks and duplicates (whatever the case), in order
    new.options := coalesce((
      select jsonb_agg(o.value order by o.first_position)
      from (
        select distinct on (lower(t.value)) t.value, t.ordinality as first_position
        from (
          select btrim(e.item #>> '{}') as value, e.ordinality
          from jsonb_array_elements(new.options) with ordinality as e(item, ordinality)
          where jsonb_typeof(e.item) in ('string', 'number')
        ) as t
        where t.value <> ''
        order by lower(t.value), t.ordinality
      ) as o
    ), '[]'::jsonb);
    if jsonb_array_length(new.options) = 0 then
      raise exception 'Добавьте варианты списка'
        using errcode = 'check_violation', hint = 'custom_field_options_required';
    end if;
  else
    new.options := '[]'::jsonb;
  end if;

  -- An archived field leaves the card
  if not new.is_active or new.entity <> 'deal' then
    new.show_on_card := false;
  end if;
  if new.show_on_card and (tg_op = 'INSERT' or not old.show_on_card) and (
    select count(*) from public.custom_fields f
    where f.organization_id = new.organization_id and f.show_on_card and f.id <> new.id
  ) >= 2 then
    raise exception 'На карточке канбана можно показать не больше двух полей'
      using errcode = 'check_violation', hint = 'custom_field_card_limit';
  end if;
  return new;
end;
$$;

-- Values of a deal or a patient (argument: 'deal' or 'patient'). SECURITY
-- DEFINER: webhooks and automations write deals without reading rights.
CREATE OR REPLACE FUNCTION "private"."handle_custom_values"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  entity_name text := tg_argv[0];
  old_values jsonb := '{}'::jsonb;
  new_values jsonb := coalesce(new.custom_values, '{}'::jsonb);
  result jsonb := '{}'::jsonb;
  field public.custom_fields;
  field_key text;
  normalized jsonb;
  stage_changed boolean := false;
  check_required boolean;
  stage_kind text;
  first_stage_id bigint;
  missing text;
  viewer_org bigint := private.current_organization_id();
begin
  if tg_op = 'UPDATE' then
    old_values := coalesce(old.custom_values, '{}'::jsonb);
    if entity_name = 'deal' then
      stage_changed := new.stage_id is distinct from old.stage_id
        or new.pipeline_id is distinct from old.pipeline_id;
    end if;
    if new_values = old_values and not stage_changed then
      return new;
    end if;
  end if;
  if jsonb_typeof(new_values) is distinct from 'object' then
    raise exception 'Дополнительные поля: ожидается объект'
      using errcode = 'check_violation', hint = 'custom_field_invalid';
  end if;
  -- A row of another clinic: RLS refuses it, don't tell anything about it
  if viewer_org is not null and viewer_org is distinct from new.organization_id then
    return new;
  end if;

  if new_values is distinct from old_values then
    for field in
      select * from public.custom_fields f
      where f.organization_id = new.organization_id and f.entity = entity_name
    loop
      field_key := field.id::text;
      if not field.is_active then
        -- Archived: the stored value stays as it was
        if old_values ? field_key then
          result := result || jsonb_build_object(field_key, old_values -> field_key);
        end if;
      elsif new_values ? field_key then
        if old_values -> field_key = new_values -> field_key then
          -- Unchanged values are kept as stored (an option removed since)
          result := result || jsonb_build_object(field_key, new_values -> field_key);
        else
          normalized := private.custom_value(field, new_values -> field_key);
          if normalized is not null then
            result := result || jsonb_build_object(field_key, normalized);
          end if;
        end if;
      end if;
    end loop;
    -- Keys of unknown fields are dropped
    new.custom_values := result;
  end if;

  -- Required fields: employees only, not while importing
  if private.current_sales_id() is null or current_setting('crm.importing', true) = 'on' then
    return new;
  end if;
  if entity_name = 'deal' then
    select s.kind into stage_kind from public.stages s where s.id = new.stage_id;
    select s.id into first_stage_id
    from public.stages s
    where s.pipeline_id = new.pipeline_id
    order by s.position, s.id
    limit 1;
    check_required := stage_kind is distinct from 'lost'
      and new.stage_id is distinct from first_stage_id
      and (tg_op = 'INSERT' or stage_changed or new.custom_values is distinct from old_values);
  else
    check_required := new.custom_values is distinct from old_values;
  end if;
  if check_required then
    select f.name into missing
    from public.custom_fields f
    where f.organization_id = new.organization_id and f.entity = entity_name
      and f.is_active and f.required
      and case
        when f.type = 'checkbox' then (new.custom_values -> f.id::text) is distinct from 'true'::jsonb
        else not (new.custom_values ? f.id::text)
      end
    order by f.position, f.id
    limit 1;
    if missing is not null then
      raise exception 'Заполните поле «%»', missing
        using errcode = 'check_violation', hint = 'custom_field_required';
    end if;
  end if;
  return new;
end;
$$;

--
-- Views
--

-- Deals with what the board and the lists display (redefined with the UTM
-- tags at the end in 32_marketing.sql)
create or replace view public.deals_summary with (security_invoker = on) as
select
    d.id,
    d.organization_id,
    d.patient_id,
    d.pipeline_id,
    d.stage_id,
    d.name,
    d.source_id,
    d.service_id,
    d.plan_amount,
    d.paid_amount,
    d.sales_id,
    d.lost_reason_id,
    d.lost_comment,
    d.appointment_at,
    d.visit_at,
    d.tags,
    d.description,
    d.index,
    d.created_at,
    d.updated_at,
    d.stage_changed_at,
    d.closed_at,
    d.first_response_at,
    d.archived_at,
    s.kind as stage_kind,
    p.first_name as patient_first_name,
    p.last_name as patient_last_name,
    p.phones[1] as patient_phone,
    lower(concat_ws(' ', d.name, p.last_name, p.first_name, p.middle_name, array_to_string(p.phones, ' '))) as search_text,
    (
        select count(*)
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
    ) as nb_open_tasks,
    (
        select min(t.due_date)
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
    ) as next_task_due_at,
    (
        select count(*)
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id and m.direction = 'in' and m.read_at is null
    ) as nb_unread_messages,
    (
        select max(m.sent_at)
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id
    ) as last_message_at,
    (
        select m.text
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id
        order by m.sent_at desc, m.id desc
        limit 1
    ) as last_message_text,
    d.doctor_id,
    dr.name as doctor_name,
    d.consultation_amount,
    (
        select coalesce(sum(pay.amount), 0)::bigint
        from public.deal_payments pay
        where pay.organization_id = d.organization_id and pay.deal_id = d.id and pay.kind = 'prepayment'
    ) as prepayment_amount,
    d.unsorted_at,
    d.custom_values,
    -- Deal list (stage 21): the latest change or message, the nearest open task
    greatest(d.updated_at, (
        select max(m.sent_at)
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id
    )) as last_activity_at,
    (
        select t.text
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
        order by t.due_date, t.id
        limit 1
    ) as next_task_text
from public.deals d
    join public.stages s on s.id = d.stage_id
    join public.patients p on p.organization_id = d.organization_id and p.id = d.patient_id
    left join public.doctors dr on dr.organization_id = d.organization_id and dr.id = d.doctor_id;

-- Redefined with the columns of the light patient card in 29_treatment_plans.sql
create or replace view public.patients_summary with (security_invoker = on) as
select
    p.id,
    p.organization_id,
    p.first_name,
    p.last_name,
    p.middle_name,
    p.phone_jsonb,
    p.phones,
    p.birth_date,
    p.city,
    p.whatsapp,
    p.instagram,
    p.telegram,
    p.source_id,
    p.tags,
    p.sales_id,
    p.gender,
    p.avatar,
    p.background,
    p.status,
    p.first_seen,
    p.last_seen,
    array_to_string(p.phones, ' ') as phone_fts,
    (
        select count(*)
        from public.deals d
        where d.organization_id = p.organization_id and d.patient_id = p.id
    ) as nb_deals,
    (
        select count(*)
        from public.deals d
            join public.stages s on s.id = d.stage_id
        where d.organization_id = p.organization_id and d.patient_id = p.id and s.kind = 'open'
    ) as nb_open_deals,
    (
        select count(*)
        from public.tasks t
            join public.deals d on d.organization_id = t.organization_id and d.id = t.deal_id
        where d.organization_id = p.organization_id and d.patient_id = p.id and t.done_date is null
    ) as nb_tasks,
    p.custom_values
from public.patients p;

--
-- Triggers
--

create or replace trigger custom_field_write
    before insert or update on public.custom_fields
    for each row execute function private.handle_custom_field_write();

-- After deal_before_write (alphabetical order): the stage is final
create or replace trigger deal_custom_values
    before insert or update on public.deals
    for each row execute function private.handle_custom_values('deal');

create or replace trigger patient_custom_values
    before insert or update on public.patients
    for each row execute function private.handle_custom_values('patient');

create or replace trigger audit_custom_field
    after insert or update or delete on public.custom_fields
    for each row execute function private.audit_row('custom_field', 'entity,name,type,options,required,is_active,show_on_card');

--
-- Row Level Security
--

alter table public.custom_fields enable row level security;

-- Every employee reads the definitions (forms, cards, filters); the owner and
-- the head edit them
create policy "Organization members can read" on public.custom_fields for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Owner and head can insert" on public.custom_fields for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can update" on public.custom_fields for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head can delete" on public.custom_fields for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

--
-- Grants
--

grant all on table public.custom_fields to anon;
grant all on table public.custom_fields to authenticated;
grant all on table public.custom_fields to service_role;
grant all on sequence public.custom_fields_id_seq to anon, authenticated, service_role;

grant all on table public.deals_summary to anon;
grant all on table public.deals_summary to authenticated;
grant all on table public.deals_summary to service_role;

grant all on table public.patients_summary to anon;
grant all on table public.patients_summary to authenticated;
grant all on table public.patients_summary to service_role;

revoke all on function private.custom_value(public.custom_fields, jsonb) from public;
grant execute on function private.custom_value(public.custom_fields, jsonb) to service_role;
revoke all on function private.custom_values_diff(jsonb, jsonb) from public;
grant execute on function private.custom_values_diff(jsonb, jsonb) to service_role;
revoke all on function private.custom_field_text(text, jsonb, text) from public;
grant execute on function private.custom_field_text(text, jsonb, text) to service_role;
revoke all on function private.custom_field_vars(bigint, text, jsonb, text) from public;
grant execute on function private.custom_field_vars(bigint, text, jsonb, text) to service_role;
revoke all on function private.handle_custom_field_write() from public;
grant execute on function private.handle_custom_field_write() to service_role;
revoke all on function private.handle_custom_values() from public;
grant execute on function private.handle_custom_values() to service_role;
