--
-- Digital pipeline, outgoing webhooks and the public REST API (stage 20)
--
-- Digital pipeline («Цифровая воронка», as in amoCRM): per stage, triggers
-- «when X happens to a deal of this stage (and it matches the conditions),
-- do Y». They sit next to the task rules (stage 5) and the auto-message
-- rules (stage 6), which keep their own tables; the settings screen shows
-- the three of them in one grid, stages as columns.
--   events     stage_entered, message_in, message_out, call_missed,
--              payment_added, appointment_set (immediate, run by the
--              triggers of this file) and idle, visit_passed (delayed, run by
--              pg_cron through private.stage_triggers_tick every 5 minutes)
--   conditions source, service, doctor, responsible (any of the chosen ids),
--              tags present / absent
--   actions    move_stage, set_responsible, add_tag, remove_tag, create_task,
--              send_template (stage 6 queue), send_webhook, set_field
-- Every run is written to public.stage_trigger_runs (the deal feed shows it)
-- and happens at most once per (trigger, deal, event instance): the unique
-- event_key. A chain of automatic actions is limited by the session variable
-- crm.automation_depth (at most 3 nested actions). Automatic changes are
-- audited with the source 'automation'. An action that fails (a move blocked
-- by the stage checklist, a refusal without reason...) is logged as skipped
-- or failed and never raised to the sender of the event (an inbound message
-- must be stored whatever happens). Imports (crm.importing) run nothing.
--
-- Outgoing webhooks: the owner and the head register URLs with the events
-- they want. The triggers of this file queue one delivery per webhook
-- (public.webhook_deliveries); the edge function webhooks_dispatch, started
-- every minute by pg_cron through pg_net (Vault secrets project_url and
-- automessages_dispatch_key, as for the auto-messages), takes them
-- (public.claim_webhook_deliveries), posts the JSON signed with HMAC-SHA256
-- (per-webhook secret) and reports back (public.complete_webhook_delivery):
-- retries with backoff, and after 10 failures in a row the webhook is
-- switched off with the error shown in the settings.
--
-- Public REST API: API keys (read, or read + write) created by the owner and
-- the head; only the SHA-256 of a key is stored, the key is shown once. The
-- edge function api (Authorization: Bearer <key>) calls the public.api_*
-- functions below (service role only): they resolve the clinic from the key
-- hash, check the scope and a per-key limit of requests per minute, and work
-- inside that clinic only.
--

--
-- Tables
--

-- Outgoing webhooks of the clinic. The secret signs the deliveries; only the
-- owner and the head read it.
create table public.webhooks (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text,
    url text not null,
    events text[] not null default '{}'::text[],
    secret text not null default replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', ''),
    is_active boolean not null default true,
    -- Failed attempts in a row; reaching 10 switches the webhook off
    failure_count integer not null default 0,
    last_error text,
    last_success_at timestamp with time zone,
    last_failure_at timestamp with time zone,
    -- Switched off by the dispatcher after too many failures
    disabled_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    constraint webhooks_url_check check (url ~ '^https?://[^/\s]+'),
    constraint webhooks_events_check check (events <@ array['deal.created', 'deal.stage_changed', 'deal.won', 'deal.lost',
        'patient.created', 'message.received', 'payment.added', 'task.completed']::text[])
);

-- The delivery queue. pending -> sending -> delivered | pending (retry, later)
-- | failed (too many attempts); pending -> cancelled (webhook switched off).
-- Events: those of webhooks.events, 'automation' (action of a stage trigger)
-- and 'ping' (test from the settings).
create table public.webhook_deliveries (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    webhook_id bigint not null,
    event text not null,
    payload jsonb not null,
    status text not null default 'pending',
    attempts integer not null default 0,
    next_attempt_at timestamp with time zone not null default now(),
    response_status integer,
    error text,
    claimed_at timestamp with time zone,
    delivered_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    constraint webhook_deliveries_status_check check (status in ('pending', 'sending', 'delivered', 'failed', 'cancelled'))
);

-- A trigger of the digital pipeline: stage + event (+ conditions) -> action.
-- pipeline_id is filled from the stage (private.handle_stage_trigger_saved);
-- a move goes to a stage of the same pipeline.
create table public.stage_triggers (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    pipeline_id bigint not null,
    stage_id bigint not null,
    name text,
    event text not null,
    -- idle: minutes without activity; visit_passed: minutes after the visit
    delay_minutes integer not null default 0,
    -- Conditions: empty = any
    source_ids bigint[] not null default '{}'::bigint[],
    service_ids bigint[] not null default '{}'::bigint[],
    doctor_ids bigint[] not null default '{}'::bigint[],
    sales_ids bigint[] not null default '{}'::bigint[],
    tags_present bigint[] not null default '{}'::bigint[],
    tags_absent bigint[] not null default '{}'::bigint[],
    action text not null,
    target_stage_id bigint,
    -- set_responsible: null = the next one of the round robin
    target_sales_id bigint,
    tag_id bigint,
    task_type text,
    task_text text,
    task_due_minutes integer,
    template_id bigint,
    message_mode text,
    webhook_id bigint,
    field_name text,
    plan_amount bigint,
    doctor_id bigint,
    service_id bigint,
    is_active boolean not null default true,
    position integer not null default 0,
    created_at timestamp with time zone not null default now(),
    constraint stage_triggers_event_check check (event in ('stage_entered', 'message_in', 'message_out', 'call_missed',
        'idle', 'payment_added', 'appointment_set', 'visit_passed')),
    constraint stage_triggers_delay_check check (delay_minutes >= 0 and (event <> 'idle' or delay_minutes > 0)),
    constraint stage_triggers_action_check check (action in ('move_stage', 'set_responsible', 'add_tag', 'remove_tag',
        'create_task', 'send_template', 'send_webhook', 'set_field', 'start_salesbot')),
    constraint stage_triggers_move_check check (action <> 'move_stage' or (target_stage_id is not null and target_stage_id <> stage_id)),
    constraint stage_triggers_tag_check check (action not in ('add_tag', 'remove_tag') or tag_id is not null),
    constraint stage_triggers_task_check check (action <> 'create_task' or (
        task_type in ('call', 'message', 'reminder', 'other') and btrim(coalesce(task_text, '')) <> '' and task_due_minutes >= 0)),
    constraint stage_triggers_template_check check (action <> 'send_template' or (
        template_id is not null and coalesce(message_mode, 'auto') in ('auto', 'confirm'))),
    constraint stage_triggers_webhook_check check (action <> 'send_webhook' or webhook_id is not null),
    constraint stage_triggers_field_check check (action <> 'set_field' or (
        (field_name = 'plan_amount' and plan_amount >= 0)
        or (field_name = 'doctor_id' and doctor_id is not null)
        or (field_name = 'service_id' and service_id is not null)))
);

-- What the triggers did, per deal (deal feed, loop protection). status: done,
-- skipped (checklist, chain too long), failed (the action raised an error).
-- event_key identifies the event instance: a trigger runs once per key.
create table public.stage_trigger_runs (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    deal_id bigint not null,
    trigger_id bigint,
    trigger_name text,
    event text not null,
    event_key text not null,
    action text not null,
    status text not null default 'done',
    details jsonb not null default '{}'::jsonb,
    error text,
    created_at timestamp with time zone not null default now(),
    constraint stage_trigger_runs_status_check check (status in ('done', 'skipped', 'failed'))
);

-- API keys: only the SHA-256 (hex) of the key is stored; prefix = its first
-- characters, to recognize it in the list. scope: read, or write (read + write).
create table public.api_keys (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    name text not null,
    prefix text not null,
    key_hash text not null,
    scope text not null default 'read',
    created_by bigint,
    created_at timestamp with time zone not null default now(),
    last_used_at timestamp with time zone,
    revoked_at timestamp with time zone,
    constraint api_keys_name_not_blank check (btrim(name) <> ''),
    constraint api_keys_scope_check check (scope in ('read', 'write'))
);

-- Requests of a key per minute (rate limit), old windows purged by the tick
create table public.api_request_counts (
    api_key_id bigint not null,
    window_start timestamp with time zone not null,
    requests integer not null default 0,
    constraint api_request_counts_pkey primary key (api_key_id, window_start)
);

-- An automatic message queued by a stage trigger has no rule: its template
alter table public.automessages add column template_id bigint;

alter table public.webhooks add constraint webhooks_organization_id_id_key unique (organization_id, id);
alter table public.webhook_deliveries add constraint webhook_deliveries_organization_id_id_key unique (organization_id, id);
alter table public.stage_triggers add constraint stage_triggers_organization_id_id_key unique (organization_id, id);
alter table public.stage_trigger_runs add constraint stage_trigger_runs_organization_id_id_key unique (organization_id, id);
alter table public.api_keys add constraint api_keys_organization_id_id_key unique (organization_id, id);

alter table public.webhooks
    add constraint webhooks_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.webhook_deliveries
    add constraint webhook_deliveries_webhook_id_fkey foreign key (organization_id, webhook_id) references public.webhooks(organization_id, id) on delete cascade;
alter table public.stage_triggers
    add constraint stage_triggers_pipeline_id_fkey foreign key (organization_id, pipeline_id) references public.pipelines(organization_id, id) on delete cascade;
alter table public.stage_triggers
    add constraint stage_triggers_stage_id_fkey foreign key (organization_id, stage_id) references public.stages(organization_id, id) on delete cascade;
-- The stage and the target of a move belong to the trigger's pipeline
alter table public.stage_triggers
    add constraint stage_triggers_pipeline_stage_fkey foreign key (pipeline_id, stage_id) references public.stages(pipeline_id, id) on delete cascade;
alter table public.stage_triggers
    add constraint stage_triggers_target_stage_id_fkey foreign key (pipeline_id, target_stage_id) references public.stages(pipeline_id, id) on delete cascade;
alter table public.stage_triggers
    add constraint stage_triggers_target_sales_id_fkey foreign key (organization_id, target_sales_id) references public.sales(organization_id, id) on delete cascade;
alter table public.stage_triggers
    add constraint stage_triggers_tag_id_fkey foreign key (organization_id, tag_id) references public.tags(organization_id, id) on delete cascade;
alter table public.stage_triggers
    add constraint stage_triggers_template_id_fkey foreign key (organization_id, template_id) references public.message_templates(organization_id, id) on delete cascade;
alter table public.stage_triggers
    add constraint stage_triggers_webhook_id_fkey foreign key (organization_id, webhook_id) references public.webhooks(organization_id, id) on delete cascade;
alter table public.stage_triggers
    add constraint stage_triggers_doctor_id_fkey foreign key (organization_id, doctor_id) references public.doctors(organization_id, id) on delete cascade;
alter table public.stage_triggers
    add constraint stage_triggers_service_id_fkey foreign key (organization_id, service_id) references public.services(organization_id, id) on delete cascade;
alter table public.stage_trigger_runs
    add constraint stage_trigger_runs_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.stage_trigger_runs
    add constraint stage_trigger_runs_trigger_id_fkey foreign key (organization_id, trigger_id) references public.stage_triggers(organization_id, id) on delete set null (trigger_id);
alter table public.api_keys
    add constraint api_keys_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.api_keys
    add constraint api_keys_created_by_fkey foreign key (organization_id, created_by) references public.sales(organization_id, id) on delete set null (created_by);
alter table public.api_request_counts
    add constraint api_request_counts_api_key_id_fkey foreign key (api_key_id) references public.api_keys(id) on delete cascade;
alter table public.automessages
    add constraint automessages_template_id_fkey foreign key (organization_id, template_id) references public.message_templates(organization_id, id) on delete set null (template_id);

create index webhooks_organization_id_idx on public.webhooks using btree (organization_id);
create index webhook_deliveries_due_idx on public.webhook_deliveries using btree (next_attempt_at) where status = 'pending';
create index webhook_deliveries_webhook_id_idx on public.webhook_deliveries using btree (organization_id, webhook_id, created_at desc);
create index stage_triggers_stage_event_idx on public.stage_triggers using btree (organization_id, stage_id, event) where is_active;
create index stage_triggers_delayed_idx on public.stage_triggers using btree (event) where is_active and event in ('idle', 'visit_passed');
create unique index stage_trigger_runs_once_idx on public.stage_trigger_runs using btree (trigger_id, deal_id, event_key);
create index stage_trigger_runs_deal_id_idx on public.stage_trigger_runs using btree (organization_id, deal_id, created_at);
create unique index api_keys_key_hash_idx on public.api_keys using btree (key_hash);
create index api_keys_organization_id_idx on public.api_keys using btree (organization_id, created_at);
create index automessages_template_id_idx on public.automessages using btree (organization_id, template_id) where template_id is not null;

--
-- JSON of the entities (webhook payloads and API responses)
--

CREATE OR REPLACE FUNCTION "private"."deal_json"("deal" "public"."deals") RETURNS "jsonb"
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
  select jsonb_build_object(
    'id', deal.id,
    'name', deal.name,
    'patient_id', deal.patient_id,
    'pipeline_id', deal.pipeline_id,
    'stage_id', deal.stage_id,
    'stage_name', s.name,
    'stage_kind', s.kind,
    'sales_id', deal.sales_id,
    'source_id', deal.source_id,
    'service_id', deal.service_id,
    'doctor_id', deal.doctor_id,
    'plan_amount', deal.plan_amount,
    'paid_amount', deal.paid_amount,
    'consultation_amount', deal.consultation_amount,
    'appointment_at', deal.appointment_at,
    'visit_at', deal.visit_at,
    'tags', to_jsonb(deal.tags),
    'description', deal.description,
    'lost_reason_id', deal.lost_reason_id,
    'lost_comment', deal.lost_comment,
    'created_at', deal.created_at,
    'updated_at', deal.updated_at,
    'stage_changed_at', deal.stage_changed_at,
    'closed_at', deal.closed_at,
    'archived_at', deal.archived_at
  )
  from (select 1) one
    left join public.stages s on s.id = deal.stage_id
$$;

CREATE OR REPLACE FUNCTION "private"."patient_json"("patient" "public"."patients") RETURNS "jsonb"
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select jsonb_build_object(
    'id', patient.id,
    'first_name', patient.first_name,
    'last_name', patient.last_name,
    'middle_name', patient.middle_name,
    'phones', to_jsonb(patient.phones),
    'birth_date', patient.birth_date,
    'city', patient.city,
    'source_id', patient.source_id,
    'sales_id', patient.sales_id,
    'tags', to_jsonb(patient.tags),
    'first_seen', patient.first_seen,
    'last_seen', patient.last_seen
  )
$$;

--
-- Outgoing webhooks
--

-- Does an active webhook of the clinic want this event (cheap check before
-- building a payload)
CREATE OR REPLACE FUNCTION "private"."has_webhook"("org_id" bigint, "webhook_event" "text") RETURNS boolean
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
  select current_setting('crm.importing', true) is distinct from 'on'
    and exists (
      select 1 from public.webhooks w
      where w.organization_id = org_id and w.is_active and webhook_event = any(w.events)
    )
$$;

-- Queues the event for the active webhooks that want it (only_webhook_id: for
-- that webhook only, whatever its events: the action of a stage trigger, the
-- test). Payload: { event, occurred_at, organization_id, data }.
CREATE OR REPLACE FUNCTION "private"."enqueue_webhook"("org_id" bigint, "webhook_event" "text", "data" "jsonb", "only_webhook_id" bigint DEFAULT NULL::bigint) RETURNS integer
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  queued integer;
begin
  -- Imports (public.import_batch) are bulk writes: nothing is sent
  if current_setting('crm.importing', true) = 'on' then
    return 0;
  end if;
  insert into public.webhook_deliveries (organization_id, webhook_id, event, payload)
  select org_id, w.id, webhook_event,
    jsonb_build_object('event', webhook_event, 'occurred_at', now(), 'organization_id', org_id, 'data', data)
  from public.webhooks w
  where w.organization_id = org_id
    and w.is_active
    and case when only_webhook_id is null then webhook_event = any(w.events) else w.id = only_webhook_id end;
  get diagnostics queued = row_count;
  return queued;
end;
$$;

-- Wait before the next attempt: 1 min, 5 min, 30 min, 2 h, then 6 h
CREATE OR REPLACE FUNCTION "private"."webhook_retry_delay"("attempt" integer) RETURNS interval
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select case
    when attempt <= 1 then interval '1 minute'
    when attempt = 2 then interval '5 minutes'
    when attempt = 3 then interval '30 minutes'
    when attempt = 4 then interval '2 hours'
    else interval '6 hours'
  end
$$;

-- Switching a webhook on starts afresh; switching it off cancels its queue
CREATE OR REPLACE FUNCTION "private"."handle_webhook_update"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if new.is_active and not old.is_active then
    new.failure_count := 0;
    new.disabled_at := null;
    new.last_error := null;
  elsif old.is_active and not new.is_active then
    update public.webhook_deliveries d
    set status = 'cancelled', error = coalesce(d.error, 'Вебхук выключен')
    where d.organization_id = new.organization_id and d.webhook_id = new.id and d.status = 'pending';
  end if;
  return new;
end;
$$;

-- Dispatcher (edge function webhooks_dispatch, service role only): takes the
-- due deliveries of the active webhooks with FOR UPDATE SKIP LOCKED (two runs
-- never take the same row) and returns them with the URL and the secret. A
-- run that died while sending gives its rows back after 10 minutes (the
-- receiver deduplicates by delivery id).
CREATE OR REPLACE FUNCTION "public"."claim_webhook_deliveries"("max_rows" integer DEFAULT 50) RETURNS TABLE("id" bigint, "organization_id" bigint, "webhook_id" bigint, "url" "text", "secret" "text", "event" "text", "payload" "jsonb", "attempts" integer)
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
begin
  update public.webhook_deliveries d
  set status = 'pending', next_attempt_at = now()
  where d.status = 'sending' and d.claimed_at < now() - interval '10 minutes';

  return query
  with due as (
    select d.id
    from public.webhook_deliveries d
      join public.webhooks w on w.organization_id = d.organization_id and w.id = d.webhook_id
    where d.status = 'pending' and d.next_attempt_at <= now() and w.is_active
    order by d.next_attempt_at, d.id
    limit greatest(max_rows, 0)
    for update of d skip locked
  ), taken as (
    update public.webhook_deliveries d
    set status = 'sending', claimed_at = now()
    from due
    where d.id = due.id
    returning d.id, d.organization_id, d.webhook_id, d.event, d.payload, d.attempts
  )
  select t.id, t.organization_id, t.webhook_id, w.url, w.secret, t.event, t.payload, t.attempts
  from taken t
    join public.webhooks w on w.organization_id = t.organization_id and w.id = t.webhook_id
  order by t.id;
end;
$$;

-- Result of a delivery (edge function webhooks_dispatch, service role only).
-- A failure is retried later (private.webhook_retry_delay), 5 attempts at
-- most; 10 failed attempts in a row switch the webhook off. Returns the new
-- status of the delivery (null: not being sent).
CREATE OR REPLACE FUNCTION "public"."complete_webhook_delivery"("delivery_id" bigint, "delivered" boolean, "response_status" integer DEFAULT NULL::integer, "error_text" "text" DEFAULT NULL::"text") RETURNS "text"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  delivery public.webhook_deliveries;
  new_status text;
  failures integer;
  message text := left(coalesce(nullif(btrim(error_text), ''),
    case when response_status is not null then 'HTTP ' || response_status else 'Ошибка отправки' end), 500);
begin
  select * into delivery from public.webhook_deliveries d
  where d.id = delivery_id
  for update;
  if not found or delivery.status <> 'sending' then
    return null;
  end if;

  if delivered then
    update public.webhook_deliveries d
    set status = 'delivered', attempts = d.attempts + 1, response_status = complete_webhook_delivery.response_status,
        error = null, delivered_at = now()
    where d.id = delivery.id;
    update public.webhooks w
    set failure_count = 0, last_success_at = now()
    where w.organization_id = delivery.organization_id and w.id = delivery.webhook_id;
    return 'delivered';
  end if;

  new_status := case when delivery.attempts + 1 >= 5 then 'failed' else 'pending' end;
  update public.webhook_deliveries d
  set status = new_status, attempts = d.attempts + 1, response_status = complete_webhook_delivery.response_status,
      error = message,
      next_attempt_at = now() + private.webhook_retry_delay(d.attempts + 1)
  where d.id = delivery.id;

  update public.webhooks w
  set failure_count = w.failure_count + 1, last_error = message, last_failure_at = now()
  where w.organization_id = delivery.organization_id and w.id = delivery.webhook_id
  returning w.failure_count into failures;
  if failures >= 10 then
    update public.webhooks w
    set is_active = false, disabled_at = now(),
        last_error = 'Отключён после ' || failures || ' ошибок подряд: ' || message
    where w.organization_id = delivery.organization_id and w.id = delivery.webhook_id and w.is_active;
  end if;
  return new_status;
end;
$$;

-- Called every minute by pg_cron: starts the edge function when a delivery
-- is due. Needs the Vault secrets project_url and automessages_dispatch_key
-- (the key of all the dispatchers, function secret AUTOMESSAGES_DISPATCH_KEY).
CREATE OR REPLACE FUNCTION "private"."request_webhooks_dispatch"() RETURNS bigint
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  project_url text;
  dispatch_key text;
begin
  if not exists (
    select 1 from public.webhook_deliveries d
    where (d.status = 'pending' and d.next_attempt_at <= now())
      or (d.status = 'sending' and d.claimed_at < now() - interval '10 minutes')
  ) then
    return null;
  end if;
  if to_regclass('vault.decrypted_secrets') is null then
    return null;
  end if;
  execute 'select decrypted_secret from vault.decrypted_secrets where name = $1'
    into project_url using 'project_url';
  execute 'select decrypted_secret from vault.decrypted_secrets where name = $1'
    into dispatch_key using 'automessages_dispatch_key';
  if project_url is null or dispatch_key is null then
    raise warning 'webhooks: Vault secrets project_url and automessages_dispatch_key are not set';
    return null;
  end if;
  return net.http_post(
    url := rtrim(project_url, '/') || '/functions/v1/webhooks_dispatch',
    body := '{}'::jsonb,
    params := '{}'::jsonb,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || dispatch_key
    ),
    timeout_milliseconds := 5000
  );
end;
$$;

-- «Отправить тест» in the settings (owner and head): a ping to one webhook
CREATE OR REPLACE FUNCTION "public"."send_test_webhook"("target_webhook_id" bigint) RETURNS integer
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
begin
  if org_id is null or private.current_user_role() not in ('owner', 'head') then
    raise exception 'Only the owner and the head manage webhooks' using errcode = '42501';
  end if;
  if not exists (
    select 1 from public.webhooks w
    where w.organization_id = org_id and w.id = target_webhook_id and w.is_active
  ) then
    raise exception 'Вебхук не найден или выключен' using errcode = '22023';
  end if;
  return private.enqueue_webhook(org_id, 'ping',
    jsonb_build_object('message', 'Тестовое событие DentalCRM'), target_webhook_id);
end;
$$;

-- A new signing secret (owner and head)
CREATE OR REPLACE FUNCTION "public"."regenerate_webhook_secret"("target_webhook_id" bigint) RETURNS "text"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  new_secret text := replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', '');
begin
  if org_id is null or private.current_user_role() not in ('owner', 'head') then
    raise exception 'Only the owner and the head manage webhooks' using errcode = '42501';
  end if;
  update public.webhooks w
  set secret = new_secret
  where w.organization_id = org_id and w.id = target_webhook_id;
  if not found then
    raise exception 'Вебхук не найден' using errcode = '22023';
  end if;
  return new_secret;
end;
$$;

-- Deals: created, stage changed, won, lost
CREATE OR REPLACE FUNCTION "private"."handle_deal_webhooks"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  new_kind text;
begin
  if tg_op = 'INSERT' then
    if private.has_webhook(new.organization_id, 'deal.created') then
      perform private.enqueue_webhook(new.organization_id, 'deal.created',
        jsonb_build_object('deal_id', new.id, 'patient_id', new.patient_id, 'deal', private.deal_json(new)));
    end if;
    return null;
  end if;
  if new.stage_id is not distinct from old.stage_id then
    return null;
  end if;
  if private.has_webhook(new.organization_id, 'deal.stage_changed') then
    perform private.enqueue_webhook(new.organization_id, 'deal.stage_changed',
      jsonb_build_object('deal_id', new.id, 'patient_id', new.patient_id,
        'previous_stage_id', old.stage_id, 'deal', private.deal_json(new)));
  end if;
  select s.kind into new_kind from public.stages s where s.id = new.stage_id;
  if new_kind in ('won', 'lost') and private.has_webhook(new.organization_id, 'deal.' || new_kind) then
    perform private.enqueue_webhook(new.organization_id, 'deal.' || new_kind,
      jsonb_build_object('deal_id', new.id, 'patient_id', new.patient_id, 'deal', private.deal_json(new)));
  end if;
  return null;
end;
$$;

CREATE OR REPLACE FUNCTION "private"."handle_patient_webhooks"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if private.has_webhook(new.organization_id, 'patient.created') then
    perform private.enqueue_webhook(new.organization_id, 'patient.created',
      jsonb_build_object('patient_id', new.id, 'patient', private.patient_json(new)));
  end if;
  return null;
end;
$$;

CREATE OR REPLACE FUNCTION "private"."handle_task_webhooks"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if new.done_date is not null and old.done_date is null
    and private.has_webhook(new.organization_id, 'task.completed') then
    perform private.enqueue_webhook(new.organization_id, 'task.completed',
      jsonb_build_object('task_id', new.id, 'deal_id', new.deal_id,
        'task', jsonb_build_object('id', new.id, 'deal_id', new.deal_id, 'type', new.type, 'text', new.text,
          'due_date', new.due_date, 'done_date', new.done_date, 'sales_id', new.sales_id)));
  end if;
  return null;
end;
$$;

--
-- Digital pipeline
--

-- The pipeline of a trigger is the one of its stage
CREATE OR REPLACE FUNCTION "private"."handle_stage_trigger_saved"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
begin
  select s.pipeline_id into new.pipeline_id
  from public.stages s
  where s.organization_id = new.organization_id and s.id = new.stage_id;
  new.name := nullif(btrim(new.name), '');
  return new;
end;
$$;

-- Conditions of a trigger: every non-empty list must match the deal
CREATE OR REPLACE FUNCTION "private"."stage_trigger_matches"("trigger_row" "public"."stage_triggers", "deal" "public"."deals") RETURNS boolean
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select coalesce(
    (cardinality(trigger_row.source_ids) = 0 or deal.source_id = any(trigger_row.source_ids))
    and (cardinality(trigger_row.service_ids) = 0 or deal.service_id = any(trigger_row.service_ids))
    and (cardinality(trigger_row.doctor_ids) = 0 or deal.doctor_id = any(trigger_row.doctor_ids))
    and (cardinality(trigger_row.sales_ids) = 0 or deal.sales_id = any(trigger_row.sales_ids))
    and trigger_row.tags_present <@ deal.tags
    and not (trigger_row.tags_absent && deal.tags),
    false)
$$;

-- The action of a trigger on a deal; returns what changed (shown in the deal
-- feed). Raises when the action cannot be done (the caller logs it).
CREATE OR REPLACE FUNCTION "private"."apply_stage_trigger_action"("trigger_row" "public"."stage_triggers", "deal" "public"."deals") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := deal.organization_id;
  new_sales_id bigint;
  new_id bigint;
  zone text;
  template_body text;
  rendered text;
  old_value jsonb;
  queued integer;
begin
  case trigger_row.action
  when 'move_stage' then
    if deal.stage_id = trigger_row.target_stage_id then
      return jsonb_build_object('unchanged', true);
    end if;
    update public.deals d
    set stage_id = trigger_row.target_stage_id
    where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('from_stage_id', deal.stage_id, 'to_stage_id', trigger_row.target_stage_id);

  when 'set_responsible' then
    new_sales_id := coalesce(trigger_row.target_sales_id, private.next_responsible(org_id));
    if new_sales_id is null then
      raise exception 'Некому назначить: распределение по очереди не настроено' using errcode = '22023';
    end if;
    if exists (select 1 from public.sales s where s.id = new_sales_id and s.disabled) then
      raise exception 'Сотрудник отключён' using errcode = '22023';
    end if;
    if deal.sales_id is not distinct from new_sales_id then
      return jsonb_build_object('unchanged', true);
    end if;
    update public.deals d
    set sales_id = new_sales_id
    where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('from_sales_id', deal.sales_id, 'to_sales_id', new_sales_id);

  when 'add_tag' then
    if trigger_row.tag_id = any(deal.tags) then
      return jsonb_build_object('unchanged', true, 'tag_id', trigger_row.tag_id);
    end if;
    update public.deals d
    set tags = array_append(d.tags, trigger_row.tag_id)
    where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('tag_id', trigger_row.tag_id);

  when 'remove_tag' then
    if not trigger_row.tag_id = any(deal.tags) then
      return jsonb_build_object('unchanged', true, 'tag_id', trigger_row.tag_id);
    end if;
    update public.deals d
    set tags = array_remove(d.tags, trigger_row.tag_id)
    where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('tag_id', trigger_row.tag_id);

  when 'create_task' then
    -- Same as the task rules (private.create_rule_tasks)
    insert into public.tasks (organization_id, deal_id, type, text, due_date, sales_id)
    values (org_id, deal.id, trigger_row.task_type, btrim(trigger_row.task_text),
      now() + make_interval(mins => trigger_row.task_due_minutes), deal.sales_id)
    returning id into new_id;
    return jsonb_build_object('task_id', new_id);

  when 'send_template' then
    -- The stage 6 queue: "show first" becomes the task with the text and the
    -- «Отправить» button right away; "auto" is sent by the dispatcher
    -- (quiet hours apply, leaving the stage cancels it)
    if coalesce(trigger_row.message_mode, 'auto') = 'confirm' then
      select t.body into template_body from public.message_templates t
      where t.organization_id = org_id and t.id = trigger_row.template_id;
      rendered := private.render_template(template_body, private.automessage_vars(deal));
      insert into public.automessages (organization_id, deal_id, rule_id, template_id, stage_id, timing, send_at, status, text, processed_at)
      values (org_id, deal.id, null, trigger_row.template_id, deal.stage_id, 'after_stage', now(), 'awaiting', rendered, now())
      returning id into new_id;
      insert into public.tasks (organization_id, deal_id, type, text, due_date, sales_id, automessage_id)
      values (org_id, deal.id, 'message', rendered, now(), deal.sales_id, new_id);
    else
      select o.timezone into zone from public.organizations o where o.id = org_id;
      insert into public.automessages (organization_id, deal_id, rule_id, template_id, stage_id, timing, send_at)
      values (org_id, deal.id, null, trigger_row.template_id, deal.stage_id, 'after_stage',
        private.automessage_send_time(now(), zone))
      returning id into new_id;
    end if;
    return jsonb_build_object('automessage_id', new_id, 'template_id', trigger_row.template_id,
      'mode', coalesce(trigger_row.message_mode, 'auto'));

  when 'send_webhook' then
    queued := private.enqueue_webhook(org_id, 'automation',
      jsonb_build_object('deal_id', deal.id, 'patient_id', deal.patient_id,
        'trigger', jsonb_build_object('id', trigger_row.id, 'name', trigger_row.name, 'event', trigger_row.event),
        'deal', private.deal_json(deal)),
      trigger_row.webhook_id);
    if queued = 0 then
      raise exception 'Вебхук выключен' using errcode = '22023';
    end if;
    return jsonb_build_object('webhook_id', trigger_row.webhook_id);

  when 'start_salesbot' then
    -- «Запустить салесбот» (26_salesbot.sql): replaces the bot of the deal
    new_id := private.salesbot_start(trigger_row.salesbot_id, deal.id, 'pipeline');
    if new_id is null then
      raise exception 'Бот не запущен' using errcode = '22023';
    end if;
    return jsonb_build_object('salesbot_id', trigger_row.salesbot_id, 'session_id', new_id);

  when 'set_field' then
    old_value := to_jsonb(deal) -> trigger_row.field_name;
    if trigger_row.field_name = 'plan_amount' then
      update public.deals d set plan_amount = trigger_row.plan_amount
      where d.organization_id = org_id and d.id = deal.id;
      return jsonb_build_object('field', 'plan_amount', 'from', old_value, 'to', trigger_row.plan_amount);
    elsif trigger_row.field_name = 'doctor_id' then
      update public.deals d set doctor_id = trigger_row.doctor_id
      where d.organization_id = org_id and d.id = deal.id;
      return jsonb_build_object('field', 'doctor_id', 'from', old_value, 'to', trigger_row.doctor_id);
    else
      update public.deals d set service_id = trigger_row.service_id
      where d.organization_id = org_id and d.id = deal.id;
      return jsonb_build_object('field', 'service_id', 'from', old_value, 'to', trigger_row.service_id);
    end if;
  end case;
  return '{}'::jsonb;
end;
$$;

-- Runs one trigger on one deal for one event instance (event_key), once:
-- checks that the deal is still at the stage and matches the conditions,
-- records the run, applies the action one level deeper (crm.automation_depth,
-- at most 3 levels) with the audit source 'automation'. An error of the
-- action is caught and recorded: skipped for the stage checklist, failed
-- otherwise. Returns the status, or null when nothing ran.
CREATE OR REPLACE FUNCTION "private"."fire_stage_trigger"("trigger_row" "public"."stage_triggers", "target_deal_id" bigint, "instance_key" "text") RETURNS "text"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  deal public.deals;
  depth integer := coalesce(nullif(current_setting('crm.automation_depth', true), '')::integer, 0);
  previous_source text := coalesce(current_setting('crm.audit_source', true), '');
  run_id bigint;
  run_status text := 'done';
  result jsonb;
  error_hint text;
  error_message text;
begin
  if current_setting('crm.importing', true) = 'on' then
    return null;
  end if;
  select * into deal from public.deals d
  where d.organization_id = trigger_row.organization_id and d.id = target_deal_id;
  -- Unsorted leads (stage 18) wait for a person to accept them
  if not found or deal.archived_at is not null or deal.unsorted_at is not null
    or deal.stage_id <> trigger_row.stage_id
    or not private.stage_trigger_matches(trigger_row, deal) then
    return null;
  end if;

  insert into public.stage_trigger_runs (organization_id, deal_id, trigger_id, trigger_name, event, event_key, action)
  values (deal.organization_id, deal.id, trigger_row.id, trigger_row.name, trigger_row.event, instance_key,
    trigger_row.action)
  on conflict (trigger_id, deal_id, event_key) do nothing
  returning id into run_id;
  if run_id is null then
    return null;
  end if;

  if depth >= 3 then
    update public.stage_trigger_runs r
    set status = 'skipped', error = 'Слишком длинная цепочка автоматических действий'
    where r.id = run_id;
    return 'skipped';
  end if;

  perform set_config('crm.automation_depth', (depth + 1)::text, true);
  perform set_config('crm.audit_source', 'automation', true);
  begin
    result := private.apply_stage_trigger_action(trigger_row, deal);
  exception when others then
    get stacked diagnostics error_hint = pg_exception_hint, error_message = message_text;
    run_status := case when error_hint = 'stage_checklist_incomplete' then 'skipped' else 'failed' end;
  end;
  perform set_config('crm.automation_depth', depth::text, true);
  perform set_config('crm.audit_source', previous_source, true);

  update public.stage_trigger_runs r
  set status = run_status, details = coalesce(result, '{}'::jsonb), error = left(error_message, 500)
  where r.id = run_id;
  return run_status;
end;
$$;

-- The active triggers of the deal's stage for an immediate event
CREATE OR REPLACE FUNCTION "private"."run_stage_triggers"("deal" "public"."deals", "trigger_event" "text", "instance_key" "text") RETURNS integer
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  trigger_row public.stage_triggers;
  fired integer := 0;
begin
  if current_setting('crm.importing', true) = 'on' or deal.archived_at is not null then
    return 0;
  end if;
  for trigger_row in
    select t.* from public.stage_triggers t
    where t.organization_id = deal.organization_id
      and t.stage_id = deal.stage_id
      and t.event = trigger_event
      and t.is_active
    order by t.position, t.id
  loop
    -- An earlier trigger may have moved the deal: fire_stage_trigger checks it
    if private.fire_stage_trigger(trigger_row, deal.id, instance_key) is not null then
      fired := fired + 1;
    end if;
  end loop;
  return fired;
end;
$$;

-- Deals: entering a stage (creation too), a visit date set
CREATE OR REPLACE FUNCTION "private"."handle_deal_stage_triggers"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  current_deal public.deals;
begin
  if tg_op = 'INSERT' or new.stage_id is distinct from old.stage_id then
    perform private.run_stage_triggers(new, 'stage_entered',
      'stage:' || new.stage_id || ':' || extract(epoch from new.stage_changed_at));
  end if;
  if new.appointment_at is not null
    and (tg_op = 'INSERT' or new.appointment_at is distinct from old.appointment_at) then
    -- The first triggers may have moved the deal: its current row
    select * into current_deal from public.deals d where d.organization_id = new.organization_id and d.id = new.id;
    perform private.run_stage_triggers(current_deal, 'appointment_set',
      'appointment:' || extract(epoch from new.appointment_at));
  end if;
  return null;
end;
$$;

-- Messages: inbound and outbound triggers, webhook «message received»
CREATE OR REPLACE FUNCTION "private"."handle_message_pipeline"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  target public.deals;
begin
  if new.direction = 'in' and private.has_webhook(new.organization_id, 'message.received') then
    perform private.enqueue_webhook(new.organization_id, 'message.received',
      jsonb_build_object('message_id', new.id, 'deal_id', new.deal_id, 'patient_id', new.patient_id,
        'message', jsonb_build_object('id', new.id, 'deal_id', new.deal_id, 'patient_id', new.patient_id,
          'transport', new.transport, 'text', new.text, 'content_type', new.content_type,
          'content_uri', new.content_uri, 'sent_at', new.sent_at)));
  end if;
  select * into target from public.deals d where d.organization_id = new.organization_id and d.id = new.deal_id;
  if found then
    perform private.run_stage_triggers(target,
      case when new.direction = 'in' then 'message_in' else 'message_out' end,
      'message:' || new.id);
  end if;
  return null;
end;
$$;

-- Calls: a missed incoming call of a deal
CREATE OR REPLACE FUNCTION "private"."handle_call_stage_triggers"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  target public.deals;
begin
  if new.status = 'missed' and new.direction = 'in' and new.deal_id is not null
    and (tg_op = 'INSERT' or old.status is distinct from 'missed') then
    select * into target from public.deals d where d.organization_id = new.organization_id and d.id = new.deal_id;
    if found then
      perform private.run_stage_triggers(target, 'call_missed', 'call:' || new.id);
    end if;
  end if;
  return null;
end;
$$;

-- Payments: triggers «payment added», webhook «payment added»
CREATE OR REPLACE FUNCTION "private"."handle_payment_pipeline"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  target public.deals;
begin
  select * into target from public.deals d where d.organization_id = new.organization_id and d.id = new.deal_id;
  if private.has_webhook(new.organization_id, 'payment.added') then
    perform private.enqueue_webhook(new.organization_id, 'payment.added',
      jsonb_build_object('payment_id', new.id, 'deal_id', new.deal_id, 'patient_id', target.patient_id,
        'payment', jsonb_build_object('id', new.id, 'deal_id', new.deal_id, 'amount', new.amount, 'kind', new.kind,
          'paid_at', new.paid_at, 'comment', new.comment)));
  end if;
  if target.id is not null then
    perform private.run_stage_triggers(target, 'payment_added', 'payment:' || new.id);
  end if;
  return null;
end;
$$;

-- Last activity of a deal: entering its stage, a message, a note, a call, a
-- completed task (edits of the fields do not count: automatic ones either)
CREATE OR REPLACE FUNCTION "private"."deal_last_activity_at"("deal" "public"."deals") RETURNS timestamp with time zone
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
  select greatest(
    deal.stage_changed_at,
    (select max(m.sent_at) from public.messages m where m.organization_id = deal.organization_id and m.deal_id = deal.id),
    (select max(n.date) from public.deal_notes n where n.organization_id = deal.organization_id and n.deal_id = deal.id),
    (select max(c.called_at) from public.calls c where c.organization_id = deal.organization_id and c.deal_id = deal.id),
    (select max(t.done_date) from public.tasks t where t.organization_id = deal.organization_id and t.deal_id = deal.id)
  )
$$;

-- Delayed triggers, run by pg_cron every 5 minutes (and by the tests with a
-- moment): «N minutes without activity» (once per quiet period) and «N
-- minutes after the visit» (once per visit date). At most 200 deals per
-- trigger and run; the next run takes the rest. Also purges the old API rate
-- limit windows.
CREATE OR REPLACE FUNCTION "private"."stage_triggers_tick"("moment" timestamp with time zone DEFAULT "now"()) RETURNS integer
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  trigger_row public.stage_triggers;
  target record;
  fired integer := 0;
begin
  for trigger_row in
    select t.* from public.stage_triggers t
    where t.is_active and t.event in ('idle', 'visit_passed')
    order by t.organization_id, t.position, t.id
  loop
    for target in
      select c.id, c.event_key
      from (
        select d.id,
          case when trigger_row.event = 'idle'
            then 'idle:' || extract(epoch from private.deal_last_activity_at(d))
            else 'visit:' || extract(epoch from d.appointment_at)
          end as event_key,
          case when trigger_row.event = 'idle'
            then private.deal_last_activity_at(d)
            else d.appointment_at
          end as since
        from public.deals d
        where d.organization_id = trigger_row.organization_id
          and d.stage_id = trigger_row.stage_id
          and d.archived_at is null
          and (trigger_row.event = 'idle' or d.appointment_at is not null)
          and private.stage_trigger_matches(trigger_row, d)
      ) c
      where c.since <= moment - make_interval(mins => trigger_row.delay_minutes)
        and not exists (
          select 1 from public.stage_trigger_runs r
          where r.trigger_id = trigger_row.id and r.deal_id = c.id and r.event_key = c.event_key
        )
      order by c.since, c.id
      limit 200
    loop
      if private.fire_stage_trigger(trigger_row, target.id, target.event_key) is not null then
        fired := fired + 1;
      end if;
    end loop;
  end loop;

  delete from public.api_request_counts c where c.window_start < moment - interval '1 hour';
  return fired;
end;
$$;

--
-- API keys
--

CREATE OR REPLACE FUNCTION "private"."api_key_hash"("api_key" "text") RETURNS "text"
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select encode(sha256(convert_to(coalesce(api_key, ''), 'UTF8')), 'hex')
$$;

-- A new key (owner and head): returned once, only its hash is stored
CREATE OR REPLACE FUNCTION "public"."create_api_key"("key_name" "text", "key_scope" "text" DEFAULT 'read'::"text") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  new_key text := 'dcrm_' || replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', '');
  new_row public.api_keys;
begin
  if org_id is null or private.current_user_role() not in ('owner', 'head') then
    raise exception 'Only the owner and the head manage API keys' using errcode = '42501';
  end if;
  if key_scope is null or key_scope not in ('read', 'write') then
    raise exception 'Доступ ключа: read или write' using errcode = '22023';
  end if;
  insert into public.api_keys (organization_id, name, prefix, key_hash, scope, created_by)
  values (org_id, btrim(coalesce(key_name, '')), left(new_key, 12), private.api_key_hash(new_key), key_scope,
    private.current_sales_id())
  returning * into new_row;
  return jsonb_build_object('id', new_row.id, 'name', new_row.name, 'prefix', new_row.prefix,
    'scope', new_row.scope, 'created_at', new_row.created_at, 'key', new_key);
end;
$$;

CREATE OR REPLACE FUNCTION "public"."revoke_api_key"("key_id" bigint) RETURNS boolean
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if private.current_organization_id() is null or private.current_user_role() not in ('owner', 'head') then
    raise exception 'Only the owner and the head manage API keys' using errcode = '42501';
  end if;
  update public.api_keys k
  set revoked_at = now()
  where k.organization_id = private.current_organization_id() and k.id = key_id and k.revoked_at is null;
  return found;
end;
$$;

-- The clinic of an API key. Errors carry PostgREST HTTP statuses (PTnnn):
-- 401 unknown or revoked key, 403 read-only key for a write, 429 more than
-- 60 requests in the current minute. Changes made through the API are
-- audited with the source 'api'.
CREATE OR REPLACE FUNCTION "private"."api_authenticate"("api_key" "text", "need_write" boolean) RETURNS "public"."api_keys"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  key_row public.api_keys;
  used integer;
begin
  select * into key_row from public.api_keys k
  where k.key_hash = private.api_key_hash(api_key) and k.revoked_at is null;
  if not found then
    raise exception 'Неверный или отозванный API-ключ' using errcode = 'PT401', hint = 'invalid_key';
  end if;
  if need_write and key_row.scope <> 'write' then
    raise exception 'Ключ только для чтения' using errcode = 'PT403', hint = 'read_only_key';
  end if;
  insert into public.api_request_counts as c (api_key_id, window_start, requests)
  values (key_row.id, date_trunc('minute', now()), 1)
  on conflict (api_key_id, window_start) do update set requests = c.requests + 1
  returning c.requests into used;
  if used > 60 then
    raise exception 'Слишком много запросов: не больше 60 в минуту на ключ' using errcode = 'PT429', hint = 'rate_limited';
  end if;
  update public.api_keys k set last_used_at = now() where k.id = key_row.id;
  perform set_config('crm.audit_source', 'api', true);
  return key_row;
end;
$$;

-- Page and page size of a list: page from 1, per_page 1..100 (50)
CREATE OR REPLACE FUNCTION "private"."api_page"("params" "jsonb", OUT "page" integer, OUT "per_page" integer) RETURNS "record"
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select greatest(coalesce((params ->> 'page')::integer, 1), 1),
    least(greatest(coalesce((params ->> 'per_page')::integer, 50), 1), 100)
$$;

-- Tag ids of a request, all of the clinic
CREATE OR REPLACE FUNCTION "private"."api_tag_ids"("org_id" bigint, "value" "jsonb") RETURNS bigint[]
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  ids bigint[];
begin
  if value is null or value = 'null'::jsonb then
    return '{}'::bigint[];
  end if;
  if jsonb_typeof(value) <> 'array' then
    raise exception 'tags: ожидается массив id тегов' using errcode = '22023';
  end if;
  select coalesce(array_agg(distinct x::bigint), '{}'::bigint[]) into ids
  from jsonb_array_elements_text(value) as x;
  if exists (
    select 1 from unnest(ids) as i
    where not exists (select 1 from public.tags t where t.organization_id = org_id and t.id = i)
  ) then
    raise exception 'tags: неизвестный тег' using errcode = '23503';
  end if;
  return ids;
end;
$$;

-- A patient of the request: found by phone, else created. Returns
-- { patient_id, created }.
CREATE OR REPLACE FUNCTION "private"."api_find_or_create_patient"("org_id" bigint, "body" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  numbers text[];
  found_id bigint;
begin
  if body is null or jsonb_typeof(body) <> 'object' then
    raise exception 'patient: ожидается объект' using errcode = '22023';
  end if;
  select coalesce(array_agg(distinct private.normalize_phone(x)) filter (where private.normalize_phone(x) is not null), '{}'::text[])
  into numbers
  from (
    select body ->> 'phone' as x
    union all
    select jsonb_array_elements_text(case when jsonb_typeof(body -> 'phones') = 'array' then body -> 'phones' else '[]'::jsonb end)
  ) p;
  if cardinality(numbers) > 0 then
    select p.id into found_id from public.patients p
    where p.organization_id = org_id and p.phones && numbers
    order by p.last_seen desc, p.id desc
    limit 1;
    if found_id is not null then
      return jsonb_build_object('patient_id', found_id, 'created', false);
    end if;
  end if;
  if nullif(btrim(coalesce(body ->> 'first_name', '')), '') is null
    and nullif(btrim(coalesce(body ->> 'last_name', '')), '') is null
    and cardinality(numbers) = 0 then
    raise exception 'Укажите имя или телефон пациента' using errcode = '22023';
  end if;
  insert into public.patients (organization_id, first_name, last_name, middle_name, phone_jsonb, birth_date, city, source_id, sales_id, tags)
  values (
    org_id,
    nullif(btrim(body ->> 'first_name'), ''),
    nullif(btrim(body ->> 'last_name'), ''),
    nullif(btrim(body ->> 'middle_name'), ''),
    coalesce((select jsonb_agg(jsonb_build_object('number', n, 'type', 'mobile')) from unnest(numbers) as n), '[]'::jsonb),
    (body ->> 'birth_date')::date,
    nullif(btrim(body ->> 'city'), ''),
    (body ->> 'source_id')::bigint,
    (body ->> 'sales_id')::bigint,
    private.api_tag_ids(org_id, body -> 'tags')
  )
  returning id into found_id;
  return jsonb_build_object('patient_id', found_id, 'created', true);
end;
$$;

--
-- Public REST API (edge function api, service role only). Every function
-- takes the API key: the clinic comes from its hash, nothing outside that
-- clinic is read or written.
--

-- GET /api/deals?pipeline_id=&stage_id=&patient_id=&updated_since=&page=&per_page=
-- Ordered by updated_at then id (incremental sync with updated_since).
CREATE OR REPLACE FUNCTION "public"."api_list_deals"("api_key" "text", "params" "jsonb" DEFAULT '{}'::"jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authenticate(api_key, false)).organization_id;
  page_number integer := (private.api_page(params)).page;
  page_size integer := (private.api_page(params)).per_page;
  f_pipeline bigint := (params ->> 'pipeline_id')::bigint;
  f_stage bigint := (params ->> 'stage_id')::bigint;
  f_patient bigint := (params ->> 'patient_id')::bigint;
  f_updated timestamp with time zone := (params ->> 'updated_since')::timestamp with time zone;
  total bigint;
  items jsonb;
begin
  select count(*) into total
  from public.deals d
  where d.organization_id = org_id
    and (f_pipeline is null or d.pipeline_id = f_pipeline)
    and (f_stage is null or d.stage_id = f_stage)
    and (f_patient is null or d.patient_id = f_patient)
    and (f_updated is null or d.updated_at >= f_updated);
  select coalesce(jsonb_agg(private.deal_json(p.d) order by (p.d).updated_at, (p.d).id), '[]'::jsonb) into items
  from (
    select d from public.deals d
    where d.organization_id = org_id
      and (f_pipeline is null or d.pipeline_id = f_pipeline)
      and (f_stage is null or d.stage_id = f_stage)
      and (f_patient is null or d.patient_id = f_patient)
      and (f_updated is null or d.updated_at >= f_updated)
    order by d.updated_at, d.id
    limit page_size offset (page_number - 1) * page_size
  ) p;
  return jsonb_build_object('data', items,
    'meta', jsonb_build_object('page', page_number, 'per_page', page_size, 'total', total));
end;
$$;

-- GET /api/deals/:id (with its patient)
CREATE OR REPLACE FUNCTION "public"."api_get_deal"("api_key" "text", "deal_id" bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authenticate(api_key, false)).organization_id;
  deal public.deals;
  patient public.patients;
begin
  select * into deal from public.deals d where d.organization_id = org_id and d.id = api_get_deal.deal_id;
  if not found then
    raise exception 'Сделка не найдена' using errcode = 'PT404', hint = 'not_found';
  end if;
  select * into patient from public.patients p where p.organization_id = org_id and p.id = deal.patient_id;
  return jsonb_build_object('data', private.deal_json(deal) || jsonb_build_object('patient', private.patient_json(patient)));
end;
$$;

-- POST /api/deals: patient_id, or patient { first_name, last_name, phone }
-- (found by phone or created), and the deal fields. Without sales_id the
-- deal is distributed by the clinic rules, like a website lead.
CREATE OR REPLACE FUNCTION "public"."api_create_deal"("api_key" "text", "body" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authenticate(api_key, true)).organization_id;
  new_patient_id bigint;
  new_pipeline_id bigint;
  new_stage_id bigint;
  new_deal public.deals;
  created_patient boolean := false;
  found_patient jsonb;
begin
  if body is null or jsonb_typeof(body) <> 'object' then
    raise exception 'Ожидается JSON-объект' using errcode = '22023';
  end if;
  new_patient_id := (body ->> 'patient_id')::bigint;
  if new_patient_id is null and body ? 'patient' then
    found_patient := private.api_find_or_create_patient(org_id, body -> 'patient');
    new_patient_id := (found_patient ->> 'patient_id')::bigint;
    created_patient := (found_patient ->> 'created')::boolean;
  end if;
  if new_patient_id is null then
    raise exception 'Укажите patient_id или patient' using errcode = '22023';
  end if;
  if not exists (select 1 from public.patients p where p.organization_id = org_id and p.id = new_patient_id) then
    raise exception 'Пациент не найден' using errcode = 'PT404', hint = 'not_found';
  end if;

  new_pipeline_id := (body ->> 'pipeline_id')::bigint;
  new_stage_id := (body ->> 'stage_id')::bigint;
  if new_stage_id is not null and new_pipeline_id is null then
    select s.pipeline_id into new_pipeline_id from public.stages s
    where s.organization_id = org_id and s.id = new_stage_id;
    if new_pipeline_id is null then
      raise exception 'Этап не найден' using errcode = '23503';
    end if;
  end if;

  insert into public.deals (organization_id, patient_id, pipeline_id, stage_id, name, source_id, service_id,
    doctor_id, sales_id, plan_amount, consultation_amount, appointment_at, visit_at, description, tags)
  values (org_id, new_patient_id, new_pipeline_id, new_stage_id,
    nullif(btrim(body ->> 'name'), ''),
    (body ->> 'source_id')::bigint,
    (body ->> 'service_id')::bigint,
    (body ->> 'doctor_id')::bigint,
    (body ->> 'sales_id')::bigint,
    coalesce((body ->> 'plan_amount')::bigint, 0),
    (body ->> 'consultation_amount')::bigint,
    (body ->> 'appointment_at')::timestamp with time zone,
    (body ->> 'visit_at')::timestamp with time zone,
    body ->> 'description',
    private.api_tag_ids(org_id, body -> 'tags'))
  returning * into new_deal;

  -- The row after the triggers (distribution, automations)
  select * into new_deal from public.deals d where d.organization_id = org_id and d.id = new_deal.id;
  return jsonb_build_object('data', private.deal_json(new_deal), 'created_patient', created_patient);
end;
$$;

-- PATCH /api/deals/:id: only the fields present in the body change. The
-- rules of the deals apply (stage checklist, refusal reason, refusal locked).
CREATE OR REPLACE FUNCTION "public"."api_update_deal"("api_key" "text", "deal_id" bigint, "body" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authenticate(api_key, true)).organization_id;
  deal public.deals;
  new_stage_id bigint;
  new_pipeline_id bigint;
begin
  if body is null or jsonb_typeof(body) <> 'object' then
    raise exception 'Ожидается JSON-объект' using errcode = '22023';
  end if;
  select * into deal from public.deals d
  where d.organization_id = org_id and d.id = api_update_deal.deal_id
  for update;
  if not found then
    raise exception 'Сделка не найдена' using errcode = 'PT404', hint = 'not_found';
  end if;

  new_stage_id := case when body ? 'stage_id' then (body ->> 'stage_id')::bigint else deal.stage_id end;
  new_pipeline_id := case
    when body ? 'pipeline_id' then (body ->> 'pipeline_id')::bigint
    when body ? 'stage_id' then (select s.pipeline_id from public.stages s where s.organization_id = org_id and s.id = new_stage_id)
    else deal.pipeline_id
  end;
  if new_stage_id is null or new_pipeline_id is null then
    raise exception 'Этап не найден' using errcode = '23503';
  end if;

  update public.deals d
  set pipeline_id = new_pipeline_id,
      stage_id = new_stage_id,
      name = case when body ? 'name' then nullif(btrim(body ->> 'name'), '') else d.name end,
      sales_id = case when body ? 'sales_id' then (body ->> 'sales_id')::bigint else d.sales_id end,
      source_id = case when body ? 'source_id' then (body ->> 'source_id')::bigint else d.source_id end,
      service_id = case when body ? 'service_id' then (body ->> 'service_id')::bigint else d.service_id end,
      doctor_id = case when body ? 'doctor_id' then (body ->> 'doctor_id')::bigint else d.doctor_id end,
      plan_amount = case when body ? 'plan_amount' then coalesce((body ->> 'plan_amount')::bigint, 0) else d.plan_amount end,
      consultation_amount = case when body ? 'consultation_amount' then (body ->> 'consultation_amount')::bigint else d.consultation_amount end,
      appointment_at = case when body ? 'appointment_at' then (body ->> 'appointment_at')::timestamp with time zone else d.appointment_at end,
      visit_at = case when body ? 'visit_at' then (body ->> 'visit_at')::timestamp with time zone else d.visit_at end,
      description = case when body ? 'description' then body ->> 'description' else d.description end,
      tags = case when body ? 'tags' then private.api_tag_ids(org_id, body -> 'tags') else d.tags end,
      lost_reason_id = case when body ? 'lost_reason_id' then (body ->> 'lost_reason_id')::bigint else d.lost_reason_id end,
      lost_comment = case when body ? 'lost_comment' then body ->> 'lost_comment' else d.lost_comment end
  where d.organization_id = org_id and d.id = deal.id;

  select * into deal from public.deals d where d.organization_id = org_id and d.id = api_update_deal.deal_id;
  return jsonb_build_object('data', private.deal_json(deal));
end;
$$;

-- GET /api/patients?phone=&q=&created_since=&page=&per_page=
CREATE OR REPLACE FUNCTION "public"."api_list_patients"("api_key" "text", "params" "jsonb" DEFAULT '{}'::"jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authenticate(api_key, false)).organization_id;
  page_number integer := (private.api_page(params)).page;
  page_size integer := (private.api_page(params)).per_page;
  f_phone text := private.normalize_phone(params ->> 'phone');
  f_query text := nullif(lower(btrim(coalesce(params ->> 'q', ''))), '');
  f_created timestamp with time zone := (params ->> 'created_since')::timestamp with time zone;
  total bigint;
  items jsonb;
begin
  if params ->> 'phone' is not null and f_phone is null then
    raise exception 'phone: неверный номер' using errcode = '22023';
  end if;
  select count(*) into total
  from public.patients p
  where p.organization_id = org_id
    and (f_phone is null or p.phones @> array[f_phone])
    and (f_query is null or lower(concat_ws(' ', p.last_name, p.first_name, p.middle_name)) like '%' || f_query || '%')
    and (f_created is null or p.first_seen >= f_created);
  select coalesce(jsonb_agg(private.patient_json(x.p) order by (x.p).id), '[]'::jsonb) into items
  from (
    select p from public.patients p
    where p.organization_id = org_id
      and (f_phone is null or p.phones @> array[f_phone])
      and (f_query is null or lower(concat_ws(' ', p.last_name, p.first_name, p.middle_name)) like '%' || f_query || '%')
      and (f_created is null or p.first_seen >= f_created)
    order by p.id
    limit page_size offset (page_number - 1) * page_size
  ) x;
  return jsonb_build_object('data', items,
    'meta', jsonb_build_object('page', page_number, 'per_page', page_size, 'total', total));
end;
$$;

-- POST /api/patients: a patient with the same phone is returned, not doubled
CREATE OR REPLACE FUNCTION "public"."api_create_patient"("api_key" "text", "body" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authenticate(api_key, true)).organization_id;
  result jsonb := private.api_find_or_create_patient(org_id, body);
  patient public.patients;
begin
  select * into patient from public.patients p
  where p.organization_id = org_id and p.id = (result ->> 'patient_id')::bigint;
  return jsonb_build_object('data', private.patient_json(patient), 'created', (result ->> 'created')::boolean);
end;
$$;

-- POST /api/deals/:id/notes { text }
CREATE OR REPLACE FUNCTION "public"."api_add_deal_note"("api_key" "text", "deal_id" bigint, "body" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authenticate(api_key, true)).organization_id;
  note_text text := nullif(btrim(coalesce(body ->> 'text', '')), '');
  note public.deal_notes;
begin
  if note_text is null then
    raise exception 'Укажите text' using errcode = '22023';
  end if;
  if not exists (select 1 from public.deals d where d.organization_id = org_id and d.id = api_add_deal_note.deal_id) then
    raise exception 'Сделка не найдена' using errcode = 'PT404', hint = 'not_found';
  end if;
  insert into public.deal_notes (organization_id, deal_id, type, text, sales_id)
  values (org_id, api_add_deal_note.deal_id, 'api', left(note_text, 10000), null)
  returning * into note;
  return jsonb_build_object('data', jsonb_build_object('id', note.id, 'deal_id', note.deal_id, 'text', note.text, 'date', note.date));
end;
$$;

-- GET /api/pipelines: the pipelines with their stages
CREATE OR REPLACE FUNCTION "public"."api_list_pipelines"("api_key" "text") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authenticate(api_key, false)).organization_id;
begin
  return jsonb_build_object('data', coalesce((
    select jsonb_agg(jsonb_build_object(
      'id', p.id, 'name', p.name, 'is_default', p.is_default, 'position', p.position,
      'stages', coalesce((
        select jsonb_agg(jsonb_build_object('id', s.id, 'name', s.name, 'position', s.position,
          'kind', s.kind, 'color', s.color) order by s.position, s.id)
        from public.stages s where s.pipeline_id = p.id
      ), '[]'::jsonb)) order by p.position, p.id)
    from public.pipelines p
    where p.organization_id = org_id
  ), '[]'::jsonb));
end;
$$;

--
-- Triggers
--

create or replace trigger stage_trigger_saved
    before insert or update on public.stage_triggers
    for each row execute function private.handle_stage_trigger_saved();

create or replace trigger webhook_update
    before update on public.webhooks
    for each row execute function private.handle_webhook_update();

-- After the other deal triggers (names sort after deal_after_write,
-- deal_automessages...): task rules and auto-messages of the stage first
create or replace trigger deal_stage_triggers
    after insert or update on public.deals
    for each row execute function private.handle_deal_stage_triggers();

create or replace trigger deal_webhooks
    after insert or update on public.deals
    for each row execute function private.handle_deal_webhooks();

create or replace trigger patient_webhooks
    after insert on public.patients
    for each row execute function private.handle_patient_webhooks();

create or replace trigger task_webhooks
    after update of done_date on public.tasks
    for each row execute function private.handle_task_webhooks();

create or replace trigger message_pipeline
    after insert on public.messages
    for each row execute function private.handle_message_pipeline();

create or replace trigger call_stage_triggers
    after insert or update of status on public.calls
    for each row execute function private.handle_call_stage_triggers();

-- After deal_payment_changed: the deal has its new paid amount
create or replace trigger deal_payment_pipeline
    after insert on public.deal_payments
    for each row execute function private.handle_payment_pipeline();

-- Audit log (secrets and key hashes are never copied)
create or replace trigger audit_stage_trigger
    after insert or update or delete on public.stage_triggers
    for each row execute function private.audit_row('stage_trigger', 'name,stage_id,event,delay_minutes,action,target_stage_id,target_sales_id,tag_id,template_id,webhook_id,is_active');

create or replace trigger audit_webhook
    after insert or update or delete on public.webhooks
    for each row execute function private.audit_row('webhook', 'name,url,events,is_active');

create or replace trigger audit_api_key
    after insert or update on public.api_keys
    for each row execute function private.audit_row('api_key', 'name,prefix,scope,revoked_at');

--
-- Row Level Security
--

alter table public.webhooks enable row level security;
alter table public.webhook_deliveries enable row level security;
alter table public.stage_triggers enable row level security;
alter table public.stage_trigger_runs enable row level security;
alter table public.api_keys enable row level security;
alter table public.api_request_counts enable row level security;

-- Triggers are settings: every employee reads them, the owner and the head edit
create policy "Organization members can read" on public.stage_triggers for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Owner and head can insert" on public.stage_triggers for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can update" on public.stage_triggers for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head can delete" on public.stage_triggers for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

-- The runs follow the deal
create policy "Runs of visible deals can be read" on public.stage_trigger_runs for select to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = stage_trigger_runs.organization_id and d.id = stage_trigger_runs.deal_id));

-- Webhooks, their deliveries and the API keys: owner and head only
create policy "Owner and head can read" on public.webhooks for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can insert" on public.webhooks for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can update" on public.webhooks for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head can delete" on public.webhooks for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can read" on public.webhook_deliveries for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can read" on public.api_keys for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

--
-- Grants
--

grant all on table public.stage_triggers to authenticated;
grant all on table public.stage_triggers to service_role;
revoke all on table public.stage_triggers from anon;
grant all on sequence public.stage_triggers_id_seq to authenticated, service_role;
revoke all on sequence public.stage_triggers_id_seq from anon;

-- Written by the triggers only
revoke all on table public.stage_trigger_runs from anon, authenticated;
grant select on table public.stage_trigger_runs to authenticated;
grant all on table public.stage_trigger_runs to service_role;
revoke all on sequence public.stage_trigger_runs_id_seq from anon, authenticated;

-- Webhooks: the owner and the head write the URL, the events and the switch;
-- the secret and the delivery state are written by the functions
revoke all on table public.webhooks from anon, authenticated;
grant select, delete on table public.webhooks to authenticated;
grant insert (name, url, events, is_active) on table public.webhooks to authenticated;
grant update (name, url, events, is_active) on table public.webhooks to authenticated;
grant all on table public.webhooks to service_role;
revoke all on sequence public.webhooks_id_seq from anon;
grant all on sequence public.webhooks_id_seq to authenticated, service_role;

revoke all on table public.webhook_deliveries from anon, authenticated;
grant select on table public.webhook_deliveries to authenticated;
grant all on table public.webhook_deliveries to service_role;
revoke all on sequence public.webhook_deliveries_id_seq from anon, authenticated;

-- API keys: listed without their hash; created and revoked by the functions
revoke all on table public.api_keys from anon, authenticated;
grant select (id, organization_id, name, prefix, scope, created_by, created_at, last_used_at, revoked_at) on table public.api_keys to authenticated;
grant all on table public.api_keys to service_role;
revoke all on sequence public.api_keys_id_seq from anon, authenticated;

revoke all on table public.api_request_counts from anon, authenticated;
grant all on table public.api_request_counts to service_role;

-- Settings actions of the owner and the head (checked inside)
revoke all on function public.send_test_webhook(bigint) from public, anon;
grant execute on function public.send_test_webhook(bigint) to authenticated, service_role;
revoke all on function public.regenerate_webhook_secret(bigint) from public, anon;
grant execute on function public.regenerate_webhook_secret(bigint) to authenticated, service_role;
revoke all on function public.create_api_key(text, text) from public, anon;
grant execute on function public.create_api_key(text, text) to authenticated, service_role;
revoke all on function public.revoke_api_key(bigint) from public, anon;
grant execute on function public.revoke_api_key(bigint) to authenticated, service_role;

-- Dispatcher and API: service role only
revoke all on function public.claim_webhook_deliveries(integer) from public, anon, authenticated;
grant execute on function public.claim_webhook_deliveries(integer) to service_role;
revoke all on function public.complete_webhook_delivery(bigint, boolean, integer, text) from public, anon, authenticated;
grant execute on function public.complete_webhook_delivery(bigint, boolean, integer, text) to service_role;
revoke all on function public.api_list_deals(text, jsonb) from public, anon, authenticated;
grant execute on function public.api_list_deals(text, jsonb) to service_role;
revoke all on function public.api_get_deal(text, bigint) from public, anon, authenticated;
grant execute on function public.api_get_deal(text, bigint) to service_role;
revoke all on function public.api_create_deal(text, jsonb) from public, anon, authenticated;
grant execute on function public.api_create_deal(text, jsonb) to service_role;
revoke all on function public.api_update_deal(text, bigint, jsonb) from public, anon, authenticated;
grant execute on function public.api_update_deal(text, bigint, jsonb) to service_role;
revoke all on function public.api_list_patients(text, jsonb) from public, anon, authenticated;
grant execute on function public.api_list_patients(text, jsonb) to service_role;
revoke all on function public.api_create_patient(text, jsonb) from public, anon, authenticated;
grant execute on function public.api_create_patient(text, jsonb) to service_role;
revoke all on function public.api_add_deal_note(text, bigint, jsonb) from public, anon, authenticated;
grant execute on function public.api_add_deal_note(text, bigint, jsonb) to service_role;
revoke all on function public.api_list_pipelines(text) from public, anon, authenticated;
grant execute on function public.api_list_pipelines(text) to service_role;

-- Definer helpers of the triggers, the tick and the API: not callable by clients
revoke all on function private.deal_json(public.deals) from public, anon, authenticated;
revoke all on function private.has_webhook(bigint, text) from public, anon, authenticated;
revoke all on function private.enqueue_webhook(bigint, text, jsonb, bigint) from public, anon, authenticated;
revoke all on function private.handle_webhook_update() from public, anon, authenticated;
revoke all on function private.request_webhooks_dispatch() from public, anon, authenticated;
revoke all on function private.handle_deal_webhooks() from public, anon, authenticated;
revoke all on function private.handle_patient_webhooks() from public, anon, authenticated;
revoke all on function private.handle_task_webhooks() from public, anon, authenticated;
revoke all on function private.apply_stage_trigger_action(public.stage_triggers, public.deals) from public, anon, authenticated;
revoke all on function private.fire_stage_trigger(public.stage_triggers, bigint, text) from public, anon, authenticated;
revoke all on function private.run_stage_triggers(public.deals, text, text) from public, anon, authenticated;
revoke all on function private.handle_deal_stage_triggers() from public, anon, authenticated;
revoke all on function private.handle_message_pipeline() from public, anon, authenticated;
revoke all on function private.handle_call_stage_triggers() from public, anon, authenticated;
revoke all on function private.handle_payment_pipeline() from public, anon, authenticated;
revoke all on function private.deal_last_activity_at(public.deals) from public, anon, authenticated;
revoke all on function private.stage_triggers_tick(timestamp with time zone) from public, anon, authenticated;
revoke all on function private.api_authenticate(text, boolean) from public, anon, authenticated;
revoke all on function private.api_tag_ids(bigint, jsonb) from public, anon, authenticated;
revoke all on function private.api_find_or_create_patient(bigint, jsonb) from public, anon, authenticated;
grant execute on function private.deal_json(public.deals) to service_role;
grant execute on function private.has_webhook(bigint, text) to service_role;
grant execute on function private.enqueue_webhook(bigint, text, jsonb, bigint) to service_role;
grant execute on function private.api_authenticate(text, boolean) to service_role;
grant execute on function private.api_tag_ids(bigint, jsonb) to service_role;
grant execute on function private.api_find_or_create_patient(bigint, jsonb) to service_role;
