--
-- Deal list, saved filters, bulk actions, sales plan (stage 21)
--
-- Saved filters: a named set of list filters (the ra-core filter values of
-- the deals, with relative values such as "me" or "this month" kept as
-- tokens, see src/components/atomic-crm/deals/list/savedFilters.ts). A
-- filter is personal (sales_id = its author, who alone sees and edits it) or
-- clinic-wide (sales_id is null: created and edited by the owner and the
-- head, seen by everybody). The built-in presets live in the app.
--
-- Bulk actions: public.bulk_deals(action, ids, params) runs one action on
-- many deals with the caller's rights (SECURITY INVOKER): RLS decides which
-- deals the caller may change, the deal triggers apply the usual rules
-- (lost reason, stage checklist, locked lost deals) and log every change to
-- deal_events and the audit log with the source 'user'. Every deal is done
-- in its own subtransaction: the result lists, per deal, whether it worked
-- and why not. Messages to the patients go through the mailing queue of
-- stage 17 (anti-ban limits, working hours, opt-out): a mailing whose
-- segment is the chosen deals (deal_ids), owner and head only like the
-- mailings. Archiving and deleting are for the owner and the head as well.
--
-- Sales plan: targets per month for the clinic (sales_id is null) and per
-- employee: new deals, won deals, paid amount, visits (a null target is not
-- set). public.report_sales_plan(month) returns the targets and the facts of
-- the month in the clinic's time zone; the progress and the forecast (linear
-- extrapolation to the end of the month) are computed by the app
-- (src/components/atomic-crm/reports/salesPlan.ts, also the demo twin).
--   new deals: deals created in the month, by their responsible;
--   won deals: deals that entered a won stage in the month (once per deal);
--   paid amount: payments dated in the month;
--   visits: deals that first reached the "visit" key stage of the reports
--     (private.report_key_stages) in the month, in their current pipeline.
-- Owner and head only, like the reports.
--

create table public.saved_filters (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    -- null: the whole clinic; else the personal filter of this employee
    sales_id bigint default private.current_sales_id(),
    name text not null,
    resource text not null default 'deals',
    filter jsonb not null default '{}'::jsonb,
    position integer not null default 0,
    created_at timestamp with time zone not null default now(),
    constraint saved_filters_name_not_blank check (btrim(name) <> ''),
    constraint saved_filters_resource_check check (resource in ('deals')),
    constraint saved_filters_filter_is_object check (jsonb_typeof(filter) = 'object')
);

create table public.sales_plans (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    -- First day of the month
    month date not null,
    -- null: the target of the whole clinic
    sales_id bigint,
    new_deals integer,
    won_deals integer,
    -- Tenge
    paid_amount bigint,
    visits integer,
    updated_at timestamp with time zone not null default now(),
    constraint sales_plans_month_check check (extract(day from month) = 1),
    constraint sales_plans_targets_positive check (new_deals >= 0 and won_deals >= 0 and paid_amount >= 0 and visits >= 0),
    constraint sales_plans_month_sales_key unique nulls not distinct (organization_id, month, sales_id)
);

alter table public.saved_filters add constraint saved_filters_organization_id_id_key unique (organization_id, id);
alter table public.sales_plans add constraint sales_plans_organization_id_id_key unique (organization_id, id);

alter table public.saved_filters
    add constraint saved_filters_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.saved_filters
    add constraint saved_filters_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id) on delete cascade;
alter table public.sales_plans
    add constraint sales_plans_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.sales_plans
    add constraint sales_plans_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id) on delete cascade;

create index saved_filters_organization_id_idx on public.saved_filters using btree (organization_id, resource, sales_id, position);

--
-- Functions
--

-- One action on many deals. Actions and params:
--   stage: stage_id, lost_reason_id and lost_comment (a lost stage);
--   responsible: sales_id (null: nobody);
--   add_tags, remove_tags: tag_ids;
--   task: text, due_date, type (call by default), sales_id (the responsible
--     of each deal by default);
--   message: template_id or body, name (of the mailing) - owner and head;
--   archive, delete - owner and head.
-- Returns { action, results: [{ id, ok, error, code }], ok, failed,
-- mailing_id }. At most 1000 deals per call.
CREATE OR REPLACE FUNCTION "public"."bulk_deals"("action" "text", "ids" bigint[], "params" "jsonb" DEFAULT '{}'::"jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  user_role text := private.current_user_role();
  current_id bigint;
  touched bigint;
  failed boolean;
  err_message text;
  err_hint text;
  err_state text;
  results jsonb := '[]'::jsonb;
  target_stage public.stages;
  target_sales_id bigint;
  tag_ids bigint[];
  task_text text;
  task_due timestamp with time zone;
  task_type text;
  message_body text;
  template_name text;
  visible bigint[];
  new_mailing_id bigint;
begin
  if org_id is null then
    raise exception 'Нет доступа' using errcode = '42501';
  end if;
  if action is null or action not in ('stage', 'responsible', 'add_tags', 'remove_tags', 'task', 'message', 'archive', 'delete') then
    raise exception 'Неизвестное действие «%»', action
      using errcode = '22023', hint = 'bulk_unknown_action';
  end if;
  if cardinality(ids) > 1000 then
    raise exception 'Не больше 1000 сделок за раз'
      using errcode = '22023', hint = 'bulk_too_many';
  end if;
  if action in ('message', 'archive', 'delete') and coalesce(user_role in ('owner', 'head'), false) is false then
    raise exception 'Это действие доступно владельцу и руководителю'
      using errcode = '42501', hint = 'bulk_forbidden';
  end if;
  params := coalesce(params, '{}'::jsonb);

  -- Parameters, checked once
  if action = 'stage' then
    select s.* into target_stage from public.stages s
    where s.organization_id = org_id and s.id = nullif(params ->> 'stage_id', '')::bigint;
    if target_stage.id is null then
      raise exception 'Выберите этап' using errcode = '22023', hint = 'bulk_stage_required';
    end if;
  elsif action = 'responsible' then
    target_sales_id := nullif(params ->> 'sales_id', '')::bigint;
    if target_sales_id is not null and not exists (
      select 1 from public.sales s
      where s.organization_id = org_id and s.id = target_sales_id and not s.disabled
    ) then
      raise exception 'Сотрудник не найден' using errcode = '22023', hint = 'bulk_sales_not_found';
    end if;
  elsif action in ('add_tags', 'remove_tags') then
    tag_ids := array(
      select distinct t.value::bigint
      from jsonb_array_elements_text(case when jsonb_typeof(params -> 'tag_ids') = 'array' then params -> 'tag_ids' else '[]'::jsonb end) t
    );
    if cardinality(tag_ids) = 0 then
      raise exception 'Выберите теги' using errcode = '22023', hint = 'bulk_tags_required';
    end if;
  elsif action = 'task' then
    task_text := nullif(btrim(params ->> 'text'), '');
    task_due := nullif(params ->> 'due_date', '')::timestamp with time zone;
    task_type := coalesce(nullif(params ->> 'type', ''), 'call');
    target_sales_id := nullif(params ->> 'sales_id', '')::bigint;
    if task_text is null or task_due is null then
      raise exception 'Укажите текст и срок задачи' using errcode = '22023', hint = 'bulk_task_required';
    end if;
  elsif action = 'message' then
    select t.body, t.name into message_body, template_name
    from public.message_templates t
    where t.organization_id = org_id and t.id = nullif(params ->> 'template_id', '')::bigint;
    message_body := coalesce(nullif(btrim(params ->> 'body'), ''), message_body);
    if message_body is null then
      raise exception 'Выберите шаблон сообщения' using errcode = '22023', hint = 'bulk_message_required';
    end if;
    -- The deals the caller sees (RLS); their patients are queued by the
    -- mailing trigger with the stage 17 rules
    visible := array(
      select d.id from public.deals d
      where d.organization_id = org_id and d.id = any(ids)
    );
    if cardinality(visible) > 0 then
      insert into public.mailings (name, segment, template_id, body)
      values (
        coalesce(nullif(btrim(params ->> 'name'), ''), template_name, 'Сообщение по сделкам'),
        jsonb_build_object('deal_ids', to_jsonb(visible)),
        nullif(params ->> 'template_id', '')::bigint,
        message_body
      )
      returning id into new_mailing_id;
    end if;
  end if;

  for current_id in
    select u.id from unnest(ids) with ordinality u(id, n)
    where u.id is not null
    group by u.id
    order by min(u.n)
  loop
    touched := null;
    failed := false;
    if action = 'message' then
      if not current_id = any(visible) then
        touched := null;
      elsif exists (
        select 1 from public.mailing_messages mm
        where mm.organization_id = org_id and mm.mailing_id = new_mailing_id and mm.deal_id = current_id
      ) then
        touched := current_id;
      else
        failed := true;
        select
          case
            when p.messaging_opt_out then 'Пациент отказался от сообщений'
            when cardinality(p.phones) = 0 and not exists (
              select 1 from public.patient_chats c where c.organization_id = org_id and c.patient_id = p.id
            ) then 'Нет телефона или чата'
            else 'Пациенту уже отправляется сообщение по другой сделке'
          end,
          case
            when p.messaging_opt_out then 'opted_out'
            when cardinality(p.phones) = 0 then 'no_contact'
            else 'duplicate'
          end
        into err_message, err_hint
        from public.deals d
          join public.patients p on p.organization_id = d.organization_id and p.id = d.patient_id
        where d.organization_id = org_id and d.id = current_id;
        results := results || jsonb_build_object('id', current_id, 'ok', false, 'error', err_message, 'code', err_hint);
      end if;
    else
      begin
        if action = 'stage' then
          update public.deals d
          set stage_id = target_stage.id,
            pipeline_id = target_stage.pipeline_id,
            lost_reason_id = case when target_stage.kind = 'lost'
              then coalesce(nullif(params ->> 'lost_reason_id', '')::bigint, d.lost_reason_id)
              else d.lost_reason_id end,
            lost_comment = case when target_stage.kind = 'lost'
              then coalesce(nullif(btrim(params ->> 'lost_comment'), ''), d.lost_comment)
              else d.lost_comment end
          where d.organization_id = org_id and d.id = current_id
          returning d.id into touched;
        elsif action = 'responsible' then
          update public.deals d
          set sales_id = target_sales_id
          where d.organization_id = org_id and d.id = current_id
          returning d.id into touched;
        elsif action = 'add_tags' then
          update public.deals d
          set tags = d.tags || array(select t from unnest(tag_ids) t where t <> all(d.tags) order by t)
          where d.organization_id = org_id and d.id = current_id
          returning d.id into touched;
        elsif action = 'remove_tags' then
          update public.deals d
          set tags = array(select t.tag from unnest(d.tags) with ordinality t(tag, n) where t.tag <> all(tag_ids) order by t.n)
          where d.organization_id = org_id and d.id = current_id
          returning d.id into touched;
        elsif action = 'archive' then
          update public.deals d
          set archived_at = coalesce(d.archived_at, now())
          where d.organization_id = org_id and d.id = current_id
          returning d.id into touched;
        elsif action = 'delete' then
          delete from public.deals d
          where d.organization_id = org_id and d.id = current_id
          returning d.id into touched;
        elsif action = 'task' then
          insert into public.tasks (organization_id, deal_id, type, text, due_date, sales_id)
          select d.organization_id, d.id, task_type, task_text, task_due, coalesce(target_sales_id, d.sales_id)
          from public.deals d
          where d.organization_id = org_id and d.id = current_id
          returning deal_id into touched;
        end if;
      exception when others then
        get stacked diagnostics err_message = message_text, err_hint = pg_exception_hint, err_state = returned_sqlstate;
        failed := true;
        results := results || jsonb_build_object('id', current_id, 'ok', false, 'error', err_message,
          'code', coalesce(nullif(err_hint, ''), err_state));
      end;
    end if;
    if not failed then
      if touched is null then
        results := results || jsonb_build_object('id', current_id, 'ok', false,
          'error', 'Сделка не найдена или нет доступа', 'code', 'not_found');
      else
        results := results || jsonb_build_object('id', current_id, 'ok', true);
      end if;
    end if;
  end loop;

  return jsonb_build_object(
    'action', action,
    'results', results,
    'ok', (select count(*) from jsonb_array_elements(results) r where (r ->> 'ok')::boolean),
    'failed', (select count(*) from jsonb_array_elements(results) r where not (r ->> 'ok')::boolean),
    'mailing_id', new_mailing_id
  );
end;
$$;

-- Targets and facts of a month (the current one by default) for the clinic
-- and every employee: { month, days_total, days_elapsed, clinic: { plan,
-- fact }, by_sales: [{ id, name, plan, fact }] }. A plan is null when no
-- target is set; the facts of the deals without a responsible only count
-- for the clinic.
CREATE OR REPLACE FUNCTION "public"."report_sales_plan"("target_month" "date" DEFAULT NULL::"date") RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  clinic_tz text;
  today date;
  month_start date;
  month_end date;
  month_from timestamp with time zone;
  month_to timestamp with time zone;
  report jsonb;
begin
  perform private.report_check_access();
  select coalesce(nullif(o.timezone, ''), 'Asia/Almaty') into clinic_tz
  from public.organizations o
  where o.id = org_id;
  today := (now() at time zone clinic_tz)::date;
  month_start := date_trunc('month', coalesce(target_month, today))::date;
  month_end := (month_start + interval '1 month')::date;
  month_from := month_start::timestamp without time zone at time zone clinic_tz;
  month_to := month_end::timestamp without time zone at time zone clinic_tz;

  with scope as (
    select d.id, d.sales_id, d.created_at, d.pipeline_id, d.stage_id, d.stage_changed_at
    from public.deals d
    where d.organization_id = org_id
  ),
  keys as (
    select * from private.report_key_stages()
  ),
  entries as (
    select e.deal_id, s.position, e.created_at as at
    from public.deal_events e
      join scope d on d.id = e.deal_id
      join public.stages s on s.id = e.to_stage_id and s.pipeline_id = d.pipeline_id
    where e.organization_id = org_id
      and e.type in ('created', 'stage_changed')
      and s.kind <> 'lost'
    union all
    select d.id, s.position, d.stage_changed_at
    from scope d
      join public.stages s on s.id = d.stage_id
    where s.kind <> 'lost'
  ),
  visited as (
    select en.deal_id, min(en.at) as visited_at
    from entries en
      join scope d on d.id = en.deal_id
      join keys k on k.pipeline_id = d.pipeline_id
    where en.position >= k.visit_position
    group by en.deal_id
  ),
  facts as (
    select x.sales_id,
      sum(x.new_deals)::bigint as new_deals,
      sum(x.won_deals)::bigint as won_deals,
      sum(x.paid_amount)::bigint as paid_amount,
      sum(x.visits)::bigint as visits
    from (
      select d.sales_id, count(*) as new_deals, 0 as won_deals, 0 as paid_amount, 0 as visits
      from scope d
      where d.created_at >= month_from and d.created_at < month_to
      group by d.sales_id
      union all
      select d.sales_id, 0, count(distinct d.id), 0, 0
      from public.deal_events e
        join scope d on d.id = e.deal_id
        join public.stages s on s.id = e.to_stage_id
      where e.organization_id = org_id
        and e.type in ('created', 'stage_changed')
        and s.kind = 'won'
        and e.created_at >= month_from and e.created_at < month_to
      group by d.sales_id
      union all
      select d.sales_id, 0, 0, sum(p.amount), 0
      from public.deal_payments p
        join scope d on d.id = p.deal_id
      where p.organization_id = org_id
        and p.paid_at >= month_start and p.paid_at < month_end
      group by d.sales_id
      union all
      select d.sales_id, 0, 0, 0, count(*)
      from visited v
        join scope d on d.id = v.deal_id
      where v.visited_at >= month_from and v.visited_at < month_to
      group by d.sales_id
    ) x
    group by x.sales_id
  ),
  plans as (
    select sp.sales_id,
      jsonb_build_object('new_deals', sp.new_deals, 'won_deals', sp.won_deals,
        'paid_amount', sp.paid_amount, 'visits', sp.visits) as plan
    from public.sales_plans sp
    where sp.organization_id = org_id and sp.month = month_start
  ),
  staff as (
    select sa.id, btrim(concat_ws(' ', sa.first_name, sa.last_name)) as name, sa.last_name,
      p.plan,
      jsonb_build_object(
        'new_deals', coalesce(f.new_deals, 0), 'won_deals', coalesce(f.won_deals, 0),
        'paid_amount', coalesce(f.paid_amount, 0), 'visits', coalesce(f.visits, 0)
      ) as fact,
      sa.disabled, f.sales_id is not null as has_fact
    from public.sales sa
      left join plans p on p.sales_id = sa.id
      left join facts f on f.sales_id = sa.id
    where sa.organization_id = org_id
  )
  select jsonb_build_object(
    'month', to_char(month_start, 'YYYY-MM-DD'),
    'days_total', month_end - month_start,
    'days_elapsed', greatest(0, least(month_end - month_start, today - month_start + 1)),
    'clinic', jsonb_build_object(
      'plan', (select p.plan from plans p where p.sales_id is null),
      'fact', (
        select jsonb_build_object(
          'new_deals', coalesce(sum(f.new_deals), 0), 'won_deals', coalesce(sum(f.won_deals), 0),
          'paid_amount', coalesce(sum(f.paid_amount), 0), 'visits', coalesce(sum(f.visits), 0))
        from facts f
      )
    ),
    'by_sales', (
      select coalesce(jsonb_agg(jsonb_build_object('id', st.id, 'name', st.name, 'plan', st.plan, 'fact', st.fact)
        order by st.last_name, st.id), '[]'::jsonb)
      from staff st
      where not st.disabled or st.plan is not null or st.has_fact
    )
  ) into report;
  return report;
end;
$$;

-- Saves the targets of a month: rows [{ sales_id (null: the clinic),
-- new_deals, won_deals, paid_amount, visits }]; a row without any target
-- removes the plan of that employee. Owner and head (RLS as well).
CREATE OR REPLACE FUNCTION "public"."save_sales_plan"("target_month" "date", "plans" "jsonb") RETURNS integer
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  month_start date := date_trunc('month', target_month)::date;
  item jsonb;
  row_sales_id bigint;
  saved integer := 0;
begin
  perform private.report_check_access();
  if month_start is null or jsonb_typeof(plans) is distinct from 'array' then
    raise exception 'Укажите месяц и цели' using errcode = '22023', hint = 'sales_plan_invalid';
  end if;
  for item in select value from jsonb_array_elements(plans) loop
    row_sales_id := nullif(item ->> 'sales_id', '')::bigint;
    if coalesce(item ->> 'new_deals', item ->> 'won_deals', item ->> 'paid_amount', item ->> 'visits') is null then
      delete from public.sales_plans sp
      where sp.organization_id = org_id and sp.month = month_start
        and sp.sales_id is not distinct from row_sales_id;
    else
      insert into public.sales_plans (organization_id, month, sales_id, new_deals, won_deals, paid_amount, visits)
      values (org_id, month_start, row_sales_id,
        (item ->> 'new_deals')::integer, (item ->> 'won_deals')::integer,
        (item ->> 'paid_amount')::bigint, (item ->> 'visits')::integer)
      on conflict (organization_id, month, sales_id) do update
      set new_deals = excluded.new_deals, won_deals = excluded.won_deals,
        paid_amount = excluded.paid_amount, visits = excluded.visits, updated_at = now();
      saved := saved + 1;
    end if;
  end loop;
  return saved;
end;
$$;

--
-- Triggers: the audit log (15_audit.sql) records the plans and the mailings
--

create or replace trigger audit_sales_plan
    after insert or update or delete on public.sales_plans
    for each row execute function private.audit_row('sales_plan', 'month,sales_id,new_deals,won_deals,paid_amount,visits');

create or replace trigger audit_mailing
    after insert on public.mailings
    for each row execute function private.audit_row('mailing', 'name,body,scheduled_at');

--
-- Row Level Security
--

alter table public.saved_filters enable row level security;
alter table public.sales_plans enable row level security;

-- Clinic filters for everybody, personal ones for their author only; the
-- owner and the head manage the clinic filters
create policy "Employees read clinic filters and their own" on public.saved_filters for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (sales_id is null or sales_id = (select private.current_sales_id())));
create policy "Own or clinic filters by role can be inserted" on public.saved_filters for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and ((sales_id is null and (select private.current_user_role()) in ('owner', 'head')) or sales_id = (select private.current_sales_id())));
create policy "Own or clinic filters by role can be updated" on public.saved_filters for update to authenticated
    using (organization_id = (select private.current_organization_id()) and ((sales_id is null and (select private.current_user_role()) in ('owner', 'head')) or sales_id = (select private.current_sales_id())))
    with check (organization_id = (select private.current_organization_id()) and ((sales_id is null and (select private.current_user_role()) in ('owner', 'head')) or sales_id = (select private.current_sales_id())));
create policy "Own or clinic filters by role can be deleted" on public.saved_filters for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and ((sales_id is null and (select private.current_user_role()) in ('owner', 'head')) or sales_id = (select private.current_sales_id())));

-- The plan is for the owner and the head, like the reports
create policy "Owner and head can read" on public.sales_plans for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can insert" on public.sales_plans for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can update" on public.sales_plans for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head can delete" on public.sales_plans for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

--
-- Grants
--

grant all on table public.saved_filters to anon;
grant all on table public.saved_filters to authenticated;
grant all on table public.saved_filters to service_role;
grant all on sequence public.saved_filters_id_seq to anon, authenticated, service_role;

grant all on table public.sales_plans to anon;
grant all on table public.sales_plans to authenticated;
grant all on table public.sales_plans to service_role;
grant all on sequence public.sales_plans_id_seq to anon, authenticated, service_role;

revoke all on function public.bulk_deals(text, bigint[], jsonb) from public, anon;
grant execute on function public.bulk_deals(text, bigint[], jsonb) to authenticated, service_role;
revoke all on function public.report_sales_plan(date) from public, anon;
grant execute on function public.report_sales_plan(date) to authenticated, service_role;
revoke all on function public.save_sales_plan(date, jsonb) from public, anon;
grant execute on function public.save_sales_plan(date, jsonb) to authenticated, service_role;
