--
-- Attachments (stage 22): files of a deal, files sent to the patient and
-- received from them in the chat.
--
-- Files live in the private storage bucket "deal-files" under
-- "<organization_id>/deals/<deal_id>/<uuid>-<name>". The storage policies
-- below let an employee read and upload files of the deals they see (the
-- deals policy applies to the sub-query), and delete them when they are the
-- owner or the head of the clinic, or uploaded the file. Links are signed
-- (createSignedUrl): a clinic never gets a public address of a patient file.
-- Note attachments stay in the public "attachments" bucket (07_storage.sql).
--
-- public.deal_files lists the files of a deal: uploaded on the «Файлы» tab
-- (message_id is null, shown in the deal feed), or sent / received in the
-- chat (message_id set, written by the edge functions with the service role).
-- The patient is taken from the deal, so the patient card lists the files of
-- all the patient's deals. Chat files belong to the conversation and cannot
-- be deleted from the list.
--
-- messages.attachment_*: the file of a message in our storage (outgoing
-- files, and incoming media copied by the webhooks). content_uri keeps the
-- messenger's own link.
--

alter table public.messages add column attachment_path text;
alter table public.messages add column attachment_name text;
alter table public.messages add column attachment_mime text;
alter table public.messages add column attachment_size bigint;

create table public.deal_files (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    deal_id bigint not null,
    -- The patient of the deal (set by the trigger)
    patient_id bigint not null,
    -- Object name in the "deal-files" bucket
    path text not null,
    name text not null,
    size bigint not null default 0,
    mime text not null default 'application/octet-stream',
    -- Who uploaded it; null for a file received from the patient
    sales_id bigint default private.current_sales_id(),
    -- A file sent or received in the chat
    message_id bigint,
    created_at timestamp with time zone not null default now(),
    constraint deal_files_name_not_blank check (btrim(name) <> ''),
    constraint deal_files_size_check check (size >= 0 and size <= 20971520),
    constraint deal_files_path_check check (path like organization_id::text || '/deals/' || deal_id::text || '/%')
);

alter table public.deal_files add constraint deal_files_organization_id_id_key unique (organization_id, id);
alter table public.deal_files add constraint deal_files_path_key unique (organization_id, path);
alter table public.deal_files
    add constraint deal_files_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.deal_files
    add constraint deal_files_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.deal_files
    add constraint deal_files_patient_id_fkey foreign key (organization_id, patient_id) references public.patients(organization_id, id) on delete cascade;
alter table public.deal_files
    add constraint deal_files_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);
alter table public.deal_files
    add constraint deal_files_message_id_fkey foreign key (organization_id, message_id) references public.messages(organization_id, id) on delete set null (message_id);

create index deal_files_deal_id_idx on public.deal_files using btree (organization_id, deal_id, created_at);
create index deal_files_patient_id_idx on public.deal_files using btree (organization_id, patient_id, created_at);
create index deal_files_message_id_idx on public.deal_files using btree (organization_id, message_id) where message_id is not null;

-- The patient of a new file is the patient of its deal
CREATE OR REPLACE FUNCTION "private"."handle_deal_file_before_insert"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  select d.patient_id into new.patient_id
  from public.deals d
  where d.organization_id = new.organization_id and d.id = new.deal_id;
  return new;
end;
$$;

-- A deal moved to another patient (patients merged) takes its files along
CREATE OR REPLACE FUNCTION "private"."handle_deal_patient_files"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  update public.deal_files f
  set patient_id = new.patient_id
  where f.organization_id = new.organization_id and f.deal_id = new.id;
  return null;
end;
$$;

create or replace trigger set_deal_file_patient
    before insert on public.deal_files
    for each row execute function private.handle_deal_file_before_insert();

create or replace trigger move_deal_files_with_patient
    after update of patient_id on public.deals
    for each row
    when (old.patient_id is distinct from new.patient_id)
    execute function private.handle_deal_patient_files();

-- Audit log: uploads and deletions on the «Файлы» tab (chat files are in
-- the conversation already)
create or replace trigger audit_deal_file_insert
    after insert on public.deal_files
    for each row
    when (new.message_id is null)
    execute function private.audit_row('file', 'name,size,mime');

create or replace trigger audit_deal_file_delete
    after delete on public.deal_files
    for each row
    when (old.message_id is null)
    execute function private.audit_row('file', 'name,size,mime');

-- The deal of a storage object of the current clinic
-- ("<organization_id>/deals/<deal_id>/..."), else null. Runs with the
-- caller's rights: the storage policies check the deal is visible.
-- (Policies qualify objects.name: a bare "name" would be the deal name.)
CREATE OR REPLACE FUNCTION "private"."storage_deal_id"("object_name" "text") RETURNS bigint
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $_$
declare
  parts text[] := string_to_array(object_name, '/');
begin
  if coalesce(array_length(parts, 1), 0) < 4
    or parts[1] is distinct from private.current_organization_id()::text
    or parts[2] <> 'deals'
    or parts[3] !~ '^[0-9]{1,18}$'
    or parts[4] = ''
  then
    return null;
  end if;
  return parts[3]::bigint;
end;
$_$;

-- Row level security: files follow the visibility of their deal; an
-- employee adds files as themselves; the owner and the head delete any file
-- of the list, a manager the files they uploaded
alter table public.deal_files enable row level security;

create policy "Rows of visible deals can be read" on public.deal_files for select to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = deal_files.organization_id and d.id = deal_files.deal_id));
create policy "Own files of visible deals can be inserted" on public.deal_files for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and sales_id = (select private.current_sales_id()) and message_id is null and exists (select 1 from public.deals d where d.organization_id = deal_files.organization_id and d.id = deal_files.deal_id));
create policy "Owner, head or uploader can delete" on public.deal_files for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and message_id is null and ((select private.current_user_role()) in ('owner', 'head') or sales_id = (select private.current_sales_id())) and exists (select 1 from public.deals d where d.organization_id = deal_files.organization_id and d.id = deal_files.deal_id));

-- Storage: the private bucket of deal files (20 MB, images, PDF, office
-- documents, audio, video)
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('deal-files', 'deal-files', false, 20971520, array[
    'image/*', 'video/*', 'audio/*', 'application/pdf',
    'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/vnd.oasis.opendocument.text', 'application/vnd.oasis.opendocument.spreadsheet',
    'application/vnd.oasis.opendocument.presentation', 'application/rtf', 'text/plain', 'text/csv'
])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create policy "Deal files of visible deals: select" on storage.objects for select to authenticated
    using (bucket_id = 'deal-files' and exists (select 1 from public.deals d where d.organization_id = (select private.current_organization_id()) and d.id = private.storage_deal_id(objects.name)));
create policy "Deal files of visible deals: insert" on storage.objects for insert to authenticated
    with check (bucket_id = 'deal-files' and exists (select 1 from public.deals d where d.organization_id = (select private.current_organization_id()) and d.id = private.storage_deal_id(objects.name)));
create policy "Deal files by owner, head or uploader: delete" on storage.objects for delete to authenticated
    using (bucket_id = 'deal-files' and ((select private.current_user_role()) in ('owner', 'head') or objects.owner = (select auth.uid())) and exists (select 1 from public.deals d where d.organization_id = (select private.current_organization_id()) and d.id = private.storage_deal_id(objects.name)));

-- Grants: no update (a file is replaced by a new one)
revoke all on table public.deal_files from anon, authenticated;
grant select, insert, delete on table public.deal_files to authenticated;
grant all on table public.deal_files to service_role;
revoke all on sequence public.deal_files_id_seq from anon, authenticated;
grant usage on sequence public.deal_files_id_seq to authenticated;
grant all on sequence public.deal_files_id_seq to service_role;

revoke all on function private.handle_deal_file_before_insert() from public;
revoke all on function private.handle_deal_patient_files() from public;

-- The note attachments of a clinic still referenced by a note: the cleanup
-- function (delete_note_attachments) removes only the others, whatever
-- paths its caller sends
create or replace function public.note_attachment_paths_in_use(org_id bigint, paths text[])
returns setof text
language sql stable security definer
set search_path to ''
as $$
  select p from unnest(paths) p
  where exists (
    select 1
    from (
      select n.attachments from public.deal_notes n where n.organization_id = org_id
      union all
      select n.attachments from public.patient_notes n where n.organization_id = org_id
    ) notes, unnest(notes.attachments) a
    where a ->> 'path' = p or a ->> 'src' like '%/' || p
  )
$$;
revoke all on function public.note_attachment_paths_in_use(bigint, text[]) from public, anon, authenticated;
grant execute on function public.note_attachment_paths_in_use(bigint, text[]) to service_role;
