--
-- Integrations marketplace, developer apps, fine API scopes and integrator
-- access (stage 25)
--
-- Developer apps («Приложения разработчиков»): an integrator (agency) or the
-- owner / head registers an app in the clinic — name, developer, links,
-- the scopes it needs and the webhook events it wants. Installing it
-- (public.install_developer_app) creates an API key bound to the app with
-- exactly these scopes (public.api_keys.app_id) and, with the scope
-- 'webhooks', a webhook subscription (public.webhooks.app_id). Uninstalling
-- revokes the key and deletes the webhooks. A manifest (JSON) carries the
-- same definition to other clinics (public.import_app_manifest).
--
-- Fine API scopes: api_keys.scopes lists them; a key without scopes is a key
-- of stage 20 and keeps its rights (read: deals:read, patients:read,
-- settings:read; write: plus deals:write and patients:write). Every public
-- api_* function asks private.api_authorize for the scope it needs.
--
-- Integrator (sales.role = 'integrator'): a technical account of an agency.
-- It configures the clinic (pipelines, stages, digital pipeline, automations,
-- auto-messages, quick replies, custom fields, integrations, API) and only
-- reads deals and patients; no money (payments, reports, plans), no staff,
-- no deleting. Message texts are hidden unless the owner turns on
-- sales.can_read_messages. After sales.access_expires_at the account
-- behaves as disabled (private.current_organization_id() and the other
-- helpers of 01_tables.sql return null). Rights are granted here, in one
-- place: permissive policies "Integrator can ..." next to the owner and head
-- ones for the configuration tables, restrictive policies "Integrators
-- cannot ..." / "Integrators do not see ..." on the operational tables.
--

--
-- Tables
--

-- Integrator access: until when, and whether the conversations are visible
alter table public.sales add column access_expires_at timestamp with time zone;
alter table public.sales add column can_read_messages boolean not null default false;

-- Fine scopes of a key (empty: the read / write key of stage 20) and the app
-- that owns it
alter table public.api_keys add column scopes text[] not null default '{}'::text[];
alter table public.api_keys add column app_id bigint;
alter table public.api_keys add constraint api_keys_scopes_check check (scopes <@ array['deals:read', 'deals:write',
    'patients:read', 'patients:write', 'messages:read', 'messages:write', 'tasks', 'settings:read', 'settings:write',
    'pipelines:write', 'salesbot:write', 'webhooks']::text[]);

-- Webhook subscription of an app (deleted with it)
alter table public.webhooks add column app_id bigint;

-- An app of a developer, registered in the clinic. slug: the id of its
-- manifest, the same in every clinic.
create table public.developer_apps (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    slug text not null,
    name text not null,
    description text,
    developer_name text not null,
    developer_contact text,
    website_url text,
    -- Page of the app where the clinic sets it up (opened from the catalog)
    settings_url text,
    scopes text[] not null default '{}'::text[],
    webhook_url text,
    webhook_events text[] not null default '{}'::text[],
    installed_at timestamp with time zone,
    installed_by bigint,
    api_key_id bigint,
    uninstalled_at timestamp with time zone,
    created_by bigint,
    created_at timestamp with time zone not null default now(),
    constraint developer_apps_slug_check check (slug ~ '^[a-z0-9][a-z0-9_-]{1,62}$'),
    constraint developer_apps_name_not_blank check (btrim(name) <> ''),
    constraint developer_apps_developer_not_blank check (btrim(developer_name) <> ''),
    constraint developer_apps_website_url_check check (website_url is null or website_url ~ '^https?://[^/\s]+'),
    constraint developer_apps_settings_url_check check (settings_url is null or settings_url ~ '^https?://[^/\s]+'),
    constraint developer_apps_webhook_url_check check (webhook_url is null or webhook_url ~ '^https?://[^/\s]+'),
    constraint developer_apps_scopes_check check (cardinality(scopes) > 0 and scopes <@ array['deals:read', 'deals:write',
        'patients:read', 'patients:write', 'messages:read', 'messages:write', 'tasks', 'settings:read', 'settings:write',
        'pipelines:write', 'salesbot:write', 'webhooks']::text[]),
    constraint developer_apps_webhook_events_check check (webhook_events <@ array['deal.created', 'deal.stage_changed',
        'deal.won', 'deal.lost', 'patient.created', 'message.received', 'payment.added', 'task.completed']::text[]),
    constraint developer_apps_webhook_check check (cardinality(webhook_events) = 0 or (webhook_url is not null and 'webhooks' = any(scopes))),
    constraint developer_apps_slug_key unique (organization_id, slug)
);

alter table public.developer_apps add constraint developer_apps_organization_id_id_key unique (organization_id, id);

alter table public.developer_apps
    add constraint developer_apps_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.developer_apps
    add constraint developer_apps_installed_by_fkey foreign key (organization_id, installed_by) references public.sales(organization_id, id) on delete set null (installed_by);
alter table public.developer_apps
    add constraint developer_apps_created_by_fkey foreign key (organization_id, created_by) references public.sales(organization_id, id) on delete set null (created_by);
alter table public.developer_apps
    add constraint developer_apps_api_key_id_fkey foreign key (organization_id, api_key_id) references public.api_keys(organization_id, id) on delete set null (api_key_id);
alter table public.api_keys
    add constraint api_keys_app_id_fkey foreign key (organization_id, app_id) references public.developer_apps(organization_id, id) on delete set null (app_id);
alter table public.webhooks
    add constraint webhooks_app_id_fkey foreign key (organization_id, app_id) references public.developer_apps(organization_id, id) on delete cascade;

create index api_keys_app_id_idx on public.api_keys using btree (organization_id, app_id) where app_id is not null;
create index webhooks_app_id_idx on public.webhooks using btree (organization_id, app_id) where app_id is not null;

--
-- Functions
--

-- Configuration rights: owner, head and integrator
CREATE OR REPLACE FUNCTION "private"."can_configure"() RETURNS boolean
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  return coalesce(private.current_user_role() in ('owner', 'head', 'integrator'), false);
end;
$$;

-- Message texts: every employee, an integrator only with «доступ к переписке»
CREATE OR REPLACE FUNCTION "private"."can_read_messages"() RETURNS boolean
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  return coalesce((
    select s.role <> 'integrator' or s.can_read_messages
    from public.sales s
    where s.user_id = auth.uid() and not s.disabled
      and (s.access_expires_at is null or s.access_expires_at > now())
  ), false);
end;
$$;

-- The owner sets the access of an integrator: until when (null: no limit)
-- and whether the conversations are visible
CREATE OR REPLACE FUNCTION "public"."set_integrator_access"("target_sales_id" bigint, "expires_at" timestamp with time zone, "read_messages" boolean) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
begin
  if org_id is null or private.current_user_role() is distinct from 'owner' then
    raise exception 'Доступ интегратора настраивает владелец клиники' using errcode = '42501';
  end if;
  update public.sales s
  set access_expires_at = expires_at, can_read_messages = coalesce(read_messages, false)
  where s.organization_id = org_id and s.id = target_sales_id and s.role = 'integrator';
  if not found then
    raise exception 'Интегратор не найден' using errcode = 'P0002';
  end if;
end;
$$;

-- Scopes of an API key: its own, or those of a stage 20 key
CREATE OR REPLACE FUNCTION "private"."api_key_scopes"("key_row" "public"."api_keys") RETURNS "text"[]
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select case
    when cardinality(key_row.scopes) > 0 then key_row.scopes
    when key_row.scope = 'write' then array['deals:read', 'deals:write', 'patients:read', 'patients:write', 'settings:read']
    else array['deals:read', 'patients:read', 'settings:read']
  end
$$;

-- The clinic of an API key that has the scope (see private.api_authenticate:
-- 401, 429). 403 read_only_key for a write with a read key of stage 20,
-- 403 insufficient_scope otherwise.
CREATE OR REPLACE FUNCTION "private"."api_authorize"("api_key" "text", "need_scope" "text") RETURNS "public"."api_keys"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  key_row public.api_keys := private.api_authenticate(api_key, false);
begin
  if need_scope = any(private.api_key_scopes(key_row)) then
    return key_row;
  end if;
  if cardinality(key_row.scopes) = 0 and key_row.scope = 'read' then
    raise exception 'Ключ только для чтения' using errcode = 'PT403', hint = 'read_only_key';
  end if;
  raise exception 'У ключа нет доступа %', need_scope using errcode = 'PT403', hint = 'insufficient_scope';
end;
$$;

-- Normalizes an app before it is saved; its scopes and webhook only change
-- while it is not installed (the key and the webhook were made from them)
CREATE OR REPLACE FUNCTION "private"."handle_developer_app_saved"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
begin
  new.slug := lower(btrim(new.slug));
  new.name := btrim(new.name);
  new.developer_name := btrim(new.developer_name);
  new.description := nullif(btrim(coalesce(new.description, '')), '');
  new.developer_contact := nullif(btrim(coalesce(new.developer_contact, '')), '');
  new.website_url := nullif(btrim(coalesce(new.website_url, '')), '');
  new.settings_url := nullif(btrim(coalesce(new.settings_url, '')), '');
  new.webhook_url := nullif(btrim(coalesce(new.webhook_url, '')), '');
  new.scopes := coalesce((select array_agg(distinct s order by s) from unnest(new.scopes) as s), '{}'::text[]);
  new.webhook_events := coalesce((select array_agg(distinct e order by e) from unnest(new.webhook_events) as e), '{}'::text[]);
  if tg_op = 'UPDATE' and old.installed_at is not null and new.installed_at is not null
    and (new.scopes is distinct from old.scopes or new.webhook_url is distinct from old.webhook_url
      or new.webhook_events is distinct from old.webhook_events or new.slug is distinct from old.slug) then
    raise exception 'Отключите приложение, чтобы изменить доступы или вебхук'
      using errcode = 'check_violation', hint = 'app_installed';
  end if;
  return new;
end;
$$;

-- A deleted app takes its webhooks (foreign key); its key is revoked
CREATE OR REPLACE FUNCTION "private"."handle_developer_app_deleted"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  update public.api_keys k
  set revoked_at = now()
  where k.organization_id = old.organization_id and k.app_id = old.id and k.revoked_at is null;
  return old;
end;
$$;

-- Installs an app (owner, head, integrator): an API key with the scopes of
-- the app and, with the scope 'webhooks', its webhook. Returns the key and
-- the webhook secret, once.
CREATE OR REPLACE FUNCTION "public"."install_developer_app"("target_app_id" bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  app public.developer_apps;
  new_key text := 'dcrm_' || replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', '');
  key_row public.api_keys;
  hook public.webhooks;
begin
  if org_id is null or not private.can_configure() then
    raise exception 'Приложения устанавливает владелец, руководитель или интегратор' using errcode = '42501';
  end if;
  select * into app from public.developer_apps a
  where a.organization_id = org_id and a.id = target_app_id
  for update;
  if not found then
    raise exception 'Приложение не найдено' using errcode = 'P0002';
  end if;
  if app.installed_at is not null then
    raise exception 'Приложение уже установлено' using errcode = 'check_violation', hint = 'app_installed';
  end if;

  insert into public.api_keys (organization_id, name, prefix, key_hash, scope, scopes, app_id, created_by)
  values (org_id, left('Приложение «' || app.name || '»', 200), left(new_key, 12), private.api_key_hash(new_key),
    case when exists (select 1 from unnest(app.scopes) as s where s like '%:write' or s in ('tasks', 'webhooks'))
      then 'write' else 'read' end,
    app.scopes, app.id, private.current_sales_id())
  returning * into key_row;

  if 'webhooks' = any(app.scopes) and app.webhook_url is not null and cardinality(app.webhook_events) > 0 then
    insert into public.webhooks (organization_id, name, url, events, app_id)
    values (org_id, left(app.name, 200), app.webhook_url, app.webhook_events, app.id)
    returning * into hook;
  end if;

  update public.developer_apps a
  set installed_at = now(), installed_by = private.current_sales_id(), api_key_id = key_row.id, uninstalled_at = null
  where a.id = app.id;

  return jsonb_build_object('app_id', app.id, 'key', new_key, 'key_prefix', key_row.prefix,
    'scopes', to_jsonb(key_row.scopes), 'webhook_id', hook.id, 'webhook_secret', hook.secret);
end;
$$;

-- Uninstalls an app: its key is revoked, its webhooks deleted
CREATE OR REPLACE FUNCTION "public"."uninstall_developer_app"("target_app_id" bigint) RETURNS boolean
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
begin
  if org_id is null or not private.can_configure() then
    raise exception 'Приложения отключает владелец, руководитель или интегратор' using errcode = '42501';
  end if;
  update public.developer_apps a
  set installed_at = null, api_key_id = null, uninstalled_at = now()
  where a.organization_id = org_id and a.id = target_app_id and a.installed_at is not null;
  if not found then
    return false;
  end if;
  update public.api_keys k
  set revoked_at = now()
  where k.organization_id = org_id and k.app_id = target_app_id and k.revoked_at is null;
  delete from public.webhooks w
  where w.organization_id = org_id and w.app_id = target_app_id;
  return true;
end;
$$;

-- An app from its manifest (JSON exported in another clinic): created, or
-- updated while it is not installed. Returns its id; installing is a
-- separate step (the scopes are shown to the user first).
--   { "manifest_version": 1, "id": "roistat-analytics", "name": "...",
--     "description": "...", "developer": { "name", "contact", "website" },
--     "settings_url": "https://...", "scopes": ["deals:read", ...],
--     "webhook": { "url": "https://...", "events": ["deal.created", ...] } }
CREATE OR REPLACE FUNCTION "public"."import_app_manifest"("manifest" "jsonb") RETURNS bigint
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  saved_id bigint;
  app_scopes text[];
  app_events text[];
begin
  if org_id is null or not private.can_configure() then
    raise exception 'Приложения добавляет владелец, руководитель или интегратор' using errcode = '42501';
  end if;
  if manifest is null or jsonb_typeof(manifest) <> 'object' then
    raise exception 'Манифест: ожидается JSON-объект' using errcode = '22023';
  end if;
  if coalesce(manifest ->> 'manifest_version', '1') <> '1' then
    raise exception 'Манифест: неизвестная версия %', manifest ->> 'manifest_version' using errcode = '22023';
  end if;
  if jsonb_typeof(manifest -> 'scopes') is distinct from 'array' then
    raise exception 'Манифест: scopes — массив доступов' using errcode = '22023';
  end if;
  if manifest ? 'webhook' and jsonb_typeof(manifest -> 'webhook') not in ('object', 'null') then
    raise exception 'Манифест: webhook — объект { url, events }' using errcode = '22023';
  end if;
  select coalesce(array_agg(x), '{}'::text[]) into app_scopes from jsonb_array_elements_text(manifest -> 'scopes') as x;
  select coalesce(array_agg(x), '{}'::text[]) into app_events
  from jsonb_array_elements_text(case when jsonb_typeof(manifest #> '{webhook,events}') = 'array'
    then manifest #> '{webhook,events}' else '[]'::jsonb end) as x;

  insert into public.developer_apps as a (organization_id, slug, name, description, developer_name, developer_contact,
    website_url, settings_url, scopes, webhook_url, webhook_events, created_by)
  values (org_id, coalesce(manifest ->> 'id', ''), coalesce(manifest ->> 'name', ''), manifest ->> 'description',
    coalesce(manifest #>> '{developer,name}', ''), manifest #>> '{developer,contact}', manifest #>> '{developer,website}',
    manifest ->> 'settings_url', app_scopes, manifest #>> '{webhook,url}', app_events, private.current_sales_id())
  on conflict (organization_id, slug) do update
    set name = excluded.name, description = excluded.description, developer_name = excluded.developer_name,
        developer_contact = excluded.developer_contact, website_url = excluded.website_url,
        settings_url = excluded.settings_url, scopes = excluded.scopes, webhook_url = excluded.webhook_url,
        webhook_events = excluded.webhook_events
    where a.installed_at is null
  returning a.id into saved_id;
  if saved_id is null then
    raise exception 'Приложение «%» уже установлено: отключите его, чтобы обновить', manifest ->> 'name'
      using errcode = 'check_violation', hint = 'app_installed';
  end if;
  return saved_id;
end;
$$;

--
-- Public REST API: configuration of the clinic (edge function api, service
-- role only). Same rules as stage 20: the clinic comes from the key, the
-- scope is checked, nothing outside the clinic is read or written.
--

-- A pipeline with its stages
CREATE OR REPLACE FUNCTION "private"."api_pipeline_json"("org_id" bigint, "target_pipeline_id" bigint) RETURNS "jsonb"
    LANGUAGE "sql" STABLE
    SET "search_path" TO ''
    AS $$
  select jsonb_build_object(
    'id', p.id, 'name', p.name, 'is_default', p.is_default, 'position', p.position,
    'stages', coalesce((
      select jsonb_agg(jsonb_build_object('id', s.id, 'pipeline_id', s.pipeline_id, 'name', s.name,
        'position', s.position, 'kind', s.kind, 'color', s.color, 'script', s.script) order by s.position, s.id)
      from public.stages s where s.organization_id = org_id and s.pipeline_id = p.id
    ), '[]'::jsonb))
  from public.pipelines p
  where p.organization_id = org_id and p.id = target_pipeline_id
$$;

-- GET /api/account: the clinic, its users and its pipelines
CREATE OR REPLACE FUNCTION "public"."api_get_account"("api_key" "text") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authorize(api_key, 'settings:read')).organization_id;
begin
  return jsonb_build_object('data', (
    select jsonb_build_object(
      'id', o.id, 'name', o.name, 'timezone', o.timezone, 'currency', o.currency,
      'users', coalesce((
        select jsonb_agg(jsonb_build_object('id', s.id, 'first_name', s.first_name, 'last_name', s.last_name,
          'email', s.email, 'role', s.role, 'disabled', s.disabled) order by s.id)
        from public.sales s where s.organization_id = org_id
      ), '[]'::jsonb),
      'pipelines', coalesce((
        select jsonb_agg(private.api_pipeline_json(org_id, p.id) order by p.position, p.id)
        from public.pipelines p where p.organization_id = org_id
      ), '[]'::jsonb))
    from public.organizations o where o.id = org_id));
end;
$$;

-- POST /api/pipelines { name, stages?: [{ name, kind, color }] }: without
-- stages, «Новый лид», «Успешно», «Отказ» (as in the settings)
CREATE OR REPLACE FUNCTION "public"."api_create_pipeline"("api_key" "text", "body" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authorize(api_key, 'pipelines:write')).organization_id;
  new_id bigint;
  item jsonb;
  item_position integer := 0;
begin
  if body is null or jsonb_typeof(body) <> 'object' then
    raise exception 'Ожидается JSON-объект' using errcode = '22023';
  end if;
  if nullif(btrim(coalesce(body ->> 'name', '')), '') is null then
    raise exception 'Укажите name' using errcode = '22023';
  end if;
  if body ? 'stages' and jsonb_typeof(body -> 'stages') <> 'array' then
    raise exception 'stages: ожидается массив этапов' using errcode = '22023';
  end if;
  insert into public.pipelines (organization_id, name, position)
  values (org_id, btrim(body ->> 'name'),
    coalesce((select max(p.position) + 1 from public.pipelines p where p.organization_id = org_id), 0))
  returning id into new_id;
  if jsonb_array_length(coalesce(body -> 'stages', '[]'::jsonb)) = 0 then
    insert into public.stages (organization_id, pipeline_id, name, position, kind, color)
    values
      (org_id, new_id, 'Новый лид', 0, 'open', '#83A2DB'),
      (org_id, new_id, 'Успешно', 1, 'won', '#8CC9A7'),
      (org_id, new_id, 'Отказ', 2, 'lost', '#FD8E8C');
  else
    for item in select * from jsonb_array_elements(body -> 'stages') loop
      insert into public.stages (organization_id, pipeline_id, name, position, kind, color)
      values (org_id, new_id, btrim(coalesce(item ->> 'name', '')), item_position, coalesce(item ->> 'kind', 'open'),
        coalesce(nullif(item ->> 'color', ''), '#83A2DB'));
      item_position := item_position + 1;
    end loop;
  end if;
  return jsonb_build_object('data', private.api_pipeline_json(org_id, new_id));
end;
$$;

-- PATCH /api/pipelines/:id { name, position, is_default }
CREATE OR REPLACE FUNCTION "public"."api_update_pipeline"("api_key" "text", "pipeline_id" bigint, "body" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authorize(api_key, 'pipelines:write')).organization_id;
begin
  if body is null or jsonb_typeof(body) <> 'object' then
    raise exception 'Ожидается JSON-объект' using errcode = '22023';
  end if;
  if not exists (select 1 from public.pipelines p where p.organization_id = org_id and p.id = api_update_pipeline.pipeline_id) then
    raise exception 'Воронка не найдена' using errcode = 'PT404', hint = 'not_found';
  end if;
  if (body ->> 'is_default')::boolean then
    update public.pipelines p set is_default = false
    where p.organization_id = org_id and p.is_default and p.id <> api_update_pipeline.pipeline_id;
  end if;
  update public.pipelines p
  set name = case when body ? 'name' then btrim(coalesce(body ->> 'name', '')) else p.name end,
      position = case when body ? 'position' then coalesce((body ->> 'position')::integer, 0) else p.position end,
      is_default = case when body ? 'is_default' then coalesce((body ->> 'is_default')::boolean, false) else p.is_default end
  where p.organization_id = org_id and p.id = api_update_pipeline.pipeline_id;
  return jsonb_build_object('data', private.api_pipeline_json(org_id, api_update_pipeline.pipeline_id));
end;
$$;

-- GET /api/stages?pipeline_id=
CREATE OR REPLACE FUNCTION "public"."api_list_stages"("api_key" "text", "params" "jsonb" DEFAULT '{}'::"jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authorize(api_key, 'settings:read')).organization_id;
  f_pipeline bigint := (params ->> 'pipeline_id')::bigint;
begin
  return jsonb_build_object('data', coalesce((
    select jsonb_agg(jsonb_build_object('id', s.id, 'pipeline_id', s.pipeline_id, 'name', s.name,
      'position', s.position, 'kind', s.kind, 'color', s.color, 'script', s.script)
      order by s.pipeline_id, s.position, s.id)
    from public.stages s
    where s.organization_id = org_id and (f_pipeline is null or s.pipeline_id = f_pipeline)
  ), '[]'::jsonb));
end;
$$;

-- POST /api/stages { pipeline_id, name, kind, color, position, script }:
-- without position, the stage goes before the won and lost stages
CREATE OR REPLACE FUNCTION "public"."api_create_stage"("api_key" "text", "body" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authorize(api_key, 'pipelines:write')).organization_id;
  target_pipeline bigint := (body ->> 'pipeline_id')::bigint;
  new_position integer;
  new_stage public.stages;
begin
  if body is null or jsonb_typeof(body) <> 'object' then
    raise exception 'Ожидается JSON-объект' using errcode = '22023';
  end if;
  if target_pipeline is null or not exists (
    select 1 from public.pipelines p where p.organization_id = org_id and p.id = target_pipeline
  ) then
    raise exception 'Воронка не найдена' using errcode = '23503';
  end if;
  new_position := coalesce((body ->> 'position')::integer, (
    select min(s.position) from public.stages s
    where s.organization_id = org_id and s.pipeline_id = target_pipeline and s.kind <> 'open'
  ), (select max(s.position) + 1 from public.stages s where s.organization_id = org_id and s.pipeline_id = target_pipeline), 0);
  -- Room for the new stage
  update public.stages s set position = s.position + 1
  where s.organization_id = org_id and s.pipeline_id = target_pipeline and s.position >= new_position;
  insert into public.stages (organization_id, pipeline_id, name, position, kind, color, script)
  values (org_id, target_pipeline, btrim(coalesce(body ->> 'name', '')), new_position, coalesce(body ->> 'kind', 'open'),
    coalesce(nullif(body ->> 'color', ''), '#83A2DB'), nullif(body ->> 'script', ''))
  returning * into new_stage;
  return jsonb_build_object('data', jsonb_build_object('id', new_stage.id, 'pipeline_id', new_stage.pipeline_id,
    'name', new_stage.name, 'position', new_stage.position, 'kind', new_stage.kind, 'color', new_stage.color,
    'script', new_stage.script));
end;
$$;

-- PATCH /api/stages/:id { name, kind, color, position, script }
CREATE OR REPLACE FUNCTION "public"."api_update_stage"("api_key" "text", "stage_id" bigint, "body" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authorize(api_key, 'pipelines:write')).organization_id;
  saved public.stages;
begin
  if body is null or jsonb_typeof(body) <> 'object' then
    raise exception 'Ожидается JSON-объект' using errcode = '22023';
  end if;
  update public.stages s
  set name = case when body ? 'name' then btrim(coalesce(body ->> 'name', '')) else s.name end,
      kind = case when body ? 'kind' then coalesce(body ->> 'kind', '') else s.kind end,
      color = case when body ? 'color' then coalesce(nullif(body ->> 'color', ''), s.color) else s.color end,
      position = case when body ? 'position' then coalesce((body ->> 'position')::integer, 0) else s.position end,
      script = case when body ? 'script' then nullif(body ->> 'script', '') else s.script end
  where s.organization_id = org_id and s.id = api_update_stage.stage_id
  returning * into saved;
  if not found then
    raise exception 'Этап не найден' using errcode = 'PT404', hint = 'not_found';
  end if;
  return jsonb_build_object('data', jsonb_build_object('id', saved.id, 'pipeline_id', saved.pipeline_id,
    'name', saved.name, 'position', saved.position, 'kind', saved.kind, 'color', saved.color, 'script', saved.script));
end;
$$;

-- A trigger of the digital pipeline as the API shows it
CREATE OR REPLACE FUNCTION "private"."api_stage_trigger_json"("trigger_row" "public"."stage_triggers") RETURNS "jsonb"
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select to_jsonb(trigger_row) - 'organization_id'
$$;

-- GET /api/stage_triggers?pipeline_id=&stage_id=
CREATE OR REPLACE FUNCTION "public"."api_list_stage_triggers"("api_key" "text", "params" "jsonb" DEFAULT '{}'::"jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authorize(api_key, 'settings:read')).organization_id;
  f_pipeline bigint := (params ->> 'pipeline_id')::bigint;
  f_stage bigint := (params ->> 'stage_id')::bigint;
begin
  return jsonb_build_object('data', coalesce((
    select jsonb_agg(private.api_stage_trigger_json(t) order by t.stage_id, t.position, t.id)
    from public.stage_triggers t
    where t.organization_id = org_id
      and (f_pipeline is null or t.pipeline_id = f_pipeline)
      and (f_stage is null or t.stage_id = f_stage)
  ), '[]'::jsonb));
end;
$$;

-- POST /api/stage_triggers: the columns of public.stage_triggers (stage_id,
-- event, action and the fields of the action; conditions optional)
CREATE OR REPLACE FUNCTION "public"."api_create_stage_trigger"("api_key" "text", "body" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authorize(api_key, 'pipelines:write')).organization_id;
  r public.stage_triggers;
  saved public.stage_triggers;
begin
  if body is null or jsonb_typeof(body) <> 'object' then
    raise exception 'Ожидается JSON-объект' using errcode = '22023';
  end if;
  r := jsonb_populate_record(null::public.stage_triggers, body);
  if r.stage_id is null or not exists (select 1 from public.stages s where s.organization_id = org_id and s.id = r.stage_id) then
    raise exception 'Этап не найден' using errcode = '23503';
  end if;
  insert into public.stage_triggers (organization_id, pipeline_id, stage_id, name, event, delay_minutes, source_ids,
    service_ids, doctor_ids, sales_ids, tags_present, tags_absent, action, target_stage_id, target_sales_id, tag_id,
    task_type, task_text, task_due_minutes, template_id, message_mode, webhook_id, field_name, plan_amount, doctor_id,
    service_id, is_active, position)
  values (org_id, (select s.pipeline_id from public.stages s where s.organization_id = org_id and s.id = r.stage_id),
    r.stage_id, r.name, r.event, coalesce(r.delay_minutes, 0), coalesce(r.source_ids, '{}'), coalesce(r.service_ids, '{}'),
    coalesce(r.doctor_ids, '{}'), coalesce(r.sales_ids, '{}'), coalesce(r.tags_present, '{}'), coalesce(r.tags_absent, '{}'),
    r.action, r.target_stage_id, r.target_sales_id, r.tag_id, r.task_type, r.task_text, r.task_due_minutes, r.template_id,
    r.message_mode, r.webhook_id, r.field_name, r.plan_amount, r.doctor_id, r.service_id, coalesce(r.is_active, true),
    coalesce(r.position, 0))
  returning * into saved;
  return jsonb_build_object('data', private.api_stage_trigger_json(saved));
end;
$$;

-- PATCH /api/stage_triggers/:id: only the fields present in the body change
CREATE OR REPLACE FUNCTION "public"."api_update_stage_trigger"("api_key" "text", "trigger_id" bigint, "body" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authorize(api_key, 'pipelines:write')).organization_id;
  current_row public.stage_triggers;
  r public.stage_triggers;
  saved public.stage_triggers;
begin
  if body is null or jsonb_typeof(body) <> 'object' then
    raise exception 'Ожидается JSON-объект' using errcode = '22023';
  end if;
  select * into current_row from public.stage_triggers t
  where t.organization_id = org_id and t.id = api_update_stage_trigger.trigger_id
  for update;
  if not found then
    raise exception 'Триггер не найден' using errcode = 'PT404', hint = 'not_found';
  end if;
  -- The current row, overwritten by the fields of the body
  r := jsonb_populate_record(current_row, body - 'id' - 'organization_id' - 'pipeline_id' - 'created_at');
  update public.stage_triggers t
  set stage_id = r.stage_id, name = r.name, event = r.event, delay_minutes = coalesce(r.delay_minutes, 0),
      source_ids = coalesce(r.source_ids, '{}'), service_ids = coalesce(r.service_ids, '{}'),
      doctor_ids = coalesce(r.doctor_ids, '{}'), sales_ids = coalesce(r.sales_ids, '{}'),
      tags_present = coalesce(r.tags_present, '{}'), tags_absent = coalesce(r.tags_absent, '{}'),
      action = r.action, target_stage_id = r.target_stage_id, target_sales_id = r.target_sales_id, tag_id = r.tag_id,
      task_type = r.task_type, task_text = r.task_text, task_due_minutes = r.task_due_minutes,
      template_id = r.template_id, message_mode = r.message_mode, webhook_id = r.webhook_id,
      field_name = r.field_name, plan_amount = r.plan_amount, doctor_id = r.doctor_id, service_id = r.service_id,
      is_active = coalesce(r.is_active, true), position = coalesce(r.position, 0)
  where t.organization_id = org_id and t.id = current_row.id
  returning * into saved;
  return jsonb_build_object('data', private.api_stage_trigger_json(saved));
end;
$$;

-- DELETE /api/stage_triggers/:id
CREATE OR REPLACE FUNCTION "public"."api_delete_stage_trigger"("api_key" "text", "trigger_id" bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authorize(api_key, 'pipelines:write')).organization_id;
begin
  delete from public.stage_triggers t
  where t.organization_id = org_id and t.id = api_delete_stage_trigger.trigger_id;
  if not found then
    raise exception 'Триггер не найден' using errcode = 'PT404', hint = 'not_found';
  end if;
  return jsonb_build_object('data', jsonb_build_object('id', api_delete_stage_trigger.trigger_id, 'deleted', true));
end;
$$;

-- GET /api/custom_fields?entity=deal|patient
CREATE OR REPLACE FUNCTION "public"."api_list_custom_fields"("api_key" "text", "params" "jsonb" DEFAULT '{}'::"jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authorize(api_key, 'settings:read')).organization_id;
  f_entity text := params ->> 'entity';
begin
  return jsonb_build_object('data', coalesce((
    select jsonb_agg(to_jsonb(f) - 'organization_id' order by f.entity, f.position, f.id)
    from public.custom_fields f
    where f.organization_id = org_id and (f_entity is null or f.entity = f_entity)
  ), '[]'::jsonb));
end;
$$;

-- POST /api/custom_fields { entity, name, type, options, required, show_on_card, position }
CREATE OR REPLACE FUNCTION "public"."api_create_custom_field"("api_key" "text", "body" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authorize(api_key, 'settings:write')).organization_id;
  saved public.custom_fields;
begin
  if body is null or jsonb_typeof(body) <> 'object' then
    raise exception 'Ожидается JSON-объект' using errcode = '22023';
  end if;
  insert into public.custom_fields (organization_id, entity, name, type, options, required, show_on_card, position)
  values (org_id, coalesce(body ->> 'entity', 'deal'), btrim(coalesce(body ->> 'name', '')), coalesce(body ->> 'type', 'text'),
    coalesce(body -> 'options', '[]'::jsonb), coalesce((body ->> 'required')::boolean, false),
    coalesce((body ->> 'show_on_card')::boolean, false),
    coalesce((body ->> 'position')::integer, (select coalesce(max(f.position) + 1, 0) from public.custom_fields f
      where f.organization_id = org_id and f.entity = coalesce(body ->> 'entity', 'deal'))))
  returning * into saved;
  return jsonb_build_object('data', to_jsonb(saved) - 'organization_id');
end;
$$;

-- GET /api/tasks?deal_id=&done=true|false&page=&per_page=
CREATE OR REPLACE FUNCTION "public"."api_list_tasks"("api_key" "text", "params" "jsonb" DEFAULT '{}'::"jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authorize(api_key, 'tasks')).organization_id;
  page_number integer := (private.api_page(params)).page;
  page_size integer := (private.api_page(params)).per_page;
  f_deal bigint := (params ->> 'deal_id')::bigint;
  f_done boolean := (params ->> 'done')::boolean;
  total bigint;
  items jsonb;
begin
  select count(*) into total from public.tasks t
  where t.organization_id = org_id and (f_deal is null or t.deal_id = f_deal)
    and (f_done is null or (t.done_date is not null) = f_done);
  select coalesce(jsonb_agg(x.j order by x.due_date, x.id), '[]'::jsonb) into items
  from (
    select t.id, t.due_date, jsonb_build_object('id', t.id, 'deal_id', t.deal_id, 'type', t.type, 'text', t.text,
      'due_date', t.due_date, 'done_date', t.done_date, 'sales_id', t.sales_id, 'duration_minutes', t.duration_minutes,
      'result', t.result, 'created_at', t.created_at) as j
    from public.tasks t
    where t.organization_id = org_id and (f_deal is null or t.deal_id = f_deal)
      and (f_done is null or (t.done_date is not null) = f_done)
    order by t.due_date, t.id
    limit page_size offset (page_number - 1) * page_size
  ) x;
  return jsonb_build_object('data', items,
    'meta', jsonb_build_object('page', page_number, 'per_page', page_size, 'total', total));
end;
$$;

-- POST /api/tasks { deal_id, type, text, due_date, sales_id, duration_minutes }:
-- without sales_id the task goes to the responsible of the deal
CREATE OR REPLACE FUNCTION "public"."api_create_task"("api_key" "text", "body" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authorize(api_key, 'tasks')).organization_id;
  deal public.deals;
  saved public.tasks;
begin
  if body is null or jsonb_typeof(body) <> 'object' then
    raise exception 'Ожидается JSON-объект' using errcode = '22023';
  end if;
  select * into deal from public.deals d where d.organization_id = org_id and d.id = (body ->> 'deal_id')::bigint;
  if not found then
    raise exception 'Сделка не найдена' using errcode = 'PT404', hint = 'not_found';
  end if;
  if nullif(btrim(coalesce(body ->> 'text', '')), '') is null then
    raise exception 'Укажите text' using errcode = '22023';
  end if;
  insert into public.tasks (organization_id, deal_id, type, text, due_date, sales_id, duration_minutes)
  values (org_id, deal.id, coalesce(body ->> 'type', 'call'), left(btrim(body ->> 'text'), 10000),
    coalesce((body ->> 'due_date')::timestamp with time zone, now() + interval '1 hour'),
    coalesce((body ->> 'sales_id')::bigint, deal.sales_id), (body ->> 'duration_minutes')::integer)
  returning * into saved;
  return jsonb_build_object('data', jsonb_build_object('id', saved.id, 'deal_id', saved.deal_id, 'type', saved.type,
    'text', saved.text, 'due_date', saved.due_date, 'done_date', saved.done_date, 'sales_id', saved.sales_id,
    'duration_minutes', saved.duration_minutes, 'created_at', saved.created_at));
end;
$$;

-- GET /api/messages?deal_id=&page=&per_page=: the conversation of a deal
CREATE OR REPLACE FUNCTION "public"."api_list_messages"("api_key" "text", "params" "jsonb" DEFAULT '{}'::"jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authorize(api_key, 'messages:read')).organization_id;
  page_number integer := (private.api_page(params)).page;
  page_size integer := (private.api_page(params)).per_page;
  f_deal bigint := (params ->> 'deal_id')::bigint;
  total bigint;
  items jsonb;
begin
  if f_deal is null then
    raise exception 'Укажите deal_id' using errcode = '22023';
  end if;
  select count(*) into total from public.messages m where m.organization_id = org_id and m.deal_id = f_deal;
  select coalesce(jsonb_agg(x.j order by x.sent_at, x.id), '[]'::jsonb) into items
  from (
    select m.id, m.sent_at, jsonb_build_object('id', m.id, 'deal_id', m.deal_id, 'patient_id', m.patient_id,
      'transport', m.transport, 'direction', m.direction, 'text', m.text, 'content_type', m.content_type,
      'status', m.status, 'sales_id', m.sales_id, 'sent_at', m.sent_at) as j
    from public.messages m
    where m.organization_id = org_id and m.deal_id = f_deal
    order by m.sent_at, m.id
    limit page_size offset (page_number - 1) * page_size
  ) x;
  return jsonb_build_object('data', items,
    'meta', jsonb_build_object('page', page_number, 'per_page', page_size, 'total', total));
end;
$$;

-- POST /api/messages { deal_id, text }: queued like an automatic message
-- (public.automessages without rule nor template, the text as given) and
-- sent within a minute by automessages_dispatch through the channel of the
-- conversation (Wazzup24 or the Telegram bot)
CREATE OR REPLACE FUNCTION "public"."api_send_message"("api_key" "text", "body" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := (private.api_authorize(api_key, 'messages:write')).organization_id;
  deal public.deals;
  message_text text := nullif(btrim(coalesce(body ->> 'text', '')), '');
  saved public.automessages;
begin
  if body is null or jsonb_typeof(body) <> 'object' then
    raise exception 'Ожидается JSON-объект' using errcode = '22023';
  end if;
  if message_text is null then
    raise exception 'Укажите text' using errcode = '22023';
  end if;
  if length(message_text) > 4000 then
    raise exception 'text: не длиннее 4000 символов' using errcode = '22023';
  end if;
  select * into deal from public.deals d where d.organization_id = org_id and d.id = (body ->> 'deal_id')::bigint;
  if not found then
    raise exception 'Сделка не найдена' using errcode = 'PT404', hint = 'not_found';
  end if;
  if not exists (
    select 1 from public.messenger_integrations i where i.organization_id = org_id and i.api_key is not null
  ) and not exists (
    select 1 from public.telegram_bots b where b.organization_id = org_id and b.bot_token is not null
  ) then
    raise exception 'Мессенджеры не подключены (Настройки → Мессенджеры)' using errcode = '23514';
  end if;
  insert into public.automessages (organization_id, deal_id, rule_id, template_id, stage_id, timing, send_at, text)
  values (org_id, deal.id, null, null, deal.stage_id, 'after_stage', now(), message_text)
  returning * into saved;
  return jsonb_build_object('data', jsonb_build_object('id', saved.id, 'deal_id', saved.deal_id,
    'status', 'queued', 'text', saved.text, 'send_at', saved.send_at));
end;
$$;

--
-- Triggers
--

create or replace trigger developer_app_saved
    before insert or update on public.developer_apps
    for each row execute function private.handle_developer_app_saved();

create or replace trigger developer_app_deleted
    before delete on public.developer_apps
    for each row execute function private.handle_developer_app_deleted();

create or replace trigger audit_developer_app
    after insert or update or delete on public.developer_apps
    for each row execute function private.audit_row('developer_app', 'slug,name,developer_name,scopes,webhook_url,webhook_events,installed_at,uninstalled_at');

--
-- Row Level Security
--

alter table public.developer_apps enable row level security;

create policy "Owner, head and integrator can read" on public.developer_apps for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.can_configure()));
create policy "Owner, head and integrator can insert" on public.developer_apps for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.can_configure()));
create policy "Owner, head and integrator can update" on public.developer_apps for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.can_configure()))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner, head and integrator can delete" on public.developer_apps for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.can_configure()));

-- Integrator: the configuration tables, next to the owner and head policies
create policy "Integrator can update" on public.organization_settings for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator')
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can update" on public.configuration for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator')
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');

create policy "Integrator can insert" on public.pipelines for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can update" on public.pipelines for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator')
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can delete" on public.pipelines for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');

create policy "Integrator can insert" on public.stages for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can update" on public.stages for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator')
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can delete" on public.stages for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');

create policy "Integrator can insert" on public.services for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can update" on public.services for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator')
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can delete" on public.services for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');

create policy "Integrator can insert" on public.lead_sources for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator' and not is_system and code is null);
create policy "Integrator can update" on public.lead_sources for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator')
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can delete" on public.lead_sources for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator' and not is_system);

create policy "Integrator can insert" on public.lost_reasons for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can update" on public.lost_reasons for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator')
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can delete" on public.lost_reasons for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');

create policy "Integrator can insert" on public.task_rules for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can update" on public.task_rules for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator')
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can delete" on public.task_rules for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');

create policy "Integrator can insert" on public.stage_checklist_items for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can update" on public.stage_checklist_items for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator')
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can delete" on public.stage_checklist_items for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');

create policy "Integrator can insert" on public.message_templates for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can update" on public.message_templates for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator')
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can delete" on public.message_templates for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');

create policy "Integrator can insert" on public.automessage_rules for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can update" on public.automessage_rules for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator')
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can delete" on public.automessage_rules for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');

create policy "Integrator can read" on public.lead_submissions for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');

create policy "Integrator can insert" on public.doctors for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can update" on public.doctors for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator')
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can delete" on public.doctors for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');

-- Clinic-wide quick replies (sales_id null); personal ones follow their policies
create policy "Integrator can insert" on public.quick_replies for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and sales_id is null and (select private.current_user_role()) = 'integrator');
create policy "Integrator can update" on public.quick_replies for update to authenticated
    using (organization_id = (select private.current_organization_id()) and sales_id is null and (select private.current_user_role()) = 'integrator')
    with check (organization_id = (select private.current_organization_id()) and sales_id is null and (select private.current_user_role()) = 'integrator');
create policy "Integrator can delete" on public.quick_replies for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and sales_id is null and (select private.current_user_role()) = 'integrator');

create policy "Integrator can insert" on public.recall_rules for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can update" on public.recall_rules for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator')
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can delete" on public.recall_rules for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');

create policy "Integrator can insert" on public.custom_fields for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can update" on public.custom_fields for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator')
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can delete" on public.custom_fields for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');

create policy "Integrator can insert" on public.stage_triggers for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can update" on public.stage_triggers for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator')
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can delete" on public.stage_triggers for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');

create policy "Integrator can read" on public.webhooks for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can insert" on public.webhooks for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can update" on public.webhooks for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator')
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can delete" on public.webhooks for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can read" on public.webhook_deliveries for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');
create policy "Integrator can read" on public.api_keys for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) = 'integrator');

-- Integrator: deals, patients and their rows are read-only
create policy "Integrators cannot insert" on public.patients as restrictive for insert to authenticated
    with check ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot update" on public.patients as restrictive for update to authenticated
    using ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot delete" on public.patients as restrictive for delete to authenticated
    using ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot insert" on public.patient_notes as restrictive for insert to authenticated
    with check ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot update" on public.patient_notes as restrictive for update to authenticated
    using ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot delete" on public.patient_notes as restrictive for delete to authenticated
    using ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot insert" on public.deals as restrictive for insert to authenticated
    with check ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot update" on public.deals as restrictive for update to authenticated
    using ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot delete" on public.deals as restrictive for delete to authenticated
    using ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot insert" on public.deal_notes as restrictive for insert to authenticated
    with check ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot update" on public.deal_notes as restrictive for update to authenticated
    using ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot delete" on public.deal_notes as restrictive for delete to authenticated
    using ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot insert" on public.tasks as restrictive for insert to authenticated
    with check ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot update" on public.tasks as restrictive for update to authenticated
    using ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot delete" on public.tasks as restrictive for delete to authenticated
    using ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot insert" on public.calls as restrictive for insert to authenticated
    with check ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot update" on public.calls as restrictive for update to authenticated
    using ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot delete" on public.calls as restrictive for delete to authenticated
    using ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot update" on public.messages as restrictive for update to authenticated
    using ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot insert" on public.deal_checklist_checks as restrictive for insert to authenticated
    with check ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot delete" on public.deal_checklist_checks as restrictive for delete to authenticated
    using ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot insert" on public.deal_files as restrictive for insert to authenticated
    with check ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot delete" on public.deal_files as restrictive for delete to authenticated
    using ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators cannot update" on public.automessages as restrictive for update to authenticated
    using ((select private.current_user_role()) is distinct from 'integrator');

-- Integrator: no money, no conversations without «доступ к переписке»
create policy "Integrators do not see payments" on public.deal_payments as restrictive for all to authenticated
    using ((select private.current_user_role()) is distinct from 'integrator');
create policy "Integrators see messages with access" on public.messages as restrictive for select to authenticated
    using ((select private.can_read_messages()));

--
-- Grants
--

-- Apps: the definition is written by the users, the installation by the functions
revoke all on table public.developer_apps from anon, authenticated;
grant select, delete on table public.developer_apps to authenticated;
grant insert (slug, name, description, developer_name, developer_contact, website_url, settings_url, scopes, webhook_url,
    webhook_events) on table public.developer_apps to authenticated;
grant update (slug, name, description, developer_name, developer_contact, website_url, settings_url, scopes, webhook_url,
    webhook_events) on table public.developer_apps to authenticated;
grant all on table public.developer_apps to service_role;
revoke all on sequence public.developer_apps_id_seq from anon;
grant all on sequence public.developer_apps_id_seq to authenticated, service_role;

-- The new columns of the keys are listed too (never the hash)
grant select (scopes, app_id) on table public.api_keys to authenticated;

revoke all on function private.can_configure() from public, anon;
grant execute on function private.can_configure() to authenticated, service_role;
revoke all on function private.can_read_messages() from public, anon;
grant execute on function private.can_read_messages() to authenticated, service_role;
revoke all on function public.set_integrator_access(bigint, timestamp with time zone, boolean) from public, anon;
grant execute on function public.set_integrator_access(bigint, timestamp with time zone, boolean) to authenticated, service_role;
revoke all on function public.install_developer_app(bigint) from public, anon;
grant execute on function public.install_developer_app(bigint) to authenticated, service_role;
revoke all on function public.uninstall_developer_app(bigint) from public, anon;
grant execute on function public.uninstall_developer_app(bigint) to authenticated, service_role;
revoke all on function public.import_app_manifest(jsonb) from public, anon;
grant execute on function public.import_app_manifest(jsonb) to authenticated, service_role;
revoke all on function private.handle_developer_app_deleted() from public, anon, authenticated;

-- API: service role only
revoke all on function private.api_key_scopes(public.api_keys) from public, anon, authenticated;
grant execute on function private.api_key_scopes(public.api_keys) to service_role;
revoke all on function private.api_authorize(text, text) from public, anon, authenticated;
grant execute on function private.api_authorize(text, text) to service_role;
revoke all on function private.api_pipeline_json(bigint, bigint) from public, anon, authenticated;
grant execute on function private.api_pipeline_json(bigint, bigint) to service_role;
revoke all on function private.api_stage_trigger_json(public.stage_triggers) from public, anon, authenticated;
grant execute on function private.api_stage_trigger_json(public.stage_triggers) to service_role;
revoke all on function public.api_get_account(text) from public, anon, authenticated;
grant execute on function public.api_get_account(text) to service_role;
revoke all on function public.api_create_pipeline(text, jsonb) from public, anon, authenticated;
grant execute on function public.api_create_pipeline(text, jsonb) to service_role;
revoke all on function public.api_update_pipeline(text, bigint, jsonb) from public, anon, authenticated;
grant execute on function public.api_update_pipeline(text, bigint, jsonb) to service_role;
revoke all on function public.api_list_stages(text, jsonb) from public, anon, authenticated;
grant execute on function public.api_list_stages(text, jsonb) to service_role;
revoke all on function public.api_create_stage(text, jsonb) from public, anon, authenticated;
grant execute on function public.api_create_stage(text, jsonb) to service_role;
revoke all on function public.api_update_stage(text, bigint, jsonb) from public, anon, authenticated;
grant execute on function public.api_update_stage(text, bigint, jsonb) to service_role;
revoke all on function public.api_list_stage_triggers(text, jsonb) from public, anon, authenticated;
grant execute on function public.api_list_stage_triggers(text, jsonb) to service_role;
revoke all on function public.api_create_stage_trigger(text, jsonb) from public, anon, authenticated;
grant execute on function public.api_create_stage_trigger(text, jsonb) to service_role;
revoke all on function public.api_update_stage_trigger(text, bigint, jsonb) from public, anon, authenticated;
grant execute on function public.api_update_stage_trigger(text, bigint, jsonb) to service_role;
revoke all on function public.api_delete_stage_trigger(text, bigint) from public, anon, authenticated;
grant execute on function public.api_delete_stage_trigger(text, bigint) to service_role;
revoke all on function public.api_list_custom_fields(text, jsonb) from public, anon, authenticated;
grant execute on function public.api_list_custom_fields(text, jsonb) to service_role;
revoke all on function public.api_create_custom_field(text, jsonb) from public, anon, authenticated;
grant execute on function public.api_create_custom_field(text, jsonb) to service_role;
revoke all on function public.api_list_tasks(text, jsonb) from public, anon, authenticated;
grant execute on function public.api_list_tasks(text, jsonb) to service_role;
revoke all on function public.api_create_task(text, jsonb) from public, anon, authenticated;
grant execute on function public.api_create_task(text, jsonb) to service_role;
revoke all on function public.api_list_messages(text, jsonb) from public, anon, authenticated;
grant execute on function public.api_list_messages(text, jsonb) to service_role;
revoke all on function public.api_send_message(text, jsonb) from public, anon, authenticated;
grant execute on function public.api_send_message(text, jsonb) to service_role;
