--
-- Treatment plans with an estimate («План лечения и смета», stage 29), the
-- price list and the light patient card
--
-- Elements of a MIS, not a MIS: no medical record, no tooth chart, no
-- inventory, no receipts. What a sales CRM of a dental clinic needs to sell
-- a treatment:
--
--   services               the price list: the same table as before (the
--                          deal's «Услуга» picker, reports), with a code, a
--                          category (free text with suggestions in the app)
--                          and the price of stage 24. «Активна» is
--                          not is_archived. Only the owner and the head (and
--                          the integrator of stage 25) edit it (05_policies).
--   treatment_plans        several plans per deal («Вариант эконом /
--                          премиум»): status draft → presented → agreed →
--                          in_progress → completed, or declined; discounts of
--                          the plan (percent and/or amount); the doctor
--                          (the deal's by default). The patient is the
--                          deal's (set by the trigger, moved with the deal).
--   treatment_plan_items   the positions: stage of the treatment (1..n,
--                          «Этап 1, 2…»), the service (optional) and its name
--                          (a copy, editable), the tooth as free text
--                          («36», «11-13»), quantity, unit price, discount,
--                          done. line_total is computed by the database.
--
-- Totals, in whole tenge (the TS twin is src/components/atomic-crm/treatment/
-- planMath.ts):
--   line_total = round(quantity × unit_price × (100 − discount %) / 100)
--   subtotal   = Σ line_total (per stage: public.treatment_plan_stages)
--   total      = max(0, subtotal − round(subtotal × plan discount % / 100)
--                − plan discount amount)      (private.treatment_plan_total)
-- public.treatment_plans_summary gives every plan with its totals and
-- progress (items done).
--
-- The main plan of the deal: a plan that becomes agreed is the deal's main
-- plan (is_main, one per deal: a unique index; the previous main plan keeps
-- its status). deals.plan_amount follows the total of the main plan (when
-- it is agreed, and when its items or discounts change), and the deal moves
-- forward to the stage «План согласован» of its pipeline when there is one,
-- with the rules of the digital pipeline: forward only, never out of a
-- closed deal; the stage checklist may refuse the move — the refusal is
-- written to the deal feed (stage_trigger_runs, without trigger). Marking
-- items done moves an agreed plan to in_progress, all items done to
-- completed.
--
-- Rights: whoever sees the deal sees its plans (not the integrator: no
-- money); owner, head and manager create and edit them. A discount above
-- organization_settings.max_discount_percent (10 % by default) — of an item,
-- or of the plan (percent and amount together, against its subtotal) — and
-- a price below the price list are for the owner and the head only.
--
-- The light patient card: allergies, contraindications, chronic diseases
-- (free text) and the preferred doctor. Merging patients keeps both texts.
--
-- Template variable {сумма_плана} (08_automessages.sql): the plan amount of
-- the deal, i.e. the total of its agreed plan.
--

alter table public.organization_settings add column max_discount_percent numeric(5,2) not null default 10;
alter table public.organization_settings add constraint organization_settings_max_discount_check
    check (max_discount_percent >= 0 and max_discount_percent <= 100);

-- The price list
alter table public.services add column code text;
alter table public.services add column category text;

-- The light patient card
alter table public.patients add column allergies text;
alter table public.patients add column contraindications text;
alter table public.patients add column chronic_diseases text;
alter table public.patients add column preferred_doctor_id bigint;

create table public.treatment_plans (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    deal_id bigint not null,
    -- The patient of the deal (set by the trigger)
    patient_id bigint not null,
    name text not null default 'План лечения',
    status text not null default 'draft',
    -- The agreed plan of the deal: its total is deals.plan_amount
    is_main boolean not null default false,
    discount_percent numeric(5,2) not null default 0,
    discount_amount bigint not null default 0,
    note text,
    doctor_id bigint,
    created_by bigint default private.current_sales_id(),
    agreed_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint treatment_plans_name_not_blank check (btrim(name) <> ''),
    constraint treatment_plans_status_check check (status in ('draft', 'presented', 'agreed', 'in_progress', 'completed', 'declined')),
    constraint treatment_plans_discount_percent_check check (discount_percent >= 0 and discount_percent <= 100),
    constraint treatment_plans_discount_amount_check check (discount_amount >= 0),
    constraint treatment_plans_main_is_agreed check (not is_main or status in ('agreed', 'in_progress', 'completed'))
);

create table public.treatment_plan_items (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    plan_id bigint not null,
    -- «Этап 1, 2…» of the treatment
    stage_no integer not null default 1,
    service_id bigint,
    -- A copy of the service name, editable
    name text not null,
    -- Tooth number(s) as free text: «36», «11-13» (no tooth chart)
    tooth text,
    quantity integer not null default 1,
    unit_price bigint not null default 0,
    discount_percent numeric(5,2) not null default 0,
    done boolean not null default false,
    done_at timestamp with time zone,
    position integer not null default 0,
    line_total bigint generated always as (round((quantity * unit_price)::numeric * (100 - discount_percent) / 100)::bigint) stored,
    created_at timestamp with time zone not null default now(),
    constraint treatment_plan_items_name_not_blank check (btrim(name) <> ''),
    constraint treatment_plan_items_stage_check check (stage_no >= 1 and stage_no <= 20),
    constraint treatment_plan_items_quantity_check check (quantity >= 1 and quantity <= 1000),
    constraint treatment_plan_items_price_check check (unit_price >= 0 and unit_price <= 1000000000),
    constraint treatment_plan_items_discount_check check (discount_percent >= 0 and discount_percent <= 100)
);

alter table public.treatment_plans add constraint treatment_plans_organization_id_id_key unique (organization_id, id);
alter table public.treatment_plan_items add constraint treatment_plan_items_organization_id_id_key unique (organization_id, id);

alter table public.treatment_plans
    add constraint treatment_plans_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.treatment_plans
    add constraint treatment_plans_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.treatment_plans
    add constraint treatment_plans_patient_id_fkey foreign key (organization_id, patient_id) references public.patients(organization_id, id) on delete cascade;
alter table public.treatment_plans
    add constraint treatment_plans_doctor_id_fkey foreign key (organization_id, doctor_id) references public.doctors(organization_id, id) on delete set null (doctor_id);
alter table public.treatment_plans
    add constraint treatment_plans_created_by_fkey foreign key (organization_id, created_by) references public.sales(organization_id, id) on delete set null (created_by);
alter table public.treatment_plan_items
    add constraint treatment_plan_items_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.treatment_plan_items
    add constraint treatment_plan_items_plan_id_fkey foreign key (organization_id, plan_id) references public.treatment_plans(organization_id, id) on delete cascade;
alter table public.treatment_plan_items
    add constraint treatment_plan_items_service_id_fkey foreign key (organization_id, service_id) references public.services(organization_id, id) on delete set null (service_id);
alter table public.patients
    add constraint patients_preferred_doctor_id_fkey foreign key (organization_id, preferred_doctor_id) references public.doctors(organization_id, id) on delete set null (preferred_doctor_id);

create index treatment_plans_deal_id_idx on public.treatment_plans using btree (organization_id, deal_id, created_at);
create index treatment_plans_patient_id_idx on public.treatment_plans using btree (organization_id, patient_id);
-- One main (agreed) plan per deal
create unique index treatment_plans_main_idx on public.treatment_plans using btree (organization_id, deal_id) where is_main;
create index treatment_plan_items_plan_id_idx on public.treatment_plan_items using btree (organization_id, plan_id, stage_no, position);
create index treatment_plan_items_service_id_idx on public.treatment_plan_items using btree (organization_id, service_id) where service_id is not null;

--
-- Functions
--

-- The total of a plan from its subtotal (Σ line_total) and its discounts,
-- whole tenge, never below zero. Twin: planTotal() in planMath.ts
CREATE OR REPLACE FUNCTION "private"."treatment_plan_total"("subtotal" bigint, "discount_percent" numeric, "discount_amount" bigint) RETURNS bigint
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select greatest(0, subtotal - round(subtotal * discount_percent / 100)::bigint - discount_amount);
$$;

-- «Хронические: …» of two merged patients: one text, or both
CREATE OR REPLACE FUNCTION "private"."merge_note_text"("kept" "text", "merged" "text") RETURNS "text"
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select case
    when nullif(btrim(kept), '') is null then nullif(btrim(merged), '')
    when nullif(btrim(merged), '') is null or btrim(merged) = btrim(kept) then kept
    else kept || E'\n' || btrim(merged)
  end;
$$;

-- The discount limit of the clinic, for an employee who is not the owner or
-- the head (a system write has no role: no limit). Raises 42501.
CREATE OR REPLACE FUNCTION "private"."check_treatment_discount"("org_id" bigint, "discount_percent" numeric, "subtotal" bigint, "discount_amount" bigint) RETURNS "void"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  role text := private.current_user_role();
  max_percent numeric;
begin
  if role is null or role in ('owner', 'head')
    or current_setting('crm.treatment_copy', true) = 'on' then
    return;
  end if;
  select s.max_discount_percent into max_percent
  from public.organization_settings s where s.organization_id = org_id;
  max_percent := coalesce(max_percent, 10);
  -- percent and amount together, against the subtotal
  if discount_percent > max_percent
    or coalesce(subtotal, 0) * discount_percent + coalesce(discount_amount, 0) * 100 > max_percent * coalesce(subtotal, 0) then
    raise exception 'Скидка больше % %% — только владелец или руководитель', trim_scale(max_percent)
      using errcode = '42501', hint = 'discount_limit';
  end if;
end;
$$;

-- deals.plan_amount = the total of the main plan of the deal
CREATE OR REPLACE FUNCTION "private"."sync_treatment_plan_amount"("target_plan_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  plan public.treatment_plans;
  total bigint;
begin
  select * into plan from public.treatment_plans p where p.id = target_plan_id;
  if not found or not plan.is_main then
    return;
  end if;
  select private.treatment_plan_total(coalesce(sum(i.line_total), 0)::bigint, plan.discount_percent, plan.discount_amount)
  into total
  from public.treatment_plan_items i
  where i.organization_id = plan.organization_id and i.plan_id = plan.id;
  update public.deals d
  set plan_amount = total
  where d.organization_id = plan.organization_id and d.id = plan.deal_id
    and d.plan_amount is distinct from total;
end;
$$;

-- An agreed plan moves its deal forward to «План согласован» of the deal's
-- pipeline (when the pipeline has it), like the digital pipeline: never
-- backwards, never out of a closed deal or «Неразобранное». A refused move
-- (stage checklist) is skipped and written to the deal feed.
CREATE OR REPLACE FUNCTION "private"."treatment_plan_move_stage"("plan" "public"."treatment_plans") RETURNS "text"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  deal public.deals;
  current_stage public.stages;
  target_stage public.stages;
  reason text;
  previous_source text := coalesce(current_setting('crm.audit_source', true), '');
begin
  if current_setting('crm.importing', true) = 'on' then
    return null;
  end if;
  select * into deal from public.deals d where d.organization_id = plan.organization_id and d.id = plan.deal_id;
  if not found or deal.archived_at is not null or deal.unsorted_at is not null then
    return null;
  end if;
  select * into current_stage from public.stages s where s.id = deal.stage_id;
  select * into target_stage from public.stages s
  where s.organization_id = deal.organization_id and s.pipeline_id = deal.pipeline_id
    and s.kind = 'open' and s.name = 'План согласован'
  order by s.position, s.id
  limit 1;
  if target_stage.id is null or current_stage.kind <> 'open'
    or target_stage.position <= current_stage.position then
    return null;
  end if;

  perform set_config('crm.audit_source', 'automation', true);
  begin
    update public.deals d
    set stage_id = target_stage.id
    where d.organization_id = deal.organization_id and d.id = deal.id;
  exception when others then
    get stacked diagnostics reason = message_text;
  end;
  perform set_config('crm.audit_source', previous_source, true);

  insert into public.stage_trigger_runs (organization_id, deal_id, trigger_id, trigger_name, event, event_key, action, status, details, error)
  values (deal.organization_id, deal.id, null, 'План лечения «' || plan.name || '»', 'treatment_plan',
    'treatment_plan:' || plan.id || ':' || extract(epoch from clock_timestamp()),
    'move_stage', case when reason is null then 'done' else 'skipped' end,
    jsonb_build_object('from_stage_id', deal.stage_id, 'to_stage_id', target_stage.id, 'plan_id', plan.id),
    left(reason, 500));
  return case when reason is null then 'done' else 'skipped' end;
end;
$$;

-- Before a plan is written: the patient and the doctor of the deal, the
-- status rules (agreed → main plan of the deal, agreed_at), the discount
-- limit
CREATE OR REPLACE FUNCTION "private"."handle_treatment_plan_before_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  deal public.deals;
  subtotal bigint;
begin
  if tg_op = 'UPDATE' and new.deal_id is distinct from old.deal_id then
    raise exception 'План лечения не переносится в другую сделку' using errcode = '22023';
  end if;
  select * into deal from public.deals d where d.organization_id = new.organization_id and d.id = new.deal_id;
  if tg_op = 'INSERT' then
    new.patient_id := deal.patient_id;
    new.doctor_id := coalesce(new.doctor_id, deal.doctor_id);
  end if;
  new.name := coalesce(nullif(btrim(new.name), ''), 'План лечения');

  if new.status in ('draft', 'presented', 'declined') then
    new.is_main := false;
    if new.status <> 'declined' then
      new.agreed_at := null;
    end if;
  elsif tg_op = 'INSERT' then
    new.agreed_at := coalesce(new.agreed_at, now());
    new.is_main := true;
  elsif old.status in ('draft', 'presented', 'declined') then
    -- Agreed now: the main plan of the deal
    new.agreed_at := now();
    new.is_main := true;
  end if;
  if new.is_main and (tg_op = 'INSERT' or not old.is_main) then
    update public.treatment_plans p
    set is_main = false
    where p.organization_id = new.organization_id and p.deal_id = new.deal_id
      and p.is_main and p.id <> new.id;
  end if;

  if (tg_op = 'INSERT' and (new.discount_percent > 0 or new.discount_amount > 0))
    or (tg_op = 'UPDATE' and (new.discount_percent <> old.discount_percent or new.discount_amount <> old.discount_amount)) then
    select coalesce(sum(i.line_total), 0) into subtotal
    from public.treatment_plan_items i
    where i.organization_id = new.organization_id and i.plan_id = new.id;
    perform private.check_treatment_discount(new.organization_id, new.discount_percent, subtotal, new.discount_amount);
  end if;
  new.updated_at := now();
  return new;
end;
$$;

-- After a plan is written: the plan amount of the deal, and the stage when
-- the plan was just agreed
CREATE OR REPLACE FUNCTION "private"."handle_treatment_plan_after_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if new.is_main and (tg_op = 'INSERT' or not old.is_main
    or new.discount_percent <> old.discount_percent or new.discount_amount <> old.discount_amount) then
    perform private.sync_treatment_plan_amount(new.id);
  end if;
  if new.status = 'agreed' and (tg_op = 'INSERT' or old.status in ('draft', 'presented', 'declined')) then
    perform private.treatment_plan_move_stage(new);
  end if;
  return null;
end;
$$;

-- Before an item is written: the name of the service, the done time, the
-- discount limit and the price list for the managers
CREATE OR REPLACE FUNCTION "private"."handle_treatment_item_before_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  role text := private.current_user_role();
  service public.services;
begin
  if tg_op = 'UPDATE' and new.plan_id is distinct from old.plan_id then
    raise exception 'Позиция не переносится в другой план' using errcode = '22023';
  end if;
  if new.service_id is not null then
    select * into service from public.services s
    where s.organization_id = new.organization_id and s.id = new.service_id;
  end if;
  new.name := coalesce(nullif(btrim(new.name), ''), service.name);
  new.tooth := nullif(btrim(new.tooth), '');
  if new.done and (tg_op = 'INSERT' or not old.done) then
    new.done_at := now();
  elsif not new.done then
    new.done_at := null;
  end if;

  if role is not null and role not in ('owner', 'head')
    and current_setting('crm.treatment_copy', true) is distinct from 'on' then
    if new.discount_percent > 0 and (tg_op = 'INSERT' or new.discount_percent <> old.discount_percent) then
      perform private.check_treatment_discount(new.organization_id, new.discount_percent, 0, 0);
    end if;
    if service.price is not null and new.unit_price < round(service.price)
      and (tg_op = 'INSERT' or new.unit_price <> old.unit_price or new.service_id is distinct from old.service_id) then
      raise exception 'Цена ниже прайса (% ₸) — только владелец или руководитель', private.format_tenge(service.price)
        using errcode = '42501', hint = 'price_below_list';
    end if;
  end if;
  return new;
end;
$$;

-- After items change: the progress of an agreed plan (some done: in
-- progress, all done: completed) and the plan amount of the deal
CREATE OR REPLACE FUNCTION "private"."handle_treatment_item_after_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := coalesce(new.organization_id, old.organization_id);
  target_plan_id bigint := coalesce(new.plan_id, old.plan_id);
  plan public.treatment_plans;
  total_items integer;
  done_items integer;
  next_status text;
begin
  select * into plan from public.treatment_plans p
  where p.organization_id = org_id and p.id = target_plan_id;
  if not found then
    return null;
  end if;
  if plan.status in ('agreed', 'in_progress', 'completed') then
    select count(*), count(*) filter (where i.done) into total_items, done_items
    from public.treatment_plan_items i
    where i.organization_id = org_id and i.plan_id = plan.id;
    next_status := case
      when total_items > 0 and done_items = total_items then 'completed'
      when plan.status = 'completed' then 'in_progress'
      when done_items > 0 and plan.status = 'agreed' then 'in_progress'
      else plan.status
    end;
    if next_status <> plan.status then
      update public.treatment_plans p set status = next_status
      where p.organization_id = org_id and p.id = plan.id;
    end if;
  end if;
  if plan.is_main then
    perform private.sync_treatment_plan_amount(plan.id);
  end if;
  return null;
end;
$$;

-- A deal moved to another patient (patients merged) takes its plans along
CREATE OR REPLACE FUNCTION "private"."handle_deal_patient_plans"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  update public.treatment_plans p
  set patient_id = new.patient_id
  where p.organization_id = new.organization_id and p.deal_id = new.id;
  return null;
end;
$$;

-- «Дублировать план»: a draft copy with the items (not done). Runs with the
-- caller's rights; the discounts are copied as they are.
CREATE OR REPLACE FUNCTION "public"."duplicate_treatment_plan"("source_plan_id" bigint) RETURNS bigint
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  source public.treatment_plans;
  new_plan_id bigint;
begin
  select * into source from public.treatment_plans p
  where p.organization_id = private.current_organization_id() and p.id = source_plan_id;
  if not found then
    raise exception 'План не найден' using errcode = 'P0002';
  end if;
  perform set_config('crm.treatment_copy', 'on', true);
  insert into public.treatment_plans (organization_id, deal_id, name, status, discount_percent, discount_amount, note, doctor_id)
  values (source.organization_id, source.deal_id, left(source.name, 180) || ' (копия)', 'draft',
    source.discount_percent, source.discount_amount, source.note, source.doctor_id)
  returning id into new_plan_id;
  insert into public.treatment_plan_items (organization_id, plan_id, stage_no, service_id, name, tooth, quantity, unit_price, discount_percent, position)
  select i.organization_id, new_plan_id, i.stage_no, i.service_id, i.name, i.tooth, i.quantity, i.unit_price, i.discount_percent, i.position
  from public.treatment_plan_items i
  where i.organization_id = source.organization_id and i.plan_id = source.id
  order by i.stage_no, i.position, i.id;
  perform set_config('crm.treatment_copy', '', true);
  return new_plan_id;
end;
$$;

-- Reports «Деньги» → «Согласованные планы по позициям»: the services of the
-- main plans agreed in the period, by sum (top 20). Same filters as the
-- other reports; owner and head only.
CREATE OR REPLACE FUNCTION "public"."report_plan_services"("period_from" timestamp with time zone DEFAULT NULL::timestamp with time zone, "period_to" timestamp with time zone DEFAULT NULL::timestamp with time zone, "filter_pipeline_id" bigint DEFAULT NULL::bigint, "filter_sales_id" bigint DEFAULT NULL::bigint, "filter_source_id" bigint DEFAULT NULL::bigint, "filter_doctor_id" bigint DEFAULT NULL::bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $$
begin
  perform private.report_check_access();
  return coalesce((
    select jsonb_agg(jsonb_build_object('service_id', r.service_id, 'name', r.name, 'quantity', r.quantity,
      'amount', r.amount, 'plans', r.plans) order by r.amount desc, r.name)
    from (
      select i.service_id, coalesce(sv.name, i.name) as name, sum(i.quantity)::bigint as quantity,
        sum(i.line_total)::bigint as amount, count(distinct p.id) as plans
      from public.treatment_plans p
        join public.deals d on d.organization_id = p.organization_id and d.id = p.deal_id
        join public.treatment_plan_items i on i.organization_id = p.organization_id and i.plan_id = p.id
        left join public.services sv on sv.organization_id = i.organization_id and sv.id = i.service_id
      where p.organization_id = private.current_organization_id()
        and p.is_main
        and (period_from is null or p.agreed_at >= period_from)
        and (period_to is null or p.agreed_at < period_to)
        and (filter_pipeline_id is null or d.pipeline_id = filter_pipeline_id)
        and (filter_sales_id is null or d.sales_id = filter_sales_id)
        and (filter_source_id is null or d.source_id = filter_source_id)
        and (filter_doctor_id is null or coalesce(p.doctor_id, d.doctor_id) = filter_doctor_id)
      group by i.service_id, coalesce(sv.name, i.name)
      order by amount desc, name
      limit 20
    ) r
  ), '[]'::jsonb);
end;
$$;

--
-- Views
--

-- The patients with the light patient card (first declared in
-- 19_custom_fields.sql; the new columns come last)
create or replace view public.patients_summary with (security_invoker = on) as
select
    p.id,
    p.organization_id,
    p.first_name,
    p.last_name,
    p.middle_name,
    p.phone_jsonb,
    p.phones,
    p.birth_date,
    p.city,
    p.whatsapp,
    p.instagram,
    p.telegram,
    p.source_id,
    p.tags,
    p.sales_id,
    p.gender,
    p.avatar,
    p.background,
    p.status,
    p.first_seen,
    p.last_seen,
    array_to_string(p.phones, ' ') as phone_fts,
    (
        select count(*)
        from public.deals d
        where d.organization_id = p.organization_id and d.patient_id = p.id
    ) as nb_deals,
    (
        select count(*)
        from public.deals d
            join public.stages s on s.id = d.stage_id
        where d.organization_id = p.organization_id and d.patient_id = p.id and s.kind = 'open'
    ) as nb_open_deals,
    (
        select count(*)
        from public.tasks t
            join public.deals d on d.organization_id = t.organization_id and d.id = t.deal_id
        where d.organization_id = p.organization_id and d.patient_id = p.id and t.done_date is null
    ) as nb_tasks,
    p.custom_values,
    p.allergies,
    p.contraindications,
    p.chronic_diseases,
    p.preferred_doctor_id
from public.patients p;

-- Plans with their totals and progress (deal page, patient card, estimate)
create or replace view public.treatment_plans_summary with (security_invoker = on) as
select
    tp.id,
    tp.organization_id,
    tp.deal_id,
    tp.patient_id,
    tp.name,
    tp.status,
    tp.is_main,
    tp.discount_percent,
    tp.discount_amount,
    tp.note,
    tp.doctor_id,
    tp.created_by,
    tp.agreed_at,
    tp.created_at,
    tp.updated_at,
    t.items_count,
    t.done_count,
    t.gross_amount,
    t.subtotal_amount,
    t.done_amount,
    private.treatment_plan_total(t.subtotal_amount, tp.discount_percent, tp.discount_amount) as total_amount,
    t.gross_amount - private.treatment_plan_total(t.subtotal_amount, tp.discount_percent, tp.discount_amount) as discount_total,
    d.name as deal_name,
    d.paid_amount as deal_paid_amount
from public.treatment_plans tp
    join public.deals d on d.organization_id = tp.organization_id and d.id = tp.deal_id
    cross join lateral (
        select
            count(i.id)::integer as items_count,
            (count(i.id) filter (where i.done))::integer as done_count,
            coalesce(sum(i.quantity * i.unit_price), 0)::bigint as gross_amount,
            coalesce(sum(i.line_total), 0)::bigint as subtotal_amount,
            coalesce(sum(i.line_total) filter (where i.done), 0)::bigint as done_amount
        from public.treatment_plan_items i
        where i.organization_id = tp.organization_id and i.plan_id = tp.id
    ) t;

-- Subtotal of every stage of a plan
create or replace view public.treatment_plan_stages with (security_invoker = on) as
select
    i.organization_id,
    i.plan_id,
    i.stage_no,
    count(*)::integer as items_count,
    (count(*) filter (where i.done))::integer as done_count,
    sum(i.line_total)::bigint as subtotal_amount
from public.treatment_plan_items i
group by i.organization_id, i.plan_id, i.stage_no;

--
-- Triggers
--

create or replace trigger treatment_plan_before_write
    before insert or update on public.treatment_plans
    for each row execute function private.handle_treatment_plan_before_write();

create or replace trigger treatment_plan_after_write
    after insert or update on public.treatment_plans
    for each row execute function private.handle_treatment_plan_after_write();

create or replace trigger treatment_item_before_write
    before insert or update on public.treatment_plan_items
    for each row execute function private.handle_treatment_item_before_write();

create or replace trigger treatment_item_after_write
    after insert or update or delete on public.treatment_plan_items
    for each row execute function private.handle_treatment_item_after_write();

create or replace trigger move_deal_plans_with_patient
    after update of patient_id on public.deals
    for each row
    when (old.patient_id is distinct from new.patient_id)
    execute function private.handle_deal_patient_plans();

-- Audit log
create or replace trigger audit_treatment_plan
    after insert or update or delete on public.treatment_plans
    for each row execute function private.audit_row('treatment_plan', 'name,status,is_main,discount_percent,discount_amount,doctor_id,note');

create or replace trigger audit_treatment_plan_item
    after insert or update or delete on public.treatment_plan_items
    for each row execute function private.audit_row('treatment_plan_item', 'name,stage_no,tooth,quantity,unit_price,discount_percent,done');

create or replace trigger audit_service
    after insert or update or delete on public.services
    for each row execute function private.audit_row('service', 'name,code,category,price,is_archived');

create or replace trigger audit_patient_medical
    after update on public.patients
    for each row execute function private.audit_row('patient', 'allergies,contraindications,chronic_diseases,preferred_doctor_id');

--
-- Row Level Security
--

alter table public.treatment_plans enable row level security;
alter table public.treatment_plan_items enable row level security;

-- Plans follow the visibility of their deal; the integrator sees no money
create policy "Rows of visible deals can be read" on public.treatment_plans for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) <> 'integrator'
        and exists (select 1 from public.deals d where d.organization_id = treatment_plans.organization_id and d.id = treatment_plans.deal_id));
create policy "Staff can insert on visible deals" on public.treatment_plans for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head', 'manager')
        and exists (select 1 from public.deals d where d.organization_id = treatment_plans.organization_id and d.id = treatment_plans.deal_id));
create policy "Staff can update on visible deals" on public.treatment_plans for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head', 'manager')
        and exists (select 1 from public.deals d where d.organization_id = treatment_plans.organization_id and d.id = treatment_plans.deal_id))
    with check (organization_id = (select private.current_organization_id()));
create policy "Staff can delete on visible deals" on public.treatment_plans for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head', 'manager')
        and exists (select 1 from public.deals d where d.organization_id = treatment_plans.organization_id and d.id = treatment_plans.deal_id));

-- Items follow their plan (the sub-query applies the plans policy)
create policy "Items of visible plans can be read" on public.treatment_plan_items for select to authenticated
    using (organization_id = (select private.current_organization_id())
        and exists (select 1 from public.treatment_plans p where p.organization_id = treatment_plan_items.organization_id and p.id = treatment_plan_items.plan_id));
create policy "Staff can insert items" on public.treatment_plan_items for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head', 'manager')
        and exists (select 1 from public.treatment_plans p where p.organization_id = treatment_plan_items.organization_id and p.id = treatment_plan_items.plan_id));
create policy "Staff can update items" on public.treatment_plan_items for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head', 'manager')
        and exists (select 1 from public.treatment_plans p where p.organization_id = treatment_plan_items.organization_id and p.id = treatment_plan_items.plan_id))
    with check (organization_id = (select private.current_organization_id()));
create policy "Staff can delete items" on public.treatment_plan_items for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head', 'manager')
        and exists (select 1 from public.treatment_plans p where p.organization_id = treatment_plan_items.organization_id and p.id = treatment_plan_items.plan_id));

--
-- Grants
--

revoke all on table public.treatment_plans from anon;
grant select, insert, update, delete on table public.treatment_plans to authenticated;
grant all on table public.treatment_plans to service_role;
revoke all on sequence public.treatment_plans_id_seq from anon;
grant usage on sequence public.treatment_plans_id_seq to authenticated;
grant all on sequence public.treatment_plans_id_seq to service_role;

revoke all on table public.treatment_plan_items from anon;
grant select, insert, update, delete on table public.treatment_plan_items to authenticated;
grant all on table public.treatment_plan_items to service_role;
revoke all on sequence public.treatment_plan_items_id_seq from anon;
grant usage on sequence public.treatment_plan_items_id_seq to authenticated;
grant all on sequence public.treatment_plan_items_id_seq to service_role;

revoke all on table public.treatment_plans_summary from anon;
grant select on table public.treatment_plans_summary to authenticated;
grant all on table public.treatment_plans_summary to service_role;
revoke all on table public.treatment_plan_stages from anon;
grant select on table public.treatment_plan_stages to authenticated;
grant all on table public.treatment_plan_stages to service_role;

revoke all on function private.check_treatment_discount(bigint, numeric, bigint, bigint) from public;
grant execute on function private.check_treatment_discount(bigint, numeric, bigint, bigint) to service_role;
revoke all on function private.sync_treatment_plan_amount(bigint) from public;
grant execute on function private.sync_treatment_plan_amount(bigint) to service_role;
revoke all on function private.treatment_plan_move_stage(public.treatment_plans) from public;
grant execute on function private.treatment_plan_move_stage(public.treatment_plans) to service_role;
revoke all on function private.handle_treatment_plan_before_write() from public;
revoke all on function private.handle_treatment_plan_after_write() from public;
revoke all on function private.handle_treatment_item_before_write() from public;
revoke all on function private.handle_treatment_item_after_write() from public;
revoke all on function private.handle_deal_patient_plans() from public;

revoke all on function public.duplicate_treatment_plan(bigint) from public, anon;
grant execute on function public.duplicate_treatment_plan(bigint) to authenticated, service_role;
revoke all on function public.report_plan_services(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint) from public, anon;
grant execute on function public.report_plan_services(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint) to authenticated;
grant execute on function public.report_plan_services(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint) to service_role;
