--
-- Marketing analytics («Маркетинговая аналитика», stage 32): the UTM tags of
-- a deal, the utm_source → lead source mapping, the ad spend, and the
-- report «Маркетинг» (spend, leads, cost per lead, came, paid, revenue, ROMI
-- per source and per campaign).
--
--   deals.utm_source … utm_term   the tags of the website form that brought
--   deals.referrer, landing_page  the request (public.ingest_lead: first touch,
--                                 an open deal keeps its tags), editable on
--                                 the deal page («Источник/UTM»)
--   lead_sources.utm_sources      utm_source values of a lead source
--                                 (Settings → Заявки с сайта): a deal with
--                                 such a utm_source gets that source
--   public.ad_spend               spend on advertising: a source, an optional
--                                 campaign (matched with deals.utm_campaign,
--                                 case-insensitive), a date range (a month
--                                 by default), an amount in tenge
--
-- utm_source → lead source (private.utm_lead_source): a source listing the
-- value in utm_sources, else a source whose code or name is the value
-- (utm_source=instagram → «Instagram»). In public.ingest_lead the mapped
-- source wins over the form's `source` field (the tag names the advert that
-- paid for the click); a deal written without a source (deal page, import)
-- gets it too (BEFORE trigger deal_attribution).
--
-- public.report_marketing(period_from, period_to, filter_source_id), in the
-- style of 09_reports.sql (owner and head only, periods half-open, dates of
-- money in the clinic's time zone). Per source, per campaign and in total:
--   spend    the ad spend of the period; a range crossing a bound of the
--            period counts pro rata of its days (rounded per row)
--   leads    deals created in the period
--   came     among them, deals that reached «Пришёл на консультацию» (the
--            key stage of the reports) or have a visit date (a visit of the
--            schedule marked «Пришёл» / «Приём завершён» sets it)
--   paid     among them, deals with a payment dated in the period
--   revenue  those payments
--   cpl, cost_per_came, cost_per_paid   spend / count (null without spend)
--   romi     (revenue − spend) / spend, in whole percent (null without spend)
-- The TS twin for the demo is src/components/atomic-crm/marketing/
-- marketingMath.ts.
--
-- Rights: the ad spend is money: the owner and the head read and write it
-- (RLS), like the reports; managers and the integrator see none of it. The
-- UTM tags of a deal follow the deal. The mapping is edited by whoever
-- edits the lead sources.
--

--
-- Tables and columns
--

alter table public.deals add column utm_source text;
alter table public.deals add column utm_medium text;
alter table public.deals add column utm_campaign text;
alter table public.deals add column utm_content text;
alter table public.deals add column utm_term text;
alter table public.deals add column referrer text;
alter table public.deals add column landing_page text;

alter table public.lead_sources add column utm_sources text[] not null default '{}'::text[];

create table public.ad_spend (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    source_id bigint not null,
    campaign text,
    spent_from date not null,
    spent_to date not null,
    -- Tenge
    amount bigint not null,
    comment text,
    sales_id bigint default private.current_sales_id(),
    created_at timestamp with time zone not null default now(),
    constraint ad_spend_amount_check check (amount >= 0),
    constraint ad_spend_period_check check (spent_to >= spent_from),
    constraint ad_spend_campaign_not_blank check (campaign is null or btrim(campaign) <> '')
);

alter table public.ad_spend add constraint ad_spend_organization_id_id_key unique (organization_id, id);

alter table public.ad_spend
    add constraint ad_spend_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.ad_spend
    add constraint ad_spend_source_id_fkey foreign key (organization_id, source_id) references public.lead_sources(organization_id, id) on delete cascade;
alter table public.ad_spend
    add constraint ad_spend_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id) on delete set null (sales_id);

create index ad_spend_period_idx on public.ad_spend using btree (organization_id, spent_from, spent_to);
create index deals_utm_campaign_idx on public.deals using btree (organization_id, lower(utm_campaign)) where utm_campaign is not null;

--
-- Functions
--

-- The lead source of an utm_source value: listed in a source's utm_sources,
-- else the code or the name of a source (case-insensitive); null if none
CREATE OR REPLACE FUNCTION "private"."utm_lead_source"("org_id" bigint, "utm_value" "text") RETURNS bigint
    LANGUAGE "sql" STABLE
    SET "search_path" TO ''
    AS $$
  select s.id
  from public.lead_sources s
  where s.organization_id = org_id
    and nullif(btrim(utm_value), '') is not null
    and (
      exists (select 1 from unnest(s.utm_sources) u where lower(btrim(u)) = lower(btrim(utm_value)))
      or lower(s.code) = lower(btrim(utm_value))
      or lower(s.name) = lower(btrim(utm_value))
    )
  order by
    exists (select 1 from unnest(s.utm_sources) u where lower(btrim(u)) = lower(btrim(utm_value))) desc,
    s.is_archived, s.position, s.id
  limit 1
$$;

-- UTM tags of a deal: trimmed (blank is null), at most 500 characters; a
-- deal without a source takes the one its utm_source maps to
CREATE OR REPLACE FUNCTION "private"."handle_deal_attribution"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
begin
  new.utm_source := left(nullif(btrim(new.utm_source), ''), 500);
  new.utm_medium := left(nullif(btrim(new.utm_medium), ''), 500);
  new.utm_campaign := left(nullif(btrim(new.utm_campaign), ''), 500);
  new.utm_content := left(nullif(btrim(new.utm_content), ''), 500);
  new.utm_term := left(nullif(btrim(new.utm_term), ''), 500);
  new.referrer := left(nullif(btrim(new.referrer), ''), 2000);
  new.landing_page := left(nullif(btrim(new.landing_page), ''), 2000);
  if new.source_id is null and new.utm_source is not null
    and (tg_op = 'INSERT' or new.utm_source is distinct from old.utm_source) then
    new.source_id := private.utm_lead_source(new.organization_id, new.utm_source);
  end if;
  return new;
end;
$$;

-- utm_sources of a lead source: trimmed, lower case, without blanks and
-- repeats
CREATE OR REPLACE FUNCTION "private"."handle_lead_source_utm"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
begin
  new.utm_sources := coalesce((
    select array_agg(v order by first_at)
    from (
      select lower(btrim(u)) as v, min(n) as first_at
      from unnest(new.utm_sources) with ordinality as t(u, n)
      where nullif(btrim(u), '') is not null
      group by lower(btrim(u))
    ) cleaned
  ), '{}'::text[]);
  return new;
end;
$$;

-- Marketing: spend, leads, came, paid, revenue, cost per lead / came /
-- paid and ROMI of the period, per source (with its campaigns) and in
-- total. See the header of this file.
CREATE OR REPLACE FUNCTION "public"."report_marketing"("period_from" timestamp with time zone DEFAULT NULL::timestamp with time zone, "period_to" timestamp with time zone DEFAULT NULL::timestamp with time zone, "filter_source_id" bigint DEFAULT NULL::bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  clinic_tz text;
  first_day date;
  after_last_day date;
  report jsonb;
begin
  perform private.report_check_access();
  select o.timezone into clinic_tz
  from public.organizations o
  where o.id = org_id;
  first_day := (period_from at time zone coalesce(clinic_tz, 'Asia/Almaty'))::date;
  after_last_day := (period_to at time zone coalesce(clinic_tz, 'Asia/Almaty'))::date;

  with spend as (
    -- A range crossing a bound of the period counts pro rata of its days
    select
      a.source_id,
      nullif(lower(btrim(a.campaign)), '') as campaign,
      round(
        a.amount::numeric
        * (least(a.spent_to + 1, coalesce(after_last_day, a.spent_to + 1)) - greatest(a.spent_from, coalesce(first_day, a.spent_from)))
        / (a.spent_to + 1 - a.spent_from)
      )::bigint as amount
    from public.ad_spend a
    where a.organization_id = org_id
      and (filter_source_id is null or a.source_id = filter_source_id)
      and (first_day is null or a.spent_to >= first_day)
      and (after_last_day is null or a.spent_from < after_last_day)
  ),
  leads as (
    select
      d.source_id,
      nullif(lower(btrim(dl.utm_campaign)), '') as campaign,
      (d.reached_visit or dl.visit_at is not null) as came,
      coalesce((
        select sum(p.amount)
        from public.deal_payments p
        where p.organization_id = org_id and p.deal_id = d.deal_id
          and (first_day is null or p.paid_at >= first_day)
          and (after_last_day is null or p.paid_at < after_last_day)
      ), 0) as revenue
    from private.report_deal_progress(null, null, filter_source_id, null) d
      join public.deals dl on dl.organization_id = org_id and dl.id = d.deal_id
    where (period_from is null or d.created_at >= period_from)
      and (period_to is null or d.created_at < period_to)
  ),
  facts as (
    select s.source_id, s.campaign, s.amount as spend, 0 as leads, 0 as came, 0 as paid, 0::numeric as revenue
    from spend s
    union all
    select l.source_id, l.campaign, 0, 1, l.came::integer, (l.revenue > 0)::integer, l.revenue
    from leads l
  ),
  grouped as (
    select
      grouping(f.source_id) as all_sources,
      grouping(f.campaign) as all_campaigns,
      f.source_id,
      f.campaign,
      coalesce(sum(f.spend), 0)::bigint as spend,
      coalesce(sum(f.leads), 0)::bigint as leads,
      coalesce(sum(f.came), 0)::bigint as came,
      coalesce(sum(f.paid), 0)::bigint as paid,
      coalesce(sum(f.revenue), 0)::bigint as revenue
    from facts f
    group by grouping sets ((), (f.source_id), (f.source_id, f.campaign))
  ),
  metrics as (
    select g.*, jsonb_build_object(
      'spend', g.spend,
      'leads', g.leads,
      'came', g.came,
      'paid', g.paid,
      'revenue', g.revenue,
      'cpl', case when g.spend > 0 and g.leads > 0 then round(g.spend::numeric / g.leads) end,
      'cost_per_came', case when g.spend > 0 and g.came > 0 then round(g.spend::numeric / g.came) end,
      'cost_per_paid', case when g.spend > 0 and g.paid > 0 then round(g.spend::numeric / g.paid) end,
      'romi', case when g.spend > 0 then round((g.revenue - g.spend)::numeric * 100 / g.spend) end
    ) as row_json
    from grouped g
  )
  select jsonb_build_object(
    -- The grand total row exists even without any fact
    'totals', (select m.row_json from metrics m where m.all_sources = 1),
    'by_source', (
      select coalesce(jsonb_agg(
        jsonb_build_object('id', m.source_id, 'name', ls.name) || m.row_json
        || jsonb_build_object('campaigns', (
          select coalesce(jsonb_agg(
            jsonb_build_object('campaign', c.campaign) || c.row_json
            order by c.spend desc, c.leads desc, c.campaign nulls last
          ), '[]'::jsonb)
          from metrics c
          where c.all_sources = 0 and c.all_campaigns = 0
            and c.source_id is not distinct from m.source_id
        ))
        order by m.spend desc, m.leads desc, ls.position, ls.id
      ), '[]'::jsonb)
      from metrics m
        left join public.lead_sources ls on ls.id = m.source_id
      where m.all_sources = 0 and m.all_campaigns = 1
    )
  ) into report;
  return report;
end;
$$;

--
-- Triggers
--

-- Before deal_before_write (alphabetical order): the source is set before
-- the distribution and the stage rules read it
create or replace trigger deal_attribution
    before insert or update on public.deals
    for each row execute function private.handle_deal_attribution();

create or replace trigger lead_source_utm
    before insert or update of utm_sources on public.lead_sources
    for each row execute function private.handle_lead_source_utm();

create or replace trigger audit_ad_spend
    after insert or update or delete on public.ad_spend
    for each row execute function private.audit_row('ad_spend', 'source_id,campaign,spent_from,spent_to,amount,comment');

--
-- Views
--

-- deals_summary of 19_custom_fields.sql with the UTM tags at the end
create or replace view public.deals_summary with (security_invoker = on) as
select
    d.id,
    d.organization_id,
    d.patient_id,
    d.pipeline_id,
    d.stage_id,
    d.name,
    d.source_id,
    d.service_id,
    d.plan_amount,
    d.paid_amount,
    d.sales_id,
    d.lost_reason_id,
    d.lost_comment,
    d.appointment_at,
    d.visit_at,
    d.tags,
    d.description,
    d.index,
    d.created_at,
    d.updated_at,
    d.stage_changed_at,
    d.closed_at,
    d.first_response_at,
    d.archived_at,
    s.kind as stage_kind,
    p.first_name as patient_first_name,
    p.last_name as patient_last_name,
    p.phones[1] as patient_phone,
    lower(concat_ws(' ', d.name, p.last_name, p.first_name, p.middle_name, array_to_string(p.phones, ' '))) as search_text,
    (
        select count(*)
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
    ) as nb_open_tasks,
    (
        select min(t.due_date)
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
    ) as next_task_due_at,
    (
        select count(*)
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id and m.direction = 'in' and m.read_at is null
    ) as nb_unread_messages,
    (
        select max(m.sent_at)
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id
    ) as last_message_at,
    (
        select m.text
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id
        order by m.sent_at desc, m.id desc
        limit 1
    ) as last_message_text,
    d.doctor_id,
    dr.name as doctor_name,
    d.consultation_amount,
    (
        select coalesce(sum(pay.amount), 0)::bigint
        from public.deal_payments pay
        where pay.organization_id = d.organization_id and pay.deal_id = d.id and pay.kind = 'prepayment'
    ) as prepayment_amount,
    d.unsorted_at,
    d.custom_values,
    -- Deal list (stage 21): the latest change or message, the nearest open task
    greatest(d.updated_at, (
        select max(m.sent_at)
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id
    )) as last_activity_at,
    (
        select t.text
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
        order by t.due_date, t.id
        limit 1
    ) as next_task_text,
    d.utm_source,
    d.utm_medium,
    d.utm_campaign,
    d.utm_content,
    d.utm_term,
    d.referrer,
    d.landing_page
from public.deals d
    join public.stages s on s.id = d.stage_id
    join public.patients p on p.organization_id = d.organization_id and p.id = d.patient_id
    left join public.doctors dr on dr.organization_id = d.organization_id and dr.id = d.doctor_id;

--
-- Row level security
--

alter table public.ad_spend enable row level security;

-- Money: the owner and the head only, like the reports
create policy "Owner and head can read" on public.ad_spend for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can insert" on public.ad_spend for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can update" on public.ad_spend for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head can delete" on public.ad_spend for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

--
-- Grants
--

revoke all on table public.ad_spend from anon;
grant select, insert, update, delete on table public.ad_spend to authenticated;
grant all on table public.ad_spend to service_role;
revoke all on sequence public.ad_spend_id_seq from anon;
grant usage, select on sequence public.ad_spend_id_seq to authenticated;
grant all on sequence public.ad_spend_id_seq to service_role;

-- The utm_source values of a lead source (its code stays fixed)
grant update (utm_sources) on table public.lead_sources to authenticated;

revoke all on function private.utm_lead_source(bigint, text) from public;
grant execute on function private.utm_lead_source(bigint, text) to authenticated, service_role;
revoke all on function public.report_marketing(timestamp with time zone, timestamp with time zone, bigint) from public, anon;
grant execute on function public.report_marketing(timestamp with time zone, timestamp with time zone, bigint) to authenticated;
grant execute on function public.report_marketing(timestamp with time zone, timestamp with time zone, bigint) to service_role;
