--
-- Branches «Филиалы» (stage 33): a clinic network with several addresses.
--
--   public.branches          dictionary of the clinic: name, address, phone,
--                            active switch, order (owner and head)
--   public.sales_branches    the branches an employee works in (one or several)
--   branch_id                of a deal (where the patient goes), a doctor, a
--                            chair, a visit, a task (the branch of its deal,
--                            kept by triggers, for the lists) and a messenger
--                            channel (new leads of the channel land there)
--
-- Nullable everywhere: a clinic without branches (or with one) works exactly
-- as before, the interface shows the branches from the second one on. A row
-- without a branch is «общий»: a doctor or a chair of every branch, a deal
-- or a visit of the whole network (a lead of a channel mapped to no branch).
-- No default branch is created: every writer (forms, import, API, salesbot,
-- MIS) keeps working without knowing about branches, and nothing is moved
-- in existing clinics. When a clinic opens its second address, the owner
-- attaches the existing deals and visits to the first branch in one click
-- (public.assign_branch_to_unassigned).
--
-- The branch of a new deal: the one given (deal form, website form field
-- `branch`, the channel of a message, the clinic number of a call), else the
-- doctor's, else the branch of its responsible (or of the employee creating
-- it) when they work in one branch only (trigger deal_assign_branch, before
-- the distribution). A visit takes the branch of its chair, else of its
-- doctor, else of its deal.
--
-- Leads of a branch are distributed among the chosen employees who work in
-- that branch (round robin, «first to answer», notifications); when none of
-- them does, among all the chosen ones (private.branch_pool), so no lead is
-- lost.
--
-- Rights: the scope «Мой филиал» ('branch', 30_access_rights.sql) for deals
-- and tasks: own rows, rows of the employee's branches and rows without a
-- branch (private.current_branch_ids(), declared in 01_tables.sql because
-- the policies of 05_policies.sql use it). Patients are shared by the
-- network (one card). The dictionary and the employees' branches: the owner
-- and the head write, everybody reads. A channel's branch: the owner and the
-- head (column grant).
--
-- Reports take an optional filter_branch_id (09_reports.sql,
-- 29_treatment_plans.sql).
--

--
-- Tables and columns
--

create table public.branches (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    address text,
    phone text,
    is_active boolean not null default true,
    position integer not null default 0,
    created_at timestamp with time zone not null default now(),
    constraint branches_name_not_blank check (btrim(name) <> ''),
    constraint branches_address_length check (address is null or char_length(address) <= 500),
    constraint branches_phone_length check (phone is null or char_length(phone) <= 50)
);

create table public.sales_branches (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    sales_id bigint not null,
    branch_id bigint not null,
    created_at timestamp with time zone not null default now(),
    constraint sales_branches_key unique (organization_id, sales_id, branch_id)
);

alter table public.branches add constraint branches_organization_id_id_key unique (organization_id, id);

alter table public.deals add column branch_id bigint;
alter table public.doctors add column branch_id bigint;
alter table public.chairs add column branch_id bigint;
alter table public.visits add column branch_id bigint;
alter table public.tasks add column branch_id bigint;
alter table public.messenger_channels add column branch_id bigint;

alter table public.branches
    add constraint branches_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.sales_branches
    add constraint sales_branches_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id) on delete cascade;
alter table public.sales_branches
    add constraint sales_branches_branch_id_fkey foreign key (organization_id, branch_id) references public.branches(organization_id, id) on delete cascade;
-- A branch with deals, visits or tasks cannot be deleted (switch it off);
-- doctors, chairs and channels become «общие»
alter table public.deals
    add constraint deals_branch_id_fkey foreign key (organization_id, branch_id) references public.branches(organization_id, id);
alter table public.visits
    add constraint visits_branch_id_fkey foreign key (organization_id, branch_id) references public.branches(organization_id, id);
alter table public.tasks
    add constraint tasks_branch_id_fkey foreign key (organization_id, branch_id) references public.branches(organization_id, id);
alter table public.doctors
    add constraint doctors_branch_id_fkey foreign key (organization_id, branch_id) references public.branches(organization_id, id) on delete set null (branch_id);
alter table public.chairs
    add constraint chairs_branch_id_fkey foreign key (organization_id, branch_id) references public.branches(organization_id, id) on delete set null (branch_id);
alter table public.messenger_channels
    add constraint messenger_channels_branch_id_fkey foreign key (organization_id, branch_id) references public.branches(organization_id, id) on delete set null (branch_id);

create index branches_organization_id_idx on public.branches using btree (organization_id, position);
create index sales_branches_branch_id_idx on public.sales_branches using btree (organization_id, branch_id);
create index deals_branch_id_idx on public.deals using btree (organization_id, branch_id) where branch_id is not null;
create index visits_branch_id_idx on public.visits using btree (organization_id, branch_id) where branch_id is not null;
create index tasks_branch_id_idx on public.tasks using btree (organization_id, branch_id) where branch_id is not null;

--
-- Functions
--

-- A branch of the clinic by its id or its name (case-insensitive; an active
-- one first), null when nothing matches: the `branch` field of a website form
CREATE OR REPLACE FUNCTION "private"."find_branch"("org_id" bigint, "value" "text") RETURNS bigint
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  wanted text := nullif(btrim(value), '');
begin
  if wanted is null then
    return null;
  end if;
  return (
    select b.id
    from public.branches b
    where b.organization_id = org_id
      and (lower(btrim(b.name)) = lower(wanted) or (wanted ~ '^[0-9]{1,18}$' and b.id = wanted::bigint))
    order by b.is_active desc, b.position, b.id
    limit 1
  );
end;
$$;

-- The employees a lead of a branch goes to, among the candidates (in their
-- order): those who work in the branch; all the candidates when the lead has
-- no branch or none of them works there
CREATE OR REPLACE FUNCTION "private"."branch_pool"("org_id" bigint, "branch" bigint, "candidates" bigint[]) RETURNS bigint[]
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  in_branch bigint[];
begin
  if branch is null or candidates is null then
    return coalesce(candidates, '{}'::bigint[]);
  end if;
  select coalesce(array_agg(c.sales_id order by c.position), '{}'::bigint[]) into in_branch
  from unnest(candidates) with ordinality as c(sales_id, position)
  where exists (
    select 1 from public.sales_branches sb
    where sb.organization_id = org_id and sb.sales_id = c.sales_id and sb.branch_id = branch
  );
  return case when cardinality(in_branch) > 0 then in_branch else candidates end;
end;
$$;

-- The branch of a deal written without one: the doctor's, else (a new deal)
-- the branch of its responsible, or of the employee creating it, when they
-- work in one branch only. Runs before deal_attribution and deal_before_write
-- (alphabetical order): the distribution knows the branch. An explicit
-- branch, or a branch removed by hand, is kept.
CREATE OR REPLACE FUNCTION "private"."handle_deal_branch"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  responsible bigint;
begin
  if new.branch_id is not null then
    return new;
  end if;
  if tg_op = 'UPDATE' and (old.branch_id is not null or new.doctor_id is not distinct from old.doctor_id) then
    return new;
  end if;
  if new.doctor_id is not null then
    select d.branch_id into new.branch_id
    from public.doctors d
    where d.organization_id = new.organization_id and d.id = new.doctor_id;
  end if;
  if new.branch_id is null and tg_op = 'INSERT' then
    responsible := coalesce(new.sales_id, private.current_sales_id());
    if responsible is not null then
      select min(sb.branch_id) into new.branch_id
      from public.sales_branches sb
      where sb.organization_id = new.organization_id and sb.sales_id = responsible
      having count(*) = 1;
    end if;
  end if;
  return new;
end;
$$;

-- The tasks of a deal follow its branch
CREATE OR REPLACE FUNCTION "private"."handle_deal_branch_changed"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  update public.tasks t
  set branch_id = new.branch_id
  where t.organization_id = new.organization_id and t.deal_id = new.id
    and t.branch_id is distinct from new.branch_id;
  return null;
end;
$$;

-- tasks.branch_id is always the branch of the task's deal (the lists filter
-- on it, the policies of «Мой филиал» read it)
CREATE OR REPLACE FUNCTION "private"."handle_task_branch"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  new.branch_id := (
    select d.branch_id
    from public.deals d
    where d.organization_id = new.organization_id and d.id = new.deal_id
  );
  return new;
end;
$$;

-- The branch of a visit: the one chosen, else of its chair, else of its
-- doctor, else of its deal; moving the visit to another chair or doctor
-- takes their branch
CREATE OR REPLACE FUNCTION "private"."handle_visit_branch"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if tg_op = 'INSERT' and new.branch_id is not null then
    return new;
  end if;
  if tg_op = 'UPDATE' and (
    new.branch_id is distinct from old.branch_id
    or (new.chair_id is not distinct from old.chair_id and new.doctor_id is not distinct from old.doctor_id)
  ) then
    return new;
  end if;
  new.branch_id := coalesce(
    (select c.branch_id from public.chairs c where c.organization_id = new.organization_id and c.id = new.chair_id),
    (select d.branch_id from public.doctors d where d.organization_id = new.organization_id and d.id = new.doctor_id),
    case when tg_op = 'UPDATE' then new.branch_id end,
    (select d.branch_id from public.deals d where d.organization_id = new.organization_id and d.id = new.deal_id)
  );
  return new;
end;
$$;

-- «Привязать к филиалу»: the deals and visits without a branch go to this
-- one (a clinic opening its second address). Owner and head. A system write:
-- no automations, no notifications. Returns { deals, visits }.
CREATE OR REPLACE FUNCTION "public"."assign_branch_to_unassigned"("target_branch_id" bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  moved_deals integer;
  moved_visits integer;
  previous_importing text := current_setting('crm.importing', true);
  previous_notifications text := current_setting('crm.notifications', true);
begin
  if org_id is null or private.current_user_role() is distinct from 'owner'
    and private.current_user_role() is distinct from 'head' then
    raise exception 'Филиалы настраивают владелец и руководитель'
      using errcode = '42501', hint = 'branches_forbidden';
  end if;
  if not exists (select 1 from public.branches b where b.organization_id = org_id and b.id = target_branch_id) then
    raise exception 'Филиал не найден' using errcode = '22023', hint = 'branches_not_found';
  end if;
  perform set_config('crm.importing', 'on', true);
  perform set_config('crm.notifications', 'off', true);
  update public.deals d
  set branch_id = target_branch_id
  where d.organization_id = org_id and d.branch_id is null;
  get diagnostics moved_deals = row_count;
  update public.visits v
  set branch_id = target_branch_id
  where v.organization_id = org_id and v.branch_id is null;
  get diagnostics moved_visits = row_count;
  perform set_config('crm.importing', coalesce(previous_importing, ''), true);
  perform set_config('crm.notifications', coalesce(previous_notifications, ''), true);
  return jsonb_build_object('deals', moved_deals, 'visits', moved_visits);
end;
$$;

--
-- Triggers
--

-- Before deal_attribution and deal_before_write (alphabetical order)
create or replace trigger deal_assign_branch
    before insert or update on public.deals
    for each row execute function private.handle_deal_branch();

create or replace trigger deal_branch_changed
    after update of branch_id on public.deals
    for each row
    when (old.branch_id is distinct from new.branch_id)
    execute function private.handle_deal_branch_changed();

create or replace trigger task_branch
    before insert or update of deal_id, branch_id on public.tasks
    for each row execute function private.handle_task_branch();

create or replace trigger visit_branch
    before insert or update on public.visits
    for each row execute function private.handle_visit_branch();

create or replace trigger audit_branch
    after insert or update or delete on public.branches
    for each row execute function private.audit_row('branch', 'name,address,phone,is_active');

--
-- Views
--

-- deals_summary of 32_marketing.sql with the branch at the end
create or replace view public.deals_summary with (security_invoker = on) as
select
    d.id,
    d.organization_id,
    d.patient_id,
    d.pipeline_id,
    d.stage_id,
    d.name,
    d.source_id,
    d.service_id,
    d.plan_amount,
    d.paid_amount,
    d.sales_id,
    d.lost_reason_id,
    d.lost_comment,
    d.appointment_at,
    d.visit_at,
    d.tags,
    d.description,
    d.index,
    d.created_at,
    d.updated_at,
    d.stage_changed_at,
    d.closed_at,
    d.first_response_at,
    d.archived_at,
    s.kind as stage_kind,
    p.first_name as patient_first_name,
    p.last_name as patient_last_name,
    p.phones[1] as patient_phone,
    lower(concat_ws(' ', d.name, p.last_name, p.first_name, p.middle_name, array_to_string(p.phones, ' '))) as search_text,
    (
        select count(*)
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
    ) as nb_open_tasks,
    (
        select min(t.due_date)
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
    ) as next_task_due_at,
    (
        select count(*)
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id and m.direction = 'in' and m.read_at is null
    ) as nb_unread_messages,
    (
        select max(m.sent_at)
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id
    ) as last_message_at,
    (
        select m.text
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id
        order by m.sent_at desc, m.id desc
        limit 1
    ) as last_message_text,
    d.doctor_id,
    dr.name as doctor_name,
    d.consultation_amount,
    (
        select coalesce(sum(pay.amount), 0)::bigint
        from public.deal_payments pay
        where pay.organization_id = d.organization_id and pay.deal_id = d.id and pay.kind = 'prepayment'
    ) as prepayment_amount,
    d.unsorted_at,
    d.custom_values,
    -- Deal list (stage 21): the latest change or message, the nearest open task
    greatest(d.updated_at, (
        select max(m.sent_at)
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id
    )) as last_activity_at,
    (
        select t.text
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
        order by t.due_date, t.id
        limit 1
    ) as next_task_text,
    d.utm_source,
    d.utm_medium,
    d.utm_campaign,
    d.utm_content,
    d.utm_term,
    d.referrer,
    d.landing_page,
    d.branch_id,
    br.name as branch_name
from public.deals d
    join public.stages s on s.id = d.stage_id
    join public.patients p on p.organization_id = d.organization_id and p.id = d.patient_id
    left join public.doctors dr on dr.organization_id = d.organization_id and dr.id = d.doctor_id
    left join public.branches br on br.organization_id = d.organization_id and br.id = d.branch_id;

--
-- Row level security
--

alter table public.branches enable row level security;
alter table public.sales_branches enable row level security;

-- A dictionary: every employee reads it, the owner and the head manage it
create policy "Organization members can read" on public.branches for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Owner and head can insert" on public.branches for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can update" on public.branches for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head can delete" on public.branches for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

create policy "Organization members can read" on public.sales_branches for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Owner and head can insert" on public.sales_branches for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can delete" on public.sales_branches for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

-- Deals and tasks (the rules of 05_policies.sql, declared here because they
-- read branch_id): the view, edit and delete scopes of the employee — all,
-- «Мой филиал» (own, of the employee's branches, without a branch), own,
-- own and unassigned (deals), none. Tasks: of visible deals too.
create policy "Visible deals can be read" on public.deals for select to authenticated
    using (
        organization_id = (select private.current_organization_id())
        and (
            (select private.access_scope('deals', 'view')) = 'all'
            or ((select private.access_scope('deals', 'view')) in ('branch', 'own', 'own_and_unassigned') and sales_id = (select private.current_sales_id()))
            or ((select private.access_scope('deals', 'view')) = 'own_and_unassigned' and sales_id is null)
            or ((select private.access_scope('deals', 'view')) = 'branch' and (branch_id is null or (select private.current_branch_ids()) @> array[branch_id]))
        )
    );
create policy "Deals in the edit scope can be updated" on public.deals for update to authenticated
    using (
        organization_id = (select private.current_organization_id())
        and (
            (select private.access_scope('deals', 'edit')) = 'all'
            or ((select private.access_scope('deals', 'edit')) in ('branch', 'own', 'own_and_unassigned') and sales_id = (select private.current_sales_id()))
            or ((select private.access_scope('deals', 'edit')) = 'own_and_unassigned' and sales_id is null)
            or ((select private.access_scope('deals', 'edit')) = 'branch' and (branch_id is null or (select private.current_branch_ids()) @> array[branch_id]))
        )
    )
    with check (organization_id = (select private.current_organization_id()));
create policy "Deals in the delete scope can be deleted" on public.deals for delete to authenticated
    using (
        organization_id = (select private.current_organization_id())
        and (
            (select private.access_scope('deals', 'delete')) = 'all'
            or ((select private.access_scope('deals', 'delete')) in ('branch', 'own', 'own_and_unassigned') and sales_id = (select private.current_sales_id()))
            or ((select private.access_scope('deals', 'delete')) = 'own_and_unassigned' and sales_id is null)
            or ((select private.access_scope('deals', 'delete')) = 'branch' and (branch_id is null or (select private.current_branch_ids()) @> array[branch_id]))
        )
    );
create policy "Tasks in the view scope can be read" on public.tasks for select to authenticated
    using (
        organization_id = (select private.current_organization_id())
        and ((select private.access_scope('tasks', 'view')) = 'all'
            or ((select private.access_scope('tasks', 'view')) in ('branch', 'own') and sales_id = (select private.current_sales_id()))
            or ((select private.access_scope('tasks', 'view')) = 'branch' and (branch_id is null or (select private.current_branch_ids()) @> array[branch_id])))
        and exists (select 1 from public.deals d where d.organization_id = tasks.organization_id and d.id = tasks.deal_id)
    );
create policy "Tasks in the edit scope can be updated" on public.tasks for update to authenticated
    using (
        organization_id = (select private.current_organization_id())
        and ((select private.access_scope('tasks', 'edit')) = 'all'
            or ((select private.access_scope('tasks', 'edit')) in ('branch', 'own') and sales_id = (select private.current_sales_id()))
            or ((select private.access_scope('tasks', 'edit')) = 'branch' and (branch_id is null or (select private.current_branch_ids()) @> array[branch_id])))
        and exists (select 1 from public.deals d where d.organization_id = tasks.organization_id and d.id = tasks.deal_id)
    )
    with check (organization_id = (select private.current_organization_id()));
create policy "Tasks in the delete scope can be deleted" on public.tasks for delete to authenticated
    using (
        organization_id = (select private.current_organization_id())
        and ((select private.access_scope('tasks', 'delete')) = 'all'
            or ((select private.access_scope('tasks', 'delete')) in ('branch', 'own') and sales_id = (select private.current_sales_id()))
            or ((select private.access_scope('tasks', 'delete')) = 'branch' and (branch_id is null or (select private.current_branch_ids()) @> array[branch_id])))
        and exists (select 1 from public.deals d where d.organization_id = tasks.organization_id and d.id = tasks.deal_id)
    );

-- The branch of a messenger channel (the only column employees may write)
create policy "Owner and head can update" on public.messenger_channels for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));

--
-- Grants
--

revoke all on table public.branches from anon;
grant select, insert, update, delete on table public.branches to authenticated;
grant all on table public.branches to service_role;
revoke all on sequence public.branches_id_seq from anon;
grant usage, select on sequence public.branches_id_seq to authenticated;
grant all on sequence public.branches_id_seq to service_role;
revoke all on table public.sales_branches from anon;
grant select, insert, delete on table public.sales_branches to authenticated;
grant all on table public.sales_branches to service_role;
revoke all on sequence public.sales_branches_id_seq from anon;
grant usage, select on sequence public.sales_branches_id_seq to authenticated;
grant all on sequence public.sales_branches_id_seq to service_role;

grant update (branch_id) on table public.messenger_channels to authenticated;

revoke all on function private.current_branch_ids() from public;
grant execute on function private.current_branch_ids() to authenticated;
grant execute on function private.current_branch_ids() to service_role;
revoke all on function private.find_branch(bigint, text) from public;
grant execute on function private.find_branch(bigint, text) to service_role;
revoke all on function private.branch_pool(bigint, bigint, bigint[]) from public;
grant execute on function private.branch_pool(bigint, bigint, bigint[]) to authenticated, service_role;
revoke all on function private.handle_deal_branch() from public;
revoke all on function private.handle_deal_branch_changed() from public;
revoke all on function private.handle_task_branch() from public;
revoke all on function private.handle_visit_branch() from public;
revoke all on function public.assign_branch_to_unassigned(bigint) from public, anon;
grant execute on function public.assign_branch_to_unassigned(bigint) to authenticated;
grant execute on function public.assign_branch_to_unassigned(bigint) to service_role;
