--
-- «Салесбот» (stage 26): chat bot scenarios, their sessions and log, the
-- digital pipeline action «Запустить салесбот», bot messages through the
-- auto-message queue, the notification «Бот передал диалог».
-- Source of truth: supabase/schemas/26_salesbot.sql (+ the functions of
-- 08_automessages.sql, 16_notifications.sql and 20_digital_pipeline.sql
-- copied below).
--
--
-- «Салесбот» (stage 26): chat bot scenarios, as in amoCRM
--
-- A bot (public.salesbots) is a scenario: a graph of steps stored as jsonb
--   { "start": "<step id>", "steps": [ { "id", "type", ...params, "next" } ] }
-- Step types (the same in the app: salesbot/engine.ts, the pure twin that
-- powers the «Тест» mode of the editor and the demo):
--   send_message  text (template variables + {ответ}) or template_id, optional
--                 numbered answer buttons appended as "1 — Записаться" lines
--   wait_reply    timeout_minutes; next (a reply came), timeout_next
--   condition     branches [{ match, value | stage_id | tag_id | source_id |
--                 field_id, next }] tried in order, else_next. Matches on the
--                 last reply: keywords (comma separated, whole words), option
--                 (number N or the text of button N), regex, any; on the deal:
--                 stage, tag, source, field (custom field value, empty value =
--                 filled)
--   set           actions [{ kind: stage | responsible | tag_add | tag_remove |
--                 field | deal_field | patient_field, ... }]; a value may be
--                 {ответ} (the last reply)
--   create_task   task_type, text, due_minutes
--   handoff       stops the bot: notification «Бот передал диалог» to the
--                 responsible (+ an optional task)
--   webhook       webhook_id: fire-and-forget through the stage 20 webhook
--                 queue (event 'salesbot'); the response is not read
--   delay         minutes
--   stop          the scenario ends
-- The scenario is checked on save (private.salesbot_errors): a broken
-- structure is refused, and an active bot must have no error at all.
--
-- Runtime: one session per deal at a time (public.salesbot_sessions, with a
-- snapshot of the scenario, so editing a bot never breaks a conversation in
-- progress), every step logged in public.salesbot_logs (deal feed,
-- debugging). private.salesbot_advance runs the steps synchronously until the
-- scenario waits (wait_reply, delay) or ends. Messages go through the
-- auto-message queue of stage 6 (automessages.salesbot_session_id, text
-- ready): the dispatcher sends them, quiet hours apply (a bot reply at night
-- waits until 9:00, the reply timeout counts from that moment).
--
-- Starts: a new deal's first inbound message (bots with trigger_new_lead,
-- optionally for some channels / sources), a keyword of an inbound message,
-- the digital pipeline action «Запустить салесбот», or an employee
-- (public.start_salesbot). A new start replaces the running session. Nothing
-- starts on unsorted deals (accepting one runs the new-lead bots) nor during
-- an import. An inbound message resumes a waiting session; an employee's own
-- message stops it; pg_cron runs private.salesbot_tick every minute for the
-- timeouts and the delays. Loop protection: 50 steps per activation, 30
-- messages per session.
--

--
-- Rights helper
--

-- May the current user configure the clinic (bots, triggers...). One place to
-- extend with new roles.
CREATE OR REPLACE FUNCTION "private"."can_configure"() RETURNS boolean
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  return coalesce(private.current_user_role() in ('owner', 'head'), false);
end;
$$;

--
-- Tables
--

create table public.salesbots (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    description text,
    is_active boolean not null default false,
    scenario jsonb not null default '{"start": null, "steps": []}'::jsonb,
    -- Incremented when the scenario changes (sessions keep their version)
    version integer not null default 1,
    -- «Новое входящее сообщение в новой сделке», optionally only for these
    -- channels (messages.transport) and deal sources
    trigger_new_lead boolean not null default false,
    trigger_transports text[] not null default '{}'::text[],
    trigger_source_ids bigint[] not null default '{}'::bigint[],
    -- An inbound message containing one of these words (lowercase)
    trigger_keywords text[] not null default '{}'::text[],
    position integer not null default 0,
    created_by bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint salesbots_name_not_blank check (btrim(name) <> ''),
    constraint salesbots_scenario_object check (jsonb_typeof(scenario) = 'object'),
    constraint salesbots_transports_check check (trigger_transports <@ array['whatsapp', 'instagram', 'telegram', 'telegram_bot']::text[])
);

-- A conversation of a bot with the patient of a deal. running: the steps are
-- being run (inside a transaction); waiting: for a reply or a delay
-- (wait_until); done, handed_off, stopped, failed: finished.
create table public.salesbot_sessions (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    deal_id bigint not null,
    bot_id bigint,
    bot_name text not null,
    bot_version integer not null,
    scenario jsonb not null,
    current_step text,
    -- wait (reply | delay), buttons of the last message, replies, last_send_at
    state jsonb not null default '{}'::jsonb,
    status text not null default 'running',
    wait_until timestamp with time zone,
    last_reply text,
    messages_sent integer not null default 0,
    -- new_lead, keyword, pipeline, manual
    trigger text not null,
    started_by bigint,
    stopped_reason text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    finished_at timestamp with time zone,
    constraint salesbot_sessions_status_check check (status in ('running', 'waiting', 'done', 'handed_off', 'stopped', 'failed')),
    constraint salesbot_sessions_trigger_check check (trigger in ('new_lead', 'keyword', 'pipeline', 'manual'))
);

-- What the bot did, step by step (deal feed and debugging). kind: started,
-- sent, waiting, reply, timeout, branch, set, task, handoff, webhook, delay,
-- moved, skipped, failed, done, stopped.
create table public.salesbot_logs (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    session_id bigint not null,
    deal_id bigint not null,
    step_id text,
    step_type text,
    kind text not null,
    text text,
    details jsonb not null default '{}'::jsonb,
    created_at timestamp with time zone not null default now()
);

-- The messages of a bot go through the auto-message queue with their text
alter table public.automessages add column salesbot_session_id bigint;
-- Digital pipeline action «Запустить салесбот»
alter table public.stage_triggers add column salesbot_id bigint;
alter table public.stage_triggers add constraint stage_triggers_salesbot_check check (action <> 'start_salesbot' or salesbot_id is not null);

alter table public.salesbots add constraint salesbots_organization_id_id_key unique (organization_id, id);
alter table public.salesbot_sessions add constraint salesbot_sessions_organization_id_id_key unique (organization_id, id);

alter table public.salesbots
    add constraint salesbots_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.salesbots
    add constraint salesbots_created_by_fkey foreign key (organization_id, created_by) references public.sales(organization_id, id) on delete set null (created_by);
alter table public.salesbot_sessions
    add constraint salesbot_sessions_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.salesbot_sessions
    add constraint salesbot_sessions_bot_id_fkey foreign key (organization_id, bot_id) references public.salesbots(organization_id, id) on delete set null (bot_id);
alter table public.salesbot_sessions
    add constraint salesbot_sessions_started_by_fkey foreign key (organization_id, started_by) references public.sales(organization_id, id) on delete set null (started_by);
alter table public.salesbot_logs
    add constraint salesbot_logs_session_id_fkey foreign key (organization_id, session_id) references public.salesbot_sessions(organization_id, id) on delete cascade;
alter table public.salesbot_logs
    add constraint salesbot_logs_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.automessages
    add constraint automessages_salesbot_session_id_fkey foreign key (organization_id, salesbot_session_id) references public.salesbot_sessions(organization_id, id) on delete set null (salesbot_session_id);
alter table public.stage_triggers
    add constraint stage_triggers_salesbot_id_fkey foreign key (organization_id, salesbot_id) references public.salesbots(organization_id, id) on delete cascade;

create index salesbots_organization_id_idx on public.salesbots using btree (organization_id, position, id);
-- One running or waiting session per deal
create unique index salesbot_sessions_active_idx on public.salesbot_sessions using btree (organization_id, deal_id) where status in ('running', 'waiting');
create index salesbot_sessions_deal_id_idx on public.salesbot_sessions using btree (organization_id, deal_id, created_at);
create index salesbot_sessions_bot_id_idx on public.salesbot_sessions using btree (organization_id, bot_id);
create index salesbot_sessions_due_idx on public.salesbot_sessions using btree (wait_until) where status = 'waiting';
create index salesbot_logs_deal_id_idx on public.salesbot_logs using btree (organization_id, deal_id, created_at);
create index salesbot_logs_session_id_idx on public.salesbot_logs using btree (organization_id, session_id, id);
create index automessages_salesbot_session_id_idx on public.automessages using btree (organization_id, salesbot_session_id) where salesbot_session_id is not null;

--
-- Scenario
--

-- Lowercase, ё → е (whatever the collation of the database). Same as
-- normalizeText() in salesbot/engine.ts.
CREATE OR REPLACE FUNCTION "private"."salesbot_normalize"("value" "text") RETURNS "text"
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select replace(
    translate(lower(coalesce(value, '')),
      'АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯӘҒҚҢӨҰҮҺІ',
      'абвгдеёжзийклмнопрстуфхцчшщъыьэюяәғқңөұүһі'),
    'ё', 'е')
$$;

-- The errors of a scenario, [{ code, step }]: invalid, no_steps,
-- duplicate_id, unknown_type, no_start, dangling_next, missing_target,
-- missing_param, empty_message, bad_timeout, bad_delay, invalid_regex,
-- unreachable. Same as validateScenario() in salesbot/engine.ts.
CREATE OR REPLACE FUNCTION "private"."salesbot_errors"("scenario" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql" IMMUTABLE
    SET "search_path" TO ''
    AS $_$
declare
  errors jsonb := '[]'::jsonb;
  step jsonb;
  branch jsonb;
  action jsonb;
  ids text[] := '{}'::text[];
  step_id text;
  step_type text;
  optional_targets text[];
  required_targets text[];
  target text;
  edges jsonb := '{}'::jsonb;
  reachable text[] := '{}'::text[];
  frontier text[];
  next_frontier text[];
  start_id text;
begin
  if scenario is null or jsonb_typeof(scenario) <> 'object'
    or jsonb_typeof(scenario -> 'steps') is distinct from 'array' then
    return '[{"code": "invalid", "step": null}]'::jsonb;
  end if;
  if jsonb_array_length(scenario -> 'steps') = 0 then
    return '[{"code": "no_steps", "step": null}]'::jsonb;
  end if;

  for step in select e.value from jsonb_array_elements(scenario -> 'steps') as e loop
    step_id := case when jsonb_typeof(step) = 'object' then nullif(btrim(coalesce(step ->> 'id', '')), '') end;
    if step_id is null then
      errors := errors || jsonb_build_array(jsonb_build_object('code', 'invalid', 'step', null));
      continue;
    end if;
    if step_id = any(ids) then
      errors := errors || jsonb_build_array(jsonb_build_object('code', 'duplicate_id', 'step', step_id));
    end if;
    ids := ids || step_id;
  end loop;

  start_id := scenario ->> 'start';
  if start_id is null or not (start_id = any(ids)) then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'no_start', 'step', null));
  end if;

  for step in select e.value from jsonb_array_elements(scenario -> 'steps') as e where jsonb_typeof(e.value) = 'object' loop
    step_id := nullif(btrim(coalesce(step ->> 'id', '')), '');
    continue when step_id is null;
    step_type := step ->> 'type';
    optional_targets := '{}'::text[];
    required_targets := '{}'::text[];
    case step_type
    when 'send_message' then
      if btrim(coalesce(step ->> 'text', '')) = '' and coalesce(step ->> 'template_id', '') !~ '^\d+$' then
        errors := errors || jsonb_build_array(jsonb_build_object('code', 'empty_message', 'step', step_id));
      end if;
      if step ? 'buttons' and step -> 'buttons' <> 'null'::jsonb and (jsonb_typeof(step -> 'buttons') <> 'array'
        or exists (select 1 from jsonb_array_elements(step -> 'buttons') as b
                   where jsonb_typeof(b.value) <> 'string' or btrim(b.value #>> '{}') = '')) then
        errors := errors || jsonb_build_array(jsonb_build_object('code', 'missing_param', 'step', step_id));
      end if;
      optional_targets := array[step ->> 'next'];
    when 'wait_reply' then
      if coalesce(step ->> 'timeout_minutes', '') !~ '^\d+$' or (step ->> 'timeout_minutes')::bigint < 1 then
        errors := errors || jsonb_build_array(jsonb_build_object('code', 'bad_timeout', 'step', step_id));
      end if;
      required_targets := array[step ->> 'next', step ->> 'timeout_next'];
    when 'condition' then
      if jsonb_typeof(step -> 'branches') is distinct from 'array' or jsonb_array_length(step -> 'branches') = 0 then
        errors := errors || jsonb_build_array(jsonb_build_object('code', 'missing_param', 'step', step_id));
      else
        for branch in select b.value from jsonb_array_elements(step -> 'branches') as b loop
          if jsonb_typeof(branch) <> 'object' or coalesce(branch ->> 'match', '') not in
              ('keywords', 'option', 'regex', 'any', 'stage', 'tag', 'source', 'field')
            or (branch ->> 'match' in ('keywords', 'regex') and btrim(coalesce(branch ->> 'value', '')) = '')
            or (branch ->> 'match' = 'option' and coalesce(branch ->> 'value', '') !~ '^\s*\d+\s*$')
            or (branch ->> 'match' = 'stage' and coalesce(branch ->> 'stage_id', '') !~ '^\d+$')
            or (branch ->> 'match' = 'tag' and coalesce(branch ->> 'tag_id', '') !~ '^\d+$')
            or (branch ->> 'match' = 'source' and coalesce(branch ->> 'source_id', '') !~ '^\d+$')
            or (branch ->> 'match' = 'field' and coalesce(branch ->> 'field_id', '') !~ '^\d+$') then
            errors := errors || jsonb_build_array(jsonb_build_object('code', 'missing_param', 'step', step_id));
          elsif branch ->> 'match' = 'regex' then
            begin
              perform '' ~ (branch ->> 'value');
            exception when others then
              errors := errors || jsonb_build_array(jsonb_build_object('code', 'invalid_regex', 'step', step_id));
            end;
          end if;
          required_targets := required_targets || case when jsonb_typeof(branch) = 'object' then branch ->> 'next' end;
        end loop;
      end if;
      required_targets := required_targets || (step ->> 'else_next');
    when 'set' then
      if jsonb_typeof(step -> 'actions') is distinct from 'array' or jsonb_array_length(step -> 'actions') = 0 then
        errors := errors || jsonb_build_array(jsonb_build_object('code', 'missing_param', 'step', step_id));
      else
        for action in select a.value from jsonb_array_elements(step -> 'actions') as a loop
          if jsonb_typeof(action) <> 'object' or coalesce(action ->> 'kind', '') not in
              ('stage', 'responsible', 'tag_add', 'tag_remove', 'field', 'deal_field', 'patient_field')
            or (action ->> 'kind' = 'stage' and coalesce(action ->> 'stage_id', '') !~ '^\d+$')
            or (action ->> 'kind' in ('tag_add', 'tag_remove') and coalesce(action ->> 'tag_id', '') !~ '^\d+$')
            or (action ->> 'kind' = 'field' and coalesce(action ->> 'field_id', '') !~ '^\d+$')
            or (action ->> 'kind' = 'deal_field' and coalesce(action ->> 'field', '') not in
              ('service_id', 'doctor_id', 'source_id', 'plan_amount', 'name'))
            or (action ->> 'kind' = 'patient_field' and coalesce(action ->> 'field', '') not in
              ('first_name', 'last_name', 'middle_name', 'city')) then
            errors := errors || jsonb_build_array(jsonb_build_object('code', 'missing_param', 'step', step_id));
          end if;
        end loop;
      end if;
      optional_targets := array[step ->> 'next'];
    when 'create_task' then
      if btrim(coalesce(step ->> 'text', '')) = ''
        or coalesce(step ->> 'task_type', '') not in ('call', 'message', 'reminder', 'other', 'meeting')
        or (step ? 'due_minutes' and coalesce(step ->> 'due_minutes', '0') !~ '^\d+$') then
        errors := errors || jsonb_build_array(jsonb_build_object('code', 'missing_param', 'step', step_id));
      end if;
      optional_targets := array[step ->> 'next'];
    when 'handoff' then
      null;
    when 'webhook' then
      if coalesce(step ->> 'webhook_id', '') !~ '^\d+$' then
        errors := errors || jsonb_build_array(jsonb_build_object('code', 'missing_param', 'step', step_id));
      end if;
      optional_targets := array[step ->> 'next'];
    when 'delay' then
      if coalesce(step ->> 'minutes', '') !~ '^\d+$' or (step ->> 'minutes')::bigint < 1 then
        errors := errors || jsonb_build_array(jsonb_build_object('code', 'bad_delay', 'step', step_id));
      end if;
      optional_targets := array[step ->> 'next'];
    when 'stop' then
      null;
    else
      errors := errors || jsonb_build_array(jsonb_build_object('code', 'unknown_type', 'step', step_id));
    end case;

    foreach target in array optional_targets loop
      if nullif(target, '') is not null and not (target = any(ids)) then
        errors := errors || jsonb_build_array(jsonb_build_object('code', 'dangling_next', 'step', step_id));
      end if;
    end loop;
    foreach target in array required_targets loop
      if nullif(target, '') is null then
        errors := errors || jsonb_build_array(jsonb_build_object('code', 'missing_target', 'step', step_id));
      elsif not (target = any(ids)) then
        errors := errors || jsonb_build_array(jsonb_build_object('code', 'dangling_next', 'step', step_id));
      end if;
    end loop;
    edges := edges || jsonb_build_object(step_id, to_jsonb(array_remove(optional_targets || required_targets, null)));
  end loop;

  -- Every step is reachable from the start
  if start_id = any(ids) then
    frontier := array[start_id];
    while cardinality(frontier) > 0 loop
      reachable := reachable || frontier;
      select coalesce(array_agg(distinct t.value), '{}'::text[]) into next_frontier
      from unnest(frontier) as f(id)
        cross join lateral jsonb_array_elements_text(coalesce(edges -> f.id, '[]'::jsonb)) as t(value)
      where not (t.value = any(reachable));
      frontier := next_frontier;
    end loop;
    for step_id in select distinct x from unnest(ids) as x where not (x = any(reachable)) order by 1 loop
      errors := errors || jsonb_build_array(jsonb_build_object('code', 'unreachable', 'step', step_id));
    end loop;
  end if;
  return errors;
end;
$_$;

-- A step of a scenario by id
CREATE OR REPLACE FUNCTION "private"."salesbot_step"("scenario" "jsonb", "step_id" "text") RETURNS "jsonb"
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select e.value
  from jsonb_array_elements(coalesce(scenario -> 'steps', '[]'::jsonb)) as e
  where e.value ->> 'id' = step_id
  limit 1
$$;

-- Does the last reply match a branch of a condition. keywords: one of the
-- comma separated words or phrases, as whole words; option: the number N
-- ("1", "1.", "1 — да") or the text of button N; regex: on the lowercased
-- reply; any: there is a reply. Same as replyMatches() in salesbot/engine.ts.
CREATE OR REPLACE FUNCTION "private"."salesbot_reply_matches"("branch" "jsonb", "reply" "text", "buttons" "jsonb") RETURNS boolean
    LANGUAGE "plpgsql" IMMUTABLE
    SET "search_path" TO ''
    AS $_$
declare
  answer text := btrim(private.salesbot_normalize(reply));
  word text;
  option_number integer;
  letters constant text := 'a-z0-9а-яәғқңөұүһі';
begin
  if reply is null then
    return false;
  end if;
  case branch ->> 'match'
  when 'any' then
    return true;
  when 'keywords' then
    foreach word in array string_to_array(private.salesbot_normalize(branch ->> 'value'), ',') loop
      word := btrim(word);
      continue when word = '';
      if answer ~ ('(^|[^' || letters || '])'
        || regexp_replace(word, '([.^$*+?()\[\]{}|\\-])', '\\\1', 'g')
        || '([^' || letters || ']|$)') then
        return true;
      end if;
    end loop;
    return false;
  when 'option' then
    option_number := btrim(branch ->> 'value')::integer;
    return answer ~ ('^' || option_number || '([^0-9]|$)')
      or (jsonb_typeof(buttons) = 'array' and option_number between 1 and jsonb_array_length(buttons)
        and answer = btrim(private.salesbot_normalize(buttons ->> (option_number - 1))));
  when 'regex' then
    begin
      return answer ~ (branch ->> 'value');
    exception when others then
      return false;
    end;
  else
    return false;
  end case;
end;
$_$;

-- Does the deal match a branch on its data (stage, tag, source, custom field)
CREATE OR REPLACE FUNCTION "private"."salesbot_deal_matches"("branch" "jsonb", "deal" "public"."deals") RETURNS boolean
    LANGUAGE "plpgsql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
declare
  stored jsonb;
  expected text := btrim(private.salesbot_normalize(branch ->> 'value'));
begin
  case branch ->> 'match'
  when 'stage' then
    return deal.stage_id = (branch ->> 'stage_id')::bigint;
  when 'tag' then
    return (branch ->> 'tag_id')::bigint = any(deal.tags);
  when 'source' then
    return coalesce(deal.source_id = (branch ->> 'source_id')::bigint, false);
  when 'field' then
    stored := deal.custom_values -> (branch ->> 'field_id');
    if stored is null or stored = 'null'::jsonb then
      return false;
    end if;
    if expected = '' then
      return true;
    end if;
    if jsonb_typeof(stored) = 'array' then
      return exists (select 1 from jsonb_array_elements_text(stored) as v where btrim(private.salesbot_normalize(v)) = expected);
    end if;
    if jsonb_typeof(stored) = 'boolean' then
      return (stored = 'true'::jsonb) = (expected in ('true', '1', 'да', 'yes', '+'));
    end if;
    return btrim(private.salesbot_normalize(stored #>> '{}')) = expected;
  else
    return false;
  end case;
end;
$$;

-- Text of a message step for a deal: the template or the text, the template
-- variables, {ответ} (the last reply), then the numbered buttons
CREATE OR REPLACE FUNCTION "private"."salesbot_message_text"("step" "jsonb", "deal" "public"."deals", "reply" "text") RETURNS "text"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  body text := step ->> 'text';
  rendered text;
  buttons text;
begin
  if coalesce(step ->> 'template_id', '') ~ '^\d+$' then
    select t.body into body from public.message_templates t
    where t.organization_id = deal.organization_id and t.id = (step ->> 'template_id')::bigint;
  end if;
  rendered := private.render_template(body,
    private.automessage_vars(deal) || jsonb_build_object('ответ', coalesce(reply, '')));
  if jsonb_typeof(step -> 'buttons') = 'array' and jsonb_array_length(step -> 'buttons') > 0 then
    select string_agg(b.ordinality || ' — ' || btrim(b.value), E'\n' order by b.ordinality) into buttons
    from jsonb_array_elements_text(step -> 'buttons') with ordinality as b;
    rendered := btrim(concat_ws(E'\n\n', nullif(rendered, ''), buttons), E' \n');
  end if;
  return rendered;
end;
$$;

--
-- Runtime
--

CREATE OR REPLACE FUNCTION "private"."salesbot_log"("session" "public"."salesbot_sessions", "step" "jsonb", "log_kind" "text", "log_text" "text" DEFAULT NULL::"text", "log_details" "jsonb" DEFAULT '{}'::"jsonb") RETURNS "void"
    LANGUAGE "sql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
  insert into public.salesbot_logs (organization_id, session_id, deal_id, step_id, step_type, kind, text, details)
  values (session.organization_id, session.id, session.deal_id, step ->> 'id', step ->> 'type', log_kind,
    left(log_text, 2000), coalesce(log_details, '{}'::jsonb))
$$;

-- Ends a session. A stopped one (replaced, stopped by an employee, a human
-- took over) cancels the messages it still has in the queue.
CREATE OR REPLACE FUNCTION "private"."salesbot_finish"("target_session_id" bigint, "final_status" "text", "reason" "text" DEFAULT NULL::"text") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  session public.salesbot_sessions;
begin
  update public.salesbot_sessions s
  set status = final_status, stopped_reason = reason, wait_until = null, finished_at = now(), updated_at = now(),
      state = s.state - 'wait'
  where s.id = target_session_id and s.status in ('running', 'waiting')
  returning * into session;
  if not found then
    return;
  end if;
  if final_status = 'stopped' then
    update public.automessages a
    set status = 'cancelled', error = coalesce(reason, 'Бот остановлен'), processed_at = now()
    where a.organization_id = session.organization_id and a.salesbot_session_id = session.id
      and a.status = 'pending';
  end if;
  perform private.salesbot_log(session, null,
    case when final_status in ('done', 'stopped', 'failed') then final_status else 'handoff' end, reason);
end;
$$;

-- One action of a «set» step; returns what changed, raises when it cannot be
-- done (the stage checklist, a value of the wrong type...)
CREATE OR REPLACE FUNCTION "private"."salesbot_apply_set"("action" "jsonb", "deal" "public"."deals", "reply" "text") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := deal.organization_id;
  value text := replace(coalesce(action ->> 'value', ''), '{ответ}', coalesce(reply, ''));
  target_id bigint;
  target_kind text;
  new_sales_id bigint;
begin
  case action ->> 'kind'
  when 'stage' then
    target_id := (action ->> 'stage_id')::bigint;
    select s.kind into target_kind from public.stages s
    where s.organization_id = org_id and s.id = target_id and s.pipeline_id = deal.pipeline_id;
    if target_kind is null then
      raise exception 'Этап не найден в воронке сделки' using errcode = '22023';
    end if;
    if target_kind = 'lost' then
      raise exception 'Перевести в отказ может только сотрудник: нужна причина' using errcode = '22023';
    end if;
    if deal.stage_id = target_id then
      return jsonb_build_object('unchanged', true, 'stage_id', target_id);
    end if;
    update public.deals d set stage_id = target_id where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('from_stage_id', deal.stage_id, 'to_stage_id', target_id);

  when 'responsible' then
    new_sales_id := coalesce((action ->> 'sales_id')::bigint, private.next_responsible(org_id));
    if new_sales_id is null or not exists (
      select 1 from public.sales s where s.organization_id = org_id and s.id = new_sales_id and not s.disabled
    ) then
      raise exception 'Некому назначить' using errcode = '22023';
    end if;
    if deal.sales_id is not distinct from new_sales_id then
      return jsonb_build_object('unchanged', true, 'sales_id', new_sales_id);
    end if;
    update public.deals d set sales_id = new_sales_id where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('from_sales_id', deal.sales_id, 'to_sales_id', new_sales_id);

  when 'tag_add', 'tag_remove' then
    target_id := (action ->> 'tag_id')::bigint;
    if not exists (select 1 from public.tags t where t.organization_id = org_id and t.id = target_id) then
      raise exception 'Тег не найден' using errcode = '22023';
    end if;
    if (target_id = any(deal.tags)) = (action ->> 'kind' = 'tag_add') then
      return jsonb_build_object('unchanged', true, 'tag_id', target_id);
    end if;
    update public.deals d
    set tags = case when action ->> 'kind' = 'tag_add' then array_append(d.tags, target_id) else array_remove(d.tags, target_id) end
    where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('tag_id', target_id);

  when 'field' then
    target_id := (action ->> 'field_id')::bigint;
    if not exists (
      select 1 from public.custom_fields f
      where f.organization_id = org_id and f.id = target_id and f.entity = 'deal' and f.is_active
    ) then
      raise exception 'Поле не найдено' using errcode = '22023';
    end if;
    update public.deals d
    set custom_values = case when btrim(value) = '' then d.custom_values - target_id::text
      else d.custom_values || jsonb_build_object(target_id::text, btrim(value)) end
    where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('field_id', target_id, 'value', btrim(value));

  when 'deal_field' then
    value := nullif(btrim(value), '');
    case action ->> 'field'
    when 'service_id' then
      update public.deals d set service_id = value::bigint where d.organization_id = org_id and d.id = deal.id;
    when 'doctor_id' then
      update public.deals d set doctor_id = value::bigint where d.organization_id = org_id and d.id = deal.id;
    when 'source_id' then
      update public.deals d set source_id = value::bigint where d.organization_id = org_id and d.id = deal.id;
    when 'plan_amount' then
      update public.deals d set plan_amount = coalesce(regexp_replace(value, '[^0-9]', '', 'g')::bigint, 0)
      where d.organization_id = org_id and d.id = deal.id;
    when 'name' then
      update public.deals d set name = left(value, 200) where d.organization_id = org_id and d.id = deal.id;
    else
      raise exception 'Поле сделки нельзя изменить' using errcode = '22023';
    end case;
    return jsonb_build_object('field', action ->> 'field', 'value', value);

  when 'patient_field' then
    value := left(nullif(btrim(value), ''), 200);
    case action ->> 'field'
    when 'first_name' then
      update public.patients p set first_name = value where p.organization_id = org_id and p.id = deal.patient_id;
    when 'last_name' then
      update public.patients p set last_name = value where p.organization_id = org_id and p.id = deal.patient_id;
    when 'middle_name' then
      update public.patients p set middle_name = value where p.organization_id = org_id and p.id = deal.patient_id;
    when 'city' then
      update public.patients p set city = value where p.organization_id = org_id and p.id = deal.patient_id;
    else
      raise exception 'Поле пациента нельзя изменить' using errcode = '22023';
    end case;
    return jsonb_build_object('field', action ->> 'field', 'value', value);
  else
    raise exception 'Неизвестное действие' using errcode = '22023';
  end case;
end;
$$;

-- Runs the steps of a running session until it waits (a reply, a delay) or
-- ends. At most 50 steps per call and 30 messages per session (loop
-- protection). The changes are automatic (crm.automation_depth one level
-- deeper, audit source 'automation'); an action that fails is logged
-- (skipped for the stage checklist, failed otherwise) and the scenario goes
-- on. Returns the status of the session.
CREATE OR REPLACE FUNCTION "private"."salesbot_advance"("target_session_id" bigint) RETURNS "text"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  session public.salesbot_sessions;
  deal public.deals;
  step jsonb;
  branch jsonb;
  action jsonb;
  step_type text;
  next_id text;
  outgoing text;
  send_at timestamp with time zone;
  wait_from timestamp with time zone;
  zone text;
  new_id bigint;
  result jsonb;
  steps_done integer := 0;
  recipient bigint;
  recipients bigint[];
  handoff_note text;
  queued integer;
  error_hint text;
  error_message text;
  final_status text;
  final_reason text;
  depth integer := coalesce(nullif(current_setting('crm.automation_depth', true), '')::integer, 0);
  previous_source text := coalesce(current_setting('crm.audit_source', true), '');
  previous_session text := coalesce(current_setting('crm.salesbot_session', true), '');
begin
  select * into session from public.salesbot_sessions s where s.id = target_session_id for update;
  if not found or session.status <> 'running' then
    return session.status;
  end if;
  select o.timezone into zone from public.organizations o where o.id = session.organization_id;

  perform set_config('crm.automation_depth', (depth + 1)::text, true);
  perform set_config('crm.audit_source', 'automation', true);
  perform set_config('crm.salesbot_session', session.id::text, true);

  loop
    if session.current_step is null then
      final_status := 'done';
      final_reason := null;
      exit;
    end if;
    step := private.salesbot_step(session.scenario, session.current_step);
    if step is null then
      final_status := 'failed';
      final_reason := 'Шаг сценария не найден';
      exit;
    end if;
    steps_done := steps_done + 1;
    if steps_done > 50 then
      final_status := 'failed';
      final_reason := 'Слишком много шагов подряд: проверьте, нет ли в сценарии петли';
      exit;
    end if;
    select * into deal from public.deals d
    where d.organization_id = session.organization_id and d.id = session.deal_id;
    if not found or deal.archived_at is not null then
      final_status := 'stopped';
      final_reason := 'Сделка в архиве';
      exit;
    end if;

    step_type := step ->> 'type';
    next_id := nullif(step ->> 'next', '');

    if step_type = 'send_message' then
      if session.messages_sent >= 30 then
        final_status := 'failed';
        final_reason := 'Бот отправил слишком много сообщений';
        exit;
      end if;
      outgoing := private.salesbot_message_text(step, deal, session.last_reply);
      if coalesce(outgoing, '') = '' then
        perform private.salesbot_log(session, step, 'skipped', 'Пустой текст сообщения');
      else
        send_at := private.automessage_send_time(now(), zone);
        insert into public.automessages (organization_id, deal_id, rule_id, template_id, stage_id, timing, send_at,
          text, salesbot_session_id)
        values (session.organization_id, deal.id, null, null, deal.stage_id, 'after_stage', send_at,
          outgoing, session.id)
        returning id into new_id;
        session.messages_sent := session.messages_sent + 1;
        session.state := session.state || jsonb_build_object('last_send_at', send_at,
          'buttons', coalesce(case when jsonb_typeof(step -> 'buttons') = 'array' then step -> 'buttons' end, '[]'::jsonb));
        perform private.salesbot_log(session, step, 'sent', outgoing,
          jsonb_build_object('automessage_id', new_id, 'send_at', send_at));
      end if;
      session.current_step := next_id;

    elsif step_type = 'wait_reply' then
      -- The timeout counts from the moment the last message goes out (quiet hours)
      wait_from := greatest(now(), coalesce((session.state ->> 'last_send_at')::timestamp with time zone, now()));
      session.status := 'waiting';
      session.wait_until := wait_from + make_interval(mins => (step ->> 'timeout_minutes')::integer);
      session.state := session.state || '{"wait": "reply"}'::jsonb;
      perform private.salesbot_log(session, step, 'waiting', null, jsonb_build_object('until', session.wait_until));
      exit;

    elsif step_type = 'delay' then
      session.status := 'waiting';
      session.wait_until := now() + make_interval(mins => (step ->> 'minutes')::integer);
      session.state := session.state || '{"wait": "delay"}'::jsonb;
      perform private.salesbot_log(session, step, 'delay', null, jsonb_build_object('until', session.wait_until));
      exit;

    elsif step_type = 'condition' then
      next_id := null;
      for branch in select b.value from jsonb_array_elements(step -> 'branches') with ordinality as b order by b.ordinality loop
        if (branch ->> 'match' in ('keywords', 'option', 'regex', 'any')
              and private.salesbot_reply_matches(branch, session.last_reply, session.state -> 'buttons'))
          or (branch ->> 'match' in ('stage', 'tag', 'source', 'field') and private.salesbot_deal_matches(branch, deal)) then
          next_id := branch ->> 'next';
          exit;
        end if;
      end loop;
      perform private.salesbot_log(session, step, 'branch', session.last_reply,
        jsonb_build_object('next', coalesce(next_id, step ->> 'else_next'), 'matched', next_id is not null));
      session.current_step := coalesce(next_id, nullif(step ->> 'else_next', ''));

    elsif step_type = 'set' then
      for action in select a.value from jsonb_array_elements(step -> 'actions') with ordinality as a order by a.ordinality loop
        select * into deal from public.deals d
        where d.organization_id = session.organization_id and d.id = session.deal_id;
        begin
          result := private.salesbot_apply_set(action, deal, session.last_reply);
          perform private.salesbot_log(session, step, 'set', null, jsonb_build_object('action', action, 'result', result));
        exception when others then
          get stacked diagnostics error_hint = pg_exception_hint, error_message = message_text;
          perform private.salesbot_log(session, step,
            case when error_hint = 'stage_checklist_incomplete' then 'skipped' else 'failed' end,
            error_message, jsonb_build_object('action', action));
        end;
      end loop;
      session.current_step := next_id;

    elsif step_type = 'create_task' then
      begin
        insert into public.tasks (organization_id, deal_id, type, text, due_date, sales_id)
        values (deal.organization_id, deal.id, step ->> 'task_type',
          private.render_template(step ->> 'text',
            private.automessage_vars(deal) || jsonb_build_object('ответ', coalesce(session.last_reply, ''))),
          now() + make_interval(mins => coalesce((step ->> 'due_minutes')::integer, 0)), deal.sales_id)
        returning id into new_id;
        perform private.salesbot_log(session, step, 'task', step ->> 'text', jsonb_build_object('task_id', new_id));
      exception when others then
        get stacked diagnostics error_message = message_text;
        perform private.salesbot_log(session, step, 'failed', error_message);
      end;
      session.current_step := next_id;

    elsif step_type = 'handoff' then
      handoff_note := nullif(btrim(coalesce(step ->> 'text', '')), '');
      if coalesce((step ->> 'create_task')::boolean, false) then
        insert into public.tasks (organization_id, deal_id, type, text, due_date, sales_id)
        values (deal.organization_id, deal.id, 'message',
          coalesce(nullif(btrim(coalesce(step ->> 'task_text', '')), ''), 'Ответить пациенту: бот передал диалог'),
          now(), deal.sales_id)
        returning id into new_id;
      else
        new_id := null;
      end if;
      if current_setting('crm.notifications', true) is distinct from 'off' then
        recipients := case when deal.sales_id is not null then array[deal.sales_id] else private.deal_audience(deal) end;
        foreach recipient in array coalesce(recipients, '{}'::bigint[]) loop
          perform private.add_notification(deal.organization_id, recipient, 'bot_handoff', 'Бот передал диалог',
            private.deal_label(deal) || coalesce(': ' || handoff_note, ''), deal.id, deal.patient_id, new_id);
        end loop;
      end if;
      final_status := 'handed_off';
      final_reason := handoff_note;
      exit;

    elsif step_type = 'webhook' then
      queued := private.enqueue_webhook(deal.organization_id, 'salesbot',
        jsonb_build_object('deal_id', deal.id, 'patient_id', deal.patient_id,
          'salesbot', jsonb_build_object('id', session.bot_id, 'name', session.bot_name, 'session_id', session.id,
            'step', step ->> 'id', 'last_reply', session.last_reply, 'replies', coalesce(session.state -> 'replies', '[]'::jsonb)),
          'deal', private.deal_json(deal)),
        (step ->> 'webhook_id')::bigint);
      perform private.salesbot_log(session, step, case when queued > 0 then 'webhook' else 'failed' end,
        case when queued > 0 then null else 'Вебхук выключен или удалён' end,
        jsonb_build_object('webhook_id', (step ->> 'webhook_id')::bigint));
      session.current_step := next_id;

    elsif step_type = 'stop' then
      final_status := 'done';
      final_reason := null;
      exit;

    else
      final_status := 'failed';
      final_reason := 'Неизвестный шаг сценария';
      exit;
    end if;
  end loop;

  -- Save where it stopped, then end it when the scenario is over
  update public.salesbot_sessions s
  set current_step = session.current_step, state = session.state, status = session.status,
      wait_until = session.wait_until, messages_sent = session.messages_sent, updated_at = now()
  where s.id = session.id and s.status = 'running';
  if final_status is not null then
    perform private.salesbot_finish(session.id, final_status, final_reason);
  end if;

  perform set_config('crm.automation_depth', depth::text, true);
  perform set_config('crm.audit_source', previous_source, true);
  perform set_config('crm.salesbot_session', previous_session, true);
  select s.status into session.status from public.salesbot_sessions s where s.id = session.id;
  return session.status;
end;
$$;

-- Starts a bot on a deal (trigger: new_lead, keyword, pipeline, manual) and
-- runs its first steps. The running session of the deal is stopped first
-- (one session per deal). Returns the session, or null when nothing starts:
-- an import, an unsorted deal (automatic starts; a manual one raises).
CREATE OR REPLACE FUNCTION "private"."salesbot_start"("target_bot_id" bigint, "target_deal_id" bigint, "start_trigger" "text", "actor_id" bigint DEFAULT NULL::bigint) RETURNS bigint
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  bot public.salesbots;
  deal public.deals;
  session public.salesbot_sessions;
  previous public.salesbot_sessions;
begin
  if current_setting('crm.importing', true) = 'on' then
    return null;
  end if;
  select * into deal from public.deals d where d.id = target_deal_id;
  if not found then
    raise exception 'Сделка не найдена' using errcode = '22023', hint = 'salesbot_deal_unknown';
  end if;
  if deal.unsorted_at is not null then
    if start_trigger = 'manual' then
      raise exception 'Сначала примите заявку из «Неразобранного»' using errcode = 'check_violation', hint = 'salesbot_unsorted';
    end if;
    return null;
  end if;
  if deal.archived_at is not null then
    raise exception 'Сделка в архиве' using errcode = 'check_violation', hint = 'salesbot_archived';
  end if;
  -- A bot changing the deal cannot start another bot on it (loop protection)
  if coalesce(current_setting('crm.salesbot_session', true), '') <> '' then
    raise exception 'Бот уже ведёт эту сделку' using errcode = 'check_violation', hint = 'salesbot_busy';
  end if;
  select * into bot from public.salesbots b
  where b.organization_id = deal.organization_id and b.id = target_bot_id;
  if not found then
    raise exception 'Бот не найден' using errcode = '22023', hint = 'salesbot_unknown';
  end if;
  if not bot.is_active then
    raise exception 'Бот выключен' using errcode = 'check_violation', hint = 'salesbot_inactive';
  end if;

  for previous in
    select * from public.salesbot_sessions s
    where s.organization_id = deal.organization_id and s.deal_id = deal.id and s.status in ('running', 'waiting')
    for update
  loop
    perform private.salesbot_finish(previous.id, 'stopped', 'Запущен бот «' || bot.name || '»');
  end loop;

  insert into public.salesbot_sessions (organization_id, deal_id, bot_id, bot_name, bot_version, scenario,
    current_step, trigger, started_by)
  values (deal.organization_id, deal.id, bot.id, bot.name, bot.version, bot.scenario,
    bot.scenario ->> 'start', start_trigger, actor_id)
  returning * into session;
  perform private.salesbot_log(session, null, 'started', bot.name,
    jsonb_build_object('trigger', start_trigger, 'bot_id', bot.id, 'version', bot.version, 'sales_id', actor_id));
  perform private.salesbot_advance(session.id);
  return session.id;
end;
$$;

-- An inbound message of a deal: resumes its waiting session with the reply;
-- without a session, starts the new-lead bot (first message of the deal) or
-- a keyword bot. A session whose deal is closed follows the patient to the
-- new deal of the reply (a patient answering a reactivation).
CREATE OR REPLACE FUNCTION "private"."salesbot_on_inbound"("message" "public"."messages") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  deal public.deals;
  session public.salesbot_sessions;
  step jsonb;
  bot_id bigint;
  reply text := coalesce(message.text, '');
  answer text := private.salesbot_normalize(message.text);
begin
  select * into deal from public.deals d where d.organization_id = message.organization_id and d.id = message.deal_id;
  if not found or deal.unsorted_at is not null or deal.archived_at is not null then
    return;
  end if;

  select * into session from public.salesbot_sessions s
  where s.organization_id = deal.organization_id and s.deal_id = deal.id and s.status in ('running', 'waiting')
  for update;
  if not found then
    select s.* into session from public.salesbot_sessions s
      join public.deals d on d.organization_id = s.organization_id and d.id = s.deal_id
      join public.stages st on st.id = d.stage_id
    where s.organization_id = deal.organization_id and d.patient_id = deal.patient_id and d.id <> deal.id
      and s.status = 'waiting' and st.kind in ('won', 'lost')
    order by s.updated_at desc, s.id desc
    limit 1
    for update of s;
    if found then
      update public.salesbot_sessions s set deal_id = deal.id, updated_at = now()
      where s.id = session.id
      returning * into session;
      perform private.salesbot_log(session, null, 'moved', null, jsonb_build_object('deal_id', deal.id));
    end if;
  end if;

  if session.id is not null then
    session.state := jsonb_set(session.state, '{replies}',
      (coalesce(session.state -> 'replies', '[]'::jsonb) || to_jsonb(left(reply, 1000)))
        - case when jsonb_array_length(coalesce(session.state -> 'replies', '[]'::jsonb)) >= 20 then 0 else 1000 end);
    step := private.salesbot_step(session.scenario, session.current_step);
    if session.status = 'waiting' and session.state ->> 'wait' = 'reply' then
      update public.salesbot_sessions s
      set last_reply = reply, state = session.state - 'wait', status = 'running', wait_until = null,
          current_step = nullif(step ->> 'next', ''), updated_at = now()
      where s.id = session.id
      returning * into session;
      perform private.salesbot_log(session, step, 'reply', reply, jsonb_build_object('message_id', message.id));
      perform private.salesbot_advance(session.id);
    else
      -- A delay is running: the reply is kept for the next condition
      update public.salesbot_sessions s set last_reply = reply, state = session.state, updated_at = now()
      where s.id = session.id
      returning * into session;
      perform private.salesbot_log(session, step, 'reply', reply, jsonb_build_object('message_id', message.id));
    end if;
    return;
  end if;

  -- The first message of a new deal
  if not exists (
    select 1 from public.messages m
    where m.organization_id = message.organization_id and m.deal_id = message.deal_id and m.id <> message.id
  ) then
    select b.id into bot_id from public.salesbots b
    where b.organization_id = deal.organization_id and b.is_active and b.trigger_new_lead
      and (cardinality(b.trigger_transports) = 0 or message.transport = any(b.trigger_transports))
      and (cardinality(b.trigger_source_ids) = 0 or deal.source_id = any(b.trigger_source_ids))
    order by b.position, b.id
    limit 1;
    if bot_id is not null then
      perform private.salesbot_start(bot_id, deal.id, 'new_lead');
      return;
    end if;
  end if;

  if answer <> '' then
    select b.id into bot_id from public.salesbots b
    where b.organization_id = deal.organization_id and b.is_active
      and exists (
        select 1 from unnest(b.trigger_keywords) as k
        where btrim(k) <> '' and position(private.salesbot_normalize(btrim(k)) in answer) > 0
      )
    order by b.position, b.id
    limit 1;
    if bot_id is not null then
      perform private.salesbot_start(bot_id, deal.id, 'keyword');
    end if;
  end if;
end;
$$;

-- Messages: an inbound one goes to the bots, an employee's own outbound one
-- (not an auto-message) stops the bot: a human took over. A problem of the
-- bots never refuses the message.
CREATE OR REPLACE FUNCTION "private"."handle_message_salesbot"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  active_id bigint;
begin
  if current_setting('crm.importing', true) = 'on' or new.deal_id is null then
    return null;
  end if;
  if new.direction = 'out' then
    if new.sales_id is not null and new.automessage_id is null then
      select s.id into active_id from public.salesbot_sessions s
      where s.organization_id = new.organization_id and s.deal_id = new.deal_id and s.status in ('running', 'waiting');
      if active_id is not null then
        perform private.salesbot_finish(active_id, 'stopped', 'Сотрудник ответил сам');
      end if;
    end if;
    return null;
  end if;
  begin
    perform private.salesbot_on_inbound(new);
  exception when others then
    raise warning 'salesbot: message % not handled: %', new.id, sqlerrm;
  end;
  return null;
end;
$$;

-- Deals: an accepted unsorted lead starts the new-lead bot of its first
-- message; an archived deal stops its bot
CREATE OR REPLACE FUNCTION "private"."handle_deal_salesbot"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  first_message public.messages;
  active_id bigint;
  bot_id bigint;
begin
  if current_setting('crm.importing', true) = 'on' then
    return null;
  end if;
  if new.archived_at is not null and old.archived_at is null then
    select s.id into active_id from public.salesbot_sessions s
    where s.organization_id = new.organization_id and s.deal_id = new.id and s.status in ('running', 'waiting');
    if active_id is not null then
      perform private.salesbot_finish(active_id, 'stopped', 'Сделка в архиве');
    end if;
    return null;
  end if;
  if old.unsorted_at is null or new.unsorted_at is not null
    or (select s.kind from public.stages s where s.id = new.stage_id) <> 'open' then
    return null;
  end if;
  select * into first_message from public.messages m
  where m.organization_id = new.organization_id and m.deal_id = new.id and m.direction = 'in'
  order by m.sent_at, m.id
  limit 1;
  if first_message.id is null then
    return null;
  end if;
  select b.id into bot_id from public.salesbots b
  where b.organization_id = new.organization_id and b.is_active and b.trigger_new_lead
    and (cardinality(b.trigger_transports) = 0 or first_message.transport = any(b.trigger_transports))
    and (cardinality(b.trigger_source_ids) = 0 or new.source_id = any(b.trigger_source_ids))
  order by b.position, b.id
  limit 1;
  if bot_id is not null then
    begin
      perform private.salesbot_start(bot_id, new.id, 'new_lead');
    exception when others then
      raise warning 'salesbot: deal % not started: %', new.id, sqlerrm;
    end;
  end if;
  return null;
end;
$$;

-- Timeouts of the replies and ends of the delays, run by pg_cron every minute
-- (and by the tests with a moment). At most 500 sessions per run; a broken
-- session fails alone.
CREATE OR REPLACE FUNCTION "private"."salesbot_tick"("moment" timestamp with time zone DEFAULT "now"()) RETURNS integer
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  session public.salesbot_sessions;
  step jsonb;
  resumed integer := 0;
begin
  for session in
    select * from public.salesbot_sessions s
    where s.status = 'waiting' and s.wait_until <= moment
    order by s.wait_until, s.id
    limit 500
    for update skip locked
  loop
    step := private.salesbot_step(session.scenario, session.current_step);
    begin
      update public.salesbot_sessions s
      set status = 'running', wait_until = null, state = s.state - 'wait', updated_at = now(),
          current_step = nullif(case when session.state ->> 'wait' = 'reply' then step ->> 'timeout_next' else step ->> 'next' end, '')
      where s.id = session.id
      returning * into session;
      if step ->> 'type' = 'wait_reply' then
        perform private.salesbot_log(session, step, 'timeout');
      end if;
      perform private.salesbot_advance(session.id);
      resumed := resumed + 1;
    exception when others then
      perform private.salesbot_finish(session.id, 'failed', left(sqlerrm, 500));
    end;
  end loop;
  return resumed;
end;
$$;

-- Normalizes a bot on save and checks its scenario: a broken structure is
-- refused, an active bot must have no error. The version grows when the
-- scenario changes.
CREATE OR REPLACE FUNCTION "private"."handle_salesbot_saved"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  errors jsonb := private.salesbot_errors(new.scenario);
begin
  new.name := btrim(new.name);
  new.trigger_keywords := coalesce((
    select array_agg(distinct k order by k)
    from (select btrim(private.salesbot_normalize(x)) as k from unnest(new.trigger_keywords) as x) w
    where k <> ''
  ), '{}'::text[]);
  if tg_op = 'INSERT' then
    new.version := 1;
    new.created_by := coalesce(new.created_by, private.current_sales_id());
  else
    new.version := old.version + case when new.scenario is distinct from old.scenario then 1 else 0 end;
    new.created_at := old.created_at;
    new.updated_at := now();
  end if;
  if exists (select 1 from jsonb_array_elements(errors) as e where e.value ->> 'code' in ('invalid', 'duplicate_id', 'unknown_type')) then
    raise exception 'Сценарий бота повреждён' using errcode = 'check_violation', hint = 'salesbot_invalid';
  end if;
  if new.is_active and jsonb_array_length(errors) > 0 then
    raise exception 'Исправьте ошибки сценария перед включением бота (%)',
      (select string_agg(distinct e.value ->> 'code', ', ') from jsonb_array_elements(errors) as e)
      using errcode = 'check_violation', hint = 'salesbot_invalid';
  end if;
  return new;
end;
$$;

-- «Запустить бота» on the deal page: every employee who sees the deal
CREATE OR REPLACE FUNCTION "public"."start_salesbot"("target_deal_id" bigint, "target_bot_id" bigint) RETURNS bigint
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  deal public.deals;
begin
  select * into deal from public.deals d where d.id = target_deal_id;
  if private.current_organization_id() is null or not private.deal_visible(deal) then
    raise exception 'Сделка не найдена' using errcode = '42501';
  end if;
  return private.salesbot_start(target_bot_id, deal.id, 'manual', private.current_sales_id());
end;
$$;

-- «Остановить бота»: every employee who sees the deal
CREATE OR REPLACE FUNCTION "public"."stop_salesbot"("target_deal_id" bigint) RETURNS boolean
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  deal public.deals;
  active_id bigint;
begin
  select * into deal from public.deals d where d.id = target_deal_id;
  if private.current_organization_id() is null or not private.deal_visible(deal) then
    raise exception 'Сделка не найдена' using errcode = '42501';
  end if;
  select s.id into active_id from public.salesbot_sessions s
  where s.organization_id = deal.organization_id and s.deal_id = deal.id and s.status in ('running', 'waiting');
  if active_id is null then
    return false;
  end if;
  perform private.salesbot_finish(active_id, 'stopped', 'Остановлен сотрудником');
  return true;
end;
$$;

--
-- Triggers
--

create or replace trigger salesbot_saved
    before insert or update on public.salesbots
    for each row execute function private.handle_salesbot_saved();

-- After the other message triggers (first answer, notifications, digital
-- pipeline): the bot's reply is queued last
create or replace trigger message_salesbot
    after insert on public.messages
    for each row execute function private.handle_message_salesbot();

create or replace trigger deal_salesbot
    after update on public.deals
    for each row execute function private.handle_deal_salesbot();

create or replace trigger audit_salesbot
    after insert or update or delete on public.salesbots
    for each row execute function private.audit_row('salesbot', 'name,is_active,version,trigger_new_lead,trigger_transports,trigger_keywords');

--
-- Row Level Security
--

alter table public.salesbots enable row level security;
alter table public.salesbot_sessions enable row level security;
alter table public.salesbot_logs enable row level security;

-- Bots are settings: every employee reads them (to start one by hand), those
-- who configure the clinic edit them
create policy "Organization members can read" on public.salesbots for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Configurators can insert" on public.salesbots for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.can_configure()));
create policy "Configurators can update" on public.salesbots for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.can_configure()))
    with check (organization_id = (select private.current_organization_id()));
create policy "Configurators can delete" on public.salesbots for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.can_configure()));

-- Sessions and their log follow the deal
create policy "Sessions of visible deals can be read" on public.salesbot_sessions for select to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = salesbot_sessions.organization_id and d.id = salesbot_sessions.deal_id));
create policy "Logs of visible deals can be read" on public.salesbot_logs for select to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = salesbot_logs.organization_id and d.id = salesbot_logs.deal_id));

--
-- Grants
--

revoke all on table public.salesbots from anon, authenticated;
grant select, insert, delete on table public.salesbots to authenticated;
grant update (name, description, is_active, scenario, trigger_new_lead, trigger_transports, trigger_source_ids, trigger_keywords, position)
    on table public.salesbots to authenticated;
grant all on table public.salesbots to service_role;
revoke all on sequence public.salesbots_id_seq from anon;
grant all on sequence public.salesbots_id_seq to authenticated, service_role;

-- Written by the functions only
revoke all on table public.salesbot_sessions from anon, authenticated;
grant select on table public.salesbot_sessions to authenticated;
grant all on table public.salesbot_sessions to service_role;
revoke all on sequence public.salesbot_sessions_id_seq from anon, authenticated;
revoke all on table public.salesbot_logs from anon, authenticated;
grant select on table public.salesbot_logs to authenticated;
grant all on table public.salesbot_logs to service_role;
revoke all on sequence public.salesbot_logs_id_seq from anon, authenticated;

revoke all on function public.start_salesbot(bigint, bigint) from public, anon;
grant execute on function public.start_salesbot(bigint, bigint) to authenticated, service_role;
revoke all on function public.stop_salesbot(bigint) from public, anon;
grant execute on function public.stop_salesbot(bigint) to authenticated, service_role;

revoke all on function private.salesbot_log(public.salesbot_sessions, jsonb, text, text, jsonb) from public, anon, authenticated;
revoke all on function private.salesbot_finish(bigint, text, text) from public, anon, authenticated;
revoke all on function private.salesbot_apply_set(jsonb, public.deals, text) from public, anon, authenticated;
revoke all on function private.salesbot_advance(bigint) from public, anon, authenticated;
revoke all on function private.salesbot_start(bigint, bigint, text, bigint) from public, anon, authenticated;
revoke all on function private.salesbot_on_inbound(public.messages) from public, anon, authenticated;
revoke all on function private.handle_message_salesbot() from public, anon, authenticated;
revoke all on function private.handle_deal_salesbot() from public, anon, authenticated;
revoke all on function private.salesbot_tick(timestamp with time zone) from public, anon, authenticated;
revoke all on function private.salesbot_message_text(jsonb, public.deals, text) from public, anon, authenticated;

--
-- Changes of earlier files
--

-- 16_notifications.sql: the kind «Бот передал диалог»
alter table public.notifications drop constraint notifications_kind_check;
alter table public.notifications add constraint notifications_kind_check
    check (kind in ('lead_assigned', 'patient_message', 'task_overdue', 'response_overdue', 'bot_handoff'));
alter table public.notification_preferences drop constraint notification_preferences_kinds_check;
alter table public.notification_preferences add constraint notification_preferences_kinds_check
    check (kinds <@ array['lead_assigned', 'patient_message', 'task_overdue', 'response_overdue', 'bot_handoff']);
alter table public.notification_preferences alter column kinds
    set default array['lead_assigned', 'patient_message', 'task_overdue', 'response_overdue', 'bot_handoff'];

-- Preferences of the current employee (the defaults when never saved)
CREATE OR REPLACE FUNCTION "public"."get_notification_preferences"() RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  me bigint := private.current_sales_id();
  prefs public.notification_preferences;
begin
  if me is null then
    raise exception 'Not an employee' using errcode = '42501';
  end if;
  select * into prefs from public.notification_preferences p where p.sales_id = me;
  return jsonb_build_object(
    'kinds', to_jsonb(coalesce(prefs.kinds, array['lead_assigned', 'patient_message', 'task_overdue', 'response_overdue', 'bot_handoff'])),
    'browser_enabled', coalesce(prefs.browser_enabled, false),
    'telegram_enabled', coalesce(prefs.telegram_enabled, true),
    'telegram_linked', prefs.telegram_chat_id is not null,
    'telegram_username', prefs.telegram_username,
    'telegram_link_code', case when prefs.telegram_link_expires_at > now() then prefs.telegram_link_code end,
    'telegram_link_expires_at', case when prefs.telegram_link_expires_at > now() then prefs.telegram_link_expires_at end
  );
end;
$$;

-- 20_digital_pipeline.sql: the action «Запустить салесбот»
alter table public.stage_triggers drop constraint stage_triggers_action_check;
alter table public.stage_triggers add constraint stage_triggers_action_check check (action in ('move_stage', 'set_responsible', 'add_tag', 'remove_tag',
        'create_task', 'send_template', 'send_webhook', 'set_field', 'start_salesbot'));

-- The action of a trigger on a deal; returns what changed (shown in the deal
-- feed). Raises when the action cannot be done (the caller logs it).
CREATE OR REPLACE FUNCTION "private"."apply_stage_trigger_action"("trigger_row" "public"."stage_triggers", "deal" "public"."deals") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := deal.organization_id;
  new_sales_id bigint;
  new_id bigint;
  zone text;
  template_body text;
  rendered text;
  old_value jsonb;
  queued integer;
begin
  case trigger_row.action
  when 'move_stage' then
    if deal.stage_id = trigger_row.target_stage_id then
      return jsonb_build_object('unchanged', true);
    end if;
    update public.deals d
    set stage_id = trigger_row.target_stage_id
    where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('from_stage_id', deal.stage_id, 'to_stage_id', trigger_row.target_stage_id);

  when 'set_responsible' then
    new_sales_id := coalesce(trigger_row.target_sales_id, private.next_responsible(org_id));
    if new_sales_id is null then
      raise exception 'Некому назначить: распределение по очереди не настроено' using errcode = '22023';
    end if;
    if exists (select 1 from public.sales s where s.id = new_sales_id and s.disabled) then
      raise exception 'Сотрудник отключён' using errcode = '22023';
    end if;
    if deal.sales_id is not distinct from new_sales_id then
      return jsonb_build_object('unchanged', true);
    end if;
    update public.deals d
    set sales_id = new_sales_id
    where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('from_sales_id', deal.sales_id, 'to_sales_id', new_sales_id);

  when 'add_tag' then
    if trigger_row.tag_id = any(deal.tags) then
      return jsonb_build_object('unchanged', true, 'tag_id', trigger_row.tag_id);
    end if;
    update public.deals d
    set tags = array_append(d.tags, trigger_row.tag_id)
    where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('tag_id', trigger_row.tag_id);

  when 'remove_tag' then
    if not trigger_row.tag_id = any(deal.tags) then
      return jsonb_build_object('unchanged', true, 'tag_id', trigger_row.tag_id);
    end if;
    update public.deals d
    set tags = array_remove(d.tags, trigger_row.tag_id)
    where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('tag_id', trigger_row.tag_id);

  when 'create_task' then
    -- Same as the task rules (private.create_rule_tasks)
    insert into public.tasks (organization_id, deal_id, type, text, due_date, sales_id)
    values (org_id, deal.id, trigger_row.task_type, btrim(trigger_row.task_text),
      now() + make_interval(mins => trigger_row.task_due_minutes), deal.sales_id)
    returning id into new_id;
    return jsonb_build_object('task_id', new_id);

  when 'send_template' then
    -- The stage 6 queue: "show first" becomes the task with the text and the
    -- «Отправить» button right away; "auto" is sent by the dispatcher
    -- (quiet hours apply, leaving the stage cancels it)
    if coalesce(trigger_row.message_mode, 'auto') = 'confirm' then
      select t.body into template_body from public.message_templates t
      where t.organization_id = org_id and t.id = trigger_row.template_id;
      rendered := private.render_template(template_body, private.automessage_vars(deal));
      insert into public.automessages (organization_id, deal_id, rule_id, template_id, stage_id, timing, send_at, status, text, processed_at)
      values (org_id, deal.id, null, trigger_row.template_id, deal.stage_id, 'after_stage', now(), 'awaiting', rendered, now())
      returning id into new_id;
      insert into public.tasks (organization_id, deal_id, type, text, due_date, sales_id, automessage_id)
      values (org_id, deal.id, 'message', rendered, now(), deal.sales_id, new_id);
    else
      select o.timezone into zone from public.organizations o where o.id = org_id;
      insert into public.automessages (organization_id, deal_id, rule_id, template_id, stage_id, timing, send_at)
      values (org_id, deal.id, null, trigger_row.template_id, deal.stage_id, 'after_stage',
        private.automessage_send_time(now(), zone))
      returning id into new_id;
    end if;
    return jsonb_build_object('automessage_id', new_id, 'template_id', trigger_row.template_id,
      'mode', coalesce(trigger_row.message_mode, 'auto'));

  when 'send_webhook' then
    queued := private.enqueue_webhook(org_id, 'automation',
      jsonb_build_object('deal_id', deal.id, 'patient_id', deal.patient_id,
        'trigger', jsonb_build_object('id', trigger_row.id, 'name', trigger_row.name, 'event', trigger_row.event),
        'deal', private.deal_json(deal)),
      trigger_row.webhook_id);
    if queued = 0 then
      raise exception 'Вебхук выключен' using errcode = '22023';
    end if;
    return jsonb_build_object('webhook_id', trigger_row.webhook_id);

  when 'start_salesbot' then
    -- «Запустить салесбот» (26_salesbot.sql): replaces the bot of the deal
    new_id := private.salesbot_start(trigger_row.salesbot_id, deal.id, 'pipeline');
    if new_id is null then
      raise exception 'Бот не запущен' using errcode = '22023';
    end if;
    return jsonb_build_object('salesbot_id', trigger_row.salesbot_id, 'session_id', new_id);

  when 'set_field' then
    old_value := to_jsonb(deal) -> trigger_row.field_name;
    if trigger_row.field_name = 'plan_amount' then
      update public.deals d set plan_amount = trigger_row.plan_amount
      where d.organization_id = org_id and d.id = deal.id;
      return jsonb_build_object('field', 'plan_amount', 'from', old_value, 'to', trigger_row.plan_amount);
    elsif trigger_row.field_name = 'doctor_id' then
      update public.deals d set doctor_id = trigger_row.doctor_id
      where d.organization_id = org_id and d.id = deal.id;
      return jsonb_build_object('field', 'doctor_id', 'from', old_value, 'to', trigger_row.doctor_id);
    else
      update public.deals d set service_id = trigger_row.service_id
      where d.organization_id = org_id and d.id = deal.id;
      return jsonb_build_object('field', 'service_id', 'from', old_value, 'to', trigger_row.service_id);
    end if;
  end case;
  return '{}'::jsonb;
end;
$$;

-- 08_automessages.sql: the messages of a salesbot (text ready, not tied to the stage)

-- Cancels the queued messages of a deal (statuses: which ones; only_timing:
-- only the rows of this timing)
CREATE OR REPLACE FUNCTION "private"."cancel_automessages"("org_id" bigint, "target_deal_id" bigint, "statuses" "text"[], "only_timing" "text", "reason" "text") RETURNS integer
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  cancelled integer;
begin
  -- The messages of a salesbot (26_salesbot.sql) belong to its conversation:
  -- leaving the stage does not cancel them, stopping the bot does
  update public.automessages a
  set status = 'cancelled', error = reason, processed_at = now()
  where a.organization_id = org_id
    and a.deal_id = target_deal_id
    and a.status = any(statuses)
    and (only_timing is null or a.timing = only_timing)
    and a.salesbot_session_id is null;
  get diagnostics cancelled = row_count;
  return cancelled;
end;
$$;

-- Dispatcher (edge function automessages_dispatch, service role only): takes
-- the due rows, at most per_clinic per clinic, with FOR UPDATE SKIP LOCKED so
-- that two runs never take the same row. Returns the rows to send through
-- Wazzup24 (status sending); "show first" rows become a task (awaiting);
-- rows whose deal left the stage or whose rule is off are cancelled; a
-- clinic without messengers gets a failed row with the reason.
CREATE OR REPLACE FUNCTION "public"."claim_automessages"("per_clinic" integer DEFAULT 20) RETURNS TABLE("id" bigint, "organization_id" bigint, "deal_id" bigint, "patient_id" bigint, "message_text" "text")
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  job public.automessages;
  job_deal public.deals;
  job_rule public.automessage_rules;
  template_body text;
  rendered text;
  taken jsonb := '{}'::jsonb;
begin
  -- A run that died while sending: rather a failed row than a message sent twice
  update public.automessages a
  set status = 'failed', error = 'Отправка прервалась, проверьте переписку', processed_at = now()
  where a.status = 'sending' and a.claimed_at < now() - interval '10 minutes';

  for job in
    select a.* from public.automessages a
    where a.status = 'pending' and a.send_at <= now()
    order by a.send_at, a.id
    limit 1000
    for update skip locked
  loop
    if coalesce((taken ->> job.organization_id::text)::integer, 0) >= per_clinic then
      continue;
    end if;
    select d.* into job_deal from public.deals d
    where d.organization_id = job.organization_id and d.id = job.deal_id;
    select r.* into job_rule from public.automessage_rules r
    where r.organization_id = job.organization_id and r.id = job.rule_id;

    -- A message of a salesbot (stage 26) has its text and stays when the
    -- deal changes stage (the bot moves it itself)
    if (job.salesbot_session_id is null and job_deal.stage_id is distinct from job.stage_id)
      or job_deal.archived_at is not null then
      update public.automessages a
      set status = 'cancelled', error = 'Сделка ушла с этапа', processed_at = now()
      where a.id = job.id;
      continue;
    end if;
    -- A row queued by a stage trigger (stage 20) has its template, no rule
    if job.salesbot_session_id is null and job.template_id is null
      and (job_rule.id is null or not job_rule.is_active) then
      update public.automessages a
      set status = 'cancelled', error = 'Правило выключено или удалено', processed_at = now()
      where a.id = job.id;
      continue;
    end if;

    if job.salesbot_session_id is not null then
      rendered := job.text;
    else
      select t.body into template_body from public.message_templates t
      where t.organization_id = job.organization_id and t.id = coalesce(job.template_id, job_rule.template_id);
      rendered := private.render_template(template_body, private.automessage_vars(job_deal));
    end if;
    if coalesce(rendered, '') = '' then
      update public.automessages a
      set status = 'failed', error = 'Пустой текст сообщения', processed_at = now()
      where a.id = job.id;
      continue;
    end if;

    if job_rule.mode = 'confirm' then
      insert into public.tasks (organization_id, deal_id, type, text, due_date, sales_id, automessage_id)
      values (job.organization_id, job.deal_id, 'message', rendered, now(), job_deal.sales_id, job.id);
      update public.automessages a
      set status = 'awaiting', text = rendered, processed_at = now()
      where a.id = job.id;
      continue;
    end if;

    if not exists (
      select 1 from public.messenger_integrations i
      where i.organization_id = job.organization_id and i.api_key is not null
    ) and not exists (
      select 1 from public.telegram_bots b
      where b.organization_id = job.organization_id and b.bot_token is not null
    ) then
      update public.automessages a
      set status = 'failed', text = rendered, processed_at = now(),
          error = 'Мессенджеры не подключены (Настройки → Мессенджеры)'
      where a.id = job.id;
      continue;
    end if;

    update public.automessages a
    set status = 'sending', text = rendered, claimed_at = now()
    where a.id = job.id;
    taken := jsonb_set(taken, array[job.organization_id::text],
      to_jsonb(coalesce((taken ->> job.organization_id::text)::integer, 0) + 1));
    id := job.id;
    organization_id := job.organization_id;
    deal_id := job.deal_id;
    patient_id := job_deal.patient_id;
    message_text := rendered;
    return next;
  end loop;
end;
$$;

-- The timeouts and delays of the bots every minute; skipped where pg_cron is
-- not installed, e.g. the SQL tests
do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule('salesbot-tick', '* * * * *', 'select private.salesbot_tick()');
  end if;
end;
$$;
