--
-- Repeat sales and segment mailings (stage 17)
--
-- Repeat sales: a recall rule "a deal won (of a service) -> N months later a
-- new deal" is processed by a daily pg_cron job (private.process_recalls).
-- Every (rule, won deal) is handled once (table recalls): a new deal is
-- created, or the recall is skipped (the patient already has an open deal)
-- or cancelled (the patient opted out). The rule may also message the
-- patient: "show first" reuses the stage 6 queue (automessages row awaiting +
-- task with the «Отправить» button), "auto" goes through the mailing queue.
--
-- Mailings: the owner or the head picks a segment of patients and a text;
-- the recipients are queued in mailing_messages. The edge function
-- mailings_dispatch, started every minute by pg_cron, takes the due rows
-- (public.claim_mailing_messages) within the anti-ban limits of the clinic
-- (per minute, per day, working hours) and sends them through Wazzup24 like
-- the automatic messages, with a random pause between two messages.
--
-- Opt-out: patients.messaging_opt_out (a toggle on the patient card, set
-- automatically by an incoming «стоп» / «stop» / «отписаться», or by a
-- refusal with the reason «Не беспокоить»). Such a patient never gets
-- mailings or recall messages; service messages of open deals still work.
--

alter table public.patients add column messaging_opt_out boolean not null default false;
alter table public.patients add column messaging_opt_out_at timestamp with time zone;

-- Won deal (of service_id, or any) -> delay_months later a new deal in
-- pipeline_id / stage_id, of deal_service_id (else the service of the won
-- deal), optionally with a message of template_id
create table public.recall_rules (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    service_id bigint,
    delay_months integer not null default 6,
    pipeline_id bigint not null,
    stage_id bigint not null,
    deal_service_id bigint,
    template_id bigint,
    message_mode text not null default 'confirm',
    is_active boolean not null default false,
    position integer not null default 0,
    created_at timestamp with time zone not null default now(),
    constraint recall_rules_name_not_blank check (btrim(name) <> ''),
    constraint recall_rules_delay_check check (delay_months between 1 and 60),
    constraint recall_rules_mode_check check (message_mode in ('auto', 'confirm'))
);

-- One row per (rule, won deal): what the daily job did and why
create table public.recalls (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    rule_id bigint,
    deal_id bigint not null,
    patient_id bigint not null,
    due_at timestamp with time zone not null,
    status text not null,
    recall_deal_id bigint,
    reason text,
    created_at timestamp with time zone not null default now(),
    constraint recalls_status_check check (status in ('created', 'skipped', 'cancelled'))
);

-- Anti-ban limits of the clinic (WhatsApp): within safe bounds
create table public.mailing_settings (
    organization_id bigint primary key default private.current_organization_id(),
    per_minute integer not null default 10,
    per_day integer not null default 300,
    work_start time without time zone not null default '09:00',
    work_end time without time zone not null default '21:00',
    constraint mailing_settings_per_minute_check check (per_minute between 1 and 20),
    constraint mailing_settings_per_day_check check (per_day between 1 and 1000),
    constraint mailing_settings_hours_check check (work_start >= '08:00' and work_end <= '22:00' and work_start < work_end)
);

-- A mailing to a segment of patients. scheduled -> done (everything taken),
-- scheduled <-> paused, scheduled | paused -> cancelled.
-- segment: { tag_ids, tag_mode (any | all), service_ids, inactive_months,
-- source_ids, has_open_deal, sales_ids } (see private.mailing_segment)
create table public.mailings (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    segment jsonb not null default '{}'::jsonb,
    template_id bigint,
    body text not null,
    scheduled_at timestamp with time zone not null default now(),
    status text not null default 'scheduled',
    recipients_count integer not null default 0,
    created_by bigint default private.current_sales_id(),
    created_at timestamp with time zone not null default now(),
    finished_at timestamp with time zone,
    constraint mailings_name_not_blank check (btrim(name) <> ''),
    constraint mailings_body_not_blank check (btrim(body) <> ''),
    constraint mailings_status_check check (status in ('scheduled', 'paused', 'cancelled', 'done')),
    constraint mailings_segment_is_object check (jsonb_typeof(segment) = 'object')
);

-- The queue of mailings and recall messages, one row per patient.
-- pending -> sending -> sent | failed; pending -> skipped (opted out, no
-- phone or chat) | cancelled. deal_id: the recall deal, or for a mailing the
-- deal the message was attached to (the latest open deal, else the latest
-- deal); without any deal the message is sent to the patient's chat and only
-- recorded here (external_id, delivery_status).
create table public.mailing_messages (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    mailing_id bigint,
    recall_id bigint,
    patient_id bigint not null,
    deal_id bigint,
    body text not null,
    send_at timestamp with time zone not null default now(),
    status text not null default 'pending',
    text text,
    error text,
    message_id bigint,
    external_id text,
    delivery_status text,
    claimed_at timestamp with time zone,
    processed_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    constraint mailing_messages_status_check check (status in ('pending', 'sending', 'sent', 'failed', 'skipped', 'cancelled')),
    constraint mailing_messages_origin_check check ((mailing_id is null) <> (recall_id is null))
);

-- The message stored for a queued mailing row
alter table public.messages add column mailing_message_id bigint;

alter table public.recall_rules add constraint recall_rules_organization_id_id_key unique (organization_id, id);
alter table public.recalls add constraint recalls_organization_id_id_key unique (organization_id, id);
alter table public.mailings add constraint mailings_organization_id_id_key unique (organization_id, id);
alter table public.mailing_messages add constraint mailing_messages_organization_id_id_key unique (organization_id, id);

alter table public.recall_rules
    add constraint recall_rules_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.recall_rules
    add constraint recall_rules_pipeline_id_fkey foreign key (organization_id, pipeline_id) references public.pipelines(organization_id, id) on delete cascade;
-- The stage must belong to the pipeline
alter table public.recall_rules
    add constraint recall_rules_stage_id_fkey foreign key (pipeline_id, stage_id) references public.stages(pipeline_id, id) on delete cascade;
alter table public.recall_rules
    add constraint recall_rules_service_id_fkey foreign key (organization_id, service_id) references public.services(organization_id, id) on delete cascade;
alter table public.recall_rules
    add constraint recall_rules_deal_service_id_fkey foreign key (organization_id, deal_service_id) references public.services(organization_id, id) on delete set null (deal_service_id);
alter table public.recall_rules
    add constraint recall_rules_template_id_fkey foreign key (organization_id, template_id) references public.message_templates(organization_id, id) on delete set null (template_id);
alter table public.recalls
    add constraint recalls_rule_id_fkey foreign key (organization_id, rule_id) references public.recall_rules(organization_id, id) on delete set null (rule_id);
alter table public.recalls
    add constraint recalls_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.recalls
    add constraint recalls_patient_id_fkey foreign key (organization_id, patient_id) references public.patients(organization_id, id) on delete cascade;
alter table public.recalls
    add constraint recalls_recall_deal_id_fkey foreign key (organization_id, recall_deal_id) references public.deals(organization_id, id) on delete set null (recall_deal_id);
alter table public.mailing_settings
    add constraint mailing_settings_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.mailings
    add constraint mailings_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.mailings
    add constraint mailings_template_id_fkey foreign key (organization_id, template_id) references public.message_templates(organization_id, id) on delete set null (template_id);
alter table public.mailings
    add constraint mailings_created_by_fkey foreign key (organization_id, created_by) references public.sales(organization_id, id) on delete set null (created_by);
alter table public.mailing_messages
    add constraint mailing_messages_mailing_id_fkey foreign key (organization_id, mailing_id) references public.mailings(organization_id, id) on delete cascade;
alter table public.mailing_messages
    add constraint mailing_messages_recall_id_fkey foreign key (organization_id, recall_id) references public.recalls(organization_id, id) on delete cascade;
alter table public.mailing_messages
    add constraint mailing_messages_patient_id_fkey foreign key (organization_id, patient_id) references public.patients(organization_id, id) on delete cascade;
alter table public.mailing_messages
    add constraint mailing_messages_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete set null (deal_id);
alter table public.mailing_messages
    add constraint mailing_messages_message_id_fkey foreign key (organization_id, message_id) references public.messages(organization_id, id) on delete set null (message_id);
alter table public.messages
    add constraint messages_mailing_message_id_fkey foreign key (organization_id, mailing_message_id) references public.mailing_messages(organization_id, id) on delete set null (mailing_message_id);

create unique index recalls_rule_deal_idx on public.recalls using btree (rule_id, deal_id);
create index recalls_created_at_idx on public.recalls using btree (organization_id, created_at);
create index recall_rules_organization_id_idx on public.recall_rules using btree (organization_id, position);
create index mailings_created_at_idx on public.mailings using btree (organization_id, created_at);
-- A patient is queued once per mailing
create unique index mailing_messages_mailing_patient_idx on public.mailing_messages using btree (mailing_id, patient_id) where mailing_id is not null;
create index mailing_messages_due_idx on public.mailing_messages using btree (send_at) where status = 'pending';
create index mailing_messages_claimed_idx on public.mailing_messages using btree (organization_id, claimed_at) where claimed_at is not null;
create index mailing_messages_external_id_idx on public.mailing_messages using btree (organization_id, external_id) where external_id is not null;
create index mailing_messages_patient_id_idx on public.mailing_messages using btree (organization_id, patient_id);
create index messages_mailing_message_id_idx on public.messages using btree (organization_id, mailing_message_id) where mailing_message_id is not null;

--
-- Views
--

-- Progress of the mailings: statuses of the queue and of the sent messages
create or replace view public.mailings_summary with (security_invoker = on) as
select
    ml.id,
    ml.organization_id,
    ml.name,
    ml.segment,
    ml.template_id,
    ml.body,
    ml.scheduled_at,
    ml.status,
    ml.recipients_count,
    ml.created_by,
    ml.created_at,
    ml.finished_at,
    coalesce(q.queued, 0) as queued_count,
    coalesce(q.sent, 0) as sent_count,
    coalesce(q.delivered, 0) as delivered_count,
    coalesce(q.read, 0) as read_count,
    coalesce(q.failed, 0) as failed_count,
    coalesce(q.skipped, 0) as skipped_count,
    coalesce(q.cancelled, 0) as cancelled_count
from public.mailings ml
    left join lateral (
        select
            count(*) filter (where mm.status in ('pending', 'sending')) as queued,
            count(*) filter (where mm.status = 'sent') as sent,
            count(*) filter (where mm.status = 'sent' and coalesce(m.status, mm.delivery_status) in ('delivered', 'read')) as delivered,
            count(*) filter (where mm.status = 'sent' and coalesce(m.status, mm.delivery_status) = 'read') as read,
            count(*) filter (where mm.status = 'failed' or (mm.status = 'sent' and coalesce(m.status, mm.delivery_status) = 'error')) as failed,
            count(*) filter (where mm.status = 'skipped') as skipped,
            count(*) filter (where mm.status = 'cancelled') as cancelled
        from public.mailing_messages mm
            left join public.messages m on m.organization_id = mm.organization_id and m.id = mm.message_id
        where mm.organization_id = ml.organization_id and mm.mailing_id = ml.id
    ) q on true;

--
-- Functions
--

-- «Стоп», «STOP!», « отписаться » (whole message; any case, trailing
-- punctuation and spaces ignored). Cyrillic is lowered by translate() so
-- that the result does not depend on the database locale.
CREATE OR REPLACE FUNCTION "private"."is_opt_out_text"("value" "text") RETURNS boolean
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select lower(translate(
      regexp_replace(coalesce(value, ''), '^[[:space:][:punct:]]+|[[:space:][:punct:]]+$', '', 'g'),
      'АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ',
      'абвгдеёжзийклмнопрстуфхцчшщъыьэюя'))
    in ('стоп', 'stop', 'отписаться')
$$;

-- The system source of the recall deals (created when missing)
CREATE OR REPLACE FUNCTION "private"."repeat_source_id"("org_id" bigint) RETURNS bigint
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  found_id bigint;
begin
  select s.id into found_id from public.lead_sources s
  where s.organization_id = org_id and s.code = 'repeat';
  if found_id is null then
    insert into public.lead_sources (organization_id, name, code, is_system, position)
    values (org_id, 'Повторное обращение', 'repeat', true,
      coalesce((select max(s.position) + 1 from public.lead_sources s where s.organization_id = org_id), 0))
    returning id into found_id;
  end if;
  return found_id;
end;
$$;

-- Defaults of a clinic (new clinics through the owner trigger, existing ones
-- through the migration): the anti-ban limits and a recall rule
-- «Профгигиена»: 6 months after any won deal, a deal «Повторный визит:
-- Гигиена» on the first stage of the main pipeline (off, no message until a
-- template is chosen). The dictionaries are not touched: the source
-- «Повторное обращение» is added with the first recall deal
-- (private.repeat_source_id), the refusal reason «Не беспокоить» is
-- recognized by its name when the clinic adds it.
CREATE OR REPLACE FUNCTION "private"."seed_repeat_mailings"("org_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  default_pipeline_id bigint;
  first_stage_id bigint;
  hygiene_id bigint;
begin
  insert into public.mailing_settings (organization_id) values (org_id)
  on conflict (organization_id) do nothing;

  if exists (select 1 from public.recall_rules r where r.organization_id = org_id) then
    return;
  end if;
  select p.id into default_pipeline_id from public.pipelines p
  where p.organization_id = org_id and p.is_default;
  if default_pipeline_id is null then
    return;
  end if;
  select s.id into first_stage_id from public.stages s
  where s.pipeline_id = default_pipeline_id
  order by s.position, s.id limit 1;
  select s.id into hygiene_id from public.services s
  where s.organization_id = org_id and s.name in ('Гигиена', 'Профгигиена')
  order by s.position, s.id limit 1;

  insert into public.recall_rules (organization_id, name, service_id, delay_months, pipeline_id, stage_id,
    deal_service_id, template_id, message_mode, is_active, position)
  values (org_id, 'Профгигиена', null, 6, default_pipeline_id, first_stage_id,
    hygiene_id, null, 'confirm', false, 0);
end;
$$;

-- The owner is created right after the clinic and its pipeline
CREATE OR REPLACE FUNCTION "private"."handle_owner_created"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  perform private.seed_repeat_mailings(new.organization_id);
  return null;
end;
$$;

-- Due recalls between from_at (excluded) and to_at (included), of one clinic
-- (or all): the latest won deal of the patient matching an active rule,
-- delay_months after it was won, not handled yet
CREATE OR REPLACE FUNCTION "private"."recall_candidates"("org_id" bigint, "from_at" timestamp with time zone, "to_at" timestamp with time zone) RETURNS TABLE("organization_id" bigint, "rule_id" bigint, "deal_id" bigint, "patient_id" bigint, "due_at" timestamp with time zone)
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
  select c.organization_id, c.rule_id, c.deal_id, c.patient_id, c.due_at
  from (
    select r.organization_id, r.id as rule_id, d.id as deal_id, d.patient_id,
      d.closed_at + make_interval(months => r.delay_months) as due_at,
      row_number() over (partition by r.id, d.patient_id order by d.closed_at desc, d.id desc) as rank
    from public.recall_rules r
      join public.deals d on d.organization_id = r.organization_id
      join public.stages s on s.id = d.stage_id
    where r.is_active
      and (org_id is null or r.organization_id = org_id)
      and s.kind = 'won'
      and d.closed_at is not null
      and d.archived_at is null
      and (r.service_id is null or d.service_id = r.service_id)
  ) c
  where c.rank = 1
    and c.due_at > from_at
    and c.due_at <= to_at
    and not exists (select 1 from public.recalls x where x.rule_id = c.rule_id and x.deal_id = c.deal_id)
$$;

-- Daily job (pg_cron): recalls due in the last 30 days are handled once:
--   the patient opted out, or refused with «Не беспокоить» -> cancelled;
--   the patient has an open deal -> skipped;
--   else a deal «Повторный визит: {услуга}» with the source «Повторное
--   обращение», the responsible of the won deal, and the message of the rule.
CREATE OR REPLACE FUNCTION "private"."process_recalls"("moment" timestamp with time zone DEFAULT "now"()) RETURNS integer
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  candidate record;
  recall_rule public.recall_rules;
  won_deal public.deals;
  target public.patients;
  new_deal public.deals;
  recall_row_id bigint;
  service_name text;
  responsible bigint;
  template_body text;
  rendered text;
  am_id bigint;
  handled integer := 0;
begin
  for candidate in
    select * from private.recall_candidates(null, moment - interval '30 days', moment) c
    order by c.due_at, c.deal_id
  loop
    insert into public.recalls (organization_id, rule_id, deal_id, patient_id, due_at, status)
    values (candidate.organization_id, candidate.rule_id, candidate.deal_id, candidate.patient_id, candidate.due_at, 'created')
    on conflict (rule_id, deal_id) do nothing
    returning id into recall_row_id;
    if recall_row_id is null then
      continue;
    end if;
    handled := handled + 1;

    select * into recall_rule from public.recall_rules r where r.id = candidate.rule_id;
    select * into won_deal from public.deals d
    where d.organization_id = candidate.organization_id and d.id = candidate.deal_id;
    select * into target from public.patients p
    where p.organization_id = candidate.organization_id and p.id = candidate.patient_id;

    if target.messaging_opt_out then
      update public.recalls x set status = 'cancelled', reason = 'Пациент отказался от сообщений'
      where x.id = recall_row_id;
      continue;
    end if;
    if exists (
      select 1 from public.deals d
        join public.stages s on s.id = d.stage_id
        join public.lost_reasons lr on lr.organization_id = d.organization_id and lr.id = d.lost_reason_id
      where d.organization_id = target.organization_id and d.patient_id = target.id
        and s.kind = 'lost' and lower(btrim(lr.name)) in ('не беспокоить', 'Не беспокоить')
    ) then
      update public.recalls x set status = 'cancelled', reason = 'Отказ «Не беспокоить»'
      where x.id = recall_row_id;
      continue;
    end if;
    if exists (
      select 1 from public.deals d
        join public.stages s on s.id = d.stage_id
      where d.organization_id = target.organization_id and d.patient_id = target.id
        and s.kind = 'open' and d.archived_at is null
    ) then
      update public.recalls x set status = 'skipped', reason = 'У пациента уже есть открытая сделка'
      where x.id = recall_row_id;
      continue;
    end if;

    select sv.name into service_name from public.services sv
    where sv.organization_id = recall_rule.organization_id and sv.id = coalesce(recall_rule.deal_service_id, won_deal.service_id);
    select sl.id into responsible from public.sales sl
    where sl.organization_id = recall_rule.organization_id and not sl.disabled
      and sl.id = coalesce(won_deal.sales_id, target.sales_id);

    insert into public.deals (organization_id, patient_id, pipeline_id, stage_id, name, source_id, service_id, sales_id)
    values (recall_rule.organization_id, target.id, recall_rule.pipeline_id, recall_rule.stage_id,
      'Повторный визит: ' || coalesce(service_name, recall_rule.name),
      private.repeat_source_id(recall_rule.organization_id),
      coalesce(recall_rule.deal_service_id, won_deal.service_id),
      responsible)
    returning * into new_deal;
    update public.recalls x set recall_deal_id = new_deal.id where x.id = recall_row_id;

    -- The message of the rule, when the patient can be reached
    if recall_rule.template_id is null or (cardinality(target.phones) = 0 and not exists (
      select 1 from public.patient_chats c where c.organization_id = target.organization_id and c.patient_id = target.id
    )) then
      continue;
    end if;
    select t.body into template_body from public.message_templates t
    where t.organization_id = recall_rule.organization_id and t.id = recall_rule.template_id;
    if recall_rule.message_mode = 'confirm' then
      -- Stage 6 "show first": the task with the text and the «Отправить» button
      rendered := private.render_template(template_body, private.automessage_vars(new_deal));
      insert into public.automessages (organization_id, deal_id, rule_id, stage_id, timing, send_at, status, text, processed_at)
      values (new_deal.organization_id, new_deal.id, null, new_deal.stage_id, 'after_stage', moment, 'awaiting', rendered, moment)
      returning id into am_id;
      insert into public.tasks (organization_id, deal_id, type, text, due_date, sales_id, automessage_id)
      values (new_deal.organization_id, new_deal.id, 'message', rendered, moment, new_deal.sales_id, am_id);
    else
      insert into public.mailing_messages (organization_id, recall_id, patient_id, deal_id, body, send_at)
      values (new_deal.organization_id, recall_row_id, target.id, new_deal.id, template_body, moment);
    end if;
  end loop;
  return handled;
end;
$$;

-- Patients of a segment of the clinic, with the reason a patient is left
-- out: opted_out, no_contact (no phone and no messenger chat), duplicate
-- (same first phone as a more recently seen patient), else ok. Filters (all
-- optional, combined with AND):
--   tag_ids + tag_mode: any (default) or all of the tags;
--   service_ids: a deal of one of these services;
--   inactive_months: the last visit or won deal is older than N months;
--   source_ids, sales_ids (responsible): of the patient;
--   has_open_deal: true / false.
CREATE OR REPLACE FUNCTION "private"."mailing_segment"("org_id" bigint, "segment" "jsonb", "moment" timestamp with time zone DEFAULT "now"()) RETURNS TABLE("patient_id" bigint, "status" "text")
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
  with f as (
    select
      array(select jsonb_array_elements_text(case when jsonb_typeof(segment -> 'tag_ids') = 'array' then segment -> 'tag_ids' else '[]'::jsonb end)::bigint) as tag_ids,
      coalesce(segment ->> 'tag_mode', 'any') as tag_mode,
      array(select jsonb_array_elements_text(case when jsonb_typeof(segment -> 'service_ids') = 'array' then segment -> 'service_ids' else '[]'::jsonb end)::bigint) as service_ids,
      array(select jsonb_array_elements_text(case when jsonb_typeof(segment -> 'source_ids') = 'array' then segment -> 'source_ids' else '[]'::jsonb end)::bigint) as source_ids,
      array(select jsonb_array_elements_text(case when jsonb_typeof(segment -> 'sales_ids') = 'array' then segment -> 'sales_ids' else '[]'::jsonb end)::bigint) as sales_ids,
      nullif(segment ->> 'inactive_months', '')::integer as inactive_months,
      nullif(segment ->> 'has_open_deal', '')::boolean as has_open_deal
  ),
  matched as (
    select p.id, p.phones, p.messaging_opt_out, p.last_seen
    from public.patients p, f
    where p.organization_id = org_id
      and (cardinality(f.tag_ids) = 0
        or (f.tag_mode = 'all' and p.tags @> f.tag_ids)
        or (f.tag_mode <> 'all' and p.tags && f.tag_ids))
      and (cardinality(f.service_ids) = 0 or exists (
        select 1 from public.deals d
        where d.organization_id = p.organization_id and d.patient_id = p.id and d.service_id = any(f.service_ids)))
      and (cardinality(f.source_ids) = 0 or p.source_id = any(f.source_ids))
      and (cardinality(f.sales_ids) = 0 or p.sales_id = any(f.sales_ids))
      and (f.has_open_deal is null or f.has_open_deal = exists (
        select 1 from public.deals d join public.stages s on s.id = d.stage_id
        where d.organization_id = p.organization_id and d.patient_id = p.id
          and s.kind = 'open' and d.archived_at is null))
      and (f.inactive_months is null or (
        select greatest(max(d.visit_at), max(d.closed_at) filter (where s.kind = 'won'))
        from public.deals d join public.stages s on s.id = d.stage_id
        where d.organization_id = p.organization_id and d.patient_id = p.id
      ) < moment - make_interval(months => f.inactive_months))
  ),
  classified as (
    select m.id, m.last_seen,
      case
        when m.messaging_opt_out then 'opted_out'
        when cardinality(m.phones) = 0 and not exists (
          select 1 from public.patient_chats c where c.organization_id = org_id and c.patient_id = m.id
        ) then 'no_contact'
      end as excluded,
      coalesce(m.phones[1], 'patient:' || m.id) as contact_key
    from matched m
  )
  select c.id,
    coalesce(c.excluded,
      case when row_number() over (partition by c.excluded is null, c.contact_key order by c.last_seen desc, c.id desc) > 1
        then 'duplicate' else 'ok' end)
  from classified c
$$;

-- Live count and preview of a segment (owner and head)
CREATE OR REPLACE FUNCTION "public"."mailing_segment_preview"("segment" "jsonb", "preview_limit" integer DEFAULT 20) RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  result jsonb;
begin
  if org_id is null or private.current_user_role() not in ('owner', 'head') then
    raise exception 'Рассылки доступны владельцу и руководителю' using errcode = '42501';
  end if;
  select jsonb_build_object(
    'count', count(*) filter (where s.status = 'ok'),
    'matched', count(*),
    'opted_out', count(*) filter (where s.status = 'opted_out'),
    'no_contact', count(*) filter (where s.status = 'no_contact'),
    'duplicates', count(*) filter (where s.status = 'duplicate'),
    'patients', coalesce((
      select jsonb_agg(jsonb_build_object('id', x.id, 'first_name', x.first_name, 'last_name', x.last_name, 'phone', x.phones[1])
        order by x.last_name nulls last, x.first_name, x.id)
      from (
        select p.id, p.first_name, p.last_name, p.phones
        from private.mailing_segment(org_id, segment) q
          join public.patients p on p.organization_id = org_id and p.id = q.patient_id
        where q.status = 'ok'
        order by p.last_name nulls last, p.first_name, p.id
        limit greatest(preview_limit, 0)
      ) x
    ), '[]'::jsonb)
  ) into result
  from private.mailing_segment(org_id, segment) s;
  return result;
end;
$$;

-- A new mailing queues the patients of its segment
CREATE OR REPLACE FUNCTION "private"."handle_mailing_created"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  queued integer;
begin
  insert into public.mailing_messages (organization_id, mailing_id, patient_id, body, send_at)
  select new.organization_id, new.id, s.patient_id, new.body, new.scheduled_at
  from private.mailing_segment(new.organization_id, new.segment) s
  where s.status = 'ok'
  order by s.patient_id;
  get diagnostics queued = row_count;
  update public.mailings ml set recipients_count = queued where ml.id = new.id;
  return null;
end;
$$;

-- The waiting messages of a cancelled mailing (called by the trigger of an
-- employee's update: only in the employee's clinic)
CREATE OR REPLACE FUNCTION "private"."cancel_mailing_messages"("org_id" bigint, "target_mailing_id" bigint) RETURNS integer
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  cancelled integer;
begin
  update public.mailing_messages mm
  set status = 'cancelled', error = 'Рассылка отменена', processed_at = now()
  where mm.organization_id = org_id and mm.mailing_id = target_mailing_id and mm.status = 'pending'
    and (auth.uid() is null or org_id = private.current_organization_id());
  get diagnostics cancelled = row_count;
  return cancelled;
end;
$$;

-- Employees pause, resume and cancel (column grant: status); the system
-- (dispatcher) marks done. Cancelling cancels the rows still waiting.
CREATE OR REPLACE FUNCTION "private"."handle_mailing_update"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
begin
  if new.status is distinct from old.status then
    if current_user = 'authenticated' and not (
      (old.status = 'scheduled' and new.status in ('paused', 'cancelled'))
      or (old.status = 'paused' and new.status in ('scheduled', 'cancelled'))
    ) then
      raise exception 'Эту рассылку нельзя перевести в статус «%»', new.status
        using errcode = 'check_violation', hint = 'mailing_status_locked';
    end if;
    if new.status in ('cancelled', 'done') then
      new.finished_at := now();
    end if;
    if new.status = 'cancelled' then
      perform private.cancel_mailing_messages(new.organization_id, new.id);
    end if;
  end if;
  return new;
end;
$$;

-- Opt-out switched on: the waiting mailing and recall messages are cancelled
CREATE OR REPLACE FUNCTION "private"."handle_patient_opt_out"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if not new.messaging_opt_out then
    new.messaging_opt_out_at := null;
    return new;
  end if;
  if tg_op = 'UPDATE' and old.messaging_opt_out then
    return new;
  end if;
  new.messaging_opt_out_at := now();
  if tg_op = 'UPDATE' then
    update public.mailing_messages mm
    set status = 'cancelled', error = 'Пациент отказался от сообщений', processed_at = now()
    where mm.organization_id = new.organization_id and mm.patient_id = new.id and mm.status = 'pending';
    update public.automessages a
    set status = 'cancelled', error = 'Пациент отказался от сообщений', processed_at = now()
    where a.organization_id = new.organization_id and a.rule_id is null
      and a.status in ('pending', 'awaiting')
      and a.deal_id in (
        select x.recall_deal_id from public.recalls x
        where x.organization_id = new.organization_id and x.patient_id = new.id
      );
  end if;
  return new;
end;
$$;

-- An incoming «стоп» / «stop» / «отписаться» opts the patient out
CREATE OR REPLACE FUNCTION "private"."handle_message_opt_out"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if private.is_opt_out_text(new.text) then
    update public.patients p
    set messaging_opt_out = true
    where p.organization_id = new.organization_id and p.id = new.patient_id
      and not p.messaging_opt_out;
  end if;
  return null;
end;
$$;

-- A refusal with the reason «Не беспокоить» opts the patient out
CREATE OR REPLACE FUNCTION "private"."handle_deal_do_not_disturb"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if new.lost_reason_id is not null
    and exists (select 1 from public.stages s where s.id = new.stage_id and s.kind = 'lost')
    and exists (
      select 1 from public.lost_reasons lr
      where lr.organization_id = new.organization_id and lr.id = new.lost_reason_id
        and lower(btrim(lr.name)) in ('не беспокоить', 'Не беспокоить')
    )
  then
    update public.patients p
    set messaging_opt_out = true
    where p.organization_id = new.organization_id and p.id = new.patient_id
      and not p.messaging_opt_out;
  end if;
  return null;
end;
$$;

-- A message stored with its mailing row: the row is sent
CREATE OR REPLACE FUNCTION "private"."handle_mailing_message_sent"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  update public.mailing_messages mm
  set status = 'sent', error = null, text = new.text, message_id = new.id,
      external_id = new.external_id, processed_at = now()
  where mm.organization_id = new.organization_id and mm.id = new.mailing_message_id;
  return null;
end;
$$;

-- How many mailing messages the clinic may still send at this moment:
-- nothing outside the working hours (clinic time zone), else the rest of the
-- per-minute and per-day limits (rows taken by the dispatcher count)
CREATE OR REPLACE FUNCTION "private"."mailing_allowance"("org_id" bigint, "moment" timestamp with time zone) RETURNS integer
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
  select case
    when (moment at time zone z.tz)::time < st.work_start or (moment at time zone z.tz)::time >= st.work_end then 0
    else greatest(0, least(
      st.per_minute - (
        select count(*) from public.mailing_messages m
        where m.organization_id = org_id and m.claimed_at > moment - interval '1 minute' and m.claimed_at <= moment),
      st.per_day - (
        select count(*) from public.mailing_messages m
        where m.organization_id = org_id
          and m.claimed_at >= (((moment at time zone z.tz)::date)::timestamp without time zone at time zone z.tz)
          and m.claimed_at <= moment)
    ))::integer
  end
  from (
    select coalesce(nullif(o.timezone, ''), 'Asia/Almaty') as tz
    from public.organizations o where o.id = org_id
  ) z
  cross join lateral (
    select coalesce(s.per_minute, 10) as per_minute, coalesce(s.per_day, 300) as per_day,
      coalesce(s.work_start, time '09:00') as work_start, coalesce(s.work_end, time '21:00') as work_end
    from (select 1) one
      left join public.mailing_settings s on s.organization_id = org_id
  ) st
$$;

-- Template variables of a patient without a deal
CREATE OR REPLACE FUNCTION "private"."mailing_patient_vars"("org_id" bigint, "target_patient_id" bigint) RETURNS "jsonb"
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
  select jsonb_build_object(
    'имя', nullif(btrim(p.first_name), ''),
    'услуга', null,
    'дата_визита', null,
    'клиника', coalesce(nullif(btrim(c.config ->> 'title'), ''), o.name)
  )
  from public.organizations o
    left join public.configuration c on c.organization_id = o.id
    left join public.patients p on p.organization_id = o.id and p.id = target_patient_id
  where o.id = org_id
$$;

-- Dispatcher of the mailings (edge function mailings_dispatch, service role
-- only). Per clinic with Wazzup24 connected: at most per_run rows and what
-- the limits allow (private.mailing_allowance); rows of paused or cancelled
-- mailings wait. Opted-out patients and patients without a phone or a chat
-- are skipped; a recall message whose deal is closed is cancelled. The text
-- is rendered now; a mailing message is attached to the latest open deal,
-- else the latest deal, else none (the patient's chat only). Mailings with
-- nothing left are marked done.
CREATE OR REPLACE FUNCTION "public"."claim_mailing_messages"("per_run" integer DEFAULT 4) RETURNS TABLE("id" bigint, "organization_id" bigint, "patient_id" bigint, "deal_id" bigint, "message_text" "text")
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  clinic bigint;
  allowance integer;
  taken integer;
  job public.mailing_messages;
  target_deal public.deals;
  rendered text;
begin
  -- A run that died while sending: rather a failed row than a message sent twice
  update public.mailing_messages mm
  set status = 'failed', error = 'Отправка прервалась, проверьте переписку', processed_at = now()
  where mm.status = 'sending' and mm.claimed_at < now() - interval '10 minutes';

  for clinic in
    select distinct mm.organization_id from public.mailing_messages mm
    where mm.status = 'pending' and mm.send_at <= now()
    order by mm.organization_id
  loop
    if not exists (
      select 1 from public.messenger_integrations i
      where i.organization_id = clinic and i.api_key is not null
    ) then
      continue;
    end if;
    allowance := least(per_run, private.mailing_allowance(clinic, now()));
    taken := 0;
    if allowance <= 0 then
      continue;
    end if;

    for job in
      select mm.* from public.mailing_messages mm
        left join public.mailings ml on ml.organization_id = mm.organization_id and ml.id = mm.mailing_id
      where mm.organization_id = clinic and mm.status = 'pending' and mm.send_at <= now()
        and (mm.mailing_id is null or ml.status = 'scheduled')
      order by mm.send_at, mm.id
      limit 500
      for update of mm skip locked
    loop
      exit when taken >= allowance;

      if exists (
        select 1 from public.patients p
        where p.organization_id = clinic and p.id = job.patient_id and p.messaging_opt_out
      ) then
        update public.mailing_messages mm
        set status = 'skipped', error = 'Пациент отказался от сообщений', processed_at = now()
        where mm.id = job.id;
        continue;
      end if;
      if not exists (
        select 1 from public.patients p
        where p.organization_id = clinic and p.id = job.patient_id and cardinality(p.phones) > 0
      ) and not exists (
        select 1 from public.patient_chats c
        where c.organization_id = clinic and c.patient_id = job.patient_id
      ) then
        update public.mailing_messages mm
        set status = 'skipped', error = 'Нет телефона или чата', processed_at = now()
        where mm.id = job.id;
        continue;
      end if;

      if job.recall_id is not null then
        select d.* into target_deal from public.deals d
          join public.stages s on s.id = d.stage_id
        where d.organization_id = clinic and d.id = job.deal_id
          and s.kind = 'open' and d.archived_at is null;
        if target_deal.id is null then
          update public.mailing_messages mm
          set status = 'cancelled', error = 'Сделка повторной продажи уже закрыта', processed_at = now()
          where mm.id = job.id;
          continue;
        end if;
      else
        select d.* into target_deal from public.deals d
          join public.stages s on s.id = d.stage_id
        where d.organization_id = clinic and d.patient_id = job.patient_id
          and s.kind = 'open' and d.archived_at is null
        order by d.updated_at desc, d.id desc
        limit 1;
        if target_deal.id is null then
          select d.* into target_deal from public.deals d
          where d.organization_id = clinic and d.patient_id = job.patient_id
          order by d.updated_at desc, d.id desc
          limit 1;
        end if;
      end if;

      rendered := private.render_template(job.body,
        case when target_deal.id is not null
          then private.automessage_vars(target_deal)
          else private.mailing_patient_vars(clinic, job.patient_id)
        end);
      if coalesce(rendered, '') = '' then
        update public.mailing_messages mm
        set status = 'failed', error = 'Пустой текст сообщения', processed_at = now()
        where mm.id = job.id;
        continue;
      end if;

      update public.mailing_messages mm
      set status = 'sending', text = rendered, claimed_at = now(), deal_id = target_deal.id
      where mm.id = job.id;
      taken := taken + 1;
      id := job.id;
      organization_id := clinic;
      patient_id := job.patient_id;
      deal_id := target_deal.id;
      message_text := rendered;
      return next;
    end loop;
  end loop;

  update public.mailings ml
  set status = 'done'
  where ml.status = 'scheduled' and ml.scheduled_at <= now()
    and not exists (
      select 1 from public.mailing_messages mm
      where mm.organization_id = ml.organization_id and mm.mailing_id = ml.id
        and mm.status in ('pending', 'sending')
    );
end;
$$;

-- Delivery status of a mailing message sent without a deal (nothing stored
-- in messages): called by wazzup_webhook when update_message_status found
-- no message
CREATE OR REPLACE FUNCTION "public"."update_mailing_message_status"("webhook_token" "text", "external_id" "text", "status" "text", "error" "text" DEFAULT NULL::"text") RETURNS boolean
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint;
begin
  select i.organization_id into org_id
  from public.messenger_integrations i
  where i.webhook_token = update_mailing_message_status.webhook_token;
  if org_id is null then
    raise exception 'Unknown webhook token' using errcode = '28000';
  end if;
  if update_mailing_message_status.status not in ('sent', 'delivered', 'read', 'error') then
    return false;
  end if;
  update public.mailing_messages mm
  set delivery_status = update_mailing_message_status.status,
      error = case when update_mailing_message_status.status = 'error' then update_mailing_message_status.error else mm.error end
  where mm.organization_id = org_id
    and mm.external_id = update_mailing_message_status.external_id
    and mm.message_id is null;
  return found;
end;
$$;

-- Repeat sales screen (owner and head): recalls due in the next 30 days,
-- recalls handled in the period (created_at), and how many recall deals
-- were won
CREATE OR REPLACE FUNCTION "public"."report_recalls"("period_from" timestamp with time zone DEFAULT NULL::timestamp with time zone, "period_to" timestamp with time zone DEFAULT NULL::timestamp with time zone) RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  upcoming jsonb;
  handled jsonb;
  totals jsonb;
begin
  if org_id is null or private.current_user_role() not in ('owner', 'head') then
    raise exception 'Отчёты доступны владельцу и руководителю' using errcode = '42501';
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
      'rule_id', c.rule_id, 'rule_name', r.name, 'deal_id', c.deal_id, 'deal_name', d.name,
      'patient_id', c.patient_id, 'patient_name', btrim(concat_ws(' ', p.last_name, p.first_name)),
      'due_at', c.due_at, 'opted_out', p.messaging_opt_out)
    order by c.due_at, c.deal_id), '[]'::jsonb)
  into upcoming
  from private.recall_candidates(org_id, now(), now() + interval '30 days') c
    join public.recall_rules r on r.id = c.rule_id
    join public.deals d on d.organization_id = c.organization_id and d.id = c.deal_id
    join public.patients p on p.organization_id = c.organization_id and p.id = c.patient_id;

  with period as (
    select x.*, s.kind as recall_kind
    from public.recalls x
      left join public.deals rd on rd.organization_id = x.organization_id and rd.id = x.recall_deal_id
      left join public.stages s on s.id = rd.stage_id
    where x.organization_id = org_id
      and (period_from is null or x.created_at >= period_from)
      and (period_to is null or x.created_at < period_to)
  )
  select jsonb_build_object(
      'created', count(*) filter (where status = 'created'),
      'skipped', count(*) filter (where status = 'skipped'),
      'cancelled', count(*) filter (where status = 'cancelled'),
      'open', count(*) filter (where status = 'created' and recall_kind = 'open'),
      'won', count(*) filter (where status = 'created' and recall_kind = 'won'),
      'lost', count(*) filter (where status = 'created' and recall_kind = 'lost'),
      'upcoming', jsonb_array_length(upcoming))
  into totals
  from period;

  select coalesce(jsonb_agg(jsonb_build_object(
      'id', x.id, 'rule_name', r.name, 'patient_id', x.patient_id,
      'patient_name', btrim(concat_ws(' ', p.last_name, p.first_name)),
      'due_at', x.due_at, 'created_at', x.created_at, 'status', x.status, 'reason', x.reason,
      'recall_deal_id', x.recall_deal_id, 'recall_deal_name', rd.name, 'recall_deal_kind', s.kind)
    order by x.created_at desc, x.id desc), '[]'::jsonb)
  into handled
  from (
    select * from public.recalls y
    where y.organization_id = org_id
      and (period_from is null or y.created_at >= period_from)
      and (period_to is null or y.created_at < period_to)
    order by y.created_at desc, y.id desc
    limit 200
  ) x
    left join public.recall_rules r on r.organization_id = x.organization_id and r.id = x.rule_id
    left join public.patients p on p.organization_id = x.organization_id and p.id = x.patient_id
    left join public.deals rd on rd.organization_id = x.organization_id and rd.id = x.recall_deal_id
    left join public.stages s on s.id = rd.stage_id;

  return jsonb_build_object('upcoming', upcoming, 'recalls', handled, 'totals', totals);
end;
$$;

-- Called every minute by pg_cron: starts the edge function mailings_dispatch
-- when something is due. Same Vault secrets as the automatic messages:
-- project_url and automessages_dispatch_key.
CREATE OR REPLACE FUNCTION "private"."request_mailings_dispatch"() RETURNS bigint
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  project_url text;
  dispatch_key text;
begin
  if not exists (
    select 1 from public.mailing_messages mm
    where (mm.status = 'pending' and mm.send_at <= now())
      or (mm.status = 'sending' and mm.claimed_at < now() - interval '10 minutes')
  ) then
    return null;
  end if;
  if to_regclass('vault.decrypted_secrets') is null then
    return null;
  end if;
  execute 'select decrypted_secret from vault.decrypted_secrets where name = $1'
    into project_url using 'project_url';
  execute 'select decrypted_secret from vault.decrypted_secrets where name = $1'
    into dispatch_key using 'automessages_dispatch_key';
  if project_url is null or dispatch_key is null then
    raise warning 'mailings: Vault secrets project_url and automessages_dispatch_key are not set';
    return null;
  end if;
  return net.http_post(
    url := rtrim(project_url, '/') || '/functions/v1/mailings_dispatch',
    body := '{}'::jsonb,
    params := '{}'::jsonb,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || dispatch_key
    ),
    timeout_milliseconds := 5000
  );
end;
$$;

--
-- Triggers
--

create or replace trigger owner_created_repeat_mailings
    after insert on public.sales
    for each row
    when (new.role = 'owner')
    execute function private.handle_owner_created();

create or replace trigger mailing_created
    after insert on public.mailings
    for each row execute function private.handle_mailing_created();

create or replace trigger mailing_update
    before update on public.mailings
    for each row execute function private.handle_mailing_update();

create or replace trigger patient_opt_out
    before insert or update of messaging_opt_out on public.patients
    for each row execute function private.handle_patient_opt_out();

create or replace trigger message_opt_out
    after insert on public.messages
    for each row
    when (new.direction = 'in')
    execute function private.handle_message_opt_out();

create or replace trigger message_mailing_sent
    after insert on public.messages
    for each row
    when (new.mailing_message_id is not null)
    execute function private.handle_mailing_message_sent();

create or replace trigger deal_do_not_disturb
    after insert or update of stage_id, lost_reason_id on public.deals
    for each row execute function private.handle_deal_do_not_disturb();

--
-- Row Level Security
--

alter table public.recall_rules enable row level security;
alter table public.recalls enable row level security;
alter table public.mailing_settings enable row level security;
alter table public.mailings enable row level security;
alter table public.mailing_messages enable row level security;

-- Recall rules and limits are settings (owner and head); mailings, their
-- queue and the recalls are for the owner and the head only
create policy "Organization members can read" on public.recall_rules for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Owner and head can insert" on public.recall_rules for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can update" on public.recall_rules for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head can delete" on public.recall_rules for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can read" on public.recalls for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Organization members can read" on public.mailing_settings for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Owner and head can insert" on public.mailing_settings for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can update" on public.mailing_settings for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head can read" on public.mailings for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can insert" on public.mailings for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can update" on public.mailings for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head can read" on public.mailing_messages for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

--
-- Grants
--

grant all on table public.recall_rules to anon;
grant all on table public.recall_rules to authenticated;
grant all on table public.recall_rules to service_role;
grant all on sequence public.recall_rules_id_seq to anon, authenticated, service_role;

revoke all on table public.recalls from anon, authenticated;
grant select on table public.recalls to authenticated;
grant all on table public.recalls to service_role;
revoke all on sequence public.recalls_id_seq from anon, authenticated;
grant all on sequence public.recalls_id_seq to service_role;

revoke all on table public.mailing_settings from anon, authenticated;
grant select, insert, update on table public.mailing_settings to authenticated;
grant all on table public.mailing_settings to service_role;

-- Mailings are created with a segment and a text, then only renamed,
-- paused, resumed or cancelled; the queue is written by the system
revoke all on table public.mailings from anon, authenticated;
grant select on table public.mailings to authenticated;
grant insert (name, segment, template_id, body, scheduled_at) on table public.mailings to authenticated;
grant update (name, status) on table public.mailings to authenticated;
grant all on table public.mailings to service_role;
revoke all on sequence public.mailings_id_seq from anon, authenticated;
grant usage on sequence public.mailings_id_seq to authenticated;
grant all on sequence public.mailings_id_seq to service_role;

revoke all on table public.mailing_messages from anon, authenticated;
grant select on table public.mailing_messages to authenticated;
grant all on table public.mailing_messages to service_role;
revoke all on sequence public.mailing_messages_id_seq from anon, authenticated;
grant all on sequence public.mailing_messages_id_seq to service_role;

revoke all on table public.mailings_summary from anon, authenticated;
grant select on table public.mailings_summary to authenticated;
grant all on table public.mailings_summary to service_role;

revoke all on function public.mailing_segment_preview(jsonb, integer) from public, anon;
grant execute on function public.mailing_segment_preview(jsonb, integer) to authenticated, service_role;
revoke all on function public.report_recalls(timestamp with time zone, timestamp with time zone) from public, anon;
grant execute on function public.report_recalls(timestamp with time zone, timestamp with time zone) to authenticated, service_role;
revoke all on function public.claim_mailing_messages(integer) from public, anon, authenticated;
grant execute on function public.claim_mailing_messages(integer) to service_role;
revoke all on function public.update_mailing_message_status(text, text, text, text) from public, anon, authenticated;
grant execute on function public.update_mailing_message_status(text, text, text, text) to service_role;
-- Definer helpers of the triggers, the daily job and the dispatcher
revoke all on function private.repeat_source_id(bigint) from public, anon, authenticated;
revoke all on function private.seed_repeat_mailings(bigint) from public, anon, authenticated;
revoke all on function private.recall_candidates(bigint, timestamp with time zone, timestamp with time zone) from public, anon, authenticated;
revoke all on function private.process_recalls(timestamp with time zone) from public, anon, authenticated;
revoke all on function private.mailing_segment(bigint, jsonb, timestamp with time zone) from public, anon, authenticated;
revoke all on function private.request_mailings_dispatch() from public, anon, authenticated;
revoke all on function private.mailing_allowance(bigint, timestamp with time zone) from public, anon, authenticated;
grant execute on function private.mailing_allowance(bigint, timestamp with time zone) to service_role;
revoke all on function private.mailing_patient_vars(bigint, bigint) from public, anon, authenticated;
grant execute on function private.mailing_patient_vars(bigint, bigint) to service_role;
revoke all on function private.handle_owner_created() from public, anon, authenticated;
revoke all on function private.handle_mailing_created() from public, anon, authenticated;
revoke all on function private.cancel_mailing_messages(bigint, bigint) from public, anon;
grant execute on function private.cancel_mailing_messages(bigint, bigint) to authenticated, service_role;
revoke all on function private.handle_patient_opt_out() from public, anon, authenticated;
revoke all on function private.handle_message_opt_out() from public, anon, authenticated;
revoke all on function private.handle_deal_do_not_disturb() from public, anon, authenticated;
revoke all on function private.handle_mailing_message_sent() from public, anon, authenticated;

--
-- Changed functions (02_functions.sql)
--

CREATE OR REPLACE FUNCTION "private"."handle_message_created"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  -- An automatic message or a mailing (no author) is not an answer of the clinic
  if new.direction = 'out'
    and ((new.automessage_id is null and new.mailing_message_id is null) or new.sales_id is not null) then
    update public.deals d
    set first_response_at = new.sent_at
    where d.organization_id = new.organization_id and d.id = new.deal_id
      and d.first_response_at is null;
    -- "First to answer takes the lead", among the chosen employees
    if new.sales_id is not null then
      update public.deals d
      set sales_id = new.sales_id
      where d.organization_id = new.organization_id and d.id = new.deal_id
        and d.sales_id is null
        and exists (
          select 1 from public.organization_settings s
          where s.organization_id = new.organization_id
            and s.lead_distribution = 'first_response'
            and (cardinality(s.lead_distribution_sales_ids) = 0
              or new.sales_id = any(s.lead_distribution_sales_ids))
        );
    end if;
  end if;
  return null;
end;
$$;

-- Defaults for the existing clinics: limits and the (disabled) recall rule
-- «Профгигиена»
select private.seed_repeat_mailings(o.id) from public.organizations o;

-- The mailing dispatcher runs every minute, the recalls once a day at 03:25
-- UTC (9:25 in Almaty); skipped where pg_cron is not installed, e.g. the SQL
-- tests
do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule('mailings-dispatch', '* * * * *', 'select private.request_mailings_dispatch()');
    perform cron.schedule('recalls-daily', '25 3 * * *', 'select private.process_recalls()');
  end if;
end;
$$;
