--
-- Stage 42: money going out of the cash desk (see
-- supabase/schemas/42_cash_outflows.sql): expenses («Расход») with the
-- categories of a clinic, the payouts of the payroll and the new lab
-- payments linked to their expense, the lab settlement with paid and
-- balance, the plan item doctor copied with a plan, the data of the
-- existing clinics.
--

--
-- The clinic setting
--

-- «Администраторы проводят расходы из кассы»
alter table public.organization_settings add column manager_cash_expenses boolean not null default false;

--
-- Categories
--

create table public.cash_expense_categories (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    -- System categories: salary, lab, materials, rent, other
    code text,
    is_active boolean not null default true,
    position integer not null default 0,
    created_at timestamp with time zone not null default now(),
    constraint cash_expense_categories_name_not_blank check (btrim(name) <> ''),
    constraint cash_expense_categories_name_length check (char_length(name) <= 100),
    constraint cash_expense_categories_code_check check (code is null or code in ('salary', 'lab', 'materials', 'rent', 'other'))
);

alter table public.cash_expense_categories add constraint cash_expense_categories_organization_id_id_key unique (organization_id, id);
alter table public.cash_expense_categories
    add constraint cash_expense_categories_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
create unique index cash_expense_categories_code_idx on public.cash_expense_categories using btree (organization_id, code) where code is not null;
create unique index cash_expense_categories_name_idx on public.cash_expense_categories using btree (organization_id, lower(name));

--
-- Expenses in the ledger (account_operations of stage 36)
--

drop view public.account_operations_summary;
alter table public.account_operations drop column till_delta;
alter table public.account_operations add column till_delta bigint generated always as (
        case
            when method = 'deposit' or kind = 'correction' then 0
            when kind in ('payment', 'deposit') then amount
            when kind in ('refund', 'expense') then - amount
            else 0
        end) stored;
alter table public.account_operations add column category_id bigint;
alter table public.account_operations alter column patient_id drop not null;
alter table public.account_operations drop constraint account_operations_kind_check;
alter table public.account_operations add constraint account_operations_kind_check
    check (kind in ('payment', 'deposit', 'deposit_payment', 'refund', 'correction', 'expense'));
alter table public.account_operations drop constraint account_operations_kind_rules;
alter table public.account_operations add constraint account_operations_kind_rules check (
        case kind
            when 'payment' then account = 'services' and method <> 'deposit'
            when 'deposit' then account = 'deposit' and method not in ('deposit', 'other')
            when 'deposit_payment' then account = 'services' and method = 'deposit'
            when 'refund' then not (account = 'deposit' and method = 'deposit')
            when 'expense' then account = 'services' and method in ('cash', 'card', 'kaspi_qr', 'kaspi_transfer', 'bank_transfer')
            else method = 'other'
        end);
-- A patient's operation, or an expense: no patient, a category
alter table public.account_operations add constraint account_operations_expense_check
    check ((kind = 'expense') = (patient_id is null) and (kind = 'expense') = (category_id is not null));
alter table public.account_operations
    add constraint account_operations_category_id_fkey foreign key (organization_id, category_id) references public.cash_expense_categories(organization_id, id);
create index account_operations_category_id_idx on public.account_operations using btree (organization_id, category_id) where category_id is not null;

--
-- Links: payouts and lab payments
--

alter table public.payroll_adjustments add column account_operation_id bigint;
alter table public.payroll_adjustments add constraint payroll_adjustments_account_operation_id_key unique (account_operation_id);
alter table public.payroll_adjustments add constraint payroll_adjustments_operation_check check (account_operation_id is null or kind = 'payout');
alter table public.payroll_adjustments
    add constraint payroll_adjustments_account_operation_id_fkey foreign key (organization_id, account_operation_id) references public.account_operations(organization_id, id) on delete cascade;

create table public.lab_payments (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    lab_id bigint not null,
    -- The month of the settlement it pays (its first day)
    month date not null,
    amount bigint not null,
    method text not null default 'bank_transfer',
    paid_at timestamp with time zone not null default now(),
    comment text,
    -- The expense of the cash desk («из кассы»)
    account_operation_id bigint,
    created_by bigint default private.current_sales_id(),
    created_at timestamp with time zone not null default now(),
    constraint lab_payments_month_check check (extract(day from month) = 1),
    constraint lab_payments_amount_check check (amount > 0 and amount <= 1000000000),
    constraint lab_payments_method_check check (method in ('cash', 'card', 'kaspi_qr', 'kaspi_transfer', 'bank_transfer', 'other')),
    constraint lab_payments_comment_length check (comment is null or char_length(comment) <= 1000)
);

alter table public.lab_payments add constraint lab_payments_organization_id_id_key unique (organization_id, id);
alter table public.lab_payments add constraint lab_payments_account_operation_id_key unique (account_operation_id);
alter table public.lab_payments
    add constraint lab_payments_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.lab_payments
    add constraint lab_payments_lab_id_fkey foreign key (organization_id, lab_id) references public.labs(organization_id, id);
alter table public.lab_payments
    add constraint lab_payments_account_operation_id_fkey foreign key (organization_id, account_operation_id) references public.account_operations(organization_id, id) on delete cascade;
alter table public.lab_payments
    add constraint lab_payments_created_by_fkey foreign key (organization_id, created_by) references public.sales(organization_id, id) on delete set null (created_by);
create index lab_payments_month_idx on public.lab_payments using btree (organization_id, month);

--
-- Functions
--

-- The categories of a new clinic
CREATE OR REPLACE FUNCTION "private"."seed_cash_expense_categories"("org_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  insert into public.cash_expense_categories (organization_id, name, code, position)
  select org_id, c.name, c.code, c.position
  from (values
    ('Зарплата', 'salary', 0),
    ('Лаборатория', 'lab', 1),
    ('Материалы', 'materials', 2),
    ('Аренда', 'rent', 3),
    ('Прочее', 'other', 4)
  ) as c(name, code, position)
  where not exists (
    select 1 from public.cash_expense_categories e
    where e.organization_id = org_id and (e.code = c.code or lower(e.name) = lower(c.name)));
end;
$$;

CREATE OR REPLACE FUNCTION "private"."handle_organization_cash_expense_categories"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  perform private.seed_cash_expense_categories(new.id);
  return new;
end;
$$;

-- The category of a system code in a clinic
CREATE OR REPLACE FUNCTION "private"."cash_expense_category_id"("org_id" bigint, "category_code" "text") RETURNS bigint
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  return (select c.id from public.cash_expense_categories c where c.organization_id = org_id and c.code = category_code);
end;
$$;

-- Who records expenses: the owner and the head; an administrator when the
-- clinic allows it
CREATE OR REPLACE FUNCTION "private"."can_record_expense"() RETURNS boolean
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  role text := private.current_user_role();
begin
  if role in ('owner', 'head') then
    return true;
  end if;
  if role = 'manager' then
    return coalesce((
      select s.manager_cash_expenses from public.organization_settings s
      where s.organization_id = private.current_organization_id()), false);
  end if;
  return false;
end;
$$;

-- A system category keeps its code and is not deleted
CREATE OR REPLACE FUNCTION "private"."handle_cash_expense_category_before_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if tg_op = 'DELETE' then
    if old.code is not null and pg_trigger_depth() = 1
      and exists (select 1 from public.organizations o where o.id = old.organization_id) then
      raise exception 'Системную статью расхода нельзя удалить — только переименовать или убрать в архив'
        using errcode = '22023', hint = 'expense_category_system';
    end if;
    return old;
  end if;
  if tg_op = 'INSERT' then
    if pg_trigger_depth() = 1 and private.current_user_role() is not null then
      new.code := null;
    end if;
  elsif new.code is distinct from old.code then
    raise exception 'Код системной статьи не меняется' using errcode = '22023', hint = 'expense_category_system';
  end if;
  new.name := btrim(new.name);
  return new;
end;
$$;

-- Before an operation is written (after the checks of stage 36): an
-- expense has no patient, deal, plan or visit, a category of the clinic, a
-- real method and a writer allowed to spend
CREATE OR REPLACE FUNCTION "private"."handle_account_operation_expense"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  sync text := coalesce(current_setting('crm.ledger_sync', true), '');
  category public.cash_expense_categories;
begin
  if new.kind <> 'expense' then
    if new.category_id is not null then
      raise exception 'Статья расхода указывается только у расхода' using errcode = '22023', hint = 'expense_category';
    end if;
    return new;
  end if;
  if tg_op = 'INSERT' then
    if new.patient_id is not null or new.deal_id is not null or new.plan_id is not null or new.visit_id is not null
      or cardinality(new.plan_item_ids) > 0 then
      raise exception 'Расход не связан с пациентом, сделкой или визитом' using errcode = '22023', hint = 'expense_patient';
    end if;
    if sync = '' and private.current_user_role() is not null and not private.can_record_expense() then
      raise exception 'Расходы из кассы проводят владелец и руководитель' using errcode = '42501', hint = 'expense_forbidden';
    end if;
    new.account := 'services';
    new.prepayment := false;
    new.cash_received := null;
  end if;
  if new.method not in ('cash', 'card', 'kaspi_qr', 'kaspi_transfer', 'bank_transfer') then
    raise exception 'Расход проводится наличными, картой, Kaspi или переводом' using errcode = '22023', hint = 'expense_method';
  end if;
  select * into category from public.cash_expense_categories c
  where c.organization_id = new.organization_id and c.id = new.category_id;
  if not found then
    raise exception 'Укажите статью расхода' using errcode = '22023', hint = 'expense_category';
  end if;
  if tg_op = 'UPDATE' and new.category_id is distinct from old.category_id then
    if exists (select 1 from public.payroll_adjustments a where a.account_operation_id = new.id)
      or exists (select 1 from public.lab_payments l where l.account_operation_id = new.id) then
      raise exception 'Это выплата зарплаты или оплата лаборатории: статья не меняется' using errcode = '22023', hint = 'expense_linked';
    end if;
  end if;
  if (tg_op = 'INSERT' or new.category_id is distinct from old.category_id) and not category.is_active then
    raise exception 'Статья расхода в архиве' using errcode = '22023', hint = 'expense_category_archived';
  end if;
  return new;
end;
$$;

-- The method and the time of an expense changed in the cash desk: its
-- payout or lab payment follows
CREATE OR REPLACE FUNCTION "private"."handle_expense_link_sync"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  perform set_config('crm.cash_link', 'on', true);
  update public.payroll_adjustments a
  set occurred_on = private.clinic_date(new.organization_id, new.occurred_at)
  where a.organization_id = new.organization_id and a.account_operation_id = new.id
    and a.occurred_on is distinct from private.clinic_date(new.organization_id, new.occurred_at);
  update public.lab_payments l
  set method = new.method, paid_at = new.occurred_at
  where l.organization_id = new.organization_id and l.account_operation_id = new.id
    and (l.method <> new.method or l.paid_at <> new.occurred_at);
  perform set_config('crm.cash_link', '', true);
  return null;
end;
$$;

-- A payout given from the cash desk: its operation is an expense of the
-- category Зарплата with the same amount; the link, the amount and the day
-- are the operation's
CREATE OR REPLACE FUNCTION "private"."handle_payroll_adjustment_cash_link"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  op public.account_operations;
begin
  if tg_op = 'UPDATE' then
    if new.account_operation_id is distinct from old.account_operation_id then
      raise exception 'Связь выплаты с кассой не меняется' using errcode = '22023', hint = 'cash_linked';
    end if;
    if old.account_operation_id is not null and coalesce(current_setting('crm.cash_link', true), '') <> 'on'
      and (new.amount <> old.amount or new.occurred_on <> old.occurred_on or new.kind <> old.kind) then
      raise exception 'Выплата проведена через кассу: сумму и дату меняют в кассе или отменяют выплату'
        using errcode = '22023', hint = 'cash_linked';
    end if;
    return new;
  end if;
  if new.account_operation_id is null then
    return new;
  end if;
  select * into op from public.account_operations o
  where o.organization_id = new.organization_id and o.id = new.account_operation_id;
  if not found or op.kind <> 'expense' or op.amount <> new.amount
    or op.category_id is distinct from private.cash_expense_category_id(new.organization_id, 'salary')
    or exists (select 1 from public.lab_payments l where l.account_operation_id = op.id) then
    raise exception 'Выплату связывают с расходом «Зарплата» той же суммы' using errcode = '22023', hint = 'cash_link_invalid';
  end if;
  new.occurred_on := private.clinic_date(new.organization_id, op.occurred_at);
  return new;
end;
$$;

-- A lab payment: the month is its first day; from the cash desk — the
-- expense of the category Лаборатория with the same amount gives the method
-- and the moment
CREATE OR REPLACE FUNCTION "private"."handle_lab_payment_before_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  op public.account_operations;
begin
  new.month := date_trunc('month', new.month)::date;
  new.comment := nullif(btrim(new.comment), '');
  if tg_op = 'UPDATE' then
    if new.account_operation_id is distinct from old.account_operation_id then
      raise exception 'Связь оплаты с кассой не меняется' using errcode = '22023', hint = 'cash_linked';
    end if;
    if new.lab_id <> old.lab_id and exists (select 1 from public.labs l where l.organization_id = new.organization_id and l.id = old.lab_id) then
      raise exception 'Оплату нельзя перенести в другую лабораторию' using errcode = '22023', hint = 'lab_payment_lab';
    end if;
    if old.account_operation_id is not null and coalesce(current_setting('crm.cash_link', true), '') <> 'on'
      and (new.amount <> old.amount or new.method <> old.method or new.paid_at <> old.paid_at) then
      raise exception 'Оплата проведена через кассу: сумму, способ и время меняют в кассе или отменяют оплату'
        using errcode = '22023', hint = 'cash_linked';
    end if;
    return new;
  end if;
  if pg_trigger_depth() = 1 and private.current_user_role() is not null then
    new.created_by := private.current_sales_id();
    new.created_at := now();
  end if;
  if new.account_operation_id is not null then
    select * into op from public.account_operations o
    where o.organization_id = new.organization_id and o.id = new.account_operation_id;
    if not found or op.kind <> 'expense' or op.amount <> new.amount
      or op.category_id is distinct from private.cash_expense_category_id(new.organization_id, 'lab')
      or exists (select 1 from public.payroll_adjustments a where a.account_operation_id = op.id) then
      raise exception 'Оплату лаборатории связывают с расходом «Лаборатория» той же суммы' using errcode = '22023', hint = 'cash_link_invalid';
    end if;
    new.method := op.method;
    new.paid_at := op.occurred_at;
  end if;
  return new;
end;
$$;

-- A payout or a lab payment deleted by an employee cancels its operation
-- (a cascade — the clinic, the doctor, the operation itself — does not)
CREATE OR REPLACE FUNCTION "private"."handle_cash_link_deleted"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if old.account_operation_id is not null and pg_trigger_depth() = 1 then
    delete from public.account_operations o
    where o.organization_id = old.organization_id and o.id = old.account_operation_id;
  end if;
  return null;
end;
$$;

-- The moment of a day-only date: now when it is today in the clinic, else
-- noon of that day
CREATE OR REPLACE FUNCTION "private"."cash_moment"("org_id" bigint, "day" "date") RETURNS timestamp with time zone
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if day is null then
    return now();
  end if;
  return private.payment_moment(org_id, day, now());
end;
$$;

-- «Выплата» of the payroll; «Выдать из кассы» (from_cash) writes the
-- expense Зарплата first (a cash payout needs the open shift of the
-- cashier). The owner and the head; a closed month still takes payouts.
CREATE OR REPLACE FUNCTION "public"."record_payroll_payout"("target_doctor_id" bigint, "target_sales_id" bigint, "target_month" "date", "payout_amount" bigint, "payout_day" "date" DEFAULT NULL::"date", "payout_note" "text" DEFAULT NULL::"text", "from_cash" boolean DEFAULT false, "payout_method" "text" DEFAULT 'cash'::"text") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  person text;
  op_id bigint;
  adjustment_id bigint;
  moment timestamp with time zone;
begin
  perform private.payroll_check_access();
  if target_month is null or payout_amount is null or payout_amount <= 0 then
    raise exception 'Укажите месяц и сумму выплаты' using errcode = '22023';
  end if;
  if num_nonnulls(target_doctor_id, target_sales_id) <> 1 then
    raise exception 'Укажите врача или сотрудника' using errcode = '22023';
  end if;
  if target_doctor_id is not null then
    select d.name into person from public.doctors d where d.organization_id = org_id and d.id = target_doctor_id;
  else
    select btrim(concat_ws(' ', s.first_name, s.last_name)) into person
    from public.sales s where s.organization_id = org_id and s.id = target_sales_id;
  end if;
  if person is null then
    raise exception 'Сотрудник не найден' using errcode = 'P0002';
  end if;
  moment := private.cash_moment(org_id, payout_day);
  if from_cash then
    if coalesce(payout_method, 'cash') = 'cash' and not exists (
      select 1 from public.cash_shifts s
      where s.organization_id = org_id and s.sales_id = private.current_sales_id() and s.closed_at is null) then
      raise exception 'Откройте смену кассы, чтобы выдать наличные' using errcode = '22023', hint = 'shift_required';
    end if;
    insert into public.account_operations (organization_id, kind, amount, method, occurred_at, category_id, comment)
    values (org_id, 'expense', payout_amount, coalesce(payout_method, 'cash'), moment,
      private.cash_expense_category_id(org_id, 'salary'),
      left(concat_ws(' — ', 'Зарплата: ' || person || ', ' || to_char(date_trunc('month', target_month), 'MM.YYYY'),
        nullif(btrim(payout_note), '')), 1000))
    returning id into op_id;
  end if;
  insert into public.payroll_adjustments (organization_id, doctor_id, sales_id, month, kind, amount, note, occurred_on,
    account_operation_id)
  values (org_id, target_doctor_id, target_sales_id, date_trunc('month', target_month)::date, 'payout', payout_amount,
    nullif(btrim(payout_note), ''), coalesce(payout_day, private.clinic_date(org_id, now())), op_id)
  returning id into adjustment_id;
  return jsonb_build_object('adjustment_id', adjustment_id, 'operation_id', op_id);
end;
$$;

-- «Оплатить» a lab for a month; from_cash writes the expense Лаборатория
-- first (cash needs the open shift of the cashier). The owner and the head.
CREATE OR REPLACE FUNCTION "public"."record_lab_payment"("target_lab_id" bigint, "target_month" "date", "payment_amount" bigint, "payment_method" "text" DEFAULT 'bank_transfer'::"text", "payment_day" "date" DEFAULT NULL::"date", "payment_comment" "text" DEFAULT NULL::"text", "from_cash" boolean DEFAULT false) RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  lab_name text;
  op_id bigint;
  payment_id bigint;
  moment timestamp with time zone;
begin
  if org_id is null or coalesce(private.current_user_role() in ('owner', 'head'), false) is false then
    raise exception 'Оплату лаборатории проводят владелец и руководитель' using errcode = '42501', hint = 'lab_payment_forbidden';
  end if;
  if target_month is null or payment_amount is null or payment_amount <= 0 then
    raise exception 'Укажите месяц и сумму оплаты' using errcode = '22023';
  end if;
  select l.name into lab_name from public.labs l where l.organization_id = org_id and l.id = target_lab_id;
  if lab_name is null then
    raise exception 'Лаборатория не найдена' using errcode = 'P0002';
  end if;
  moment := private.cash_moment(org_id, payment_day);
  if from_cash then
    if coalesce(payment_method, 'cash') = 'cash' and not exists (
      select 1 from public.cash_shifts s
      where s.organization_id = org_id and s.sales_id = private.current_sales_id() and s.closed_at is null) then
      raise exception 'Откройте смену кассы, чтобы выдать наличные' using errcode = '22023', hint = 'shift_required';
    end if;
    insert into public.account_operations (organization_id, kind, amount, method, occurred_at, category_id, comment)
    values (org_id, 'expense', payment_amount, coalesce(payment_method, 'cash'), moment,
      private.cash_expense_category_id(org_id, 'lab'),
      left(concat_ws(' — ', 'Лаборатория: ' || lab_name || ', ' || to_char(date_trunc('month', target_month), 'MM.YYYY'),
        nullif(btrim(payment_comment), '')), 1000))
    returning id into op_id;
  end if;
  insert into public.lab_payments (organization_id, lab_id, month, amount, method, paid_at, comment, account_operation_id)
  values (org_id, target_lab_id, target_month, payment_amount, coalesce(payment_method, 'bank_transfer'), moment,
    payment_comment, op_id)
  returning id into payment_id;
  return jsonb_build_object('payment_id', payment_id, 'operation_id', op_id);
end;
$$;

-- Reports «Деньги» → «Расходы по статьям»: the expenses of the period by
-- category (the ledger), with the branch filter
CREATE OR REPLACE FUNCTION "public"."report_cash_expenses"("period_from" timestamp with time zone DEFAULT NULL::timestamp with time zone, "period_to" timestamp with time zone DEFAULT NULL::timestamp with time zone, "filter_branch_id" bigint DEFAULT NULL::bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $$
begin
  perform private.report_check_access();
  return coalesce((
    select jsonb_agg(jsonb_build_object('category_id', r.category_id, 'name', r.name, 'code', r.code,
      'amount', r.amount, 'cash', r.cash, 'operations', r.operations) order by r.amount desc, r.name)
    from (
      select c.id as category_id, c.name, c.code,
        sum(o.amount)::bigint as amount,
        sum(private.operation_method_amount(o.method, o.parts, o.amount, 'cash'))::bigint as cash,
        count(*)::integer as operations
      from public.account_operations o
        join public.cash_expense_categories c on c.organization_id = o.organization_id and c.id = o.category_id
      where o.organization_id = private.current_organization_id()
        and o.kind = 'expense'
        and (period_from is null or o.occurred_at >= period_from)
        and (period_to is null or o.occurred_at < period_to)
        and (filter_branch_id is null or o.branch_id = filter_branch_id)
      group by c.id, c.name, c.code
    ) r
  ), '[]'::jsonb);
end;
$$;

--
-- Views
--

-- Operations with the names the lists need (patient card, cash desk); an
-- expense has no patient but a category
create or replace view public.account_operations_summary with (security_invoker = on) as
select
    o.id,
    o.organization_id,
    o.patient_id,
    o.kind,
    o.account,
    o.amount,
    o.method,
    o.parts,
    o.cash_received,
    o.prepayment,
    o.occurred_at,
    o.sales_id,
    o.branch_id,
    o.shift_id,
    o.deal_id,
    o.plan_id,
    o.plan_item_ids,
    o.visit_id,
    o.comment,
    o.source,
    o.deal_payment_id,
    o.created_at,
    o.deposit_delta,
    o.paid_delta,
    o.till_delta,
    nullif(btrim(concat_ws(' ', p.last_name, p.first_name, p.middle_name)), '') as patient_name,
    p.phones[1] as patient_phone,
    nullif(btrim(concat_ws(' ', s.first_name, s.last_name)), '') as cashier_name,
    d.name as deal_name,
    tp.name as plan_name,
    b.name as branch_name,
    o.category_id,
    c.name as category_name,
    c.code as category_code,
    pa.id as payroll_adjustment_id,
    lp.id as lab_payment_id
from public.account_operations o
    left join public.patients p on p.organization_id = o.organization_id and p.id = o.patient_id
    left join public.sales s on s.organization_id = o.organization_id and s.id = o.sales_id
    left join public.deals d on d.organization_id = o.organization_id and d.id = o.deal_id
    left join public.treatment_plans tp on tp.organization_id = o.organization_id and tp.id = o.plan_id
    left join public.branches b on b.organization_id = o.organization_id and b.id = o.branch_id
    left join public.cash_expense_categories c on c.organization_id = o.organization_id and c.id = o.category_id
    left join public.payroll_adjustments pa on pa.organization_id = o.organization_id and pa.account_operation_id = o.id
    left join public.lab_payments lp on lp.organization_id = o.organization_id and lp.account_operation_id = o.id;

-- Lab payments with the names
create or replace view public.lab_payments_summary with (security_invoker = on) as
select
    l.id,
    l.organization_id,
    l.lab_id,
    l.month,
    l.amount,
    l.method,
    l.paid_at,
    l.comment,
    l.account_operation_id,
    l.created_by,
    l.created_at,
    lb.name as lab_name,
    nullif(btrim(concat_ws(' ', s.first_name, s.last_name)), '') as created_by_name
from public.lab_payments l
    join public.labs lb on lb.organization_id = l.organization_id and lb.id = l.lab_id
    left join public.sales s on s.organization_id = l.organization_id and s.id = l.created_by;

--
-- Triggers
--

create or replace trigger seed_cash_expense_categories
    after insert on public.organizations
    for each row execute function private.handle_organization_cash_expense_categories();

create or replace trigger cash_expense_category_before_write
    before insert or update or delete on public.cash_expense_categories
    for each row execute function private.handle_cash_expense_category_before_write();

-- Fires after account_operation_before_write (stage 36), alphabetically
create or replace trigger account_operation_expense
    before insert or update on public.account_operations
    for each row execute function private.handle_account_operation_expense();

create or replace trigger account_operation_expense_link_sync
    after update of method, occurred_at on public.account_operations
    for each row
    when (new.kind = 'expense' and (new.method <> old.method or new.occurred_at <> old.occurred_at))
    execute function private.handle_expense_link_sync();

create or replace trigger payroll_adjustment_cash_link
    before insert or update on public.payroll_adjustments
    for each row execute function private.handle_payroll_adjustment_cash_link();

create or replace trigger payroll_adjustment_cash_link_deleted
    after delete on public.payroll_adjustments
    for each row execute function private.handle_cash_link_deleted();

create or replace trigger lab_payment_before_write
    before insert or update on public.lab_payments
    for each row execute function private.handle_lab_payment_before_write();

create or replace trigger lab_payment_deleted
    after delete on public.lab_payments
    for each row execute function private.handle_cash_link_deleted();

create or replace trigger audit_cash_expense_category
    after insert or update or delete on public.cash_expense_categories
    for each row when (pg_trigger_depth() = 0) execute function private.audit_row('cash_expense_category', 'name,is_active');

create or replace trigger audit_lab_payment
    after insert or update or delete on public.lab_payments
    for each row execute function private.audit_row('lab_payment', 'lab_id,month,amount,method,paid_at,comment,account_operation_id');

--
-- Row Level Security
--

alter table public.cash_expense_categories enable row level security;
alter table public.lab_payments enable row level security;

create policy "Staff read expense categories" on public.cash_expense_categories for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head', 'manager'));
create policy "Owner and head add expense categories" on public.cash_expense_categories for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head change expense categories" on public.cash_expense_categories for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head delete expense categories" on public.cash_expense_categories for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

-- Expenses (no patient): owner and head, an administrator with the reports
-- right, the administrator who recorded them
create policy "Staff read cash expenses" on public.account_operations for select to authenticated
    using (organization_id = (select private.current_organization_id()) and patient_id is null
        and ((select private.current_user_role()) in ('owner', 'head')
            or ((select private.current_user_role()) = 'manager'
                and (sales_id = (select private.current_sales_id()) or (select private.access_scope('reports', 'view')) = 'all'))));
create policy "Allowed staff record expenses" on public.account_operations for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and patient_id is null and kind = 'expense'
        and (select private.can_record_expense()));

create policy "Owner and head read lab payments" on public.lab_payments for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head add lab payments" on public.lab_payments for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head change lab payments" on public.lab_payments for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head delete lab payments" on public.lab_payments for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

--
-- Grants
--

-- The category of an expense changes too
grant update (category_id) on table public.account_operations to authenticated;

revoke all on table public.account_operations_summary from anon;
grant select on table public.account_operations_summary to authenticated;
grant all on table public.account_operations_summary to service_role;

revoke all on table public.cash_expense_categories from anon;
grant select, insert, delete on table public.cash_expense_categories to authenticated;
grant update (name, is_active, position) on table public.cash_expense_categories to authenticated;
grant all on table public.cash_expense_categories to service_role;
revoke all on sequence public.cash_expense_categories_id_seq from anon;
grant usage on sequence public.cash_expense_categories_id_seq to authenticated;
grant all on sequence public.cash_expense_categories_id_seq to service_role;

revoke all on table public.lab_payments from anon;
grant select, insert, delete on table public.lab_payments to authenticated;
grant update (lab_id, month, amount, method, paid_at, comment) on table public.lab_payments to authenticated;
grant all on table public.lab_payments to service_role;
revoke all on sequence public.lab_payments_id_seq from anon;
grant usage on sequence public.lab_payments_id_seq to authenticated;
grant all on sequence public.lab_payments_id_seq to service_role;

revoke all on table public.lab_payments_summary from anon;
grant select on table public.lab_payments_summary to authenticated;
grant all on table public.lab_payments_summary to service_role;

revoke all on function private.seed_cash_expense_categories(bigint) from public;
grant execute on function private.seed_cash_expense_categories(bigint) to service_role;
revoke all on function private.handle_organization_cash_expense_categories() from public;
revoke all on function private.cash_expense_category_id(bigint, text) from public;
grant execute on function private.cash_expense_category_id(bigint, text) to service_role;
revoke all on function private.can_record_expense() from public;
grant execute on function private.can_record_expense() to authenticated, service_role;
revoke all on function private.handle_cash_expense_category_before_write() from public;
revoke all on function private.handle_account_operation_expense() from public;
revoke all on function private.handle_expense_link_sync() from public;
revoke all on function private.handle_payroll_adjustment_cash_link() from public;
revoke all on function private.handle_lab_payment_before_write() from public;
revoke all on function private.handle_cash_link_deleted() from public;
revoke all on function private.cash_moment(bigint, date) from public;
grant execute on function private.cash_moment(bigint, date) to authenticated, service_role;

revoke all on function public.record_payroll_payout(bigint, bigint, date, bigint, date, text, boolean, text) from public, anon;
grant execute on function public.record_payroll_payout(bigint, bigint, date, bigint, date, text, boolean, text) to authenticated, service_role;
revoke all on function public.record_lab_payment(bigint, date, bigint, text, date, text, boolean) from public, anon;
grant execute on function public.record_lab_payment(bigint, date, bigint, text, date, text, boolean) to authenticated, service_role;
revoke all on function public.report_cash_expenses(timestamp with time zone, timestamp with time zone, bigint) from public, anon;
grant execute on function public.report_cash_expenses(timestamp with time zone, timestamp with time zone, bigint) to authenticated, service_role;

--
-- Changed definitions of earlier stages
--

-- 36_payments.sql: the expenses apart in the report by method; the category
-- in the audit log of an operation
CREATE OR REPLACE FUNCTION "public"."report_cash_methods"("period_from" timestamp with time zone DEFAULT NULL::timestamp with time zone, "period_to" timestamp with time zone DEFAULT NULL::timestamp with time zone, "filter_branch_id" bigint DEFAULT NULL::bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $$
begin
  perform private.report_check_access();
  return coalesce((
    select jsonb_agg(jsonb_build_object('method', r.method, 'income', r.income, 'refunds', r.refunds,
      'expenses', r.expenses, 'net', r.income - r.refunds - r.expenses, 'operations', r.operations)
      order by r.income - r.refunds - r.expenses desc, r.method)
    from (
      select m.method,
        coalesce(sum(m.amount) filter (where m.sign > 0), 0)::bigint as income,
        coalesce(sum(m.amount) filter (where m.sign < 0 and m.kind <> 'expense'), 0)::bigint as refunds,
        coalesce(sum(m.amount) filter (where m.kind = 'expense'), 0)::bigint as expenses,
        count(distinct m.id) as operations
      from (
        select o.id, o.kind, sign(o.till_delta) as sign, x.method, x.amount
        from public.account_operations o
          cross join lateral (
            select p ->> 'method' as method, (p ->> 'amount')::bigint as amount
            from jsonb_array_elements(case when o.method = 'mixed' then o.parts else '[]'::jsonb end) as p
            union all
            select o.method, o.amount where o.method <> 'mixed'
          ) x
        where o.organization_id = private.current_organization_id()
          and o.till_delta <> 0
          and (period_from is null or o.occurred_at >= period_from)
          and (period_to is null or o.occurred_at < period_to)
          and (filter_branch_id is null or o.branch_id = filter_branch_id)
      ) m
      group by m.method
    ) r
  ), '[]'::jsonb);
end;
$$;

create or replace trigger audit_account_operation
    after insert or update or delete on public.account_operations
    for each row
    when (coalesce(current_setting('crm.ledger_sync', true), '') not in ('deal', 'system'))
    execute function private.audit_row('account_operation', 'kind,account,amount,method,parts,occurred_at,comment,deal_id,plan_id,visit_id,shift_id,category_id');

-- 40_lab_orders.sql: the settlement with paid and balance (new columns)
drop function public.report_lab_settlement(date);
CREATE OR REPLACE FUNCTION "public"."report_lab_settlement"("in_month" "date") RETURNS TABLE("lab_id" bigint, "lab_name" "text", "is_own" boolean, "orders_count" integer, "items_count" integer, "amount" bigint, "paid" bigint, "balance" bigint, "total_balance" bigint)
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
#variable_conflict use_column
declare
  org_id bigint := private.current_organization_id();
  month_start date := date_trunc('month', in_month)::date;
  month_end date := (date_trunc('month', in_month) + interval '1 month')::date;
begin
  if org_id is null or private.current_user_role() not in ('owner', 'head') then
    raise exception 'Суммы лабораторий видят владелец и руководитель' using errcode = '42501';
  end if;
  return query
  with owed as (
    select o.lab_id,
      date_trunc('month', o.ready_at)::date as month,
      count(distinct o.id)::integer as orders_count,
      coalesce(sum(i.qty), 0)::integer as items_count,
      coalesce(sum(i.qty::bigint * pr.price), 0)::bigint as amount
    from public.lab_orders o
      left join public.lab_order_items i on i.organization_id = o.organization_id and i.order_id = o.id
      left join public.lab_order_item_prices pr on pr.organization_id = i.organization_id and pr.item_id = i.id
    where o.organization_id = org_id and o.ready_at < month_end
    group by o.lab_id, date_trunc('month', o.ready_at)
  ),
  paid as (
    select p.lab_id, p.month, sum(p.amount)::bigint as amount
    from public.lab_payments p
    where p.organization_id = org_id and p.month < month_end
    group by p.lab_id, p.month
  ),
  per_lab as (
    select l.id, l.name, l.is_own,
      coalesce((select sum(w.orders_count) from owed w where w.lab_id = l.id and w.month = month_start), 0)::integer as orders_count,
      coalesce((select sum(w.items_count) from owed w where w.lab_id = l.id and w.month = month_start), 0)::integer as items_count,
      coalesce((select sum(w.amount) from owed w where w.lab_id = l.id and w.month = month_start), 0)::bigint as amount,
      coalesce((select sum(p.amount) from paid p where p.lab_id = l.id and p.month = month_start), 0)::bigint as paid,
      (coalesce((select sum(w.amount) from owed w where w.lab_id = l.id), 0)
        - coalesce((select sum(p.amount) from paid p where p.lab_id = l.id), 0))::bigint as total_balance
    from public.labs l
    where l.organization_id = org_id
  )
  select x.id, x.name, x.is_own, x.orders_count, x.items_count, x.amount, x.paid, x.amount - x.paid, x.total_balance
  from per_lab x
  where x.orders_count > 0 or x.paid > 0 or x.total_balance <> 0
  order by 6 desc, 2;
end;
$$;

revoke all on function public.report_lab_settlement(date) from public, anon;
grant execute on function public.report_lab_settlement(date) to authenticated, service_role;

-- 29_treatment_plans.sql: a duplicated plan keeps the doctor of its items;
-- the doctor of an item in the audit log
CREATE OR REPLACE FUNCTION "public"."duplicate_treatment_plan"("source_plan_id" bigint) RETURNS bigint
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  source public.treatment_plans;
  stage record;
  new_plan_id bigint;
  new_stage_id bigint;
begin
  select * into source from public.treatment_plans p
  where p.organization_id = private.current_organization_id() and p.id = source_plan_id;
  if not found then
    raise exception 'План не найден' using errcode = 'P0002';
  end if;
  perform set_config('crm.treatment_copy', 'on', true);
  insert into public.treatment_plans (organization_id, deal_id, name, status, discount_percent, discount_amount, note, doctor_id,
    plan_type_id, complaints, insurance_policy)
  values (source.organization_id, source.deal_id, left(source.name, 180) || ' (копия)', 'draft',
    source.discount_percent, source.discount_amount, source.note, source.doctor_id,
    source.plan_type_id, source.complaints, source.insurance_policy)
  returning id into new_plan_id;
  for stage in
    select * from public.treatment_stages s
    where s.organization_id = source.organization_id and s.plan_id = source.id
    order by s.position, s.id
  loop
    insert into public.treatment_stages (organization_id, plan_id, position, name, doctor_id, direction_id, deadline,
      description, status, discount_percent)
    values (stage.organization_id, new_plan_id, stage.position, stage.name, stage.doctor_id, stage.direction_id, stage.deadline,
      stage.description, case when stage.status = 'cancelled' then 'cancelled' else 'new' end, stage.discount_percent)
    returning id into new_stage_id;
    insert into public.treatment_plan_items (organization_id, plan_id, stage_id, service_id, name, tooth, quantity, unit_price, discount_percent, position, doctor_id)
    select i.organization_id, new_plan_id, new_stage_id, i.service_id, i.name, i.tooth, i.quantity, i.unit_price, i.discount_percent, i.position, i.doctor_id
    from public.treatment_plan_items i
    where i.organization_id = source.organization_id and i.stage_id = stage.id
    order by i.position, i.id;
  end loop;
  perform set_config('crm.treatment_copy', '', true);
  return new_plan_id;
end;
$$;

create or replace trigger audit_treatment_plan_item
    after insert or update or delete on public.treatment_plan_items
    for each row execute function private.audit_row('treatment_plan_item', 'name,stage_no,tooth,quantity,unit_price,discount_percent,done,doctor_id');

-- 15_audit.sql: the new clinic setting in the audit log
create or replace trigger audit_settings
    after update on public.organization_settings
    for each row execute function private.audit_row('settings', 'manager_deal_visibility,pipeline_move_mode,lead_distribution,lead_distribution_sales_ids,unsorted_enabled,unsorted_source_ids,manager_cash_expenses');

--
-- Data of the existing clinics
--

-- The categories (a template, not in the audit log)
alter table public.cash_expense_categories disable trigger audit_cash_expense_category;
select private.seed_cash_expense_categories(o.id) from public.organizations o;
alter table public.cash_expense_categories enable trigger audit_cash_expense_category;
