-- Stage 16: employee notifications (bell, browser, Telegram) and response-time
-- control. Everything is declared in supabase/schemas/16_notifications.sql
-- (copied below); the data statements at the end are not schema.

--
-- Employee notifications and response-time control (stage 16)
--
-- Notifications are rows of public.notifications, one per recipient, created
-- by the database only:
--   lead_assigned     a deal became mine (distribution, reassignment by
--                     somebody else); never for my own action
--   patient_message   an inbound message on a deal I lead (unassigned deals:
--                     the "first to answer" list, else the owner and heads);
--                     a burst of messages of one deal updates one unread row
--   task_overdue      my task passed its due date (once per due date)
--   response_overdue  a patient waits for an answer longer than the clinic's
--                     limit (working minutes), once per waiting episode, and
--                     once more to the owner and heads at 3x the limit
-- Bulk writes (imports, migrations) can switch the triggers off for their
-- transaction: set local crm.notifications = 'off'.
-- pg_cron runs private.notifications_tick() every minute (overdue tasks and
-- answers); it starts the edge function notifications_dispatch, which sends
-- the new notifications to the employees who linked their Telegram (one
-- platform bot, NOTIFY_TELEGRAM_BOT_TOKEN). The bell and the browser
-- notifications of the app read the table.
--
-- "Waiting for an answer": the deal is open, and an inbound message came
-- after the last answer of the clinic (an outbound message by an employee or
-- from the phone; automatic messages are not answers). The wait starts at the
-- first such message and only counts the clinic's working hours
-- (organization_settings.response_hours_*, organizations.timezone). The same
-- rules in the app: providers/commons/responseTime.ts.
--

--
-- Settings of the clinic: response limit, working hours, whom to alert
--

alter table public.organization_settings add column response_control_enabled boolean not null default true;
alter table public.organization_settings add column response_limit_minutes integer not null default 15;
alter table public.organization_settings add column response_hours_start integer not null default 9;
alter table public.organization_settings add column response_hours_end integer not null default 21;
-- Alerted when the limit is reached: the responsible (for an unassigned deal:
-- whoever gets its messages), the owner and heads, and chosen employees
alter table public.organization_settings add column response_alert_responsible boolean not null default true;
alter table public.organization_settings add column response_alert_managers boolean not null default true;
alter table public.organization_settings add column response_alert_sales_ids bigint[] not null default '{}'::bigint[];
alter table public.organization_settings add constraint organization_settings_response_limit_check
    check (response_limit_minutes between 1 and 1440);
alter table public.organization_settings add constraint organization_settings_response_hours_check
    check (response_hours_start >= 0 and response_hours_start < response_hours_end and response_hours_end <= 24);

-- A task is notified once per due date (moving the due date resets it)
alter table public.tasks add column overdue_notified_at timestamp with time zone;

--
-- Tables
--

create table public.notifications (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    -- The recipient
    sales_id bigint not null,
    kind text not null,
    title text not null,
    body text,
    deal_id bigint,
    patient_id bigint,
    task_id bigint,
    -- patient_message: messages coalesced in this row
    message_count integer not null default 1,
    created_at timestamp with time zone not null default now(),
    -- Last change (a coalesced message): the bell shows the newest first
    updated_at timestamp with time zone not null default now(),
    read_at timestamp with time zone,
    -- Telegram: null (not handled), sending, sent, skipped (kind switched
    -- off), failed
    telegram_status text,
    telegram_claimed_at timestamp with time zone,
    telegram_sent_at timestamp with time zone,
    constraint notifications_kind_check
        check (kind in ('lead_assigned', 'patient_message', 'task_overdue', 'response_overdue')),
    constraint notifications_telegram_status_check
        check (telegram_status in ('sending', 'sent', 'skipped', 'failed'))
);

-- Preferences of an employee (no row: the defaults). In-app notifications are
-- always on; kinds choose what goes to the browser and to Telegram.
create table public.notification_preferences (
    sales_id bigint primary key,
    organization_id bigint not null,
    kinds text[] not null default array['lead_assigned', 'patient_message', 'task_overdue', 'response_overdue'],
    browser_enabled boolean not null default false,
    telegram_enabled boolean not null default true,
    -- Linked with /start <code> sent to the platform bot
    telegram_chat_id text,
    telegram_username text,
    telegram_linked_at timestamp with time zone,
    telegram_link_code text,
    telegram_link_expires_at timestamp with time zone,
    updated_at timestamp with time zone not null default now(),
    constraint notification_preferences_kinds_check
        check (kinds <@ array['lead_assigned', 'patient_message', 'task_overdue', 'response_overdue'])
);

-- response_overdue already sent: level 1 at the limit, level 2 at 3x the
-- limit, per waiting episode (the first unanswered message)
create table public.response_alerts (
    organization_id bigint not null,
    deal_id bigint not null,
    waiting_since timestamp with time zone not null,
    level integer not null,
    created_at timestamp with time zone not null default now(),
    constraint response_alerts_pkey primary key (organization_id, deal_id, waiting_since, level),
    constraint response_alerts_level_check check (level in (1, 2))
);

alter table public.notifications add constraint notifications_organization_id_id_key unique (organization_id, id);

alter table public.notifications
    add constraint notifications_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.notifications
    add constraint notifications_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id) on delete cascade;
alter table public.notifications
    add constraint notifications_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.notifications
    add constraint notifications_patient_id_fkey foreign key (organization_id, patient_id) references public.patients(organization_id, id) on delete cascade;
alter table public.notifications
    add constraint notifications_task_id_fkey foreign key (organization_id, task_id) references public.tasks(organization_id, id) on delete set null (task_id);
alter table public.notification_preferences
    add constraint notification_preferences_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id) on delete cascade;
alter table public.response_alerts
    add constraint response_alerts_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;

create index notifications_sales_id_idx on public.notifications using btree (sales_id, updated_at desc);
create index notifications_unread_idx on public.notifications using btree (organization_id, sales_id, deal_id) where read_at is null;
create index notifications_deal_id_idx on public.notifications using btree (organization_id, deal_id);
create index notifications_telegram_idx on public.notifications using btree (created_at) where telegram_status is null;
create unique index notification_preferences_link_code_idx on public.notification_preferences using btree (telegram_link_code) where telegram_link_code is not null;
create index tasks_overdue_idx on public.tasks using btree (due_date) where done_date is null and overdue_notified_at is null;

--
-- Response time
--

-- Minutes between two moments that fall within the working hours of the
-- clinic (hours_start:00 to hours_end:00, every day, in its time zone).
-- Same as workingMinutes() in providers/commons/responseTime.ts.
CREATE OR REPLACE FUNCTION "private"."working_minutes"("from_at" timestamp with time zone, "to_at" timestamp with time zone, "time_zone" "text", "hours_start" integer DEFAULT 9, "hours_end" integer DEFAULT 21) RETURNS integer
    LANGUAGE "sql" STABLE
    SET "search_path" TO ''
    AS $$
  select coalesce(floor(sum(greatest(0, extract(epoch from
      least(to_at, (g.day + make_interval(hours => hours_end)) at time zone z.tz)
      - greatest(from_at, (g.day + make_interval(hours => hours_start)) at time zone z.tz)
    ))) / 60)::integer, 0)
  from (select coalesce(nullif(time_zone, ''), 'Asia/Almaty') as tz) z
    cross join lateral generate_series(
      (from_at at time zone z.tz)::date::timestamp,
      (to_at at time zone z.tz)::date::timestamp,
      interval '1 day') as g(day)
  where from_at < to_at
$$;

-- Since when the patient of a deal waits for an answer: the first inbound
-- message after the last answer of the clinic (null: nobody waits). An
-- automatic message is not an answer. Runs with the caller's rights.
CREATE OR REPLACE FUNCTION "private"."deal_waiting_since"("org_id" bigint, "target_deal_id" bigint) RETURNS timestamp with time zone
    LANGUAGE "sql" STABLE
    SET "search_path" TO ''
    AS $$
  select min(m.sent_at)
  from public.messages m
  where m.organization_id = org_id and m.deal_id = target_deal_id and m.direction = 'in'
    and m.sent_at > coalesce((
      select max(r.sent_at)
      from public.messages r
      where r.organization_id = org_id and r.deal_id = target_deal_id and r.direction = 'out'
        and (r.automessage_id is null or r.sales_id is not null)
    ), '-infinity'::timestamp with time zone)
$$;

-- Open deals whose patient waits for an answer, with the working minutes
-- waited and the clinic's limit (overdue: the limit is reached). The board
-- marks the overdue ones, the dashboard lists them.
create or replace view public.deals_waiting with (security_invoker = on) as
select
    d.id,
    d.organization_id,
    d.patient_id,
    d.pipeline_id,
    d.stage_id,
    d.sales_id,
    d.name,
    p.first_name as patient_first_name,
    p.last_name as patient_last_name,
    p.phones[1] as patient_phone,
    w.waiting_since,
    w.waiting_minutes,
    os.response_limit_minutes as limit_minutes,
    w.waiting_minutes >= os.response_limit_minutes as overdue
from public.deals d
    join public.stages s on s.id = d.stage_id and s.kind = 'open'
    join public.patients p on p.organization_id = d.organization_id and p.id = d.patient_id
    join public.organizations o on o.id = d.organization_id
    join public.organization_settings os on os.organization_id = d.organization_id and os.response_control_enabled
    cross join lateral (
        select
            ws.since as waiting_since,
            private.working_minutes(ws.since, now(), o.timezone, os.response_hours_start, os.response_hours_end) as waiting_minutes
        from (select private.deal_waiting_since(d.organization_id, d.id) as since) ws
    ) w
where d.archived_at is null and w.waiting_since is not null;

--
-- Notification helpers
--

-- "1 сообщение", "2 сообщения", "5 сообщений"
CREATE OR REPLACE FUNCTION "private"."plural_ru"("n" integer, "one" "text", "few" "text", "many" "text") RETURNS "text"
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select n || ' ' || case
    when n % 100 between 11 and 14 then many
    when n % 10 = 1 then one
    when n % 10 between 2 and 4 then few
    else many
  end
$$;

-- "Иванова Асель · Имплантация": the patient and what the deal is about
CREATE OR REPLACE FUNCTION "private"."deal_label"("deal" "public"."deals") RETURNS "text"
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
  select concat_ws(' · ',
    coalesce(nullif(btrim(concat_ws(' ', p.last_name, p.first_name)), ''), p.phones[1], 'Пациент'),
    coalesce(nullif(btrim(deal.name), ''), sv.name))
  from (select 1) x
    left join public.patients p on p.organization_id = deal.organization_id and p.id = deal.patient_id
    left join public.services sv on sv.organization_id = deal.organization_id and sv.id = deal.service_id
$$;

-- Active owner and heads of a clinic
CREATE OR REPLACE FUNCTION "private"."clinic_managers"("org_id" bigint) RETURNS bigint[]
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
  select coalesce(array_agg(s.id order by s.id), '{}'::bigint[])
  from public.sales s
  where s.organization_id = org_id and s.role in ('owner', 'head') and not s.disabled
$$;

-- Who hears about the patients of a deal: its responsible; for an unassigned
-- deal the "first to answer" list (everybody when the list is empty), else
-- the owner and heads
CREATE OR REPLACE FUNCTION "private"."deal_audience"("deal" "public"."deals") RETURNS bigint[]
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  settings public.organization_settings;
  chosen bigint[];
begin
  if deal.sales_id is not null and exists (
    select 1 from public.sales s
    where s.organization_id = deal.organization_id and s.id = deal.sales_id and not s.disabled
  ) then
    return array[deal.sales_id];
  end if;
  select * into settings from public.organization_settings os where os.organization_id = deal.organization_id;
  if deal.sales_id is null and settings.lead_distribution = 'first_response' then
    select coalesce(array_agg(s.id order by s.id), '{}'::bigint[]) into chosen
    from public.sales s
    where s.organization_id = deal.organization_id and not s.disabled
      and (cardinality(settings.lead_distribution_sales_ids) = 0 or s.id = any(settings.lead_distribution_sales_ids));
    if cardinality(chosen) > 0 then
      return chosen;
    end if;
  end if;
  return private.clinic_managers(deal.organization_id);
end;
$$;

-- A notification for an active employee of the clinic (else nothing)
CREATE OR REPLACE FUNCTION "private"."add_notification"("org_id" bigint, "recipient_id" bigint, "notification_kind" "text", "notification_title" "text", "notification_body" "text", "target_deal_id" bigint DEFAULT NULL::bigint, "target_patient_id" bigint DEFAULT NULL::bigint, "target_task_id" bigint DEFAULT NULL::bigint) RETURNS bigint
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  new_id bigint;
begin
  if recipient_id is null or not exists (
    select 1 from public.sales s
    where s.organization_id = org_id and s.id = recipient_id and not s.disabled
  ) then
    return null;
  end if;
  insert into public.notifications (organization_id, sales_id, kind, title, body, deal_id, patient_id, task_id)
  values (org_id, recipient_id, notification_kind, notification_title, notification_body,
    target_deal_id, target_patient_id, target_task_id)
  returning id into new_id;
  return new_id;
end;
$$;

--
-- Triggers
--

-- lead_assigned: a deal got a responsible (on creation or later) who is not
-- the author of the change. The first answer of "first to answer takes the
-- lead" is the employee's own action too: their message is stored in the
-- same transaction as the assignment.
CREATE OR REPLACE FUNCTION "private"."handle_deal_assignment_notify"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  actor_id bigint := private.current_sales_id();
  actor_name text;
begin
  if new.sales_id is null or (tg_op = 'UPDATE' and new.sales_id is not distinct from old.sales_id)
    or current_setting('crm.notifications', true) = 'off' then
    return null;
  end if;
  if new.sales_id = actor_id then
    return null;
  end if;
  if exists (
    select 1 from public.messages m
    where m.organization_id = new.organization_id and m.deal_id = new.id
      and m.direction = 'out' and m.sales_id = new.sales_id and m.created_at = now()
  ) then
    return null;
  end if;
  select nullif(btrim(concat_ws(' ', s.first_name, s.last_name)), '') into actor_name
  from public.sales s where s.id = actor_id;
  perform private.add_notification(new.organization_id, new.sales_id, 'lead_assigned',
    case when tg_op = 'INSERT' and actor_id is null then 'Новое обращение' else 'Вам передали сделку' end,
    private.deal_label(new) || coalesce(' · от ' || actor_name, ''),
    new.id, new.patient_id, null);
  return null;
end;
$$;

-- patient_message: an inbound message tells the deal's audience. A message
-- of the same deal within 5 minutes of the last one updates the unread
-- notification (count in the title and the body) instead of adding one; a
-- new lead assigned in the same transaction already got "Новое обращение".
CREATE OR REPLACE FUNCTION "private"."handle_message_notify"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  deal public.deals;
  recipient bigint;
  patient_name text;
  excerpt text;
begin
  if current_setting('crm.notifications', true) = 'off' then
    return null;
  end if;
  select d.* into deal from public.deals d
  where d.organization_id = new.organization_id and d.id = new.deal_id;
  if deal.id is null then
    return null;
  end if;
  select coalesce(nullif(btrim(concat_ws(' ', p.last_name, p.first_name)), ''), p.phones[1], 'Пациент')
  into patient_name
  from public.patients p where p.organization_id = new.organization_id and p.id = new.patient_id;
  excerpt := left(coalesce(nullif(btrim(new.text), ''), '[вложение]'), 200);

  foreach recipient in array private.deal_audience(deal) loop
    update public.notifications n
    set message_count = n.message_count + 1,
        title = 'Новые сообщения (' || (n.message_count + 1) || ')',
        body = patient_name || ', ' || private.plural_ru(n.message_count + 1, 'сообщение', 'сообщения', 'сообщений')
          || ': ' || excerpt,
        updated_at = now()
    where n.organization_id = new.organization_id and n.sales_id = recipient
      and n.kind = 'patient_message' and n.deal_id = new.deal_id
      and n.read_at is null and n.updated_at > now() - interval '5 minutes';
    if found then
      continue;
    end if;
    if exists (
      select 1 from public.notifications n
      where n.organization_id = new.organization_id and n.sales_id = recipient
        and n.kind = 'lead_assigned' and n.deal_id = new.deal_id and n.created_at = now()
    ) then
      continue;
    end if;
    perform private.add_notification(new.organization_id, recipient, 'patient_message',
      'Новое сообщение', patient_name || ': ' || excerpt, new.deal_id, new.patient_id, null);
  end loop;
  return null;
end;
$$;

-- A task whose due date moves may be notified again
CREATE OR REPLACE FUNCTION "private"."handle_task_due_changed"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
begin
  if new.due_date is distinct from old.due_date then
    new.overdue_notified_at := null;
  end if;
  return new;
end;
$$;

--
-- Periodic job (pg_cron, every minute)
--

-- task_overdue: open tasks that passed their due date within the last day
-- (older ones are not announced, e.g. right after the deployment), once
CREATE OR REPLACE FUNCTION "private"."notify_overdue_tasks"() RETURNS integer
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  task record;
  deal public.deals;
  notified integer := 0;
begin
  for task in
    update public.tasks t
    set overdue_notified_at = now()
    where t.done_date is null and t.overdue_notified_at is null
      and t.due_date < now() and t.due_date > now() - interval '1 day'
    returning t.organization_id, t.id, t.deal_id, t.sales_id, t.text
  loop
    select d.* into deal from public.deals d
    where d.organization_id = task.organization_id and d.id = task.deal_id;
    if private.add_notification(task.organization_id, coalesce(task.sales_id, deal.sales_id), 'task_overdue',
      'Задача просрочена',
      coalesce(nullif(btrim(task.text), ''), 'Задача') || ' · ' || private.deal_label(deal),
      task.deal_id, deal.patient_id, task.id) is not null then
      notified := notified + 1;
    end if;
  end loop;
  return notified;
end;
$$;

-- response_overdue: deals waiting longer than the limit of their clinic.
-- Level 1 (the limit) goes to the configured people, level 2 (3x the limit)
-- to the owner and heads; each level once per waiting episode.
CREATE OR REPLACE FUNCTION "private"."notify_response_overdue"() RETURNS integer
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  item record;
  reached integer;
  new_level integer;
  recipients bigint[];
  recipient bigint;
  notified integer := 0;
begin
  for item in
    select d as deal, os as settings, w.waiting_since,
      private.working_minutes(w.waiting_since, now(), o.timezone, os.response_hours_start, os.response_hours_end) as minutes
    from public.deals d
      join public.stages s on s.id = d.stage_id and s.kind = 'open'
      join public.organizations o on o.id = d.organization_id
      join public.organization_settings os on os.organization_id = d.organization_id and os.response_control_enabled
      cross join lateral (select private.deal_waiting_since(d.organization_id, d.id) as waiting_since) w
    where d.archived_at is null
      and w.waiting_since is not null
      and w.waiting_since < now() - make_interval(mins => os.response_limit_minutes)
      and not exists (
        select 1 from public.response_alerts a
        where a.organization_id = d.organization_id and a.deal_id = d.id
          and a.waiting_since = w.waiting_since and a.level = 2
      )
  loop
    reached := case
      when item.minutes >= 3 * (item.settings).response_limit_minutes then 2
      when item.minutes >= (item.settings).response_limit_minutes then 1
      else 0
    end;
    recipients := '{}'::bigint[];
    new_level := 0;
    for level_no in 1..reached loop
      insert into public.response_alerts (organization_id, deal_id, waiting_since, level)
      values ((item.deal).organization_id, (item.deal).id, item.waiting_since, level_no)
      on conflict do nothing;
      if not found then
        continue;
      end if;
      new_level := level_no;
      if level_no = 1 then
        if (item.settings).response_alert_responsible then
          recipients := recipients || private.deal_audience(item.deal);
        end if;
        if (item.settings).response_alert_managers then
          recipients := recipients || private.clinic_managers((item.deal).organization_id);
        end if;
        recipients := recipients || (item.settings).response_alert_sales_ids;
      else
        recipients := recipients || private.clinic_managers((item.deal).organization_id);
      end if;
    end loop;
    if new_level = 0 then
      continue;
    end if;
    for recipient in select distinct r from unnest(recipients) r loop
      if private.add_notification((item.deal).organization_id, recipient, 'response_overdue',
        case when new_level = 2 then 'Пациент всё ещё ждёт ответа' else 'Пациент ждёт ответа' end,
        private.deal_label(item.deal) || ' · ждёт ' || item.minutes || ' мин',
        (item.deal).id, (item.deal).patient_id, null) is not null then
        notified := notified + 1;
      end if;
    end loop;
  end loop;
  return notified;
end;
$$;

-- Starts the edge function notifications_dispatch when a linked employee has
-- a notification to receive in Telegram. Needs the Vault secrets project_url
-- and notifications_dispatch_key (= function secret NOTIFICATIONS_DISPATCH_KEY).
CREATE OR REPLACE FUNCTION "private"."request_notifications_dispatch"() RETURNS bigint
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  project_url text;
  dispatch_key text;
begin
  if not exists (
    select 1 from public.notifications n
      join public.notification_preferences p on p.organization_id = n.organization_id and p.sales_id = n.sales_id
    where n.telegram_status is null and n.created_at > now() - interval '1 hour'
      and p.telegram_enabled and p.telegram_chat_id is not null
  ) then
    return null;
  end if;
  if to_regclass('vault.decrypted_secrets') is null then
    return null;
  end if;
  execute 'select decrypted_secret from vault.decrypted_secrets where name = $1'
    into project_url using 'project_url';
  execute 'select decrypted_secret from vault.decrypted_secrets where name = $1'
    into dispatch_key using 'notifications_dispatch_key';
  if project_url is null or dispatch_key is null then
    raise warning 'notifications: Vault secrets project_url and notifications_dispatch_key are not set';
    return null;
  end if;
  return net.http_post(
    url := rtrim(project_url, '/') || '/functions/v1/notifications_dispatch',
    body := '{}'::jsonb,
    params := '{}'::jsonb,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || dispatch_key
    ),
    timeout_milliseconds := 5000
  );
end;
$$;

-- The job of pg_cron: overdue tasks, overdue answers, then Telegram
CREATE OR REPLACE FUNCTION "private"."notifications_tick"() RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  tasks integer;
  answers integer;
begin
  tasks := private.notify_overdue_tasks();
  answers := private.notify_response_overdue();
  perform private.request_notifications_dispatch();
  return jsonb_build_object('task_overdue', tasks, 'response_overdue', answers);
end;
$$;

--
-- Telegram (edge functions notifications_dispatch and notify_telegram_webhook,
-- service role only)
--

-- Takes the new notifications of the employees who linked Telegram, at most
-- max_rows, with FOR UPDATE SKIP LOCKED so that two runs never take the same
-- row. A kind the employee switched off is skipped; the others are returned
-- (status sending) with the chat to send to. A run that died while sending
-- leaves failed rows after 10 minutes: better than a message sent twice.
CREATE OR REPLACE FUNCTION "public"."claim_telegram_notifications"("max_rows" integer DEFAULT 100) RETURNS TABLE("notification_id" bigint, "chat_id" "text", "notification_kind" "text", "notification_title" "text", "notification_body" "text", "notification_deal_id" bigint, "clinic_name" "text")
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  job record;
begin
  update public.notifications n
  set telegram_status = 'failed'
  where n.telegram_status = 'sending' and n.telegram_claimed_at < now() - interval '10 minutes';

  for job in
    select n.id, n.kind, n.title, n.body, n.deal_id, p.telegram_chat_id, p.kinds,
      coalesce(nullif(btrim(c.config ->> 'title'), ''), o.name) as clinic
    from public.notifications n
      join public.notification_preferences p on p.organization_id = n.organization_id and p.sales_id = n.sales_id
      join public.organizations o on o.id = n.organization_id
      left join public.configuration c on c.organization_id = n.organization_id
    where n.telegram_status is null and n.created_at > now() - interval '1 hour'
      and p.telegram_enabled and p.telegram_chat_id is not null
    order by n.id
    limit greatest(max_rows, 0)
    for update of n skip locked
  loop
    if not (job.kind = any(job.kinds)) then
      update public.notifications n set telegram_status = 'skipped' where n.id = job.id;
      continue;
    end if;
    update public.notifications n
    set telegram_status = 'sending', telegram_claimed_at = now()
    where n.id = job.id;
    notification_id := job.id;
    chat_id := job.telegram_chat_id;
    notification_kind := job.kind;
    notification_title := job.title;
    notification_body := job.body;
    notification_deal_id := job.deal_id;
    clinic_name := job.clinic;
    return next;
  end loop;
end;
$$;

-- /start <code> from the platform bot: links the chat to the employee who
-- asked for the code (valid 30 minutes, once)
CREATE OR REPLACE FUNCTION "public"."link_telegram_chat"("link_code" "text", "chat_id" "text", "chat_username" "text" DEFAULT NULL::"text") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  linked public.notification_preferences;
begin
  if nullif(btrim(link_code), '') is null or nullif(btrim(chat_id), '') is null then
    return jsonb_build_object('linked', false);
  end if;
  update public.notification_preferences p
  set telegram_chat_id = btrim(link_telegram_chat.chat_id),
      telegram_username = nullif(btrim(chat_username), ''),
      telegram_linked_at = now(),
      telegram_enabled = true,
      telegram_link_code = null,
      telegram_link_expires_at = null,
      updated_at = now()
  where p.telegram_link_code = btrim(link_code) and p.telegram_link_expires_at > now()
  returning p.* into linked;
  if linked.sales_id is null then
    return jsonb_build_object('linked', false);
  end if;
  return (
    select jsonb_build_object('linked', true, 'first_name', s.first_name,
      'clinic', coalesce(nullif(btrim(c.config ->> 'title'), ''), o.name))
    from public.sales s
      join public.organizations o on o.id = s.organization_id
      left join public.configuration c on c.organization_id = s.organization_id
    where s.id = linked.sales_id
  );
end;
$$;

-- /stop from the platform bot, or the bot was blocked: the chat gets nothing
CREATE OR REPLACE FUNCTION "public"."unlink_telegram_chat"("chat_id" "text") RETURNS integer
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  unlinked integer;
begin
  update public.notification_preferences p
  set telegram_chat_id = null, telegram_username = null, telegram_linked_at = null, updated_at = now()
  where p.telegram_chat_id = unlink_telegram_chat.chat_id;
  get diagnostics unlinked = row_count;
  return unlinked;
end;
$$;

--
-- Employee API (the current user only)
--

-- Preferences of the current employee (the defaults when never saved)
CREATE OR REPLACE FUNCTION "public"."get_notification_preferences"() RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  me bigint := private.current_sales_id();
  prefs public.notification_preferences;
begin
  if me is null then
    raise exception 'Not an employee' using errcode = '42501';
  end if;
  select * into prefs from public.notification_preferences p where p.sales_id = me;
  return jsonb_build_object(
    'kinds', to_jsonb(coalesce(prefs.kinds, array['lead_assigned', 'patient_message', 'task_overdue', 'response_overdue'])),
    'browser_enabled', coalesce(prefs.browser_enabled, false),
    'telegram_enabled', coalesce(prefs.telegram_enabled, true),
    'telegram_linked', prefs.telegram_chat_id is not null,
    'telegram_username', prefs.telegram_username,
    'telegram_link_code', case when prefs.telegram_link_expires_at > now() then prefs.telegram_link_code end,
    'telegram_link_expires_at', case when prefs.telegram_link_expires_at > now() then prefs.telegram_link_expires_at end
  );
end;
$$;

-- Saves what the employee receives in the browser and in Telegram
CREATE OR REPLACE FUNCTION "public"."save_notification_preferences"("kinds" "text"[], "browser_enabled" boolean, "telegram_enabled" boolean) RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  me bigint := private.current_sales_id();
begin
  if me is null then
    raise exception 'Not an employee' using errcode = '42501';
  end if;
  insert into public.notification_preferences (sales_id, organization_id, kinds, browser_enabled, telegram_enabled)
  values (me, private.current_organization_id(),
    array(select distinct k from unnest(coalesce(save_notification_preferences.kinds, '{}'::text[])) k order by k),
    coalesce(save_notification_preferences.browser_enabled, false),
    coalesce(save_notification_preferences.telegram_enabled, true))
  on conflict (sales_id) do update
  set kinds = excluded.kinds,
      browser_enabled = excluded.browser_enabled,
      telegram_enabled = excluded.telegram_enabled,
      updated_at = now();
  return public.get_notification_preferences();
end;
$$;

-- «Подключить Telegram»: a one-time code for t.me/<bot>?start=<code>
CREATE OR REPLACE FUNCTION "public"."create_telegram_link_code"() RETURNS "text"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  me bigint := private.current_sales_id();
  code text := substr(replace(gen_random_uuid()::text, '-', ''), 1, 16);
begin
  if me is null then
    raise exception 'Not an employee' using errcode = '42501';
  end if;
  insert into public.notification_preferences (sales_id, organization_id, telegram_link_code, telegram_link_expires_at)
  values (me, private.current_organization_id(), code, now() + interval '30 minutes')
  on conflict (sales_id) do update
  set telegram_link_code = excluded.telegram_link_code,
      telegram_link_expires_at = excluded.telegram_link_expires_at,
      updated_at = now();
  return code;
end;
$$;

-- «Отключить Telegram»
CREATE OR REPLACE FUNCTION "public"."unlink_telegram"() RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  update public.notification_preferences p
  set telegram_chat_id = null, telegram_username = null, telegram_linked_at = null,
      telegram_link_code = null, telegram_link_expires_at = null, updated_at = now()
  where p.sales_id = private.current_sales_id();
end;
$$;

-- «Прочитать все» (RLS: only the caller's notifications)
CREATE OR REPLACE FUNCTION "public"."mark_all_notifications_read"() RETURNS integer
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  marked integer;
begin
  update public.notifications n
  set read_at = now()
  where n.sales_id = private.current_sales_id() and n.read_at is null;
  get diagnostics marked = row_count;
  return marked;
end;
$$;

--
-- Triggers
--

create or replace trigger deal_notify_assignment
    after insert or update of sales_id on public.deals
    for each row execute function private.handle_deal_assignment_notify();

create or replace trigger message_notify
    after insert on public.messages
    for each row
    when (new.direction = 'in')
    execute function private.handle_message_notify();

create or replace trigger task_due_changed
    before update of due_date on public.tasks
    for each row execute function private.handle_task_due_changed();

--
-- Row Level Security: an employee reads and marks only their own
-- notifications; preferences and alerts go through the functions above
--

alter table public.notifications enable row level security;
alter table public.notification_preferences enable row level security;
alter table public.response_alerts enable row level security;

create policy "Own notifications can be read" on public.notifications for select to authenticated
    using (organization_id = (select private.current_organization_id()) and sales_id = (select private.current_sales_id()));
create policy "Own notifications can be marked read" on public.notifications for update to authenticated
    using (organization_id = (select private.current_organization_id()) and sales_id = (select private.current_sales_id()))
    with check (organization_id = (select private.current_organization_id()) and sales_id = (select private.current_sales_id()));

--
-- Grants
--

revoke all on table public.notifications from anon, authenticated;
grant select on table public.notifications to authenticated;
grant update (read_at) on table public.notifications to authenticated;
grant all on table public.notifications to service_role;
revoke all on sequence public.notifications_id_seq from anon, authenticated;
grant all on sequence public.notifications_id_seq to service_role;

revoke all on table public.notification_preferences from anon, authenticated;
grant all on table public.notification_preferences to service_role;
revoke all on table public.response_alerts from anon, authenticated;
grant all on table public.response_alerts to service_role;

revoke all on table public.deals_waiting from anon, authenticated;
grant select on table public.deals_waiting to authenticated;
grant select on table public.deals_waiting to service_role;

-- Helpers of the view (run with the caller's rights)
revoke all on function private.working_minutes(timestamp with time zone, timestamp with time zone, text, integer, integer) from public;
grant execute on function private.working_minutes(timestamp with time zone, timestamp with time zone, text, integer, integer) to authenticated;
grant execute on function private.working_minutes(timestamp with time zone, timestamp with time zone, text, integer, integer) to service_role;
revoke all on function private.deal_waiting_since(bigint, bigint) from public;
grant execute on function private.deal_waiting_since(bigint, bigint) to authenticated;
grant execute on function private.deal_waiting_since(bigint, bigint) to service_role;

-- Definer helpers of the triggers and the job: not callable by clients
revoke all on function private.plural_ru(integer, text, text, text) from public;
revoke all on function private.deal_label(public.deals) from public, anon, authenticated;
revoke all on function private.clinic_managers(bigint) from public, anon, authenticated;
revoke all on function private.deal_audience(public.deals) from public, anon, authenticated;
revoke all on function private.add_notification(bigint, bigint, text, text, text, bigint, bigint, bigint) from public, anon, authenticated;
revoke all on function private.handle_deal_assignment_notify() from public, anon, authenticated;
revoke all on function private.handle_message_notify() from public, anon, authenticated;
revoke all on function private.notify_overdue_tasks() from public, anon, authenticated;
revoke all on function private.notify_response_overdue() from public, anon, authenticated;
revoke all on function private.request_notifications_dispatch() from public, anon, authenticated;
revoke all on function private.notifications_tick() from public, anon, authenticated;

-- The edge functions (service role)
revoke all on function public.claim_telegram_notifications(integer) from public, anon, authenticated;
grant execute on function public.claim_telegram_notifications(integer) to service_role;
revoke all on function public.link_telegram_chat(text, text, text) from public, anon, authenticated;
grant execute on function public.link_telegram_chat(text, text, text) to service_role;
revoke all on function public.unlink_telegram_chat(text) from public, anon, authenticated;
grant execute on function public.unlink_telegram_chat(text) to service_role;

-- Employees
revoke all on function public.get_notification_preferences() from public, anon;
grant execute on function public.get_notification_preferences() to authenticated, service_role;
revoke all on function public.save_notification_preferences(text[], boolean, boolean) from public, anon;
grant execute on function public.save_notification_preferences(text[], boolean, boolean) to authenticated, service_role;
revoke all on function public.create_telegram_link_code() from public, anon;
grant execute on function public.create_telegram_link_code() to authenticated, service_role;
revoke all on function public.unlink_telegram() from public, anon;
grant execute on function public.unlink_telegram() to authenticated, service_role;
revoke all on function public.mark_all_notifications_read() from public, anon;
grant execute on function public.mark_all_notifications_read() to authenticated, service_role;

--
-- Data
--

-- Deals already waiting for an answer when this is deployed do not alert
-- (they show on the board and the dashboard)
insert into public.response_alerts (organization_id, deal_id, waiting_since, level)
select d.organization_id, d.id, w.waiting_since, l.level
from public.deals d
  cross join lateral (select private.deal_waiting_since(d.organization_id, d.id) as waiting_since) w
  cross join (values (1), (2)) as l(level)
where w.waiting_since is not null
on conflict do nothing;

-- The job runs every minute (pg_cron + pg_net; skipped where pg_cron is not
-- installed, e.g. the SQL tests)
do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule('notifications-tick', '* * * * *', 'select private.notifications_tick()');
  end if;
end;
$$;
