--
-- Stage 34: the treatment plan editor as a full page — plan types and
-- directions (clinic dictionaries), the header of a plan (type, complaints,
-- insurance policy), real stages of a plan (treatment_stages: name, doctor,
-- direction, deadline, description, status, discount), stage templates.
-- The stage-29 items are moved to stages by their stage number; every plan
-- gets at least «Этап 1». See supabase/schemas/34_plan_editor.sql.
--

--
-- Dictionaries
--

create table public.treatment_plan_types (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    position integer not null default 0,
    is_archived boolean not null default false,
    created_at timestamp with time zone not null default now(),
    constraint treatment_plan_types_name_not_blank check (btrim(name) <> '')
);

create table public.treatment_directions (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    position integer not null default 0,
    is_archived boolean not null default false,
    created_at timestamp with time zone not null default now(),
    constraint treatment_directions_name_not_blank check (btrim(name) <> '')
);

alter table public.treatment_plan_types add constraint treatment_plan_types_organization_id_id_key unique (organization_id, id);
alter table public.treatment_directions add constraint treatment_directions_organization_id_id_key unique (organization_id, id);
alter table public.treatment_plan_types
    add constraint treatment_plan_types_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.treatment_directions
    add constraint treatment_directions_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
create index treatment_plan_types_organization_id_idx on public.treatment_plan_types using btree (organization_id, position);
create index treatment_directions_organization_id_idx on public.treatment_directions using btree (organization_id, position);

--
-- The header of a plan
--

alter table public.treatment_plans add column plan_type_id bigint;
alter table public.treatment_plans add column complaints text;
alter table public.treatment_plans add column insurance_policy text;
alter table public.treatment_plans add constraint treatment_plans_insurance_policy_length check (char_length(insurance_policy) <= 100);
alter table public.treatment_plans
    add constraint treatment_plans_plan_type_id_fkey foreign key (organization_id, plan_type_id) references public.treatment_plan_types(organization_id, id) on delete set null (plan_type_id);

--
-- Stages
--

create table public.treatment_stages (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    plan_id bigint not null,
    -- The stage number («Этап 1, 2…»): the next one when not given
    position integer not null default 0,
    name text not null default '',
    doctor_id bigint,
    direction_id bigint,
    deadline date,
    description text,
    status text not null default 'new',
    discount_percent numeric(5,2) not null default 0,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint treatment_stages_name_not_blank check (btrim(name) <> ''),
    constraint treatment_stages_position_check check (position >= 1 and position <= 20),
    constraint treatment_stages_status_check check (status in ('new', 'in_progress', 'done', 'cancelled')),
    constraint treatment_stages_discount_check check (discount_percent >= 0 and discount_percent <= 100)
);

alter table public.treatment_stages add constraint treatment_stages_organization_id_id_key unique (organization_id, id);
-- The items reference (organization_id, plan_id, id): a stage of their plan
alter table public.treatment_stages add constraint treatment_stages_plan_id_id_key unique (organization_id, plan_id, id);
alter table public.treatment_stages add constraint treatment_stages_plan_position_key unique (organization_id, plan_id, position) deferrable;
alter table public.treatment_stages
    add constraint treatment_stages_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.treatment_stages
    add constraint treatment_stages_plan_id_fkey foreign key (organization_id, plan_id) references public.treatment_plans(organization_id, id) on delete cascade;
alter table public.treatment_stages
    add constraint treatment_stages_doctor_id_fkey foreign key (organization_id, doctor_id) references public.doctors(organization_id, id) on delete set null (doctor_id);
alter table public.treatment_stages
    add constraint treatment_stages_direction_id_fkey foreign key (organization_id, direction_id) references public.treatment_directions(organization_id, id) on delete set null (direction_id);

alter table public.treatment_plan_items add column stage_id bigint;

--
-- Stage templates
--

create table public.treatment_stage_templates (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    direction_id bigint,
    description text,
    -- [{ service_id, name, quantity, unit_price, discount_percent }], no teeth
    items jsonb not null default '[]'::jsonb,
    created_by bigint default private.current_sales_id(),
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint treatment_stage_templates_name_not_blank check (btrim(name) <> ''),
    constraint treatment_stage_templates_items_check check (jsonb_typeof(items) = 'array')
);

alter table public.treatment_stage_templates add constraint treatment_stage_templates_organization_id_id_key unique (organization_id, id);
alter table public.treatment_stage_templates
    add constraint treatment_stage_templates_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.treatment_stage_templates
    add constraint treatment_stage_templates_direction_id_fkey foreign key (organization_id, direction_id) references public.treatment_directions(organization_id, id) on delete set null (direction_id);
alter table public.treatment_stage_templates
    add constraint treatment_stage_templates_created_by_fkey foreign key (organization_id, created_by) references public.sales(organization_id, id) on delete set null (created_by);
create index treatment_stage_templates_organization_id_idx on public.treatment_stage_templates using btree (organization_id, name);

--
-- Functions
--

-- The total of a stage from the sum of its line totals and its discount.
-- Twin: stageTotal() in planMath.ts
CREATE OR REPLACE FUNCTION "private"."treatment_stage_total"("lines_total" bigint, "discount_percent" numeric) RETURNS bigint
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select lines_total - round(lines_total * discount_percent / 100)::bigint;
$$;

-- The subtotal of a plan: the totals of its stages, cancelled ones aside
CREATE OR REPLACE FUNCTION "private"."treatment_plan_subtotal"("org_id" bigint, "target_plan_id" bigint) RETURNS bigint
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  subtotal bigint;
begin
  select coalesce(sum(private.treatment_stage_total(t.lines_total, t.discount_percent)), 0)::bigint
  into subtotal
  from (
    select s.id, s.discount_percent, coalesce(sum(i.line_total), 0)::bigint as lines_total
    from public.treatment_stages s
      left join public.treatment_plan_items i on i.organization_id = s.organization_id and i.stage_id = s.id
    where s.organization_id = org_id and s.plan_id = target_plan_id and s.status <> 'cancelled'
    group by s.id, s.discount_percent
  ) t;
  return subtotal;
end;
$$;

-- The stage-29 items moved to real stages: a stage («Этап N») per stage
-- number of the items without a stage, «Этап 1» for a plan without any, the
-- items linked to their stage. Run once by the migration of stage 34; safe
-- to run again (only what has no stage yet). Returns the items moved.
CREATE OR REPLACE FUNCTION "private"."move_treatment_items_to_stages"() RETURNS integer
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  moved integer;
begin
  insert into public.treatment_stages (organization_id, plan_id, position, name, doctor_id)
  select n.organization_id, n.plan_id, n.stage_no, 'Этап ' || n.stage_no, p.doctor_id
  from (
    select i.organization_id, i.plan_id, i.stage_no
    from public.treatment_plan_items i
    where i.stage_id is null
    group by i.organization_id, i.plan_id, i.stage_no
    union
    select p.organization_id, p.id, 1
    from public.treatment_plans p
    where not exists (select 1 from public.treatment_stages s where s.organization_id = p.organization_id and s.plan_id = p.id)
      and not exists (select 1 from public.treatment_plan_items i
        where i.organization_id = p.organization_id and i.plan_id = p.id and i.stage_id is null)
  ) n
    join public.treatment_plans p on p.organization_id = n.organization_id and p.id = n.plan_id
  where not exists (select 1 from public.treatment_stages s
    where s.organization_id = n.organization_id and s.plan_id = n.plan_id and s.position = n.stage_no)
  order by n.organization_id, n.plan_id, n.stage_no;

  update public.treatment_plan_items i
  set stage_id = s.id
  from public.treatment_stages s
  where i.stage_id is null
    and s.organization_id = i.organization_id and s.plan_id = i.plan_id and s.position = i.stage_no;
  get diagnostics moved = row_count;
  return moved;
end;
$$;

-- «Оплачено» of a plan: the payments of its deal (deals.paid_amount). One
-- function, so that the patient payments and deposits can take over later
-- without touching the views and the editor. Runs with the caller's rights.
CREATE OR REPLACE FUNCTION "private"."treatment_plan_paid"("org_id" bigint, "target_deal_id" bigint) RETURNS bigint
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $$
begin
  return coalesce((
    select d.paid_amount from public.deals d
    where d.organization_id = org_id and d.id = target_deal_id
  ), 0);
end;
$$;

-- The stage of a plan with this number, created («Этап N») when missing:
-- items written with a stage number only (stage 29)
CREATE OR REPLACE FUNCTION "private"."treatment_stage_at"("org_id" bigint, "target_plan_id" bigint, "stage_number" integer) RETURNS bigint
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  found_id bigint;
begin
  select s.id into found_id
  from public.treatment_stages s
  where s.organization_id = org_id and s.plan_id = target_plan_id and s.position = stage_number;
  if found_id is null then
    insert into public.treatment_stages (organization_id, plan_id, position, name)
    values (org_id, target_plan_id, stage_number, 'Этап ' || stage_number)
    returning id into found_id;
  end if;
  return found_id;
end;
$$;

-- A stage follows its items: some done → in progress, all done → done,
-- no longer all done → in progress. A cancelled stage stays cancelled.
-- Twin: stageStatusAfterProgress() in planMath.ts
CREATE OR REPLACE FUNCTION "private"."treatment_stage_progress"("org_id" bigint, "target_stage_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  stage public.treatment_stages;
  total_items integer;
  done_items integer;
  next_status text;
begin
  select * into stage from public.treatment_stages s
  where s.organization_id = org_id and s.id = target_stage_id;
  if not found or stage.status = 'cancelled' then
    return;
  end if;
  select count(*), count(*) filter (where i.done) into total_items, done_items
  from public.treatment_plan_items i
  where i.organization_id = org_id and i.stage_id = stage.id;
  next_status := case
    when total_items > 0 and done_items = total_items then 'done'
    when stage.status = 'done' then 'in_progress'
    when done_items > 0 and stage.status = 'new' then 'in_progress'
    else stage.status
  end;
  if next_status <> stage.status then
    update public.treatment_stages s set status = next_status
    where s.organization_id = org_id and s.id = stage.id;
  end if;
end;
$$;

-- After items or stages change: the progress of an agreed plan (some done:
-- in progress, all done: completed; cancelled stages aside) and the plan
-- amount of the deal
CREATE OR REPLACE FUNCTION "private"."refresh_treatment_plan"("org_id" bigint, "target_plan_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  plan public.treatment_plans;
  total_items integer;
  done_items integer;
  next_status text;
begin
  select * into plan from public.treatment_plans p
  where p.organization_id = org_id and p.id = target_plan_id;
  if not found then
    return;
  end if;
  if plan.status in ('agreed', 'in_progress', 'completed') then
    select count(*), count(*) filter (where i.done) into total_items, done_items
    from public.treatment_plan_items i
      join public.treatment_stages s on s.organization_id = i.organization_id and s.id = i.stage_id
    where i.organization_id = org_id and i.plan_id = plan.id and s.status <> 'cancelled';
    next_status := case
      when total_items > 0 and done_items = total_items then 'completed'
      when plan.status = 'completed' then 'in_progress'
      when done_items > 0 and plan.status = 'agreed' then 'in_progress'
      else plan.status
    end;
    if next_status <> plan.status then
      update public.treatment_plans p set status = next_status
      where p.organization_id = org_id and p.id = plan.id;
    end if;
  end if;
  if plan.is_main then
    perform private.sync_treatment_plan_amount(plan.id);
  end if;
end;
$$;

-- Before a stage is written: its plan never changes, the next number and
-- «Этап N» by default, the doctor of the plan, the discount limit
CREATE OR REPLACE FUNCTION "private"."handle_treatment_stage_before_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  plan_doctor_id bigint;
begin
  if tg_op = 'UPDATE' and new.plan_id is distinct from old.plan_id then
    raise exception 'Этап не переносится в другой план' using errcode = '22023';
  end if;
  if tg_op = 'INSERT' then
    if coalesce(new.position, 0) < 1 then
      select coalesce(max(s.position), 0) + 1 into new.position
      from public.treatment_stages s
      where s.organization_id = new.organization_id and s.plan_id = new.plan_id;
    end if;
    if new.position > 20 then
      raise exception 'В плане не больше 20 этапов' using errcode = '23514', hint = 'too_many_stages';
    end if;
    if new.doctor_id is null then
      select p.doctor_id into plan_doctor_id from public.treatment_plans p
      where p.organization_id = new.organization_id and p.id = new.plan_id;
      new.doctor_id := plan_doctor_id;
    end if;
  end if;
  new.name := coalesce(nullif(btrim(new.name), ''), 'Этап ' || new.position);
  new.description := nullif(btrim(new.description), '');
  if new.discount_percent > 0 and (tg_op = 'INSERT' or new.discount_percent <> old.discount_percent) then
    perform private.check_treatment_discount(new.organization_id, new.discount_percent, 0, 0);
  end if;
  new.updated_at := now();
  return new;
end;
$$;

-- After a stage is written: the stage number of its items, the numbers of
-- the next stages when one is deleted, the totals and the progress of the
-- plan (status, discount, a deleted stage)
CREATE OR REPLACE FUNCTION "private"."handle_treatment_stage_after_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := coalesce(new.organization_id, old.organization_id);
  target_plan_id bigint := coalesce(new.plan_id, old.plan_id);
begin
  if tg_op = 'UPDATE' and new.position <> old.position then
    update public.treatment_plan_items i
    set stage_no = new.position
    where i.organization_id = org_id and i.stage_id = new.id and i.stage_no <> new.position;
  end if;
  -- A deleted stage: the next ones move up («Этап 3» becomes «Этап 2»)
  if tg_op = 'DELETE' and exists (
    select 1 from public.treatment_plans p where p.organization_id = org_id and p.id = target_plan_id) then
    update public.treatment_stages s
    set position = s.position - 1
    where s.organization_id = org_id and s.plan_id = target_plan_id and s.position > old.position;
  end if;
  if tg_op = 'DELETE'
    or (tg_op = 'UPDATE' and (new.status <> old.status or new.discount_percent <> old.discount_percent)) then
    perform private.refresh_treatment_plan(org_id, target_plan_id);
  end if;
  return null;
end;
$$;

-- A new plan starts with «Этап 1» (a duplicated plan copies its stages)
CREATE OR REPLACE FUNCTION "private"."handle_treatment_plan_first_stage"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if current_setting('crm.treatment_copy', true) = 'on' then
    return null;
  end if;
  insert into public.treatment_stages (organization_id, plan_id, position, name, doctor_id)
  values (new.organization_id, new.id, 1, 'Этап 1', new.doctor_id);
  return null;
end;
$$;

-- Default plan types and directions of a clinic (Settings → «Планы лечения»)
CREATE OR REPLACE FUNCTION "private"."seed_treatment_dictionaries"("org_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if not exists (select 1 from public.treatment_plan_types t where t.organization_id = org_id) then
    insert into public.treatment_plan_types (organization_id, name, position)
    values
      (org_id, 'Основной', 0),
      (org_id, 'Альтернативный', 1),
      (org_id, 'Эконом', 2),
      (org_id, 'Премиум', 3);
  end if;
  if not exists (select 1 from public.treatment_directions d where d.organization_id = org_id) then
    insert into public.treatment_directions (organization_id, name, position)
    values
      (org_id, 'Терапия', 0),
      (org_id, 'Хирургия', 1),
      (org_id, 'Ортопедия', 2),
      (org_id, 'Ортодонтия', 3),
      (org_id, 'Пародонтология', 4),
      (org_id, 'Имплантация', 5),
      (org_id, 'Гигиена', 6),
      (org_id, 'Детская стоматология', 7);
  end if;
end;
$$;

CREATE OR REPLACE FUNCTION "private"."handle_organization_treatment_dictionaries"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  perform private.seed_treatment_dictionaries(new.id);
  return new;
end;
$$;

-- «Сохранить как шаблон этапа»: the stage without teeth — identical lines
-- (same service, name, price, discount) merged, quantities added up. Runs
-- with the caller's rights.
CREATE OR REPLACE FUNCTION "public"."save_stage_template"("source_stage_id" bigint, "template_name" "text" DEFAULT NULL::"text") RETURNS bigint
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  stage public.treatment_stages;
  new_template_id bigint;
begin
  select * into stage from public.treatment_stages s
  where s.organization_id = private.current_organization_id() and s.id = source_stage_id;
  if not found then
    raise exception 'Этап не найден' using errcode = 'P0002';
  end if;
  insert into public.treatment_stage_templates (organization_id, name, direction_id, description, items)
  values (stage.organization_id, coalesce(nullif(btrim(template_name), ''), stage.name), stage.direction_id, stage.description,
    coalesce((
      select jsonb_agg(jsonb_build_object('service_id', l.service_id, 'name', l.name, 'quantity', l.quantity,
        'unit_price', l.unit_price, 'discount_percent', l.discount_percent) order by l.first_position, l.first_id)
      from (
        select i.service_id, i.name, i.unit_price, i.discount_percent,
          least(sum(i.quantity), 1000)::integer as quantity, min(i.position) as first_position, min(i.id) as first_id
        from public.treatment_plan_items i
        where i.organization_id = stage.organization_id and i.stage_id = stage.id
        group by i.service_id, i.name, i.unit_price, i.discount_percent
      ) l
    ), '[]'::jsonb))
  returning id into new_template_id;
  return new_template_id;
end;
$$;

-- «Добавить этап из шаблона»: a new stage at the end of the plan with the
-- template's items, at the prices of the current price list (the saved
-- price when the service is gone, archived or without a price). The
-- discounts are copied as they were saved. Runs with the caller's rights.
CREATE OR REPLACE FUNCTION "public"."add_stage_from_template"("target_plan_id" bigint, "source_template_id" bigint) RETURNS bigint
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  plan public.treatment_plans;
  template public.treatment_stage_templates;
  new_stage_id bigint;
begin
  select * into plan from public.treatment_plans p
  where p.organization_id = private.current_organization_id() and p.id = target_plan_id;
  if not found then
    raise exception 'План не найден' using errcode = 'P0002';
  end if;
  select * into template from public.treatment_stage_templates t
  where t.organization_id = plan.organization_id and t.id = source_template_id;
  if not found then
    raise exception 'Шаблон не найден' using errcode = 'P0002';
  end if;
  insert into public.treatment_stages (organization_id, plan_id, name, direction_id, description)
  values (plan.organization_id, plan.id, template.name, template.direction_id, template.description)
  returning id into new_stage_id;

  perform set_config('crm.treatment_copy', 'on', true);
  insert into public.treatment_plan_items (organization_id, plan_id, stage_id, service_id, name, quantity, unit_price, discount_percent, position)
  select plan.organization_id, plan.id, new_stage_id, sv.id,
    coalesce(nullif(btrim(x.item ->> 'name'), ''), sv.name, 'Услуга'),
    least(greatest(coalesce((x.item ->> 'quantity')::integer, 1), 1), 1000),
    coalesce(case when sv.id is not null and not sv.is_archived then round(sv.price)::bigint end,
      (x.item ->> 'unit_price')::bigint, 0),
    least(greatest(coalesce((x.item ->> 'discount_percent')::numeric, 0), 0), 100),
    (x.n - 1)::integer
  from jsonb_array_elements(template.items) with ordinality as x(item, n)
    left join public.services sv on sv.organization_id = plan.organization_id and sv.id = (x.item ->> 'service_id')::bigint
  order by x.n;
  perform set_config('crm.treatment_copy', '', true);
  return new_stage_id;
end;
$$;

--
-- Stage 29 functions, now with the stages (29_treatment_plans.sql)
--

-- deals.plan_amount = the total of the main plan of the deal
CREATE OR REPLACE FUNCTION "private"."sync_treatment_plan_amount"("target_plan_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  plan public.treatment_plans;
  total bigint;
begin
  select * into plan from public.treatment_plans p where p.id = target_plan_id;
  if not found or not plan.is_main then
    return;
  end if;
  -- The stages of the plan, cancelled ones aside (stage 34)
  total := private.treatment_plan_total(private.treatment_plan_subtotal(plan.organization_id, plan.id),
    plan.discount_percent, plan.discount_amount);
  update public.deals d
  set plan_amount = total
  where d.organization_id = plan.organization_id and d.id = plan.deal_id
    and d.plan_amount is distinct from total;
end;
$$;

-- Before a plan is written: the patient and the doctor of the deal, the
-- status rules (agreed → main plan of the deal, agreed_at), the discount
-- limit
CREATE OR REPLACE FUNCTION "private"."handle_treatment_plan_before_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  deal public.deals;
  subtotal bigint;
begin
  if tg_op = 'UPDATE' and new.deal_id is distinct from old.deal_id then
    raise exception 'План лечения не переносится в другую сделку' using errcode = '22023';
  end if;
  select * into deal from public.deals d where d.organization_id = new.organization_id and d.id = new.deal_id;
  if tg_op = 'INSERT' then
    new.patient_id := deal.patient_id;
    new.doctor_id := coalesce(new.doctor_id, deal.doctor_id);
  end if;
  new.name := coalesce(nullif(btrim(new.name), ''), 'План лечения');

  if new.status in ('draft', 'presented', 'declined') then
    new.is_main := false;
    if new.status <> 'declined' then
      new.agreed_at := null;
    end if;
  elsif tg_op = 'INSERT' then
    new.agreed_at := coalesce(new.agreed_at, now());
    new.is_main := true;
  elsif old.status in ('draft', 'presented', 'declined') then
    -- Agreed now: the main plan of the deal
    new.agreed_at := now();
    new.is_main := true;
  end if;
  if new.is_main and (tg_op = 'INSERT' or not old.is_main) then
    update public.treatment_plans p
    set is_main = false
    where p.organization_id = new.organization_id and p.deal_id = new.deal_id
      and p.is_main and p.id <> new.id;
  end if;

  if (tg_op = 'INSERT' and (new.discount_percent > 0 or new.discount_amount > 0))
    or (tg_op = 'UPDATE' and (new.discount_percent <> old.discount_percent or new.discount_amount <> old.discount_amount)) then
    subtotal := private.treatment_plan_subtotal(new.organization_id, new.id);
    perform private.check_treatment_discount(new.organization_id, new.discount_percent, subtotal, new.discount_amount);
  end if;
  new.updated_at := now();
  return new;
end;
$$;

-- Before an item is written: the name of the service, the done time, the
-- discount limit and the price list for the managers
CREATE OR REPLACE FUNCTION "private"."handle_treatment_item_before_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  role text := private.current_user_role();
  service public.services;
  stage_position integer;
begin
  if tg_op = 'UPDATE' and new.plan_id is distinct from old.plan_id then
    raise exception 'Позиция не переносится в другой план' using errcode = '22023';
  end if;
  -- The stage (stage 34): written by its id, or by its number only (stage
  -- 29 clients) — the stage with this number, created when missing.
  -- stage_no follows the number of the stage.
  if new.stage_id is null
    or (tg_op = 'UPDATE' and new.stage_no is distinct from old.stage_no and new.stage_id is not distinct from old.stage_id) then
    new.stage_id := private.treatment_stage_at(new.organization_id, new.plan_id, coalesce(new.stage_no, 1));
  end if;
  select s.position into stage_position from public.treatment_stages s
  where s.organization_id = new.organization_id and s.plan_id = new.plan_id and s.id = new.stage_id;
  if stage_position is null then
    raise exception 'Этап не найден в плане' using errcode = '23503';
  end if;
  new.stage_no := stage_position;
  if new.service_id is not null then
    select * into service from public.services s
    where s.organization_id = new.organization_id and s.id = new.service_id;
  end if;
  new.name := coalesce(nullif(btrim(new.name), ''), service.name);
  new.tooth := nullif(btrim(new.tooth), '');
  if new.done and (tg_op = 'INSERT' or not old.done) then
    new.done_at := now();
  elsif not new.done then
    new.done_at := null;
  end if;

  if role is not null and role not in ('owner', 'head')
    and current_setting('crm.treatment_copy', true) is distinct from 'on' then
    if new.discount_percent > 0 and (tg_op = 'INSERT' or new.discount_percent <> old.discount_percent) then
      perform private.check_treatment_discount(new.organization_id, new.discount_percent, 0, 0);
    end if;
    if service.price is not null and new.unit_price < round(service.price)
      and (tg_op = 'INSERT' or new.unit_price <> old.unit_price or new.service_id is distinct from old.service_id) then
      raise exception 'Цена ниже прайса (% ₸) — только владелец или руководитель', private.format_tenge(service.price)
        using errcode = '42501', hint = 'price_below_list';
    end if;
  end if;
  return new;
end;
$$;

-- After items change: the status of their stages (stage 34), the progress
-- of an agreed plan (some done: in progress, all done: completed) and the
-- plan amount of the deal (private.refresh_treatment_plan)
CREATE OR REPLACE FUNCTION "private"."handle_treatment_item_after_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := coalesce(new.organization_id, old.organization_id);
  target_plan_id bigint := coalesce(new.plan_id, old.plan_id);
begin
  if tg_op <> 'INSERT' and (tg_op = 'DELETE' or new.stage_id is distinct from old.stage_id) then
    perform private.treatment_stage_progress(org_id, old.stage_id);
  end if;
  if tg_op <> 'DELETE' then
    perform private.treatment_stage_progress(org_id, new.stage_id);
  end if;
  perform private.refresh_treatment_plan(org_id, target_plan_id);
  return null;
end;
$$;

-- «Дублировать план»: a draft copy with the header, the stages (new, a
-- cancelled one stays cancelled) and the items (not done). Runs with the
-- caller's rights; the discounts are copied as they are.
CREATE OR REPLACE FUNCTION "public"."duplicate_treatment_plan"("source_plan_id" bigint) RETURNS bigint
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  source public.treatment_plans;
  stage record;
  new_plan_id bigint;
  new_stage_id bigint;
begin
  select * into source from public.treatment_plans p
  where p.organization_id = private.current_organization_id() and p.id = source_plan_id;
  if not found then
    raise exception 'План не найден' using errcode = 'P0002';
  end if;
  perform set_config('crm.treatment_copy', 'on', true);
  insert into public.treatment_plans (organization_id, deal_id, name, status, discount_percent, discount_amount, note, doctor_id,
    plan_type_id, complaints, insurance_policy)
  values (source.organization_id, source.deal_id, left(source.name, 180) || ' (копия)', 'draft',
    source.discount_percent, source.discount_amount, source.note, source.doctor_id,
    source.plan_type_id, source.complaints, source.insurance_policy)
  returning id into new_plan_id;
  for stage in
    select * from public.treatment_stages s
    where s.organization_id = source.organization_id and s.plan_id = source.id
    order by s.position, s.id
  loop
    insert into public.treatment_stages (organization_id, plan_id, position, name, doctor_id, direction_id, deadline,
      description, status, discount_percent)
    values (stage.organization_id, new_plan_id, stage.position, stage.name, stage.doctor_id, stage.direction_id, stage.deadline,
      stage.description, case when stage.status = 'cancelled' then 'cancelled' else 'new' end, stage.discount_percent)
    returning id into new_stage_id;
    insert into public.treatment_plan_items (organization_id, plan_id, stage_id, service_id, name, tooth, quantity, unit_price, discount_percent, position)
    select i.organization_id, new_plan_id, new_stage_id, i.service_id, i.name, i.tooth, i.quantity, i.unit_price, i.discount_percent, i.position
    from public.treatment_plan_items i
    where i.organization_id = source.organization_id and i.stage_id = stage.id
    order by i.position, i.id;
  end loop;
  perform set_config('crm.treatment_copy', '', true);
  return new_plan_id;
end;
$$;

-- Reports «Деньги» → «Согласованные планы по позициям»: the services of the
-- main plans agreed in the period, by sum (top 20; cancelled stages aside
-- since stage 34). Same filters as the
-- other reports (the branch since stage 33); owner and head only.
CREATE OR REPLACE FUNCTION "public"."report_plan_services"("period_from" timestamp with time zone DEFAULT NULL::timestamp with time zone, "period_to" timestamp with time zone DEFAULT NULL::timestamp with time zone, "filter_pipeline_id" bigint DEFAULT NULL::bigint, "filter_sales_id" bigint DEFAULT NULL::bigint, "filter_source_id" bigint DEFAULT NULL::bigint, "filter_doctor_id" bigint DEFAULT NULL::bigint, "filter_branch_id" bigint DEFAULT NULL::bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $$
begin
  perform private.report_check_access();
  return coalesce((
    select jsonb_agg(jsonb_build_object('service_id', r.service_id, 'name', r.name, 'quantity', r.quantity,
      'amount', r.amount, 'plans', r.plans) order by r.amount desc, r.name)
    from (
      select i.service_id, coalesce(sv.name, i.name) as name, sum(i.quantity)::bigint as quantity,
        sum(i.line_total)::bigint as amount, count(distinct p.id) as plans
      from public.treatment_plans p
        join public.deals d on d.organization_id = p.organization_id and d.id = p.deal_id
        join public.treatment_plan_items i on i.organization_id = p.organization_id and i.plan_id = p.id
        join public.treatment_stages st on st.organization_id = i.organization_id and st.id = i.stage_id and st.status <> 'cancelled'
        left join public.services sv on sv.organization_id = i.organization_id and sv.id = i.service_id
      where p.organization_id = private.current_organization_id()
        and p.is_main
        and (period_from is null or p.agreed_at >= period_from)
        and (period_to is null or p.agreed_at < period_to)
        and (filter_pipeline_id is null or d.pipeline_id = filter_pipeline_id)
        and (filter_sales_id is null or d.sales_id = filter_sales_id)
        and (filter_source_id is null or d.source_id = filter_source_id)
        and (filter_doctor_id is null or coalesce(p.doctor_id, d.doctor_id) = filter_doctor_id)
        and (filter_branch_id is null or d.branch_id = filter_branch_id)
      group by i.service_id, coalesce(sv.name, i.name)
      order by amount desc, name
      limit 20
    ) r
  ), '[]'::jsonb);
end;
$$;

--
-- The stage-29 data: dictionaries of every clinic, a stage per stage number
-- of the items (and «Этап 1» for a plan without items), the items linked to
-- their stage. The audit triggers of the stages come later: the move is not
-- an action of anybody. The stage follows its items (done, in progress)
-- through the item triggers.
--

select private.seed_treatment_dictionaries(o.id) from public.organizations o;

select private.move_treatment_items_to_stages();

alter table public.treatment_plan_items alter column stage_id set not null;

alter table public.treatment_plan_items
    add constraint treatment_plan_items_stage_id_fkey foreign key (organization_id, plan_id, stage_id) references public.treatment_stages(organization_id, plan_id, id) on delete cascade;
create index treatment_plan_items_stage_id_idx on public.treatment_plan_items using btree (organization_id, stage_id, position);

--
-- Views
--

-- Plans with their totals and progress (deal page, patient card, estimate).
-- First declared in 29_treatment_plans.sql; the stages (discounts,
-- cancelled ones aside) since stage 34, the new columns come last.
create or replace view public.treatment_plans_summary with (security_invoker = on) as
select
    tp.id,
    tp.organization_id,
    tp.deal_id,
    tp.patient_id,
    tp.name,
    tp.status,
    tp.is_main,
    tp.discount_percent,
    tp.discount_amount,
    tp.note,
    tp.doctor_id,
    tp.created_by,
    tp.agreed_at,
    tp.created_at,
    tp.updated_at,
    t.items_count,
    t.done_count,
    t.gross_amount,
    t.subtotal_amount,
    t.done_amount,
    private.treatment_plan_total(t.subtotal_amount, tp.discount_percent, tp.discount_amount) as total_amount,
    t.gross_amount - private.treatment_plan_total(t.subtotal_amount, tp.discount_percent, tp.discount_amount) as discount_total,
    d.name as deal_name,
    d.paid_amount as deal_paid_amount,
    tp.plan_type_id,
    tp.complaints,
    tp.insurance_policy,
    t.stages_count,
    t.gross_amount - t.subtotal_amount as stages_discount_amount,
    t.subtotal_amount - private.treatment_plan_total(t.subtotal_amount, tp.discount_percent, tp.discount_amount) as extra_discount_amount,
    private.treatment_plan_paid(tp.organization_id, tp.deal_id) as paid_amount
from public.treatment_plans tp
    join public.deals d on d.organization_id = tp.organization_id and d.id = tp.deal_id
    cross join lateral (
        select
            coalesce(sum(s.items_count), 0)::integer as items_count,
            coalesce(sum(s.done_count), 0)::integer as done_count,
            coalesce(sum(s.gross_amount), 0)::bigint as gross_amount,
            coalesce(sum(private.treatment_stage_total(s.lines_amount, s.discount_percent)), 0)::bigint as subtotal_amount,
            coalesce(sum(s.done_amount), 0)::bigint as done_amount,
            count(*)::integer as stages_count
        from (
            select
                st.id,
                st.discount_percent,
                count(i.id) as items_count,
                count(i.id) filter (where i.done) as done_count,
                coalesce(sum(i.quantity * i.unit_price), 0)::bigint as gross_amount,
                coalesce(sum(i.line_total), 0)::bigint as lines_amount,
                coalesce(sum(i.line_total) filter (where i.done), 0)::bigint as done_amount
            from public.treatment_stages st
                left join public.treatment_plan_items i on i.organization_id = st.organization_id and i.stage_id = st.id
            where st.organization_id = tp.organization_id and st.plan_id = tp.id and st.status <> 'cancelled'
            group by st.id, st.discount_percent
        ) s
    ) t;

-- Every stage of a plan with its totals. First declared in
-- 29_treatment_plans.sql over the stage numbers of the items; the stages
-- themselves since stage 34 (subtotal_amount: Σ line totals, total_amount:
-- after the stage discount), the new columns come last.
create or replace view public.treatment_plan_stages with (security_invoker = on) as
select
    st.organization_id,
    st.plan_id,
    st.position as stage_no,
    count(i.id)::integer as items_count,
    (count(i.id) filter (where i.done))::integer as done_count,
    coalesce(sum(i.line_total), 0)::bigint as subtotal_amount,
    st.id as stage_id,
    st.name,
    st.status,
    st.discount_percent,
    private.treatment_stage_total(coalesce(sum(i.line_total), 0)::bigint, st.discount_percent) as total_amount
from public.treatment_stages st
    left join public.treatment_plan_items i on i.organization_id = st.organization_id and i.stage_id = st.id
group by st.organization_id, st.plan_id, st.position, st.id, st.name, st.status, st.discount_percent;

--
-- Triggers
--

create or replace trigger treatment_stage_before_write
    before insert or update on public.treatment_stages
    for each row execute function private.handle_treatment_stage_before_write();

create or replace trigger treatment_stage_after_write
    after insert or update or delete on public.treatment_stages
    for each row execute function private.handle_treatment_stage_after_write();

create or replace trigger treatment_plan_first_stage
    after insert on public.treatment_plans
    for each row execute function private.handle_treatment_plan_first_stage();

create or replace trigger seed_treatment_dictionaries
    after insert on public.organizations
    for each row execute function private.handle_organization_treatment_dictionaries();

-- Audit log
create or replace trigger audit_treatment_stage
    after insert or update or delete on public.treatment_stages
    for each row execute function private.audit_row('treatment_stage', 'name,position,status,doctor_id,direction_id,deadline,discount_percent,description');

create or replace trigger audit_treatment_stage_template
    after insert or update or delete on public.treatment_stage_templates
    for each row execute function private.audit_row('treatment_stage_template', 'name,direction_id,description');

--
-- Row Level Security
--

alter table public.treatment_plan_types enable row level security;
alter table public.treatment_directions enable row level security;
alter table public.treatment_stages enable row level security;
alter table public.treatment_stage_templates enable row level security;

-- Dictionaries: every employee reads, whoever configures the clinic writes
create policy "Employees can read" on public.treatment_plan_types for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Configurators can insert" on public.treatment_plan_types for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.can_configure()));
create policy "Configurators can update" on public.treatment_plan_types for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.can_configure()))
    with check (organization_id = (select private.current_organization_id()));
create policy "Configurators can delete" on public.treatment_plan_types for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.can_configure()));

create policy "Employees can read" on public.treatment_directions for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Configurators can insert" on public.treatment_directions for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.can_configure()));
create policy "Configurators can update" on public.treatment_directions for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.can_configure()))
    with check (organization_id = (select private.current_organization_id()));
create policy "Configurators can delete" on public.treatment_directions for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.can_configure()));

-- Stages follow their plan (the sub-query applies the plans policy)
create policy "Stages of visible plans can be read" on public.treatment_stages for select to authenticated
    using (organization_id = (select private.current_organization_id())
        and exists (select 1 from public.treatment_plans p where p.organization_id = treatment_stages.organization_id and p.id = treatment_stages.plan_id));
create policy "Staff can insert stages" on public.treatment_stages for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head', 'manager')
        and exists (select 1 from public.treatment_plans p where p.organization_id = treatment_stages.organization_id and p.id = treatment_stages.plan_id));
create policy "Staff can update stages" on public.treatment_stages for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head', 'manager')
        and exists (select 1 from public.treatment_plans p where p.organization_id = treatment_stages.organization_id and p.id = treatment_stages.plan_id))
    with check (organization_id = (select private.current_organization_id()));
create policy "Staff can delete stages" on public.treatment_stages for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head', 'manager')
        and exists (select 1 from public.treatment_plans p where p.organization_id = treatment_stages.organization_id and p.id = treatment_stages.plan_id));

-- Templates: the staff who write plans (prices: not the integrator)
create policy "Staff can read templates" on public.treatment_stage_templates for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head', 'manager'));
create policy "Staff can insert templates" on public.treatment_stage_templates for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head', 'manager'));
create policy "Staff can update templates" on public.treatment_stage_templates for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head', 'manager'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Staff can delete templates" on public.treatment_stage_templates for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head', 'manager'));

--
-- Grants
--

revoke all on table public.treatment_plan_types from anon;
grant select, insert, update, delete on table public.treatment_plan_types to authenticated;
grant all on table public.treatment_plan_types to service_role;
revoke all on sequence public.treatment_plan_types_id_seq from anon;
grant usage on sequence public.treatment_plan_types_id_seq to authenticated;
grant all on sequence public.treatment_plan_types_id_seq to service_role;

revoke all on table public.treatment_directions from anon;
grant select, insert, update, delete on table public.treatment_directions to authenticated;
grant all on table public.treatment_directions to service_role;
revoke all on sequence public.treatment_directions_id_seq from anon;
grant usage on sequence public.treatment_directions_id_seq to authenticated;
grant all on sequence public.treatment_directions_id_seq to service_role;

revoke all on table public.treatment_stages from anon;
grant select, insert, update, delete on table public.treatment_stages to authenticated;
grant all on table public.treatment_stages to service_role;
revoke all on sequence public.treatment_stages_id_seq from anon;
grant usage on sequence public.treatment_stages_id_seq to authenticated;
grant all on sequence public.treatment_stages_id_seq to service_role;

revoke all on table public.treatment_stage_templates from anon;
grant select, insert, update, delete on table public.treatment_stage_templates to authenticated;
grant all on table public.treatment_stage_templates to service_role;
revoke all on sequence public.treatment_stage_templates_id_seq from anon;
grant usage on sequence public.treatment_stage_templates_id_seq to authenticated;
grant all on sequence public.treatment_stage_templates_id_seq to service_role;

revoke all on table public.treatment_plans_summary from anon;
grant select on table public.treatment_plans_summary to authenticated;
grant all on table public.treatment_plans_summary to service_role;
revoke all on table public.treatment_plan_stages from anon;
grant select on table public.treatment_plan_stages to authenticated;
grant all on table public.treatment_plan_stages to service_role;

revoke all on function private.treatment_plan_subtotal(bigint, bigint) from public;
grant execute on function private.treatment_plan_subtotal(bigint, bigint) to service_role;
revoke all on function private.treatment_stage_at(bigint, bigint, integer) from public;
grant execute on function private.treatment_stage_at(bigint, bigint, integer) to service_role;
revoke all on function private.treatment_stage_progress(bigint, bigint) from public;
grant execute on function private.treatment_stage_progress(bigint, bigint) to service_role;
revoke all on function private.refresh_treatment_plan(bigint, bigint) from public;
grant execute on function private.refresh_treatment_plan(bigint, bigint) to service_role;
revoke all on function private.move_treatment_items_to_stages() from public;
grant execute on function private.move_treatment_items_to_stages() to service_role;
revoke all on function private.seed_treatment_dictionaries(bigint) from public;
grant execute on function private.seed_treatment_dictionaries(bigint) to service_role;
revoke all on function private.handle_treatment_stage_before_write() from public;
revoke all on function private.handle_treatment_stage_after_write() from public;
revoke all on function private.handle_treatment_plan_first_stage() from public;
revoke all on function private.handle_organization_treatment_dictionaries() from public;

revoke all on function public.save_stage_template(bigint, text) from public, anon;
grant execute on function public.save_stage_template(bigint, text) to authenticated, service_role;
revoke all on function public.add_stage_from_template(bigint, bigint) from public, anon;
grant execute on function public.add_stage_from_template(bigint, bigint) to authenticated, service_role;

-- The audit of the plans logs the new header fields
create or replace trigger audit_treatment_plan
    after insert or update or delete on public.treatment_plans
    for each row execute function private.audit_row('treatment_plan', 'name,status,is_main,discount_percent,discount_amount,doctor_id,note,plan_type_id,complaints,insurance_policy');

