--
-- Stage 33: branches «Филиалы» (see supabase/schemas/33_branches.sql).
-- Nullable branch_id on deals, doctors, chairs, visits, tasks and messenger
-- channels: existing clinics keep working unchanged (no default branch).
-- The scope «Мой филиал» for deals and tasks, lead routing by branch, an
-- optional branch filter on the reports.
--

-- New signatures: the old ones go first (a call would be ambiguous)
drop function private.next_responsible(bigint);
drop function private.report_deal_progress(bigint, bigint, bigint, bigint);
drop function public.report_conversion(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint);
drop function public.report_speed(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint);
drop function public.report_lost_reasons(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint);
drop function public.report_money(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint);
drop function public.report_plan_services(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint);

create table public.branches (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    address text,
    phone text,
    is_active boolean not null default true,
    position integer not null default 0,
    created_at timestamp with time zone not null default now(),
    constraint branches_name_not_blank check (btrim(name) <> ''),
    constraint branches_address_length check (address is null or char_length(address) <= 500),
    constraint branches_phone_length check (phone is null or char_length(phone) <= 50)
);

create table public.sales_branches (
    organization_id bigint not null default private.current_organization_id(),
    sales_id bigint not null,
    branch_id bigint not null,
    created_at timestamp with time zone not null default now(),
    constraint sales_branches_pkey primary key (organization_id, sales_id, branch_id)
);

alter table public.branches add constraint branches_organization_id_id_key unique (organization_id, id);

alter table public.deals add column branch_id bigint;
alter table public.doctors add column branch_id bigint;
alter table public.chairs add column branch_id bigint;
alter table public.visits add column branch_id bigint;
alter table public.tasks add column branch_id bigint;
alter table public.messenger_channels add column branch_id bigint;

alter table public.branches
    add constraint branches_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.sales_branches
    add constraint sales_branches_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id) on delete cascade;
alter table public.sales_branches
    add constraint sales_branches_branch_id_fkey foreign key (organization_id, branch_id) references public.branches(organization_id, id) on delete cascade;
-- A branch with deals, visits or tasks cannot be deleted (switch it off);
-- doctors, chairs and channels become «общие»
alter table public.deals
    add constraint deals_branch_id_fkey foreign key (organization_id, branch_id) references public.branches(organization_id, id);
alter table public.visits
    add constraint visits_branch_id_fkey foreign key (organization_id, branch_id) references public.branches(organization_id, id);
alter table public.tasks
    add constraint tasks_branch_id_fkey foreign key (organization_id, branch_id) references public.branches(organization_id, id);
alter table public.doctors
    add constraint doctors_branch_id_fkey foreign key (organization_id, branch_id) references public.branches(organization_id, id) on delete set null (branch_id);
alter table public.chairs
    add constraint chairs_branch_id_fkey foreign key (organization_id, branch_id) references public.branches(organization_id, id) on delete set null (branch_id);
alter table public.messenger_channels
    add constraint messenger_channels_branch_id_fkey foreign key (organization_id, branch_id) references public.branches(organization_id, id) on delete set null (branch_id);

create index branches_organization_id_idx on public.branches using btree (organization_id, position);
create index sales_branches_branch_id_idx on public.sales_branches using btree (organization_id, branch_id);
create index deals_branch_id_idx on public.deals using btree (organization_id, branch_id) where branch_id is not null;
create index visits_branch_id_idx on public.visits using btree (organization_id, branch_id) where branch_id is not null;
create index tasks_branch_id_idx on public.tasks using btree (organization_id, branch_id) where branch_id is not null;

-- Branches the current user works in (stage 33, public.sales_branches): the
-- scope «Мой филиал» ('branch') of the access rights. Declared here because
-- the policies of 05_policies.sql use it; the tables are in 33_branches.sql.
create or replace function private.current_branch_ids() returns bigint[]
    language plpgsql stable security definer
    set search_path to ''
    as $$
begin
  return coalesce((
    select array_agg(sb.branch_id order by sb.branch_id)
    from public.sales s
      join public.sales_branches sb on sb.organization_id = s.organization_id and sb.sales_id = s.id
    where s.user_id = auth.uid() and not s.disabled
      and (s.access_expires_at is null or s.access_expires_at > now())
  ), '{}'::bigint[]);
end;
$$;

-- A branch of the clinic by its id or its name (case-insensitive; an active
-- one first), null when nothing matches: the `branch` field of a website form
CREATE OR REPLACE FUNCTION "private"."find_branch"("org_id" bigint, "value" "text") RETURNS bigint
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  wanted text := nullif(btrim(value), '');
begin
  if wanted is null then
    return null;
  end if;
  return (
    select b.id
    from public.branches b
    where b.organization_id = org_id
      and (lower(btrim(b.name)) = lower(wanted) or (wanted ~ '^[0-9]{1,18}$' and b.id = wanted::bigint))
    order by b.is_active desc, b.position, b.id
    limit 1
  );
end;
$$;

-- The employees a lead of a branch goes to, among the candidates (in their
-- order): those who work in the branch; all the candidates when the lead has
-- no branch or none of them works there
CREATE OR REPLACE FUNCTION "private"."branch_pool"("org_id" bigint, "branch" bigint, "candidates" bigint[]) RETURNS bigint[]
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  in_branch bigint[];
begin
  if branch is null or candidates is null then
    return coalesce(candidates, '{}'::bigint[]);
  end if;
  select coalesce(array_agg(c.sales_id order by c.position), '{}'::bigint[]) into in_branch
  from unnest(candidates) with ordinality as c(sales_id, position)
  where exists (
    select 1 from public.sales_branches sb
    where sb.organization_id = org_id and sb.sales_id = c.sales_id and sb.branch_id = branch
  );
  return case when cardinality(in_branch) > 0 then in_branch else candidates end;
end;
$$;

-- The branch of a deal written without one: the doctor's, else (a new deal)
-- the branch of its responsible, or of the employee creating it, when they
-- work in one branch only. Runs before deal_attribution and deal_before_write
-- (alphabetical order): the distribution knows the branch. An explicit
-- branch, or a branch removed by hand, is kept.
CREATE OR REPLACE FUNCTION "private"."handle_deal_branch"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  responsible bigint;
begin
  if new.branch_id is not null then
    return new;
  end if;
  if tg_op = 'UPDATE' and (old.branch_id is not null or new.doctor_id is not distinct from old.doctor_id) then
    return new;
  end if;
  if new.doctor_id is not null then
    select d.branch_id into new.branch_id
    from public.doctors d
    where d.organization_id = new.organization_id and d.id = new.doctor_id;
  end if;
  if new.branch_id is null and tg_op = 'INSERT' then
    responsible := coalesce(new.sales_id, private.current_sales_id());
    if responsible is not null then
      select min(sb.branch_id) into new.branch_id
      from public.sales_branches sb
      where sb.organization_id = new.organization_id and sb.sales_id = responsible
      having count(*) = 1;
    end if;
  end if;
  return new;
end;
$$;

-- The tasks of a deal follow its branch
CREATE OR REPLACE FUNCTION "private"."handle_deal_branch_changed"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  update public.tasks t
  set branch_id = new.branch_id
  where t.organization_id = new.organization_id and t.deal_id = new.id
    and t.branch_id is distinct from new.branch_id;
  return null;
end;
$$;

-- tasks.branch_id is always the branch of the task's deal (the lists filter
-- on it, the policies of «Мой филиал» read it)
CREATE OR REPLACE FUNCTION "private"."handle_task_branch"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  new.branch_id := (
    select d.branch_id
    from public.deals d
    where d.organization_id = new.organization_id and d.id = new.deal_id
  );
  return new;
end;
$$;

-- The branch of a visit: the one chosen, else of its chair, else of its
-- doctor, else of its deal; moving the visit to another chair or doctor
-- takes their branch
CREATE OR REPLACE FUNCTION "private"."handle_visit_branch"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if tg_op = 'INSERT' and new.branch_id is not null then
    return new;
  end if;
  if tg_op = 'UPDATE' and (
    new.branch_id is distinct from old.branch_id
    or (new.chair_id is not distinct from old.chair_id and new.doctor_id is not distinct from old.doctor_id)
  ) then
    return new;
  end if;
  new.branch_id := coalesce(
    (select c.branch_id from public.chairs c where c.organization_id = new.organization_id and c.id = new.chair_id),
    (select d.branch_id from public.doctors d where d.organization_id = new.organization_id and d.id = new.doctor_id),
    case when tg_op = 'UPDATE' then new.branch_id end,
    (select d.branch_id from public.deals d where d.organization_id = new.organization_id and d.id = new.deal_id)
  );
  return new;
end;
$$;

-- «Привязать к филиалу»: the deals and visits without a branch go to this
-- one (a clinic opening its second address). Owner and head. A system write:
-- no automations, no notifications. Returns { deals, visits }.
CREATE OR REPLACE FUNCTION "public"."assign_branch_to_unassigned"("target_branch_id" bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  moved_deals integer;
  moved_visits integer;
  previous_importing text := current_setting('crm.importing', true);
  previous_notifications text := current_setting('crm.notifications', true);
begin
  if org_id is null or private.current_user_role() is distinct from 'owner'
    and private.current_user_role() is distinct from 'head' then
    raise exception 'Филиалы настраивают владелец и руководитель'
      using errcode = '42501', hint = 'branches_forbidden';
  end if;
  if not exists (select 1 from public.branches b where b.organization_id = org_id and b.id = target_branch_id) then
    raise exception 'Филиал не найден' using errcode = '22023', hint = 'branches_not_found';
  end if;
  perform set_config('crm.importing', 'on', true);
  perform set_config('crm.notifications', 'off', true);
  update public.deals d
  set branch_id = target_branch_id
  where d.organization_id = org_id and d.branch_id is null;
  get diagnostics moved_deals = row_count;
  update public.visits v
  set branch_id = target_branch_id
  where v.organization_id = org_id and v.branch_id is null;
  get diagnostics moved_visits = row_count;
  perform set_config('crm.importing', coalesce(previous_importing, ''), true);
  perform set_config('crm.notifications', coalesce(previous_notifications, ''), true);
  return jsonb_build_object('deals', moved_deals, 'visits', moved_visits);
end;
$$;

CREATE OR REPLACE FUNCTION "public"."handle_deal_before_write"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  new_kind text;
  old_kind text;
  stage_changed boolean;
begin
  if tg_op = 'INSERT' then
    if new.pipeline_id is null then
      select p.id into new.pipeline_id
      from public.pipelines p
      where p.organization_id = new.organization_id
      order by p.is_default desc, p.position, p.id
      limit 1;
    end if;
    if new.stage_id is null then
      select s.id into new.stage_id
      from public.stages s
      where s.pipeline_id = new.pipeline_id
      order by s.position, s.id
      limit 1;
    end if;
    new.paid_amount := 0;
    new.stage_changed_at := now();
    -- A lead coming from outside (no user) is distributed by the clinic
    -- rules, among the employees of its branch (stage 33, set by the
    -- deal_assign_branch trigger before this one); an unsorted one
    -- (18_unsorted_duplicates.sql) waits to be accepted
    if new.sales_id is null and auth.uid() is null and new.unsorted_at is null
      and current_setting('crm.importing', true) is distinct from 'on' then
      new.sales_id := private.next_responsible(new.organization_id, new.branch_id);
    end if;
  else
    new.created_at := old.created_at;
    -- paid_amount is the total of the payments, only their trigger writes it
    if current_setting('crm.sync_paid_amount', true) is distinct from 'on' then
      new.paid_amount := old.paid_amount;
    end if;
    -- A deal never goes back to «Неразобранное»; moving an unsorted lead to
    -- a stage accepts it (see public.accept_unsorted)
    if old.unsorted_at is null
      or new.stage_id is distinct from old.stage_id
      or new.pipeline_id is distinct from old.pipeline_id then
      new.unsorted_at := null;
    end if;
    if (to_jsonb(new) - 'index' - 'updated_at') is distinct from (to_jsonb(old) - 'index' - 'updated_at') then
      new.updated_at := now();
    end if;
    -- Moved to another pipeline: to its first stage, unless the clinic lets
    -- employees choose the stage (organization_settings.pipeline_move_mode)
    -- or an unsorted lead is accepted into a chosen stage
    if new.pipeline_id is distinct from old.pipeline_id and old.unsorted_at is null and coalesce((
      select os.pipeline_move_mode from public.organization_settings os
      where os.organization_id = new.organization_id
    ), 'first_stage') = 'first_stage' then
      select s.id into new.stage_id
      from public.stages s
      where s.pipeline_id = new.pipeline_id
      order by s.position, s.id
      limit 1;
    end if;
  end if;

  select s.kind into new_kind from public.stages s where s.id = new.stage_id;
  stage_changed := tg_op = 'INSERT'
    or new.stage_id is distinct from old.stage_id
    or new.pipeline_id is distinct from old.pipeline_id;

  if tg_op = 'UPDATE' and stage_changed then
    select s.kind into old_kind from public.stages s where s.id = old.stage_id;
    if old_kind = 'lost' then
      raise exception 'Сделка в отказе не возвращается в работу. Для повторного обращения создайте новую сделку.'
        using errcode = 'check_violation', hint = 'deal_lost_locked';
    end if;
    -- The checklist of the stage blocks moving forward (refusing is always
    -- possible; an import moves deals to the stage of the file)
    if new.pipeline_id = old.pipeline_id and new_kind is distinct from 'lost'
      and current_setting('crm.importing', true) is distinct from 'on'
      and old.unsorted_at is null
      and (select s.position from public.stages s where s.id = new.stage_id)
        > (select s.position from public.stages s where s.id = old.stage_id)
      and exists (
        select 1 from public.stage_checklist_items i
        where i.stage_id = old.stage_id
          and not exists (
            select 1 from public.deal_checklist_checks c
            where c.deal_id = old.id and c.item_id = i.id
          )
      )
    then
      raise exception 'Выполните чек-лист этапа «%»', (select s.name from public.stages s where s.id = old.stage_id)
        using errcode = 'check_violation', hint = 'stage_checklist_incomplete';
    end if;
  end if;

  if new_kind = 'lost' and new.lost_reason_id is null then
    raise exception 'Укажите причину отказа'
      using errcode = 'check_violation', hint = 'lost_reason_required';
  end if;

  if stage_changed then
    new.stage_changed_at := now();
    new.closed_at := case when new_kind in ('won', 'lost') then now() else null end;
  end if;

  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."ingest_message"("webhook_token" "text", "message" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint;
  msg_transport text := message ->> 'transport';
  msg_chat_id text := nullif(btrim(message ->> 'chat_id'), '');
  msg_external_id text := nullif(btrim(message ->> 'external_id'), '');
  msg_direction text := coalesce(message ->> 'direction', 'in');
  contact jsonb := coalesce(message -> 'contact', '{}'::jsonb);
  contact_phone text;
  contact_name text;
  source_id bigint;
  found_message public.messages;
  new_channel_id bigint;
  found_patient_id bigint;
  found_deal_id bigint;
  new_message_id bigint;
  created_patient boolean := false;
  created_deal boolean := false;
begin
  if msg_transport = 'telegram_bot' then
    select b.organization_id into org_id
    from public.telegram_bots b
    where b.webhook_token = ingest_message.webhook_token;
  else
    select i.organization_id into org_id
    from public.messenger_integrations i
    where i.webhook_token = ingest_message.webhook_token;
  end if;
  if org_id is null then
    raise exception 'Unknown webhook token' using errcode = '28000';
  end if;
  if msg_transport is null or msg_transport not in ('whatsapp', 'instagram', 'telegram', 'telegram_bot')
    or msg_chat_id is null or msg_direction not in ('in', 'out') then
    raise exception 'Unsupported message' using errcode = '22023';
  end if;

  -- Webhooks are retried: a message is stored once
  if msg_external_id is not null then
    select * into found_message from public.messages m
    where m.organization_id = org_id and m.external_id = msg_external_id;
    if found then
      return jsonb_build_object('message_id', found_message.id, 'patient_id', found_message.patient_id,
        'deal_id', found_message.deal_id, 'duplicate', true);
    end if;
  end if;

  if nullif(btrim(message ->> 'channel_id'), '') is not null then
    insert into public.messenger_channels (organization_id, external_id, transport)
    values (org_id, btrim(message ->> 'channel_id'), msg_transport)
    on conflict (organization_id, external_id) do update set transport = excluded.transport
    returning id into new_channel_id;
  end if;

  select s.id into source_id from public.lead_sources s
  where s.organization_id = org_id
    and s.code = case when msg_transport = 'telegram_bot' then 'telegram' else msg_transport end;

  -- The patient: known chat, else (WhatsApp) the phone number, else a new one
  select c.patient_id into found_patient_id from public.patient_chats c
  where c.organization_id = org_id and c.transport = msg_transport and c.chat_id = msg_chat_id;
  if msg_transport = 'whatsapp' then
    contact_phone := private.normalize_phone(coalesce(nullif(btrim(contact ->> 'phone'), ''), msg_chat_id));
  end if;
  if found_patient_id is null and contact_phone is not null then
    select p.id into found_patient_id from public.patients p
    where p.organization_id = org_id and p.phones @> array[contact_phone]
    order by p.last_seen desc, p.id desc
    limit 1;
  end if;
  if found_patient_id is null then
    contact_name := coalesce(
      nullif(btrim(contact ->> 'name'), ''),
      nullif(btrim(contact ->> 'username'), ''),
      contact_phone,
      msg_chat_id
    );
    insert into public.patients (organization_id, first_name, phone_jsonb, whatsapp, instagram, telegram, source_id)
    values (
      org_id,
      contact_name,
      case when contact_phone is not null
        then jsonb_build_array(jsonb_build_object('number', contact_phone, 'type', 'mobile'))
        else '[]'::jsonb end,
      contact_phone,
      case when msg_transport = 'instagram' then coalesce(nullif(btrim(contact ->> 'username'), ''), msg_chat_id) end,
      case when msg_transport in ('telegram', 'telegram_bot') then nullif(btrim(contact ->> 'username'), '') end,
      source_id
    )
    returning id into found_patient_id;
    created_patient := true;
  end if;
  insert into public.patient_chats (organization_id, patient_id, transport, chat_id, username)
  values (org_id, found_patient_id, msg_transport, msg_chat_id, nullif(btrim(contact ->> 'username'), ''))
  on conflict (organization_id, transport, chat_id) do nothing;

  -- The deal: the most recently updated open one, else a new request
  select d.id into found_deal_id
  from public.deals d
    join public.stages s on s.id = d.stage_id
  where d.organization_id = org_id and d.patient_id = found_patient_id
    and s.kind = 'open' and d.archived_at is null
  order by d.updated_at desc, d.id desc
  limit 1;
  if found_deal_id is null then
    -- A patient's message may open an unsorted lead (clinic setting)
    insert into public.deals (organization_id, patient_id, source_id, unsorted_at, branch_id)
    values (org_id, found_patient_id, source_id,
      case when msg_direction = 'in' then private.unsorted_intake(org_id, source_id) end,
      (select c.branch_id from public.messenger_channels c where c.organization_id = org_id and c.id = new_channel_id))
    returning id into found_deal_id;
    created_deal := true;
  end if;

  insert into public.messages (
    organization_id, patient_id, deal_id, channel_id, transport, chat_id, direction,
    text, content_uri, content_type, status, external_id, sent_at
  ) values (
    org_id, found_patient_id, found_deal_id, new_channel_id, msg_transport, msg_chat_id, msg_direction,
    message ->> 'text',
    nullif(message ->> 'content_uri', ''),
    coalesce(nullif(message ->> 'content_type', ''), 'text'),
    case when msg_direction = 'in' then 'inbound' else 'sent' end,
    msg_external_id,
    coalesce((message ->> 'sent_at')::timestamp with time zone, now())
  )
  returning id into new_message_id;

  update public.patients set last_seen = now()
  where organization_id = org_id and id = found_patient_id;

  return jsonb_build_object('message_id', new_message_id, 'patient_id', found_patient_id,
    'deal_id', found_deal_id, 'created_patient', created_patient, 'created_deal', created_deal,
    'duplicate', false);
end;
$$;

CREATE OR REPLACE FUNCTION "private"."handle_message_created"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  -- An automatic message or a mailing (no author) is not an answer of the clinic
  if new.direction = 'out'
    and ((new.automessage_id is null and new.mailing_message_id is null) or new.sales_id is not null) then
    update public.deals d
    set first_response_at = new.sent_at
    where d.organization_id = new.organization_id and d.id = new.deal_id
      and d.first_response_at is null;
    -- "First to answer takes the lead", among the chosen employees (of the
    -- deal's branch when some of them work there, stage 33)
    if new.sales_id is not null then
      update public.deals d
      set sales_id = new.sales_id
      where d.organization_id = new.organization_id and d.id = new.deal_id
        and d.sales_id is null
        and exists (
          select 1 from public.organization_settings s
          where s.organization_id = new.organization_id
            and s.lead_distribution = 'first_response'
            and new.sales_id = any(private.branch_pool(new.organization_id, d.branch_id,
              case when cardinality(s.lead_distribution_sales_ids) = 0
                then array(select sa.id from public.sales sa where sa.organization_id = new.organization_id and not sa.disabled)
                else s.lead_distribution_sales_ids end))
        );
    end if;
  end if;
  return null;
end;
$$;

CREATE OR REPLACE FUNCTION "private"."next_responsible"("org_id" bigint, "branch" bigint DEFAULT NULL::bigint) RETURNS bigint
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  settings public.organization_settings;
  pool bigint[];
  last_position bigint;
  chosen bigint;
begin
  select * into settings from public.organization_settings s
  where s.organization_id = org_id
  for update;
  if not found or settings.lead_distribution <> 'round_robin' then
    return null;
  end if;
  pool := private.branch_pool(org_id, branch, array(
    select s.id from public.sales s
    where s.organization_id = org_id and not s.disabled and s.id = any(settings.lead_distribution_sales_ids)));
  select c.position into last_position
  from unnest(settings.lead_distribution_sales_ids) with ordinality as c(sales_id, position)
  where c.sales_id = settings.last_distributed_sales_id;
  select s.id into chosen
  from unnest(settings.lead_distribution_sales_ids) with ordinality as c(sales_id, position)
    join public.sales s on s.id = c.sales_id and s.organization_id = org_id and not s.disabled
  where s.id = any(pool)
  order by c.position <= coalesce(last_position, 0), c.position
  limit 1;
  if chosen is not null then
    update public.organization_settings
    set last_distributed_sales_id = chosen
    where organization_id = org_id;
  end if;
  return chosen;
end;
$$;

CREATE OR REPLACE FUNCTION "private"."report_deal_progress"("filter_pipeline_id" bigint, "filter_sales_id" bigint, "filter_source_id" bigint, "filter_doctor_id" bigint, "filter_branch_id" bigint DEFAULT NULL::bigint) RETURNS TABLE("deal_id" bigint, "pipeline_id" bigint, "stage_id" bigint, "stage_kind" "text", "sales_id" bigint, "source_id" bigint, "service_id" bigint, "doctor_id" bigint, "lost_reason_id" bigint, "plan_amount" bigint, "paid_amount" bigint, "created_at" timestamp with time zone, "closed_at" timestamp with time zone, "first_response_at" timestamp with time zone, "archived_at" timestamp with time zone, "reached_position" integer, "reached_appointment" boolean, "reached_visit" boolean, "reached_plan" boolean, "agreed_at" timestamp with time zone, "lost_from_stage_id" bigint)
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $$
#variable_conflict use_column
begin
  return query
  with scope as (
    select d.*, s.kind as stage_kind
    from public.deals d
      join public.stages s on s.id = d.stage_id
    where d.organization_id = private.current_organization_id()
      and (filter_pipeline_id is null or d.pipeline_id = filter_pipeline_id)
      and (filter_sales_id is null or d.sales_id = filter_sales_id)
      and (filter_source_id is null or d.source_id = filter_source_id)
      and (filter_doctor_id is null or d.doctor_id = filter_doctor_id)
      and (filter_branch_id is null or d.branch_id = filter_branch_id)
  ),
  -- Open and won stages entered in the current pipeline, the current one included
  entries as (
    select e.deal_id, s.position, e.created_at
    from public.deal_events e
      join scope d on d.id = e.deal_id
      join public.stages s on s.id = e.to_stage_id and s.pipeline_id = d.pipeline_id
    where e.organization_id = private.current_organization_id()
      and e.type in ('created', 'stage_changed')
      and s.kind <> 'lost'
    union all
    select d.id, s.position, d.stage_changed_at
    from scope d
      join public.stages s on s.id = d.stage_id
    where s.kind <> 'lost'
  ),
  keys as (
    select * from private.report_key_stages()
  ),
  progress as (
    select
      en.deal_id,
      max(en.position) as reached_position,
      min(en.created_at) filter (where en.position >= k.plan_position) as agreed_at
    from entries en
      join scope d on d.id = en.deal_id
      left join keys k on k.pipeline_id = d.pipeline_id
    group by en.deal_id
  )
  select
    d.id, d.pipeline_id, d.stage_id, d.stage_kind, d.sales_id, d.source_id, d.service_id,
    d.doctor_id, d.lost_reason_id, d.plan_amount, d.paid_amount, d.created_at, d.closed_at,
    d.first_response_at, d.archived_at,
    p.reached_position,
    coalesce(p.reached_position >= k.appointment_position, false),
    coalesce(p.reached_position >= k.visit_position, false),
    coalesce(p.reached_position >= k.plan_position, false),
    p.agreed_at,
    case when d.stage_kind = 'lost' then (
      select e.from_stage_id
      from public.deal_events e
      where e.organization_id = d.organization_id and e.deal_id = d.id
        and e.type = 'stage_changed' and e.to_stage_id = d.stage_id
      order by e.created_at desc, e.id desc
      limit 1
    ) end
  from scope d
    left join progress p on p.deal_id = d.id
    left join keys k on k.pipeline_id = d.pipeline_id;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."report_conversion"("period_from" timestamp with time zone DEFAULT NULL::timestamp with time zone, "period_to" timestamp with time zone DEFAULT NULL::timestamp with time zone, "filter_pipeline_id" bigint DEFAULT NULL::bigint, "filter_sales_id" bigint DEFAULT NULL::bigint, "filter_source_id" bigint DEFAULT NULL::bigint, "filter_doctor_id" bigint DEFAULT NULL::bigint, "filter_branch_id" bigint DEFAULT NULL::bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $$
declare
  funnel_pipeline_id bigint;
  report jsonb;
begin
  perform private.report_check_access();
  funnel_pipeline_id := coalesce(filter_pipeline_id, (
    select p.id from public.pipelines p
    where p.organization_id = private.current_organization_id()
    order by p.is_default desc, p.position, p.id
    limit 1
  ));

  with cohort as (
    select *
    from private.report_deal_progress(filter_pipeline_id, filter_sales_id, filter_source_id, filter_doctor_id, filter_branch_id) d
    where (period_from is null or d.created_at >= period_from)
      and (period_to is null or d.created_at < period_to)
  ),
  grouped as (
    select
      grouping(c.source_id) as by_source,
      grouping(c.sales_id) as by_sales,
      grouping(c.doctor_id) as by_doctor,
      c.source_id,
      c.sales_id,
      c.doctor_id,
      count(*) as deals,
      count(*) filter (where c.reached_appointment) as appointment,
      count(*) filter (where c.reached_visit) as visit,
      count(*) filter (where c.reached_plan) as plan,
      count(*) filter (where c.reached_plan and c.paid_amount > 0) as paid,
      count(*) filter (where c.stage_kind = 'won') as won,
      count(*) filter (where c.stage_kind = 'lost') as lost
    from cohort c
    group by grouping sets ((), (c.source_id), (c.sales_id), (c.doctor_id))
  ),
  metrics as (
    select g.*, jsonb_build_object(
      'deals', g.deals, 'appointment', g.appointment, 'visit', g.visit, 'plan', g.plan,
      'paid', g.paid, 'won', g.won, 'lost', g.lost
    ) as row_json
    from grouped g
  )
  select jsonb_build_object(
    'pipeline_id', funnel_pipeline_id,
    'funnel', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'stage_id', s.id, 'name', s.name, 'kind', s.kind, 'color', s.color,
        'deals', (
          select count(*) from cohort c
          where c.pipeline_id = s.pipeline_id
            and case when s.kind = 'open' then c.reached_position >= s.position else c.stage_id = s.id end
        )
      ) order by s.position, s.id), '[]'::jsonb)
      from public.stages s
      where s.pipeline_id = funnel_pipeline_id
    ),
    'totals', (select m.row_json from metrics m where m.by_source = 1 and m.by_sales = 1 and m.by_doctor = 1),
    'by_source', (
      select coalesce(jsonb_agg(
        jsonb_build_object('id', m.source_id, 'name', ls.name) || m.row_json
        order by m.deals desc, ls.position, ls.id
      ), '[]'::jsonb)
      from metrics m
        left join public.lead_sources ls on ls.id = m.source_id
      where m.by_source = 0
    ),
    'by_sales', (
      select coalesce(jsonb_agg(
        jsonb_build_object('id', m.sales_id, 'name', btrim(concat_ws(' ', sa.first_name, sa.last_name))) || m.row_json
        order by m.deals desc, sa.last_name, sa.id
      ), '[]'::jsonb)
      from metrics m
        left join public.sales sa on sa.id = m.sales_id
      where m.by_sales = 0
    ),
    'by_doctor', (
      select coalesce(jsonb_agg(
        jsonb_build_object('id', m.doctor_id, 'name', dr.name) || m.row_json
        order by m.deals desc, dr.position, dr.id
      ), '[]'::jsonb)
      from metrics m
        left join public.doctors dr on dr.id = m.doctor_id
      where m.by_doctor = 0
    )
  ) into report;
  return report;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."report_speed"("period_from" timestamp with time zone DEFAULT NULL::timestamp with time zone, "period_to" timestamp with time zone DEFAULT NULL::timestamp with time zone, "filter_pipeline_id" bigint DEFAULT NULL::bigint, "filter_sales_id" bigint DEFAULT NULL::bigint, "filter_source_id" bigint DEFAULT NULL::bigint, "filter_doctor_id" bigint DEFAULT NULL::bigint, "filter_branch_id" bigint DEFAULT NULL::bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $$
declare
  report jsonb;
begin
  perform private.report_check_access();

  with scope as (
    -- Tasks and messages belong to an employee whoever leads the deal
    select * from private.report_deal_progress(filter_pipeline_id, null, filter_source_id, filter_doctor_id, filter_branch_id)
  ),
  cohort as (
    select * from scope d
    where (period_from is null or d.created_at >= period_from)
      and (period_to is null or d.created_at < period_to)
  ),
  answered as (
    select c.sales_id, extract(epoch from c.first_response_at - c.created_at) as seconds
    from cohort c
    where c.first_response_at is not null and c.first_response_at >= c.created_at
      and (filter_sales_id is null or c.sales_id = filter_sales_id)
  ),
  stays as (
    select
      e.to_stage_id as stage_id,
      e.created_at as entered_at,
      coalesce(
        lead(e.created_at) over (partition by e.deal_id order by e.created_at, e.id),
        case when d.stage_id = e.to_stage_id then now() end
      ) as left_at,
      d.sales_id,
      d.source_id,
      d.doctor_id,
      d.branch_id
    from public.deal_events e
      join public.deals d on d.organization_id = e.organization_id and d.id = e.deal_id
    where e.organization_id = private.current_organization_id()
      and e.type in ('created', 'stage_changed')
  ),
  stage_stats as (
    select st.stage_id, count(*) as stays, round(avg(extract(epoch from st.left_at - st.entered_at))) as avg_seconds
    from stays st
    where st.left_at is not null
      and (period_from is null or st.entered_at >= period_from)
      and (period_to is null or st.entered_at < period_to)
      and (filter_sales_id is null or st.sales_id = filter_sales_id)
      and (filter_source_id is null or st.source_id = filter_source_id)
      and (filter_doctor_id is null or st.doctor_id = filter_doctor_id)
      and (filter_branch_id is null or st.branch_id = filter_branch_id)
    group by st.stage_id
  ),
  staff as (
    select
      sa.id,
      btrim(concat_ws(' ', sa.first_name, sa.last_name)) as name,
      sa.last_name,
      sa.disabled,
      (filter_branch_id is null or exists (
        select 1 from public.sales_branches sb
        where sb.organization_id = sa.organization_id and sb.sales_id = sa.id and sb.branch_id = filter_branch_id
      )) as in_branch,
      (select count(*) from cohort c where c.sales_id = sa.id) as deals,
      (select round(avg(a.seconds)) from answered a where a.sales_id = sa.id) as first_response_seconds,
      (select count(*) from public.tasks t join scope d on d.deal_id = t.deal_id
        where t.organization_id = sa.organization_id and t.sales_id = sa.id
          and (period_from is null or t.created_at >= period_from)
          and (period_to is null or t.created_at < period_to)) as tasks_created,
      (select count(*) from public.tasks t join scope d on d.deal_id = t.deal_id
        where t.organization_id = sa.organization_id and t.sales_id = sa.id
          and t.done_date is not null
          and (period_from is null or t.done_date >= period_from)
          and (period_to is null or t.done_date < period_to)) as tasks_done,
      (select count(*) from public.tasks t join scope d on d.deal_id = t.deal_id
        where t.organization_id = sa.organization_id and t.sales_id = sa.id
          and t.due_date < now()
          and (period_from is null or t.due_date >= period_from)
          and (period_to is null or t.due_date < period_to)) as tasks_due,
      (select count(*) from public.tasks t join scope d on d.deal_id = t.deal_id
        where t.organization_id = sa.organization_id and t.sales_id = sa.id
          and t.due_date < now()
          and (period_from is null or t.due_date >= period_from)
          and (period_to is null or t.due_date < period_to)
          and (t.done_date is null or t.done_date > t.due_date)) as tasks_overdue,
      (select count(*) from public.messages m join scope d on d.deal_id = m.deal_id
        where m.organization_id = sa.organization_id and m.sales_id = sa.id and m.direction = 'out'
          and (period_from is null or m.sent_at >= period_from)
          and (period_to is null or m.sent_at < period_to)) as messages_sent,
      (select count(*) from scope d
        where d.sales_id = sa.id and d.stage_kind = 'open' and d.archived_at is null) as open_deals,
      (select count(*) from scope d
        where d.sales_id = sa.id and d.stage_kind = 'open' and d.archived_at is null
          and not exists (
            select 1 from public.tasks t
            where t.organization_id = sa.organization_id and t.deal_id = d.deal_id and t.done_date is null
          )) as deals_without_task
    from public.sales sa
    where sa.organization_id = private.current_organization_id()
      and (filter_sales_id is null or sa.id = filter_sales_id)
  )
  select jsonb_build_object(
    'first_response', (
      select jsonb_build_object('deals', count(*), 'avg_seconds', round(avg(a.seconds)))
      from answered a
    ),
    'stages', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'stage_id', s.id, 'name', s.name, 'color', s.color,
        'pipeline_id', p.id, 'pipeline_name', p.name,
        'stays', coalesce(ss.stays, 0), 'avg_seconds', ss.avg_seconds
      ) order by p.position, p.id, s.position, s.id), '[]'::jsonb)
      from public.stages s
        join public.pipelines p on p.id = s.pipeline_id
        left join stage_stats ss on ss.stage_id = s.id
      where s.organization_id = private.current_organization_id()
        and s.kind = 'open'
        and (filter_pipeline_id is null or s.pipeline_id = filter_pipeline_id)
    ),
    'by_sales', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', st.id, 'name', st.name, 'deals', st.deals,
        'first_response_seconds', st.first_response_seconds,
        'tasks_created', st.tasks_created, 'tasks_done', st.tasks_done,
        'tasks_due', st.tasks_due, 'tasks_overdue', st.tasks_overdue,
        'messages_sent', st.messages_sent,
        'open_deals', st.open_deals, 'deals_without_task', st.deals_without_task
      ) order by st.deals desc, st.last_name, st.id), '[]'::jsonb)
      from staff st
      where (not st.disabled and st.in_branch)
        or st.deals + st.tasks_created + st.tasks_done + st.messages_sent + st.open_deals > 0
    )
  ) into report;
  return report;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."report_lost_reasons"("period_from" timestamp with time zone DEFAULT NULL::timestamp with time zone, "period_to" timestamp with time zone DEFAULT NULL::timestamp with time zone, "filter_pipeline_id" bigint DEFAULT NULL::bigint, "filter_sales_id" bigint DEFAULT NULL::bigint, "filter_source_id" bigint DEFAULT NULL::bigint, "filter_doctor_id" bigint DEFAULT NULL::bigint, "filter_branch_id" bigint DEFAULT NULL::bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $$
declare
  report jsonb;
begin
  perform private.report_check_access();

  with lost as (
    select *
    from private.report_deal_progress(filter_pipeline_id, filter_sales_id, filter_source_id, filter_doctor_id, filter_branch_id) d
    where d.stage_kind = 'lost'
      and (period_from is null or d.closed_at >= period_from)
      and (period_to is null or d.closed_at < period_to)
  )
  select jsonb_build_object(
    'totals', (
      select jsonb_build_object('deals', count(*), 'plan_amount', coalesce(sum(l.plan_amount), 0))
      from lost l
    ),
    'by_reason', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', r.lost_reason_id, 'name', lr.name, 'deals', r.deals, 'plan_amount', r.plan_amount
      ) order by r.deals desc, lr.position, lr.id), '[]'::jsonb)
      from (
        select l.lost_reason_id, count(*) as deals, sum(l.plan_amount) as plan_amount
        from lost l
        group by l.lost_reason_id
      ) r
        left join public.lost_reasons lr on lr.id = r.lost_reason_id
    ),
    'by_stage', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', r.lost_from_stage_id, 'name', s.name, 'pipeline_name', p.name,
        'deals', r.deals, 'plan_amount', r.plan_amount
      ) order by p.position, p.id, s.position, s.id), '[]'::jsonb)
      from (
        select l.lost_from_stage_id, count(*) as deals, sum(l.plan_amount) as plan_amount
        from lost l
        group by l.lost_from_stage_id
      ) r
        left join public.stages s on s.id = r.lost_from_stage_id
        left join public.pipelines p on p.id = s.pipeline_id
    )
  ) into report;
  return report;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."report_money"("period_from" timestamp with time zone DEFAULT NULL::timestamp with time zone, "period_to" timestamp with time zone DEFAULT NULL::timestamp with time zone, "filter_pipeline_id" bigint DEFAULT NULL::bigint, "filter_sales_id" bigint DEFAULT NULL::bigint, "filter_source_id" bigint DEFAULT NULL::bigint, "filter_doctor_id" bigint DEFAULT NULL::bigint, "filter_branch_id" bigint DEFAULT NULL::bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $$
declare
  clinic_tz text;
  first_day date;
  after_last_day date;
  report jsonb;
begin
  perform private.report_check_access();
  select o.timezone into clinic_tz
  from public.organizations o
  where o.id = private.current_organization_id();
  first_day := (period_from at time zone coalesce(clinic_tz, 'Asia/Almaty'))::date;
  after_last_day := (period_to at time zone coalesce(clinic_tz, 'Asia/Almaty'))::date;

  with per_deal as (
    select
      d.deal_id,
      d.service_id,
      d.sales_id,
      d.doctor_id,
      d.plan_amount,
      coalesce(
        d.agreed_at is not null
          and (period_from is null or d.agreed_at >= period_from)
          and (period_to is null or d.agreed_at < period_to),
        false
      ) as agreed,
      coalesce((
        select sum(p.amount)
        from public.deal_payments p
        where p.organization_id = private.current_organization_id() and p.deal_id = d.deal_id
          and (first_day is null or p.paid_at >= first_day)
          and (after_last_day is null or p.paid_at < after_last_day)
      ), 0) as paid,
      coalesce((
        select sum(p.amount)
        from public.deal_payments p
        where p.organization_id = private.current_organization_id() and p.deal_id = d.deal_id
          and p.kind = 'prepayment'
          and (first_day is null or p.paid_at >= first_day)
          and (after_last_day is null or p.paid_at < after_last_day)
      ), 0) as prepaid
    from private.report_deal_progress(filter_pipeline_id, filter_sales_id, filter_source_id, filter_doctor_id, filter_branch_id) d
  ),
  grouped as (
    select
      grouping(pd.service_id) as by_service,
      grouping(pd.sales_id) as by_sales,
      grouping(pd.doctor_id) as by_doctor,
      pd.service_id,
      pd.sales_id,
      pd.doctor_id,
      count(*) filter (where pd.agreed) as agreed_deals,
      coalesce(sum(pd.plan_amount) filter (where pd.agreed), 0) as agreed_amount,
      coalesce(sum(pd.paid), 0) as paid_amount,
      coalesce(sum(pd.prepaid), 0) as prepaid_amount,
      count(*) filter (where pd.paid > 0) as paying_deals
    from per_deal pd
    where pd.agreed or pd.paid > 0
    group by grouping sets ((), (pd.service_id), (pd.sales_id), (pd.doctor_id))
  ),
  metrics as (
    select g.*, jsonb_build_object(
      'agreed_deals', g.agreed_deals,
      'agreed_amount', g.agreed_amount,
      'paid_amount', g.paid_amount,
      'prepaid_amount', g.prepaid_amount,
      'paying_deals', g.paying_deals,
      'average_check', case when g.paying_deals > 0 then round(g.paid_amount / g.paying_deals) end
    ) as row_json
    from grouped g
  )
  select jsonb_build_object(
    'totals', (select m.row_json from metrics m where m.by_service = 1 and m.by_sales = 1 and m.by_doctor = 1),
    'by_service', (
      select coalesce(jsonb_agg(
        jsonb_build_object('id', m.service_id, 'name', sv.name) || m.row_json
        order by m.paid_amount desc, m.agreed_amount desc, sv.position, sv.id
      ), '[]'::jsonb)
      from metrics m
        left join public.services sv on sv.id = m.service_id
      where m.by_service = 0
    ),
    'by_sales', (
      select coalesce(jsonb_agg(
        jsonb_build_object('id', m.sales_id, 'name', btrim(concat_ws(' ', sa.first_name, sa.last_name))) || m.row_json
        order by m.paid_amount desc, m.agreed_amount desc, sa.last_name, sa.id
      ), '[]'::jsonb)
      from metrics m
        left join public.sales sa on sa.id = m.sales_id
      where m.by_sales = 0
    ),
    'by_doctor', (
      select coalesce(jsonb_agg(
        jsonb_build_object('id', m.doctor_id, 'name', dr.name) || m.row_json
        order by m.paid_amount desc, m.agreed_amount desc, dr.position, dr.id
      ), '[]'::jsonb)
      from metrics m
        left join public.doctors dr on dr.id = m.doctor_id
      where m.by_doctor = 0
    )
  ) into report;
  return report;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."ingest_lead"("token" "text", "lead" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint;
  lead_name text := nullif(btrim(lead ->> 'name'), '');
  lead_phone text := private.normalize_phone(nullif(btrim(lead ->> 'phone'), ''));
  lead_source text := nullif(btrim(lead ->> 'source'), '');
  lead_service text := nullif(btrim(lead ->> 'service'), '');
  lead_comment text := nullif(btrim(lead ->> 'comment'), '');
  lead_referrer text := left(nullif(btrim(lead ->> 'referrer'), ''), 2000);
  lead_landing_page text := left(nullif(btrim(lead ->> 'landing_page'), ''), 2000);
  lead_branch text := nullif(btrim(coalesce(lead ->> 'branch', lead ->> 'branch_id')), '');
  found_branch_id bigint;
  utm jsonb;
  payload jsonb;
  hash text;
  previous public.lead_submissions;
  found_source public.lead_sources;
  mapped_source_id bigint;
  found_service_id bigint;
  found_patient_id bigint;
  found_deal_id bigint;
  created_patient boolean := false;
  created_deal boolean := false;
  note_text text;
  new_note_id bigint;
  new_submission_id bigint;
begin
  select i.organization_id into org_id
  from public.lead_integrations i
  where i.token = ingest_lead.token;
  if org_id is null then
    raise exception 'Unknown lead token' using errcode = '28000';
  end if;
  if jsonb_typeof(lead) is distinct from 'object'
    or lead_phone is null or length(lead_phone) not between 11 and 16 then
    raise exception 'A lead needs a phone number' using errcode = '22023';
  end if;

  -- UTM tags: an utm object and/or top-level utm_* fields
  select coalesce(jsonb_object_agg(e.key, e.value), '{}'::jsonb) into utm
  from (
    select u.key, u.value
    from jsonb_each_text(case when jsonb_typeof(lead -> 'utm') = 'object' then lead -> 'utm' else '{}'::jsonb end) as u
    union
    select u.key, u.value
    from jsonb_each_text(lead) as u
    where u.key like 'utm\_%'
  ) as e
  where nullif(btrim(e.value), '') is not null;
  payload := jsonb_strip_nulls(jsonb_build_object(
    'name', lead_name, 'phone', lead_phone, 'source', lead_source,
    'service', lead_service, 'comment', lead_comment,
    'utm', case when utm <> '{}'::jsonb then utm end,
    'referrer', lead_referrer, 'landing_page', lead_landing_page,
    'branch', lead_branch
  ));
  hash := md5(payload::text);
  found_branch_id := private.find_branch(org_id, lead_branch);

  -- Forms are often submitted twice: the same request within 5 minutes is
  -- stored once (concurrent submissions of a phone wait for each other)
  perform pg_advisory_xact_lock(hashtextextended(org_id::text || ':' || lead_phone, 0));
  select * into previous from public.lead_submissions s
  where s.organization_id = org_id and s.phone = lead_phone and s.payload_hash = hash
    and s.created_at > now() - interval '5 minutes'
  order by s.created_at desc
  limit 1;
  if found then
    return jsonb_build_object('lead_id', previous.id, 'patient_id', previous.patient_id,
      'deal_id', previous.deal_id, 'duplicate', true);
  end if;

  -- The advert that brought the click names the source
  mapped_source_id := private.utm_lead_source(org_id, utm ->> 'utm_source');
  if mapped_source_id is not null then
    select * into found_source from public.lead_sources s
    where s.organization_id = org_id and s.id = mapped_source_id;
  else
    select * into found_source from public.lead_sources s
    where s.organization_id = org_id
      and (lower(s.code) = lower(coalesce(lead_source, 'website')) or lower(s.name) = lower(coalesce(lead_source, 'website')))
    order by s.is_archived, s.is_system desc, s.position, s.id
    limit 1;
  end if;
  if not found then
    select * into found_source from public.lead_sources s
    where s.organization_id = org_id and s.code = 'website';
  end if;

  if lead_service is not null then
    select s.id into found_service_id from public.services s
    where s.organization_id = org_id and lower(btrim(s.name)) = lower(lead_service)
    order by s.is_archived, s.position, s.id
    limit 1;
  end if;

  -- The patient: by phone, else a new one
  select p.id into found_patient_id from public.patients p
  where p.organization_id = org_id and p.phones @> array[lead_phone]
  order by p.last_seen desc, p.id desc
  limit 1;
  if found_patient_id is null then
    insert into public.patients (organization_id, first_name, phone_jsonb, source_id)
    values (
      org_id,
      coalesce(lead_name, lead_phone),
      jsonb_build_array(jsonb_build_object('number', lead_phone, 'type', 'mobile')),
      found_source.id
    )
    returning id into found_patient_id;
    created_patient := true;
  end if;

  -- The deal: the most recently updated open one, else a new request
  select d.id into found_deal_id
  from public.deals d
    join public.stages s on s.id = d.stage_id
  where d.organization_id = org_id and d.patient_id = found_patient_id
    and s.kind = 'open' and d.archived_at is null
  order by d.updated_at desc, d.id desc
  limit 1;
  if found_deal_id is null then
    insert into public.deals (organization_id, patient_id, source_id, service_id, unsorted_at,
      utm_source, utm_medium, utm_campaign, utm_content, utm_term, referrer, landing_page, branch_id)
    values (org_id, found_patient_id, found_source.id, found_service_id,
      private.unsorted_intake(org_id, found_source.id),
      utm ->> 'utm_source', utm ->> 'utm_medium', utm ->> 'utm_campaign',
      utm ->> 'utm_content', utm ->> 'utm_term', lead_referrer, lead_landing_page, found_branch_id)
    returning id into found_deal_id;
    created_deal := true;
  else
    if found_service_id is not null then
      update public.deals
      set service_id = found_service_id
      where organization_id = org_id and id = found_deal_id and service_id is null;
    end if;
    -- First touch: an open deal keeps the tags it came with
    if utm <> '{}'::jsonb or lead_referrer is not null or lead_landing_page is not null then
      update public.deals
      set utm_source = utm ->> 'utm_source',
          utm_medium = utm ->> 'utm_medium',
          utm_campaign = utm ->> 'utm_campaign',
          utm_content = utm ->> 'utm_content',
          utm_term = utm ->> 'utm_term',
          referrer = lead_referrer,
          landing_page = lead_landing_page
      where organization_id = org_id and id = found_deal_id
        and utm_source is null and utm_medium is null and utm_campaign is null
        and utm_content is null and utm_term is null
        and referrer is null and landing_page is null;
    end if;
  end if;

  note_text := concat_ws(E'\n',
    case when created_deal then 'Заявка' else 'Повторная заявка' end
      || ' (' || coalesce(found_source.name, 'Сайт') || ')',
    'Имя: ' || lead_name,
    'Телефон: ' || lead_phone,
    case when lead_source is not null and lower(lead_source) not in (lower(found_source.name), lower(coalesce(found_source.code, '')))
      then 'Источник: ' || lead_source end,
    'Услуга: ' || lead_service,
    'Комментарий: ' || lead_comment,
    (select string_agg(u.key || ': ' || u.value, E'\n' order by u.key) from jsonb_each_text(utm) as u),
    'Страница: ' || lead_landing_page,
    'Переход с: ' || lead_referrer,
    'Филиал: ' || (select b.name from public.branches b where b.organization_id = org_id and b.id = found_branch_id)
  );
  insert into public.deal_notes (organization_id, deal_id, type, text, date)
  values (org_id, found_deal_id, 'lead', note_text, now())
  returning id into new_note_id;

  update public.patients set last_seen = now()
  where organization_id = org_id and id = found_patient_id;

  insert into public.lead_submissions (organization_id, phone, payload_hash, payload, patient_id, deal_id)
  values (org_id, lead_phone, hash, payload, found_patient_id, found_deal_id)
  returning id into new_submission_id;

  return jsonb_build_object('lead_id', new_submission_id, 'patient_id', found_patient_id,
    'deal_id', found_deal_id, 'note_id', new_note_id, 'created_patient', created_patient,
    'created_deal', created_deal, 'duplicate', false);
end;
$$;

CREATE OR REPLACE FUNCTION "public"."ingest_call"("webhook_token" "text", "provider" "text", "call" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint;
  call_provider text := lower(btrim(coalesce(ingest_call.provider, '')));
  call_external_id text := nullif(btrim(call ->> 'call_id'), '');
  call_direction text := coalesce(nullif(btrim(call ->> 'direction'), ''), 'in');
  call_status text := nullif(btrim(call ->> 'status'), '');
  call_phone text := private.normalize_phone(nullif(btrim(call ->> 'phone'), ''));
  call_extension text := nullif(btrim(call ->> 'extension'), '');
  call_started_at timestamp with time zone := nullif(btrim(call ->> 'started_at'), '')::timestamp with time zone;
  call_duration integer := greatest(coalesce(nullif(btrim(call ->> 'duration'), '')::numeric, 0), 0)::integer;
  call_record_url text := nullif(btrim(call ->> 'record_url'), '');
  call_line text := private.normalize_phone(nullif(btrim(call ->> 'line'), ''));
  call_branch_id bigint;
  employee_id bigint;
  call_source_id bigint;
  found_call public.calls;
  new_status text;
  found_patient_id bigint;
  found_deal_id bigint;
  new_call_id bigint;
  created_patient boolean := false;
  created_deal boolean := false;
  created_task boolean := false;
begin
  select i.organization_id into org_id
  from public.telephony_integrations i
  where i.webhook_token = ingest_call.webhook_token;
  if org_id is null then
    raise exception 'Unknown webhook token' using errcode = '28000';
  end if;
  if call_provider not in ('binotel', 'zadarma', 'mango', 'sipuni', 'generic')
    or call_external_id is null
    or call_direction not in ('in', 'out')
    or coalesce(call_status, 'in_progress') not in ('in_progress', 'answered', 'missed') then
    raise exception 'Unsupported call' using errcode = '22023';
  end if;

  update public.telephony_integrations
  set last_event_at = now()
  where organization_id = org_id;

  -- The events of one call may arrive at the same time
  perform pg_advisory_xact_lock(hashtextextended(format('call:%s:%s:%s', org_id, call_provider, call_external_id), 0));

  if call_extension is not null then
    select s.id into employee_id
    from public.sales s
    where s.organization_id = org_id and s.phone_extension = call_extension and not s.disabled;
  end if;

  select * into found_call
  from public.calls c
  where c.organization_id = org_id and c.provider = call_provider and c.external_id = call_external_id;

  if found then
    -- A final status replaces "in progress", never the other way round
    new_status := case
      when call_status in ('answered', 'missed') then call_status
      else found_call.status
    end;
    update public.calls c
    set status = new_status,
        duration_seconds = greatest(c.duration_seconds, call_duration),
        recording_url = coalesce(call_record_url, c.recording_url),
        sales_id = coalesce(employee_id, c.sales_id),
        extension = coalesce(call_extension, c.extension),
        phone = coalesce(c.phone, call_phone)
    where c.id = found_call.id;
    if new_status = 'missed' and found_call.status <> 'missed' and found_call.direction = 'in'
      and found_call.deal_id is not null then
      insert into public.tasks (organization_id, deal_id, type, text, due_date, sales_id)
      select org_id, d.id, 'call', 'Перезвонить', now(), d.sales_id
      from public.deals d
      where d.organization_id = org_id and d.id = found_call.deal_id;
      created_task := true;
    end if;
    return jsonb_build_object('call_id', found_call.id, 'patient_id', found_call.patient_id,
      'deal_id', found_call.deal_id, 'created_patient', false, 'created_deal', false,
      'created_task', created_task, 'duplicate', true);
  end if;

  -- A new call needs the patient's number (a recording of an unknown call,
  -- a hidden number: nothing to attach it to)
  if call_phone is null then
    return jsonb_build_object('ignored', true);
  end if;

  -- Two new calls from one new number must not create two patients
  perform pg_advisory_xact_lock(hashtextextended(format('phone:%s:%s', org_id, call_phone), 0));

  select s.id into call_source_id from public.lead_sources s
  where s.organization_id = org_id and s.code = 'call';
  if call_source_id is null then
    insert into public.lead_sources (organization_id, name, code, is_system, position)
    select org_id, 'Звонок', 'call', true, coalesce(max(s.position) + 1, 0)
    from public.lead_sources s
    where s.organization_id = org_id
    returning id into call_source_id;
  end if;

  select p.id into found_patient_id from public.patients p
  where p.organization_id = org_id and p.phones @> array[call_phone]
  order by p.last_seen desc, p.id desc
  limit 1;
  if found_patient_id is null then
    insert into public.patients (organization_id, first_name, phone_jsonb, source_id)
    values (
      org_id,
      coalesce(nullif(btrim(call ->> 'name'), ''), call_phone),
      jsonb_build_array(jsonb_build_object('number', call_phone, 'type', 'mobile')),
      call_source_id
    )
    returning id into found_patient_id;
    created_patient := true;
  end if;

  -- The deal: the most recently updated open one, else a new request. An
  -- outgoing call to a new number belongs to the employee who made it; an
  -- incoming one is distributed by the clinic rules (handle_deal_before_write).
  select d.id into found_deal_id
  from public.deals d
    join public.stages s on s.id = d.stage_id
  where d.organization_id = org_id and d.patient_id = found_patient_id
    and s.kind = 'open' and d.archived_at is null
  order by d.updated_at desc, d.id desc
  limit 1;
  if found_deal_id is null then
    call_branch_id := coalesce(
      (select b.id from public.branches b
       where b.organization_id = org_id and call_line is not null
         and private.normalize_phone(b.phone) = call_line
       order by b.is_active desc, b.position, b.id
       limit 1),
      (select min(sb.branch_id) from public.sales_branches sb
       where sb.organization_id = org_id and sb.sales_id = employee_id
       having count(*) = 1));
    -- An incoming call may open an unsorted lead (clinic setting)
    insert into public.deals (organization_id, patient_id, source_id, sales_id, unsorted_at, branch_id)
    values (org_id, found_patient_id, call_source_id, case when call_direction = 'out' then employee_id end,
      case when call_direction = 'in' then private.unsorted_intake(org_id, call_source_id) end,
      call_branch_id)
    returning id into found_deal_id;
    created_deal := true;
  end if;

  insert into public.calls (
    organization_id, patient_id, deal_id, direction, duration_seconds, called_at,
    sales_id, external_id, recording_url, provider, status, phone, extension
  ) values (
    org_id, found_patient_id, found_deal_id, call_direction, call_duration,
    -- Unknown start (a PBX in another time zone): now, minus the talk of a finished call
    coalesce(call_started_at, now() - make_interval(secs => call_duration)),
    employee_id, call_external_id, call_record_url, call_provider,
    coalesce(call_status, 'in_progress'), call_phone, call_extension
  )
  returning id into new_call_id;

  if call_status = 'missed' and call_direction = 'in' then
    insert into public.tasks (organization_id, deal_id, type, text, due_date, sales_id)
    select org_id, d.id, 'call', 'Перезвонить', now(), d.sales_id
    from public.deals d
    where d.organization_id = org_id and d.id = found_deal_id;
    created_task := true;
  end if;

  update public.patients set last_seen = now()
  where organization_id = org_id and id = found_patient_id;

  return jsonb_build_object('call_id', new_call_id, 'patient_id', found_patient_id,
    'deal_id', found_deal_id, 'created_patient', created_patient, 'created_deal', created_deal,
    'created_task', created_task, 'duplicate', false);
end;
$$;

CREATE OR REPLACE FUNCTION "private"."deal_audience"("deal" "public"."deals") RETURNS bigint[]
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  settings public.organization_settings;
  chosen bigint[];
begin
  if deal.sales_id is not null and exists (
    select 1 from public.sales s
    where s.organization_id = deal.organization_id and s.id = deal.sales_id and not s.disabled
  ) then
    return array[deal.sales_id];
  end if;
  select * into settings from public.organization_settings os where os.organization_id = deal.organization_id;
  if deal.sales_id is null and settings.lead_distribution = 'first_response' then
    select coalesce(array_agg(s.id order by s.id), '{}'::bigint[]) into chosen
    from public.sales s
    where s.organization_id = deal.organization_id and not s.disabled
      and (cardinality(settings.lead_distribution_sales_ids) = 0 or s.id = any(settings.lead_distribution_sales_ids));
    chosen := private.branch_pool(deal.organization_id, deal.branch_id, chosen);
    if cardinality(chosen) > 0 then
      return chosen;
    end if;
  end if;
  return private.clinic_managers(deal.organization_id);
end;
$$;

CREATE OR REPLACE FUNCTION "private"."deal_visible"("deal" "public"."deals") RETURNS boolean
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  scope text := private.access_scope('deals', 'view');
begin
  return coalesce(
    deal.id is not null
    and deal.organization_id = private.current_organization_id()
    and (
      scope = 'all'
      or (scope in ('branch', 'own', 'own_and_unassigned') and deal.sales_id = private.current_sales_id())
      or (scope = 'own_and_unassigned' and deal.sales_id is null)
      or (scope = 'branch' and (deal.branch_id is null or deal.branch_id = any(private.current_branch_ids())))
    ),
    false);
end;
$$;

CREATE OR REPLACE FUNCTION "public"."accept_unsorted"("lead_deal_id" bigint, "target_stage_id" bigint DEFAULT NULL::bigint, "target_sales_id" bigint DEFAULT NULL::bigint) RETURNS bigint
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  lead_row public.deals;
  stage_row public.stages;
  responsible bigint := target_sales_id;
begin
  select * into lead_row from public.deals d
  where d.id = lead_deal_id and d.organization_id = private.current_organization_id();
  if not found then
    raise exception 'Сделка не найдена' using errcode = 'P0002';
  end if;
  if lead_row.unsorted_at is null then
    raise exception 'Заявка уже разобрана' using errcode = 'check_violation', hint = 'deal_not_unsorted';
  end if;
  if target_stage_id is null then
    select * into stage_row from public.stages s
    where s.pipeline_id = lead_row.pipeline_id and s.kind = 'open'
    order by s.position, s.id
    limit 1;
  else
    select * into stage_row from public.stages s
    where s.id = target_stage_id and s.organization_id = lead_row.organization_id;
  end if;
  if stage_row.id is null or stage_row.kind <> 'open' then
    raise exception 'Выберите этап в работе' using errcode = 'check_violation', hint = 'unsorted_stage_not_open';
  end if;
  if responsible is null then
    responsible := coalesce(lead_row.sales_id, private.next_responsible(lead_row.organization_id, lead_row.branch_id));
  elsif not exists (
    select 1 from public.sales s
    where s.organization_id = lead_row.organization_id and s.id = responsible and not s.disabled
  ) then
    raise exception 'Сотрудник не найден' using errcode = 'check_violation', hint = 'unsorted_sales_unknown';
  end if;
  update public.deals d
  set unsorted_at = null,
      pipeline_id = stage_row.pipeline_id,
      stage_id = stage_row.id,
      sales_id = responsible,
      stage_changed_at = now()
  where d.id = lead_row.id;
  return lead_row.id;
end;
$$;

CREATE OR REPLACE FUNCTION "private"."apply_stage_trigger_action"("trigger_row" "public"."stage_triggers", "deal" "public"."deals") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := deal.organization_id;
  new_sales_id bigint;
  new_id bigint;
  zone text;
  template_body text;
  rendered text;
  old_value jsonb;
  queued integer;
begin
  case trigger_row.action
  when 'move_stage' then
    if deal.stage_id = trigger_row.target_stage_id then
      return jsonb_build_object('unchanged', true);
    end if;
    update public.deals d
    set stage_id = trigger_row.target_stage_id
    where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('from_stage_id', deal.stage_id, 'to_stage_id', trigger_row.target_stage_id);

  when 'set_responsible' then
    new_sales_id := coalesce(trigger_row.target_sales_id, private.next_responsible(org_id, deal.branch_id));
    if new_sales_id is null then
      raise exception 'Некому назначить: распределение по очереди не настроено' using errcode = '22023';
    end if;
    if exists (select 1 from public.sales s where s.id = new_sales_id and s.disabled) then
      raise exception 'Сотрудник отключён' using errcode = '22023';
    end if;
    if deal.sales_id is not distinct from new_sales_id then
      return jsonb_build_object('unchanged', true);
    end if;
    update public.deals d
    set sales_id = new_sales_id
    where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('from_sales_id', deal.sales_id, 'to_sales_id', new_sales_id);

  when 'add_tag' then
    if trigger_row.tag_id = any(deal.tags) then
      return jsonb_build_object('unchanged', true, 'tag_id', trigger_row.tag_id);
    end if;
    update public.deals d
    set tags = array_append(d.tags, trigger_row.tag_id)
    where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('tag_id', trigger_row.tag_id);

  when 'remove_tag' then
    if not trigger_row.tag_id = any(deal.tags) then
      return jsonb_build_object('unchanged', true, 'tag_id', trigger_row.tag_id);
    end if;
    update public.deals d
    set tags = array_remove(d.tags, trigger_row.tag_id)
    where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('tag_id', trigger_row.tag_id);

  when 'create_task' then
    -- Same as the task rules (private.create_rule_tasks)
    insert into public.tasks (organization_id, deal_id, type, text, due_date, sales_id)
    values (org_id, deal.id, trigger_row.task_type, btrim(trigger_row.task_text),
      now() + make_interval(mins => trigger_row.task_due_minutes), deal.sales_id)
    returning id into new_id;
    return jsonb_build_object('task_id', new_id);

  when 'send_template' then
    -- The stage 6 queue: "show first" becomes the task with the text and the
    -- «Отправить» button right away; "auto" is sent by the dispatcher
    -- (quiet hours apply, leaving the stage cancels it)
    if coalesce(trigger_row.message_mode, 'auto') = 'confirm' then
      select t.body into template_body from public.message_templates t
      where t.organization_id = org_id and t.id = trigger_row.template_id;
      rendered := private.render_template(template_body, private.automessage_vars(deal));
      insert into public.automessages (organization_id, deal_id, rule_id, template_id, stage_id, timing, send_at, status, text, processed_at)
      values (org_id, deal.id, null, trigger_row.template_id, deal.stage_id, 'after_stage', now(), 'awaiting', rendered, now())
      returning id into new_id;
      insert into public.tasks (organization_id, deal_id, type, text, due_date, sales_id, automessage_id)
      values (org_id, deal.id, 'message', rendered, now(), deal.sales_id, new_id);
    else
      select o.timezone into zone from public.organizations o where o.id = org_id;
      insert into public.automessages (organization_id, deal_id, rule_id, template_id, stage_id, timing, send_at)
      values (org_id, deal.id, null, trigger_row.template_id, deal.stage_id, 'after_stage',
        private.automessage_send_time(now(), zone))
      returning id into new_id;
    end if;
    return jsonb_build_object('automessage_id', new_id, 'template_id', trigger_row.template_id,
      'mode', coalesce(trigger_row.message_mode, 'auto'));

  when 'send_webhook' then
    queued := private.enqueue_webhook(org_id, 'automation',
      jsonb_build_object('deal_id', deal.id, 'patient_id', deal.patient_id,
        'trigger', jsonb_build_object('id', trigger_row.id, 'name', trigger_row.name, 'event', trigger_row.event),
        'deal', private.deal_json(deal)),
      trigger_row.webhook_id);
    if queued = 0 then
      raise exception 'Вебхук выключен' using errcode = '22023';
    end if;
    return jsonb_build_object('webhook_id', trigger_row.webhook_id);

  when 'start_salesbot' then
    -- «Запустить салесбот» (26_salesbot.sql): replaces the bot of the deal
    new_id := private.salesbot_start(trigger_row.salesbot_id, deal.id, 'pipeline');
    if new_id is null then
      raise exception 'Бот не запущен' using errcode = '22023';
    end if;
    return jsonb_build_object('salesbot_id', trigger_row.salesbot_id, 'session_id', new_id);

  when 'set_field' then
    old_value := to_jsonb(deal) -> trigger_row.field_name;
    if trigger_row.field_name = 'plan_amount' then
      update public.deals d set plan_amount = trigger_row.plan_amount
      where d.organization_id = org_id and d.id = deal.id;
      return jsonb_build_object('field', 'plan_amount', 'from', old_value, 'to', trigger_row.plan_amount);
    elsif trigger_row.field_name = 'doctor_id' then
      update public.deals d set doctor_id = trigger_row.doctor_id
      where d.organization_id = org_id and d.id = deal.id;
      return jsonb_build_object('field', 'doctor_id', 'from', old_value, 'to', trigger_row.doctor_id);
    else
      update public.deals d set service_id = trigger_row.service_id
      where d.organization_id = org_id and d.id = deal.id;
      return jsonb_build_object('field', 'service_id', 'from', old_value, 'to', trigger_row.service_id);
    end if;
  end case;
  return '{}'::jsonb;
end;
$$;

CREATE OR REPLACE FUNCTION "private"."salesbot_apply_set"("action" "jsonb", "deal" "public"."deals", "reply" "text") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := deal.organization_id;
  value text := replace(coalesce(action ->> 'value', ''), '{ответ}', coalesce(reply, ''));
  target_id bigint;
  target_kind text;
  new_sales_id bigint;
begin
  case action ->> 'kind'
  when 'stage' then
    target_id := (action ->> 'stage_id')::bigint;
    select s.kind into target_kind from public.stages s
    where s.organization_id = org_id and s.id = target_id and s.pipeline_id = deal.pipeline_id;
    if target_kind is null then
      raise exception 'Этап не найден в воронке сделки' using errcode = '22023';
    end if;
    if target_kind = 'lost' then
      raise exception 'Перевести в отказ может только сотрудник: нужна причина' using errcode = '22023';
    end if;
    if deal.stage_id = target_id then
      return jsonb_build_object('unchanged', true, 'stage_id', target_id);
    end if;
    update public.deals d set stage_id = target_id where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('from_stage_id', deal.stage_id, 'to_stage_id', target_id);

  when 'responsible' then
    new_sales_id := coalesce((action ->> 'sales_id')::bigint, private.next_responsible(org_id, deal.branch_id));
    if new_sales_id is null or not exists (
      select 1 from public.sales s where s.organization_id = org_id and s.id = new_sales_id and not s.disabled
    ) then
      raise exception 'Некому назначить' using errcode = '22023';
    end if;
    if deal.sales_id is not distinct from new_sales_id then
      return jsonb_build_object('unchanged', true, 'sales_id', new_sales_id);
    end if;
    update public.deals d set sales_id = new_sales_id where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('from_sales_id', deal.sales_id, 'to_sales_id', new_sales_id);

  when 'tag_add', 'tag_remove' then
    target_id := (action ->> 'tag_id')::bigint;
    if not exists (select 1 from public.tags t where t.organization_id = org_id and t.id = target_id) then
      raise exception 'Тег не найден' using errcode = '22023';
    end if;
    if (target_id = any(deal.tags)) = (action ->> 'kind' = 'tag_add') then
      return jsonb_build_object('unchanged', true, 'tag_id', target_id);
    end if;
    update public.deals d
    set tags = case when action ->> 'kind' = 'tag_add' then array_append(d.tags, target_id) else array_remove(d.tags, target_id) end
    where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('tag_id', target_id);

  when 'field' then
    target_id := (action ->> 'field_id')::bigint;
    if not exists (
      select 1 from public.custom_fields f
      where f.organization_id = org_id and f.id = target_id and f.entity = 'deal' and f.is_active
    ) then
      raise exception 'Поле не найдено' using errcode = '22023';
    end if;
    update public.deals d
    set custom_values = case when btrim(value) = '' then d.custom_values - target_id::text
      else d.custom_values || jsonb_build_object(target_id::text, btrim(value)) end
    where d.organization_id = org_id and d.id = deal.id;
    return jsonb_build_object('field_id', target_id, 'value', btrim(value));

  when 'deal_field' then
    value := nullif(btrim(value), '');
    case action ->> 'field'
    when 'service_id' then
      update public.deals d set service_id = value::bigint where d.organization_id = org_id and d.id = deal.id;
    when 'doctor_id' then
      update public.deals d set doctor_id = value::bigint where d.organization_id = org_id and d.id = deal.id;
    when 'source_id' then
      update public.deals d set source_id = value::bigint where d.organization_id = org_id and d.id = deal.id;
    when 'plan_amount' then
      update public.deals d set plan_amount = coalesce(regexp_replace(value, '[^0-9]', '', 'g')::bigint, 0)
      where d.organization_id = org_id and d.id = deal.id;
    when 'name' then
      update public.deals d set name = left(value, 200) where d.organization_id = org_id and d.id = deal.id;
    else
      raise exception 'Поле сделки нельзя изменить' using errcode = '22023';
    end case;
    return jsonb_build_object('field', action ->> 'field', 'value', value);

  when 'patient_field' then
    value := left(nullif(btrim(value), ''), 200);
    case action ->> 'field'
    when 'first_name' then
      update public.patients p set first_name = value where p.organization_id = org_id and p.id = deal.patient_id;
    when 'last_name' then
      update public.patients p set last_name = value where p.organization_id = org_id and p.id = deal.patient_id;
    when 'middle_name' then
      update public.patients p set middle_name = value where p.organization_id = org_id and p.id = deal.patient_id;
    when 'city' then
      update public.patients p set city = value where p.organization_id = org_id and p.id = deal.patient_id;
    else
      raise exception 'Поле пациента нельзя изменить' using errcode = '22023';
    end case;
    return jsonb_build_object('field', action ->> 'field', 'value', value);
  else
    raise exception 'Неизвестное действие' using errcode = '22023';
  end case;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."report_plan_services"("period_from" timestamp with time zone DEFAULT NULL::timestamp with time zone, "period_to" timestamp with time zone DEFAULT NULL::timestamp with time zone, "filter_pipeline_id" bigint DEFAULT NULL::bigint, "filter_sales_id" bigint DEFAULT NULL::bigint, "filter_source_id" bigint DEFAULT NULL::bigint, "filter_doctor_id" bigint DEFAULT NULL::bigint, "filter_branch_id" bigint DEFAULT NULL::bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $$
begin
  perform private.report_check_access();
  return coalesce((
    select jsonb_agg(jsonb_build_object('service_id', r.service_id, 'name', r.name, 'quantity', r.quantity,
      'amount', r.amount, 'plans', r.plans) order by r.amount desc, r.name)
    from (
      select i.service_id, coalesce(sv.name, i.name) as name, sum(i.quantity)::bigint as quantity,
        sum(i.line_total)::bigint as amount, count(distinct p.id) as plans
      from public.treatment_plans p
        join public.deals d on d.organization_id = p.organization_id and d.id = p.deal_id
        join public.treatment_plan_items i on i.organization_id = p.organization_id and i.plan_id = p.id
        left join public.services sv on sv.organization_id = i.organization_id and sv.id = i.service_id
      where p.organization_id = private.current_organization_id()
        and p.is_main
        and (period_from is null or p.agreed_at >= period_from)
        and (period_to is null or p.agreed_at < period_to)
        and (filter_pipeline_id is null or d.pipeline_id = filter_pipeline_id)
        and (filter_sales_id is null or d.sales_id = filter_sales_id)
        and (filter_source_id is null or d.source_id = filter_source_id)
        and (filter_doctor_id is null or coalesce(p.doctor_id, d.doctor_id) = filter_doctor_id)
        and (filter_branch_id is null or d.branch_id = filter_branch_id)
      group by i.service_id, coalesce(sv.name, i.name)
      order by amount desc, name
      limit 20
    ) r
  ), '[]'::jsonb);
end;
$$;

CREATE OR REPLACE FUNCTION "private"."access_scopes"("entity" "text", "action" "text") RETURNS "text"[]
    LANGUAGE "plpgsql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
begin
  if entity = 'reports' then
    return case when action = 'view' then array['all', 'none'] end;
  end if;
  if entity not in ('deals', 'patients', 'tasks') or action not in ('view', 'create', 'edit', 'delete', 'export') then
    return null;
  end if;
  if action = 'create' then
    return array['all', 'none'];
  end if;
  if entity = 'deals' then
    return array['all', 'branch', 'own_and_unassigned', 'own', 'none'];
  end if;
  if entity = 'tasks' then
    return array['all', 'branch', 'own', 'none'];
  end if;
  return array['all', 'own', 'none'];
end;
$$;

CREATE OR REPLACE FUNCTION "public"."my_access_rights"() RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  me public.sales;
  overrides jsonb;
begin
  select s.* into me
  from public.sales s
  where s.user_id = auth.uid() and not s.disabled
    and (s.access_expires_at is null or s.access_expires_at > now());
  if me.id is null then
    return null;
  end if;
  select r.rights into overrides
  from public.access_rights r
  where r.organization_id = me.organization_id and r.sales_id = me.id;
  return jsonb_build_object(
    'sales_id', me.id,
    'role', me.role,
    'rights', private.access_matrix(me.organization_id, me.role, overrides),
    'customized', overrides is not null and me.role in ('head', 'manager'),
    'branch_ids', coalesce((
      select jsonb_agg(sb.branch_id order by sb.branch_id)
      from public.sales_branches sb
      where sb.organization_id = me.organization_id and sb.sales_id = me.id
    ), '[]'::jsonb)
  );
end;
$$;

-- «Мой филиал»: the policies of deals and tasks are recreated below
drop policy "Visible deals can be read" on public.deals;
drop policy "Deals in the edit scope can be updated" on public.deals;
drop policy "Deals in the delete scope can be deleted" on public.deals;
drop policy "Tasks in the view scope can be read" on public.tasks;
drop policy "Tasks in the edit scope can be updated" on public.tasks;
drop policy "Tasks in the delete scope can be deleted" on public.tasks;

--
-- Triggers
--

-- Before deal_attribution and deal_before_write (alphabetical order)
create or replace trigger deal_assign_branch
    before insert or update on public.deals
    for each row execute function private.handle_deal_branch();

create or replace trigger deal_branch_changed
    after update of branch_id on public.deals
    for each row
    when (old.branch_id is distinct from new.branch_id)
    execute function private.handle_deal_branch_changed();

create or replace trigger task_branch
    before insert or update of deal_id, branch_id on public.tasks
    for each row execute function private.handle_task_branch();

create or replace trigger visit_branch
    before insert or update on public.visits
    for each row execute function private.handle_visit_branch();

create or replace trigger audit_branch
    after insert or update or delete on public.branches
    for each row execute function private.audit_row('branch', 'name,address,phone,is_active');

--
-- Views
--

-- deals_summary of 32_marketing.sql with the branch at the end
create or replace view public.deals_summary with (security_invoker = on) as
select
    d.id,
    d.organization_id,
    d.patient_id,
    d.pipeline_id,
    d.stage_id,
    d.name,
    d.source_id,
    d.service_id,
    d.plan_amount,
    d.paid_amount,
    d.sales_id,
    d.lost_reason_id,
    d.lost_comment,
    d.appointment_at,
    d.visit_at,
    d.tags,
    d.description,
    d.index,
    d.created_at,
    d.updated_at,
    d.stage_changed_at,
    d.closed_at,
    d.first_response_at,
    d.archived_at,
    s.kind as stage_kind,
    p.first_name as patient_first_name,
    p.last_name as patient_last_name,
    p.phones[1] as patient_phone,
    lower(concat_ws(' ', d.name, p.last_name, p.first_name, p.middle_name, array_to_string(p.phones, ' '))) as search_text,
    (
        select count(*)
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
    ) as nb_open_tasks,
    (
        select min(t.due_date)
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
    ) as next_task_due_at,
    (
        select count(*)
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id and m.direction = 'in' and m.read_at is null
    ) as nb_unread_messages,
    (
        select max(m.sent_at)
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id
    ) as last_message_at,
    (
        select m.text
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id
        order by m.sent_at desc, m.id desc
        limit 1
    ) as last_message_text,
    d.doctor_id,
    dr.name as doctor_name,
    d.consultation_amount,
    (
        select coalesce(sum(pay.amount), 0)::bigint
        from public.deal_payments pay
        where pay.organization_id = d.organization_id and pay.deal_id = d.id and pay.kind = 'prepayment'
    ) as prepayment_amount,
    d.unsorted_at,
    d.custom_values,
    -- Deal list (stage 21): the latest change or message, the nearest open task
    greatest(d.updated_at, (
        select max(m.sent_at)
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id
    )) as last_activity_at,
    (
        select t.text
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
        order by t.due_date, t.id
        limit 1
    ) as next_task_text,
    d.utm_source,
    d.utm_medium,
    d.utm_campaign,
    d.utm_content,
    d.utm_term,
    d.referrer,
    d.landing_page,
    d.branch_id,
    br.name as branch_name
from public.deals d
    join public.stages s on s.id = d.stage_id
    join public.patients p on p.organization_id = d.organization_id and p.id = d.patient_id
    left join public.doctors dr on dr.organization_id = d.organization_id and dr.id = d.doctor_id
    left join public.branches br on br.organization_id = d.organization_id and br.id = d.branch_id;

--
-- Row level security
--

alter table public.branches enable row level security;
alter table public.sales_branches enable row level security;

-- A dictionary: every employee reads it, the owner and the head manage it
create policy "Organization members can read" on public.branches for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Owner and head can insert" on public.branches for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can update" on public.branches for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head can delete" on public.branches for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

create policy "Organization members can read" on public.sales_branches for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Owner and head can insert" on public.sales_branches for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can delete" on public.sales_branches for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

-- Deals and tasks (the rules of 05_policies.sql, declared here because they
-- read branch_id): the view, edit and delete scopes of the employee — all,
-- «Мой филиал» (own, of the employee's branches, without a branch), own,
-- own and unassigned (deals), none. Tasks: of visible deals too.
create policy "Visible deals can be read" on public.deals for select to authenticated
    using (
        organization_id = (select private.current_organization_id())
        and (
            (select private.access_scope('deals', 'view')) = 'all'
            or ((select private.access_scope('deals', 'view')) in ('branch', 'own', 'own_and_unassigned') and sales_id = (select private.current_sales_id()))
            or ((select private.access_scope('deals', 'view')) = 'own_and_unassigned' and sales_id is null)
            or ((select private.access_scope('deals', 'view')) = 'branch' and (branch_id is null or (select private.current_branch_ids()) @> array[branch_id]))
        )
    );
create policy "Deals in the edit scope can be updated" on public.deals for update to authenticated
    using (
        organization_id = (select private.current_organization_id())
        and (
            (select private.access_scope('deals', 'edit')) = 'all'
            or ((select private.access_scope('deals', 'edit')) in ('branch', 'own', 'own_and_unassigned') and sales_id = (select private.current_sales_id()))
            or ((select private.access_scope('deals', 'edit')) = 'own_and_unassigned' and sales_id is null)
            or ((select private.access_scope('deals', 'edit')) = 'branch' and (branch_id is null or (select private.current_branch_ids()) @> array[branch_id]))
        )
    )
    with check (organization_id = (select private.current_organization_id()));
create policy "Deals in the delete scope can be deleted" on public.deals for delete to authenticated
    using (
        organization_id = (select private.current_organization_id())
        and (
            (select private.access_scope('deals', 'delete')) = 'all'
            or ((select private.access_scope('deals', 'delete')) in ('branch', 'own', 'own_and_unassigned') and sales_id = (select private.current_sales_id()))
            or ((select private.access_scope('deals', 'delete')) = 'own_and_unassigned' and sales_id is null)
            or ((select private.access_scope('deals', 'delete')) = 'branch' and (branch_id is null or (select private.current_branch_ids()) @> array[branch_id]))
        )
    );
create policy "Tasks in the view scope can be read" on public.tasks for select to authenticated
    using (
        organization_id = (select private.current_organization_id())
        and ((select private.access_scope('tasks', 'view')) = 'all'
            or ((select private.access_scope('tasks', 'view')) in ('branch', 'own') and sales_id = (select private.current_sales_id()))
            or ((select private.access_scope('tasks', 'view')) = 'branch' and (branch_id is null or (select private.current_branch_ids()) @> array[branch_id])))
        and exists (select 1 from public.deals d where d.organization_id = tasks.organization_id and d.id = tasks.deal_id)
    );
create policy "Tasks in the edit scope can be updated" on public.tasks for update to authenticated
    using (
        organization_id = (select private.current_organization_id())
        and ((select private.access_scope('tasks', 'edit')) = 'all'
            or ((select private.access_scope('tasks', 'edit')) in ('branch', 'own') and sales_id = (select private.current_sales_id()))
            or ((select private.access_scope('tasks', 'edit')) = 'branch' and (branch_id is null or (select private.current_branch_ids()) @> array[branch_id])))
        and exists (select 1 from public.deals d where d.organization_id = tasks.organization_id and d.id = tasks.deal_id)
    )
    with check (organization_id = (select private.current_organization_id()));
create policy "Tasks in the delete scope can be deleted" on public.tasks for delete to authenticated
    using (
        organization_id = (select private.current_organization_id())
        and ((select private.access_scope('tasks', 'delete')) = 'all'
            or ((select private.access_scope('tasks', 'delete')) in ('branch', 'own') and sales_id = (select private.current_sales_id()))
            or ((select private.access_scope('tasks', 'delete')) = 'branch' and (branch_id is null or (select private.current_branch_ids()) @> array[branch_id])))
        and exists (select 1 from public.deals d where d.organization_id = tasks.organization_id and d.id = tasks.deal_id)
    );

-- The branch of a messenger channel (the only column employees may write)
create policy "Owner and head can update" on public.messenger_channels for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));

--
-- Grants
--

revoke all on table public.branches from anon;
grant select, insert, update, delete on table public.branches to authenticated;
grant all on table public.branches to service_role;
revoke all on sequence public.branches_id_seq from anon;
grant usage, select on sequence public.branches_id_seq to authenticated;
grant all on sequence public.branches_id_seq to service_role;
revoke all on table public.sales_branches from anon;
grant select, insert, delete on table public.sales_branches to authenticated;
grant all on table public.sales_branches to service_role;

grant update (branch_id) on table public.messenger_channels to authenticated;

revoke all on function private.current_branch_ids() from public;
grant execute on function private.current_branch_ids() to authenticated;
grant execute on function private.current_branch_ids() to service_role;
revoke all on function private.find_branch(bigint, text) from public;
grant execute on function private.find_branch(bigint, text) to service_role;
revoke all on function private.branch_pool(bigint, bigint, bigint[]) from public;
grant execute on function private.branch_pool(bigint, bigint, bigint[]) to authenticated, service_role;
revoke all on function private.handle_deal_branch() from public;
revoke all on function private.handle_deal_branch_changed() from public;
revoke all on function private.handle_task_branch() from public;
revoke all on function private.handle_visit_branch() from public;
revoke all on function public.assign_branch_to_unassigned(bigint) from public, anon;
grant execute on function public.assign_branch_to_unassigned(bigint) to authenticated;
grant execute on function public.assign_branch_to_unassigned(bigint) to service_role;

revoke all on function private.next_responsible(bigint, bigint) from public;
grant execute on function private.next_responsible(bigint, bigint) to authenticated, service_role;
revoke all on function private.report_deal_progress(bigint, bigint, bigint, bigint, bigint) from public;
grant execute on function private.report_deal_progress(bigint, bigint, bigint, bigint, bigint) to authenticated;
grant execute on function private.report_deal_progress(bigint, bigint, bigint, bigint, bigint) to service_role;
revoke all on function public.report_conversion(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint, bigint) from public, anon;
grant execute on function public.report_conversion(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint, bigint) to authenticated;
grant execute on function public.report_conversion(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint, bigint) to service_role;
revoke all on function public.report_speed(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint, bigint) from public, anon;
grant execute on function public.report_speed(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint, bigint) to authenticated;
grant execute on function public.report_speed(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint, bigint) to service_role;
revoke all on function public.report_lost_reasons(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint, bigint) from public, anon;
grant execute on function public.report_lost_reasons(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint, bigint) to authenticated;
grant execute on function public.report_lost_reasons(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint, bigint) to service_role;
revoke all on function public.report_money(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint, bigint) from public, anon;
grant execute on function public.report_money(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint, bigint) to authenticated;
grant execute on function public.report_money(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint, bigint) to service_role;
revoke all on function public.report_plan_services(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint, bigint) from public, anon;
grant execute on function public.report_plan_services(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint, bigint) to authenticated;
grant execute on function public.report_plan_services(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint, bigint) to service_role;
