--
-- The clinic price list «Прайс» (stage 35): a main section of the app, like
-- the price list of a dental MIS.
--
--   service_categories      the tree of the price list: sections and their
--                           subsections (two levels: «Терапия → Лечение
--                           кариеса»), ordered by position. Names are unique
--                           among siblings and contain no «/» (the path
--                           separator of the import and export files).
--   services                the same table as before (deals, visits,
--                           treatment plans, reports): category_id, the unit
--                           (зуб / челюсть / посещение / услуга), the
--                           duration in minutes (the default length of a
--                           visit of this service), the direction or
--                           specialty and a note on the materials.
--                           services.category (stage 29) stays: it is kept
--                           equal to the path of category_id («Терапия /
--                           Лечение кариеса»), and a writer that only knows
--                           the text (the stage-29 import, the API) gets its
--                           category found or created from the path.
--   service_costs           the cost price «себестоимость» of a service: a
--                           table of its own so that RLS hides it from
--                           everybody but the owner and the head (managers
--                           read the prices to talk to the patients, not the
--                           margins; the integrator configures the price
--                           list but sees no money).
--   service_price_history   every price change (the first price too): who,
--                           when, old → new. Written by a trigger, read by
--                           every member of the clinic.
--   price_list              the view of the page: the services with their
--                           cost price (null where RLS hides it), whether
--                           they are used (deals, visits, treatment plans,
--                           recall rules, stage triggers) and the time of the
--                           last price change.
--
-- Treatment plans keep the price they were made with: an item copies the
-- unit price (treatment_plan_items.unit_price), a new price changes nothing
-- in existing plans.
--
-- Bulk actions (public.bulk_services): move to a category, change the price
-- by a percentage or by an amount (rounded to 100 ₸, never below 0),
-- archive, restore, delete (unused services only: the used ones are
-- archived instead, so deals, visits and plans keep their service).
--
-- Rights: the owner and the head edit the price list and the categories (the
-- integrator too, as in stage 25); every member reads them. The cost price:
-- the owner and the head only.
--

--
-- Tables and columns
--

create table public.service_categories (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    -- null: a section; else the section of this subsection
    parent_id bigint,
    name text not null,
    position integer not null default 0,
    created_at timestamp with time zone not null default now(),
    constraint service_categories_name_not_blank check (btrim(name) <> ''),
    constraint service_categories_name_check check (char_length(name) <= 100 and strpos(name, '/') = 0),
    constraint service_categories_parent_check check (parent_id is null or parent_id <> id)
);

create table public.service_costs (
    organization_id bigint not null default private.current_organization_id(),
    service_id bigint not null,
    cost_price numeric(12,2) not null,
    updated_by bigint default private.current_sales_id(),
    updated_at timestamp with time zone not null default now(),
    constraint service_costs_pkey primary key (organization_id, service_id),
    constraint service_costs_cost_price_check check (cost_price >= 0)
);

create table public.service_price_history (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    service_id bigint not null,
    old_price numeric(12,2),
    new_price numeric(12,2),
    sales_id bigint,
    changed_at timestamp with time zone not null default now()
);

alter table public.services add column category_id bigint;
alter table public.services add column unit text not null default 'service';
alter table public.services add column duration_minutes integer;
alter table public.services add column specialty text;
alter table public.services add column materials_note text;
alter table public.services add constraint services_unit_check
    check (unit in ('tooth', 'jaw', 'visit', 'service'));
alter table public.services add constraint services_duration_check
    check (duration_minutes is null or (duration_minutes >= 5 and duration_minutes <= 720));
alter table public.services add constraint services_specialty_length
    check (specialty is null or char_length(specialty) <= 100);
alter table public.services add constraint services_materials_note_length
    check (materials_note is null or char_length(materials_note) <= 1000);

alter table public.service_categories add constraint service_categories_organization_id_id_key unique (organization_id, id);

alter table public.service_categories
    add constraint service_categories_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
-- Deleting a section deletes its subsections (their services lose the category)
alter table public.service_categories
    add constraint service_categories_parent_id_fkey foreign key (organization_id, parent_id) references public.service_categories(organization_id, id) on delete cascade;
alter table public.services
    add constraint services_category_id_fkey foreign key (organization_id, category_id) references public.service_categories(organization_id, id) on delete set null (category_id);
alter table public.service_costs
    add constraint service_costs_service_id_fkey foreign key (organization_id, service_id) references public.services(organization_id, id) on delete cascade;
alter table public.service_costs
    add constraint service_costs_updated_by_fkey foreign key (organization_id, updated_by) references public.sales(organization_id, id) on delete set null (updated_by);
alter table public.service_price_history
    add constraint service_price_history_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.service_price_history
    add constraint service_price_history_service_id_fkey foreign key (organization_id, service_id) references public.services(organization_id, id) on delete cascade;
alter table public.service_price_history
    add constraint service_price_history_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id) on delete set null (sales_id);

-- Names are unique among the siblings (case and spaces ignored)
create unique index service_categories_name_key on public.service_categories using btree (organization_id, coalesce(parent_id, (0)::bigint), lower(btrim(name)));
create index service_categories_parent_id_idx on public.service_categories using btree (organization_id, parent_id, position);
create index services_category_id_idx on public.services using btree (organization_id, category_id) where category_id is not null;
create index service_price_history_service_id_idx on public.service_price_history using btree (organization_id, service_id, changed_at desc);
-- «Используется»: a service of deals or visits cannot be deleted
create index deals_service_id_idx on public.deals using btree (organization_id, service_id) where service_id is not null;
create index visits_service_id_idx on public.visits using btree (organization_id, service_id) where service_id is not null;

--
-- Functions
--

-- «Терапия / Лечение кариеса»: the path of a category, null when unknown
CREATE OR REPLACE FUNCTION "private"."service_category_path"("org_id" bigint, "target_category_id" bigint) RETURNS "text"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  return (
    select case when p.id is null then c.name else p.name || ' / ' || c.name end
    from public.service_categories c
      left join public.service_categories p on p.organization_id = c.organization_id and p.id = c.parent_id
    where c.organization_id = org_id and c.id = target_category_id
  );
end;
$$;

-- The category of a path «Раздел / Подраздел» (case and spaces ignored),
-- created when missing; null for an empty path. Deeper levels are ignored.
CREATE OR REPLACE FUNCTION "private"."resolve_service_category"("org_id" bigint, "path" "text") RETURNS bigint
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  parts text[];
  part text;
  parent bigint := null;
  found bigint;
  level integer := 0;
begin
  select array_agg(btrim(regexp_replace(p, '\s+', ' ', 'g')) order by n)
  into parts
  from unnest(regexp_split_to_array(coalesce(path, ''), '\s*[/>→]\s*')) with ordinality as t(p, n)
  where btrim(p) <> '';
  if parts is null then
    return null;
  end if;
  foreach part in array parts loop
    level := level + 1;
    exit when level > 2;
    select c.id into found
    from public.service_categories c
    where c.organization_id = org_id and c.parent_id is not distinct from parent
      and lower(btrim(c.name)) = lower(part);
    if found is null then
      insert into public.service_categories (organization_id, parent_id, name, position)
      values (org_id, parent, left(part, 100), coalesce((
        select max(c.position) + 1 from public.service_categories c
        where c.organization_id = org_id and c.parent_id is not distinct from parent), 0))
      returning id into found;
    end if;
    parent := found;
  end loop;
  return parent;
end;
$$;

-- Whether deals, visits, treatment plans, recall rules or stage triggers
-- use a service (such a service is archived, not deleted)
CREATE OR REPLACE FUNCTION "private"."service_in_use"("org_id" bigint, "target_service_id" bigint) RETURNS boolean
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  return exists (select 1 from public.deals d where d.organization_id = org_id and d.service_id = target_service_id)
    or exists (select 1 from public.visits v where v.organization_id = org_id and v.service_id = target_service_id)
    or exists (select 1 from public.treatment_plan_items i where i.organization_id = org_id and i.service_id = target_service_id)
    or exists (select 1 from public.recall_rules r where r.organization_id = org_id
      and (r.service_id = target_service_id or r.deal_service_id = target_service_id))
    or exists (select 1 from public.stage_triggers t where t.organization_id = org_id and t.service_id = target_service_id);
end;
$$;

-- A price after a bulk change: rounded to 100 ₸ (half up), never below 0
CREATE OR REPLACE FUNCTION "private"."round_price"("value" numeric) RETURNS numeric
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select greatest(0, round(value / 100) * 100)
$$;

-- Before a service is written: its category and the path in services.category
-- stay together, whichever of the two the writer gave
CREATE OR REPLACE FUNCTION "private"."handle_service_category"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  new.specialty := nullif(btrim(new.specialty), '');
  new.materials_note := nullif(btrim(new.materials_note), '');
  if tg_op = 'INSERT' or new.category_id is distinct from old.category_id then
    if new.category_id is not null then
      new.category := private.service_category_path(new.organization_id, new.category_id);
      if new.category is null then
        raise exception 'Раздел прайса не найден' using errcode = '23503';
      end if;
    elsif nullif(btrim(new.category), '') is not null
      and (tg_op = 'INSERT' or new.category is distinct from old.category) then
      new.category_id := private.resolve_service_category(new.organization_id, new.category);
      new.category := private.service_category_path(new.organization_id, new.category_id);
    else
      new.category := null;
    end if;
  elsif new.category is distinct from old.category then
    if nullif(btrim(new.category), '') is null then
      new.category_id := null;
      new.category := null;
    elsif new.category_id is null
      or new.category is distinct from private.service_category_path(new.organization_id, new.category_id) then
      new.category_id := private.resolve_service_category(new.organization_id, new.category);
      new.category := private.service_category_path(new.organization_id, new.category_id);
    end if;
  end if;
  return new;
end;
$$;

-- After a price changes (the first price too): a row of the price history
CREATE OR REPLACE FUNCTION "private"."handle_service_price_history"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if tg_op = 'INSERT' and new.price is null then
    return null;
  end if;
  if tg_op = 'UPDATE' and new.price is not distinct from old.price then
    return null;
  end if;
  insert into public.service_price_history (organization_id, service_id, old_price, new_price, sales_id)
  values (new.organization_id, new.id, case when tg_op = 'UPDATE' then old.price end, new.price, private.current_sales_id());
  return null;
end;
$$;

-- Before a category is written: a trimmed name, at most two levels
CREATE OR REPLACE FUNCTION "private"."handle_service_category_before_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  new.name := btrim(regexp_replace(new.name, '\s+', ' ', 'g'));
  if new.parent_id is not null and (tg_op = 'INSERT' or new.parent_id is distinct from old.parent_id) then
    if exists (select 1 from public.service_categories p
      where p.organization_id = new.organization_id and p.id = new.parent_id and p.parent_id is not null) then
      raise exception 'В прайсе два уровня: раздел и подраздел' using errcode = '22023';
    end if;
    if tg_op = 'UPDATE' and exists (select 1 from public.service_categories c
      where c.organization_id = new.organization_id and c.parent_id = new.id) then
      raise exception 'Раздел с подразделами не может стать подразделом' using errcode = '22023';
    end if;
  end if;
  return new;
end;
$$;

-- After a category is renamed or moved: the paths of its services (and of
-- the services of its subsections)
CREATE OR REPLACE FUNCTION "private"."handle_service_category_after_update"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  update public.services s
  set category = private.service_category_path(s.organization_id, s.category_id)
  where s.organization_id = new.organization_id
    and s.category_id in (
      select c.id from public.service_categories c
      where c.organization_id = new.organization_id and (c.id = new.id or c.parent_id = new.id))
    and s.category is distinct from private.service_category_path(s.organization_id, s.category_id);
  return null;
end;
$$;

-- Before a category is deleted: the services of a subsection go to its
-- section, those of a section (and of its subsections) lose the category
CREATE OR REPLACE FUNCTION "private"."handle_service_category_delete"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  target bigint := null;
begin
  if old.parent_id is not null and exists (select 1 from public.service_categories p
    where p.organization_id = old.organization_id and p.id = old.parent_id) then
    target := old.parent_id;
  end if;
  update public.services s
  set category_id = target
  where s.organization_id = old.organization_id
    and s.category_id in (
      select c.id from public.service_categories c
      where c.organization_id = old.organization_id and (c.id = old.id or c.parent_id = old.id));
  return old;
end;
$$;

-- «Себестоимость» of a service: null removes it. Owner and head only.
CREATE OR REPLACE FUNCTION "public"."set_service_cost"("target_service_id" bigint, "cost" numeric) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
begin
  if private.current_user_role() is distinct from 'owner' and private.current_user_role() is distinct from 'head' then
    raise exception 'Себестоимость видят и меняют только владелец и руководитель' using errcode = '42501';
  end if;
  if not exists (select 1 from public.services s where s.organization_id = org_id and s.id = target_service_id) then
    raise exception 'Услуга не найдена' using errcode = 'P0002';
  end if;
  if cost is null then
    delete from public.service_costs c where c.organization_id = org_id and c.service_id = target_service_id;
  else
    insert into public.service_costs (organization_id, service_id, cost_price, updated_by, updated_at)
    values (org_id, target_service_id, cost, private.current_sales_id(), now())
    on conflict (organization_id, service_id)
    do update set cost_price = excluded.cost_price, updated_by = excluded.updated_by, updated_at = excluded.updated_at;
  end if;
end;
$$;

-- Bulk actions of the price list on the given services of the clinic:
--   move            to target_category_id (null: «Без раздела»)
--   price_percent   price × (100 + amount) / 100, rounded to 100 ₸
--   price_amount    price + amount, rounded to 100 ₸
--   archive, restore
--   delete          unused services are deleted, used ones archived
-- Returns {"updated": n, "deleted": n, "archived": n}.
CREATE OR REPLACE FUNCTION "public"."bulk_services"("service_ids" bigint[], "bulk_action" "text", "amount" numeric DEFAULT NULL::numeric, "target_category_id" bigint DEFAULT NULL::bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  updated integer := 0;
  deleted integer := 0;
  archived integer := 0;
begin
  if coalesce(private.current_user_role(), '') not in ('owner', 'head', 'integrator') then
    raise exception 'Прайс меняют владелец и руководитель клиники' using errcode = '42501';
  end if;
  if bulk_action = 'move' then
    if target_category_id is not null and not exists (select 1 from public.service_categories c
      where c.organization_id = org_id and c.id = target_category_id) then
      raise exception 'Раздел прайса не найден' using errcode = '23503';
    end if;
    update public.services s set category_id = target_category_id
    where s.organization_id = org_id and s.id = any(service_ids)
      and s.category_id is distinct from target_category_id;
    get diagnostics updated = row_count;
  elsif bulk_action in ('price_percent', 'price_amount') then
    if amount is null or (bulk_action = 'price_percent' and (amount <= -100 or amount > 1000)) then
      raise exception 'Неверное изменение цены' using errcode = '22023';
    end if;
    update public.services s
    set price = private.round_price(case when bulk_action = 'price_percent'
      then s.price * (100 + amount) / 100 else s.price + amount end)
    where s.organization_id = org_id and s.id = any(service_ids) and s.price is not null
      and s.price is distinct from private.round_price(case when bulk_action = 'price_percent'
        then s.price * (100 + amount) / 100 else s.price + amount end);
    get diagnostics updated = row_count;
  elsif bulk_action in ('archive', 'restore') then
    update public.services s set is_archived = (bulk_action = 'archive')
    where s.organization_id = org_id and s.id = any(service_ids)
      and s.is_archived is distinct from (bulk_action = 'archive');
    get diagnostics updated = row_count;
  elsif bulk_action = 'delete' then
    update public.services s set is_archived = true
    where s.organization_id = org_id and s.id = any(service_ids)
      and private.service_in_use(org_id, s.id) and not s.is_archived;
    get diagnostics archived = row_count;
    delete from public.services s
    where s.organization_id = org_id and s.id = any(service_ids)
      and not private.service_in_use(org_id, s.id);
    get diagnostics deleted = row_count;
  else
    raise exception 'Неизвестное действие: %', bulk_action using errcode = '22023';
  end if;
  return jsonb_build_object('updated', updated, 'deleted', deleted, 'archived', archived);
end;
$$;

--
-- Views
--

-- The page «Прайс»: the cost price is null where RLS hides service_costs
create or replace view public.price_list with (security_invoker = on) as
select
    s.id,
    s.organization_id,
    s.name,
    s.code,
    s.category,
    s.category_id,
    s.price,
    s.unit,
    s.duration_minutes,
    s.specialty,
    s.materials_note,
    s.position,
    s.is_archived,
    sc.cost_price,
    private.service_in_use(s.organization_id, s.id) as in_use,
    (select max(h.changed_at) from public.service_price_history h
     where h.organization_id = s.organization_id and h.service_id = s.id) as price_changed_at
from public.services s
    left join public.service_costs sc on sc.organization_id = s.organization_id and sc.service_id = s.id;

--
-- Triggers
--

create or replace trigger service_category_sync
    before insert or update on public.services
    for each row execute function private.handle_service_category();

create or replace trigger service_price_history
    after insert or update of price on public.services
    for each row execute function private.handle_service_price_history();

create or replace trigger service_category_before_write
    before insert or update on public.service_categories
    for each row execute function private.handle_service_category_before_write();

create or replace trigger service_category_after_update
    after update of name, parent_id on public.service_categories
    for each row execute function private.handle_service_category_after_update();

create or replace trigger service_category_delete
    before delete on public.service_categories
    for each row execute function private.handle_service_category_delete();

create or replace trigger audit_service_category
    after insert or update or delete on public.service_categories
    for each row execute function private.audit_row('service_category', 'name,parent_id');

--
-- Row level security
--

alter table public.service_categories enable row level security;
alter table public.service_costs enable row level security;
alter table public.service_price_history enable row level security;

create policy "Organization members can read" on public.service_categories for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Price list editors can insert" on public.service_categories for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head', 'integrator'));
create policy "Price list editors can update" on public.service_categories for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head', 'integrator'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Price list editors can delete" on public.service_categories for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head', 'integrator'));

-- The cost price: the owner and the head only
create policy "Owner and head can read" on public.service_costs for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can insert" on public.service_costs for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can update" on public.service_costs for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head can delete" on public.service_costs for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

-- The price history: read by the clinic, written by the trigger only
create policy "Organization members can read" on public.service_price_history for select to authenticated
    using (organization_id = (select private.current_organization_id()));

--
-- Grants
--

revoke all on table public.service_categories from anon;
grant select, insert, update, delete on table public.service_categories to authenticated;
grant all on table public.service_categories to service_role;
revoke all on sequence public.service_categories_id_seq from anon;
grant usage, select on sequence public.service_categories_id_seq to authenticated;
grant all on sequence public.service_categories_id_seq to service_role;

revoke all on table public.service_costs from anon;
grant select, insert, update, delete on table public.service_costs to authenticated;
grant all on table public.service_costs to service_role;

revoke all on table public.service_price_history from anon;
grant select on table public.service_price_history to authenticated;
grant all on table public.service_price_history to service_role;
revoke all on sequence public.service_price_history_id_seq from anon;
grant all on sequence public.service_price_history_id_seq to service_role;

revoke all on table public.price_list from anon;
grant select on table public.price_list to authenticated;
grant all on table public.price_list to service_role;

revoke all on function private.service_category_path(bigint, bigint) from public;
grant execute on function private.service_category_path(bigint, bigint) to service_role;
revoke all on function private.resolve_service_category(bigint, text) from public;
grant execute on function private.resolve_service_category(bigint, text) to service_role;
revoke all on function private.service_in_use(bigint, bigint) from public;
grant execute on function private.service_in_use(bigint, bigint) to authenticated, service_role;
revoke all on function private.round_price(numeric) from public;
grant execute on function private.round_price(numeric) to authenticated, service_role;
revoke all on function private.handle_service_category() from public;
revoke all on function private.handle_service_price_history() from public;
revoke all on function private.handle_service_category_before_write() from public;
revoke all on function private.handle_service_category_after_update() from public;
revoke all on function private.handle_service_category_delete() from public;

revoke all on function public.set_service_cost(bigint, numeric) from public, anon;
grant execute on function public.set_service_cost(bigint, numeric) to authenticated, service_role;
revoke all on function public.bulk_services(bigint[], text, numeric, bigint) from public, anon;
grant execute on function public.bulk_services(bigint[], text, numeric, bigint) to authenticated, service_role;
