--
-- Stage 39: payroll of the doctors and the staff (see supabase/schemas/39_payroll.sql).
--

--
-- Payroll of the doctors and the staff (stage 39): «Зарплаты», like a dental
-- MIS — a doctor earns a percentage of the work they did.
--
--   payroll_schemes        the pay scheme of a doctor (or of an employee of
--                          the CRM: an assistant, an administrator), with
--                          its effective date (the history of schemes: the
--                          scheme of a day is the last one effective on that
--                          day):
--                            fixed_salary      «оклад» per month
--                            percent           of the work done
--                            percent_base      'price': of the price of the
--                                              work (with the discounts of
--                                              the plan); 'paid': of the part
--                                              the patient paid
--                            deduct_materials  the cost price of the service
--                                              (stage 35) is deducted first
--                            category_rates    [{category_id, percent}]: the
--                                              percentage of a section (or
--                                              subsection) of the price list
--                                              instead of the default one
--                                              («Ортопедия» 25 %, «Терапия»
--                                              30 %); a subsection's own rate
--                                              wins over its section's
--                            visit_rate        a fixed amount per completed
--                                              visit
--                            min_guaranteed    «минимум»: the month's accrual
--                                              (work, visits, salary) is
--                                              topped up to it
--   payroll_adjustments    manual lines of a month: bonus («премия»), penalty
--                          («штраф»), payout («выплата»)
--   payroll_months         a closed month: its lines are frozen in
--                          payroll_closed_lines; bonuses and penalties of a
--                          closed month cannot change (payouts can)
--
-- The work of a doctor in a month (private.payroll_compute):
--   plan_item  a done item of a treatment plan (not declined, stage not
--              cancelled), done that month in the clinic's time zone; its
--              doctor: the item's doctor, else the stage's, else the plan's.
--              Amount = line total × stage discount × plan discount, pro rata
--              (Σ amounts of a whole plan = its total).
--   visit      a completed visit of the CRM with a priced service whose deal
--              has no treatment plan (as the patient account of stage 36
--              charges it); amount = the service price.
--   visit_rate every completed visit of the doctor (CRM or MIS) × visit_rate.
-- For an employee of the CRM: payment (the services paid on the deals they
-- are responsible for: account_operations.paid_delta, a refund negative) and
-- visit_rate (completed visits they booked).
-- Then fixed (the salary of the scheme effective on the last day) and
-- minimum (the top-up to min_guaranteed).
--
-- A line: materials = cost price × quantity (when deducted); base = (amount −
-- materials, never below 0) × paid share in the 'paid' mode (paid share of a
-- plan = its payments / the amount of its done work, at most 1; of a visit =
-- its payments / its price); accrued = base × percent. Whole tenge, half
-- away from zero. Twin: src/components/atomic-crm/payroll/payrollMath.ts.
--
-- public.payroll_month(month) returns the month for the page: per doctor and
-- employee the scheme, the lines, the totals, bonuses, penalties, payouts,
-- the balance («остаток к выплате»), the count of overdue plan stages (a
-- stage of theirs with a past deadline in the month, not done), the days off
-- (weekly hours and exceptions of the schedule, stage 28) and a calendar of
-- the month (works and accrual per day).
--
-- Rights: the owner and the head only (money, stage 30): the tables, the
-- functions. A doctor is no user of the CRM: no self-view. Schemes,
-- adjustments and closings go to the audit log.
--

--
-- Tables
--

-- The doctor who did the work of an item (else the stage's, else the plan's)
alter table public.treatment_plan_items add column doctor_id bigint;
alter table public.treatment_plan_items
    add constraint treatment_plan_items_doctor_id_fkey foreign key (organization_id, doctor_id) references public.doctors(organization_id, id) on delete set null (doctor_id);

create table public.payroll_schemes (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    doctor_id bigint,
    sales_id bigint,
    effective_from date not null default CURRENT_DATE,
    fixed_salary bigint not null default 0,
    percent numeric(5,2) not null default 0,
    percent_base text not null default 'price',
    deduct_materials boolean not null default false,
    category_rates jsonb not null default '[]'::jsonb,
    visit_rate bigint not null default 0,
    min_guaranteed bigint not null default 0,
    note text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint payroll_schemes_employee_check check (num_nonnulls(doctor_id, sales_id) = 1),
    constraint payroll_schemes_fixed_salary_check check (fixed_salary >= 0 and fixed_salary <= 1000000000),
    constraint payroll_schemes_percent_check check (percent >= 0 and percent <= 100),
    constraint payroll_schemes_percent_base_check check (percent_base in ('price', 'paid')),
    constraint payroll_schemes_category_rates_is_array check (jsonb_typeof(category_rates) = 'array'),
    constraint payroll_schemes_visit_rate_check check (visit_rate >= 0 and visit_rate <= 1000000000),
    constraint payroll_schemes_min_guaranteed_check check (min_guaranteed >= 0 and min_guaranteed <= 1000000000),
    constraint payroll_schemes_note_length check (note is null or char_length(note) <= 1000)
);

create table public.payroll_adjustments (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    doctor_id bigint,
    sales_id bigint,
    -- The first day of the month it belongs to
    month date not null,
    kind text not null,
    amount bigint not null,
    note text,
    -- The day of a payout (or of the bonus, the penalty)
    occurred_on date not null default CURRENT_DATE,
    created_by bigint default private.current_sales_id(),
    created_at timestamp with time zone not null default now(),
    constraint payroll_adjustments_employee_check check (num_nonnulls(doctor_id, sales_id) = 1),
    constraint payroll_adjustments_month_check check (extract(day from month) = 1),
    constraint payroll_adjustments_kind_check check (kind in ('bonus', 'penalty', 'payout')),
    constraint payroll_adjustments_amount_check check (amount > 0 and amount <= 1000000000),
    constraint payroll_adjustments_note_length check (note is null or char_length(note) <= 1000)
);

create table public.payroll_months (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    month date not null,
    closed_at timestamp with time zone not null default now(),
    closed_by bigint default private.current_sales_id(),
    constraint payroll_months_month_check check (extract(day from month) = 1)
);

-- The frozen lines of a closed month (written by close_payroll_month only)
create table public.payroll_closed_lines (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    month date not null,
    doctor_id bigint,
    sales_id bigint,
    scheme_id bigint,
    source text not null,
    source_id bigint,
    work_day date,
    patient_id bigint,
    patient_name text,
    service_name text,
    category_name text,
    amount bigint not null default 0,
    materials bigint not null default 0,
    base bigint not null default 0,
    percent numeric(5,2),
    accrued bigint not null default 0
);

alter table public.payroll_schemes add constraint payroll_schemes_organization_id_id_key unique (organization_id, id);
alter table public.payroll_adjustments add constraint payroll_adjustments_organization_id_id_key unique (organization_id, id);
alter table public.payroll_months add constraint payroll_months_month_key unique (organization_id, month);

alter table public.payroll_schemes
    add constraint payroll_schemes_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.payroll_schemes
    add constraint payroll_schemes_doctor_id_fkey foreign key (organization_id, doctor_id) references public.doctors(organization_id, id) on delete cascade;
alter table public.payroll_schemes
    add constraint payroll_schemes_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id) on delete cascade;
alter table public.payroll_adjustments
    add constraint payroll_adjustments_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.payroll_adjustments
    add constraint payroll_adjustments_doctor_id_fkey foreign key (organization_id, doctor_id) references public.doctors(organization_id, id) on delete cascade;
alter table public.payroll_adjustments
    add constraint payroll_adjustments_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id) on delete cascade;
alter table public.payroll_adjustments
    add constraint payroll_adjustments_created_by_fkey foreign key (organization_id, created_by) references public.sales(organization_id, id) on delete set null (created_by);
alter table public.payroll_months
    add constraint payroll_months_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.payroll_months
    add constraint payroll_months_closed_by_fkey foreign key (organization_id, closed_by) references public.sales(organization_id, id) on delete set null (closed_by);
alter table public.payroll_closed_lines
    add constraint payroll_closed_lines_month_fkey foreign key (organization_id, month) references public.payroll_months(organization_id, month) on delete cascade;

create unique index payroll_schemes_doctor_day_idx on public.payroll_schemes using btree (organization_id, doctor_id, effective_from) where doctor_id is not null;
create unique index payroll_schemes_sales_day_idx on public.payroll_schemes using btree (organization_id, sales_id, effective_from) where sales_id is not null;
create index payroll_adjustments_month_idx on public.payroll_adjustments using btree (organization_id, month);
create index payroll_closed_lines_month_idx on public.payroll_closed_lines using btree (organization_id, month);
create index treatment_plan_items_done_at_idx on public.treatment_plan_items using btree (organization_id, done_at) where done;

--
-- Functions
--

-- The scheme of a doctor or an employee on a day: the last one effective
CREATE OR REPLACE FUNCTION "private"."payroll_scheme_at"("org_id" bigint, "target_doctor_id" bigint, "target_sales_id" bigint, "day" "date") RETURNS "public"."payroll_schemes"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  scheme public.payroll_schemes;
begin
  select * into scheme
  from public.payroll_schemes s
  where s.organization_id = org_id
    and s.doctor_id is not distinct from target_doctor_id
    and s.sales_id is not distinct from target_sales_id
    and s.effective_from <= day
  order by s.effective_from desc, s.id desc
  limit 1;
  return scheme;
end;
$$;

-- The percentage of a scheme for a service category: the category's own
-- rate, else its section's, else the default. Twin: percentFor()
CREATE OR REPLACE FUNCTION "private"."payroll_percent"("scheme" "public"."payroll_schemes", "category_id" bigint, "section_id" bigint) RETURNS numeric
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select coalesce(
    (select (r ->> 'percent')::numeric from jsonb_array_elements(scheme.category_rates) r
     where category_id is not null and (r ->> 'category_id')::bigint = category_id limit 1),
    (select (r ->> 'percent')::numeric from jsonb_array_elements(scheme.category_rates) r
     where section_id is not null and (r ->> 'category_id')::bigint = section_id limit 1),
    scheme.percent,
    0);
$$;

-- a × b / c rounded half away from zero, 0 when c is 0. Twin: mulDiv()
CREATE OR REPLACE FUNCTION "private"."payroll_mul_div"("a" numeric, "b" numeric, "c" numeric) RETURNS bigint
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select case when c = 0 then 0::bigint else round(a * b / c)::bigint end;
$$;

-- Every line of a month (month_start: its first day), computed from the
-- work: see the header. SECURITY DEFINER: the whole clinic's work, whatever
-- deals the caller sees; the public functions check the rights.
CREATE OR REPLACE FUNCTION "private"."payroll_compute"("org_id" bigint, "month_start" "date") RETURNS TABLE("doctor_id" bigint, "sales_id" bigint, "scheme_id" bigint, "source" "text", "source_id" bigint, "work_day" "date", "patient_id" bigint, "patient_name" "text", "service_name" "text", "category_name" "text", "amount" bigint, "materials" bigint, "base" bigint, "percent" numeric, "accrued" bigint)
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
#variable_conflict use_column
declare
  tz text := coalesce((select nullif(o.timezone, '') from public.organizations o where o.id = org_id), 'Asia/Almaty');
  month_end date := (month_start + interval '1 month')::date;
  from_at timestamp with time zone := month_start::timestamp at time zone tz;
  to_at timestamp with time zone := month_end::timestamp at time zone tz;
  rec record;
  scheme public.payroll_schemes;
  pct numeric;
  net bigint;
  line_base bigint;
  person record;
  total bigint;
  -- Σ accrued per person so far: { "d<doctor id>" | "s<sales id>": amount }
  totals jsonb := '{}'::jsonb;
  person_key text;
begin
  -- Done plan items
  for rec in
    with plans as (
      select distinct i.plan_id
      from public.treatment_plan_items i
      where i.organization_id = org_id and i.done and i.done_at >= from_at and i.done_at < to_at
    ),
    stage_sums as (
      select s.id, s.discount_percent, coalesce(sum(i.line_total), 0)::bigint as lines
      from public.treatment_stages s
        left join public.treatment_plan_items i on i.organization_id = s.organization_id and i.stage_id = s.id
      where s.organization_id = org_id and s.plan_id in (select plan_id from plans)
      group by s.id, s.discount_percent
    ),
    plan_sums as (
      select p.id, private.treatment_plan_subtotal(org_id, p.id) as subtotal, p.discount_percent, p.discount_amount,
        p.is_main, p.deal_id, p.patient_id, p.doctor_id
      from public.treatment_plans p
      where p.organization_id = org_id and p.id in (select plan_id from plans) and p.status <> 'declined'
    ),
    done as (
      select i.id, i.plan_id, i.service_id, i.name, i.quantity, i.done_at,
        coalesce(i.doctor_id, s.doctor_id, ps.doctor_id) as doctor_id, ps.patient_id,
        private.payroll_mul_div(
          i.line_total::numeric * private.treatment_stage_total(ss.lines, ss.discount_percent),
          private.treatment_plan_total(ps.subtotal, ps.discount_percent, ps.discount_amount),
          ss.lines::numeric * ps.subtotal) as amount
      from public.treatment_plan_items i
        join public.treatment_stages s on s.organization_id = i.organization_id and s.id = i.stage_id
        join stage_sums ss on ss.id = s.id
        join plan_sums ps on ps.id = i.plan_id
      where i.organization_id = org_id and i.done and i.done_at is not null and s.status <> 'cancelled'
    ),
    shares as (
      select d.plan_id, sum(d.amount)::bigint as done_amount,
        coalesce((
          select sum(o.paid_delta) from public.account_operations o
          where o.organization_id = org_id
            and (o.plan_id = d.plan_id or (ps.is_main and o.deal_id = ps.deal_id and o.plan_id is null))
        ), 0)::bigint as paid
      from done d join plan_sums ps on ps.id = d.plan_id
      group by d.plan_id, ps.is_main, ps.deal_id
    )
    select d.*, sh.done_amount, sh.paid,
      sv.category_id, c.parent_id as section_id, coalesce(sec.name, c.name) as category_name,
      coalesce(round(sc.cost_price * d.quantity)::bigint, 0) as cost,
      private.clinic_date(org_id, d.done_at) as day,
      nullif(btrim(concat_ws(' ', pt.last_name, pt.first_name)), '') as patient_name
    from done d
      join shares sh on sh.plan_id = d.plan_id
      left join public.services sv on sv.organization_id = org_id and sv.id = d.service_id
      left join public.service_categories c on c.organization_id = org_id and c.id = sv.category_id
      left join public.service_categories sec on sec.organization_id = org_id and sec.id = c.parent_id
      left join public.service_costs sc on sc.organization_id = org_id and sc.service_id = d.service_id
      left join public.patients pt on pt.organization_id = org_id and pt.id = d.patient_id
    where d.done_at >= from_at and d.done_at < to_at and d.doctor_id is not null
    order by d.done_at, d.id
  loop
    scheme := private.payroll_scheme_at(org_id, rec.doctor_id, null, rec.day);
    pct := case when scheme.id is null then 0 else private.payroll_percent(scheme, rec.category_id, rec.section_id) end;
    net := greatest(0, rec.amount - case when scheme.deduct_materials then rec.cost else 0 end);
    line_base := case when scheme.percent_base = 'paid' and rec.paid < rec.done_amount
      then private.payroll_mul_div(net, greatest(rec.paid, 0), rec.done_amount) else net end;
    doctor_id := rec.doctor_id;
    sales_id := null;
    scheme_id := scheme.id;
    source := 'plan_item';
    source_id := rec.id;
    work_day := rec.day;
    patient_id := rec.patient_id;
    patient_name := rec.patient_name;
    service_name := rec.name;
    category_name := rec.category_name;
    amount := rec.amount;
    materials := case when scheme.deduct_materials then rec.cost else 0 end;
    base := line_base;
    percent := pct;
    accrued := private.payroll_mul_div(line_base, pct, 100);
    person_key := case when doctor_id is not null then 'd' || doctor_id else 's' || sales_id end;
    totals := totals || jsonb_build_object(person_key, coalesce((totals ->> person_key)::bigint, 0) + accrued);
    return next;
  end loop;

  -- Completed visits of the CRM with a priced service, deal without a plan
  for rec in
    select v.id, v.doctor_id, v.patient_id, v.service_id, sv.name as service_name, round(sv.price)::bigint as price,
      sv.category_id, c.parent_id as section_id, coalesce(sec.name, c.name) as category_name,
      coalesce(round(sc.cost_price)::bigint, 0) as cost,
      coalesce((select sum(o.paid_delta) from public.account_operations o
        where o.organization_id = org_id and o.visit_id = v.id), 0)::bigint as paid,
      private.clinic_date(org_id, v.starts_at) as day,
      nullif(btrim(concat_ws(' ', pt.last_name, pt.first_name)), '') as patient_name
    from public.visits v
      join public.services sv on sv.organization_id = v.organization_id and sv.id = v.service_id
      left join public.service_categories c on c.organization_id = org_id and c.id = sv.category_id
      left join public.service_categories sec on sec.organization_id = org_id and sec.id = c.parent_id
      left join public.service_costs sc on sc.organization_id = org_id and sc.service_id = sv.id
      left join public.patients pt on pt.organization_id = org_id and pt.id = v.patient_id
    where v.organization_id = org_id and v.status = 'completed' and v.source = 'crm' and v.doctor_id is not null
      and sv.price > 0 and v.starts_at >= from_at and v.starts_at < to_at
      and not exists (
        select 1 from public.treatment_plans tp
        where tp.organization_id = v.organization_id and tp.deal_id = v.deal_id and tp.status <> 'declined')
    order by v.starts_at, v.id
  loop
    scheme := private.payroll_scheme_at(org_id, rec.doctor_id, null, rec.day);
    pct := case when scheme.id is null then 0 else private.payroll_percent(scheme, rec.category_id, rec.section_id) end;
    net := greatest(0, rec.price - case when scheme.deduct_materials then rec.cost else 0 end);
    line_base := case when scheme.percent_base = 'paid' and rec.paid < rec.price
      then private.payroll_mul_div(net, greatest(rec.paid, 0), rec.price) else net end;
    doctor_id := rec.doctor_id;
    sales_id := null;
    scheme_id := scheme.id;
    source := 'visit';
    source_id := rec.id;
    work_day := rec.day;
    patient_id := rec.patient_id;
    patient_name := rec.patient_name;
    service_name := rec.service_name;
    category_name := rec.category_name;
    amount := rec.price;
    materials := case when scheme.deduct_materials then rec.cost else 0 end;
    base := line_base;
    percent := pct;
    accrued := private.payroll_mul_div(line_base, pct, 100);
    person_key := case when doctor_id is not null then 'd' || doctor_id else 's' || sales_id end;
    totals := totals || jsonb_build_object(person_key, coalesce((totals ->> person_key)::bigint, 0) + accrued);
    return next;
  end loop;

  -- Payments of the deals of an employee of the CRM (percent of sales)
  for rec in
    select o.id, d.sales_id, o.patient_id, o.paid_delta, private.clinic_date(org_id, o.occurred_at) as day,
      d.name as deal_name,
      nullif(btrim(concat_ws(' ', pt.last_name, pt.first_name)), '') as patient_name
    from public.account_operations o
      join public.deals d on d.organization_id = o.organization_id and d.id = o.deal_id
      left join public.patients pt on pt.organization_id = org_id and pt.id = o.patient_id
    where o.organization_id = org_id and o.paid_delta <> 0 and d.sales_id is not null
      and o.occurred_at >= from_at and o.occurred_at < to_at
      and exists (select 1 from public.payroll_schemes s where s.organization_id = org_id and s.sales_id = d.sales_id)
    order by o.occurred_at, o.id
  loop
    scheme := private.payroll_scheme_at(org_id, null, rec.sales_id, rec.day);
    if scheme.id is null or scheme.percent = 0 then
      continue;
    end if;
    doctor_id := null;
    sales_id := rec.sales_id;
    scheme_id := scheme.id;
    source := 'payment';
    source_id := rec.id;
    work_day := rec.day;
    patient_id := rec.patient_id;
    patient_name := rec.patient_name;
    service_name := rec.deal_name;
    category_name := null;
    amount := rec.paid_delta;
    materials := 0;
    base := rec.paid_delta;
    percent := scheme.percent;
    accrued := private.payroll_mul_div(rec.paid_delta, scheme.percent, 100);
    person_key := case when doctor_id is not null then 'd' || doctor_id else 's' || sales_id end;
    totals := totals || jsonb_build_object(person_key, coalesce((totals ->> person_key)::bigint, 0) + accrued);
    return next;
  end loop;

  -- A fixed rate per completed visit: the doctor's, or the employee's who
  -- booked it
  for rec in
    select v.id, x.doctor_id, x.sales_id, v.patient_id, private.clinic_date(org_id, v.starts_at) as day,
      sv.name as service_name,
      nullif(btrim(concat_ws(' ', pt.last_name, pt.first_name)), '') as patient_name
    from public.visits v
      cross join lateral (
        select v.doctor_id, null::bigint as sales_id where v.doctor_id is not null
        union all
        select null::bigint, v.created_by where v.created_by is not null
      ) x
      left join public.services sv on sv.organization_id = v.organization_id and sv.id = v.service_id
      left join public.patients pt on pt.organization_id = org_id and pt.id = v.patient_id
    where v.organization_id = org_id and v.status = 'completed' and v.starts_at >= from_at and v.starts_at < to_at
      and exists (select 1 from public.payroll_schemes s where s.organization_id = org_id and s.visit_rate > 0
        and s.doctor_id is not distinct from x.doctor_id and s.sales_id is not distinct from x.sales_id)
    order by v.starts_at, v.id
  loop
    scheme := private.payroll_scheme_at(org_id, rec.doctor_id, rec.sales_id, rec.day);
    if scheme.id is null or scheme.visit_rate = 0 then
      continue;
    end if;
    doctor_id := rec.doctor_id;
    sales_id := rec.sales_id;
    scheme_id := scheme.id;
    source := 'visit_rate';
    source_id := rec.id;
    work_day := rec.day;
    patient_id := rec.patient_id;
    patient_name := rec.patient_name;
    service_name := rec.service_name;
    category_name := null;
    amount := scheme.visit_rate;
    materials := 0;
    base := scheme.visit_rate;
    percent := null;
    accrued := scheme.visit_rate;
    person_key := case when doctor_id is not null then 'd' || doctor_id else 's' || sales_id end;
    totals := totals || jsonb_build_object(person_key, coalesce((totals ->> person_key)::bigint, 0) + accrued);
    return next;
  end loop;

  -- The salary and the minimum: the scheme of the last day of the month
  for person in
    select distinct s.doctor_id, s.sales_id
    from public.payroll_schemes s
    where s.organization_id = org_id and s.effective_from < month_end
  loop
    scheme := private.payroll_scheme_at(org_id, person.doctor_id, person.sales_id, month_end - 1);
    if scheme.fixed_salary > 0 then
      doctor_id := person.doctor_id;
      sales_id := person.sales_id;
      scheme_id := scheme.id;
      source := 'fixed';
      source_id := null;
      work_day := null;
      patient_id := null;
      patient_name := null;
      service_name := null;
      category_name := null;
      amount := scheme.fixed_salary;
      materials := 0;
      base := scheme.fixed_salary;
      percent := null;
      accrued := scheme.fixed_salary;
      person_key := case when doctor_id is not null then 'd' || doctor_id else 's' || sales_id end;
      totals := totals || jsonb_build_object(person_key, coalesce((totals ->> person_key)::bigint, 0) + accrued);
      return next;
    end if;
    if scheme.min_guaranteed > 0 then
      total := coalesce((totals ->> case when person.doctor_id is not null then 'd' || person.doctor_id else 's' || person.sales_id end)::bigint, 0);
      if total < scheme.min_guaranteed then
        doctor_id := person.doctor_id;
        sales_id := person.sales_id;
        scheme_id := scheme.id;
        source := 'minimum';
        source_id := null;
        work_day := null;
        patient_id := null;
        patient_name := null;
        service_name := null;
        category_name := null;
        amount := scheme.min_guaranteed - total;
        materials := 0;
        base := scheme.min_guaranteed - total;
        percent := null;
        accrued := scheme.min_guaranteed - total;
        person_key := case when doctor_id is not null then 'd' || doctor_id else 's' || sales_id end;
        totals := totals || jsonb_build_object(person_key, coalesce((totals ->> person_key)::bigint, 0) + accrued);
        return next;
      end if;
    end if;
  end loop;
end;
$$;

-- The owner and the head only (money, stage 30)
CREATE OR REPLACE FUNCTION "private"."payroll_check_access"() RETURNS "void"
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $$
begin
  if coalesce(private.current_user_role() in ('owner', 'head'), false) is false then
    raise exception 'Зарплаты видят только владелец и руководитель'
      using errcode = 'insufficient_privilege', hint = 'payroll_forbidden';
  end if;
end;
$$;

-- The lines of a month: frozen when it is closed, else computed
CREATE OR REPLACE FUNCTION "private"."payroll_month_lines"("org_id" bigint, "month_start" "date") RETURNS TABLE("doctor_id" bigint, "sales_id" bigint, "scheme_id" bigint, "source" "text", "source_id" bigint, "work_day" "date", "patient_id" bigint, "patient_name" "text", "service_name" "text", "category_name" "text", "amount" bigint, "materials" bigint, "base" bigint, "percent" numeric, "accrued" bigint)
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
#variable_conflict use_column
begin
  if exists (select 1 from public.payroll_months m where m.organization_id = org_id and m.month = month_start) then
    return query
    select l.doctor_id, l.sales_id, l.scheme_id, l.source, l.source_id, l.work_day, l.patient_id, l.patient_name,
      l.service_name, l.category_name, l.amount, l.materials, l.base, l.percent, l.accrued
    from public.payroll_closed_lines l
    where l.organization_id = org_id and l.month = month_start
    order by l.id;
  else
    return query select * from private.payroll_compute(org_id, month_start);
  end if;
end;
$$;

-- A day off of a doctor: an exception without hours, else a weekday
-- missing from the weekly hours (no weekly hours: the clinic's, every day).
-- Twin: isDayOff()
CREATE OR REPLACE FUNCTION "private"."payroll_day_off"("org_id" bigint, "target_doctor_id" bigint, "day" "date") RETURNS boolean
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  exception_row public.doctor_exceptions;
  hours jsonb;
begin
  select * into exception_row from public.doctor_exceptions e
  where e.organization_id = org_id and e.doctor_id = target_doctor_id and e.day = payroll_day_off.day;
  if found then
    return exception_row.start_time is null;
  end if;
  select d.working_hours into hours from public.doctors d where d.organization_id = org_id and d.id = target_doctor_id;
  if hours is null or hours = '{}'::jsonb then
    return false;
  end if;
  return not (hours ? extract(isodow from day)::integer::text);
end;
$$;

-- «Зарплаты» of a month: see the header. The owner and the head.
CREATE OR REPLACE FUNCTION "public"."payroll_month"("target_month" "date") RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  month_start date := date_trunc('month', target_month)::date;
  month_end date := (date_trunc('month', target_month) + interval '1 month')::date;
  today date := private.clinic_date(private.current_organization_id(), now());
  closing public.payroll_months;
  grouped jsonb;
  employees jsonb := '[]'::jsonb;
  person record;
  person_key text;
  person_lines jsonb;
  scheme public.payroll_schemes;
  adjustments jsonb;
  bonuses bigint;
  penalties bigint;
  payouts bigint;
  lines_accrued bigint;
  days jsonb;
begin
  perform private.payroll_check_access();
  if target_month is null then
    raise exception 'Укажите месяц' using errcode = '22023';
  end if;
  select * into closing from public.payroll_months m where m.organization_id = org_id and m.month = month_start;

  select coalesce(jsonb_object_agg(g.key, g.lines), '{}'::jsonb) into grouped
  from (
    select case when l.doctor_id is not null then 'd' || l.doctor_id else 's' || l.sales_id end as key,
      jsonb_agg(to_jsonb(l) order by l.work_day nulls last, l.source, l.source_id) as lines
    from private.payroll_month_lines(org_id, month_start) l
    group by 1
  ) g;

  for person in
    select 'doctor' as kind, d.id as doctor_id, null::bigint as sales_id, d.name, d.specialty, d.color,
      d.position, d.is_active
    from public.doctors d
    where d.organization_id = org_id
      and (d.is_active or grouped ? ('d' || d.id)
        or exists (select 1 from public.payroll_adjustments a where a.organization_id = org_id and a.doctor_id = d.id and a.month = month_start))
    union all
    select 'sales', null, s.id, btrim(concat_ws(' ', s.first_name, s.last_name)), s.role, null, 0, not s.disabled
    from public.sales s
    where s.organization_id = org_id
      and (grouped ? ('s' || s.id)
        or exists (select 1 from public.payroll_schemes p where p.organization_id = org_id and p.sales_id = s.id and p.effective_from < month_end)
        or exists (select 1 from public.payroll_adjustments a where a.organization_id = org_id and a.sales_id = s.id and a.month = month_start))
    order by 1, 7, 4
  loop
    person_key := case when person.doctor_id is not null then 'd' || person.doctor_id else 's' || person.sales_id end;
    person_lines := coalesce(grouped -> person_key, '[]'::jsonb);
    scheme := private.payroll_scheme_at(org_id, person.doctor_id, person.sales_id, month_end - 1);

    select coalesce(jsonb_agg(to_jsonb(a) order by a.occurred_on, a.id), '[]'::jsonb),
      coalesce(sum(a.amount) filter (where a.kind = 'bonus'), 0)::bigint,
      coalesce(sum(a.amount) filter (where a.kind = 'penalty'), 0)::bigint,
      coalesce(sum(a.amount) filter (where a.kind = 'payout'), 0)::bigint
    into adjustments, bonuses, penalties, payouts
    from public.payroll_adjustments a
    where a.organization_id = org_id and a.month = month_start
      and a.doctor_id is not distinct from person.doctor_id and a.sales_id is not distinct from person.sales_id;

    select coalesce(sum((l ->> 'accrued')::bigint), 0)::bigint into lines_accrued
    from jsonb_array_elements(person_lines) l;

    select jsonb_agg(jsonb_build_object(
        'day', g.day::date,
        'works', coalesce(w.works, 0),
        'amount', coalesce(w.amount, 0),
        'overdue', coalesce(o.overdue, 0),
        'off', person.doctor_id is not null and private.payroll_day_off(org_id, person.doctor_id, g.day::date))
      order by g.day)
    into days
    from generate_series(month_start, month_end - 1, interval '1 day') g(day)
      left join (
        select (l ->> 'work_day')::date as day,
          count(*) filter (where l ->> 'source' in ('plan_item', 'visit')) as works,
          sum((l ->> 'accrued')::bigint) as amount
        from jsonb_array_elements(person_lines) l
        where l ->> 'work_day' is not null
        group by 1
      ) w on w.day = g.day::date
      left join (
        select st.deadline as day, count(*) as overdue
        from public.treatment_stages st
          join public.treatment_plans p on p.organization_id = st.organization_id and p.id = st.plan_id
        where st.organization_id = org_id and person.doctor_id is not null
          and coalesce(st.doctor_id, p.doctor_id) = person.doctor_id
          and st.deadline >= month_start and st.deadline < month_end and st.deadline < today
          and st.status not in ('done', 'cancelled') and p.status <> 'declined'
        group by st.deadline
      ) o on o.day = g.day::date;

    employees := employees || jsonb_build_array(jsonb_build_object(
      'kind', person.kind,
      'doctor_id', person.doctor_id,
      'sales_id', person.sales_id,
      'name', person.name,
      'specialty', person.specialty,
      'color', person.color,
      'is_active', person.is_active,
      'scheme', case when scheme.id is not null then to_jsonb(scheme) end,
      'works_count', (select count(*) from jsonb_array_elements(person_lines) l where l ->> 'source' in ('plan_item', 'visit')),
      'work_amount', (select coalesce(sum((l ->> 'amount')::bigint), 0) from jsonb_array_elements(person_lines) l where l ->> 'source' in ('plan_item', 'visit', 'payment')),
      'materials', (select coalesce(sum((l ->> 'materials')::bigint), 0) from jsonb_array_elements(person_lines) l),
      'work_accrued', (select coalesce(sum((l ->> 'accrued')::bigint), 0) from jsonb_array_elements(person_lines) l where l ->> 'source' in ('plan_item', 'visit', 'payment')),
      'visits_count', (select count(*) from jsonb_array_elements(person_lines) l where l ->> 'source' = 'visit_rate'),
      'visits_accrued', (select coalesce(sum((l ->> 'accrued')::bigint), 0) from jsonb_array_elements(person_lines) l where l ->> 'source' = 'visit_rate'),
      'fixed', (select coalesce(sum((l ->> 'accrued')::bigint), 0) from jsonb_array_elements(person_lines) l where l ->> 'source' = 'fixed'),
      'minimum', (select coalesce(sum((l ->> 'accrued')::bigint), 0) from jsonb_array_elements(person_lines) l where l ->> 'source' = 'minimum'),
      'bonuses', bonuses,
      'penalties', penalties,
      'accrued', lines_accrued + bonuses - penalties,
      'paid_out', payouts,
      'balance', lines_accrued + bonuses - penalties - payouts,
      'overdue_count', (select coalesce(sum((d ->> 'overdue')::integer), 0) from jsonb_array_elements(days) d),
      'days_off', (select count(*) from jsonb_array_elements(days) d where (d ->> 'off')::boolean),
      'days', days,
      'lines', person_lines,
      'adjustments', adjustments));
  end loop;

  return jsonb_build_object(
    'month', month_start,
    'closed', closing.id is not null,
    'closed_at', closing.closed_at,
    'closed_by', closing.closed_by,
    'employees', employees);
end;
$$;

-- «Закрыть месяц»: its lines are frozen (the owner and the head)
CREATE OR REPLACE FUNCTION "public"."close_payroll_month"("target_month" "date") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  month_start date := date_trunc('month', target_month)::date;
  lines_count integer;
  total bigint;
begin
  perform private.payroll_check_access();
  if target_month is null or month_start > date_trunc('month', private.clinic_date(org_id, now()))::date then
    raise exception 'Нельзя закрыть месяц, который ещё не начался' using errcode = '22023';
  end if;
  if exists (select 1 from public.payroll_months m where m.organization_id = org_id and m.month = month_start) then
    raise exception 'Месяц уже закрыт' using errcode = '23505', hint = 'payroll_month_closed';
  end if;
  insert into public.payroll_months (organization_id, month) values (org_id, month_start);
  insert into public.payroll_closed_lines (organization_id, month, doctor_id, sales_id, scheme_id, source, source_id,
    work_day, patient_id, patient_name, service_name, category_name, amount, materials, base, percent, accrued)
  select org_id, month_start, l.doctor_id, l.sales_id, l.scheme_id, l.source, l.source_id, l.work_day, l.patient_id,
    l.patient_name, l.service_name, l.category_name, l.amount, l.materials, l.base, l.percent, l.accrued
  from private.payroll_compute(org_id, month_start) l;
  get diagnostics lines_count = row_count;
  select coalesce(sum(l.accrued), 0)::bigint into total
  from public.payroll_closed_lines l where l.organization_id = org_id and l.month = month_start;
  return jsonb_build_object('month', month_start, 'lines', lines_count, 'accrued', total);
end;
$$;

-- «Открыть месяц»: the owner only; the lines are computed again
CREATE OR REPLACE FUNCTION "public"."reopen_payroll_month"("target_month" "date") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
begin
  if private.current_user_role() is distinct from 'owner' then
    raise exception 'Открыть закрытый месяц может только владелец' using errcode = 'insufficient_privilege', hint = 'payroll_forbidden';
  end if;
  delete from public.payroll_months m
  where m.organization_id = org_id and m.month = date_trunc('month', target_month)::date;
  if not found then
    raise exception 'Месяц не закрыт' using errcode = 'P0002';
  end if;
end;
$$;

-- A scheme: the category rates checked and normalized
CREATE OR REPLACE FUNCTION "private"."handle_payroll_scheme_before_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  rate jsonb;
  rates jsonb := '[]'::jsonb;
  category bigint;
  rate_percent numeric;
begin
  for rate in select * from jsonb_array_elements(new.category_rates) loop
    if jsonb_typeof(rate) <> 'object' or jsonb_typeof(rate -> 'category_id') is distinct from 'number'
      or jsonb_typeof(rate -> 'percent') is distinct from 'number' then
      raise exception 'Процент направления: укажите раздел прайса и процент' using errcode = '22023';
    end if;
    category := (rate ->> 'category_id')::bigint;
    rate_percent := (rate ->> 'percent')::numeric;
    if rate_percent < 0 or rate_percent > 100 then
      raise exception 'Процент должен быть от 0 до 100' using errcode = '22023';
    end if;
    if not exists (select 1 from public.service_categories c where c.organization_id = new.organization_id and c.id = category) then
      raise exception 'Раздел прайса не найден' using errcode = '22023';
    end if;
    if rates @> jsonb_build_array(jsonb_build_object('category_id', category)) then
      raise exception 'Процент для раздела указан дважды' using errcode = '22023';
    end if;
    rates := rates || jsonb_build_array(jsonb_build_object('category_id', category, 'percent', round(rate_percent, 2)));
  end loop;
  new.category_rates := rates;
  new.updated_at := now();
  return new;
end;
$$;

-- Bonuses and penalties of a closed month are frozen (payouts are not);
-- the month is its first day
CREATE OR REPLACE FUNCTION "private"."handle_payroll_adjustment_before_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  -- Deleting the clinic, the doctor or the employee takes everything
  if tg_op = 'DELETE' and pg_trigger_depth() > 1 then
    return old;
  end if;
  if tg_op <> 'INSERT' and old.kind <> 'payout' and exists (
    select 1 from public.payroll_months m where m.organization_id = old.organization_id and m.month = old.month) then
    raise exception 'Месяц закрыт: премии и штрафы не меняются' using errcode = '22023', hint = 'payroll_month_closed';
  end if;
  if tg_op = 'DELETE' then
    return old;
  end if;
  new.month := date_trunc('month', new.month)::date;
  if new.kind <> 'payout' and exists (
    select 1 from public.payroll_months m where m.organization_id = new.organization_id and m.month = new.month) then
    raise exception 'Месяц закрыт: премии и штрафы не меняются' using errcode = '22023', hint = 'payroll_month_closed';
  end if;
  return new;
end;
$$;

--
-- Triggers
--

create or replace trigger payroll_scheme_before_write
    before insert or update on public.payroll_schemes
    for each row execute function private.handle_payroll_scheme_before_write();

create or replace trigger payroll_adjustment_before_write
    before insert or update or delete on public.payroll_adjustments
    for each row execute function private.handle_payroll_adjustment_before_write();

create or replace trigger audit_payroll_scheme
    after insert or update or delete on public.payroll_schemes
    for each row execute function private.audit_row('payroll_scheme', 'doctor_id,sales_id,effective_from,fixed_salary,percent,percent_base,deduct_materials,category_rates,visit_rate,min_guaranteed,note');

create or replace trigger audit_payroll_adjustment
    after insert or update or delete on public.payroll_adjustments
    for each row execute function private.audit_row('payroll_adjustment', 'doctor_id,sales_id,month,kind,amount,note,occurred_on');

create or replace trigger audit_payroll_month
    after insert or delete on public.payroll_months
    for each row execute function private.audit_row('payroll_month', 'month,closed_at');

--
-- Row Level Security
--

alter table public.payroll_schemes enable row level security;
alter table public.payroll_adjustments enable row level security;
alter table public.payroll_months enable row level security;
alter table public.payroll_closed_lines enable row level security;

create policy "Owner and head read schemes" on public.payroll_schemes for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head add schemes" on public.payroll_schemes for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head change schemes" on public.payroll_schemes for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head delete schemes" on public.payroll_schemes for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

create policy "Owner and head read adjustments" on public.payroll_adjustments for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head add adjustments" on public.payroll_adjustments for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head change adjustments" on public.payroll_adjustments for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head delete adjustments" on public.payroll_adjustments for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

create policy "Owner and head read closed months" on public.payroll_months for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head read frozen lines" on public.payroll_closed_lines for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

--
-- Grants
--

revoke all on table public.payroll_schemes from anon;
grant select, insert, update, delete on table public.payroll_schemes to authenticated;
grant all on table public.payroll_schemes to service_role;
revoke all on sequence public.payroll_schemes_id_seq from anon;
grant usage on sequence public.payroll_schemes_id_seq to authenticated;
grant all on sequence public.payroll_schemes_id_seq to service_role;

revoke all on table public.payroll_adjustments from anon;
grant select, insert, update, delete on table public.payroll_adjustments to authenticated;
grant all on table public.payroll_adjustments to service_role;
revoke all on sequence public.payroll_adjustments_id_seq from anon;
grant usage on sequence public.payroll_adjustments_id_seq to authenticated;
grant all on sequence public.payroll_adjustments_id_seq to service_role;

revoke all on table public.payroll_months from anon;
grant select on table public.payroll_months to authenticated;
grant all on table public.payroll_months to service_role;
revoke all on sequence public.payroll_months_id_seq from anon;
grant all on sequence public.payroll_months_id_seq to service_role;

revoke all on table public.payroll_closed_lines from anon;
grant select on table public.payroll_closed_lines to authenticated;
grant all on table public.payroll_closed_lines to service_role;
revoke all on sequence public.payroll_closed_lines_id_seq from anon;
grant all on sequence public.payroll_closed_lines_id_seq to service_role;

revoke all on function private.payroll_scheme_at(bigint, bigint, bigint, date) from public;
grant execute on function private.payroll_scheme_at(bigint, bigint, bigint, date) to service_role;
revoke all on function private.payroll_percent(public.payroll_schemes, bigint, bigint) from public;
grant execute on function private.payroll_percent(public.payroll_schemes, bigint, bigint) to service_role;
revoke all on function private.payroll_mul_div(numeric, numeric, numeric) from public;
grant execute on function private.payroll_mul_div(numeric, numeric, numeric) to service_role;
revoke all on function private.payroll_compute(bigint, date) from public;
grant execute on function private.payroll_compute(bigint, date) to service_role;
revoke all on function private.payroll_month_lines(bigint, date) from public;
grant execute on function private.payroll_month_lines(bigint, date) to service_role;
revoke all on function private.payroll_day_off(bigint, bigint, date) from public;
grant execute on function private.payroll_day_off(bigint, bigint, date) to service_role;
revoke all on function private.payroll_check_access() from public;
grant execute on function private.payroll_check_access() to authenticated, service_role;
revoke all on function private.handle_payroll_scheme_before_write() from public;
revoke all on function private.handle_payroll_adjustment_before_write() from public;

revoke all on function public.payroll_month(date) from public, anon;
grant execute on function public.payroll_month(date) to authenticated, service_role;
revoke all on function public.close_payroll_month(date) from public, anon;
grant execute on function public.close_payroll_month(date) to authenticated, service_role;
revoke all on function public.reopen_payroll_month(date) from public, anon;
grant execute on function public.reopen_payroll_month(date) to authenticated, service_role;
