--
-- Quick replies (stage 14): ready answers inserted in the chat composer with
-- "/" or the lightning button.
--
-- A reply is clinic-wide (sales_id is null: edited by the owner and the head)
-- or personal (sales_id = its author, who alone sees and edits it). Every
-- employee reads the clinic-wide replies and their own. Variables ({имя},
-- {услуга}, {дата_визита}, {клиника}, {сотрудник}) are filled in the app from
-- the deal in context (renderQuickReply), the database stores the raw text.
--
-- Every clinic gets default replies: new clinics through the AFTER INSERT
-- trigger on organizations, existing ones in the migration.
--

create table public.quick_replies (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    title text not null,
    text text not null,
    -- Typed after "/" to find the reply quickly (e.g. /адрес)
    shortcut text,
    -- null: the whole clinic; else the personal reply of this employee
    sales_id bigint,
    position integer not null default 0,
    created_at timestamp with time zone not null default now(),
    constraint quick_replies_title_not_blank check (btrim(title) <> ''),
    constraint quick_replies_text_not_blank check (btrim(text) <> ''),
    constraint quick_replies_shortcut_format check (shortcut is null or shortcut ~ '^[^\s/]+$')
);

alter table public.quick_replies add constraint quick_replies_organization_id_id_key unique (organization_id, id);
alter table public.quick_replies
    add constraint quick_replies_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.quick_replies
    add constraint quick_replies_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id) on delete cascade;

create index quick_replies_organization_id_idx on public.quick_replies using btree (organization_id, sales_id, position);

-- Default replies of a clinic (the clinic edits them in Settings → Quick replies)
CREATE OR REPLACE FUNCTION "private"."seed_quick_replies"("org_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  insert into public.quick_replies (organization_id, title, shortcut, text, position)
  values
    (org_id, 'Приветствие', 'привет',
     'Здравствуйте, {имя}! Меня зовут {сотрудник}, клиника {клиника}. Чем могу помочь?', 0),
    (org_id, 'Адрес и парковка', 'адрес',
     'Наш адрес: [укажите адрес клиники]. Рядом есть бесплатная парковка [уточните, где именно]. Ждём вас!', 1),
    (org_id, 'Стоимость консультации', 'цена',
     '{имя}, консультация врача стоит [укажите цену] ₸. На ней врач проведёт осмотр и составит план лечения.', 2),
    (org_id, 'Запись на консультацию', 'запись',
     '{имя}, записали вас на консультацию {дата_визита}. Если планы изменятся, пожалуйста, напишите нам заранее.', 3),
    (org_id, 'Спасибо, ждём вас', 'спасибо',
     'Спасибо, {имя}! Ждём вас в клинике {клиника}. Хорошего дня!', 4);
end;
$$;

CREATE OR REPLACE FUNCTION "private"."handle_organization_quick_replies"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  perform private.seed_quick_replies(new.id);
  return new;
end;
$$;

create or replace trigger seed_quick_replies
    after insert on public.organizations
    for each row execute function private.handle_organization_quick_replies();

-- Row level security: clinic-wide replies for the owner and the head,
-- personal ones for their author only
alter table public.quick_replies enable row level security;

create policy "Employees read clinic replies and their own" on public.quick_replies for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (sales_id is null or sales_id = (select private.current_sales_id())));
create policy "Own or clinic replies by role can be inserted" on public.quick_replies for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and ((sales_id is null and (select private.current_user_role()) in ('owner', 'head')) or sales_id = (select private.current_sales_id())));
create policy "Own or clinic replies by role can be updated" on public.quick_replies for update to authenticated
    using (organization_id = (select private.current_organization_id()) and ((sales_id is null and (select private.current_user_role()) in ('owner', 'head')) or sales_id = (select private.current_sales_id())))
    with check (organization_id = (select private.current_organization_id()) and ((sales_id is null and (select private.current_user_role()) in ('owner', 'head')) or sales_id = (select private.current_sales_id())));
create policy "Own or clinic replies by role can be deleted" on public.quick_replies for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and ((sales_id is null and (select private.current_user_role()) in ('owner', 'head')) or sales_id = (select private.current_sales_id())));

-- Grants
grant all on table public.quick_replies to anon;
grant all on table public.quick_replies to authenticated;
grant all on table public.quick_replies to service_role;
grant all on sequence public.quick_replies_id_seq to anon, authenticated, service_role;

revoke all on function private.seed_quick_replies(bigint) from public;
grant execute on function private.seed_quick_replies(bigint) to service_role;
revoke all on function private.handle_organization_quick_replies() from public;
grant execute on function private.handle_organization_quick_replies() to service_role;

-- Existing clinics get the default replies too
select private.seed_quick_replies(o.id)
from public.organizations o
where not exists (select 1 from public.quick_replies q where q.organization_id = o.id);
