-- Stage 13: doctors, consultation price, prepayments.
-- New objects are declared in supabase/schemas/13_doctors.sql (copied below,
-- with public.deals_summary moved there from 03_views.sql). Changed functions:
-- handle_deal_after_write (02_functions.sql, logs the doctor and the
-- consultation), private.automessage_vars (08_automessages.sql, variable
-- {врач}), the report functions (09_reports.sql, filter_doctor_id and the
-- breakdowns by doctor).

--
-- Doctors, consultation price, prepayments (stage 13)
--
-- The clinic owner wants the conversion of every doctor. A doctor is not a
-- CRM user: a name and a specialty in a dictionary of the clinic, edited by
-- the owner and the head (Settings → Doctors), read by everybody. An inactive
-- doctor is hidden from the pickers and stays on the old deals. There is no
-- schedule (docs/DECISIONS.md); a MIS integration will map doctors.id to its
-- own ids, so the ids never change and a doctor with deals cannot be deleted.
--
-- The prepayment is not a deal column: a payment has a kind (prepayment or
-- payment), the prepayment of a deal is the sum of its prepayments, and the
-- paid amount stays the sum of all its payments (deals.paid_amount).
--
-- public.deals_summary is declared here rather than in 03_views.sql: it shows
-- the doctor's name, and the schema files load in order. The report functions
-- (09_reports.sql) and the template variables (08_automessages.sql) that read
-- the new columns are plpgsql, whose bodies are resolved when they run.
--

create table public.doctors (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    specialty text,
    is_active boolean not null default true,
    position integer not null default 0,
    created_at timestamp with time zone not null default now(),
    constraint doctors_name_not_blank check (btrim(name) <> '')
);

-- The doctor of a deal and the price of the consultation, in tenge
alter table public.deals add column doctor_id bigint;
alter table public.deals add column consultation_amount bigint;
alter table public.deals add constraint deals_consultation_amount_positive check (consultation_amount >= 0);

-- A payment is a prepayment or a regular payment
alter table public.deal_payments add column kind text not null default 'payment';
alter table public.deal_payments add constraint deal_payments_kind_check check (kind in ('prepayment', 'payment'));

alter table public.doctors add constraint doctors_organization_id_id_key unique (organization_id, id);

alter table public.doctors
    add constraint doctors_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
-- Composite: a deal can only point at a doctor of its own clinic
alter table public.deals
    add constraint deals_doctor_id_fkey foreign key (organization_id, doctor_id) references public.doctors(organization_id, id);

create index doctors_organization_id_idx on public.doctors using btree (organization_id, position);
create index deals_doctor_id_idx on public.deals using btree (organization_id, doctor_id) where doctor_id is not null;

--
-- Views
--

-- Deals with what the board and the lists display
create or replace view public.deals_summary with (security_invoker = on) as
select
    d.id,
    d.organization_id,
    d.patient_id,
    d.pipeline_id,
    d.stage_id,
    d.name,
    d.source_id,
    d.service_id,
    d.plan_amount,
    d.paid_amount,
    d.sales_id,
    d.lost_reason_id,
    d.lost_comment,
    d.appointment_at,
    d.visit_at,
    d.tags,
    d.description,
    d.index,
    d.created_at,
    d.updated_at,
    d.stage_changed_at,
    d.closed_at,
    d.first_response_at,
    d.archived_at,
    s.kind as stage_kind,
    p.first_name as patient_first_name,
    p.last_name as patient_last_name,
    p.phones[1] as patient_phone,
    lower(concat_ws(' ', d.name, p.last_name, p.first_name, p.middle_name, array_to_string(p.phones, ' '))) as search_text,
    (
        select count(*)
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
    ) as nb_open_tasks,
    (
        select min(t.due_date)
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
    ) as next_task_due_at,
    (
        select count(*)
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id and m.direction = 'in' and m.read_at is null
    ) as nb_unread_messages,
    (
        select max(m.sent_at)
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id
    ) as last_message_at,
    (
        select m.text
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id
        order by m.sent_at desc, m.id desc
        limit 1
    ) as last_message_text,
    d.doctor_id,
    dr.name as doctor_name,
    d.consultation_amount,
    (
        select coalesce(sum(pay.amount), 0)::bigint
        from public.deal_payments pay
        where pay.organization_id = d.organization_id and pay.deal_id = d.id and pay.kind = 'prepayment'
    ) as prepayment_amount
from public.deals d
    join public.stages s on s.id = d.stage_id
    join public.patients p on p.organization_id = d.organization_id and p.id = d.patient_id
    left join public.doctors dr on dr.organization_id = d.organization_id and dr.id = d.doctor_id;

--
-- Row Level Security
--

alter table public.doctors enable row level security;

-- A dictionary: every employee reads it (pickers), the owner and the head edit it
create policy "Organization members can read" on public.doctors for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Owner and head can insert" on public.doctors for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can update" on public.doctors for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head can delete" on public.doctors for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

--
-- Grants
--

grant all on table public.doctors to anon;
grant all on table public.doctors to authenticated;
grant all on table public.doctors to service_role;
grant all on sequence public.doctors_id_seq to anon, authenticated, service_role;

grant all on table public.deals_summary to anon;
grant all on table public.deals_summary to authenticated;
grant all on table public.deals_summary to service_role;

--
-- 02_functions.sql: the deal log follows the doctor and the consultation price
--

-- Deal log and first source of the patient
CREATE OR REPLACE FUNCTION "public"."handle_deal_after_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  tracked text[] := array[
    'name', 'patient_id', 'pipeline_id', 'sales_id', 'source_id', 'service_id',
    'plan_amount', 'paid_amount', 'lost_reason_id', 'lost_comment',
    'appointment_at', 'visit_at', 'tags', 'archived_at',
    'doctor_id', 'consultation_amount'
  ];
  field text;
  old_json jsonb;
  new_json jsonb;
  changes jsonb := '{}'::jsonb;
begin
  if tg_op = 'INSERT' then
    insert into public.deal_events (organization_id, deal_id, type, to_stage_id, sales_id)
    values (new.organization_id, new.id, 'created', new.stage_id, private.current_sales_id());

    if new.source_id is not null then
      update public.patients
      set source_id = new.source_id
      where organization_id = new.organization_id
        and id = new.patient_id
        and source_id is null;
    end if;
    if new.sales_id is not null then
      update public.patients
      set sales_id = new.sales_id
      where organization_id = new.organization_id
        and id = new.patient_id
        and sales_id is null;
    end if;
    perform private.create_rule_tasks(new, 'deal_created', null);
    perform private.create_rule_tasks(new, 'stage_entered', new.stage_id);
    return null;
  end if;

  -- A responsible assigned later (first answer, by hand) takes the
  -- unassigned open tasks of the deal
  if new.sales_id is not null and old.sales_id is null then
    update public.tasks
    set sales_id = new.sales_id
    where organization_id = new.organization_id and deal_id = new.id
      and sales_id is null and done_date is null;
    update public.patients
    set sales_id = new.sales_id
    where organization_id = new.organization_id
      and id = new.patient_id
      and sales_id is null;
  end if;
  if new.stage_id is distinct from old.stage_id then
    perform private.create_rule_tasks(new, 'stage_entered', new.stage_id);
  end if;

  old_json := to_jsonb(old);
  new_json := to_jsonb(new);
  foreach field in array tracked loop
    if old_json -> field is distinct from new_json -> field then
      changes := changes || jsonb_build_object(field, jsonb_build_array(old_json -> field, new_json -> field));
    end if;
  end loop;

  if new.stage_id is distinct from old.stage_id then
    insert into public.deal_events (organization_id, deal_id, type, from_stage_id, to_stage_id, changes, sales_id)
    values (new.organization_id, new.id, 'stage_changed', old.stage_id, new.stage_id, changes, private.current_sales_id());
  elsif changes <> '{}'::jsonb then
    insert into public.deal_events (organization_id, deal_id, type, changes, sales_id)
    values (new.organization_id, new.id, 'updated', changes, private.current_sales_id());
  end if;
  return null;
end;
$$;


--
-- 08_automessages.sql: the {врач} variable
--

-- Values of the template variables for a deal. plpgsql: {врач} reads
-- deals.doctor_id and public.doctors, declared later in 13_doctors.sql.
CREATE OR REPLACE FUNCTION "private"."automessage_vars"("deal" "public"."deals") RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  return (
    select jsonb_build_object(
      'имя', nullif(btrim(p.first_name), ''),
      'услуга', sv.name,
      'дата_визита', private.format_visit_date(coalesce(deal.appointment_at, deal.visit_at), o.timezone),
      'клиника', coalesce(nullif(btrim(c.config ->> 'title'), ''), o.name),
      'врач', nullif(btrim(dr.name), '')
    )
    from public.organizations o
      left join public.configuration c on c.organization_id = o.id
      left join public.patients p on p.organization_id = o.id and p.id = deal.patient_id
      left join public.services sv on sv.organization_id = o.id and sv.id = deal.service_id
      left join public.doctors dr on dr.organization_id = o.id and dr.id = deal.doctor_id
    where o.id = deal.organization_id
  );
end;
$$;


--
-- 09_reports.sql: filter_doctor_id on every report, breakdowns by doctor,
-- prepayments. The signatures change: the old functions are dropped.
--

drop function private.report_deal_progress(bigint, bigint, bigint);
drop function public.report_conversion(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint);
drop function public.report_speed(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint);
drop function public.report_lost_reasons(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint);
drop function public.report_money(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint);

-- Every deal of the clinic (matching the filters) with how far it went in its
-- current pipeline: the furthest open or won stage it entered, the key stages
-- reached, when it first reached the "plan agreed" stage, and for a lost deal
-- the stage it was lost from.
CREATE OR REPLACE FUNCTION "private"."report_deal_progress"("filter_pipeline_id" bigint, "filter_sales_id" bigint, "filter_source_id" bigint, "filter_doctor_id" bigint) RETURNS TABLE("deal_id" bigint, "pipeline_id" bigint, "stage_id" bigint, "stage_kind" "text", "sales_id" bigint, "source_id" bigint, "service_id" bigint, "doctor_id" bigint, "lost_reason_id" bigint, "plan_amount" bigint, "paid_amount" bigint, "created_at" timestamp with time zone, "closed_at" timestamp with time zone, "first_response_at" timestamp with time zone, "archived_at" timestamp with time zone, "reached_position" integer, "reached_appointment" boolean, "reached_visit" boolean, "reached_plan" boolean, "agreed_at" timestamp with time zone, "lost_from_stage_id" bigint)
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $$
#variable_conflict use_column
begin
  return query
  with scope as (
    select d.*, s.kind as stage_kind
    from public.deals d
      join public.stages s on s.id = d.stage_id
    where d.organization_id = private.current_organization_id()
      and (filter_pipeline_id is null or d.pipeline_id = filter_pipeline_id)
      and (filter_sales_id is null or d.sales_id = filter_sales_id)
      and (filter_source_id is null or d.source_id = filter_source_id)
      and (filter_doctor_id is null or d.doctor_id = filter_doctor_id)
  ),
  -- Open and won stages entered in the current pipeline, the current one included
  entries as (
    select e.deal_id, s.position, e.created_at
    from public.deal_events e
      join scope d on d.id = e.deal_id
      join public.stages s on s.id = e.to_stage_id and s.pipeline_id = d.pipeline_id
    where e.organization_id = private.current_organization_id()
      and e.type in ('created', 'stage_changed')
      and s.kind <> 'lost'
    union all
    select d.id, s.position, d.stage_changed_at
    from scope d
      join public.stages s on s.id = d.stage_id
    where s.kind <> 'lost'
  ),
  keys as (
    select * from private.report_key_stages()
  ),
  progress as (
    select
      en.deal_id,
      max(en.position) as reached_position,
      min(en.created_at) filter (where en.position >= k.plan_position) as agreed_at
    from entries en
      join scope d on d.id = en.deal_id
      left join keys k on k.pipeline_id = d.pipeline_id
    group by en.deal_id
  )
  select
    d.id, d.pipeline_id, d.stage_id, d.stage_kind, d.sales_id, d.source_id, d.service_id,
    d.doctor_id, d.lost_reason_id, d.plan_amount, d.paid_amount, d.created_at, d.closed_at,
    d.first_response_at, d.archived_at,
    p.reached_position,
    coalesce(p.reached_position >= k.appointment_position, false),
    coalesce(p.reached_position >= k.visit_position, false),
    coalesce(p.reached_position >= k.plan_position, false),
    p.agreed_at,
    case when d.stage_kind = 'lost' then (
      select e.from_stage_id
      from public.deal_events e
      where e.organization_id = d.organization_id and e.deal_id = d.id
        and e.type = 'stage_changed' and e.to_stage_id = d.stage_id
      order by e.created_at desc, e.id desc
      limit 1
    ) end
  from scope d
    left join progress p on p.deal_id = d.id
    left join keys k on k.pipeline_id = d.pipeline_id;
end;
$$;

-- Conversion: the deals created in the period, how far they went.
--   funnel: deals that reached each stage of the pipeline (the chosen one, else
--     the default one); a won or lost stage counts the deals standing in it
--   totals, by_source, by_sales, by_doctor: deals, reached appointment /
--     visit / plan, paid (reached the plan and has a payment), won, lost
CREATE OR REPLACE FUNCTION "public"."report_conversion"("period_from" timestamp with time zone DEFAULT NULL::timestamp with time zone, "period_to" timestamp with time zone DEFAULT NULL::timestamp with time zone, "filter_pipeline_id" bigint DEFAULT NULL::bigint, "filter_sales_id" bigint DEFAULT NULL::bigint, "filter_source_id" bigint DEFAULT NULL::bigint, "filter_doctor_id" bigint DEFAULT NULL::bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $$
declare
  funnel_pipeline_id bigint;
  report jsonb;
begin
  perform private.report_check_access();
  funnel_pipeline_id := coalesce(filter_pipeline_id, (
    select p.id from public.pipelines p
    where p.organization_id = private.current_organization_id()
    order by p.is_default desc, p.position, p.id
    limit 1
  ));

  with cohort as (
    select *
    from private.report_deal_progress(filter_pipeline_id, filter_sales_id, filter_source_id, filter_doctor_id) d
    where (period_from is null or d.created_at >= period_from)
      and (period_to is null or d.created_at < period_to)
  ),
  grouped as (
    select
      grouping(c.source_id) as by_source,
      grouping(c.sales_id) as by_sales,
      grouping(c.doctor_id) as by_doctor,
      c.source_id,
      c.sales_id,
      c.doctor_id,
      count(*) as deals,
      count(*) filter (where c.reached_appointment) as appointment,
      count(*) filter (where c.reached_visit) as visit,
      count(*) filter (where c.reached_plan) as plan,
      count(*) filter (where c.reached_plan and c.paid_amount > 0) as paid,
      count(*) filter (where c.stage_kind = 'won') as won,
      count(*) filter (where c.stage_kind = 'lost') as lost
    from cohort c
    group by grouping sets ((), (c.source_id), (c.sales_id), (c.doctor_id))
  ),
  metrics as (
    select g.*, jsonb_build_object(
      'deals', g.deals, 'appointment', g.appointment, 'visit', g.visit, 'plan', g.plan,
      'paid', g.paid, 'won', g.won, 'lost', g.lost
    ) as row_json
    from grouped g
  )
  select jsonb_build_object(
    'pipeline_id', funnel_pipeline_id,
    'funnel', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'stage_id', s.id, 'name', s.name, 'kind', s.kind, 'color', s.color,
        'deals', (
          select count(*) from cohort c
          where c.pipeline_id = s.pipeline_id
            and case when s.kind = 'open' then c.reached_position >= s.position else c.stage_id = s.id end
        )
      ) order by s.position, s.id), '[]'::jsonb)
      from public.stages s
      where s.pipeline_id = funnel_pipeline_id
    ),
    'totals', (select m.row_json from metrics m where m.by_source = 1 and m.by_sales = 1 and m.by_doctor = 1),
    'by_source', (
      select coalesce(jsonb_agg(
        jsonb_build_object('id', m.source_id, 'name', ls.name) || m.row_json
        order by m.deals desc, ls.position, ls.id
      ), '[]'::jsonb)
      from metrics m
        left join public.lead_sources ls on ls.id = m.source_id
      where m.by_source = 0
    ),
    'by_sales', (
      select coalesce(jsonb_agg(
        jsonb_build_object('id', m.sales_id, 'name', btrim(concat_ws(' ', sa.first_name, sa.last_name))) || m.row_json
        order by m.deals desc, sa.last_name, sa.id
      ), '[]'::jsonb)
      from metrics m
        left join public.sales sa on sa.id = m.sales_id
      where m.by_sales = 0
    ),
    'by_doctor', (
      select coalesce(jsonb_agg(
        jsonb_build_object('id', m.doctor_id, 'name', dr.name) || m.row_json
        order by m.deals desc, dr.position, dr.id
      ), '[]'::jsonb)
      from metrics m
        left join public.doctors dr on dr.id = m.doctor_id
      where m.by_doctor = 0
    )
  ) into report;
  return report;
end;
$$;

-- Speed and KPI.
--   first_response: deals created in the period that got an answer, and the
--     average time from creation to the first answer, in seconds
--   stages: open stages (of the chosen pipeline, else all), the stays that
--     started in the period and their average length (a stay still going on
--     counts until now)
--   by_sales: per employee, deals created in the period, first answer, tasks
--     created / done / due (already due in the period) / overdue (not done by
--     their due date), messages sent, and now: open deals, open deals without
--     an open task
CREATE OR REPLACE FUNCTION "public"."report_speed"("period_from" timestamp with time zone DEFAULT NULL::timestamp with time zone, "period_to" timestamp with time zone DEFAULT NULL::timestamp with time zone, "filter_pipeline_id" bigint DEFAULT NULL::bigint, "filter_sales_id" bigint DEFAULT NULL::bigint, "filter_source_id" bigint DEFAULT NULL::bigint, "filter_doctor_id" bigint DEFAULT NULL::bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $$
declare
  report jsonb;
begin
  perform private.report_check_access();

  with scope as (
    -- Tasks and messages belong to an employee whoever leads the deal
    select * from private.report_deal_progress(filter_pipeline_id, null, filter_source_id, filter_doctor_id)
  ),
  cohort as (
    select * from scope d
    where (period_from is null or d.created_at >= period_from)
      and (period_to is null or d.created_at < period_to)
  ),
  answered as (
    select c.sales_id, extract(epoch from c.first_response_at - c.created_at) as seconds
    from cohort c
    where c.first_response_at is not null and c.first_response_at >= c.created_at
      and (filter_sales_id is null or c.sales_id = filter_sales_id)
  ),
  stays as (
    select
      e.to_stage_id as stage_id,
      e.created_at as entered_at,
      coalesce(
        lead(e.created_at) over (partition by e.deal_id order by e.created_at, e.id),
        case when d.stage_id = e.to_stage_id then now() end
      ) as left_at,
      d.sales_id,
      d.source_id,
      d.doctor_id
    from public.deal_events e
      join public.deals d on d.organization_id = e.organization_id and d.id = e.deal_id
    where e.organization_id = private.current_organization_id()
      and e.type in ('created', 'stage_changed')
  ),
  stage_stats as (
    select st.stage_id, count(*) as stays, round(avg(extract(epoch from st.left_at - st.entered_at))) as avg_seconds
    from stays st
    where st.left_at is not null
      and (period_from is null or st.entered_at >= period_from)
      and (period_to is null or st.entered_at < period_to)
      and (filter_sales_id is null or st.sales_id = filter_sales_id)
      and (filter_source_id is null or st.source_id = filter_source_id)
      and (filter_doctor_id is null or st.doctor_id = filter_doctor_id)
    group by st.stage_id
  ),
  staff as (
    select
      sa.id,
      btrim(concat_ws(' ', sa.first_name, sa.last_name)) as name,
      sa.last_name,
      sa.disabled,
      (select count(*) from cohort c where c.sales_id = sa.id) as deals,
      (select round(avg(a.seconds)) from answered a where a.sales_id = sa.id) as first_response_seconds,
      (select count(*) from public.tasks t join scope d on d.deal_id = t.deal_id
        where t.organization_id = sa.organization_id and t.sales_id = sa.id
          and (period_from is null or t.created_at >= period_from)
          and (period_to is null or t.created_at < period_to)) as tasks_created,
      (select count(*) from public.tasks t join scope d on d.deal_id = t.deal_id
        where t.organization_id = sa.organization_id and t.sales_id = sa.id
          and t.done_date is not null
          and (period_from is null or t.done_date >= period_from)
          and (period_to is null or t.done_date < period_to)) as tasks_done,
      (select count(*) from public.tasks t join scope d on d.deal_id = t.deal_id
        where t.organization_id = sa.organization_id and t.sales_id = sa.id
          and t.due_date < now()
          and (period_from is null or t.due_date >= period_from)
          and (period_to is null or t.due_date < period_to)) as tasks_due,
      (select count(*) from public.tasks t join scope d on d.deal_id = t.deal_id
        where t.organization_id = sa.organization_id and t.sales_id = sa.id
          and t.due_date < now()
          and (period_from is null or t.due_date >= period_from)
          and (period_to is null or t.due_date < period_to)
          and (t.done_date is null or t.done_date > t.due_date)) as tasks_overdue,
      (select count(*) from public.messages m join scope d on d.deal_id = m.deal_id
        where m.organization_id = sa.organization_id and m.sales_id = sa.id and m.direction = 'out'
          and (period_from is null or m.sent_at >= period_from)
          and (period_to is null or m.sent_at < period_to)) as messages_sent,
      (select count(*) from scope d
        where d.sales_id = sa.id and d.stage_kind = 'open' and d.archived_at is null) as open_deals,
      (select count(*) from scope d
        where d.sales_id = sa.id and d.stage_kind = 'open' and d.archived_at is null
          and not exists (
            select 1 from public.tasks t
            where t.organization_id = sa.organization_id and t.deal_id = d.deal_id and t.done_date is null
          )) as deals_without_task
    from public.sales sa
    where sa.organization_id = private.current_organization_id()
      and (filter_sales_id is null or sa.id = filter_sales_id)
  )
  select jsonb_build_object(
    'first_response', (
      select jsonb_build_object('deals', count(*), 'avg_seconds', round(avg(a.seconds)))
      from answered a
    ),
    'stages', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'stage_id', s.id, 'name', s.name, 'color', s.color,
        'pipeline_id', p.id, 'pipeline_name', p.name,
        'stays', coalesce(ss.stays, 0), 'avg_seconds', ss.avg_seconds
      ) order by p.position, p.id, s.position, s.id), '[]'::jsonb)
      from public.stages s
        join public.pipelines p on p.id = s.pipeline_id
        left join stage_stats ss on ss.stage_id = s.id
      where s.organization_id = private.current_organization_id()
        and s.kind = 'open'
        and (filter_pipeline_id is null or s.pipeline_id = filter_pipeline_id)
    ),
    'by_sales', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', st.id, 'name', st.name, 'deals', st.deals,
        'first_response_seconds', st.first_response_seconds,
        'tasks_created', st.tasks_created, 'tasks_done', st.tasks_done,
        'tasks_due', st.tasks_due, 'tasks_overdue', st.tasks_overdue,
        'messages_sent', st.messages_sent,
        'open_deals', st.open_deals, 'deals_without_task', st.deals_without_task
      ) order by st.deals desc, st.last_name, st.id), '[]'::jsonb)
      from staff st
      where not st.disabled
        or st.deals + st.tasks_created + st.tasks_done + st.messages_sent + st.open_deals > 0
    )
  ) into report;
  return report;
end;
$$;

-- Lost reasons: the deals lost in the period (closed in a lost stage), by
-- reason and by the stage they were lost from, with their treatment plans
CREATE OR REPLACE FUNCTION "public"."report_lost_reasons"("period_from" timestamp with time zone DEFAULT NULL::timestamp with time zone, "period_to" timestamp with time zone DEFAULT NULL::timestamp with time zone, "filter_pipeline_id" bigint DEFAULT NULL::bigint, "filter_sales_id" bigint DEFAULT NULL::bigint, "filter_source_id" bigint DEFAULT NULL::bigint, "filter_doctor_id" bigint DEFAULT NULL::bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $$
declare
  report jsonb;
begin
  perform private.report_check_access();

  with lost as (
    select *
    from private.report_deal_progress(filter_pipeline_id, filter_sales_id, filter_source_id, filter_doctor_id) d
    where d.stage_kind = 'lost'
      and (period_from is null or d.closed_at >= period_from)
      and (period_to is null or d.closed_at < period_to)
  )
  select jsonb_build_object(
    'totals', (
      select jsonb_build_object('deals', count(*), 'plan_amount', coalesce(sum(l.plan_amount), 0))
      from lost l
    ),
    'by_reason', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', r.lost_reason_id, 'name', lr.name, 'deals', r.deals, 'plan_amount', r.plan_amount
      ) order by r.deals desc, lr.position, lr.id), '[]'::jsonb)
      from (
        select l.lost_reason_id, count(*) as deals, sum(l.plan_amount) as plan_amount
        from lost l
        group by l.lost_reason_id
      ) r
        left join public.lost_reasons lr on lr.id = r.lost_reason_id
    ),
    'by_stage', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', r.lost_from_stage_id, 'name', s.name, 'pipeline_name', p.name,
        'deals', r.deals, 'plan_amount', r.plan_amount
      ) order by p.position, p.id, s.position, s.id), '[]'::jsonb)
      from (
        select l.lost_from_stage_id, count(*) as deals, sum(l.plan_amount) as plan_amount
        from lost l
        group by l.lost_from_stage_id
      ) r
        left join public.stages s on s.id = r.lost_from_stage_id
        left join public.pipelines p on p.id = s.pipeline_id
    )
  ) into report;
  return report;
end;
$$;

-- Money: treatment plans agreed in the period (the deal first reached the
-- "plan agreed" stage or a later one), payments received in the period (dates
-- in the clinic's time zone) and the prepayments among them, the average
-- check (paid / paying deals), in total, by service, by employee and by doctor
CREATE OR REPLACE FUNCTION "public"."report_money"("period_from" timestamp with time zone DEFAULT NULL::timestamp with time zone, "period_to" timestamp with time zone DEFAULT NULL::timestamp with time zone, "filter_pipeline_id" bigint DEFAULT NULL::bigint, "filter_sales_id" bigint DEFAULT NULL::bigint, "filter_source_id" bigint DEFAULT NULL::bigint, "filter_doctor_id" bigint DEFAULT NULL::bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO ''
    AS $$
declare
  clinic_tz text;
  first_day date;
  after_last_day date;
  report jsonb;
begin
  perform private.report_check_access();
  select o.timezone into clinic_tz
  from public.organizations o
  where o.id = private.current_organization_id();
  first_day := (period_from at time zone coalesce(clinic_tz, 'Asia/Almaty'))::date;
  after_last_day := (period_to at time zone coalesce(clinic_tz, 'Asia/Almaty'))::date;

  with per_deal as (
    select
      d.deal_id,
      d.service_id,
      d.sales_id,
      d.doctor_id,
      d.plan_amount,
      coalesce(
        d.agreed_at is not null
          and (period_from is null or d.agreed_at >= period_from)
          and (period_to is null or d.agreed_at < period_to),
        false
      ) as agreed,
      coalesce((
        select sum(p.amount)
        from public.deal_payments p
        where p.organization_id = private.current_organization_id() and p.deal_id = d.deal_id
          and (first_day is null or p.paid_at >= first_day)
          and (after_last_day is null or p.paid_at < after_last_day)
      ), 0) as paid,
      coalesce((
        select sum(p.amount)
        from public.deal_payments p
        where p.organization_id = private.current_organization_id() and p.deal_id = d.deal_id
          and p.kind = 'prepayment'
          and (first_day is null or p.paid_at >= first_day)
          and (after_last_day is null or p.paid_at < after_last_day)
      ), 0) as prepaid
    from private.report_deal_progress(filter_pipeline_id, filter_sales_id, filter_source_id, filter_doctor_id) d
  ),
  grouped as (
    select
      grouping(pd.service_id) as by_service,
      grouping(pd.sales_id) as by_sales,
      grouping(pd.doctor_id) as by_doctor,
      pd.service_id,
      pd.sales_id,
      pd.doctor_id,
      count(*) filter (where pd.agreed) as agreed_deals,
      coalesce(sum(pd.plan_amount) filter (where pd.agreed), 0) as agreed_amount,
      coalesce(sum(pd.paid), 0) as paid_amount,
      coalesce(sum(pd.prepaid), 0) as prepaid_amount,
      count(*) filter (where pd.paid > 0) as paying_deals
    from per_deal pd
    where pd.agreed or pd.paid > 0
    group by grouping sets ((), (pd.service_id), (pd.sales_id), (pd.doctor_id))
  ),
  metrics as (
    select g.*, jsonb_build_object(
      'agreed_deals', g.agreed_deals,
      'agreed_amount', g.agreed_amount,
      'paid_amount', g.paid_amount,
      'prepaid_amount', g.prepaid_amount,
      'paying_deals', g.paying_deals,
      'average_check', case when g.paying_deals > 0 then round(g.paid_amount / g.paying_deals) end
    ) as row_json
    from grouped g
  )
  select jsonb_build_object(
    'totals', (select m.row_json from metrics m where m.by_service = 1 and m.by_sales = 1 and m.by_doctor = 1),
    'by_service', (
      select coalesce(jsonb_agg(
        jsonb_build_object('id', m.service_id, 'name', sv.name) || m.row_json
        order by m.paid_amount desc, m.agreed_amount desc, sv.position, sv.id
      ), '[]'::jsonb)
      from metrics m
        left join public.services sv on sv.id = m.service_id
      where m.by_service = 0
    ),
    'by_sales', (
      select coalesce(jsonb_agg(
        jsonb_build_object('id', m.sales_id, 'name', btrim(concat_ws(' ', sa.first_name, sa.last_name))) || m.row_json
        order by m.paid_amount desc, m.agreed_amount desc, sa.last_name, sa.id
      ), '[]'::jsonb)
      from metrics m
        left join public.sales sa on sa.id = m.sales_id
      where m.by_sales = 0
    ),
    'by_doctor', (
      select coalesce(jsonb_agg(
        jsonb_build_object('id', m.doctor_id, 'name', dr.name) || m.row_json
        order by m.paid_amount desc, m.agreed_amount desc, dr.position, dr.id
      ), '[]'::jsonb)
      from metrics m
        left join public.doctors dr on dr.id = m.doctor_id
      where m.by_doctor = 0
    )
  ) into report;
  return report;
end;
$$;

-- Grants: the helpers are called by the report functions with the caller's
-- rights; the reports themselves are for signed-in users (checked inside)
revoke all on function private.report_check_access() from public;
grant execute on function private.report_check_access() to authenticated;
grant execute on function private.report_check_access() to service_role;
revoke all on function private.report_key_stages() from public;
grant execute on function private.report_key_stages() to authenticated;
grant execute on function private.report_key_stages() to service_role;
revoke all on function private.report_deal_progress(bigint, bigint, bigint, bigint) from public;
grant execute on function private.report_deal_progress(bigint, bigint, bigint, bigint) to authenticated;
grant execute on function private.report_deal_progress(bigint, bigint, bigint, bigint) to service_role;

revoke all on function public.report_conversion(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint) from public, anon;
grant execute on function public.report_conversion(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint) to authenticated;
grant execute on function public.report_conversion(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint) to service_role;
revoke all on function public.report_speed(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint) from public, anon;
grant execute on function public.report_speed(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint) to authenticated;
grant execute on function public.report_speed(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint) to service_role;
revoke all on function public.report_lost_reasons(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint) from public, anon;
grant execute on function public.report_lost_reasons(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint) to authenticated;
grant execute on function public.report_lost_reasons(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint) to service_role;
revoke all on function public.report_money(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint) from public, anon;
grant execute on function public.report_money(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint) to authenticated;
grant execute on function public.report_money(timestamp with time zone, timestamp with time zone, bigint, bigint, bigint, bigint) to service_role;
