-- Stage 2: domain model of a dental clinic CRM.
--
-- Patients replace contacts, companies are removed, deals get configurable
-- pipelines and stages, dictionaries (services, sources, lost reasons),
-- payments, a change log, tasks bound to deals and calls.
--
-- CRM records of stage 1 (contacts, companies, deals, notes, tasks) are
-- dropped: nothing was in production. Organizations, staff, configuration
-- and tags are kept; every existing organization gets the default pipeline
-- and dictionaries.

drop view if exists public.activity_log;
drop view if exists public.companies_summary;
drop view if exists public.contacts_summary;

drop table if exists public.tasks cascade;
drop table if exists public.contact_notes cascade;
drop table if exists public.deal_notes cascade;
drop table if exists public.deals cascade;
drop table if exists public.contacts cascade;
drop table if exists public.companies cascade;
drop table if exists public.favicons_excluded_domains cascade;

drop function if exists public.get_avatar_for_email(text);
drop function if exists public.get_domain_favicon(text);
drop function if exists public.handle_company_saved();
drop function if exists public.handle_contact_note_created_or_updated();
drop function if exists public.handle_contact_saved();
drop function if exists public.merge_contacts(bigint, bigint);
drop function if exists public.lowercase_email_jsonb();


-- >>> from supabase/schemas/01_tables.sql
create extension if not exists "citext" with schema "extensions";

create schema if not exists "private";

create or replace function private.current_organization_id() returns bigint
    language plpgsql stable security definer
    set search_path to ''
    as $$
begin
  return (
    select s.organization_id
    from public.sales s
    where s.user_id = auth.uid() and not s.disabled
  );
end;
$$;

create or replace function private.current_user_role() returns text
    language plpgsql stable security definer
    set search_path to ''
    as $$
begin
  return (
    select s.role
    from public.sales s
    where s.user_id = auth.uid() and not s.disabled
  );
end;
$$;

create or replace function private.current_sales_id() returns bigint
    language plpgsql stable security definer
    set search_path to ''
    as $$
begin
  return (
    select s.id
    from public.sales s
    where s.user_id = auth.uid() and not s.disabled
  );
end;
$$;

create table public.organization_settings (
    organization_id bigint primary key,
    -- Which deals a manager (administrator / curator) sees
    manager_deal_visibility text not null default 'all',
    -- Moving a deal to another pipeline: to its first stage, or the user picks the stage
    pipeline_move_mode text not null default 'first_stage',
    constraint organization_settings_visibility_check
        check (manager_deal_visibility in ('all', 'own', 'own_and_unassigned')),
    constraint organization_settings_pipeline_move_check
        check (pipeline_move_mode in ('first_stage', 'choose_stage'))
);

create table public.pipelines (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    position integer not null default 0,
    is_default boolean not null default false,
    created_at timestamp with time zone not null default now(),
    constraint pipelines_name_not_blank check (btrim(name) <> '')
);

create table public.stages (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    pipeline_id bigint not null,
    name text not null,
    position integer not null default 0,
    color text not null default '#83A2DB',
    kind text not null default 'open',
    created_at timestamp with time zone not null default now(),
    constraint stages_kind_check check (kind in ('open', 'won', 'lost')),
    constraint stages_name_not_blank check (btrim(name) <> '')
);

create table public.services (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    position integer not null default 0,
    is_archived boolean not null default false,
    constraint services_name_not_blank check (btrim(name) <> '')
);

create table public.lead_sources (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    code text,
    is_system boolean not null default false,
    position integer not null default 0,
    is_archived boolean not null default false,
    constraint lead_sources_name_not_blank check (btrim(name) <> ''),
    constraint lead_sources_system_has_code check (not is_system or code is not null)
);

create table public.lost_reasons (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    position integer not null default 0,
    is_archived boolean not null default false,
    constraint lost_reasons_name_not_blank check (btrim(name) <> '')
);

create table public.patients (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    first_name text,
    last_name text,
    middle_name text,
    -- [{ "number": "+77011234567", "type": "Mobile" }], numbers normalized by trigger
    phone_jsonb jsonb not null default '[]'::jsonb,
    -- Normalized numbers, maintained by trigger, for search and deduplication
    phones text[] not null default '{}'::text[],
    birth_date date,
    city text,
    whatsapp text,
    instagram text,
    telegram text,
    -- Source of the first request (filled from the first deal)
    source_id bigint,
    tags bigint[] not null default '{}'::bigint[],
    sales_id bigint,
    gender text,
    avatar jsonb,
    background text,
    status text,
    first_seen timestamp with time zone not null default now(),
    last_seen timestamp with time zone not null default now(),
    constraint patients_phone_jsonb_is_array check (jsonb_typeof(phone_jsonb) = 'array')
);

create table public.patient_notes (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    patient_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    patient_id bigint not null,
    -- Filled with the default pipeline and its first stage when omitted
    pipeline_id bigint not null,
    stage_id bigint not null,
    name text,
    source_id bigint,
    service_id bigint,
    -- Amounts in tenge: treatment plan and total of payments (maintained by trigger)
    plan_amount bigint not null default 0,
    paid_amount bigint not null default 0,
    sales_id bigint,
    lost_reason_id bigint,
    lost_comment text,
    appointment_at timestamp with time zone,
    visit_at timestamp with time zone,
    tags bigint[] not null default '{}'::bigint[],
    description text,
    index integer not null default 0,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    stage_changed_at timestamp with time zone not null default now(),
    closed_at timestamp with time zone,
    first_response_at timestamp with time zone,
    archived_at timestamp with time zone,
    constraint deals_plan_amount_positive check (plan_amount >= 0)
);

create table public.deal_notes (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.deal_payments (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    deal_id bigint not null,
    amount bigint not null,
    paid_at date not null default current_date,
    comment text,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    constraint deal_payments_amount_positive check (amount > 0)
);

create table public.deal_events (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    deal_id bigint not null,
    type text not null,
    from_stage_id bigint,
    to_stage_id bigint,
    changes jsonb not null default '{}'::jsonb,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    constraint deal_events_type_check check (type in ('created', 'stage_changed', 'updated'))
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    deal_id bigint not null,
    type text not null default 'call',
    text text,
    due_date timestamp with time zone not null,
    done_date timestamp with time zone,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    constraint tasks_type_check check (type in ('call', 'message', 'reminder', 'other'))
);

create table public.calls (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    patient_id bigint not null,
    deal_id bigint,
    direction text not null,
    duration_seconds integer not null default 0,
    comment text,
    called_at timestamp with time zone not null default now(),
    sales_id bigint,
    external_id text,
    recording_url text,
    created_at timestamp with time zone not null default now(),
    constraint calls_direction_check check (direction in ('in', 'out')),
    constraint calls_duration_positive check (duration_seconds >= 0)
);

alter table public.pipelines add constraint pipelines_organization_id_id_key unique (organization_id, id);

alter table public.stages add constraint stages_organization_id_id_key unique (organization_id, id);

alter table public.stages add constraint stages_pipeline_id_id_key unique (pipeline_id, id);

alter table public.services add constraint services_organization_id_id_key unique (organization_id, id);

alter table public.lead_sources add constraint lead_sources_organization_id_id_key unique (organization_id, id);

alter table public.lost_reasons add constraint lost_reasons_organization_id_id_key unique (organization_id, id);

alter table public.patients add constraint patients_organization_id_id_key unique (organization_id, id);

alter table public.patient_notes add constraint patient_notes_organization_id_id_key unique (organization_id, id);

alter table public.deals add constraint deals_organization_id_id_key unique (organization_id, id);

alter table public.deal_notes add constraint deal_notes_organization_id_id_key unique (organization_id, id);

alter table public.deal_payments add constraint deal_payments_organization_id_id_key unique (organization_id, id);

alter table public.tasks add constraint tasks_organization_id_id_key unique (organization_id, id);

alter table public.calls add constraint calls_organization_id_id_key unique (organization_id, id);

alter table public.organization_settings
    add constraint organization_settings_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;

alter table public.pipelines
    add constraint pipelines_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;

alter table public.stages
    add constraint stages_pipeline_id_fkey foreign key (organization_id, pipeline_id) references public.pipelines(organization_id, id) on delete cascade;

alter table public.services
    add constraint services_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;

alter table public.lead_sources
    add constraint lead_sources_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;

alter table public.lost_reasons
    add constraint lost_reasons_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;

alter table public.patients
    add constraint patients_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;

alter table public.patients
    add constraint patients_source_id_fkey foreign key (organization_id, source_id) references public.lead_sources(organization_id, id);

alter table public.patients
    add constraint patients_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.patient_notes
    add constraint patient_notes_patient_id_fkey foreign key (organization_id, patient_id) references public.patients(organization_id, id) on delete cascade;

alter table public.patient_notes
    add constraint patient_notes_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.deals
    add constraint deals_patient_id_fkey foreign key (organization_id, patient_id) references public.patients(organization_id, id) on delete cascade;

alter table public.deals
    add constraint deals_pipeline_id_fkey foreign key (organization_id, pipeline_id) references public.pipelines(organization_id, id);

alter table public.deals
    add constraint deals_stage_id_fkey foreign key (pipeline_id, stage_id) references public.stages(pipeline_id, id);

alter table public.deals
    add constraint deals_source_id_fkey foreign key (organization_id, source_id) references public.lead_sources(organization_id, id);

alter table public.deals
    add constraint deals_service_id_fkey foreign key (organization_id, service_id) references public.services(organization_id, id);

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.deals
    add constraint deals_lost_reason_id_fkey foreign key (organization_id, lost_reason_id) references public.lost_reasons(organization_id, id);

alter table public.deal_notes
    add constraint deal_notes_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;

alter table public.deal_notes
    add constraint deal_notes_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.deal_payments
    add constraint deal_payments_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;

alter table public.deal_payments
    add constraint deal_payments_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.deal_events
    add constraint deal_events_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;

alter table public.tasks
    add constraint tasks_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;

alter table public.tasks
    add constraint tasks_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

alter table public.calls
    add constraint calls_patient_id_fkey foreign key (organization_id, patient_id) references public.patients(organization_id, id) on delete cascade;

alter table public.calls
    add constraint calls_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;

alter table public.calls
    add constraint calls_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

create unique index pipelines_one_default_idx on public.pipelines using btree (organization_id) where is_default;

create index stages_pipeline_id_idx on public.stages using btree (pipeline_id, position);

create unique index lead_sources_code_idx on public.lead_sources using btree (organization_id, code) where code is not null;

create index patients_phones_idx on public.patients using gin (phones);

create index patients_last_seen_idx on public.patients using btree (organization_id, last_seen desc);

create index patient_notes_patient_id_idx on public.patient_notes using btree (organization_id, patient_id);

create index deals_board_idx on public.deals using btree (organization_id, pipeline_id, stage_id, index);

create index deals_patient_id_idx on public.deals using btree (organization_id, patient_id);

create index deals_sales_id_idx on public.deals using btree (organization_id, sales_id);

create index deal_notes_deal_id_idx on public.deal_notes using btree (organization_id, deal_id);

create index deal_payments_deal_id_idx on public.deal_payments using btree (organization_id, deal_id);

create index deal_events_deal_id_idx on public.deal_events using btree (organization_id, deal_id, created_at);

create index tasks_deal_id_idx on public.tasks using btree (organization_id, deal_id);

create index tasks_open_due_idx on public.tasks using btree (organization_id, due_date) where done_date is null;

create index calls_patient_id_idx on public.calls using btree (organization_id, patient_id);

create unique index calls_external_id_idx on public.calls using btree (organization_id, external_id) where external_id is not null;

-- >>> from supabase/schemas/02_functions.sql
CREATE OR REPLACE FUNCTION "public"."cleanup_note_attachments"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
    DECLARE
      payload jsonb;
      request_headers jsonb;
      auth_header text;
    BEGIN
      request_headers := coalesce(
        nullif(current_setting('request.headers', true), '')::jsonb,
        '{}'::jsonb
      );
      auth_header := request_headers ->> 'authorization';

      IF auth_header IS NULL OR auth_header = '' THEN
        IF TG_OP = 'DELETE' THEN
          RETURN OLD;
        END IF;

        RETURN NEW;
      END IF;

      payload := jsonb_build_object(
        'old_record', OLD,
        'record', NEW,
        'type', TG_OP
      );

      PERFORM net.http_post(
        url := public.get_note_attachments_function_url(),
        body := payload,
        params := '{}'::jsonb,
        headers := jsonb_build_object(
          'Content-Type',
          'application/json',
          'Authorization',
          auth_header
        ),
        timeout_milliseconds := 10000
      );

      IF TG_OP = 'DELETE' THEN
        RETURN OLD;
      END IF;

      RETURN NEW;
    END;
    $$;

CREATE OR REPLACE FUNCTION "public"."get_note_attachments_function_url"() RETURNS "text"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
    DECLARE
      issuer text;
      function_url text;
    BEGIN
      issuer := coalesce(
        nullif(current_setting('request.jwt.claim.iss', true), ''),
        (
          coalesce(
            nullif(current_setting('request.jwt.claims', true), ''),
            '{}'
          )::jsonb ->> 'iss'
        )
      );
      issuer := nullif(issuer, '');
      IF issuer IS NOT NULL THEN
        issuer := rtrim(issuer, '/');
        IF right(issuer, 8) = '/auth/v1' THEN
          function_url :=
            left(issuer, length(issuer) - 8) || '/functions/v1/delete_note_attachments';

          IF function_url LIKE 'http://127.0.0.1:%' THEN
            RETURN replace(
              function_url,
              'http://127.0.0.1:',
              'http://host.docker.internal:'
            );
          END IF;

          IF function_url LIKE 'http://localhost:%' THEN
            RETURN replace(
              function_url,
              'http://localhost:',
              'http://host.docker.internal:'
            );
          END IF;

          RETURN function_url;
        END IF;
      END IF;

      RETURN 'http://host.docker.internal:54321/functions/v1/delete_note_attachments';
    END;
    $$;

CREATE OR REPLACE FUNCTION "public"."get_user_id_by_email"("email" "text") RETURNS TABLE("id" "uuid")
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $_$
BEGIN
  RETURN QUERY SELECT au.id FROM auth.users au WHERE au.email = $1;

END;

$_$;

CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
-- A new auth user either:
--  * was invited by a clinic owner: the users edge function (service role) puts
--    organization_id and role in app_metadata, which end users cannot write;
--  * signed up by themselves: a new organization is created and they own it.
declare
  org_id bigint;
  user_role text;
  org_name text;
begin
  org_id := nullif(new.raw_app_meta_data ->> 'organization_id', '')::bigint;

  if org_id is not null then
    if not exists (select 1 from public.organizations o where o.id = org_id) then
      raise exception 'Organization % does not exist', org_id;
    end if;
    user_role := coalesce(new.raw_app_meta_data ->> 'role', 'manager');
    if user_role not in ('head', 'manager') then
      user_role := 'manager';
    end if;
  else
    org_name := coalesce(
      nullif(btrim(new.raw_user_meta_data ->> 'organization_name'), ''),
      'Моя клиника'
    );
    insert into public.organizations (name) values (org_name) returning id into org_id;
    perform private.seed_organization(org_id);
    user_role := 'owner';
  end if;

  insert into public.sales (organization_id, first_name, last_name, email, user_id, role)
  values (
    org_id,
    coalesce(new.raw_user_meta_data ->> 'first_name', new.raw_user_meta_data -> 'custom_claims' ->> 'first_name', 'Pending'),
    coalesce(new.raw_user_meta_data ->> 'last_name', new.raw_user_meta_data -> 'custom_claims' ->> 'last_name', 'Pending'),
    new.email,
    new.id,
    user_role
  );
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."handle_update_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  update public.sales
  set
    first_name = coalesce(new.raw_user_meta_data ->> 'first_name', new.raw_user_meta_data -> 'custom_claims' ->> 'first_name', 'Pending'),
    last_name = coalesce(new.raw_user_meta_data ->> 'last_name', new.raw_user_meta_data -> 'custom_claims' ->> 'last_name', 'Pending'),
    email = new.email
  where user_id = new.id;

  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."is_admin"() RETURNS boolean
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  return coalesce(private.current_user_role() in ('owner', 'head'), false);
end;
$$;

CREATE OR REPLACE FUNCTION "public"."set_sales_id_default"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
BEGIN
  IF NEW.sales_id IS NULL THEN
    SELECT id INTO NEW.sales_id FROM sales WHERE user_id = auth.uid();
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION "private"."normalize_phone"("raw" "text") RETURNS "text"
    LANGUAGE "plpgsql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
declare
  digits text;
begin
  if raw is null then
    return null;
  end if;
  digits := regexp_replace(raw, '\D', '', 'g');
  if digits = '' then
    return null;
  end if;
  if length(digits) = 11 and left(digits, 1) in ('7', '8') then
    return '+7' || substr(digits, 2);
  end if;
  if length(digits) = 10 then
    return '+7' || digits;
  end if;
  return '+' || digits;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."handle_patient_saved"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
begin
  new.phone_jsonb := coalesce((
    select jsonb_agg(jsonb_set(e, '{number}', to_jsonb(private.normalize_phone(e ->> 'number'))))
    from jsonb_array_elements(new.phone_jsonb) as e
    where private.normalize_phone(e ->> 'number') is not null
  ), '[]'::jsonb);
  new.whatsapp := private.normalize_phone(new.whatsapp);
  new.instagram := nullif(lower(ltrim(btrim(coalesce(new.instagram, '')), '@')), '');
  new.telegram := nullif(ltrim(btrim(coalesce(new.telegram, '')), '@'), '');
  new.phones := array(
    select distinct n
    from (
      select private.normalize_phone(e ->> 'number') as n
      from jsonb_array_elements(new.phone_jsonb) as e
      union
      select new.whatsapp
    ) as numbers
    where n is not null
    order by n
  );
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."find_patients_by_phone"("phone" "text") RETURNS SETOF "public"."patients"
    LANGUAGE "sql" STABLE
    SET "search_path" TO ''
    AS $$
  select p.*
  from public.patients p
  where private.normalize_phone(phone) is not null
    and p.phones @> array[private.normalize_phone(phone)];
$$;

CREATE OR REPLACE FUNCTION "public"."handle_patient_note_created"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  update public.patients
  set last_seen = new.date
  where organization_id = new.organization_id
    and id = new.patient_id
    and last_seen < new.date;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "private"."seed_organization"("org_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  pipeline_id bigint;
  org_name text;
begin
  select name into org_name from public.organizations where id = org_id;

  insert into public.organization_settings (organization_id) values (org_id)
  on conflict (organization_id) do nothing;

  insert into public.configuration (organization_id, config)
  values (org_id, jsonb_build_object('title', org_name))
  on conflict (organization_id) do nothing;

  insert into public.pipelines (organization_id, name, position, is_default)
  values (org_id, 'Основная', 0, true)
  returning id into pipeline_id;

  insert into public.stages (organization_id, pipeline_id, name, position, kind, color)
  values
    (org_id, pipeline_id, 'Новый лид', 0, 'open', '#83A2DB'),
    (org_id, pipeline_id, 'В работе', 1, 'open', '#9DB5E4'),
    (org_id, pipeline_id, 'Записан', 2, 'open', '#FFCE87'),
    (org_id, pipeline_id, 'Пришёл на консультацию', 3, 'open', '#F7B98C'),
    (org_id, pipeline_id, 'План согласован', 4, 'open', '#C9B3D0'),
    (org_id, pipeline_id, 'В лечении', 5, 'open', '#A9C7E8'),
    (org_id, pipeline_id, 'Лечение завершено', 6, 'won', '#8CC9A7'),
    (org_id, pipeline_id, 'Отказ', 7, 'lost', '#FD8E8C');

  insert into public.services (organization_id, name, position)
  values
    (org_id, 'Имплантация', 0),
    (org_id, 'Ортодонтия', 1),
    (org_id, 'Терапия', 2),
    (org_id, 'Гигиена', 3),
    (org_id, 'Протезирование', 4),
    (org_id, 'Хирургия', 5),
    (org_id, 'Детская стоматология', 6),
    (org_id, 'Другое', 7);

  insert into public.lead_sources (organization_id, name, code, is_system, position)
  values
    (org_id, 'WhatsApp', 'whatsapp', true, 0),
    (org_id, 'Instagram', 'instagram', true, 1),
    (org_id, 'Telegram', 'telegram', true, 2),
    (org_id, 'Звонок', 'call', true, 3),
    (org_id, 'Сайт', 'website', true, 4),
    (org_id, '2GIS', '2gis', true, 5),
    (org_id, 'Рекомендация', 'referral', true, 6),
    (org_id, 'Другое', 'other', true, 7);

  insert into public.lost_reasons (organization_id, name, position)
  values
    (org_id, 'Дорого', 0),
    (org_id, 'Выбрал другую клинику', 1),
    (org_id, 'Не дозвонились', 2),
    (org_id, 'Передумал', 3),
    (org_id, 'Далеко или неудобно', 4),
    (org_id, 'Страх лечения', 5),
    (org_id, 'Нет времени', 6),
    (org_id, 'Другое', 7);
end;
$$;

CREATE OR REPLACE FUNCTION "private"."check_pipeline_stages"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  checked_pipeline_id bigint;
  pipeline_ids bigint[];
begin
  if tg_table_name = 'pipelines' then
    pipeline_ids := array[new.id];
  elsif tg_op = 'INSERT' then
    pipeline_ids := array[new.pipeline_id];
  elsif tg_op = 'DELETE' then
    pipeline_ids := array[old.pipeline_id];
  else
    pipeline_ids := array[old.pipeline_id, new.pipeline_id];
  end if;

  for checked_pipeline_id in
    select distinct p from unnest(pipeline_ids) as p
  loop
    if exists (select 1 from public.pipelines where id = checked_pipeline_id)
      and (
        not exists (select 1 from public.stages where pipeline_id = checked_pipeline_id and kind = 'won')
        or not exists (select 1 from public.stages where pipeline_id = checked_pipeline_id and kind = 'lost')
      )
    then
      raise exception 'В воронке должна быть хотя бы одна стадия «Успешно» и одна «Отказ»'
        using errcode = 'check_violation', hint = 'pipeline_needs_won_and_lost';
    end if;
  end loop;
  return null;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."create_pipeline"("pipeline_name" "text") RETURNS bigint
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  new_pipeline_id bigint;
begin
  insert into public.pipelines (name, position)
  values (
    pipeline_name,
    coalesce((select max(position) + 1 from public.pipelines where organization_id = private.current_organization_id()), 0)
  )
  returning id into new_pipeline_id;

  insert into public.stages (pipeline_id, name, position, kind, color)
  values
    (new_pipeline_id, 'Новый лид', 0, 'open', '#83A2DB'),
    (new_pipeline_id, 'Успешно', 1, 'won', '#8CC9A7'),
    (new_pipeline_id, 'Отказ', 2, 'lost', '#FD8E8C');

  return new_pipeline_id;
end;
$$;

CREATE OR REPLACE FUNCTION "private"."manager_deal_visibility"() RETURNS "text"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if private.current_user_role() in ('owner', 'head') then
    return 'all';
  end if;
  return coalesce((
    select s.manager_deal_visibility
    from public.organization_settings s
    where s.organization_id = private.current_organization_id()
  ), 'all');
end;
$$;

CREATE OR REPLACE FUNCTION "public"."handle_deal_before_write"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  new_kind text;
  old_kind text;
  stage_changed boolean;
begin
  if tg_op = 'INSERT' then
    if new.pipeline_id is null then
      select p.id into new.pipeline_id
      from public.pipelines p
      where p.organization_id = new.organization_id
      order by p.is_default desc, p.position, p.id
      limit 1;
    end if;
    if new.stage_id is null then
      select s.id into new.stage_id
      from public.stages s
      where s.pipeline_id = new.pipeline_id
      order by s.position, s.id
      limit 1;
    end if;
    new.paid_amount := 0;
    new.stage_changed_at := now();
  else
    new.created_at := old.created_at;
    -- paid_amount is the total of the payments, only their trigger writes it
    if current_setting('crm.sync_paid_amount', true) is distinct from 'on' then
      new.paid_amount := old.paid_amount;
    end if;
    if (to_jsonb(new) - 'index' - 'updated_at') is distinct from (to_jsonb(old) - 'index' - 'updated_at') then
      new.updated_at := now();
    end if;
  end if;

  select s.kind into new_kind from public.stages s where s.id = new.stage_id;
  stage_changed := tg_op = 'INSERT'
    or new.stage_id is distinct from old.stage_id
    or new.pipeline_id is distinct from old.pipeline_id;

  if tg_op = 'UPDATE' and stage_changed then
    select s.kind into old_kind from public.stages s where s.id = old.stage_id;
    if old_kind = 'lost' then
      raise exception 'Сделка в отказе не возвращается в работу. Для повторного обращения создайте новую сделку.'
        using errcode = 'check_violation', hint = 'deal_lost_locked';
    end if;
  end if;

  if new_kind = 'lost' and new.lost_reason_id is null then
    raise exception 'Укажите причину отказа'
      using errcode = 'check_violation', hint = 'lost_reason_required';
  end if;

  if stage_changed then
    new.stage_changed_at := now();
    new.closed_at := case when new_kind in ('won', 'lost') then now() else null end;
  end if;

  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."handle_deal_after_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  tracked text[] := array[
    'name', 'patient_id', 'pipeline_id', 'sales_id', 'source_id', 'service_id',
    'plan_amount', 'paid_amount', 'lost_reason_id', 'lost_comment',
    'appointment_at', 'visit_at', 'tags', 'archived_at'
  ];
  field text;
  old_json jsonb;
  new_json jsonb;
  changes jsonb := '{}'::jsonb;
begin
  if tg_op = 'INSERT' then
    insert into public.deal_events (organization_id, deal_id, type, to_stage_id, sales_id)
    values (new.organization_id, new.id, 'created', new.stage_id, private.current_sales_id());

    if new.source_id is not null then
      update public.patients
      set source_id = new.source_id
      where organization_id = new.organization_id
        and id = new.patient_id
        and source_id is null;
    end if;
    return null;
  end if;

  old_json := to_jsonb(old);
  new_json := to_jsonb(new);
  foreach field in array tracked loop
    if old_json -> field is distinct from new_json -> field then
      changes := changes || jsonb_build_object(field, jsonb_build_array(old_json -> field, new_json -> field));
    end if;
  end loop;

  if new.stage_id is distinct from old.stage_id then
    insert into public.deal_events (organization_id, deal_id, type, from_stage_id, to_stage_id, changes, sales_id)
    values (new.organization_id, new.id, 'stage_changed', old.stage_id, new.stage_id, changes, private.current_sales_id());
  elsif changes <> '{}'::jsonb then
    insert into public.deal_events (organization_id, deal_id, type, changes, sales_id)
    values (new.organization_id, new.id, 'updated', changes, private.current_sales_id());
  end if;
  return null;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."handle_deal_payment_changed"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  perform set_config('crm.sync_paid_amount', 'on', true);
  update public.deals d
  set paid_amount = coalesce((
    select sum(p.amount)
    from public.deal_payments p
    where p.organization_id = d.organization_id and p.deal_id = d.id
  ), 0)
  where d.organization_id = coalesce(new.organization_id, old.organization_id)
    and d.id in (new.deal_id, old.deal_id);
  perform set_config('crm.sync_paid_amount', 'off', true);
  return null;
end;
$$;

-- >>> from supabase/schemas/03_views.sql
create or replace view public.activity_log with (security_invoker = on) as
select
    ('patient.' || p.id || '.created') as id,
    'patient.created' as type,
    p.first_seen as date,
    p.id as patient_id,
    p.sales_id,
    to_json(p.*) as patient,
    null::json as deal,
    null::json as patient_note,
    null::json as deal_note
from public.patients p
union all
select
    ('patientNote.' || n.id || '.created') as id,
    'patientNote.created' as type,
    n.date,
    n.patient_id,
    n.sales_id,
    null::json as patient,
    null::json as deal,
    to_json(n.*) as patient_note,
    null::json as deal_note
from public.patient_notes n
union all
select
    ('deal.' || d.id || '.created') as id,
    'deal.created' as type,
    d.created_at as date,
    d.patient_id,
    d.sales_id,
    null::json as patient,
    to_json(d.*) as deal,
    null::json as patient_note,
    null::json as deal_note
from public.deals d
union all
select
    ('dealNote.' || n.id || '.created') as id,
    'dealNote.created' as type,
    n.date,
    d.patient_id,
    n.sales_id,
    null::json as patient,
    null::json as deal,
    null::json as patient_note,
    to_json(n.*) as deal_note
from public.deal_notes n
    join public.deals d on d.organization_id = n.organization_id and d.id = n.deal_id;

create or replace view public.patients_summary with (security_invoker = on) as
select
    p.id,
    p.organization_id,
    p.first_name,
    p.last_name,
    p.middle_name,
    p.phone_jsonb,
    p.phones,
    p.birth_date,
    p.city,
    p.whatsapp,
    p.instagram,
    p.telegram,
    p.source_id,
    p.tags,
    p.sales_id,
    p.gender,
    p.avatar,
    p.background,
    p.status,
    p.first_seen,
    p.last_seen,
    array_to_string(p.phones, ' ') as phone_fts,
    (
        select count(*)
        from public.deals d
        where d.organization_id = p.organization_id and d.patient_id = p.id
    ) as nb_deals,
    (
        select count(*)
        from public.deals d
            join public.stages s on s.id = d.stage_id
        where d.organization_id = p.organization_id and d.patient_id = p.id and s.kind = 'open'
    ) as nb_open_deals,
    (
        select count(*)
        from public.tasks t
            join public.deals d on d.organization_id = t.organization_id and d.id = t.deal_id
        where d.organization_id = p.organization_id and d.patient_id = p.id and t.done_date is null
    ) as nb_tasks
from public.patients p;

create or replace view public.deals_summary with (security_invoker = on) as
select
    d.id,
    d.organization_id,
    d.patient_id,
    d.pipeline_id,
    d.stage_id,
    d.name,
    d.source_id,
    d.service_id,
    d.plan_amount,
    d.paid_amount,
    d.sales_id,
    d.lost_reason_id,
    d.lost_comment,
    d.appointment_at,
    d.visit_at,
    d.tags,
    d.description,
    d.index,
    d.created_at,
    d.updated_at,
    d.stage_changed_at,
    d.closed_at,
    d.first_response_at,
    d.archived_at,
    s.kind as stage_kind,
    p.first_name as patient_first_name,
    p.last_name as patient_last_name,
    p.phones[1] as patient_phone,
    lower(concat_ws(' ', d.name, p.last_name, p.first_name, p.middle_name, array_to_string(p.phones, ' '))) as search_text,
    (
        select count(*)
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
    ) as nb_open_tasks,
    (
        select min(t.due_date)
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
    ) as next_task_due_at
from public.deals d
    join public.stages s on s.id = d.stage_id
    join public.patients p on p.organization_id = d.organization_id and p.id = d.patient_id;

-- >>> from supabase/schemas/04_triggers.sql
create or replace trigger set_patient_sales_id_trigger
    before insert on public.patients
    for each row execute function public.set_sales_id_default();

create or replace trigger set_patient_notes_sales_id_trigger
    before insert on public.patient_notes
    for each row execute function public.set_sales_id_default();

create or replace trigger set_deal_sales_id_trigger
    before insert on public.deals
    for each row execute function public.set_sales_id_default();

create or replace trigger set_deal_notes_sales_id_trigger
    before insert on public.deal_notes
    for each row execute function public.set_sales_id_default();

create or replace trigger set_deal_payments_sales_id_trigger
    before insert on public.deal_payments
    for each row execute function public.set_sales_id_default();

create or replace trigger set_task_sales_id_trigger
    before insert on public.tasks
    for each row execute function public.set_sales_id_default();

create or replace trigger set_call_sales_id_trigger
    before insert on public.calls
    for each row execute function public.set_sales_id_default();

create or replace trigger patient_saved
    before insert or update on public.patients
    for each row execute function public.handle_patient_saved();

create or replace trigger on_patient_notes_created
    after insert on public.patient_notes
    for each row execute function public.handle_patient_note_created();

create constraint trigger check_pipeline_stages_on_stages
    after insert or update or delete on public.stages
    deferrable initially deferred
    for each row execute function private.check_pipeline_stages();

create constraint trigger check_pipeline_stages_on_pipelines
    after insert on public.pipelines
    deferrable initially deferred
    for each row execute function private.check_pipeline_stages();

create or replace trigger deal_before_write
    before insert or update on public.deals
    for each row execute function public.handle_deal_before_write();

create or replace trigger deal_after_write
    after insert or update on public.deals
    for each row execute function public.handle_deal_after_write();

create or replace trigger deal_payment_changed
    after insert or update or delete on public.deal_payments
    for each row execute function public.handle_deal_payment_changed();

create or replace trigger on_patient_notes_attachments_updated_delete_note_attachments
    after update on public.patient_notes
    for each row
    when (old.attachments is distinct from new.attachments)
    execute function public.cleanup_note_attachments();

create or replace trigger on_patient_notes_deleted_delete_note_attachments
    after delete on public.patient_notes
    for each row execute function public.cleanup_note_attachments();

create or replace trigger on_deal_notes_attachments_updated_delete_note_attachments
    after update on public.deal_notes
    for each row
    when (old.attachments is distinct from new.attachments)
    execute function public.cleanup_note_attachments();

create or replace trigger on_deal_notes_deleted_delete_note_attachments
    after delete on public.deal_notes
    for each row execute function public.cleanup_note_attachments();

create or replace trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user();

create or replace trigger on_auth_user_updated
    after update on auth.users
    for each row execute function public.handle_update_user();

-- >>> from supabase/schemas/05_policies.sql
alter table public.organizations enable row level security;

alter table public.organization_settings enable row level security;

alter table public.sales enable row level security;

alter table public.configuration enable row level security;

alter table public.pipelines enable row level security;

alter table public.stages enable row level security;

alter table public.services enable row level security;

alter table public.lead_sources enable row level security;

alter table public.lost_reasons enable row level security;

alter table public.tags enable row level security;

alter table public.patients enable row level security;

alter table public.patient_notes enable row level security;

alter table public.deals enable row level security;

alter table public.deal_notes enable row level security;

alter table public.deal_payments enable row level security;

alter table public.deal_events enable row level security;

alter table public.tasks enable row level security;

alter table public.calls enable row level security;

create policy "Organization members can read" on public.organization_settings for select to authenticated
    using (organization_id = (select private.current_organization_id()));

create policy "Owner and head can update" on public.organization_settings for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));

create policy "Organization members can read" on public.pipelines for select to authenticated
    using (organization_id = (select private.current_organization_id()));

create policy "Owner and head can insert" on public.pipelines for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

create policy "Owner and head can update" on public.pipelines for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));

create policy "Owner and head can delete" on public.pipelines for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

create policy "Organization members can read" on public.stages for select to authenticated
    using (organization_id = (select private.current_organization_id()));

create policy "Owner and head can insert" on public.stages for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

create policy "Owner and head can update" on public.stages for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));

create policy "Owner and head can delete" on public.stages for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

create policy "Organization members can read" on public.services for select to authenticated
    using (organization_id = (select private.current_organization_id()));

create policy "Owner and head can insert" on public.services for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

create policy "Owner and head can update" on public.services for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));

create policy "Owner and head can delete" on public.services for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

create policy "Organization members can read" on public.lead_sources for select to authenticated
    using (organization_id = (select private.current_organization_id()));

create policy "Owner and head can insert" on public.lead_sources for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head') and not is_system and code is null);

create policy "Owner and head can update" on public.lead_sources for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));

create policy "Owner and head can delete" on public.lead_sources for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head') and not is_system);

create policy "Organization members can read" on public.lost_reasons for select to authenticated
    using (organization_id = (select private.current_organization_id()));

create policy "Owner and head can insert" on public.lost_reasons for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

create policy "Owner and head can update" on public.lost_reasons for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));

create policy "Owner and head can delete" on public.lost_reasons for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

create policy "Organization members can read" on public.patients for select to authenticated
    using (organization_id = (select private.current_organization_id()));

create policy "Organization members can insert" on public.patients for insert to authenticated
    with check (organization_id = (select private.current_organization_id()));

create policy "Organization members can update" on public.patients for update to authenticated
    using (organization_id = (select private.current_organization_id()))
    with check (organization_id = (select private.current_organization_id()));

create policy "Organization members can delete" on public.patients for delete to authenticated
    using (organization_id = (select private.current_organization_id()));

create policy "Organization members can read" on public.patient_notes for select to authenticated
    using (organization_id = (select private.current_organization_id()));

create policy "Organization members can insert" on public.patient_notes for insert to authenticated
    with check (organization_id = (select private.current_organization_id()));

create policy "Organization members can update" on public.patient_notes for update to authenticated
    using (organization_id = (select private.current_organization_id()))
    with check (organization_id = (select private.current_organization_id()));

create policy "Organization members can delete" on public.patient_notes for delete to authenticated
    using (organization_id = (select private.current_organization_id()));

create policy "Visible deals can be read" on public.deals for select to authenticated
    using (
        organization_id = (select private.current_organization_id())
        and (
            (select private.manager_deal_visibility()) = 'all'
            or sales_id = (select private.current_sales_id())
            or ((select private.manager_deal_visibility()) = 'own_and_unassigned' and sales_id is null)
        )
    );

create policy "Organization members can insert" on public.deals for insert to authenticated
    with check (organization_id = (select private.current_organization_id()));

create policy "Visible deals can be updated" on public.deals for update to authenticated
    using (
        organization_id = (select private.current_organization_id())
        and (
            (select private.manager_deal_visibility()) = 'all'
            or sales_id = (select private.current_sales_id())
            or ((select private.manager_deal_visibility()) = 'own_and_unassigned' and sales_id is null)
        )
    )
    with check (organization_id = (select private.current_organization_id()));

create policy "Owner and head can delete" on public.deals for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));

create policy "Rows of visible deals can be read" on public.deal_notes for select to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = deal_notes.organization_id and d.id = deal_notes.deal_id));

create policy "Rows of visible deals can be inserted" on public.deal_notes for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = deal_notes.organization_id and d.id = deal_notes.deal_id));

create policy "Rows of visible deals can be updated" on public.deal_notes for update to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = deal_notes.organization_id and d.id = deal_notes.deal_id))
    with check (organization_id = (select private.current_organization_id()));

create policy "Rows of visible deals can be deleted" on public.deal_notes for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = deal_notes.organization_id and d.id = deal_notes.deal_id));

create policy "Rows of visible deals can be read" on public.deal_payments for select to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = deal_payments.organization_id and d.id = deal_payments.deal_id));

create policy "Rows of visible deals can be inserted" on public.deal_payments for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = deal_payments.organization_id and d.id = deal_payments.deal_id));

create policy "Rows of visible deals can be updated" on public.deal_payments for update to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = deal_payments.organization_id and d.id = deal_payments.deal_id))
    with check (organization_id = (select private.current_organization_id()));

create policy "Rows of visible deals can be deleted" on public.deal_payments for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = deal_payments.organization_id and d.id = deal_payments.deal_id));

create policy "Rows of visible deals can be read" on public.deal_events for select to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = deal_events.organization_id and d.id = deal_events.deal_id));

create policy "Rows of visible deals can be read" on public.tasks for select to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = tasks.organization_id and d.id = tasks.deal_id));

create policy "Rows of visible deals can be inserted" on public.tasks for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = tasks.organization_id and d.id = tasks.deal_id));

create policy "Rows of visible deals can be updated" on public.tasks for update to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = tasks.organization_id and d.id = tasks.deal_id))
    with check (organization_id = (select private.current_organization_id()));

create policy "Rows of visible deals can be deleted" on public.tasks for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = tasks.organization_id and d.id = tasks.deal_id));

create policy "Organization members can read" on public.calls for select to authenticated
    using (organization_id = (select private.current_organization_id()));

create policy "Organization members can insert" on public.calls for insert to authenticated
    with check (organization_id = (select private.current_organization_id()));

create policy "Organization members can update" on public.calls for update to authenticated
    using (organization_id = (select private.current_organization_id()))
    with check (organization_id = (select private.current_organization_id()));

create policy "Organization members can delete" on public.calls for delete to authenticated
    using (organization_id = (select private.current_organization_id()));

-- >>> from supabase/schemas/06_grants.sql
grant usage on schema public to postgres;

grant usage on schema public to anon;

grant usage on schema public to authenticated;

grant usage on schema public to service_role;

grant usage on schema private to anon;

grant usage on schema private to authenticated;

grant usage on schema private to service_role;

revoke all on function private.current_organization_id() from public;

grant execute on function private.current_organization_id() to anon;

grant execute on function private.current_organization_id() to authenticated;

grant execute on function private.current_organization_id() to service_role;

revoke all on function private.current_user_role() from public;

grant execute on function private.current_user_role() to anon;

grant execute on function private.current_user_role() to authenticated;

grant execute on function private.current_user_role() to service_role;

revoke all on function private.current_sales_id() from public;

grant execute on function private.current_sales_id() to anon;

grant execute on function private.current_sales_id() to authenticated;

grant execute on function private.current_sales_id() to service_role;

revoke all on function private.manager_deal_visibility() from public;

grant execute on function private.manager_deal_visibility() to anon;

grant execute on function private.manager_deal_visibility() to authenticated;

grant execute on function private.manager_deal_visibility() to service_role;

revoke all on function private.normalize_phone(text) from public;

grant execute on function private.normalize_phone(text) to anon;

grant execute on function private.normalize_phone(text) to authenticated;

grant execute on function private.normalize_phone(text) to service_role;

revoke all on function private.seed_organization(bigint) from public;

grant execute on function private.seed_organization(bigint) to service_role;

revoke all on function private.check_pipeline_stages() from public;

grant execute on function private.check_pipeline_stages() to service_role;

grant all on function public.cleanup_note_attachments() to anon;

grant all on function public.cleanup_note_attachments() to authenticated;

grant all on function public.cleanup_note_attachments() to service_role;

grant all on function public.get_note_attachments_function_url() to anon;

grant all on function public.get_note_attachments_function_url() to authenticated;

grant all on function public.get_note_attachments_function_url() to service_role;

grant all on function public.handle_new_user() to anon;

grant all on function public.handle_new_user() to authenticated;

grant all on function public.handle_new_user() to service_role;

grant all on function public.handle_update_user() to anon;

grant all on function public.handle_update_user() to authenticated;

grant all on function public.handle_update_user() to service_role;

grant all on function public.is_admin() to anon;

grant all on function public.is_admin() to authenticated;

grant all on function public.is_admin() to service_role;

grant all on function public.set_sales_id_default() to anon;

grant all on function public.set_sales_id_default() to authenticated;

grant all on function public.set_sales_id_default() to service_role;

grant all on function public.handle_patient_saved() to anon;

grant all on function public.handle_patient_saved() to authenticated;

grant all on function public.handle_patient_saved() to service_role;

grant all on function public.find_patients_by_phone(text) to anon;

grant all on function public.find_patients_by_phone(text) to authenticated;

grant all on function public.find_patients_by_phone(text) to service_role;

grant all on function public.handle_patient_note_created() to anon;

grant all on function public.handle_patient_note_created() to authenticated;

grant all on function public.handle_patient_note_created() to service_role;

grant all on function public.create_pipeline(text) to anon;

grant all on function public.create_pipeline(text) to authenticated;

grant all on function public.create_pipeline(text) to service_role;

grant all on function public.handle_deal_before_write() to anon;

grant all on function public.handle_deal_before_write() to authenticated;

grant all on function public.handle_deal_before_write() to service_role;

grant all on function public.handle_deal_after_write() to anon;

grant all on function public.handle_deal_after_write() to authenticated;

grant all on function public.handle_deal_after_write() to service_role;

grant all on function public.handle_deal_payment_changed() to anon;

grant all on function public.handle_deal_payment_changed() to authenticated;

grant all on function public.handle_deal_payment_changed() to service_role;

revoke all on function public.get_user_id_by_email(text) from public;

grant all on function public.get_user_id_by_email(text) to service_role;

revoke all on table public.organizations from anon, authenticated;

grant select on table public.organizations to anon;

grant select on table public.organizations to authenticated;

grant update (name, timezone) on table public.organizations to authenticated;

grant all on table public.organizations to service_role;

grant all on table public.organization_settings to anon;

grant all on table public.organization_settings to authenticated;

grant all on table public.organization_settings to service_role;

grant all on table public.sales to anon;

grant all on table public.sales to authenticated;

grant all on table public.sales to service_role;

grant all on table public.configuration to anon;

grant all on table public.configuration to authenticated;

grant all on table public.configuration to service_role;

grant all on table public.pipelines to anon;

grant all on table public.pipelines to authenticated;

grant all on table public.pipelines to service_role;

grant all on table public.stages to anon;

grant all on table public.stages to authenticated;

grant all on table public.stages to service_role;

grant all on table public.services to anon;

grant all on table public.services to authenticated;

grant all on table public.services to service_role;

grant all on table public.lead_sources to anon;

grant all on table public.lead_sources to authenticated;

grant all on table public.lead_sources to service_role;

grant all on table public.lost_reasons to anon;

grant all on table public.lost_reasons to authenticated;

grant all on table public.lost_reasons to service_role;

grant all on table public.tags to anon;

grant all on table public.tags to authenticated;

grant all on table public.tags to service_role;

grant all on table public.patients to anon;

grant all on table public.patients to authenticated;

grant all on table public.patients to service_role;

grant all on table public.patient_notes to anon;

grant all on table public.patient_notes to authenticated;

grant all on table public.patient_notes to service_role;

grant all on table public.deals to anon;

grant all on table public.deals to authenticated;

grant all on table public.deals to service_role;

grant all on table public.deal_notes to anon;

grant all on table public.deal_notes to authenticated;

grant all on table public.deal_notes to service_role;

grant all on table public.deal_payments to anon;

grant all on table public.deal_payments to authenticated;

grant all on table public.deal_payments to service_role;

grant all on table public.deal_events to anon;

grant all on table public.deal_events to authenticated;

grant all on table public.deal_events to service_role;

grant all on table public.tasks to anon;

grant all on table public.tasks to authenticated;

grant all on table public.tasks to service_role;

grant all on table public.calls to anon;

grant all on table public.calls to authenticated;

grant all on table public.calls to service_role;

revoke update on table public.lead_sources from anon, authenticated;

grant update (name, position, is_archived) on table public.lead_sources to authenticated;

revoke insert, update, delete on table public.deal_events from anon, authenticated;

grant all on table public.activity_log to anon;

grant all on table public.activity_log to authenticated;

grant all on table public.activity_log to service_role;

grant all on table public.patients_summary to anon;

grant all on table public.patients_summary to authenticated;

grant all on table public.patients_summary to service_role;

grant all on table public.deals_summary to anon;

grant all on table public.deals_summary to authenticated;

grant all on table public.deals_summary to service_role;

grant all on sequence public.organizations_id_seq to service_role;

grant all on sequence public.configuration_id_seq to anon;

grant all on sequence public.configuration_id_seq to authenticated;

grant all on sequence public.configuration_id_seq to service_role;

grant all on sequence public.sales_id_seq to anon;

grant all on sequence public.sales_id_seq to authenticated;

grant all on sequence public.sales_id_seq to service_role;

grant all on sequence public.pipelines_id_seq to anon;

grant all on sequence public.pipelines_id_seq to authenticated;

grant all on sequence public.pipelines_id_seq to service_role;

grant all on sequence public.stages_id_seq to anon;

grant all on sequence public.stages_id_seq to authenticated;

grant all on sequence public.stages_id_seq to service_role;

grant all on sequence public.services_id_seq to anon;

grant all on sequence public.services_id_seq to authenticated;

grant all on sequence public.services_id_seq to service_role;

grant all on sequence public.lead_sources_id_seq to anon;

grant all on sequence public.lead_sources_id_seq to authenticated;

grant all on sequence public.lead_sources_id_seq to service_role;

grant all on sequence public.lost_reasons_id_seq to anon;

grant all on sequence public.lost_reasons_id_seq to authenticated;

grant all on sequence public.lost_reasons_id_seq to service_role;

grant all on sequence public.tags_id_seq to anon;

grant all on sequence public.tags_id_seq to authenticated;

grant all on sequence public.tags_id_seq to service_role;

grant all on sequence public.patients_id_seq to anon;

grant all on sequence public.patients_id_seq to authenticated;

grant all on sequence public.patients_id_seq to service_role;

grant all on sequence public.patient_notes_id_seq to anon;

grant all on sequence public.patient_notes_id_seq to authenticated;

grant all on sequence public.patient_notes_id_seq to service_role;

grant all on sequence public.deals_id_seq to anon;

grant all on sequence public.deals_id_seq to authenticated;

grant all on sequence public.deals_id_seq to service_role;

grant all on sequence public.deal_notes_id_seq to anon;

grant all on sequence public.deal_notes_id_seq to authenticated;

grant all on sequence public.deal_notes_id_seq to service_role;

grant all on sequence public.deal_payments_id_seq to anon;

grant all on sequence public.deal_payments_id_seq to authenticated;

grant all on sequence public.deal_payments_id_seq to service_role;

grant all on sequence public.deal_events_id_seq to anon;

grant all on sequence public.deal_events_id_seq to authenticated;

grant all on sequence public.deal_events_id_seq to service_role;

grant all on sequence public.tasks_id_seq to anon;

grant all on sequence public.tasks_id_seq to authenticated;

grant all on sequence public.tasks_id_seq to service_role;

grant all on sequence public.calls_id_seq to anon;

grant all on sequence public.calls_id_seq to authenticated;

grant all on sequence public.calls_id_seq to service_role;

alter default privileges for role postgres in schema public grant all on sequences to postgres;

alter default privileges for role postgres in schema public grant all on sequences to anon;

alter default privileges for role postgres in schema public grant all on sequences to authenticated;

alter default privileges for role postgres in schema public grant all on sequences to service_role;

alter default privileges for role postgres in schema public grant all on functions to postgres;

alter default privileges for role postgres in schema public grant all on functions to anon;

alter default privileges for role postgres in schema public grant all on functions to authenticated;

alter default privileges for role postgres in schema public grant all on functions to service_role;

alter default privileges for role postgres in schema public grant all on tables to postgres;

alter default privileges for role postgres in schema public grant all on tables to anon;

alter default privileges for role postgres in schema public grant all on tables to authenticated;

alter default privileges for role postgres in schema public grant all on tables to service_role;

-- >>> default pipeline and dictionaries for existing organizations
select private.seed_organization(id) from public.organizations;
