-- Stage 5: lead distribution, tasks created by rules, stage checklists.

alter table public.organization_settings
    add column lead_distribution text not null default 'off',
    add column lead_distribution_sales_ids bigint[] not null default '{}'::bigint[],
    add column last_distributed_sales_id bigint;
alter table public.organization_settings
    add constraint organization_settings_lead_distribution_check
        check (lead_distribution in ('off', 'round_robin', 'first_response'));

--
-- Automations: tasks created by rules, stage checklists
--

-- A task created on its own: when a deal is created, or enters a stage
create table public.task_rules (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    event text not null,
    stage_id bigint,
    type text not null default 'call',
    text text not null,
    due_in_minutes integer not null default 60,
    is_active boolean not null default true,
    position integer not null default 0,
    created_at timestamp with time zone not null default now(),
    constraint task_rules_event_check check (event in ('deal_created', 'stage_entered')),
    constraint task_rules_stage_check check ((event = 'stage_entered') = (stage_id is not null)),
    constraint task_rules_type_check check (type in ('call', 'message', 'reminder', 'other')),
    constraint task_rules_text_not_blank check (btrim(text) <> ''),
    constraint task_rules_due_positive check (due_in_minutes >= 0)
);

-- What must be done at a stage before the deal moves further
create table public.stage_checklist_items (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    stage_id bigint not null,
    text text not null,
    position integer not null default 0,
    constraint stage_checklist_items_text_not_blank check (btrim(text) <> '')
);

create table public.deal_checklist_checks (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    deal_id bigint not null,
    item_id bigint not null,
    sales_id bigint default private.current_sales_id(),
    checked_at timestamp with time zone not null default now()
);

alter table public.task_rules add constraint task_rules_organization_id_id_key unique (organization_id, id);
alter table public.stage_checklist_items add constraint stage_checklist_items_organization_id_id_key unique (organization_id, id);
alter table public.deal_checklist_checks add constraint deal_checklist_checks_organization_id_id_key unique (organization_id, id);

alter table public.task_rules
    add constraint task_rules_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.task_rules
    add constraint task_rules_stage_id_fkey foreign key (organization_id, stage_id) references public.stages(organization_id, id) on delete cascade;
alter table public.stage_checklist_items
    add constraint stage_checklist_items_stage_id_fkey foreign key (organization_id, stage_id) references public.stages(organization_id, id) on delete cascade;
alter table public.deal_checklist_checks
    add constraint deal_checklist_checks_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.deal_checklist_checks
    add constraint deal_checklist_checks_item_id_fkey foreign key (organization_id, item_id) references public.stage_checklist_items(organization_id, id) on delete cascade;
alter table public.deal_checklist_checks
    add constraint deal_checklist_checks_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

create index task_rules_event_idx on public.task_rules using btree (organization_id, event, stage_id);
create index stage_checklist_items_stage_id_idx on public.stage_checklist_items using btree (stage_id, position);
create unique index deal_checklist_checks_item_idx on public.deal_checklist_checks using btree (deal_id, item_id);

--
-- Automations
--

-- Round robin among the chosen active employees (organization_settings);
-- null when the clinic does not distribute this way
CREATE OR REPLACE FUNCTION "private"."next_responsible"("org_id" bigint) RETURNS bigint
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  settings public.organization_settings;
  last_position bigint;
  chosen bigint;
begin
  select * into settings from public.organization_settings s
  where s.organization_id = org_id
  for update;
  if not found or settings.lead_distribution <> 'round_robin' then
    return null;
  end if;
  select c.position into last_position
  from unnest(settings.lead_distribution_sales_ids) with ordinality as c(sales_id, position)
  where c.sales_id = settings.last_distributed_sales_id;
  select s.id into chosen
  from unnest(settings.lead_distribution_sales_ids) with ordinality as c(sales_id, position)
    join public.sales s on s.id = c.sales_id and s.organization_id = org_id and not s.disabled
  order by c.position <= coalesce(last_position, 0), c.position
  limit 1;
  if chosen is not null then
    update public.organization_settings
    set last_distributed_sales_id = chosen
    where organization_id = org_id;
  end if;
  return chosen;
end;
$$;

-- Tasks of the rules matching an event of a deal
CREATE OR REPLACE FUNCTION "private"."create_rule_tasks"("deal" "public"."deals", "rule_event" "text", "rule_stage_id" bigint) RETURNS integer
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  created integer;
begin
  insert into public.tasks (organization_id, deal_id, type, text, due_date, sales_id)
  select deal.organization_id, deal.id, r.type, r.text,
    now() + make_interval(mins => r.due_in_minutes), deal.sales_id
  from public.task_rules r
  where r.organization_id = deal.organization_id
    and r.is_active
    and r.event = rule_event
    and r.stage_id is not distinct from rule_stage_id
  order by r.position, r.id;
  get diagnostics created = row_count;
  return created;
end;
$$;

CREATE OR REPLACE FUNCTION "private"."seed_organization"("org_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  pipeline_id bigint;
  org_name text;
begin
  select name into org_name from public.organizations where id = org_id;

  insert into public.organization_settings (organization_id) values (org_id)
  on conflict (organization_id) do nothing;

  insert into public.configuration (organization_id, config)
  values (org_id, jsonb_build_object('title', org_name))
  on conflict (organization_id) do nothing;

  insert into public.pipelines (organization_id, name, position, is_default)
  values (org_id, 'Основная', 0, true)
  returning id into pipeline_id;

  insert into public.stages (organization_id, pipeline_id, name, position, kind, color)
  values
    (org_id, pipeline_id, 'Новый лид', 0, 'open', '#83A2DB'),
    (org_id, pipeline_id, 'В работе', 1, 'open', '#9DB5E4'),
    (org_id, pipeline_id, 'Записан', 2, 'open', '#FFCE87'),
    (org_id, pipeline_id, 'Пришёл на консультацию', 3, 'open', '#F7B98C'),
    (org_id, pipeline_id, 'План согласован', 4, 'open', '#C9B3D0'),
    (org_id, pipeline_id, 'В лечении', 5, 'open', '#A9C7E8'),
    (org_id, pipeline_id, 'Лечение завершено', 6, 'won', '#8CC9A7'),
    (org_id, pipeline_id, 'Отказ', 7, 'lost', '#FD8E8C');

  insert into public.services (organization_id, name, position)
  values
    (org_id, 'Имплантация', 0),
    (org_id, 'Ортодонтия', 1),
    (org_id, 'Терапия', 2),
    (org_id, 'Гигиена', 3),
    (org_id, 'Протезирование', 4),
    (org_id, 'Хирургия', 5),
    (org_id, 'Детская стоматология', 6),
    (org_id, 'Другое', 7);

  insert into public.lead_sources (organization_id, name, code, is_system, position)
  values
    (org_id, 'WhatsApp', 'whatsapp', true, 0),
    (org_id, 'Instagram', 'instagram', true, 1),
    (org_id, 'Telegram', 'telegram', true, 2),
    (org_id, 'Звонок', 'call', true, 3),
    (org_id, 'Сайт', 'website', true, 4),
    (org_id, '2GIS', '2gis', true, 5),
    (org_id, 'Рекомендация', 'referral', true, 6),
    (org_id, 'Другое', 'other', true, 7);

  insert into public.lost_reasons (organization_id, name, position)
  values
    (org_id, 'Дорого', 0),
    (org_id, 'Выбрал другую клинику', 1),
    (org_id, 'Не дозвонились', 2),
    (org_id, 'Передумал', 3),
    (org_id, 'Далеко или неудобно', 4),
    (org_id, 'Страх лечения', 5),
    (org_id, 'Нет времени', 6),
    (org_id, 'Другое', 7);

  -- Default automations: contact every new request, send the plan after the
  -- consultation (the clinic edits them in Settings → Automations)
  insert into public.task_rules (organization_id, event, stage_id, type, text, due_in_minutes, position)
  values (org_id, 'deal_created', null, 'call', 'Связаться с пациентом по новому обращению', 15, 0);
  insert into public.task_rules (organization_id, event, stage_id, type, text, due_in_minutes, position)
  select org_id, 'stage_entered', s.id, 'message', 'Отправить план лечения и стоимость', 24 * 60, 1
  from public.stages s
    join public.pipelines p on p.id = s.pipeline_id
  where p.organization_id = org_id and p.is_default and s.name = 'Пришёл на консультацию';
end;
$$;

CREATE OR REPLACE FUNCTION "public"."handle_deal_before_write"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  new_kind text;
  old_kind text;
  stage_changed boolean;
begin
  if tg_op = 'INSERT' then
    if new.pipeline_id is null then
      select p.id into new.pipeline_id
      from public.pipelines p
      where p.organization_id = new.organization_id
      order by p.is_default desc, p.position, p.id
      limit 1;
    end if;
    if new.stage_id is null then
      select s.id into new.stage_id
      from public.stages s
      where s.pipeline_id = new.pipeline_id
      order by s.position, s.id
      limit 1;
    end if;
    new.paid_amount := 0;
    new.stage_changed_at := now();
    -- A lead coming from outside (no user) is distributed by the clinic rules
    if new.sales_id is null and auth.uid() is null then
      new.sales_id := private.next_responsible(new.organization_id);
    end if;
  else
    new.created_at := old.created_at;
    -- paid_amount is the total of the payments, only their trigger writes it
    if current_setting('crm.sync_paid_amount', true) is distinct from 'on' then
      new.paid_amount := old.paid_amount;
    end if;
    if (to_jsonb(new) - 'index' - 'updated_at') is distinct from (to_jsonb(old) - 'index' - 'updated_at') then
      new.updated_at := now();
    end if;
    -- Moved to another pipeline: to its first stage, unless the clinic lets
    -- employees choose the stage (organization_settings.pipeline_move_mode)
    if new.pipeline_id is distinct from old.pipeline_id and coalesce((
      select os.pipeline_move_mode from public.organization_settings os
      where os.organization_id = new.organization_id
    ), 'first_stage') = 'first_stage' then
      select s.id into new.stage_id
      from public.stages s
      where s.pipeline_id = new.pipeline_id
      order by s.position, s.id
      limit 1;
    end if;
  end if;

  select s.kind into new_kind from public.stages s where s.id = new.stage_id;
  stage_changed := tg_op = 'INSERT'
    or new.stage_id is distinct from old.stage_id
    or new.pipeline_id is distinct from old.pipeline_id;

  if tg_op = 'UPDATE' and stage_changed then
    select s.kind into old_kind from public.stages s where s.id = old.stage_id;
    if old_kind = 'lost' then
      raise exception 'Сделка в отказе не возвращается в работу. Для повторного обращения создайте новую сделку.'
        using errcode = 'check_violation', hint = 'deal_lost_locked';
    end if;
    -- The checklist of the stage blocks moving forward (refusing is always possible)
    if new.pipeline_id = old.pipeline_id and new_kind is distinct from 'lost'
      and (select s.position from public.stages s where s.id = new.stage_id)
        > (select s.position from public.stages s where s.id = old.stage_id)
      and exists (
        select 1 from public.stage_checklist_items i
        where i.stage_id = old.stage_id
          and not exists (
            select 1 from public.deal_checklist_checks c
            where c.deal_id = old.id and c.item_id = i.id
          )
      )
    then
      raise exception 'Выполните чек-лист этапа «%»', (select s.name from public.stages s where s.id = old.stage_id)
        using errcode = 'check_violation', hint = 'stage_checklist_incomplete';
    end if;
  end if;

  if new_kind = 'lost' and new.lost_reason_id is null then
    raise exception 'Укажите причину отказа'
      using errcode = 'check_violation', hint = 'lost_reason_required';
  end if;

  if stage_changed then
    new.stage_changed_at := now();
    new.closed_at := case when new_kind in ('won', 'lost') then now() else null end;
  end if;

  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."handle_deal_after_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  tracked text[] := array[
    'name', 'patient_id', 'pipeline_id', 'sales_id', 'source_id', 'service_id',
    'plan_amount', 'paid_amount', 'lost_reason_id', 'lost_comment',
    'appointment_at', 'visit_at', 'tags', 'archived_at'
  ];
  field text;
  old_json jsonb;
  new_json jsonb;
  changes jsonb := '{}'::jsonb;
begin
  if tg_op = 'INSERT' then
    insert into public.deal_events (organization_id, deal_id, type, to_stage_id, sales_id)
    values (new.organization_id, new.id, 'created', new.stage_id, private.current_sales_id());

    if new.source_id is not null then
      update public.patients
      set source_id = new.source_id
      where organization_id = new.organization_id
        and id = new.patient_id
        and source_id is null;
    end if;
    if new.sales_id is not null then
      update public.patients
      set sales_id = new.sales_id
      where organization_id = new.organization_id
        and id = new.patient_id
        and sales_id is null;
    end if;
    perform private.create_rule_tasks(new, 'deal_created', null);
    perform private.create_rule_tasks(new, 'stage_entered', new.stage_id);
    return null;
  end if;

  -- A responsible assigned later (first answer, by hand) takes the
  -- unassigned open tasks of the deal
  if new.sales_id is not null and old.sales_id is null then
    update public.tasks
    set sales_id = new.sales_id
    where organization_id = new.organization_id and deal_id = new.id
      and sales_id is null and done_date is null;
    update public.patients
    set sales_id = new.sales_id
    where organization_id = new.organization_id
      and id = new.patient_id
      and sales_id is null;
  end if;
  if new.stage_id is distinct from old.stage_id then
    perform private.create_rule_tasks(new, 'stage_entered', new.stage_id);
  end if;

  old_json := to_jsonb(old);
  new_json := to_jsonb(new);
  foreach field in array tracked loop
    if old_json -> field is distinct from new_json -> field then
      changes := changes || jsonb_build_object(field, jsonb_build_array(old_json -> field, new_json -> field));
    end if;
  end loop;

  if new.stage_id is distinct from old.stage_id then
    insert into public.deal_events (organization_id, deal_id, type, from_stage_id, to_stage_id, changes, sales_id)
    values (new.organization_id, new.id, 'stage_changed', old.stage_id, new.stage_id, changes, private.current_sales_id());
  elsif changes <> '{}'::jsonb then
    insert into public.deal_events (organization_id, deal_id, type, changes, sales_id)
    values (new.organization_id, new.id, 'updated', changes, private.current_sales_id());
  end if;
  return null;
end;
$$;

CREATE OR REPLACE FUNCTION "private"."handle_message_created"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if new.direction = 'out' then
    update public.deals d
    set first_response_at = new.sent_at
    where d.organization_id = new.organization_id and d.id = new.deal_id
      and d.first_response_at is null;
    -- "First to answer takes the lead", among the chosen employees
    if new.sales_id is not null then
      update public.deals d
      set sales_id = new.sales_id
      where d.organization_id = new.organization_id and d.id = new.deal_id
        and d.sales_id is null
        and exists (
          select 1 from public.organization_settings s
          where s.organization_id = new.organization_id
            and s.lead_distribution = 'first_response'
            and (cardinality(s.lead_distribution_sales_ids) = 0
              or new.sales_id = any(s.lead_distribution_sales_ids))
        );
    end if;
  end if;
  return null;
end;
$$;

alter table public.task_rules enable row level security;
alter table public.stage_checklist_items enable row level security;
alter table public.deal_checklist_checks enable row level security;

-- Automations: rules and checklists are settings (owner and head); checks
-- follow the deal
create policy "Organization members can read" on public.task_rules for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Owner and head can insert" on public.task_rules for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can update" on public.task_rules for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head can delete" on public.task_rules for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Organization members can read" on public.stage_checklist_items for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Owner and head can insert" on public.stage_checklist_items for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Owner and head can update" on public.stage_checklist_items for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head can delete" on public.stage_checklist_items for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.current_user_role()) in ('owner', 'head'));
create policy "Rows of visible deals can be read" on public.deal_checklist_checks for select to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = deal_checklist_checks.organization_id and d.id = deal_checklist_checks.deal_id));
create policy "Rows of visible deals can be inserted" on public.deal_checklist_checks for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = deal_checklist_checks.organization_id and d.id = deal_checklist_checks.deal_id));
create policy "Rows of visible deals can be deleted" on public.deal_checklist_checks for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = deal_checklist_checks.organization_id and d.id = deal_checklist_checks.deal_id));

-- Automations
grant all on table public.task_rules to anon;
grant all on table public.task_rules to authenticated;
grant all on table public.task_rules to service_role;
grant all on table public.stage_checklist_items to anon;
grant all on table public.stage_checklist_items to authenticated;
grant all on table public.stage_checklist_items to service_role;
grant all on table public.deal_checklist_checks to anon;
grant all on table public.deal_checklist_checks to authenticated;
grant all on table public.deal_checklist_checks to service_role;
grant all on sequence public.task_rules_id_seq to anon, authenticated, service_role;
grant all on sequence public.stage_checklist_items_id_seq to anon, authenticated, service_role;
grant all on sequence public.deal_checklist_checks_id_seq to anon, authenticated, service_role;
revoke all on function private.next_responsible(bigint) from public;
grant execute on function private.next_responsible(bigint) to authenticated, service_role;
revoke all on function private.create_rule_tasks(public.deals, text, bigint) from public;
grant execute on function private.create_rule_tasks(public.deals, text, bigint) to authenticated, service_role;

-- Default automations for the existing clinics
insert into public.task_rules (organization_id, event, stage_id, type, text, due_in_minutes, position)
select o.id, 'deal_created', null, 'call', 'Связаться с пациентом по новому обращению', 15, 0
from public.organizations o;
insert into public.task_rules (organization_id, event, stage_id, type, text, due_in_minutes, position)
select p.organization_id, 'stage_entered', s.id, 'message', 'Отправить план лечения и стоимость', 24 * 60, 1
from public.pipelines p
  join public.stages s on s.pipeline_id = p.id and s.name = 'Пришёл на консультацию'
where p.is_default;
