-- Stage 4: messengers through Wazzup24 (WhatsApp, Instagram, Telegram),
-- messages of deals, unread counts, first response time.

--
-- Messengers (Wazzup24): WhatsApp, Instagram, Telegram
--

-- Connection of the clinic to Wazzup24. The API key is a secret: no client
-- role can read this table, only the edge functions (service role).
create table public.messenger_integrations (
    organization_id bigint primary key,
    provider text not null default 'wazzup',
    api_key text,
    -- Part of the webhook URL given to Wazzup24: identifies the clinic
    webhook_token text not null default replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', ''),
    connected_at timestamp with time zone,
    last_error text,
    constraint messenger_integrations_provider_check check (provider in ('wazzup'))
);

-- Channels connected in Wazzup24 (a WhatsApp number, an Instagram account...)
create table public.messenger_channels (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    external_id text not null,
    transport text not null,
    -- Phone number or account name shown to the employees
    name text,
    state text,
    created_at timestamp with time zone not null default now(),
    constraint messenger_channels_transport_check check (transport in ('whatsapp', 'instagram', 'telegram'))
);

-- Who a patient is in each messenger: WhatsApp chats are phone numbers,
-- Instagram and Telegram chats are identified by their external id
create table public.patient_chats (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    patient_id bigint not null,
    transport text not null,
    chat_id text not null,
    username text,
    created_at timestamp with time zone not null default now(),
    constraint patient_chats_transport_check check (transport in ('whatsapp', 'instagram', 'telegram'))
);

-- Messages of a deal. Written by the edge functions only (received through
-- the webhook, or sent through Wazzup24); employees only mark them read.
create table public.messages (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    patient_id bigint not null,
    deal_id bigint not null,
    channel_id bigint,
    transport text not null,
    chat_id text not null,
    direction text not null,
    -- Author of an outgoing message; null for the patient or the system
    sales_id bigint,
    text text,
    content_uri text,
    content_type text not null default 'text',
    -- inbound, sent, delivered, read, error
    status text not null default 'sent',
    error text,
    external_id text,
    sent_at timestamp with time zone not null default now(),
    -- Incoming messages: when an employee opened the conversation
    read_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    constraint messages_direction_check check (direction in ('in', 'out')),
    constraint messages_transport_check check (transport in ('whatsapp', 'instagram', 'telegram')),
    constraint messages_status_check check (status in ('inbound', 'sent', 'delivered', 'read', 'error'))
);

alter table public.messenger_channels add constraint messenger_channels_organization_id_id_key unique (organization_id, id);
alter table public.patient_chats add constraint patient_chats_organization_id_id_key unique (organization_id, id);
alter table public.messages add constraint messages_organization_id_id_key unique (organization_id, id);

alter table public.messenger_integrations
    add constraint messenger_integrations_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.messenger_channels
    add constraint messenger_channels_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.patient_chats
    add constraint patient_chats_patient_id_fkey foreign key (organization_id, patient_id) references public.patients(organization_id, id) on delete cascade;
alter table public.messages
    add constraint messages_deal_id_fkey foreign key (organization_id, deal_id) references public.deals(organization_id, id) on delete cascade;
alter table public.messages
    add constraint messages_patient_id_fkey foreign key (organization_id, patient_id) references public.patients(organization_id, id) on delete cascade;
alter table public.messages
    add constraint messages_channel_id_fkey foreign key (organization_id, channel_id) references public.messenger_channels(organization_id, id) on delete set null (channel_id);
alter table public.messages
    add constraint messages_sales_id_fkey foreign key (organization_id, sales_id) references public.sales(organization_id, id);

create unique index messenger_integrations_webhook_token_idx on public.messenger_integrations using btree (webhook_token);
create unique index messenger_channels_external_id_idx on public.messenger_channels using btree (organization_id, external_id);
create unique index patient_chats_chat_idx on public.patient_chats using btree (organization_id, transport, chat_id);
create index messages_deal_id_idx on public.messages using btree (organization_id, deal_id, sent_at);
create index messages_unread_idx on public.messages using btree (organization_id, deal_id) where direction = 'in' and read_at is null;
create unique index messages_external_id_idx on public.messages using btree (organization_id, external_id) where external_id is not null;

--
-- Messengers
--

-- A message received from Wazzup24 (edge function wazzup_webhook, service role),
-- in a provider-neutral shape:
--   { channel_id, transport, chat_id, external_id, direction, text,
--     content_uri, content_type, sent_at, contact: { name, phone, username } }
-- Finds the patient (WhatsApp by phone, Instagram and Telegram by chat id) or
-- creates one, attaches the message to the patient's most recently updated
-- open deal or opens a new deal, and ignores a message already received.
CREATE OR REPLACE FUNCTION "public"."ingest_message"("webhook_token" "text", "message" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint;
  msg_transport text := message ->> 'transport';
  msg_chat_id text := nullif(btrim(message ->> 'chat_id'), '');
  msg_external_id text := nullif(btrim(message ->> 'external_id'), '');
  msg_direction text := coalesce(message ->> 'direction', 'in');
  contact jsonb := coalesce(message -> 'contact', '{}'::jsonb);
  contact_phone text;
  contact_name text;
  source_id bigint;
  found_message public.messages;
  new_channel_id bigint;
  found_patient_id bigint;
  found_deal_id bigint;
  new_message_id bigint;
  created_patient boolean := false;
  created_deal boolean := false;
begin
  select i.organization_id into org_id
  from public.messenger_integrations i
  where i.webhook_token = ingest_message.webhook_token;
  if org_id is null then
    raise exception 'Unknown webhook token' using errcode = '28000';
  end if;
  if msg_transport is null or msg_transport not in ('whatsapp', 'instagram', 'telegram')
    or msg_chat_id is null or msg_direction not in ('in', 'out') then
    raise exception 'Unsupported message' using errcode = '22023';
  end if;

  -- Webhooks are retried: a message is stored once
  if msg_external_id is not null then
    select * into found_message from public.messages m
    where m.organization_id = org_id and m.external_id = msg_external_id;
    if found then
      return jsonb_build_object('message_id', found_message.id, 'patient_id', found_message.patient_id,
        'deal_id', found_message.deal_id, 'duplicate', true);
    end if;
  end if;

  if nullif(btrim(message ->> 'channel_id'), '') is not null then
    insert into public.messenger_channels (organization_id, external_id, transport)
    values (org_id, btrim(message ->> 'channel_id'), msg_transport)
    on conflict (organization_id, external_id) do update set transport = excluded.transport
    returning id into new_channel_id;
  end if;

  select s.id into source_id from public.lead_sources s
  where s.organization_id = org_id and s.code = msg_transport;

  -- The patient: known chat, else (WhatsApp) the phone number, else a new one
  select c.patient_id into found_patient_id from public.patient_chats c
  where c.organization_id = org_id and c.transport = msg_transport and c.chat_id = msg_chat_id;
  if msg_transport = 'whatsapp' then
    contact_phone := private.normalize_phone(coalesce(nullif(btrim(contact ->> 'phone'), ''), msg_chat_id));
  end if;
  if found_patient_id is null and contact_phone is not null then
    select p.id into found_patient_id from public.patients p
    where p.organization_id = org_id and p.phones @> array[contact_phone]
    order by p.last_seen desc, p.id desc
    limit 1;
  end if;
  if found_patient_id is null then
    contact_name := coalesce(
      nullif(btrim(contact ->> 'name'), ''),
      nullif(btrim(contact ->> 'username'), ''),
      contact_phone,
      msg_chat_id
    );
    insert into public.patients (organization_id, first_name, phone_jsonb, whatsapp, instagram, telegram, source_id)
    values (
      org_id,
      contact_name,
      case when contact_phone is not null
        then jsonb_build_array(jsonb_build_object('number', contact_phone, 'type', 'mobile'))
        else '[]'::jsonb end,
      contact_phone,
      case when msg_transport = 'instagram' then coalesce(nullif(btrim(contact ->> 'username'), ''), msg_chat_id) end,
      case when msg_transport = 'telegram' then nullif(btrim(contact ->> 'username'), '') end,
      source_id
    )
    returning id into found_patient_id;
    created_patient := true;
  end if;
  insert into public.patient_chats (organization_id, patient_id, transport, chat_id, username)
  values (org_id, found_patient_id, msg_transport, msg_chat_id, nullif(btrim(contact ->> 'username'), ''))
  on conflict (organization_id, transport, chat_id) do nothing;

  -- The deal: the most recently updated open one, else a new request
  select d.id into found_deal_id
  from public.deals d
    join public.stages s on s.id = d.stage_id
  where d.organization_id = org_id and d.patient_id = found_patient_id
    and s.kind = 'open' and d.archived_at is null
  order by d.updated_at desc, d.id desc
  limit 1;
  if found_deal_id is null then
    insert into public.deals (organization_id, patient_id, source_id)
    values (org_id, found_patient_id, source_id)
    returning id into found_deal_id;
    created_deal := true;
  end if;

  insert into public.messages (
    organization_id, patient_id, deal_id, channel_id, transport, chat_id, direction,
    text, content_uri, content_type, status, external_id, sent_at
  ) values (
    org_id, found_patient_id, found_deal_id, new_channel_id, msg_transport, msg_chat_id, msg_direction,
    message ->> 'text',
    nullif(message ->> 'content_uri', ''),
    coalesce(nullif(message ->> 'content_type', ''), 'text'),
    case when msg_direction = 'in' then 'inbound' else 'sent' end,
    msg_external_id,
    coalesce((message ->> 'sent_at')::timestamp with time zone, now())
  )
  returning id into new_message_id;

  update public.patients set last_seen = now()
  where organization_id = org_id and id = found_patient_id;

  return jsonb_build_object('message_id', new_message_id, 'patient_id', found_patient_id,
    'deal_id', found_deal_id, 'created_patient', created_patient, 'created_deal', created_deal,
    'duplicate', false);
end;
$$;

-- Delivery status of an outgoing message (edge function wazzup_webhook)
CREATE OR REPLACE FUNCTION "public"."update_message_status"("webhook_token" "text", "external_id" "text", "status" "text", "error" "text" DEFAULT NULL::"text") RETURNS boolean
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint;
begin
  select i.organization_id into org_id
  from public.messenger_integrations i
  where i.webhook_token = update_message_status.webhook_token;
  if org_id is null then
    raise exception 'Unknown webhook token' using errcode = '28000';
  end if;
  if update_message_status.status not in ('sent', 'delivered', 'read', 'error') then
    return false;
  end if;
  update public.messages m
  set status = update_message_status.status,
      error = case when update_message_status.status = 'error' then update_message_status.error end
  where m.organization_id = org_id
    and m.external_id = update_message_status.external_id
    and m.direction = 'out';
  return found;
end;
$$;

-- The employee opened the conversation of a deal
CREATE OR REPLACE FUNCTION "public"."mark_deal_messages_read"("deal_id" bigint) RETURNS integer
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  marked integer;
begin
  update public.messages m
  set read_at = now()
  where m.deal_id = mark_deal_messages_read.deal_id
    and m.direction = 'in'
    and m.read_at is null;
  get diagnostics marked = row_count;
  return marked;
end;
$$;

-- Is the clinic connected to Wazzup24 (owner and head; the key stays secret)
CREATE OR REPLACE FUNCTION "public"."messenger_status"() RETURNS TABLE("connected" boolean, "connected_at" timestamp with time zone, "last_error" "text")
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
  select i.api_key is not null, i.connected_at, i.last_error
  from public.messenger_integrations i
  where i.organization_id = private.current_organization_id()
    and private.current_user_role() in ('owner', 'head')
$$;

-- First answer to the patient: deals.first_response_at (response time reports)
CREATE OR REPLACE FUNCTION "private"."handle_message_created"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if new.direction = 'out' then
    update public.deals d
    set first_response_at = new.sent_at
    where d.organization_id = new.organization_id and d.id = new.deal_id
      and d.first_response_at is null;
  end if;
  return null;
end;
$$;

create or replace view public.deals_summary with (security_invoker = on) as
select
    d.id,
    d.organization_id,
    d.patient_id,
    d.pipeline_id,
    d.stage_id,
    d.name,
    d.source_id,
    d.service_id,
    d.plan_amount,
    d.paid_amount,
    d.sales_id,
    d.lost_reason_id,
    d.lost_comment,
    d.appointment_at,
    d.visit_at,
    d.tags,
    d.description,
    d.index,
    d.created_at,
    d.updated_at,
    d.stage_changed_at,
    d.closed_at,
    d.first_response_at,
    d.archived_at,
    s.kind as stage_kind,
    p.first_name as patient_first_name,
    p.last_name as patient_last_name,
    p.phones[1] as patient_phone,
    lower(concat_ws(' ', d.name, p.last_name, p.first_name, p.middle_name, array_to_string(p.phones, ' '))) as search_text,
    (
        select count(*)
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
    ) as nb_open_tasks,
    (
        select min(t.due_date)
        from public.tasks t
        where t.organization_id = d.organization_id and t.deal_id = d.id and t.done_date is null
    ) as next_task_due_at,
    (
        select count(*)
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id and m.direction = 'in' and m.read_at is null
    ) as nb_unread_messages,
    (
        select max(m.sent_at)
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id
    ) as last_message_at,
    (
        select m.text
        from public.messages m
        where m.organization_id = d.organization_id and m.deal_id = d.id
        order by m.sent_at desc, m.id desc
        limit 1
    ) as last_message_text
from public.deals d
    join public.stages s on s.id = d.stage_id
    join public.patients p on p.organization_id = d.organization_id and p.id = d.patient_id;

-- Messages: first answer of the deal
create or replace trigger message_created
    after insert on public.messages
    for each row execute function private.handle_message_created();

alter table public.messenger_integrations enable row level security;
alter table public.messenger_channels enable row level security;
alter table public.patient_chats enable row level security;
alter table public.messages enable row level security;

-- Messengers. messenger_integrations has no policy at all: its API key is
-- only read by the edge functions (service role).
create policy "Organization members can read" on public.messenger_channels for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Organization members can read" on public.patient_chats for select to authenticated
    using (organization_id = (select private.current_organization_id()));
create policy "Rows of visible deals can be read" on public.messages for select to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = messages.organization_id and d.id = messages.deal_id));
-- Only read_at is updatable (column grant): opening a conversation
create policy "Rows of visible deals can be updated" on public.messages for update to authenticated
    using (organization_id = (select private.current_organization_id()) and exists (select 1 from public.deals d where d.organization_id = messages.organization_id and d.id = messages.deal_id))
    with check (organization_id = (select private.current_organization_id()));

-- Messengers: the API key table is for the service role only; employees read
-- channels, chats and messages and may only mark messages read
revoke all on table public.messenger_integrations from anon, authenticated;
grant all on table public.messenger_integrations to service_role;
revoke all on table public.messenger_channels from anon, authenticated;
grant select on table public.messenger_channels to authenticated;
grant all on table public.messenger_channels to service_role;
revoke all on table public.patient_chats from anon, authenticated;
grant select on table public.patient_chats to authenticated;
grant all on table public.patient_chats to service_role;
revoke all on table public.messages from anon, authenticated;
grant select on table public.messages to authenticated;
grant update (read_at) on table public.messages to authenticated;
grant all on table public.messages to service_role;
revoke all on sequence public.messenger_channels_id_seq from anon, authenticated;
revoke all on sequence public.patient_chats_id_seq from anon, authenticated;
revoke all on sequence public.messages_id_seq from anon, authenticated;
grant all on sequence public.messenger_channels_id_seq to service_role;
grant all on sequence public.patient_chats_id_seq to service_role;
grant all on sequence public.messages_id_seq to service_role;

revoke all on function public.ingest_message(text, jsonb) from public, anon, authenticated;
grant execute on function public.ingest_message(text, jsonb) to service_role;
revoke all on function public.update_message_status(text, text, text, text) from public, anon, authenticated;
grant execute on function public.update_message_status(text, text, text, text) to service_role;
revoke all on function public.mark_deal_messages_read(bigint) from public, anon;
grant execute on function public.mark_deal_messages_read(bigint) to authenticated, service_role;
revoke all on function public.messenger_status() from public, anon;
grant execute on function public.messenger_status() to authenticated, service_role;
revoke all on function private.handle_message_created() from public;
grant execute on function private.handle_message_created() to service_role;
