--
-- Stage 44: finance (see supabase/schemas/44_finance.sql) — money accounts,
-- the articles of the ДДС and the P&L, the method map, manual money
-- movements and accruals, the transactions linked to the payouts and the
-- lab payments paid without the cash desk, the reports report_cash_flow,
-- report_cash_flow_movements, report_pnl and the financial model
-- (report_finance_model); the data of the existing clinics.
--

--
-- Tables
--

create table public.finance_accounts (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    kind text not null default 'bank',
    -- System accounts: till, kaspi, bank
    code text,
    opening_balance bigint not null default 0,
    opening_date date,
    is_active boolean not null default true,
    position integer not null default 0,
    created_at timestamp with time zone not null default now(),
    constraint finance_accounts_name_not_blank check (btrim(name) <> ''),
    constraint finance_accounts_name_length check (char_length(name) <= 100),
    constraint finance_accounts_kind_check check (kind in ('cash', 'bank', 'kaspi', 'other')),
    constraint finance_accounts_code_check check (code is null or code in ('till', 'kaspi', 'bank')),
    constraint finance_accounts_opening_check check (opening_balance between -100000000000 and 100000000000)
);

create table public.finance_articles (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    code text,
    section text not null,
    activity text not null default 'operating',
    pnl_line text,
    is_active boolean not null default true,
    position integer not null default 0,
    created_at timestamp with time zone not null default now(),
    constraint finance_articles_name_not_blank check (btrim(name) <> ''),
    constraint finance_articles_name_length check (char_length(name) <= 100),
    constraint finance_articles_section_check check (section in ('in', 'out')),
    constraint finance_articles_activity_check check (activity in ('operating', 'investing', 'financing')),
    constraint finance_articles_pnl_line_check check (pnl_line is null or pnl_line in (
        'revenue', 'other_income', 'materials', 'lab', 'doctors', 'staff', 'marketing', 'opex',
        'interest', 'depreciation', 'tax')),
    constraint finance_articles_code_check check (code is null or code in (
        'services', 'prepayments', 'refunds', 'other_in', 'loans_in', 'owner_in',
        'salary_doctors', 'salary_staff', 'lab', 'materials', 'rent', 'utilities', 'marketing', 'taxes',
        'loans', 'interest', 'equipment', 'dividends', 'depreciation', 'other_out'))
);

create table public.finance_method_accounts (
    organization_id bigint not null default private.current_organization_id(),
    method text not null,
    account_id bigint not null,
    constraint finance_method_accounts_pkey primary key (organization_id, method),
    constraint finance_method_accounts_method_check check (method in (
        'cash', 'card', 'kaspi_qr', 'kaspi_transfer', 'bank_transfer', 'insurance', 'other'))
);

create table public.finance_transactions (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    -- in, out, transfer (account → to_account), accrual (no money, P&L only)
    kind text not null,
    occurred_on date not null default CURRENT_DATE,
    account_id bigint,
    to_account_id bigint,
    article_id bigint,
    amount bigint not null,
    counterparty text,
    comment text,
    branch_id bigint,
    -- The payroll payout / lab payment paid without the cash desk
    payroll_adjustment_id bigint,
    lab_payment_id bigint,
    created_by bigint default private.current_sales_id(),
    created_at timestamp with time zone not null default now(),
    constraint finance_transactions_kind_check check (kind in ('in', 'out', 'transfer', 'accrual')),
    constraint finance_transactions_amount_check check (amount > 0 and amount <= 100000000000),
    constraint finance_transactions_kind_rules check (
        case kind
            when 'transfer' then account_id is not null and to_account_id is not null and account_id <> to_account_id
                and article_id is null
            when 'accrual' then account_id is null and to_account_id is null and article_id is not null
            else account_id is not null and to_account_id is null and article_id is not null
        end),
    constraint finance_transactions_link_check check (num_nonnulls(payroll_adjustment_id, lab_payment_id) <= 1
        and (num_nonnulls(payroll_adjustment_id, lab_payment_id) = 0 or kind = 'out')),
    constraint finance_transactions_counterparty_length check (counterparty is null or char_length(counterparty) <= 200),
    constraint finance_transactions_comment_length check (comment is null or char_length(comment) <= 1000)
);

create table public.finance_models (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    name text not null,
    -- The first of the 12 months
    start_month date not null,
    -- Drivers (a month may override them: finance_model_months)
    chairs numeric(6,2) not null default 3,
    working_days numeric(5,2) not null default 24,
    hours_per_day numeric(5,2) not null default 10,
    utilization numeric(5,2) not null default 70,
    visits_per_chair_hour numeric(6,2) not null default 0.8,
    avg_check bigint not null default 25000,
    -- Scenario multipliers of the utilization
    optimistic_factor numeric(4,2) not null default 1.15,
    pessimistic_factor numeric(4,2) not null default 0.85,
    opening_cash bigint not null default 0,
    investment_amount bigint not null default 0,
    investment_month smallint not null default 0,
    note text,
    created_by bigint default private.current_sales_id(),
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint finance_models_name_not_blank check (btrim(name) <> ''),
    constraint finance_models_name_length check (char_length(name) <= 100),
    constraint finance_models_start_month_check check (extract(day from start_month) = 1),
    constraint finance_models_drivers_check check (chairs >= 0 and chairs <= 1000 and working_days >= 0 and working_days <= 31
        and hours_per_day >= 0 and hours_per_day <= 24 and utilization >= 0 and utilization <= 100
        and visits_per_chair_hour >= 0 and visits_per_chair_hour <= 100 and avg_check >= 0 and avg_check <= 100000000),
    constraint finance_models_factors_check check (optimistic_factor > 0 and optimistic_factor <= 10
        and pessimistic_factor > 0 and pessimistic_factor <= 10),
    constraint finance_models_investment_check check (investment_amount >= 0 and investment_amount <= 100000000000
        and investment_month between 0 and 11),
    constraint finance_models_opening_cash_check check (opening_cash between -100000000000 and 100000000000),
    constraint finance_models_note_length check (note is null or char_length(note) <= 2000)
);

create table public.finance_model_months (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    model_id bigint not null,
    month_index smallint not null,
    chairs numeric(6,2),
    working_days numeric(5,2),
    hours_per_day numeric(5,2),
    utilization numeric(5,2),
    visits_per_chair_hour numeric(6,2),
    avg_check bigint,
    constraint finance_model_months_index_check check (month_index between 0 and 11),
    constraint finance_model_months_drivers_check check ((chairs is null or chairs between 0 and 1000)
        and (working_days is null or working_days between 0 and 31) and (hours_per_day is null or hours_per_day between 0 and 24)
        and (utilization is null or utilization between 0 and 100)
        and (visits_per_chair_hour is null or visits_per_chair_hour between 0 and 100)
        and (avg_check is null or avg_check between 0 and 100000000))
);

create table public.finance_model_lines (
    id bigint generated by default as identity primary key,
    organization_id bigint not null default private.current_organization_id(),
    model_id bigint not null,
    name text not null,
    article_id bigint,
    pnl_line text not null,
    -- fixed: amount per month; percent: of the month's revenue
    kind text not null default 'fixed',
    amount bigint not null default 0,
    percent numeric(5,2) not null default 0,
    from_index smallint not null default 0,
    to_index smallint not null default 11,
    position integer not null default 0,
    constraint finance_model_lines_name_not_blank check (btrim(name) <> ''),
    constraint finance_model_lines_name_length check (char_length(name) <= 100),
    constraint finance_model_lines_pnl_line_check check (pnl_line in (
        'materials', 'lab', 'doctors', 'staff', 'marketing', 'opex', 'interest', 'depreciation', 'tax')),
    constraint finance_model_lines_kind_check check (kind in ('fixed', 'percent')),
    constraint finance_model_lines_amount_check check (amount >= 0 and amount <= 100000000000),
    constraint finance_model_lines_percent_check check (percent >= 0 and percent <= 100),
    constraint finance_model_lines_months_check check (from_index between 0 and 11 and to_index between from_index and 11)
);

alter table public.finance_accounts add constraint finance_accounts_organization_id_id_key unique (organization_id, id);
alter table public.finance_articles add constraint finance_articles_organization_id_id_key unique (organization_id, id);
alter table public.finance_transactions add constraint finance_transactions_organization_id_id_key unique (organization_id, id);
alter table public.finance_transactions add constraint finance_transactions_payroll_adjustment_id_key unique (payroll_adjustment_id);
alter table public.finance_transactions add constraint finance_transactions_lab_payment_id_key unique (lab_payment_id);
alter table public.finance_models add constraint finance_models_organization_id_id_key unique (organization_id, id);
alter table public.finance_model_months add constraint finance_model_months_model_month_key unique (model_id, month_index);

alter table public.finance_accounts
    add constraint finance_accounts_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.finance_articles
    add constraint finance_articles_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.finance_method_accounts
    add constraint finance_method_accounts_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.finance_method_accounts
    add constraint finance_method_accounts_account_id_fkey foreign key (organization_id, account_id) references public.finance_accounts(organization_id, id);
alter table public.finance_transactions
    add constraint finance_transactions_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.finance_transactions
    add constraint finance_transactions_account_id_fkey foreign key (organization_id, account_id) references public.finance_accounts(organization_id, id);
alter table public.finance_transactions
    add constraint finance_transactions_to_account_id_fkey foreign key (organization_id, to_account_id) references public.finance_accounts(organization_id, id);
alter table public.finance_transactions
    add constraint finance_transactions_article_id_fkey foreign key (organization_id, article_id) references public.finance_articles(organization_id, id);
alter table public.finance_transactions
    add constraint finance_transactions_branch_id_fkey foreign key (organization_id, branch_id) references public.branches(organization_id, id) on delete set null (branch_id);
alter table public.finance_transactions
    add constraint finance_transactions_payroll_adjustment_id_fkey foreign key (organization_id, payroll_adjustment_id) references public.payroll_adjustments(organization_id, id) on delete cascade;
alter table public.finance_transactions
    add constraint finance_transactions_lab_payment_id_fkey foreign key (organization_id, lab_payment_id) references public.lab_payments(organization_id, id) on delete cascade;
alter table public.finance_transactions
    add constraint finance_transactions_created_by_fkey foreign key (organization_id, created_by) references public.sales(organization_id, id) on delete set null (created_by);
alter table public.finance_models
    add constraint finance_models_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.finance_models
    add constraint finance_models_created_by_fkey foreign key (organization_id, created_by) references public.sales(organization_id, id) on delete set null (created_by);
alter table public.finance_model_months
    add constraint finance_model_months_model_id_fkey foreign key (organization_id, model_id) references public.finance_models(organization_id, id) on delete cascade;
alter table public.finance_model_lines
    add constraint finance_model_lines_model_id_fkey foreign key (organization_id, model_id) references public.finance_models(organization_id, id) on delete cascade;
alter table public.finance_model_lines
    add constraint finance_model_lines_article_id_fkey foreign key (organization_id, article_id) references public.finance_articles(organization_id, id) on delete set null (article_id);

create unique index finance_accounts_code_idx on public.finance_accounts using btree (organization_id, code) where code is not null;
create unique index finance_accounts_name_idx on public.finance_accounts using btree (organization_id, lower(name));
create unique index finance_articles_code_idx on public.finance_articles using btree (organization_id, code) where code is not null;
create unique index finance_articles_name_idx on public.finance_articles using btree (organization_id, lower(name));
create index finance_transactions_day_idx on public.finance_transactions using btree (organization_id, occurred_on);
create index finance_model_lines_model_idx on public.finance_model_lines using btree (organization_id, model_id);

-- The article of an expense category (stage 42)
alter table public.cash_expense_categories add column article_id bigint;
alter table public.cash_expense_categories
    add constraint cash_expense_categories_article_id_fkey foreign key (organization_id, article_id) references public.finance_articles(organization_id, id) on delete set null (article_id);

--
-- Functions
--

-- The accounts, the method map and the articles of a new clinic; the
-- expense categories get their articles
CREATE OR REPLACE FUNCTION "private"."seed_finance"("org_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  insert into public.finance_accounts (organization_id, name, kind, code, position)
  select org_id, a.name, a.kind, a.code, a.position
  from (values
    ('Касса', 'cash', 'till', 0),
    ('Kaspi', 'kaspi', 'kaspi', 1),
    ('Банк', 'bank', 'bank', 2)
  ) as a(name, kind, code, position)
  where not exists (
    select 1 from public.finance_accounts f
    where f.organization_id = org_id and (f.code = a.code or lower(f.name) = lower(a.name)));

  insert into public.finance_method_accounts (organization_id, method, account_id)
  select org_id, m.method, f.id
  from (values
    ('cash', 'till'),
    ('card', 'kaspi'),
    ('kaspi_qr', 'kaspi'),
    ('kaspi_transfer', 'kaspi'),
    ('bank_transfer', 'bank'),
    ('insurance', 'bank'),
    ('other', 'bank')
  ) as m(method, code)
    join public.finance_accounts f on f.organization_id = org_id and f.code = m.code
  on conflict (organization_id, method) do nothing;

  insert into public.finance_articles (organization_id, name, code, section, activity, pnl_line, position)
  select org_id, a.name, a.code, a.section, a.activity, a.pnl_line, a.position
  from (values
    ('Оплата услуг', 'services', 'in', 'operating', 'revenue', 0),
    ('Предоплаты и депозиты', 'prepayments', 'in', 'operating', null, 1),
    ('Возвраты пациентам', 'refunds', 'in', 'operating', null, 2),
    ('Прочие поступления', 'other_in', 'in', 'operating', 'other_income', 3),
    ('Кредиты и займы полученные', 'loans_in', 'in', 'financing', null, 4),
    ('Вклад собственника', 'owner_in', 'in', 'financing', null, 5),
    ('Зарплата врачей', 'salary_doctors', 'out', 'operating', 'doctors', 10),
    ('Зарплата персонала', 'salary_staff', 'out', 'operating', 'staff', 11),
    ('Лаборатория', 'lab', 'out', 'operating', 'lab', 12),
    ('Материалы', 'materials', 'out', 'operating', 'materials', 13),
    ('Аренда', 'rent', 'out', 'operating', 'opex', 14),
    ('Коммунальные услуги', 'utilities', 'out', 'operating', 'opex', 15),
    ('Маркетинг', 'marketing', 'out', 'operating', 'marketing', 16),
    ('Налоги', 'taxes', 'out', 'operating', 'tax', 17),
    ('Кредиты и лизинг', 'loans', 'out', 'financing', null, 18),
    ('Проценты по кредитам', 'interest', 'out', 'financing', 'interest', 19),
    ('Оборудование и ремонт', 'equipment', 'out', 'investing', null, 20),
    ('Дивиденды и вывод собственника', 'dividends', 'out', 'financing', null, 21),
    ('Амортизация', 'depreciation', 'out', 'operating', 'depreciation', 22),
    ('Прочие выплаты', 'other_out', 'out', 'operating', 'opex', 23)
  ) as a(name, code, section, activity, pnl_line, position)
  where not exists (
    select 1 from public.finance_articles f
    where f.organization_id = org_id and (f.code = a.code or lower(f.name) = lower(a.name)));

  update public.cash_expense_categories c
  set article_id = f.id
  from public.finance_articles f
  where c.organization_id = org_id and c.article_id is null and c.code is not null
    and f.organization_id = org_id
    and f.code = case c.code when 'salary' then 'salary_staff' when 'other' then 'other_out' else c.code end;
end;
$$;

CREATE OR REPLACE FUNCTION "private"."handle_organization_finance"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  perform private.seed_finance(new.id);
  return new;
end;
$$;

-- The article of a system code in a clinic
CREATE OR REPLACE FUNCTION "private"."finance_article_id"("org_id" bigint, "article_code" "text") RETURNS bigint
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  return (select a.id from public.finance_articles a where a.organization_id = org_id and a.code = article_code);
end;
$$;

-- The account a method of the cash desk lands in
CREATE OR REPLACE FUNCTION "private"."finance_method_account"("org_id" bigint, "target_method" "text") RETURNS bigint
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  return (select m.account_id from public.finance_method_accounts m
    where m.organization_id = org_id and m.method = target_method);
end;
$$;

-- ДДС: the reports right (owner, head, an administrator with «Отчёты»)
CREATE OR REPLACE FUNCTION "private"."finance_can_view"() RETURNS boolean
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  return coalesce(private.current_user_role() in ('owner', 'head', 'manager')
    and private.access_scope('reports', 'view') = 'all', false);
end;
$$;

-- ПиУ, the model, every write: the owner and the head
CREATE OR REPLACE FUNCTION "private"."finance_can_edit"() RETURNS boolean
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  return coalesce(private.current_user_role() in ('owner', 'head'), false);
end;
$$;

-- Every money movement of the clinic between two days (half-open, either
-- may be null) — see the header. amount: + into the account, − out of it.
CREATE OR REPLACE FUNCTION "private"."finance_movements"("org_id" bigint, "from_day" "date", "to_day" "date") RETURNS TABLE("source" "text", "source_id" bigint, "day" "date", "account_id" bigint, "article_id" bigint, "amount" bigint, "branch_id" bigint, "transfer" boolean, "counterparty" "text", "comment" "text")
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
#variable_conflict use_column
declare
  tz text := coalesce((select nullif(o.timezone, '') from public.organizations o where o.id = org_id), 'Asia/Almaty');
  from_at timestamp with time zone := case when from_day is null then null else from_day::timestamp at time zone tz end;
  to_at timestamp with time zone := case when to_day is null then null else to_day::timestamp at time zone tz end;
  a_services bigint := private.finance_article_id(org_id, 'services');
  a_prepayments bigint := private.finance_article_id(org_id, 'prepayments');
  a_refunds bigint := private.finance_article_id(org_id, 'refunds');
  a_doctors bigint := private.finance_article_id(org_id, 'salary_doctors');
  a_staff bigint := private.finance_article_id(org_id, 'salary_staff');
  a_other bigint := private.finance_article_id(org_id, 'other_out');
begin
  return query
  select 'operation'::text, o.id, (o.occurred_at at time zone tz)::date, m.account_id,
    case o.kind
      when 'payment' then case when o.prepayment then a_prepayments else a_services end
      when 'deposit' then a_prepayments
      when 'refund' then a_refunds
      else coalesce(case when pa.id is null then null when pa.doctor_id is not null then a_doctors else a_staff end,
        c.article_id, a_other)
    end,
    (sign(o.till_delta) * part.amount)::bigint,
    o.branch_id, false,
    coalesce(nullif(btrim(concat_ws(' ', pt.last_name, pt.first_name)), ''), c.name),
    o.comment
  from public.account_operations o
    cross join lateral (
      select p ->> 'method' as method, (p ->> 'amount')::bigint as amount
      from jsonb_array_elements(o.parts) p
      where o.method = 'mixed'
      union all
      select o.method, o.amount where o.method <> 'mixed'
    ) part
    left join public.finance_method_accounts m on m.organization_id = o.organization_id and m.method = part.method
    left join public.cash_expense_categories c on c.organization_id = o.organization_id and c.id = o.category_id
    left join public.payroll_adjustments pa on pa.organization_id = o.organization_id and pa.account_operation_id = o.id
    left join public.patients pt on pt.organization_id = o.organization_id and pt.id = o.patient_id
  where o.organization_id = org_id and o.till_delta <> 0 and part.amount <> 0
    and (from_at is null or o.occurred_at >= from_at)
    and (to_at is null or o.occurred_at < to_at)
  union all
  select 'transaction'::text, t.id, t.occurred_on, x.account_id, t.article_id, x.amount, t.branch_id, t.kind = 'transfer',
    t.counterparty, t.comment
  from public.finance_transactions t
    cross join lateral (
      select t.account_id, case when t.kind = 'in' then t.amount else - t.amount end as amount
      union all
      select t.to_account_id, t.amount where t.kind = 'transfer'
    ) x
  where t.organization_id = org_id and t.kind <> 'accrual'
    and (from_day is null or t.occurred_on >= from_day)
    and (to_day is null or t.occurred_on < to_day);
end;
$$;

-- The bucket of a day: its day, the Monday of its week, the first of its month
CREATE OR REPLACE FUNCTION "private"."finance_bucket"("day" "date", "granularity" "text") RETURNS "date"
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select date_trunc(granularity, day::timestamp)::date;
$$;

-- «ДДС»: the cash flow statement between two days (half-open) by day, week
-- or month, with the balances of the accounts (see the header)
CREATE OR REPLACE FUNCTION "public"."report_cash_flow"("period_from" "date", "period_to" "date", "filter_branch_id" bigint DEFAULT NULL::bigint, "granularity" "text" DEFAULT 'month'::"text") RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  step interval;
  periods date[];
  result jsonb;
begin
  if not private.finance_can_view() then
    raise exception 'Нет доступа к финансам' using errcode = 'insufficient_privilege', hint = 'finance_forbidden';
  end if;
  if period_from is null or period_to is null or period_to <= period_from then
    raise exception 'Укажите период' using errcode = '22023', hint = 'finance_period';
  end if;
  if granularity not in ('day', 'week', 'month') then
    raise exception 'Разбивка — по дням, неделям или месяцам' using errcode = '22023', hint = 'finance_granularity';
  end if;
  step := ('1 ' || granularity)::interval;
  select array_agg(g::date order by g) into periods
  from generate_series(private.finance_bucket(period_from, granularity)::timestamp,
    private.finance_bucket(period_to - 1, granularity)::timestamp, step) g;
  if cardinality(periods) > 400 then
    raise exception 'Слишком длинный период для такой разбивки' using errcode = '22023', hint = 'finance_period';
  end if;

  with mv as (
    select m.*, private.finance_bucket(m.day, granularity) as period
    from private.finance_movements(org_id, null, period_to) m
    where filter_branch_id is null or m.branch_id = filter_branch_id
  ),
  inside as (
    select * from mv where mv.day >= period_from
  ),
  article_rows as (
    select i.article_id, i.period, sum(i.amount)::bigint as amount
    from inside i where not i.transfer
    group by i.article_id, i.period
  ),
  accounts as (
    select a.id as account_id, a.opening_balance, a.opening_date, a.position
    from public.finance_accounts a where a.organization_id = org_id
    union all
    select null::bigint, 0::bigint, null::date, 1000000
    where exists (select 1 from mv where mv.account_id is null)
  ),
  balances as (
    select a.account_id, a.position,
      case when filter_branch_id is null then
        a.opening_balance
        + coalesce((select sum(m.amount) from mv m where m.account_id is not distinct from a.account_id and m.day < period_from), 0)
        - coalesce((select sum(m.amount) from mv m where m.account_id is not distinct from a.account_id and m.day < a.opening_date), 0)
      end::bigint as opening,
      coalesce((select sum(i.amount) from inside i where i.account_id is not distinct from a.account_id), 0)::bigint as flow,
      coalesce((
        select jsonb_agg(jsonb_build_object('period', f.period, 'amount', f.amount) order by f.period)
        from (select i.period, sum(i.amount)::bigint as amount from inside i
          where i.account_id is not distinct from a.account_id group by i.period) f
      ), '[]'::jsonb) as flows
    from accounts a
  ),
  per as (
    select p.period,
      coalesce(sum(i.amount) filter (where not i.transfer and ar.section = 'in'), 0)::bigint as inflow,
      coalesce(- sum(i.amount) filter (where not i.transfer and ar.section = 'out'), 0)::bigint as outflow,
      coalesce(sum(i.amount) filter (where not i.transfer), 0)::bigint as net
    from unnest(periods) as p(period)
      left join inside i on i.period = p.period
      left join public.finance_articles ar on ar.organization_id = org_id and ar.id = i.article_id
    group by p.period
  ),
  opening as (
    select case when filter_branch_id is null then sum(b.opening)::bigint end as total from balances b
  ),
  totals as (
    select per.*,
      (o.total + coalesce(sum(per.net) over (order by per.period rows between unbounded preceding and 1 preceding), 0))::bigint as opening,
      (o.total + sum(per.net) over (order by per.period rows between unbounded preceding and current row))::bigint as closing
    from per cross join opening o
  )
  select jsonb_build_object(
    'granularity', granularity,
    'from', period_from,
    'to', period_to,
    'periods', to_jsonb(periods),
    'balances', filter_branch_id is null,
    'rows', coalesce((select jsonb_agg(jsonb_build_object('article_id', r.article_id, 'period', r.period, 'amount', r.amount)
      order by r.article_id, r.period) from article_rows r), '[]'::jsonb),
    'accounts', coalesce((select jsonb_agg(jsonb_build_object('account_id', b.account_id, 'opening', b.opening,
      'closing', b.opening + b.flow, 'flow', b.flow, 'flows', b.flows) order by b.position, b.account_id) from balances b), '[]'::jsonb),
    'totals', coalesce((select jsonb_agg(jsonb_build_object('period', t.period, 'inflow', t.inflow, 'outflow', t.outflow,
      'net', t.net, 'opening', t.opening, 'closing', t.closing) order by t.period) from totals t), '[]'::jsonb),
    'total', (select jsonb_build_object('inflow', coalesce(sum(t.inflow), 0), 'outflow', coalesce(sum(t.outflow), 0),
      'net', coalesce(sum(t.net), 0), 'opening', (select o.total from opening o),
      'closing', (select o.total from opening o) + coalesce(sum(t.net), 0)) from per t)
  ) into result;
  return result;
end;
$$;

-- The drill-down of a cell of the ДДС: the movements of the period with the
-- article (or the transfers: filter_transfers) and / or the account
CREATE OR REPLACE FUNCTION "public"."report_cash_flow_movements"("period_from" "date", "period_to" "date", "filter_branch_id" bigint DEFAULT NULL::bigint, "filter_article_id" bigint DEFAULT NULL::bigint, "filter_account_id" bigint DEFAULT NULL::bigint, "filter_transfers" boolean DEFAULT false) RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if not private.finance_can_view() then
    raise exception 'Нет доступа к финансам' using errcode = 'insufficient_privilege', hint = 'finance_forbidden';
  end if;
  return coalesce((
    select jsonb_agg(to_jsonb(m) order by m.day desc, m.source, m.source_id desc)
    from (
      select * from private.finance_movements(private.current_organization_id(), period_from, period_to) x
      where (filter_branch_id is null or x.branch_id = filter_branch_id)
        and (filter_article_id is null or x.article_id = filter_article_id)
        and (filter_account_id is null or x.account_id = filter_account_id)
        and (not filter_transfers or x.transfer)
      order by x.day desc, x.source, x.source_id desc
      limit 1000
    ) m
  ), '[]'::jsonb);
end;
$$;

-- Services rendered between two moments (see the header: the recognition of
-- private.payroll_compute for the plan items, of the patient account for
-- the visits), with the cost price of their materials
CREATE OR REPLACE FUNCTION "private"."finance_revenue_items"("org_id" bigint, "from_at" timestamp with time zone, "to_at" timestamp with time zone) RETURNS TABLE("source" "text", "source_id" bigint, "done_at" timestamp with time zone, "amount" bigint, "cost" bigint, "branch_id" bigint, "doctor_id" bigint)
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
#variable_conflict use_column
begin
  return query
  with plans as (
    select distinct i.plan_id
    from public.treatment_plan_items i
    where i.organization_id = org_id and i.done and i.done_at >= from_at and i.done_at < to_at
  ),
  stage_sums as (
    select s.id, s.discount_percent, coalesce(sum(i.line_total), 0)::bigint as lines
    from public.treatment_stages s
      left join public.treatment_plan_items i on i.organization_id = s.organization_id and i.stage_id = s.id
    where s.organization_id = org_id and s.plan_id in (select plan_id from plans)
    group by s.id, s.discount_percent
  ),
  plan_sums as (
    select p.id, private.treatment_plan_subtotal(org_id, p.id) as subtotal, p.discount_percent, p.discount_amount,
      p.deal_id, p.doctor_id
    from public.treatment_plans p
    where p.organization_id = org_id and p.id in (select plan_id from plans) and p.status <> 'declined'
  )
  select 'plan_item'::text, i.id, i.done_at,
    private.payroll_mul_div(
      i.line_total::numeric * private.treatment_stage_total(ss.lines, ss.discount_percent),
      private.treatment_plan_total(ps.subtotal, ps.discount_percent, ps.discount_amount),
      ss.lines::numeric * ps.subtotal),
    coalesce(round(sc.cost_price * i.quantity)::bigint, 0),
    d.branch_id,
    coalesce(i.doctor_id, s.doctor_id, ps.doctor_id)
  from public.treatment_plan_items i
    join public.treatment_stages s on s.organization_id = i.organization_id and s.id = i.stage_id
    join stage_sums ss on ss.id = s.id
    join plan_sums ps on ps.id = i.plan_id
    left join public.deals d on d.organization_id = org_id and d.id = ps.deal_id
    left join public.service_costs sc on sc.organization_id = org_id and sc.service_id = i.service_id
  where i.organization_id = org_id and i.done and i.done_at >= from_at and i.done_at < to_at and s.status <> 'cancelled'
  union all
  select 'visit'::text, v.id, v.starts_at, round(sv.price)::bigint, coalesce(round(sc.cost_price)::bigint, 0),
    v.branch_id, v.doctor_id
  from public.visits v
    join public.services sv on sv.organization_id = v.organization_id and sv.id = v.service_id
    left join public.service_costs sc on sc.organization_id = org_id and sc.service_id = sv.id
  where v.organization_id = org_id and v.status = 'completed' and v.source = 'crm'
    and sv.price > 0 and v.starts_at >= from_at and v.starts_at < to_at
    and not exists (
      select 1 from public.treatment_plans tp
      where tp.organization_id = v.organization_id and tp.deal_id = v.deal_id and tp.status <> 'declined');
end;
$$;

-- Every amount of the P&L between two months (from_month included,
-- to_month excluded): (month, line, source, article, branch, amount).
-- Income lines (revenue, other_income) and cost lines are positive;
-- refunds are a line of their own, subtracted from the revenue.
CREATE OR REPLACE FUNCTION "private"."finance_pnl_facts"("org_id" bigint, "from_month" "date", "to_month" "date") RETURNS TABLE("month" "date", "line" "text", "source" "text", "article_id" bigint, "branch_id" bigint, "amount" bigint)
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
#variable_conflict use_column
declare
  tz text := coalesce((select nullif(o.timezone, '') from public.organizations o where o.id = org_id), 'Asia/Almaty');
  from_at timestamp with time zone := from_month::timestamp at time zone tz;
  to_at timestamp with time zone := to_month::timestamp at time zone tz;
begin
  -- Services rendered and their materials
  return query
  select date_trunc('month', r.done_at at time zone tz)::date, x.line, 'services'::text, null::bigint, r.branch_id, x.amount
  from private.finance_revenue_items(org_id, from_at, to_at) r
    cross join lateral (values ('revenue', r.amount), ('materials', r.cost)) as x(line, amount)
  where x.amount <> 0;

  -- Refunds of services
  return query
  select date_trunc('month', o.occurred_at at time zone tz)::date, 'refunds'::text, 'refunds'::text, null::bigint,
    o.branch_id, o.amount
  from public.account_operations o
  where o.organization_id = org_id and o.kind = 'refund' and o.account = 'services'
    and o.occurred_at >= from_at and o.occurred_at < to_at;

  -- The lab (stage 40; the costs stage 43 marks free are 0 there)
  return query
  select c.month, 'lab'::text, 'lab'::text, null::bigint, c.branch_id, c.amount
  from public.lab_order_costs c
  where c.organization_id = org_id and c.month >= from_month and c.month < to_month and c.amount <> 0;

  -- Payroll: doctors' variable pay (cost of sales), the staff and the
  -- doctors' fixed salaries (operating)
  return query
  select m.month::date,
    case when l.doctor_id is not null and l.source <> 'fixed' then 'doctors' else 'staff' end,
    'payroll'::text, null::bigint, d.branch_id, l.accrued
  from generate_series(from_month::timestamp, (to_month - 1)::timestamp, interval '1 month') m(month)
    cross join lateral private.payroll_month_lines(org_id, m.month::date) l
    left join public.doctors d on d.organization_id = org_id and d.id = l.doctor_id
  where l.accrued <> 0;
  return query
  select a.month, case when a.doctor_id is not null then 'doctors' else 'staff' end, 'payroll'::text, null::bigint,
    d.branch_id, case when a.kind = 'bonus' then a.amount else - a.amount end
  from public.payroll_adjustments a
    left join public.doctors d on d.organization_id = org_id and d.id = a.doctor_id
  where a.organization_id = org_id and a.kind in ('bonus', 'penalty') and a.month >= from_month and a.month < to_month;

  -- Advertising (stage 32), spread over its days
  return query
  select m.month::date, 'marketing'::text, 'ad_spend'::text, null::bigint, null::bigint,
    round(s.amount * (least(s.spent_to + 1, (m.month + interval '1 month')::date) - greatest(s.spent_from, m.month::date))::numeric
      / (s.spent_to + 1 - s.spent_from))::bigint
  from public.ad_spend s
    cross join lateral generate_series(date_trunc('month', greatest(s.spent_from, from_month)::timestamp),
      date_trunc('month', least(s.spent_to, to_month - 1)::timestamp), interval '1 month') m(month)
  where s.organization_id = org_id and s.spent_to >= from_month and s.spent_from < to_month and s.amount > 0;

  -- Payments on articles of cash-basis lines (by the day they were paid)
  return query
  select date_trunc('month', mv.day)::date, ar.pnl_line, 'cash'::text, ar.id, mv.branch_id,
    case when ar.pnl_line = 'other_income' then mv.amount else - mv.amount end
  from private.finance_movements(org_id, from_month, to_month) mv
    join public.finance_articles ar on ar.organization_id = org_id and ar.id = mv.article_id
  where not mv.transfer and ar.pnl_line in ('other_income', 'marketing', 'opex', 'interest', 'depreciation', 'tax');

  -- Accruals («начисление»)
  return query
  select date_trunc('month', t.occurred_on)::date, ar.pnl_line, 'manual'::text, ar.id, t.branch_id, t.amount
  from public.finance_transactions t
    join public.finance_articles ar on ar.organization_id = org_id and ar.id = t.article_id
  where t.organization_id = org_id and t.kind = 'accrual' and ar.pnl_line is not null
    and t.occurred_on >= from_month and t.occurred_on < to_month;
end;
$$;

-- A rounded share in percent (one decimal), null without a base
CREATE OR REPLACE FUNCTION "private"."finance_share"("part" numeric, "whole" numeric) RETURNS numeric
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select case when whole is null or whole = 0 then null else round(part * 100 / whole, 1) end;
$$;

-- a / b rounded, null when b is 0
CREATE OR REPLACE FUNCTION "private"."finance_ratio"("a" numeric, "b" numeric) RETURNS bigint
    LANGUAGE "sql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
  select case when b is null or b = 0 then null else round(a / b)::bigint end;
$$;

-- The P&L of a clinic (no rights check: public.report_pnl and the model)
CREATE OR REPLACE FUNCTION "private"."finance_pnl"("org_id" bigint, "from_month" "date", "to_month" "date", "filter_branch_id" bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  tz text := coalesce((select nullif(o.timezone, '') from public.organizations o where o.id = org_id), 'Asia/Almaty');
  chair_count bigint;
  result jsonb;
begin
  select count(*) into chair_count from public.chairs c
  where c.organization_id = org_id and c.is_active and (filter_branch_id is null or c.branch_id = filter_branch_id);

  with facts as (
    select * from private.finance_pnl_facts(org_id, from_month, to_month) f
    where filter_branch_id is null or f.branch_id = filter_branch_id
  ),
  months as (
    select g::date as month from generate_series(from_month::timestamp, (to_month - 1)::timestamp, interval '1 month') g
  ),
  fact_rows as (
    select f.month, f.line, f.source, f.article_id, sum(f.amount)::bigint as amount
    from facts f group by f.month, f.line, f.source, f.article_id
  ),
  visits as (
    select date_trunc('month', v.starts_at at time zone tz)::date as month, count(*)::bigint as visits
    from public.visits v
    where v.organization_id = org_id and v.status = 'completed'
      and v.starts_at >= from_month::timestamp at time zone tz and v.starts_at < to_month::timestamp at time zone tz
      and (filter_branch_id is null or v.branch_id = filter_branch_id)
    group by 1
  ),
  lines as (
    select m.month,
      coalesce(sum(f.amount) filter (where f.line = 'revenue'), 0) - coalesce(sum(f.amount) filter (where f.line = 'refunds'), 0) as revenue,
      coalesce(sum(f.amount) filter (where f.line = 'refunds'), 0) as refunds,
      coalesce(sum(f.amount) filter (where f.line = 'revenue' and f.source = 'services'), 0)
        - coalesce(sum(f.amount) filter (where f.line = 'refunds'), 0) as services,
      coalesce(sum(f.amount) filter (where f.line = 'materials'), 0) as materials,
      coalesce(sum(f.amount) filter (where f.line = 'lab'), 0) as lab,
      coalesce(sum(f.amount) filter (where f.line = 'doctors'), 0) as doctors,
      coalesce(sum(f.amount) filter (where f.line = 'staff'), 0) as staff,
      coalesce(sum(f.amount) filter (where f.line = 'marketing'), 0) as marketing,
      coalesce(sum(f.amount) filter (where f.line = 'opex'), 0) as opex_other,
      coalesce(sum(f.amount) filter (where f.line = 'other_income'), 0) as other_income,
      coalesce(sum(f.amount) filter (where f.line = 'interest'), 0) as interest,
      coalesce(sum(f.amount) filter (where f.line = 'depreciation'), 0) as depreciation,
      coalesce(sum(f.amount) filter (where f.line = 'tax'), 0) as tax,
      coalesce(max(v.visits), 0) as visits
    from months m
      left join facts f on f.month = m.month
      left join visits v on v.month = m.month
    group by m.month
  ),
  summary as (
    select l.*,
      l.materials + l.lab + l.doctors as cogs,
      l.revenue - (l.materials + l.lab + l.doctors) as gross,
      l.staff + l.marketing + l.opex_other as opex,
      l.revenue - (l.materials + l.lab + l.doctors) - (l.staff + l.marketing + l.opex_other) + l.other_income as ebitda
    from lines l
  ),
  total as (
    select sum(s.revenue) as revenue, sum(s.refunds) as refunds, sum(s.services) as services, sum(s.materials) as materials, sum(s.lab) as lab,
      sum(s.doctors) as doctors, sum(s.staff) as staff, sum(s.marketing) as marketing, sum(s.opex_other) as opex_other,
      sum(s.other_income) as other_income, sum(s.interest) as interest, sum(s.depreciation) as depreciation,
      sum(s.tax) as tax, sum(s.visits) as visits, sum(s.cogs) as cogs, sum(s.gross) as gross, sum(s.opex) as opex,
      sum(s.ebitda) as ebitda, count(*) as months
    from summary s
  )
  select jsonb_build_object(
    'from', from_month,
    'to', to_month,
    'chairs', chair_count,
    'months', (select jsonb_agg(m.month order by m.month) from months m),
    'rows', coalesce((select jsonb_agg(jsonb_build_object('month', r.month, 'line', r.line, 'source', r.source,
      'article_id', r.article_id, 'amount', r.amount) order by r.month, r.line, r.source, r.article_id) from fact_rows r), '[]'::jsonb),
    'summary', (select jsonb_agg(jsonb_build_object(
        'month', s.month, 'revenue', s.revenue, 'refunds', s.refunds, 'materials', s.materials, 'lab', s.lab,
        'doctors', s.doctors, 'staff', s.staff, 'marketing', s.marketing, 'opex_other', s.opex_other,
        'other_income', s.other_income, 'interest', s.interest, 'depreciation', s.depreciation, 'tax', s.tax,
        'cogs', s.cogs, 'gross', s.gross, 'opex', s.opex, 'ebitda', s.ebitda,
        'net', s.ebitda - s.interest - s.depreciation - s.tax,
        'gross_margin', private.finance_share(s.gross, s.revenue),
        'net_margin', private.finance_share(s.ebitda - s.interest - s.depreciation - s.tax, s.revenue),
        'visits', s.visits,
        'avg_check', private.finance_ratio(s.services, s.visits),
        'revenue_per_chair', private.finance_ratio(s.revenue, chair_count),
        'lab_share', private.finance_share(s.lab, s.revenue),
        'payroll_share', private.finance_share(s.doctors + s.staff, s.revenue)
      ) order by s.month) from summary s),
    'total', (select jsonb_build_object(
        'revenue', t.revenue, 'refunds', t.refunds, 'materials', t.materials, 'lab', t.lab, 'doctors', t.doctors,
        'staff', t.staff, 'marketing', t.marketing, 'opex_other', t.opex_other, 'other_income', t.other_income,
        'interest', t.interest, 'depreciation', t.depreciation, 'tax', t.tax, 'cogs', t.cogs, 'gross', t.gross,
        'opex', t.opex, 'ebitda', t.ebitda, 'net', t.ebitda - t.interest - t.depreciation - t.tax,
        'gross_margin', private.finance_share(t.gross, t.revenue),
        'net_margin', private.finance_share(t.ebitda - t.interest - t.depreciation - t.tax, t.revenue),
        'visits', t.visits,
        'avg_check', private.finance_ratio(t.services, t.visits),
        'revenue_per_chair', private.finance_ratio(t.revenue, chair_count * t.months),
        'lab_share', private.finance_share(t.lab, t.revenue),
        'payroll_share', private.finance_share(t.doctors + t.staff, t.revenue)
      ) from total t)
  ) into result;
  return result;
end;
$$;

-- «ПиУ»: the P&L by month between two months (from included, to excluded;
-- any day of a month means that month). The owner and the head.
CREATE OR REPLACE FUNCTION "public"."report_pnl"("period_from" "date", "period_to" "date", "filter_branch_id" bigint DEFAULT NULL::bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  from_month date := date_trunc('month', period_from)::date;
  to_month date := date_trunc('month', period_to)::date;
begin
  if not private.finance_can_edit() then
    raise exception 'ПиУ видят только владелец и руководитель' using errcode = 'insufficient_privilege', hint = 'finance_forbidden';
  end if;
  if period_from is null or period_to is null or to_month <= from_month then
    raise exception 'Укажите период' using errcode = '22023', hint = 'finance_period';
  end if;
  if to_month > (from_month + interval '36 months')::date then
    raise exception 'Не больше 36 месяцев' using errcode = '22023', hint = 'finance_period';
  end if;
  return private.finance_pnl(private.current_organization_id(), from_month, to_month, filter_branch_id);
end;
$$;

-- The plan of a model for a scenario (base, optimistic, pessimistic):
-- visits = round(chairs × days × hours × visits per chair-hour ×
-- utilization % × factor), revenue = visits × average check; the lines
-- (fixed, % of revenue) by their P&L line; break-even; the cash plan and
-- the payback of the investment. Twin: computeModel() in financeMath.ts
CREATE OR REPLACE FUNCTION "private"."finance_model_plan"("target_model_id" bigint, "scenario" "text") RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  model public.finance_models;
  mm public.finance_model_months;
  factor numeric;
  i integer;
  chairs numeric; days numeric; hours numeric; util numeric; vpch numeric; check_amount bigint;
  capacity numeric;
  visits bigint;
  revenue bigint;
  rec record;
  line_amount bigint;
  sums jsonb;
  fixed_total bigint;
  percent_total numeric;
  be_revenue bigint;
  cogs bigint; gross bigint; opex bigint; ebitda bigint; net bigint; cash_flow bigint;
  cash bigint;
  payback_cum bigint := 0;
  payback integer;
  after_count integer := 0;
  after_sum bigint := 0;
  months jsonb := '[]'::jsonb;
  line_values jsonb;
  totals jsonb := '{}'::jsonb;
  key text;
begin
  select * into model from public.finance_models m where m.id = target_model_id;
  if not found then
    return null;
  end if;
  factor := case scenario when 'optimistic' then model.optimistic_factor when 'pessimistic' then model.pessimistic_factor else 1 end;
  cash := model.opening_cash;
  for i in 0..11 loop
    select * into mm from public.finance_model_months x where x.model_id = model.id and x.month_index = i;
    chairs := coalesce(mm.chairs, model.chairs);
    days := coalesce(mm.working_days, model.working_days);
    hours := coalesce(mm.hours_per_day, model.hours_per_day);
    util := coalesce(mm.utilization, model.utilization);
    vpch := coalesce(mm.visits_per_chair_hour, model.visits_per_chair_hour);
    check_amount := coalesce(mm.avg_check, model.avg_check);
    capacity := chairs * days * hours * vpch;
    visits := round(capacity * util * factor / 100)::bigint;
    revenue := visits * check_amount;
    sums := jsonb_build_object('materials', 0, 'lab', 0, 'doctors', 0, 'staff', 0, 'marketing', 0, 'opex', 0,
      'interest', 0, 'depreciation', 0, 'tax', 0);
    line_values := '[]'::jsonb;
    fixed_total := 0;
    percent_total := 0;
    for rec in
      select l.* from public.finance_model_lines l
      where l.model_id = model.id and i between l.from_index and l.to_index
      order by l.position, l.id
    loop
      if rec.kind = 'percent' then
        line_amount := private.payroll_mul_div(revenue, rec.percent, 100);
        percent_total := percent_total + rec.percent;
      else
        line_amount := rec.amount;
        fixed_total := fixed_total + rec.amount;
      end if;
      sums := sums || jsonb_build_object(rec.pnl_line, (sums ->> rec.pnl_line)::bigint + line_amount);
      line_values := line_values || jsonb_build_array(jsonb_build_object('line_id', rec.id, 'amount', line_amount));
    end loop;
    cogs := (sums ->> 'materials')::bigint + (sums ->> 'lab')::bigint + (sums ->> 'doctors')::bigint;
    gross := revenue - cogs;
    opex := (sums ->> 'staff')::bigint + (sums ->> 'marketing')::bigint + (sums ->> 'opex')::bigint;
    ebitda := gross - opex;
    net := ebitda - (sums ->> 'interest')::bigint - (sums ->> 'depreciation')::bigint - (sums ->> 'tax')::bigint;
    cash_flow := net + (sums ->> 'depreciation')::bigint - case when i = model.investment_month then model.investment_amount else 0 end;
    cash := cash + cash_flow;
    be_revenue := case when percent_total < 100 then ceil(fixed_total * 100 / (100 - percent_total))::bigint end;
    if model.investment_amount > 0 and i >= model.investment_month then
      payback_cum := payback_cum + net + (sums ->> 'depreciation')::bigint;
      after_count := after_count + 1;
      after_sum := after_sum + net + (sums ->> 'depreciation')::bigint;
      if payback is null and payback_cum >= model.investment_amount then
        payback := i - model.investment_month + 1;
      end if;
    end if;
    months := months || jsonb_build_array(jsonb_build_object(
      'index', i,
      'month', (model.start_month + make_interval(months => i))::date,
      'chairs', chairs, 'working_days', days, 'hours_per_day', hours, 'utilization', util,
      'visits_per_chair_hour', vpch, 'avg_check', check_amount,
      'visits', visits, 'revenue', revenue,
      'materials', (sums ->> 'materials')::bigint, 'lab', (sums ->> 'lab')::bigint, 'doctors', (sums ->> 'doctors')::bigint,
      'staff', (sums ->> 'staff')::bigint, 'marketing', (sums ->> 'marketing')::bigint, 'opex_other', (sums ->> 'opex')::bigint,
      'interest', (sums ->> 'interest')::bigint, 'depreciation', (sums ->> 'depreciation')::bigint, 'tax', (sums ->> 'tax')::bigint,
      'cogs', cogs, 'gross', gross, 'opex', opex, 'ebitda', ebitda, 'net', net,
      'cash_flow', cash_flow, 'cash', cash,
      'fixed_costs', fixed_total, 'variable_percent', percent_total,
      'break_even_revenue', be_revenue,
      'break_even_utilization', case when be_revenue is not null and capacity * check_amount > 0
        then round(be_revenue * 100 / (capacity * check_amount), 1) end,
      'lines', line_values));
    foreach key in array array['visits', 'revenue', 'materials', 'lab', 'doctors', 'staff', 'marketing', 'opex_other',
      'interest', 'depreciation', 'tax', 'cogs', 'gross', 'opex', 'ebitda', 'net', 'cash_flow'] loop
      totals := totals || jsonb_build_object(key, coalesce((totals ->> key)::bigint, 0) + (months -> i ->> key)::bigint);
    end loop;
  end loop;
  return jsonb_build_object(
    'model_id', model.id,
    'scenario', coalesce(scenario, 'base'),
    'factor', factor,
    'start_month', model.start_month,
    'months', months,
    'total', totals || jsonb_build_object('closing_cash', cash,
      'gross_margin', private.finance_share((totals ->> 'gross')::numeric, (totals ->> 'revenue')::numeric),
      'net_margin', private.finance_share((totals ->> 'net')::numeric, (totals ->> 'revenue')::numeric)),
    'investment', model.investment_amount,
    'payback_months', case
      when model.investment_amount = 0 then null
      when payback is not null then payback
      when after_count > 0 and after_sum > 0 then
        after_count + ceil((model.investment_amount - payback_cum)::numeric * after_count / after_sum)::integer
    end,
    'payback_in_horizon', payback is not null);
end;
$$;

-- «Финмодель»: the plan of a model for a scenario, and plan vs fact (the
-- P&L of the whole clinic) for its months up to the current one. The owner
-- and the head.
CREATE OR REPLACE FUNCTION "public"."report_finance_model"("target_model_id" bigint, "scenario" "text" DEFAULT 'base'::"text") RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  org_id bigint := private.current_organization_id();
  model public.finance_models;
  plan jsonb;
  current_month date;
  fact_to date;
  fact jsonb;
begin
  if not private.finance_can_edit() then
    raise exception 'Финмодель видят только владелец и руководитель' using errcode = 'insufficient_privilege', hint = 'finance_forbidden';
  end if;
  if coalesce(scenario, 'base') not in ('base', 'optimistic', 'pessimistic') then
    raise exception 'Сценарий: базовый, оптимистичный или пессимистичный' using errcode = '22023', hint = 'finance_scenario';
  end if;
  select * into model from public.finance_models m where m.organization_id = org_id and m.id = target_model_id;
  if not found then
    raise exception 'Модель не найдена' using errcode = 'P0002';
  end if;
  plan := private.finance_model_plan(model.id, coalesce(scenario, 'base'));
  current_month := date_trunc('month', private.clinic_date(org_id, now()))::date;
  fact_to := least((current_month + interval '1 month')::date, (model.start_month + interval '12 months')::date);
  if fact_to > model.start_month then
    fact := private.finance_pnl(org_id, model.start_month, fact_to, null);
  end if;
  return plan || jsonb_build_object(
    'current_month', current_month,
    'fact', coalesce((
      select jsonb_agg(jsonb_build_object(
        'month', s ->> 'month',
        'revenue', (s ->> 'revenue')::bigint,
        'gross', (s ->> 'gross')::bigint,
        'ebitda', (s ->> 'ebitda')::bigint,
        'net', (s ->> 'net')::bigint,
        'visits', (s ->> 'visits')::bigint,
        'revenue_delta', (s ->> 'revenue')::bigint - (p ->> 'revenue')::bigint,
        'net_delta', (s ->> 'net')::bigint - (p ->> 'net')::bigint,
        'revenue_percent', private.finance_share((s ->> 'revenue')::numeric, (p ->> 'revenue')::numeric),
        'partial', (s ->> 'month')::date = current_month
      ) order by s ->> 'month')
      from jsonb_array_elements(fact -> 'summary') s
        join jsonb_array_elements(plan -> 'months') p on p ->> 'month' = s ->> 'month'
    ), '[]'::jsonb));
end;
$$;

-- An account: a system one keeps its code and is not deleted
CREATE OR REPLACE FUNCTION "private"."handle_finance_account_before_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if tg_op = 'DELETE' then
    if old.code is not null and pg_trigger_depth() = 1
      and exists (select 1 from public.organizations o where o.id = old.organization_id) then
      raise exception 'Системный счёт нельзя удалить — только переименовать или убрать в архив'
        using errcode = '22023', hint = 'finance_system';
    end if;
    return old;
  end if;
  if tg_op = 'INSERT' then
    if pg_trigger_depth() = 1 and private.current_user_role() is not null then
      new.code := null;
    end if;
  elsif new.code is distinct from old.code then
    raise exception 'Код системного счёта не меняется' using errcode = '22023', hint = 'finance_system';
  end if;
  new.name := btrim(new.name);
  return new;
end;
$$;

-- An article: a system one keeps its code, section, activity and line and
-- is not deleted
CREATE OR REPLACE FUNCTION "private"."handle_finance_article_before_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if tg_op = 'DELETE' then
    if old.code is not null and pg_trigger_depth() = 1
      and exists (select 1 from public.organizations o where o.id = old.organization_id) then
      raise exception 'Системную статью нельзя удалить — только переименовать или убрать в архив'
        using errcode = '22023', hint = 'finance_system';
    end if;
    return old;
  end if;
  if tg_op = 'INSERT' then
    if pg_trigger_depth() = 1 and private.current_user_role() is not null then
      new.code := null;
    end if;
  elsif new.code is distinct from old.code
    or (old.code is not null and (new.section <> old.section or new.activity <> old.activity
      or new.pnl_line is distinct from old.pnl_line)) then
    raise exception 'У системной статьи меняются только название и архив' using errcode = '22023', hint = 'finance_system';
  end if;
  new.name := btrim(new.name);
  return new;
end;
$$;

-- A transaction: the article fits its kind (in / out by section, accrual:
-- an article of the P&L); a linked one (payout, lab payment) keeps its
-- amount, day and kind — they change on the payroll or lab side
CREATE OR REPLACE FUNCTION "private"."handle_finance_transaction_before_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  article public.finance_articles;
  syncing boolean := coalesce(current_setting('crm.finance_sync', true), '') = 'on';
begin
  if tg_op = 'DELETE' then
    if not syncing and pg_trigger_depth() = 1 and (old.payroll_adjustment_id is not null or old.lab_payment_id is not null)
      and exists (select 1 from public.organizations o where o.id = old.organization_id) then
      raise exception 'Это выплата зарплаты или оплата лаборатории: удалите её в разделе «Зарплаты» или «Лаборатория»'
        using errcode = '22023', hint = 'finance_linked';
    end if;
    return old;
  end if;
  if tg_op = 'INSERT' then
    if not syncing and (new.payroll_adjustment_id is not null or new.lab_payment_id is not null) then
      raise exception 'Связь с выплатой задаёт только система' using errcode = '22023', hint = 'finance_linked';
    end if;
    if pg_trigger_depth() = 1 and private.current_user_role() is not null then
      new.created_by := private.current_sales_id();
      new.created_at := now();
    end if;
  elsif not syncing then
    if new.payroll_adjustment_id is distinct from old.payroll_adjustment_id or new.lab_payment_id is distinct from old.lab_payment_id then
      raise exception 'Связь с выплатой не меняется' using errcode = '22023', hint = 'finance_linked';
    end if;
    if (old.payroll_adjustment_id is not null or old.lab_payment_id is not null)
      and (new.amount <> old.amount or new.occurred_on <> old.occurred_on or new.kind <> old.kind) then
      raise exception 'Сумму и дату выплаты меняют в разделе «Зарплаты» или «Лаборатория»'
        using errcode = '22023', hint = 'finance_linked';
    end if;
  end if;
  new.counterparty := nullif(btrim(new.counterparty), '');
  new.comment := nullif(btrim(new.comment), '');
  if new.article_id is not null then
    select * into article from public.finance_articles a
    where a.organization_id = new.organization_id and a.id = new.article_id;
    if not found then
      raise exception 'Статья не найдена' using errcode = '22023', hint = 'finance_article';
    end if;
    if new.kind = 'in' and article.section <> 'in' then
      raise exception 'Поступление — по статье поступлений' using errcode = '22023', hint = 'finance_article';
    end if;
    if new.kind = 'out' and article.section <> 'out' then
      raise exception 'Выплата — по статье выплат' using errcode = '22023', hint = 'finance_article';
    end if;
    if new.kind = 'accrual' and article.pnl_line is null then
      raise exception 'Начисление — по статье, которая входит в ПиУ' using errcode = '22023', hint = 'finance_article';
    end if;
    if not article.is_active and not syncing and (tg_op = 'INSERT' or new.article_id is distinct from old.article_id) then
      raise exception 'Статья в архиве' using errcode = '22023', hint = 'finance_article';
    end if;
  end if;
  return new;
end;
$$;

-- A payroll payout paid without the cash desk: its linked transaction
-- («Зарплата врачей» / «Зарплата персонала», the bank account of the
-- method bank_transfer) follows its amount and day
CREATE OR REPLACE FUNCTION "private"."handle_finance_payout_sync"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  person text;
begin
  if tg_op = 'DELETE' then
    return null;
  end if;
  perform set_config('crm.finance_sync', 'on', true);
  if new.kind <> 'payout' or new.account_operation_id is not null then
    delete from public.finance_transactions t
    where t.organization_id = new.organization_id and t.payroll_adjustment_id = new.id;
  elsif exists (select 1 from public.finance_transactions t
      where t.organization_id = new.organization_id and t.payroll_adjustment_id = new.id) then
    update public.finance_transactions t
    set amount = new.amount, occurred_on = new.occurred_on
    where t.organization_id = new.organization_id and t.payroll_adjustment_id = new.id
      and (t.amount <> new.amount or t.occurred_on <> new.occurred_on);
  else
    if new.doctor_id is not null then
      select d.name into person from public.doctors d where d.organization_id = new.organization_id and d.id = new.doctor_id;
    else
      select nullif(btrim(concat_ws(' ', s.first_name, s.last_name)), '') into person
      from public.sales s where s.organization_id = new.organization_id and s.id = new.sales_id;
    end if;
    insert into public.finance_transactions (organization_id, kind, occurred_on, account_id, article_id, amount,
      counterparty, comment, payroll_adjustment_id, created_by)
    select new.organization_id, 'out', new.occurred_on, a.account_id,
      private.finance_article_id(new.organization_id, case when new.doctor_id is not null then 'salary_doctors' else 'salary_staff' end),
      new.amount, left(person, 200),
      left(concat_ws(' — ', 'Зарплата за ' || to_char(new.month, 'MM.YYYY'), new.note), 1000), new.id, new.created_by
    from (select private.finance_method_account(new.organization_id, 'bank_transfer') as account_id) a
    where a.account_id is not null
      and private.finance_article_id(new.organization_id, 'salary_staff') is not null;
  end if;
  perform set_config('crm.finance_sync', '', true);
  return null;
end;
$$;

-- A lab payment paid without the cash desk: its linked transaction
-- («Лаборатория», the account of its method) follows its amount, day and
-- method
CREATE OR REPLACE FUNCTION "private"."handle_finance_lab_payment_sync"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  lab_name text;
  day date;
begin
  if tg_op = 'DELETE' then
    return null;
  end if;
  perform set_config('crm.finance_sync', 'on', true);
  day := private.clinic_date(new.organization_id, new.paid_at);
  if new.account_operation_id is not null then
    delete from public.finance_transactions t
    where t.organization_id = new.organization_id and t.lab_payment_id = new.id;
  elsif exists (select 1 from public.finance_transactions t
      where t.organization_id = new.organization_id and t.lab_payment_id = new.id) then
    update public.finance_transactions t
    set amount = new.amount, occurred_on = day,
      account_id = case when tg_op = 'UPDATE' and new.method <> old.method
        then coalesce(private.finance_method_account(new.organization_id, new.method), t.account_id) else t.account_id end
    where t.organization_id = new.organization_id and t.lab_payment_id = new.id;
  else
    select l.name into lab_name from public.labs l where l.organization_id = new.organization_id and l.id = new.lab_id;
    insert into public.finance_transactions (organization_id, kind, occurred_on, account_id, article_id, amount,
      counterparty, comment, lab_payment_id, created_by)
    select new.organization_id, 'out', day, a.account_id, private.finance_article_id(new.organization_id, 'lab'),
      new.amount, left(lab_name, 200),
      left(concat_ws(' — ', 'Лаборатория за ' || to_char(new.month, 'MM.YYYY'), new.comment), 1000), new.id, new.created_by
    from (select coalesce(private.finance_method_account(new.organization_id, new.method),
      private.finance_method_account(new.organization_id, 'bank_transfer')) as account_id) a
    where a.account_id is not null and private.finance_article_id(new.organization_id, 'lab') is not null;
  end if;
  perform set_config('crm.finance_sync', '', true);
  return null;
end;
$$;

-- A model changed: its time
CREATE OR REPLACE FUNCTION "private"."handle_finance_model_before_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  new.name := btrim(new.name);
  new.start_month := date_trunc('month', new.start_month)::date;
  new.updated_at := now();
  if tg_op = 'INSERT' and pg_trigger_depth() = 1 and private.current_user_role() is not null then
    new.created_by := private.current_sales_id();
  end if;
  return new;
end;
$$;

--
-- Triggers
--

-- After seed_cash_expense_categories (alphabetically): the categories exist
create or replace trigger seed_finance
    after insert on public.organizations
    for each row execute function private.handle_organization_finance();

create or replace trigger finance_account_before_write
    before insert or update or delete on public.finance_accounts
    for each row execute function private.handle_finance_account_before_write();

create or replace trigger finance_article_before_write
    before insert or update or delete on public.finance_articles
    for each row execute function private.handle_finance_article_before_write();

create or replace trigger finance_transaction_before_write
    before insert or update or delete on public.finance_transactions
    for each row execute function private.handle_finance_transaction_before_write();

create or replace trigger finance_payout_sync
    after insert or update on public.payroll_adjustments
    for each row execute function private.handle_finance_payout_sync();

create or replace trigger finance_lab_payment_sync
    after insert or update on public.lab_payments
    for each row execute function private.handle_finance_lab_payment_sync();

create or replace trigger finance_model_before_write
    before insert or update on public.finance_models
    for each row execute function private.handle_finance_model_before_write();

create or replace trigger audit_finance_account
    after insert or update or delete on public.finance_accounts
    for each row when (pg_trigger_depth() = 0) execute function private.audit_row('finance_account', 'name,kind,opening_balance,opening_date,is_active');

create or replace trigger audit_finance_article
    after insert or update or delete on public.finance_articles
    for each row when (pg_trigger_depth() = 0) execute function private.audit_row('finance_article', 'name,section,activity,pnl_line,is_active');

create or replace trigger audit_finance_transaction
    after insert or update or delete on public.finance_transactions
    for each row when (pg_trigger_depth() = 0) execute function private.audit_row('finance_transaction', 'kind,occurred_on,account_id,to_account_id,article_id,amount,counterparty,comment,branch_id');

create or replace trigger audit_finance_model
    after insert or update or delete on public.finance_models
    for each row when (pg_trigger_depth() = 0) execute function private.audit_row('finance_model', 'name,start_month,chairs,working_days,hours_per_day,utilization,visits_per_chair_hour,avg_check,investment_amount');

--
-- Row Level Security
--

alter table public.finance_accounts enable row level security;
alter table public.finance_articles enable row level security;
alter table public.finance_method_accounts enable row level security;
alter table public.finance_transactions enable row level security;
alter table public.finance_models enable row level security;
alter table public.finance_model_months enable row level security;
alter table public.finance_model_lines enable row level security;

create policy "Finance readers read accounts" on public.finance_accounts for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_view()));
create policy "Owner and head add accounts" on public.finance_accounts for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()));
create policy "Owner and head change accounts" on public.finance_accounts for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head delete accounts" on public.finance_accounts for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()));

create policy "Finance readers read articles" on public.finance_articles for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_view()));
create policy "Owner and head add articles" on public.finance_articles for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()));
create policy "Owner and head change articles" on public.finance_articles for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head delete articles" on public.finance_articles for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()));

create policy "Finance readers read the method map" on public.finance_method_accounts for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_view()));
create policy "Owner and head change the method map" on public.finance_method_accounts for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()))
    with check (organization_id = (select private.current_organization_id()));

create policy "Finance readers read transactions" on public.finance_transactions for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_view()));
create policy "Owner and head add transactions" on public.finance_transactions for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()));
create policy "Owner and head change transactions" on public.finance_transactions for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head delete transactions" on public.finance_transactions for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()));

create policy "Owner and head read models" on public.finance_models for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()));
create policy "Owner and head add models" on public.finance_models for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()));
create policy "Owner and head change models" on public.finance_models for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head delete models" on public.finance_models for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()));

create policy "Owner and head read model months" on public.finance_model_months for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()));
create policy "Owner and head add model months" on public.finance_model_months for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()));
create policy "Owner and head change model months" on public.finance_model_months for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head delete model months" on public.finance_model_months for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()));

create policy "Owner and head read model lines" on public.finance_model_lines for select to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()));
create policy "Owner and head add model lines" on public.finance_model_lines for insert to authenticated
    with check (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()));
create policy "Owner and head change model lines" on public.finance_model_lines for update to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()))
    with check (organization_id = (select private.current_organization_id()));
create policy "Owner and head delete model lines" on public.finance_model_lines for delete to authenticated
    using (organization_id = (select private.current_organization_id()) and (select private.finance_can_edit()));

--
-- Grants
--

-- The article of an expense category
grant update (article_id) on table public.cash_expense_categories to authenticated;

revoke all on table public.finance_accounts from anon;
grant select, insert, delete on table public.finance_accounts to authenticated;
grant update (name, kind, opening_balance, opening_date, is_active, position) on table public.finance_accounts to authenticated;
grant all on table public.finance_accounts to service_role;
revoke all on sequence public.finance_accounts_id_seq from anon;
grant usage on sequence public.finance_accounts_id_seq to authenticated;
grant all on sequence public.finance_accounts_id_seq to service_role;

revoke all on table public.finance_articles from anon;
grant select, insert, delete on table public.finance_articles to authenticated;
grant update (name, section, activity, pnl_line, is_active, position) on table public.finance_articles to authenticated;
grant all on table public.finance_articles to service_role;
revoke all on sequence public.finance_articles_id_seq from anon;
grant usage on sequence public.finance_articles_id_seq to authenticated;
grant all on sequence public.finance_articles_id_seq to service_role;

revoke all on table public.finance_method_accounts from anon;
grant select on table public.finance_method_accounts to authenticated;
grant update (account_id) on table public.finance_method_accounts to authenticated;
grant all on table public.finance_method_accounts to service_role;

revoke all on table public.finance_transactions from anon;
grant select, insert, delete on table public.finance_transactions to authenticated;
grant update (kind, occurred_on, account_id, to_account_id, article_id, amount, counterparty, comment, branch_id) on table public.finance_transactions to authenticated;
grant all on table public.finance_transactions to service_role;
revoke all on sequence public.finance_transactions_id_seq from anon;
grant usage on sequence public.finance_transactions_id_seq to authenticated;
grant all on sequence public.finance_transactions_id_seq to service_role;

revoke all on table public.finance_models from anon;
grant select, insert, delete on table public.finance_models to authenticated;
grant update (name, start_month, chairs, working_days, hours_per_day, utilization, visits_per_chair_hour, avg_check,
    optimistic_factor, pessimistic_factor, opening_cash, investment_amount, investment_month, note) on table public.finance_models to authenticated;
grant all on table public.finance_models to service_role;
revoke all on sequence public.finance_models_id_seq from anon;
grant usage on sequence public.finance_models_id_seq to authenticated;
grant all on sequence public.finance_models_id_seq to service_role;

revoke all on table public.finance_model_months from anon;
grant select, insert, delete on table public.finance_model_months to authenticated;
grant update (chairs, working_days, hours_per_day, utilization, visits_per_chair_hour, avg_check) on table public.finance_model_months to authenticated;
grant all on table public.finance_model_months to service_role;
revoke all on sequence public.finance_model_months_id_seq from anon;
grant usage on sequence public.finance_model_months_id_seq to authenticated;
grant all on sequence public.finance_model_months_id_seq to service_role;

revoke all on table public.finance_model_lines from anon;
grant select, insert, delete on table public.finance_model_lines to authenticated;
grant update (name, article_id, pnl_line, kind, amount, percent, from_index, to_index, position) on table public.finance_model_lines to authenticated;
grant all on table public.finance_model_lines to service_role;
revoke all on sequence public.finance_model_lines_id_seq from anon;
grant usage on sequence public.finance_model_lines_id_seq to authenticated;
grant all on sequence public.finance_model_lines_id_seq to service_role;

revoke all on function private.seed_finance(bigint) from public;
grant execute on function private.seed_finance(bigint) to service_role;
revoke all on function private.handle_organization_finance() from public;
revoke all on function private.finance_article_id(bigint, text) from public;
grant execute on function private.finance_article_id(bigint, text) to service_role;
revoke all on function private.finance_method_account(bigint, text) from public;
grant execute on function private.finance_method_account(bigint, text) to service_role;
revoke all on function private.finance_can_view() from public;
grant execute on function private.finance_can_view() to authenticated, service_role;
revoke all on function private.finance_can_edit() from public;
grant execute on function private.finance_can_edit() to authenticated, service_role;
revoke all on function private.finance_movements(bigint, date, date) from public;
grant execute on function private.finance_movements(bigint, date, date) to service_role;
revoke all on function private.finance_revenue_items(bigint, timestamp with time zone, timestamp with time zone) from public;
grant execute on function private.finance_revenue_items(bigint, timestamp with time zone, timestamp with time zone) to service_role;
revoke all on function private.finance_pnl_facts(bigint, date, date) from public;
grant execute on function private.finance_pnl_facts(bigint, date, date) to service_role;
revoke all on function private.finance_pnl(bigint, date, date, bigint) from public;
grant execute on function private.finance_pnl(bigint, date, date, bigint) to service_role;
revoke all on function private.finance_model_plan(bigint, text) from public;
grant execute on function private.finance_model_plan(bigint, text) to service_role;
revoke all on function private.handle_finance_account_before_write() from public;
revoke all on function private.handle_finance_article_before_write() from public;
revoke all on function private.handle_finance_transaction_before_write() from public;
revoke all on function private.handle_finance_payout_sync() from public;
revoke all on function private.handle_finance_lab_payment_sync() from public;
revoke all on function private.handle_finance_model_before_write() from public;

revoke all on function public.report_cash_flow(date, date, bigint, text) from public, anon;
grant execute on function public.report_cash_flow(date, date, bigint, text) to authenticated, service_role;
revoke all on function public.report_cash_flow_movements(date, date, bigint, bigint, bigint, boolean) from public, anon;
grant execute on function public.report_cash_flow_movements(date, date, bigint, bigint, bigint, boolean) to authenticated, service_role;
revoke all on function public.report_pnl(date, date, bigint) from public, anon;
grant execute on function public.report_pnl(date, date, bigint) to authenticated, service_role;
revoke all on function public.report_finance_model(bigint, text) from public, anon;
grant execute on function public.report_finance_model(bigint, text) to authenticated, service_role;

--
-- The existing clinics: accounts, method map, articles, the articles of
-- their expense categories; the transactions of the payouts and the lab
-- payments already paid without the cash desk
--
alter table public.finance_accounts disable trigger audit_finance_account;
alter table public.finance_articles disable trigger audit_finance_article;
select private.seed_finance(o.id) from public.organizations o;
alter table public.finance_accounts enable trigger audit_finance_account;
alter table public.finance_articles enable trigger audit_finance_article;

alter table public.finance_transactions disable trigger audit_finance_transaction;
select set_config('crm.finance_sync', 'on', true);
insert into public.finance_transactions (organization_id, kind, occurred_on, account_id, article_id, amount,
  counterparty, comment, payroll_adjustment_id, created_by)
select a.organization_id, 'out', a.occurred_on, private.finance_method_account(a.organization_id, 'bank_transfer'),
  private.finance_article_id(a.organization_id, case when a.doctor_id is not null then 'salary_doctors' else 'salary_staff' end),
  a.amount,
  left(coalesce(d.name, nullif(btrim(concat_ws(' ', s.first_name, s.last_name)), '')), 200),
  left(concat_ws(' — ', 'Зарплата за ' || to_char(a.month, 'MM.YYYY'), a.note), 1000), a.id, a.created_by
from public.payroll_adjustments a
  left join public.doctors d on d.organization_id = a.organization_id and d.id = a.doctor_id
  left join public.sales s on s.organization_id = a.organization_id and s.id = a.sales_id
where a.kind = 'payout' and a.account_operation_id is null
  and private.finance_method_account(a.organization_id, 'bank_transfer') is not null;
insert into public.finance_transactions (organization_id, kind, occurred_on, account_id, article_id, amount,
  counterparty, comment, lab_payment_id, created_by)
select p.organization_id, 'out', private.clinic_date(p.organization_id, p.paid_at),
  coalesce(private.finance_method_account(p.organization_id, p.method), private.finance_method_account(p.organization_id, 'bank_transfer')),
  private.finance_article_id(p.organization_id, 'lab'), p.amount, left(l.name, 200),
  left(concat_ws(' — ', 'Лаборатория за ' || to_char(p.month, 'MM.YYYY'), p.comment), 1000), p.id, p.created_by
from public.lab_payments p
  join public.labs l on l.organization_id = p.organization_id and l.id = p.lab_id
where p.account_operation_id is null
  and private.finance_method_account(p.organization_id, 'bank_transfer') is not null;
select set_config('crm.finance_sync', '', true);
alter table public.finance_transactions enable trigger audit_finance_transaction;
